
INSERT INTO
  CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM ( MEMBER_KEY,
    MEMBERSHIP_KEY,
    CUSTOMER_MDM_KEY,
    MEMBER_NUM,
    MEMBERSHIP_NUM,
    MEMBERSHIP_LEVEL,
    MEMBERSHIP_LEVEL_DESC,
    ASSOCIATE_ID,
    STATUS_CD,
    STATUS_DESCRIPTION_CD,
    BILLING_STATUS_CD,
    MIF_ELIGIBLE_CNT,
    PREV_MEMBER_NUM,
    PREVIOUS_CLUB_CD,
    TRANSFER_IN_IND,
    COMPENSATION_EMPLOYEE_ID,
    SECONDARY_COMPENSATE_EMPLOYEE_ID,
    SELLING_LOCATION_ID,
    REVENUE_LOCATION_ID,
    EMPLOYEE_IND,
    ACTIVE_MILITARY_IND,
    EMPLOYEE_ID_OF_MEMBER,
    FREE_ASSOCIATE_IND,
    AAA_JOIN_DT,
    CLUB_JOIN_DT,
    ACTIVE_DT,
    MEMBER_SINCE,
    REINST_DT,
    INCEPTION_DT,
    TENURE_DT,
    TERM_EFFECTIVE_DT,
    TERM_EXPIRY_DT,
    CORPORATE_GROUP_TYPE,
    DO_NOT_RENEW_IND,
    DUPLICATE_CARD_REQUEST_DT,
    DUP_CARD_CNT,
    COMMISSION_CD,
    CANCEL_DT,
    REASON_JOIN_AAA_CD,
    SOLICITATION_CD,
    SOURCE_OF_SALE_CD,
    ROLE_CD,
    PAID_BY_CD,
    CARD_REQUEST_SKIPPPED_DT,
    DO_NOT_RENEW_EXPIRY_DT,
    DUPLICATE_STICKER_REQUEST_DT,
    DUPLICATE_STICKER_CNT,
    DUPLICATE_CARD_REASON,
    DO_NOT_RENEW_REASON,
    LANGUAGE,
    BILLING_CATEGORY_CD,
    MITA_PENDING,
    PREV_COMMISSION_CD,
    RENEW_CNT,
    CARD_REQT_SKIP_REASON,
    PREFERRED_CONTACT_METHOD_CD,
    REINSTATEMENT_CARD_PRINT_IND,
    SPRINT_ENROLL_DT,
    SPRN_IND,
    BOARD_MEMBER_IND,
    HONORARY_MEMBER_IND,
    COURTESY_MEMBER_IND,
    UTAH_50_YEAR_IND,
    SERVICE_PROVIDER_IND,
    VIA_MAGAZINE_PREFERRED_IND,
    ERS_USAGE_YEAR1,
    ERS_USAGE_YEAR2,
    ERS_USAGE_YEAR3,
    RESIDENTIAL_ZIP_CD,
    ROW_START_DT,
    ROW_END_DT,
    UPDATE_DTTIME,
    JOB_RUN_ID,
    SOURCE_SYSTEM_CD,
    ACTIVE_FLG,
    MD5_VALUE,
    PAID_BY_CD_DESC,
    LAPSED_IND,
    ONLINE_SIGNUP_IND)(
  SELECT
    DISTINCT MEMBER_KEY,
    SAFE_CAST(MEMBERSHIP_KEY AS INT64) AS MEMBERSHIP_KEY,
    CUSTOMER_MDM_KEY,
    MEMBER_NUM,
    MEMBERSHIP_NUM,
    MEMBERSHIP_LEVEL,
    MEMBERSHIP_LEVEL_DESC,
    ASSOCIATE_ID,
    STATUS_CD,
    STATUS_DESCRIPTION_CD,
    BILLING_STATUS_CD,
    MIF_ELIGIBLE_CNT,
    PREV_MEMBER_NUM,
    PREVIOUS_CLUB_CD,
    TRANSFER_IN_IND,
    COMPENSATION_EMPLOYEE_ID,
    SECONDARY_COMPENSATE_EMPLOYEE_ID,
    SELLING_LOCATION_ID,
    REVENUE_LOCATION_ID,
    EMPLOYEE_IND,
    ACTIVE_MILITARY_IND,
    EMPLOYEE_ID_OF_MEMBER,
    FREE_ASSOCIATE_IND,
    AAA_JOIN_DT,
    CLUB_JOIN_DT,
    ACTIVE_DT,
    MEMBER_SINCE,
    REINST_DT,
    INCEPTION_DT,
    TENURE_DT,
    TERM_EFFECTIVE_DT,
    TERM_EXPIRY_DT,
    CORPORATE_GROUP_TYPE,
    DO_NOT_RENEW_IND,
    DUPLICATE_CARD_REQUEST_DT,
    DUP_CARD_CNT,
    COMMISSION_CD,
    CANCEL_DT,
    REASON_JOIN_AAA_CD,
    SOLICITATION_CD,
    SOURCE_OF_SALE_CD,
    ROLE_CD,
    PAID_BY_CD,
    CARD_REQUEST_SKIPPPED_DT,
    DO_NOT_RENEW_EXPIRY_DT,
    DUPLICATE_STICKER_REQUEST_DT,
    DUPLICATE_STICKER_CNT,
    DUPLICATE_CARD_REASON,
    DO_NOT_RENEW_REASON,
    LANGUAGE,
    BILLING_CATEGORY_CD,
    MITA_PENDING,
    PREV_COMMISSION_CD,
    RENEW_CNT,
    CARD_REQT_SKIP_REASON,
    PREFERRED_CONTACT_METHOD_CD,
    REINSTATEMENT_CARD_PRINT_IND,
    SPRINT_ENROLL_DT,
    SPRN_IND,
    BOARD_MEMBER_IND,
    HONORARY_MEMBER_IND,
    COURTESY_MEMBER_IND,
    UTAH_50_YEAR_IND,
    SERVICE_PROVIDER_IND,
    VIA_MAGAZINE_PREFERRED_IND,
    ERS_USAGE_YEAR1,
    ERS_USAGE_YEAR2,
    ERS_USAGE_YEAR3,
    RESIDENTIAL_ZIP_CD,
    EFFECTIVE_START_DT AS ROW_START_DT,
    EFFECTIVE_END_DT ROW_END_DT,
    CURRENT_DATETIME(),
    JOB_RUN_ID,
    SOURCE_SYSTEM_CD,
    ACTIVE_FLG,
    MD5_VALUE,
    PAID_BY_CD_DESC,
    LAPSED_IND,
    ONLINE_SIGNUP_IND
  FROM (
    SELECT
      A.MEMBER_KEY,
      A.MEMBERSHIP_KEY,
      MDM.CUSTOMER_MDM_KEY,
      A.MEMBER_NUM,
      ZIP_CD,
      A.RESIDENTIAL_ZIP,
      A.MEMBERSHIP_NUM,
      A.MEMBERSHIP_LEVEL,
 
      CASE WHEN PD.PRODUCT_CD_DESC IS NULL 
 	  THEN CMD.MEMBERSHIP_LEVEL_DESC
	  ELSE PD.PRODUCT_CD_DESC
      END AS MEMBERSHIP_LEVEL_DESC, 

      A.ASSOCIATE_ID,
      A.STATUS_CD,
      CASE
        WHEN A.STATUS_CD = 'A' THEN 'ACTIVE'
        WHEN A.STATUS_CD = 'P' THEN 'PENDING'
        ELSE 'CANCELLED'
      END AS STATUS_DESCRIPTION_CD,
      A.BILLING_STATUS_CD,
      A.MIF_ELIGIBLE_CNT AS MIF_ELIGIBLE_CNT,
      A.PREV_MEMBER_NUM,
      A.PREVIOUS_CLUB_CD,
      A.TRANSFER_IN_IND,
      A.COMPENSATION_EMPLOYEE_ID,
      A.SECONDARY_COMPENSATE_EMPLOYEE_ID,
      A.SELLING_LOCATION_ID,
      LZD.LOCATION_ID AS REVENUE_LOCATION_ID,
      A.EMPLOYEE_IND,
      A.ACTIVE_MILITARY_IND,
      A.EMPLOYEE_ID_OF_MEMBER,
      A.FREE_ASSOCIATE_IND,
      A.AAA_JOIN_DT,
      A.CLUB_JOIN_DT,
      A.ACTIVE_DT,
      A.MEMBER_SINCE,
      A.REINST_DT,
      CASE WHEN  CMD.MEMBER_NUM IS NULL THEN A.INCEPTION_DT  ELSE CMD.INCEPTION_DT END AS INCEPTION_DT,
      A.TENURE_DT,
     
	  
	  
	  CASE
      WHEN CMD.MEMBER_NUM IS NULL AND DATE_DIFF(A.INCEPTION_DT, A.TERM_EXPIRY_DT, DAY) > 360 THEN A.TERM_EFFECTIVE_DT
	  WHEN CMD.MEMBER_NUM IS NULL AND A.ASSOCIATE_ID = 1 THEN A.TERM_EFFECTIVE_DT
	  WHEN CMD.MEMBER_NUM IS NULL AND A.ASSOCIATE_ID <> 1 THEN A.INCEPTION_DT
      WHEN A.STATUS_CD = 'A' AND CMD.STATUS_CD = 'P' THEN A.TERM_EFFECTIVE_DT
      WHEN A.STATUS_CD = 'A' AND CMD.STATUS_CD = 'A' AND DATE_DIFF(CMD.TERM_EXPIRY_DT, A.TERM_EXPIRY_DT, DAY) > 360 THEN A.TERM_EFFECTIVE_DT
      WHEN A.STATUS_CD = 'A' AND CMD.STATUS_CD = 'C' THEN A.REINST_DT
      ELSE CMD.TERM_EFFECTIVE_DT
    END AS TERM_EFFECTIVE_DT,
	  
	  
      CASE
        WHEN CMD.MEMBER_NUM IS NULL THEN A.TERM_EXPIRY_DT
        WHEN A.STATUS_CD = 'A'
      AND CMD.STATUS_CD = 'P' THEN A.TERM_EXPIRY_DT
        WHEN A.STATUS_CD = 'A' AND CMD.STATUS_CD = 'A' AND DATE_DIFF(CMD.TERM_EXPIRY_DT, A.TERM_EXPIRY_DT, DAY) > 360 THEN A.TERM_EXPIRY_DT
        WHEN A.STATUS_CD = 'A'
      AND CMD.STATUS_CD = 'C' THEN A.TERM_EXPIRY_DT
        ELSE CMD.TERM_EXPIRY_DT
      END AS TERM_EXPIRY_DT,
      A.CORPORATE_GROUP_TYPE,
      A.DO_NOT_RENEW_IND,
      A.DUPLICATE_CARD_REQUEST_DT,
      A.DUP_CARD_CNT,
      A.COMMISSION_CD,
      A.CANCEL_DT,
      A.REASON_JOIN_AAA_CD,
      A.SOLICITATION_CD,
      A.SOURCE_OF_SALE_CD,
      CASE
        WHEN UPPER( A.ROLE_CD) = 'P' THEN 'Primary'
        WHEN UPPER( A.ROLE_CD) = 'S' THEN 'Spouse'
        WHEN UPPER( A.ROLE_CD) = 'D' THEN 'Dependent'
        WHEN UPPER( A.ROLE_CD) = 'O' THEN 'Other'
        ELSE NULL
      END AS ROLE_CD,
      A.PAID_BY_CD,
      A.CARD_REQUEST_SKIPPPED_DT,
      A.DO_NOT_RENEW_EXPIRY_DT,
      A.DUPLICATE_STICKER_REQUEST_DT,
      A.DUPLICATE_STICKER_CNT,
      A.DUPLICATE_CARD_REASON,
      A.DO_NOT_RENEW_REASON,
      A.LANGUAGE,
      A.BILLING_CATEGORY_CD,
      A.MITA_PENDING,
      A.PREV_COMMISSION_CD,
      A.RENEW_CNT,
      A.CARD_REQT_SKIP_REASON,
      A.PREFERRED_CONTACT_METHOD_CD,
      A.REINSTATEMENT_CARD_PRINT_IND,
      A.SPRINT_ENROLL_DT,
      A.SPRN_IND,
      A.BOARD_MEMBER_IND,
      A.HONORARY_MEMBER_IND,
      A.COURTESY_MEMBER_IND,
      A.UTAH_50_YEAR_IND,
      A.SERVICE_PROVIDER_IND,
      A.VIA_MAGAZINE_PREFERRED_IND,
      A.ERS_USAGE_YEAR1,
      A.ERS_USAGE_YEAR2,
      A.ERS_USAGE_YEAR3,
      A.RESIDENTIAL_ZIP_CD,
      A.EFFECTIVE_START_DT,
      A.EFFECTIVE_END_DT,
      CURRENT_DATE(),
      A.JOB_RUN_ID,
      A.SOURCE_SYSTEM_CD,
      A.ACTIVE_FLG,
      A.MD5_VALUE,
      A.PAID_BY_CD_DESC,
      A.LAPSED_IND,
      A.ONLINE_SIGNUP_IND
    FROM (
      SELECT
        TRIM(STG.MEMBER_KEY) AS MEMBER_KEY,
        TRIM(STG.MBRS_KY) AS MEMBERSHIP_KEY,
        'NULL' AS CUSTOMER_MDM_KEY,
        STG.RESIDENTIAL_ZIP,
        TRIM(STG.MEMBER_NUM) AS MEMBER_NUM,
        TRIM(STG.MEMBERSHIP_NUM) AS MEMBERSHIP_NUM,
        TRIM(STG.MEMBERSHIP_LEVEL) AS MEMBERSHIP_LEVEL,
        CAST(TRIM(STG.ASSOCIATE_ID) AS INT64) AS ASSOCIATE_ID,
        TRIM(STG.MBR_STS_CD) AS STATUS_CD,
        TRIM(STG.MBR_STS_DSC_CD) AS STATUS_DESCRIPTION_CD,
        TRIM(STG.MBR_PREV_STS_DSC_CD) AS BILLING_STATUS_CD,
        SAFE_CAST(TRIM(STG.MIF_ELIGIBLE_CNT) AS INT64) AS MIF_ELIGIBLE_CNT,
        TRIM(STG.MBR_PREV_MBRS_ID) AS PREV_MEMBER_NUM,
        TRIM(STG.MBR_PREV_CLUB_CD) AS PREVIOUS_CLUB_CD,
        CASE
          WHEN UPPER(TRIM(STG.MBR_COMM_CD)) ='T' OR UPPER(TRIM(STG.MBR_COMM_CD)) ='T1' THEN 'Y'
          ELSE 'N'
        END AS TRANSFER_IN_IND,
        TRIM(STG.COMPENSATION_EMPLOYEE_ID) AS COMPENSATION_EMPLOYEE_ID,
        TRIM(STG.SECONDARY_COMPENSATE_EMPLOYEE_ID) AS SECONDARY_COMPENSATE_EMPLOYEE_ID,
        COALESCE(ED.LOCATION_ID,
          ED1.LOCATION_ID) AS SELLING_LOCATION_ID,
        TRIM(STG.EMPLOYEE_IND) AS EMPLOYEE_IND,
        TRIM(STG.ACTIVE_MILITARY_IND) AS ACTIVE_MILITARY_IND,
        TRIM(STG.EMPLOYEE_ID_OF_MEMBER) AS EMPLOYEE_ID_OF_MEMBER,
        TRIM(STG.MBR_FREE_ASSOC_IN) AS FREE_ASSOCIATE_IND,
        DATE(PARSE_DATETIME('%Y-%m-%d %H:%M:%S',
            STG.AAA_JOIN_DT)) AS AAA_JOIN_DT,
        DATE(PARSE_DATETIME('%Y-%m-%d %H:%M:%S',
            STG.CLUB_JOIN_DT)) AS CLUB_JOIN_DT,
        DATE(PARSE_DATETIME('%Y-%m-%d %H:%M:%S',
            STG.MBR_ACTV_DT)) AS ACTIVE_DT,
        TRIM(STG.MEMBER_SINCE) AS MEMBER_SINCE,
        PARSE_DATE('%Y-%m-%d',
          SUBSTR(STG.MBR_REINST_DT,0,10)) AS REINST_DT,
        PARSE_DATE('%Y-%m-%d',
          SUBSTR(STG.CLUB_JOIN_DT,0,10)) AS INCEPTION_DT,
        CASE
          WHEN STG.MBR_REINST_DT IS NULL THEN DATE(PARSE_DATETIME('%Y-%m-%d %H:%M:%S',  STG.CLUB_JOIN_DT))
          ELSE DATE(PARSE_DATETIME('%Y-%m-%d %H:%M:%S',
            STG.MBR_REINST_DT))
        END AS TENURE_DT,
        DATE(PARSE_DATETIME('%Y-%m-%d %H:%M:%S',
            STG.TERM_EFFECTIVE_DT)) AS TERM_EFFECTIVE_DT,
        PARSE_DATE('%Y-%m-%d',
          SUBSTR(STG.TERM_EXPIRATION_DT,0,10)) AS TERM_EXPIRY_DT,
        STG.CORPORATE_GROUP_TYPE AS CORPORATE_GROUP_TYPE,
        TRIM(STG.MBR_DO_NOT_REN_IN) AS DO_NOT_RENEW_IND,
        DATE(PARSE_DATETIME('%Y-%m-%d %H:%M:%S',
            STG.MBR_DUPCD_REQ_DT)) AS DUPLICATE_CARD_REQUEST_DT,
        CAST(TRIM(STG.DUP_CARD_CNT) AS INT64) AS DUP_CARD_CNT,
        TRIM(STG.MBR_COMM_CD) AS COMMISSION_CD,
        DATE(PARSE_DATETIME('%Y-%m-%d %H:%M:%S',
            TRIM(STG.MBR_CANC_DT))) AS CANCEL_DT,
        TRIM(STG.MBR_RSN_JOIN_CD) AS REASON_JOIN_AAA_CD,
        TRIM(STG.MBR_SLCT_CD) AS SOLICITATION_CD,
        TRIM(STG.MBR_SRC_SLS_CD) AS SOURCE_OF_SALE_CD,
        CASE
          WHEN TRIM(STG.MBR_RELAT_CD) IS NULL THEN(CASE
            WHEN TRIM(STG.ASSOCIATE_ID) = '1' THEN 'P'
            ELSE 'O'
          END )
          ELSE TRIM(STG.MBR_RELAT_CD)
        END AS ROLE_CD,
        TRIM(STG.MBR_PAID_BY_CD) AS PAID_BY_CD,
        PARSE_DATE('%Y-%m-%d',
          SUBSTR(STG.MBR_DUPCD_REQ_DT,0,10)) AS CARD_REQUEST_SKIPPPED_DT,
        DATE(PARSE_DATETIME('%Y-%m-%d %H:%M:%S',
            STG.MBR_DNR_EXPIR_DT)) AS DO_NOT_RENEW_EXPIRY_DT,
        DATE(PARSE_DATETIME('%Y-%m-%d %H:%M:%S',
            STG.MBR_DUPSTCK_REQ_DT)) AS DUPLICATE_STICKER_REQUEST_DT,
        CAST(TRIM(STG.MBR_DUP_STCK_CT) AS INT64) AS DUPLICATE_STICKER_CNT,
        TRIM(STG.DUP_CARD_REASON) AS DUPLICATE_CARD_REASON,		    
        CASE WHEN TRIM(STG.MBR_DO_NOT_REN_RSN) = "P"
        THEN "Price"
        WHEN TRIM(STG.MBR_DO_NOT_REN_RSN) = "RA"
        THEN "Renewal Adjustment"
        WHEN TRIM(STG.MBR_DO_NOT_REN_RSN) = "MT"
        THEN "Membership Termination"
        WHEN TRIM(STG.MBR_DO_NOT_REN_RSN) = "MOVE"
        THEN "Moved Out Of Territory"
        END AS DO_NOT_RENEW_REASON,
        --TRIM(STG.MBR_DO_NOT_REN_RSN) AS DO_NOT_RENEW_REASON,
        TRIM(STG.MBR_LANGUAGE) AS LANGUAGE,
        TRIM(STG.MBR_BIL_CAT_CD) AS BILLING_CATEGORY_CD,
        TRIM(STG.MBR_MITA_PENDING) AS MITA_PENDING,
        TRIM(STG.MBR_PREV_COMM_CD) AS PREV_COMMISSION_CD,
        CAST(TRIM(STG.MBR_RENEW_CT) AS INT64) AS RENEW_CNT,
        TRIM(STG.CARD_REQT_SKIP_REASON) AS CARD_REQT_SKIP_REASON,
        TRIM(STG.PREF_METH_COUNT) AS PREFERRED_CONTACT_METHOD_CD,
        TRIM(STG.MBR_REINST_PRNT_CRD_IN) AS REINSTATEMENT_CARD_PRINT_IND,
        DATE(PARSE_DATETIME('%Y-%m-%d %H:%M:%S',
            TRIM(STG.SPRINT_ENROLL_DT))) AS SPRINT_ENROLL_DT,
        CASE
          WHEN TRIM(STG.SPRN_IND) = 'N' THEN '0'
          WHEN TRIM(STG.SPRN_IND) = 'Y' THEN '1'
          ELSE NULL
        END AS SPRN_IND,
        TRIM(STG.BOARD_MEMBER_IND) AS BOARD_MEMBER_IND,
        TRIM(STG.HONORARY_MEMBER_IND) AS HONORARY_MEMBER_IND,
        TRIM(STG.COURTESY_MEMBER_IND) AS COURTESY_MEMBER_IND,
        TRIM(STG.UTAH_50_YEAR_IND) AS UTAH_50_YEAR_IND,
        TRIM(STG.SERVICE_PROVIDER_IND) AS SERVICE_PROVIDER_IND,
        TRIM(STG.VIA_MAGAZINE_PREFERRED_IND) AS VIA_MAGAZINE_PREFERRED_IND,
        CAST(TRIM(STG.MBR_ERS_USAGE_YR1) AS INT64) AS ERS_USAGE_YEAR1,
        CAST(TRIM(STG.MBR_ERS_USAGE_YR2) AS INT64) AS ERS_USAGE_YEAR2,
        CAST(TRIM(STG.MBR_ERS_USAGE_YR3) AS INT64) AS ERS_USAGE_YEAR3,
        CASE
          WHEN LENGTH(REGEXP_REPLACE(STG.RESIDENTIAL_ZIP,'[0-9]','')) = 0 THEN (CASE
            WHEN LENGTH(REGEXP_REPLACE(STG.RESIDENTIAL_ZIP,'[^a-zA-Z0-9]','')) >= 5 THEN SUBSTR(REGEXP_REPLACE(STG.RESIDENTIAL_ZIP,'[^a-zA-Z0-9]',''),0,5)
            ELSE REGEXP_REPLACE(STG.RESIDENTIAL_ZIP,'[^a-zA-Z0-9]','') END)
          ELSE SUBSTR(REGEXP_REPLACE(STG.RESIDENTIAL_ZIP,'[^a-zA-Z0-9]',''),0,6)
        END AS RESIDENTIAL_ZIP_CD,
        PARSE_DATE('%Y-%m-%d',
          STG.MBRS_UPDATE_DT) AS EFFECTIVE_START_DT,
        PARSE_DATE('%Y-%m-%d',
          '9999-12-31') AS EFFECTIVE_END_DT,
        DATETIME(CURRENT_TIMESTAMP(),
          "America/Los_Angeles") UPDATE_DTTIME,
        "jobrunid" AS JOB_RUN_ID,
        "CONNECT SUITE" AS SOURCE_SYSTEM_CD,
        'Y' AS ACTIVE_FLG,
        STG.MD5_VALUE,
        CASE
          WHEN TRIM(STG.MBR_PAID_BY_CD) = "P" THEN "PRIMARY"
          WHEN TRIM(STG.MBR_PAID_BY_CD) = "D" THEN "DEPENDENT"
          ELSE NULL
        END AS PAID_BY_CD_DESC,
        
        CASE WHEN STG.MBR_STS_CD = 'C' AND TF.TRANSACTION_TYPE_CD = "LAPSE"
        THEN "Y" 
        ELSE "N"
        END AS LAPSED_IND,
         TRIM(STG.ONLINE_SIGNUP_IND) AS ONLINE_SIGNUP_IND
        
      FROM
        LANDING.WORK_CS_MEMBER_DIM_MD5 STG
      LEFT OUTER JOIN
        CUSTOMER_PRODUCT.EMPLOYEE_DIM ED
      ON
        TRIM(STG.COMPENSATION_EMPLOYEE_ID) = ED.EMPLOYEE_ID
        AND EXTRACT( DATE
        FROM
          PARSE_DATETIME('%Y-%m-%d',
            STG.MBRS_UPDATE_DT)) BETWEEN ED.ROW_START_DT
        AND ED.ROW_END_DT
      LEFT OUTER JOIN
        CUSTOMER_PRODUCT.EMPLOYEE_DIM ED1
      ON
        TRIM(STG.COMPENSATION_EMPLOYEE_ID) = ED1.ENT_ID
        AND EXTRACT( DATE
        FROM
          PARSE_DATETIME('%Y-%m-%d',
            STG.MBRS_UPDATE_DT)) BETWEEN ED1.ROW_START_DT
        AND ED1.ROW_END_DT
      LEFT OUTER JOIN
        CUSTOMER_PRODUCT.LOCATION_DIM LD2
      ON
        ED.LOCATION_ID=LD2.LOCATION_ID
        AND LD2.ACTIVE_FLG = 'Y'
        
     LEFT OUTER JOIN (
      SELECT
        *
      FROM (
        SELECT
         MEMBER_NUM, TRANSACTION_TYPE_CD,
          ROW_NUMBER() OVER(PARTITION BY MEMBER_NUM ORDER BY TRANSACTION_DT DESC) RN
        FROM
          CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_TRANSACTIONS_FACT
        WHERE
          TRANSACTION_TYPE_CD in ('LAPSE','REMOVE', 'LAPSE') )
      WHERE
        RN=1 ) TF
    ON
      TF.MEMBER_NUM =STG.MEMBER_NUM   
        
        
      WHERE
        ( NOT EXISTS (
          SELECT
            1
          FROM
            `CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM` B
          WHERE
            B.MEMBER_NUM=STG.MEMBER_NUM
            AND ACTIVE_FLG = "Y")
          OR ( EXISTS (
            SELECT
              1
            FROM
              `CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM` D
            WHERE
              D.MEMBER_NUM=STG.MEMBER_NUM
              AND ACTIVE_FLG = "Y")
            AND NOT EXISTS (
            SELECT
              1
            FROM
              `CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM` C
            WHERE
              TO_BASE64(C.MD5_VALUE)=TO_BASE64(STG.MD5_VALUE)
              AND ACTIVE_FLG = "Y" ) ) ) )A
    LEFT OUTER JOIN
      CUSTOMER_PRODUCT.LOCATION_ZIP_DIM AS LZD
    ON
      LZD.ZIP_CD = A.RESIDENTIAL_ZIP_CD
    LEFT OUTER JOIN
      REFERENCE.CONNECTSUITE_PRODUCT_DIM PD
    ON
      PD.PRODUCT_CD = A.MEMBERSHIP_LEVEL
      AND PD.CS_MODULE = 'M'
    LEFT OUTER JOIN
      CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM CMD
    ON
      A.MEMBER_NUM = CMD.MEMBER_NUM
      AND CMD.ACTIVE_FLG = 'Y'
    LEFT OUTER JOIN (
      SELECT
        *
      FROM (
        SELECT
          *,
          ROW_NUMBER() OVER (PARTITION BY SOURCE_KEY1) RN
        FROM
          CUSTOMER_PRODUCT.MDM_CUSTOMER_BRIDGE
        WHERE
          SOURCE_SYSTEM_CD ='MEMBERSHIP' )
      WHERE
        RN=1 ) MDM
    ON
      TRIM(CAST(MDM.SOURCE_KEY1 AS STRING))=TRIM(A.MEMBER_NUM)))
