INSERT INTO CUSTOMERS.CUSTOMER_CONTACT_PREFERENCES (
CUSTOMER_ID,
MEMBER_NUM,
MEMBERSHIP_NUM,
DO_NOT_PHONE,
DO_NOT_MAIL,
DO_NOT_EMAIL,
EFFECTIVE_START_DT,
EFFECTIVE_END_DT,
JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATE_DTTIME,
ACTIVE_FLAG
)
SELECT
CAST(STG.CUSTOMERID AS INT64) AS CUSTOMER_ID,
STG.MEMBER_NUM AS MEMBER_NUM,
STG.MBRS_ID AS MEMBERSHIP_NUM,
STG.DONOTPHONE AS DO_NOT_PHONE,
STG.DONOTEMAIL AS DO_NOT_MAIL,
STG.DONOTMAIL	AS DO_NOT_EMAIL,
CASE
WHEN  PARSE_DATE('%Y-%M-%D', SUBSTR(STG.MBR_JN_AAA_DT,0,10))   IS NULL THEN CURRENT_DATE()
ELSE PARSE_DATE('%Y-%M-%D', SUBSTR(STG.MBR_JN_AAA_DT ,0,10))
END AS EFFECTIVE_START_DT,
PARSE_DATE('%Y-%M-%D', '9999-12-31') AS EFFECTIVE_END_DT,
"V_JOB_RUN_ID" AS JOB_RUN_ID,
'CONNECTSUITE' AS SOURCE_SYSTEM_CD,
CURRENT_DATETIME AS CREATE_DTTIME,
'Y' AS ACTIVE_FLAG
FROM 
LANDING.WORK_CS_MEMBERSHIP_CUSTOMER_DIM STG
WHERE  STG.MEMBER_NUM NOT IN (SELECT MEMBER_NUM FROM CUSTOMERS.CUSTOMER_CONTACT_PREFERENCES)