  --DELETE FROM LANDING.WORK_CS_MEMBER_DIM_MD5 WHERE TRUE;
INSERT INTO
  LANDING.WORK_CS_MEMBER_DIM_MD5 ( MEMBER_KEY,
    MEMBER_NUM,
    MEMBERSHIP_NUM,
    ASSOCIATE_ID,
    AAA_JOIN_DT,
    CLUB_JOIN_DT,
    MBR_BRTH_DT,
    DUP_CARD_CNT,
    MBR_MID_INIT_NM,
    MBR_LST_NM,
    MBR_FST_NM,
    MBR_NM_SUFX_CD,
    MBR_GNDR_CD,
    MBR_STS_DSC_CD,
    MBR_STS_CD,
    MBR_SLTN_CD,
    MBR_RELAT_CD,
    MBR_RSN_JOIN_CD,
    MBR_PREV_CLUB_CD,
    MBR_PREV_MBRS_ID,
    MBR_DO_NOT_REN_IN,
    MBR_SLCT_CD,
    MBR_SRC_SLS_CD,
    MBR_CANC_DT,
    MBR_COMM_CD,
    COMPENSATION_EMPLOYEE_ID,
    MBRS_KY,
    MBRS_REINST_DT,
    TERM_EFFECTIVE_DT,
    TERM_EXPIRATION_DT,
    MBR_TYP_CD,
    MBR_PAID_BY_CD,
    MBR_FREE_ASSOC_IN,
    MBR_DUPCD_REQ_DT,
    SECONDARY_COMPENSATE_EMPLOYEE_ID,
    MBR_DUP_STCK_CT,
    MBR_DUPSTCK_REQ_DT,
    RESIDENTIAL_ZIP,
    MBR_BIL_CAT_CD,
    MBR_ACTV_DT,
    MBR_ERS_USAGE_YR1,
    MBR_ERS_USAGE_YR2,
    MBR_ERS_USAGE_YR3,
    MBR_PREV_STS_DSC_CD,
    MBR_REINST_PRNT_CRD_IN,
    DUP_CARD_REASON,
    MBR_DO_NOT_REN_RSN,
    MBR_CARD_NAME,
    MBR_LANGUAGE,
    CARD_REQT_SKIP_DT,
    MBR_EFF_DT,
    MBR_PREV_COMM_CD,
    MBR_DNR_EXPIR_DT,
    MBR_MITA_PENDING,
    MBR_ADD_DT,
    MBR_RENEW_CT,
    MBR_REINST_DT,
    CARD_REQT_SKIP_REASON,
    MBR_EXPIR_DT,
    PREF_METH_COUNT,
    MEMBERSHIP_LEVEL,
    ACTIVE_MILITARY_IND,
    BOARD_MEMBER_IND,
    VIA_MAGAZINE_PREFERRED_IND,
    EMPLOYEE_IND,
    EMPLOYEE_ID_OF_MEMBER,
    SPRN_IND,
    HONORARY_MEMBER_IND,
    COURTESY_MEMBER_IND,
    SERVICE_PROVIDER_IND,
    MEMBER_SINCE,
    UTAH_50_YEAR_IND,
    SPRINT_ENROLL_DT,
    MIF_ELIGIBLE_CNT,
    CORPORATE_GROUP_TYPE,
    MBRS_UPDATE_DT,
    ONLINE_SIGNUP_IND    ,
    MD5_VALUE)
    SELECT * EXCEPT(RN) FROm (
SELECT DISTINCT 
  MEMBER_KEY,
  CONCAT(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),1,15),SAFE_CAST( (CASE
          WHEN MOD ( CASE
            WHEN CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),1,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),1,1) AS INT64)*2,10)
            ELSE CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),1,1) AS INT64)*2
          END +CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),2,1) AS INT64) + (CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),3,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),3,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),3,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),4,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),5,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),5,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),5,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),6,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),7,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),7,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),7,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),8,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),9,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),9,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),9,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),10,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),11,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),11,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),11,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),12,1) AS INT64) + (CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),13,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),13,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),13,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),14,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),15,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),15,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),15,1) AS INT64)*2 END),10)= 0 THEN 0
          ELSE 10 - MOD (CASE
            WHEN CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),1,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),1,1) AS INT64)*2,10)
            ELSE CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),1,1) AS INT64)*2
          END +CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),2,1) AS INT64) + (CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),3,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),3,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),3,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),4,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),5,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),5,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),5,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),6,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),7,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),7,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),7,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),8,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),9,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),9,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),9,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),10,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),11,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),11,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),11,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),12,1) AS INT64) + (CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),13,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),13,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),13,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),14,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),15,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),15,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(STG.MEMBER_NUM),TRIM(STG.ASSOCIATE_ID)),15,1) AS INT64)*2 END),10)
        END ) AS STRING )),
  MEMBER_NUM,
  ASSOCIATE_ID,
  AAA_JOIN_DT,
  CLUB_JOIN_DT,
  MBR_BRTH_DT,
  DUP_CARD_CNT,
  MBR_MID_INIT_NM,
  MBR_LST_NM,
  MBR_FST_NM,
  MBR_NM_SUFX_CD,
  MBR_GNDR_CD,
  MBR_STS_DSC_CD,
  MBR_STS_CD,
  MBR_SLTN_CD,
  MBR_RELAT_CD,
  MBR_RSN_JOIN_CD,
  MBR_PREV_CLUB_CD,
  MBR_PREV_MBRS_ID,
  MBR_DO_NOT_REN_IN,
  MBR_SLCT_CD,
  MBR_SRC_SLS_CD,
  MBR_CANC_DT,
  MBR_COMM_CD,
  COMPENSATION_EMPLOYEE_ID,
  MBRS_KY,
  MBRS_REINST_DT,
  TERM_EFFECTIVE_DT,
  TERM_EXPIRATION_DT,
  MBR_TYP_CD,
  MBR_PAID_BY_CD,
  MBR_FREE_ASSOC_IN,
  MBR_DUPCD_REQ_DT,
  SECONDARY_COMPENSATE_EMPLOYEE_ID,
  MBR_DUP_STCK_CT,
  MBR_DUPSTCK_REQ_DT,
  RESIDENTIAL_ZIP,
  MBR_BIL_CAT_CD,
  MBR_ACTV_DT,
  MBR_ERS_USAGE_YR1,
  MBR_ERS_USAGE_YR2,
  MBR_ERS_USAGE_YR3,
  MBR_PREV_STS_DSC_CD,
  MBR_REINST_PRNT_CRD_IN,
  DUP_CARD_REASON,
  MBR_DO_NOT_REN_RSN,
  MBR_CARD_NAME,
  MBR_LANGUAGE,
  CARD_REQT_SKIP_DT,
  MBR_EFF_DT,
  MBR_PREV_COMM_CD,
  MBR_DNR_EXPIR_DT,
  MBR_MITA_PENDING,
  MBR_ADD_DT,
  MBR_RENEW_CT,
  MBR_REINST_DT,
  CARD_REQT_SKIP_REASON,
  MBR_EXPIR_DT,
  PREF_METH_COUNT,
  MEMBERSHIP_LEVEL,
  ACTIVE_MILITARY_IND,
  BOARD_MEMBER_IND,
  VIA_MAGAZINE_PREFERRED_IND,
  EMPLOYEE_IND,
  EMPLOYEE_ID_OF_MEMBER,
  SPRN_IND,
  HONORARY_MEMBER_IND,
  COURTESY_MEMBER_IND,
  SERVICE_PROVIDER_IND,
  MEMBER_SINCE,
  UTAH_50_YEAR_IND,
  SPRINT_ENROLL_DT,
  MIF_ELIGIBLE_CNT,
  CORPORATE_GROUP_TYPE,
  MBRS_UPDATE_DT,
  ONLINE_SIGNUP_IND    ,
  MD5(CONCAT( COALESCE(CAST(AAA_JOIN_DT AS STRING),
        ' '), COALESCE(CAST(MBR_BRTH_DT AS STRING),
        ' '), COALESCE(CAST(DUP_CARD_CNT AS STRING),
        ' '), COALESCE(CAST(MBR_MID_INIT_NM AS STRING),
        ' '), COALESCE(CAST(MBR_LST_NM AS STRING),
        ' '), COALESCE(CAST(MBR_FST_NM AS STRING),
        ' '), COALESCE(CAST(MBR_NM_SUFX_CD AS STRING),
        ' '), COALESCE(CAST(MBR_GNDR_CD AS STRING),
        ' '), COALESCE(CAST(MBR_STS_DSC_CD AS STRING),
        ' '), COALESCE(CAST(MBR_STS_CD AS STRING),
        ' '), COALESCE(CAST(MBR_SLTN_CD AS STRING),
        ' '), COALESCE(CAST(MBR_RELAT_CD AS STRING),
        ' '), COALESCE(CAST(MBR_RSN_JOIN_CD AS STRING),
        ' '), COALESCE(CAST(MBR_PREV_CLUB_CD AS STRING),
        ' '), COALESCE(CAST(MBR_PREV_MBRS_ID AS STRING),
        ' '), COALESCE(CAST(MBR_DO_NOT_REN_IN AS STRING),
        ' '), COALESCE(CAST(MBR_SLCT_CD AS STRING),
        ' '), COALESCE(CAST(MBR_SRC_SLS_CD AS STRING),
        ' '), COALESCE(CAST(MBR_CANC_DT AS STRING),
        ' '), COALESCE(CAST(MBR_COMM_CD AS STRING),
        ' '), COALESCE(CAST(COMPENSATION_EMPLOYEE_ID AS STRING),
        ' '), COALESCE(CAST(MBRS_KY AS STRING),
        ' '), COALESCE(CAST(MBRS_REINST_DT AS STRING),
        ' '), COALESCE(CAST(TERM_EFFECTIVE_DT AS STRING),
        ' '), COALESCE(CAST(TERM_EXPIRATION_DT AS STRING),
        ' '), COALESCE(CAST(MBR_TYP_CD AS STRING),
        ' '), COALESCE(CAST(MBR_PAID_BY_CD AS STRING),
        ' '), COALESCE(CAST(MBR_FREE_ASSOC_IN AS STRING),
        ' '), COALESCE(CAST(MBR_DUPCD_REQ_DT AS STRING),
        ' '), COALESCE(CAST(SECONDARY_COMPENSATE_EMPLOYEE_ID AS STRING),
        ' '), COALESCE(CAST(MBR_DUP_STCK_CT AS STRING),
        ' '), COALESCE(CAST(MBR_DUPSTCK_REQ_DT AS STRING),
        ' '), COALESCE(CAST(RESIDENTIAL_ZIP AS STRING),
        ' '), COALESCE(CAST(MBR_BIL_CAT_CD AS STRING),
        ' '), COALESCE(CAST(MBR_ACTV_DT AS STRING),
        ' '), COALESCE(CAST(MBR_ERS_USAGE_YR1 AS STRING),
        ' '), COALESCE(CAST(MBR_ERS_USAGE_YR2 AS STRING),
        ' '), COALESCE(CAST(MBR_ERS_USAGE_YR3 AS STRING),
        ' '), COALESCE(CAST(MBR_PREV_STS_DSC_CD AS STRING),
        ' '), COALESCE(CAST(MBR_REINST_PRNT_CRD_IN AS STRING),
        ' '), COALESCE(CAST(DUP_CARD_REASON AS STRING),
        ' '), COALESCE(CAST(MBR_DO_NOT_REN_RSN AS STRING),
        ' '), COALESCE(CAST(MBR_CARD_NAME AS STRING),
        ' '), COALESCE(CAST(MBR_LANGUAGE AS STRING),
        ' '), COALESCE(CAST(CARD_REQT_SKIP_DT AS STRING),
        ' '), COALESCE(CAST(MBR_EFF_DT AS STRING),
        ' '), COALESCE(CAST(MBR_PREV_COMM_CD AS STRING),
        ' '), COALESCE(CAST(MBR_DNR_EXPIR_DT AS STRING),
        ' '), COALESCE(CAST(MBR_MITA_PENDING AS STRING),
        ' '), COALESCE(CAST(MBR_ADD_DT AS STRING),
        ' '), COALESCE(CAST(MBR_RENEW_CT AS STRING),
        ' '), COALESCE(CAST(MBR_REINST_DT AS STRING),
        ' '), COALESCE(CAST(CARD_REQT_SKIP_REASON AS STRING),
        ' '), COALESCE(CAST(MBR_EXPIR_DT AS STRING),
        ' '), COALESCE(CAST(PREF_METH_COUNT AS STRING),
        ' '), COALESCE(CAST(MEMBERSHIP_LEVEL AS STRING),
        ' '), COALESCE(CAST(ACTIVE_MILITARY_IND AS STRING),
        ' '), COALESCE(CAST(BOARD_MEMBER_IND AS STRING),
        ' '), COALESCE(CAST(VIA_MAGAZINE_PREFERRED_IND AS STRING),
        ' '), COALESCE(CAST(EMPLOYEE_IND AS STRING),
        ' '), COALESCE(CAST(EMPLOYEE_ID_OF_MEMBER AS STRING),
        ' '), COALESCE(CAST(SPRN_IND AS STRING),
        ' '), COALESCE(CAST(HONORARY_MEMBER_IND AS STRING),
        ' '), COALESCE(CAST(COURTESY_MEMBER_IND AS STRING),
        ' '), COALESCE(CAST(SERVICE_PROVIDER_IND AS STRING),
        ' '), COALESCE(CAST(MEMBER_SINCE AS STRING),
        ' '), COALESCE(CAST(UTAH_50_YEAR_IND AS STRING),
        ' '), COALESCE(CAST(SPRINT_ENROLL_DT AS STRING),
        ' '), COALESCE(CAST(MIF_ELIGIBLE_CNT AS STRING),
        ' '), COALESCE(CAST(CORPORATE_GROUP_TYPE AS STRING),
        ' '), COALESCE(CAST(ONLINE_SIGNUP_IND     AS STRING),        
        ' ') )),
        ROW_NUMBER() OVER(PARTITION BY CONCAT(MEMBER_NUM,ASSOCIATE_ID) ORDER BY MBRS_UPDATE_DT DESC) RN
FROM
  LANDING.WORK_CS_MEMBERSHIP_CUSTOMER_DIM STG )WHERE RN =1;
