CREATE OR REPLACE TABLE OPERATIONAL.CONNECTSUITE_MEMBERSHIP AS 
SELECT DISTINCT MEMBERSHIP_KEY
,MS.MEMBERSHIP_NUM
,BILL_PAY_METHOD
,MEMBERSHIP_STATUS_CD
,CASE  WHEN MEMBERSHIP_STATUS_CD ='A'  AND DATE_SUB(TERM_EXPIRATION_DT, INTERVAL 46 DAY)  >= CURRENT_DATE() THEN 'Active'
       WHEN MEMBERSHIP_STATUS_CD ='C' THEN 'Cancelled'
       WHEN MEMBERSHIP_STATUS_CD ='P' and CURRENT_DATE() BETWEEN DATE_SUB(TERM_EXPIRATION_DT, INTERVAL 45 DAY) AND TERM_EXPIRATION_DT  THEN 'Pending'
       WHEN MEMBERSHIP_STATUS_CD ='P' and CURRENT_DATE() > TERM_EXPIRATION_DT  THEN 'Grace'
       ELSE 'Other' END AS DERIVED_MEMBERSHIP_STATUS   
,MEMBERSHIP_STATUS_DESC
,DUES_COST_AMT
,PAYMENT_APPLY_AMT
,PAYMENT_PENDING_AMT
,PAYMENT_REFUND_AMT
,DUES_ADJUSTMENT_AMT
,CREDIT_APPLY_AMT
,CREDIT_PENDING_AMT
,RETURNED_CHECK_FEE_AMT
,OTHER_FEE_AMT
,PLUS_MEMBERSHIP_IND
,FUTURE_EFFECTIVE_IND
,KIT_ISSUED_IND
,LOCATION_ID
,LOCATION_NM
,INCENTIVE_TYPE_CD
,ENTRANCE_FEE_AMT
,PREVIOUS_STAUS_DESC_CD
,DONOT_RENEW_REASON_CD
,CANCEL_DT
,MEMBERSHIP_ACTIVE_DT
,TERM_EFFECTIVE_DT
,TERM_EXPIRATION_DT
,REINSTATE_DT
,INCEPTION_DT
,TRANSFER_IN_IND
,BALANCE_DUE_AMT
,ISSUING_STATE
,MEMBERSHIP_LEVEL
,MEMBERSHIP_LEVEL_DESC
,GIFTED_IND
,LAST_UPGRADE_DT
,LAST_DOWNGRADE_DT
,COMPENSATION_EMPLOYEE_ID
,AR_DISCOUNT_APPLIED_DT
,AR_DECLINE_FLAG
,LAST_DECLINE_DT
,FIRST_DECLINE_CURR_TERM_DT
,TOTAL_CHARGES
,TOTAL_PAYMENTS
,TOTAL_CREDITS
,SAFETY_OWED
,M.NO_OF_ASSOCIATES_CNT
,M.SECONDARY_MEMBER_IND
,M.PLUS_UPGRADE_AMT
,M.PREMIER_UPGRADE_AMT
,ASSOCIATE_CHARGE_AMT
,CASE WHEN CURRENTLY_HAS_AUTO > 0 THEN 'Y' ELSE 'N' END AS CURRENTLY_HAS_AUTO
,CASE WHEN CURRENTLY_HAS_HOME > 0 THEN 'Y' ELSE 'N' END AS CURRENTLY_HAS_HOME
,CC.CC_LAST_4_DIGITS AS CREDIT_CARD_LAST_4_DIGITS
,JOB_RUN_ID
,SOURCE_SYSTEM_CD
,ROW_START_DT
,UPDATE_DTTIME
FROM CUSTOMER_PRODUCT.CONNECTSUITE_MEMBERSHIP_DIM MS
LEFT OUTER JOIN (SELECT MEMBERSHIP_NUM, SUM(PLUS_UPGRADE_AMT) AS PLUS_UPGRADE_AMT , SUM(PREMIER_UPGRADE_AMT) AS PREMIER_UPGRADE_AMT, SUM(ASSOCIATE_CHARGE_AMT) AS ASSOCIATE_CHARGE_AMT,
SUM(CASE WHEN ASSOCIATE_ID > 2 THEN 1 ELSE 0 END) AS NO_OF_ASSOCIATES_CNT,
MAX(CASE WHEN ASSOCIATE_ID = 2 THEN 'Y' ELSE 'N' END) AS SECONDARY_MEMBER_IND
FROM CUSTOMERS.CONNECTSUITE_MEMBER  
WHERE STATUS_CD in ('A','P')
GROUP BY MEMBERSHIP_NUM) M ON MS.MEMBERSHIP_NUM = M.MEMBERSHIP_NUM
LEFT OUTER JOIN (SELECT SUBSTR(MEMBER_NUM,7,8) as MEMBERSHIP_NUM,
SUM(CASE WHEN PRODUCT_TYPE='Home' then 1 else 0 end) AS CURRENTLY_HAS_HOME,
SUM(CASE WHEN PRODUCT_TYPE='Auto' then 1 else 0 end) AS CURRENTLY_HAS_AUTO
FROM CUSTOMER_PRODUCT.INSURANCE_CUSTOMER_DIM WHERE MEMBER_NUM is not null AND STATUS_CD ='A' AND SUBSTR(MEMBER_NUM, 15,1) = '1'
GROUP BY SUBSTR(MEMBER_NUM,7,8)) INS ON INS.MEMBERSHIP_NUM = M.MEMBERSHIP_NUM
LEFT OUTER JOIN (SELECT * FROM (SELECT TRIM(E.ACCOUNT_NUMBER) AS CC_LAST_4_DIGITS,
						ME.MBRS_KY AS MBRS_KY,ROW_NUMBER() OVER (PARTITION BY E.ACCOUNT_NUMBER ORDER BY  E.E_PMT_KY DESC) RN
				 FROM OPERATIONAL.CONNECTSUITE_E_PAYMENT_PROFILE E, OPERATIONAL.CONNECTSUITE_MBRSHIP_E_PAYMENT_PROFILE ME
				 WHERE E.E_PMT_KY=ME.E_PMT_KY) WHERE RN = 1 )CC ON CC.MBRS_KY = MS.MEMBERSHIP_KEY

WHERE ACTIVE_FLG = 'Y'
