CREATE OR REPLACE TABLE CUSTOMERS.CONNECTSUITE_MEMBER AS 
SELECT DISTINCT  M.MEMBER_KEY
,M.MEMBERSHIP_KEY
,M.CUSTOMER_MDM_KEY
,M.MEMBER_NUM
,M.MEMBERSHIP_NUM
,M.MEMBERSHIP_LEVEL
,M.MEMBERSHIP_LEVEL_DESC
,M.ASSOCIATE_ID
,M.STATUS_CD
,STATUS_DESCRIPTION_CD
,BILLING_STATUS_CD
,MIF_ELIGIBLE_CNT
,CM.FIRST_NM AS FIRST_NM
,CM.LAST_NM AS LAST_NM
,CM.MID_INITIAL_NM as MID_INITIAL_NM
,CM.BIRTH_DT
,CM.GENDER_CD
,CM.SALUTATION_CD
,CM.MARITAL_STATUS_CD
,CM.HOME_PHONE_NUM
,CM.WORK_PHONE_NUM
,CM.MOBILE_PHONE_NUM
,CM.EMAIL_ADDRESS
,CM.CARD_NM AS NAME_ON_MEMBERSHIP_CARD
,CM.RESIDENTIAL_ADDRESS_LINE1
,CM.RESIDENTIAL_ADDRESS_LINE2
,CM.RESIDENTIAL_CITY
,CM.RESIDENTIAL_STATE
,CM.RESIDENTIAL_ZIP
,CM.BILLING_ADDRESS_LINE1
,CM.BILLING_ADDRESS_LINE2
,CM.BILLING_CITY
,CM.BILLING_STATE
,CM.BILLING_ZIP
,CM.TEMPORARY_ADDRESS_LINE1
,CM.TEMPORARY_ADDRESS_LINE2
,CM.TEMPORARY_CITY
,CM.TEMPORARY_STATE
,CM.TEMPORARY_ZIP
,CASE
  WHEN CURRENT_DATE() BETWEEN TEMPORARY_ADDRESS_START_DT AND TEMPORARY_ADDRESS_END_DT THEN CONCAT(IFNULL(TEMPORARY_ADDRESS_LINE1,''),'',IFNULL(CASE
    WHEN TEMPORARY_ADDRESS_LINE2 IS NULL THEN NULL
    ELSE ', ' END,''),'',IFNULL(TEMPORARY_ADDRESS_LINE2,''))
  ELSE CONCAT(IFNULL(BILLING_ADDRESS_LINE1,''),'',IFNULL(CASE
    WHEN BILLING_ADDRESS_LINE2 IS NULL THEN NULL
    ELSE ', ' END,''),'', IFNULL(BILLING_ADDRESS_LINE2,''))
END AS CALC_BILLING_ADDRESS_LINE1
,NULL AS CALC_BILLING_ADDRESS_LINE2
,CASE
  WHEN CURRENT_DATE() BETWEEN TEMPORARY_ADDRESS_START_DT AND TEMPORARY_ADDRESS_END_DT AND TEMPORARY_CITY IS NOT NULL THEN TEMPORARY_CITY
  ELSE BILLING_CITY
END AS CALC_BILLING_CITY
,CASE
  WHEN CURRENT_DATE() BETWEEN TEMPORARY_ADDRESS_START_DT AND TEMPORARY_ADDRESS_END_DT  AND TEMPORARY_STATE IS NOT NULL  THEN TEMPORARY_STATE
  ELSE BILLING_STATE
END AS CALC_BILLING_STATE
,CASE
  WHEN CURRENT_DATE() BETWEEN TEMPORARY_ADDRESS_START_DT AND TEMPORARY_ADDRESS_END_DT AND TEMPORARY_ZIP IS NOT NULL   THEN TEMPORARY_ZIP
  ELSE BILLING_ZIP
END AS CALC_BILLING_ZIP
,PREV_MEMBER_NUM
,PREVIOUS_CLUB_CD
,TRANSFER_IN_IND
,COMPENSATION_EMPLOYEE_ID
,SECONDARY_COMPENSATE_EMPLOYEE_ID
,SELLING_LOCATION_ID
,REVENUE_LOCATION_ID
,EMPLOYEE_IND
,ACTIVE_MILITARY_IND
,EMPLOYEE_ID_OF_MEMBER
,FREE_ASSOCIATE_IND
,AAA_JOIN_DT
,CLUB_JOIN_DT
,ACTIVE_DT
,MEMBER_SINCE
,REINST_DT
,INCEPTION_DT
,TENURE_DT
,TERM_EFFECTIVE_DT
,TERM_EXPIRY_DT
,CORPORATE_GROUP_TYPE
,DO_NOT_RENEW_IND
,DUPLICATE_CARD_REQUEST_DT
,DUP_CARD_CNT
,COMMISSION_CD
,CANCEL_DT
,REASON_JOIN_AAA_CD
,SOLICITATION_CD
,SOURCE_OF_SALE_CD
,ROLE_CD
,PAID_BY_CD
,CARD_REQUEST_SKIPPPED_DT
,DO_NOT_RENEW_EXPIRY_DT
,DUPLICATE_STICKER_REQUEST_DT
,DUPLICATE_STICKER_CNT
,DUPLICATE_CARD_REASON
,DO_NOT_RENEW_REASON
,LANGUAGE
,BILLING_CATEGORY_CD
,MITA_PENDING
,PREV_COMMISSION_CD
,RENEW_CNT
,CARD_REQT_SKIP_REASON
,PREFERRED_CONTACT_METHOD_CD
,REINSTATEMENT_CARD_PRINT_IND
,SPRINT_ENROLL_DT
,SPRN_IND
,BOARD_MEMBER_IND
,HONORARY_MEMBER_IND
,COURTESY_MEMBER_IND
,UTAH_50_YEAR_IND
,SERVICE_PROVIDER_IND
,VIA_MAGAZINE_PREFERRED_IND
,DECEASED_IND
,ERS_USAGE_YEAR1
,ERS_USAGE_YEAR2
,ERS_USAGE_YEAR3
,RESIDENTIAL_ZIP_CD
,M.ROW_START_DT
,M.UPDATE_DTTIME
,CM.UPDATE_DTTIME AS PROFILE_UPDATE_DTTIME
,M.SOURCE_SYSTEM_CD
,PAID_BY_CD_DESC
,PLUS_UPGRADE_AMT
,PREMIER_UPGRADE_AMT
,ASSOCIATE_CHARGE_AMT
,MPR.MEMBERSHIP_LEVEL_DESC AS MEMBERSHIP_LEVEL_DETAIL_DESC
,DONOR_FIRST_NM
,DONOR_MIDDLE_INITIAL_NM
,DONOR_LAST_NM
,DO_NOT_PHONE
,DO_NOT_MAIL
,DO_NOT_EMAIL
,OK_TO_SOLICT
,DMA_PANDER_FLAG
 FROM (SELECT * FROM CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM WHERE ACTIVE_FLG = 'Y') M
 LEFT OUTER JOIN (SELECT * FROM CUSTOMERS.MEMBERSHIP_CUSTOMER_DIM WHERE ACTIVE_FLG = 'Y') CM ON CM.MEMBER_NUM = M.MEMBER_NUM
 LEFT OUTER JOIN (SELECT MEMBER_NUM, DO_NOT_PHONE, DO_NOT_MAIL, DO_NOT_EMAIL, OK_TO_SOLICT, DMA_PANDER_FLAG FROM
(SELECT MEMBER_NUM, DO_NOT_PHONE, DO_NOT_MAIL, DO_NOT_EMAIL, OK_TO_SOLICT, DMA_PANDER_FLAG ,
ROW_NUMBER() OVER(PARTITION BY MEMBER_NUM ORDER BY CUSTOMER_ID DESC) as ROW_NUM
                 FROM CUSTOMER_PRODUCT.CUSTOMER_CONTACT_PREFERENCE_DIM  WHERE ACTIVE_FLG = 'Y' AND MEMBER_NUM IS NOT NULL) WHERE ROW_NUM = 1) CP ON CP.MEMBER_NUM = M.MEMBER_NUM
 LEFT OUTER JOIN (SELECT MEMBERSHIP_NUM, DONOR_FIRST_NM, DONOR_MIDDLE_INITIAL_NM , DONOR_LAST_NM, UPDATE_DTTIME 
                  FROM CUSTOMER_PRODUCT.CONNECTSUITE_MEMBERSHIP_DIM WHERE ACTIVE_FLG = 'Y') MS ON MS.MEMBERSHIP_NUM = M.MEMBERSHIP_NUM 
 LEFT OUTER JOIN  REFERENCE.MEMBERSHIP_PRODUCT_PRICE MPR ON UPPER(TRIM(CM.RESIDENTIAL_STATE)) = UPPER(TRIM(MPR.STATE)) AND UPPER(TRIM(M.MEMBERSHIP_LEVEL)) = UPPER(TRIM(MPR.MEMBERSHIP_LEVEL))
 AND CASE WHEN M.ASSOCIATE_ID = 1 THEN  'PRIMARY' ELSE 'ASSOCIATE' END = MPR.ROLE
