  DELETE
FROM
 LANDING.WORK_CS_MEMBERSHIP_DIM_MD5 A
WHERE
 EXISTS (
 SELECT
   1
 FROM
   CUSTOMER_PRODUCT.CONNECTSUITE_MEMBERSHIP_DIM B
 WHERE
   A.MEMBERSHIP_KEY=SAFE_CAST(B.MEMBERSHIP_KEY  AS STRING)
  AND PARSE_DATE('%Y-%m-%d',A.MBRS_UPDATE_DT) = B.ROW_START_DT
   )
