DELETE
FROM
 LANDING.WORK_CS_MEMBER_DIM_MD5 A
WHERE
 EXISTS (
 SELECT
   1
 FROM
   CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM B
 WHERE
   A.MEMBER_NUM=B.MEMBER_NUM  
  AND PARSE_DATE('%Y-%m-%d',A.MBRS_UPDATE_DT) = B.ROW_START_DT
   )

   
   