   DELETE
FROM
 LANDING.WORK_CS_MEMBERSHIP_CUSTOMER_DIM_MD5 A
WHERE
 EXISTS (
 SELECT
   1
 FROM
   CUSTOMERS.MEMBERSHIP_CUSTOMER_DIM B
 WHERE
   CONCAT(A.MBRS_ID,A.ASSOCIATE_ID) =CONCAT(B.MEMBERSHIP_NUM,SAFE_CAST(B.ASSOCIATE_ID AS STRING))
  AND PARSE_DATE('%Y-%m-%d',A.MBRS_UPDATE_DT) = B.ROW_START_DT
  )