UPDATE   `CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM` DIM
SET DIM.ROW_END_DT = DATE_SUB(PARSE_DATE('%Y-%m-%d',STG.MBRS_UPDATE_DT), INTERVAL 1 DAY),
ACTIVE_FLG = 'N'
FROM `LANDING.WORK_CS_MEMBER_DIM_MD5`  STG
INNER JOIN 
(SELECT MM,ROW_START_DT,ACTIVE_FLG FROM 
(SELECT TRIM(MEMBER_NUM) MM,ROW_START_DT,ACTIVE_FLG, ROW_NUMBER() OVER (PARTITION BY TRIM(MEMBER_NUM),ACTIVE_FLG ORDER BY ROW_START_DT DESC ) DUP_CHECK FROM `CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM` WHERE ACTIVE_FLG = 'Y') 
WHERE DUP_CHECK=2 ) TEMP
ON TEMP.MM =TRIM(STG.MEMBER_NUM )
WHERE TEMP.ROW_START_DT = DIM.ROW_START_DT AND TRIM(DIM.MEMBER_NUM) = TRIM(STG.MEMBER_NUM )