UPDATE `CUSTOMERS.CUSTOMER_CONTACT_PREFERENCES` CP
SET CP.EFFECTIVE_END_DT = current_date(),
ACTIVE_FLAG = 'N'
FROM `LANDING.WORK_CS_MEMBERSHIP_CUSTOMER_DIM`  STG
INNER JOIN (SELECT MEMBER_NUM,EFFECTIVE_END_DT FROM (SELECT MEMBER_NUM,EFFECTIVE_END_DT, ROW_NUMBER() OVER (PARTITION BY MEMBER_NUM ORDER BY EFFECTIVE_END_DT DESC ) DUP_CHECK FROM `CUSTOMERS.CUSTOMER_CONTACT_PREFERENCES`) 
WHERE DUP_CHECK=2) TEMP
ON TEMP.MEMBER_NUM=CONCAT('429',LPAD(STG.mbrs_id,8,'0'),STG.mbr_assoc_id)
WHERE TEMP.EFFECTIVE_END_DT = CP.EFFECTIVE_END_DT AND CP.MEMBER_NUM = CONCAT('429',LPAD(STG.mbrs_id,8,'0'),STG.mbr_assoc_id)