SELECT
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.DLY_KY)) AS SOURCE_TRANSACTION_ID,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.DLY_MBRS_DT,
      120)) AS TRANSACTION_EFFECTIVE_DT,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.MBRS_CRD_EXPIR_DT,
      120)) AS TERM_EXPIRATION_DT,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.DLY_TRANS_DT,
      120)) AS TRANSACTION_DTTIME,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.DLY_MBRS_ID)) AS MEMBERSHIP_NUM,
  '' AS MEMBER_ROLE_CD,
  '' MEMBERSHIP_RIDER_TYPE,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.DLY_ASSOC_ID)) AS ASSOCIATE_ID,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.DLY_TRANS_CD)) AS SOURCE_TRANSACTION_TYPE,
 CASE
    WHEN DAILY_EVENT.DLY_TRANS_CD = 'ADDASSOC' THEN 'ADD'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='ADDASENT' THEN 'ENROLLMENT'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='ADDASRDR' THEN 'UPGRADE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='ADDPRMRY' THEN 'CREATE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='ADDPRENT' THEN 'ENROLLMENT'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='ADDPRRDR' THEN 'UPGRADE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='CNLASSOC' THEN 'REMOVE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='CNLASRDR' THEN 'DOWNGRADE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='CNLNAASS' THEN 'LAPSE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='CNLNAASR' THEN 'DOWNGRADE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='CNLNAPRY' THEN 'LAPSE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='CNLNAPRR' THEN 'DOWNGRADE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='CNLPRMRY' THEN 'CANCEL'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='CNLPRRDR' THEN 'DOWNGRADE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='CHGSAASS' THEN 'AGENT CHANGE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='CHGSAARD' THEN 'AGENT CHANGE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='CHGSAPRY' THEN 'AGENT CHANGE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='CHGSAPRD' THEN 'AGENT CHANGE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='REIASSOC' THEN 'REINSTATE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='REIASRDR' THEN 'REINSTATE RIDER'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='REIPRMRY' THEN 'REINSTATE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='REIPRRDR' THEN 'REINSTATE RIDER'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='RENASSOC' THEN 'RENEW'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='RENASRDR' THEN 'RENEW RIDER'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='RENPRMRY' THEN 'RENEW'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='RENPRRDR' THEN 'RENEW RIDER'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='RVPAYASS' THEN 'REVERSE PAYMENT'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='RVPAYAEN' THEN 'REVERSE ENROLLMENT PAYMENT'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='RVPAYARD' THEN 'REVERSE RIDER PAYMENT'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='RVPAYPRY' THEN 'REVERSE PAYMENT'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='RVPAYPEN' THEN 'REVERSE ENROLLMENT PAYMENT'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='RVPAYPRD' THEN 'REVERSE RIDER PAYMENT'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='CNLNAENT' THEN 'LAPSE ENROLLMENT'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='SWTASSOC' THEN 'SWITCH ASSOCIATE'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='SWTASRDR' THEN 'SWITCH RIDER'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='SWTPRMRY' THEN 'SWITCH PRIMARY'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='SWTPRRDR' THEN 'SWITCH RIDER'
    WHEN DAILY_EVENT.DLY_TRANS_CD ='CNLENT' THEN 'CANCEL ENROLLMENT'
    ELSE 'NULL'
  END AS TRANSACTION_TYPE_CD,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.DLY_SLCT_CD)) AS SOLICITATION_CD,
  TRIM(
      SOLICITATION.SLCT_DSC_CD) AS SOLICITATION_DESC,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.DLY_COMM_CD)) AS COMMISSION_CD,
   CASE
    WHEN TRIM(DAILY_EVENT.DLY_COMM_CD) = 'R' OR TRIM(DAILY_EVENT.DLY_COMM_CD) = 'R1' THEN 'RENEWAL' WHEN TRIM(DAILY_EVENT.DLY_COMM_CD) = 'T' OR TRIM(DAILY_EVENT.DLY_COMM_CD) = 'T1' THEN 'TRANSFER IN'
    ELSE 'NEW'
  END AS COMMISSION_DESC,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.DLY_SUBCAT_CD)) AS SUBCATEGORY_CD,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.DLY_TOTAL_COST_AT)) AS TRANSACTION_TOTAL_COST_AMT,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.DLY_CRED_AT)) AS TRANSACTION_CREDIT_AMT,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.DLY_DUES_AT)) AS TRANSACTION_DUE_AMT,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.DLY_USER_ID)) AS PROCESSED_EMPLOYEE_ID,
  TRIM(CONVERT(CHAR,
      SALES_AGENT.EMPLOYEE_ID)) AS COMPENSATION_EMPLOYEE_ID,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.MCST_KY)) AS COST_KEY,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.DLY_PRI_SAGT_KY)) AS DLY_PRI_SAGT_KY,
  CASE
    WHEN UPPER(TRIM(DLY_COMM_CD)) IN ('T',  'T1') THEN 'Y'
    ELSE 'N'
  END AS TRANSFER_IN_IND,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.BRN_KY)) AS BRN_KY,
  TRIM(CONVERT(CHAR,
      BRANCH.BRN_CD)) AS BRANCH_CD,
  TRIM(CONVERT(CHAR,
      BRANCH.BRN_NM)) AS BRANCH_NAME,
  TRIM(CONVERT(CHAR,
      DAILY_EVENT.DLY_COMP_CD)) AS COMPONENT_CD,
      TRIM(CONVERT(CHAR,DLY_SEC_SAGT_KY)) AS SECONDARY_SALES_AGENT_KEY,
TRIM(CONVERT(CHAR,DLY_MBRS_BRN_KY)) AS MEMBERSHIP_BRANCH_KEY    ,
TRIM(CONVERT(CHAR,DLY_USER_BRN_CD)) AS USER_BRANCH_CD           ,
TRIM(CONVERT(CHAR,DLY_PREV_COMM_CD)) AS PREVIOUS_TRANSFER_IN_IND,
TRIM(CONVERT(CHAR,DLY_RENEW_CT)) AS RENEW_COUNT                 ,
TRIM(CONVERT(CHAR,DLY_AR_IN)) AS ACCOUNTS_RECEIVABLE_IND        ,
TRIM(CONVERT(CHAR,DLY_PRORATE_IN)) AS PRORATE_IND               ,
TRIM(CONVERT(CHAR,DLY_COMMD_IN)) AS COMMISSIONABLE_IND          ,
TRIM(CONVERT(CHAR,DLY_REN_FR_DROP_IN)) AS RENEW_FROM_DROP_IND   ,
TRIM(CONVERT(CHAR,DLY_FREE_ASSOC_IN)) AS FREE_ASSOCIATE_IND   
FROM
  DAILY_EVENT AS DAILY_EVENT
LEFT OUTER JOIN
  BRANCH BRANCH
ON
  DAILY_EVENT.BRN_KY = BRANCH.BRN_KY
LEFT OUTER JOIN
  SOLICITATION SOLICITATION
ON
  SOLICITATION.SLCT_CD = DAILY_EVENT.DLY_SLCT_CD
LEFT OUTER JOIN
  SALES_AGENT SALES_AGENT
ON
  DAILY_EVENT.DLY_PRI_SAGT_KY = SALES_AGENT.SAGT_KY
WHERE
 CONVERT(DATE,
   DAILY_EVENT.DLY_TRANS_DT) >= CONVERT(DATE,
           '2019-12-24' ) AND CONVERT(DATE,
   DAILY_EVENT.DLY_TRANS_DT) <= CONVERT(DATE,
           GETDATE() - 1)
 --WHERE DAILY_EVENT.DLY_KY > 'max_dly_ky'
