SELECT
TRIM(CONVERT(CHAR,MBR_KY)) AS MBR_KY,
TRIM(MBRS_ID) AS MBRS_ID,
TRIM(MBR_ASSOC_ID) AS MBR_ASSOC_ID,
TRIM(CONVERT(CHAR,MBR_JN_AAA_DT,121)) AS MBR_JN_AAA_DT,
TRIM(CONVERT(CHAR,MBR_JN_CLB_DT,121)) AS MBR_JN_CLB_DT,
TRIM(CONVERT(CHAR,MBR_DUP_CRD_CT)) AS MBR_DUP_CRD_CT,
TRIM(MBR_STS_DSC_CD) AS MBR_STS_DSC_CD,
TRIM(MBR_STS_CD) AS MBR_STS_CD,
TRIM(MBR_SLTN_CD) AS MBR_SLTN_CD,
TRIM(MBR_RELAT_CD) AS MBR_RELAT_CD,
TRIM(MBR_RSN_JOIN_CD) AS MBR_RSN_JOIN_CD,
TRIM(MBR_PREV_CLUB_CD) AS MBR_PREV_CLUB_CD,
TRIM(MBR_PREV_MBRS_ID) AS MBR_PREV_MBRS_ID,
TRIM(MBR_DO_NOT_REN_IN) AS MBR_DO_NOT_REN_IN,
TRIM(MBR_SLCT_CD) AS MBR_SLCT_CD,
TRIM(MBR_SRC_SLS_CD) AS MBR_SRC_SLS_CD,
TRIM(CONVERT(CHAR,MBR_CANC_DT,121)) AS MBR_CANC_DT,
TRIM(MBR_COMM_CD) AS MBR_COMM_CD,
TRIM(CONVERT(CHAR,SLS_AGT_KY)) AS SLS_AGT_KY,
TRIM(CONVERT(CHAR,MBR.MBRS_KY)) AS MBRS_KY,
TRIM(MBR_TYP_CD) AS MBR_TYP_CD,
TRIM(MBR_PAID_BY_CD) AS MBR_PAID_BY_CD,
TRIM(MBR_FREE_ASSOC_IN) AS MBR_FREE_ASSOC_IN,
TRIM(MBR_RETN_ASGD_IN) AS MBR_RETN_ASGD_IN,
TRIM(CONVERT(CHAR,MBR_DUPCD_REQ_DT,121)) AS MBR_DUPCD_REQ_DT,
TRIM(CONVERT(CHAR,MBR_SEC_SAGT_KY)) AS MBR_SEC_SAGT_KY,
TRIM(CONVERT(CHAR,MBR_DUP_STCK_CT)) AS MBR_DUP_STCK_CT,
TRIM(CONVERT(CHAR,MBR_DUPSTCK_REQ_DT,121)) AS MBR_DUPSTCK_REQ_DT,
TRIM(MBR_BIL_CAT_CD) AS MBR_BIL_CAT_CD,
TRIM(MBR_CERT_TX) AS MBR_CERT_TX,
TRIM(CONVERT(CHAR,MBR_CRED_CYCLE_NR)) AS MBR_CRED_CYCLE_NR,
TRIM(CONVERT(CHAR,MBR_ACTV_DT,121)) AS MBR_ACTV_DT,
TRIM(CONVERT(CHAR,MBR_ERS_USAGE_YR1)) AS MBR_ERS_USAGE_YR1,
TRIM(CONVERT(CHAR,MBR_ERS_USAGE_YR2)) AS MBR_ERS_USAGE_YR2,
TRIM(CONVERT(CHAR,MBR_ERS_USAGE_YR3)) AS MBR_ERS_USAGE_YR3,
TRIM(MBR_PREV_STS_DSC_CD) AS MBR_PREV_STS_DSC_CD,
TRIM(MBR_REINST_PRNT_CRD_IN) AS MBR_REINST_PRNT_CRD_IN,
TRIM(DUP_CARD_REASON) AS DUP_CARD_REASON,
TRIM(MBR_DO_NOT_REN_RSN) AS MBR_DO_NOT_REN_RSN,
TRIM(MBR_LANGUAGE) AS MBR_LANGUAGE,
TRIM(CONVERT(CHAR,CARD_REQT_SKIP_DT,121)) AS CARD_REQT_SKIP_DT,
TRIM(CONVERT(CHAR,MBR_EFF_DT,121)) AS MBR_EFF_DT,
TRIM(MBR_PREV_COMM_CD) AS MBR_PREV_COMM_CD,
TRIM(CONVERT(CHAR,MBR_DNR_EXPIR_DT,121)) AS MBR_DNR_EXPIR_DT,
TRIM(MBR_MITA_PENDING) AS MBR_MITA_PENDING,
TRIM(CONVERT(CHAR,MBR_ADD_DT,121)) AS MBR_ADD_DT,
TRIM(CONVERT(CHAR,MBR_RENEW_CT)) AS MBR_RENEW_CT,
TRIM(MBR_OVERAGE_TRAN_IN) AS MBR_OVERAGE_TRAN_IN,
TRIM(CONVERT(CHAR,MBR_REINST_DT,121)) AS MBR_REINST_DT,
TRIM(CARD_REQT_SKIP_REASON) AS CARD_REQT_SKIP_REASON,
TRIM(CONVERT(CHAR,MBR_EXPIR_DT,121)) AS MBR_EXPIR_DT,
TRIM(PREF_METH_CNT) AS PREF_METH_CNT
FROM [M_PRD].[DBO].[MBR] MBR
INNER JOIN (
    SELECT DISTINCT 
      MBRS_KY,
      MAX(MBRS_UPDT_DT) AS  MBRS_UPDT_DT    
      FROM (
        SELECT
          MBRS_KY,
          MBRS_RTD2K_UPDT_DT AS MBRS_UPDT_DT
        FROM
          [M_PRD].[DBO].[MBRSHIP]
        WHERE
          CONVERT(DATE,
            MBRSHIP.MBRS_RTD2K_UPDT_DT) = CONVERT(DATE,GETDATE() - 1)
            UNION
        SELECT
          DISTINCT MBRSHIP_COMMENT.MBRS_KY AS MBRS_KY,
          MBRSHIP_COMMENT.MCMT_UPDT_DT AS MBRS_UPDT_DT
        FROM
         [M_PRD].[DBO].[MBRSHIP_COMMENT]
        WHERE
          CONVERT(DATE,
            MBRSHIP_COMMENT.MCMT_UPDT_DT) = CONVERT(DATE,GETDATE() - 1)
         ) SQ GROUP BY MBRS_KY ) CDC
		 ON
    CDC.MBRS_KY= MBR.MBRS_KY