SELECT
TRIM(CONVERT(CHAR,RIDE_KY)) AS RIDE_KY,
TRIM(RIDE_COMP_CD) AS RIDE_COMP_CD,
TRIM(CONVERT(CHAR,RIDE_EFF_DT,121)) AS RIDE_EFF_DT,
TRIM(CONVERT(CHAR,RIDE_CANC_DT,121)) AS RIDE_CANC_DT,
TRIM(CONVERT(CHAR,RIDE_COMM_CD)) AS RIDE_COMM_CD,
TRIM(RIDE_SRC_SLS_CD) AS RIDE_SRC_SLS_CD,
TRIM(RIDE_SLCT_CD) AS RIDE_SLCT_CD,
TRIM(RIDE_STS_CD) AS RIDE_STS_CD,
TRIM(RIDE_STS_DSC_CD) AS RIDE_STS_DSC_CD,
TRIM(RIDE_PAID_BY_CD) AS RIDE_PAID_BY_CD,
TRIM(CONVERT(CHAR,SLS_AGT_KY)) AS SLS_AGT_KY,
TRIM(CONVERT(CHAR,MBR_KY)) AS MBR_KY,
TRIM(CONVERT(CHAR,RIDER.MBRS_KY)) AS MBRS_KY,
TRIM(RIDE_DO_NOT_REN_IN) AS RIDE_DO_NOT_REN_IN,
TRIM(CONVERT(CHAR,RIDE_SEC_SAGT_KY)) AS RIDE_SEC_SAGT_KY,
TRIM(CONVERT(CHAR,RIDE_ACTV_DT,121)) AS RIDE_ACTV_DT,
TRIM(RIDE_PREV_STS_DSC_CD) AS RIDE_PREV_STS_DSC_CD,
TRIM(CONVERT(CHAR,RIDE_ADD_DT,121)) AS RIDE_ADD_DT,
TRIM(RIDE_DO_NOT_REN_RSN) AS RIDE_DO_NOT_REN_RSN,
TRIM(RIDE_PREV_COMM_CD) AS RIDE_PREV_COMM_CD,
TRIM(CONVERT(CHAR,RIDE_DNR_EXPIR_DT,121)) AS RIDE_DNR_EXPIR_DT,
TRIM(CONVERT(CHAR,CARD_REQT_SKIP_DT,121)) AS CARD_REQT_SKIP_DT,
TRIM(CONVERT(CHAR,RIDE_RENEW_CT)) AS RIDE_RENEW_CT,
TRIM(RIDE_OVERAGE_TRAN_IN) AS RIDE_OVERAGE_TRAN_IN,
TRIM(CONVERT(CHAR,RIDE_REINST_DT,121)) AS RIDE_REINST_DT,
TRIM(CONVERT(CHAR,RIDE_EXPIR_DT,121)) AS RIDE_EXPIR_DT
FROM [M_PRD].[DBO].[RIDER] RIDER
  INNER JOIN (
    SELECT DISTINCT 
      MBRS_KY,
      MAX(MBRS_UPDT_DT) AS  MBRS_UPDT_DT    
      FROM (
        SELECT
          MBRS_KY,
          MBRS_RTD2K_UPDT_DT AS MBRS_UPDT_DT
        FROM
          [M_PRD].[DBO].[MBRSHIP]
        WHERE
          CONVERT(DATE,
            MBRSHIP.MBRS_RTD2K_UPDT_DT) = CONVERT(DATE,
            GETDATE() - 1)
            UNION
        SELECT
          DISTINCT MBRSHIP_COMMENT.MBRS_KY AS MBRS_KY,
          MBRSHIP_COMMENT.MCMT_UPDT_DT AS MBRS_UPDT_DT
        FROM
          [M_PRD].[DBO].[MBRSHIP_COMMENT]
        WHERE
          CONVERT(DATE,
            MBRSHIP_COMMENT.MCMT_UPDT_DT) = CONVERT(DATE,
            GETDATE() - 1)
 ) SQ GROUP BY MBRS_KY
   ) CDC
  ON
    CDC.MBRS_KY=RIDER.MBRS_KY