CREATE OR REPLACE TABLE REFERENCE.ERS_LOOK_UP AS 
(select 
TABLE_NM,
LOOK_U_CD, 
LOOK_U_DESC, 
CAST(CODE_ORDER AS INT64) as CODE_ORDER, 
CODE_TYPE, 
COMMENT_REQ,
'jobrunid' as JOB_RUN_ID,
'ERS' as SOURCE_SYSTEM_CD,
CURRENT_DATETIME() as CREATE_DT
FROM LANDING.WORK_ERS_LOOK_UP)