CREATE OR REPLACE TABLE REFERENCE.ERS_LOOK_UP_NAMES AS
(SELECT
TABLE_NM, 
TABLE_DESC, 
TABLE_MOD, 
CAST(SUBSTR(LAST_UPDT,1,10) AS DATE) as LAST_UPDT, 
DISPLAY_FLG, 
REASON_MOD, 
CAST(CATEGORY AS INT64) as CATEGORY, 
MAX_CHARS, 
COMMENT_REQ,
'jobrunid' as JOB_RUN_ID,
'ERS' as SOURCE_SYSTEM_CD,
CURRENT_DATETIME() as CREATE_DT
FROM LANDING.WORK_ERS_LOOK_UP_NAMES)