SELECT
TO_CHAR(translate(SVC_FACL_FUNC_CD,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_FUNC_CD,
TO_CHAR(translate(SVC_FACL_ID,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_ID,
TO_CHAR(translate(SVC_FACL_BSC_AD,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_BSC_AD,
TO_CHAR(translate(SVC_FACL_CTY_NM,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_CTY_NM,
TO_CHAR(translate(SVC_FACL_D_S_E_TM,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_D_S_E_TM,
TO_CHAR(translate(SVC_FACL_NM,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_NM,
TO_CHAR(translate(SVC_FACL_ST_CD,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_ST_CD,
TO_CHAR(translate(SVC_FACL_STS_CD,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_STS_CD,
TO_CHAR(translate(SVC_FACL_SUPL_AD,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_SUPL_AD,
TO_CHAR(translate(SVC_FACL_ZIP_CD,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_ZIP_CD,
TO_CHAR(translate(TMP_AVG_WAIT_TIME,chr(10)||chr(11)||chr(13),' ')) as TMP_AVG_WAIT_TIME,
TO_CHAR(translate(SVC_FACL_COMMENTS,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_COMMENTS,
TO_CHAR(translate(SVC_FACL_ALLOW_OL,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_ALLOW_OL,
TO_CHAR(translate(SVC_FACL_AUTO_BID,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_AUTO_BID,
TO_CHAR(translate(SVC_FACL_AUTO_FAX,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_AUTO_FAX,
TO_CHAR(translate(FACL_AUTO_FAX_TRK,chr(10)||chr(11)||chr(13),' ')) as FACL_AUTO_FAX_TRK,
TO_CHAR(translate(SVC_FACL_LATITUDE,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_LATITUDE,
TO_CHAR(translate(SVC_FACL_LONGITUDE,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_LONGITUDE,
TO_CHAR(translate(FLEET_INDIC,chr(10)||chr(11)||chr(13),' ')) as FLEET_INDIC,
TO_CHAR(translate(AAA_FACILITY_INDIC,chr(10)||chr(11)||chr(13),' ')) as AAA_FACILITY_INDIC,
TO_CHAR(translate(MAX_CALLS_CONCUR,chr(10)||chr(11)||chr(13),' ')) as MAX_CALLS_CONCUR,
TO_CHAR(translate(MAX_CALLS_PER_DAY,chr(10)||chr(11)||chr(13),' ')) as MAX_CALLS_PER_DAY,
TO_CHAR(translate(RURAL_INDIC,chr(10)||chr(11)||chr(13),' ')) as RURAL_INDIC,
TO_CHAR(translate(SVC_AREA_MDTID,chr(10)||chr(11)||chr(13),' ')) as SVC_AREA_MDTID,
TO_CHAR(translate(SVC_BID_DISTANCE,chr(10)||chr(11)||chr(13),' ')) as SVC_BID_DISTANCE,
TO_CHAR(translate(PIN,chr(10)||chr(11)||chr(13),' ')) as PIN,
TO_CHAR(translate(PSP_INDIC,chr(10)||chr(11)||chr(13),' ')) as PSP_INDIC,
TO_CHAR(translate(BRANCH_ID,chr(10)||chr(11)||chr(13),' ')) as BRANCH_ID,
TO_CHAR(translate(SVC_FACL_CONTACT,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_CONTACT,
TO_CHAR(translate(DISTRICT_ID,chr(10)||chr(11)||chr(13),' ')) as DISTRICT_ID,
TO_CHAR(translate(SVC_FACL_CTY_BASE,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_CTY_BASE,
TO_CHAR(translate(PROF_SEQ_ID,chr(10)||chr(11)||chr(13),' ')) as PROF_SEQ_ID,
TO_CHAR(translate(SVC_FACL_TYPE,chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_TYPE,
TO_CHAR(translate(CALLOUT_FAC_NAME,chr(10)||chr(11)||chr(13),' ')) as CALLOUT_FAC_NAME,
TO_CHAR(translate(FACILITY_PREFERENCE,chr(10)||chr(11)||chr(13),' ')) as FACILITY_PREFERENCE,
TO_CHAR(translate(DISP_METHOD,chr(10)||chr(11)||chr(13),' ')) as DISP_METHOD,
TO_CHAR(translate(MAPPABLEINCALLS,chr(10)||chr(11)||chr(13),' ')) as MAPPABLEINCALLS,
TO_CHAR(translate(SHOW_MILEAGE_COST,chr(10)||chr(11)||chr(13),' ')) as SHOW_MILEAGE_COST,
TO_CHAR(translate(ESTIMATED_TOW_RATE,chr(10)||chr(11)||chr(13),' ')) as ESTIMATED_TOW_RATE,
TO_CHAR(translate(ALLOW_IN_CR,chr(10)||chr(11)||chr(13),' ')) as ALLOW_IN_CR,
TO_CHAR(translate(SPECIAL_SERVICES,chr(10)||chr(11)||chr(13),' ')) as SPECIAL_SERVICES,
TO_CHAR(LAST_UPDT_TS,'YYYY-MM-DD HH24:MI:SS.FF') as LAST_UPDT_TS ,
TO_CHAR(translate(COLOR,chr(10)||chr(11)||chr(13),' ')) as COLOR,
'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM NCA_CAD.SERVICE_FACILITY