SELECT
TO_CHAR(translate(EMPLE_ID,chr(10)||chr(11)||chr(13),' ')) as EMPLE_ID,
TO_CHAR(translate(CAD_EMPLE_TYP_CD,chr(10)||chr(11)||chr(13),' ')) as CAD_EMPLE_TYP_CD,
TO_CHAR(translate(EMPLE_FST_NM,chr(10)||chr(11)||chr(13),' ')) as EMPLE_FST_NM,
TO_CHAR(translate(EMPLE_FUNC_CD,chr(10)||chr(11)||chr(13),' ')) as EMPLE_FUNC_CD,
TO_CHAR(translate(EMPLE_LST_NM,chr(10)||chr(11)||chr(13),' ')) as EMPLE_LST_NM,
TO_CHAR(translate(EMPLE_MODE,chr(10)||chr(11)||chr(13),' ')) as EMPLE_MODE,
TO_CHAR(translate(EMPLE_PSSWD,chr(10)||chr(11)||chr(13),' ')) as EMPLE_PSSWD,
TO_CHAR(translate(EMPLE_STATUS,chr(10)||chr(11)||chr(13),' ')) as EMPLE_STATUS,
TO_CHAR(translate(CR_NUM_CALLS,chr(10)||chr(11)||chr(13),' ')) as CR_NUM_CALLS,
TO_CHAR(translate(CR_NUM_SECONDS,chr(10)||chr(11)||chr(13),' ')) as CR_NUM_SECONDS,
TO_CHAR(translate(CR_MAX_SECONDS,chr(10)||chr(11)||chr(13),' ')) as CR_MAX_SECONDS,
TO_CHAR(translate(CR_MIN_SECONDS,chr(10)||chr(11)||chr(13),' ')) as CR_MIN_SECONDS,
TO_CHAR(LAST_CHG_DATE,'YYYY-MM-DD') as LAST_CHG_DATE ,
TO_CHAR(translate(MOTD_READ,chr(10)||chr(11)||chr(13),' ')) as MOTD_READ,
TO_CHAR(translate(RESET_DI_PROF,chr(10)||chr(11)||chr(13),' ')) as RESET_DI_PROF,
TO_CHAR(EMP_PSWD_CHG_DT,'YYYY-MM-DD') as EMP_PSWD_CHG_DT ,
TO_CHAR(translate(EMP_PSWD_TRIES,chr(10)||chr(11)||chr(13),' ')) as EMP_PSWD_TRIES,
TO_CHAR(translate(EMPLE_GROUP,chr(10)||chr(11)||chr(13),' ')) as EMPLE_GROUP,
TO_CHAR(translate(EMAIL,chr(10)||chr(11)||chr(13),' ')) as EMAIL,
TO_CHAR(translate(FACILITY,chr(10)||chr(11)||chr(13),' ')) as FACILITY,
TO_CHAR(translate(SPMG,chr(10)||chr(11)||chr(13),' ')) as SPMG,
TO_CHAR(translate(AAR,chr(10)||chr(11)||chr(13),' ')) as AAR,
TO_CHAR(translate(LDAP_EMPLE_ID,chr(10)||chr(11)||chr(13),' ')) as LDAP_EMPLE_ID,
TO_CHAR(translate(LST_USED_LOC_CD,chr(10)||chr(11)||chr(13),' ')) as LST_USED_LOC_CD,
TO_CHAR(translate(LST_USED_ROLE_CD,chr(10)||chr(11)||chr(13),' ')) as LST_USED_ROLE_CD,
TO_CHAR(LAST_UPDT_TS,'YYYY-MM-DD HH24:MI:SS.FF') as LAST_UPDT_TS ,
TO_CHAR(translate(DI_QUEUE_PROMPT,chr(10)||chr(11)||chr(13),' ')) as DI_QUEUE_PROMPT,
TO_CHAR(translate(SMS_NUMBER,chr(10)||chr(11)||chr(13),' ')) as SMS_NUMBER,
'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM NCA_CAD.CAD_EMPLOYEE