SELECT
TO_CHAR(SVC_FAC_DBA.FACIL_INT_ID) FACIL_INT_ID, 
TO_CHAR(SVC_FAC_DBA.SVCF_DBA_NM) SVCF_DBA_NM, 
TO_CHAR(SVC_FAC_DBA.SVC_FACL_FED_ID) SVC_FACL_FED_ID, 
TO_CHAR(SVC_FAC_DBA.SVCF_BSC_AD) SVCF_BSC_AD, 
TO_CHAR(SVC_FAC_DBA.SVCF_SUPL_AD) SVCF_SUPL_AD, 
TO_CHAR(SVC_FAC_DBA.SVCF_CTY_NM) SVCF_CTY_NM, 
TO_CHAR(SVC_FAC_DBA.SVCF_ST_CD) SVCF_ST_CD, 
TO_CHAR(SVC_FAC_DBA.SVCF_ZIP_CD) SVCF_ZIP_CD, 
TO_CHAR(SVC_FAC_DBA.VENDOR_ID) VENDOR_ID, 
TO_CHAR(SVC_FAC_DBA.SVCF_OWNER_NM) SVCF_OWNER_NM
,'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM
 NCA_APD.SVC_FAC_DBA SVC_FAC_DBA