SELECT
SRC.SVC_FACL_ID, 
SRC.TRK_DRIVR_ID, 
SRC.SC_PROB_CD, 
SAFE_CAST(SRC.CAPABLE_DT AS DATETIME) AS CAPABLE_DT,
CAST(SRC.JOB_RUN_ID AS INT64) AS ETL_JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATED_BY,
current_datetime() as CREATE_DTTIME
FROM LANDING.WORK_ERS_STG_SVC_TRK_DRIVER_CAP AS SRC
