SELECT
SRC.COMM_CTR_ID,
CAST(SRC.ORG_SC_DT AS DATETIME) AS ORG_SC_DT,
CAST(SRC.ORG_SC_ID AS INT64) AS ORG_SC_ID,
CAST(SRC.DUP_SC_DT AS DATETIME) AS DUP_SC_DT,
CAST(SRC.DUP_SC_ID AS INT64) AS DUP_SC_ID,
DUPLICATION_REASON_CODE AS DUPLICATION_REASON_CD,
SAFE_CAST(SRC.JOB_RUN_ID AS INT64) AS ETL_JOB_RUN_ID , 
SOURCE_SYSTEM_CD,
CREATED_BY,
current_datetime() as CREATE_DTTIME
FROM LANDING.WORK_ERS_STG_HIST_DUP_CALL_LST SRC