SELECT 
SAFE_CAST(FACIL_INT_ID AS INT64) AS FACIL_INT_ID,
SVCF_DBA_NM,
SVC_FACL_FED_ID,
SVCF_BSC_AD,
SVCF_SUPL_AD,
SVCF_CTY_NM,
SVCF_ST_CD,
SVCF_ZIP_CD,
VENDOR_ID,
SVCF_OWNER_NM,
SAFE_CAST(JOB_RUN_ID AS INT64) AS ETL_JOB_RUN_ID,
CREATED_BY,
SOURCE_SYSTEM_CD,
CURRENT_DATETIME() CREATE_DTTIME
FROM `LANDING.WORK_ERS_STG_SVC_FAC_DBA`

