select 
TO_CHAR(translate(TD_ID, chr(10)||chr(11)||chr(13),' ')) AS TD_ID,
TO_CHAR(translate(TD_NAME, chr(10)||chr(11)||chr(13),' ')) AS TD_NAME,
TO_CHAR(translate(TD_ADDRESS, chr(10)||chr(11)||chr(13),' ')) AS TD_ADDRESS,
TO_CHAR(translate(TD_PHONE_NR, chr(10)||chr(11)||chr(13),' ')) AS TD_PHONE_NR,
TO_CHAR(translate(TD_PHONE_EXT, chr(10)||chr(11)||chr(13),' ')) AS TD_PHONE_EXT,
TO_CHAR(translate(TD_PHONE_TYPE, chr(10)||chr(11)||chr(13),' ')) AS TD_PHONE_TYPE,
TO_CHAR(translate(TD_CITY, chr(10)||chr(11)||chr(13),' ')) AS TD_CITY,
TO_CHAR(translate(TD_STATE, chr(10)||chr(11)||chr(13),' ')) AS TD_STATE,
TO_CHAR(translate(TD_ZIP, chr(10)||chr(11)||chr(13),' ')) AS TD_ZIP,
TO_CHAR(translate(TD_CONTACT, chr(10)||chr(11)||chr(13),' ')) AS TD_CONTACT,
TO_CHAR(translate(TD_LATITUDE, chr(10)||chr(11)||chr(13),' ')) AS TD_LATITUDE,
TO_CHAR(translate(TD_LONGITUDE, chr(10)||chr(11)||chr(13),' ')) AS TD_LONGITUDE,
TO_CHAR(translate(TD_USE_DEFAULT_TM, chr(10)||chr(11)||chr(13),' ')) AS TD_USE_DEFAULT_TM,
TO_CHAR(translate(TD_AAA_APPROVED, chr(10)||chr(11)||chr(13),' ')) AS TD_AAA_APPROVED,
TO_CHAR(translate(TD_DEALER_INDIC, chr(10)||chr(11)||chr(13),' ')) AS TD_DEALER_INDIC,
TO_CHAR(translate(TD_SHOW_CARD_SAVE, chr(10)||chr(11)||chr(13),' ')) AS TD_SHOW_CARD_SAVE,
TO_CHAR(translate(TD_GRID, chr(10)||chr(11)||chr(13),' ')) AS TD_GRID,
TO_CHAR(translate(TD_CLB_CD, chr(10)||chr(11)||chr(13),' ')) AS TD_CLB_CD,
TO_CHAR(translate(TD_SECURE_LOT, chr(10)||chr(11)||chr(13),' ')) AS TD_SECURE_LOT,
TO_CHAR(translate(TD_DROP_BOX_LOC, chr(10)||chr(11)||chr(13),' ')) AS TD_DROP_BOX_LOC,
TO_CHAR(translate(TD_EXT_DEALER_ID, chr(10)||chr(11)||chr(13),' ')) AS TD_EXT_DEALER_ID,
TO_CHAR(translate(TD_FAX_PHONE, chr(10)||chr(11)||chr(13),' ')) AS TD_FAX_PHONE,
TO_CHAR(translate(MOBILE_TECH, chr(10)||chr(11)||chr(13),' ')) AS MOBILE_TECH,
TO_CHAR(translate(TD_DEST_TYPE, chr(10)||chr(11)||chr(13),' ')) AS TD_DEST_TYPE,
TO_CHAR(LAST_UPDATE,'YYYY-MM-DD HH24:MI:SS') AS LAST_UPDATE,
TO_CHAR(translate(TD_SPP_FLAG, chr(10)||chr(11)||chr(13),' ')) AS TD_SPP_FLAG,
TO_CHAR(translate(TD_AAR_TOW_DEST_ID, chr(10)||chr(11)||chr(13),' ')) AS TD_AAR_TOW_DEST_ID,
TO_CHAR(translate(TD_AAA_DOLLARS, chr(10)||chr(11)||chr(13),' ')) AS TD_AAA_DOLLARS,
TO_CHAR(translate(TD_NOTES, chr(10)||chr(11)||chr(13),' ')) AS TD_NOTES,
TO_CHAR(translate(TD_ACCEPT_TOWS, chr(10)||chr(11)||chr(13),' ')) AS TD_ACCEPT_TOWS,
TO_CHAR(translate(TD_NATIONAL_FACILITY_ID, chr(10)||chr(11)||chr(13),' ')) AS TD_NATIONAL_FACILITY_ID,
TO_CHAR(translate(TD_TOW_NOTIFICATIONS, chr(10)||chr(11)||chr(13),' ')) AS TD_TOW_NOTIFICATIONS,
TO_CHAR(translate(TD_EMAIL_ADDRESS, chr(10)||chr(11)||chr(13),' ')) AS TD_EMAIL_ADDRESS
from NCA_CAD.TOW_DEST_LIST 