select
TO_CHAR(translate(SVC_FACL_ID, chr(10)||chr(11)||chr(13),' ')) as SVC_FACL_ID,
TO_CHAR(translate(TRK_DRIVR_ID, chr(10)||chr(11)||chr(13),' ')) as TRK_DRIVR_ID,
TO_CHAR(translate(TRK_DRIVR_FST_NM, chr(10)||chr(11)||chr(13),' ')) as TRK_DRIVR_FST_NM,
TO_CHAR(translate(TRK_DRIVR_LST_NM, chr(10)||chr(11)||chr(13),' ')) as TRK_DRIVR_LST_NM,
TO_CHAR(translate(TRK_DRIVR_TEL_NR, chr(10)||chr(11)||chr(13),' ')) as TRK_DRIVR_TEL_NR,
TO_CHAR(translate(TRK_DRIVR_TEL_X_NR, chr(10)||chr(11)||chr(13),' ')) as TRK_DRIVR_TEL_X_NR,
TO_CHAR(translate(TRK_DRIVR_TEL_T_CD, chr(10)||chr(11)||chr(13),' ')) as TRK_DRIVR_TEL_T_CD,
TO_CHAR(translate(PAGER_PROVIDER_ID, chr(10)||chr(11)||chr(13),' ')) as PAGER_PROVIDER_ID,
TO_CHAR(translate(PAGER_TYPE, chr(10)||chr(11)||chr(13),' ')) as PAGER_TYPE,
TO_CHAR(translate(PAGER_PIN, chr(10)||chr(11)||chr(13),' ')) as PAGER_PIN,
TO_CHAR(translate(TRK_DRIVR_BSC_AD, chr(10)||chr(11)||chr(13),' ')) as TRK_DRIVR_BSC_AD,
TO_CHAR(translate(TRK_DRIVR_CTY_NM, chr(10)||chr(11)||chr(13),' ')) as TRK_DRIVR_CTY_NM,
TO_CHAR(translate(TRK_DRIVR_ST_CD, chr(10)||chr(11)||chr(13),' ')) as TRK_DRIVR_ST_CD,
TO_CHAR(translate(TRK_DRIVR_ZIP_CD, chr(10)||chr(11)||chr(13),' ')) as TRK_DRIVR_ZIP_CD,
TO_CHAR(translate(UNLOCK_LICENSE_ID, chr(10)||chr(11)||chr(13),' ')) as UNLOCK_LICENSE_ID,
TO_CHAR(UNLOCK_LICENSE_DT,'YYYY-MM-DD HH24:MI:SS') as UNLOCK_LICENSE_DT,
TO_CHAR(translate(TRK_DRIVR_COMMENTS, chr(10)||chr(11)||chr(13),' ')) as TRK_DRIVR_COMMENTS,
TO_CHAR(translate(TECH_LEVEL, chr(10)||chr(11)||chr(13),' ')) as TECH_LEVEL,
TO_CHAR(translate(TRK_DRIVR_RPST_TRAINED, chr(10)||chr(11)||chr(13),' ')) as TRK_DRIVR_RPST_TRAINED,
TO_CHAR(TRK_DRIVR_RPST_TRAINED_DT,'YYYY-MM-DD HH24:MI:SS') as TRK_DRIVR_RPST_TRAINED_DT,
TO_CHAR(translate(DRIVER_PREFERENCE, chr(10)||chr(11)||chr(13),' ')) as DRIVER_PREFERENCE,
TO_CHAR(translate(EMAILADDRESS, chr(10)||chr(11)||chr(13),' ')) as EMAILADDRESS,
TO_CHAR(LAST_UPDT_TS,'YYYY-MM-DD HH24:MI:SS.FF') as LAST_UPDT_TS,
TO_CHAR(translate(LOGIN, chr(10)||chr(11)||chr(13),' ')) as LOGIN,
TO_CHAR(translate(DRIVER_ROLE, chr(10)||chr(11)||chr(13),' ')) as DRIVER_ROLE,
TO_CHAR(translate(SPMG_GROUP, chr(10)||chr(11)||chr(13),' ')) as SPMG_GROUP,
TO_CHAR(translate(DRIVER_PHOTO_URL, chr(10)||chr(11)||chr(13),' ')) as DRIVER_PHOTO_URL,
TO_CHAR(translate(PASSWORDHASH, chr(10)||chr(11)||chr(13),' ')) as PASSWORDHASH,
TO_CHAR(translate(PASSWORDGRACEUSERTIME, chr(10)||chr(11)||chr(13),' ')) as PASSWORDGRACEUSERTIME,
TO_CHAR(PASSWORDEXPIRATIONTIME,'YYYY-MM-DD HH24:MI:SS.FF') as PASSWORDEXPIRATIONTIME
from NCA_CAD.SVC_TRK_DRIVER