select TO_CHAR(translate(CLUB_ID,chr(10)||chr(11)||chr(13),' ')) as CLUB_ID,
TO_CHAR(translate(FACILITY_ID,chr(10)||chr(11)||chr(13),' ')) as FACILITY_ID,
TO_CHAR(translate(TRUCK_ID,chr(10)||chr(11)||chr(13),' ')) as TRUCK_ID,
TO_CHAR(translate(DRIVER_ID,chr(10)||chr(11)||chr(13),' ')) as DRIVER_ID,
TO_CHAR(translate(ASSIGNMENT_ID,chr(10)||chr(11)||chr(13),' ')) as ASSIGNMENT_ID,
TO_CHAR(translate(WORK_ZONE,chr(10)||chr(11)||chr(13),' ')) as WORK_ZONE,
TO_CHAR(translate(STAGING_LOC,chr(10)||chr(11)||chr(13),' ')) as STAGING_LOC,
TO_CHAR(translate(TARGET_LATITUDE,chr(10)||chr(11)||chr(13),' ')) as TARGET_LATITUDE,
TO_CHAR(translate(TARGET_LONGITUDE,chr(10)||chr(11)||chr(13),' ')) as TARGET_LONGITUDE,
TO_CHAR(translate(RADIUS,chr(10)||chr(11)||chr(13),' ')) as RADIUS,
TO_CHAR(translate(STATUS,chr(10)||chr(11)||chr(13),' ')) as STATUS,
TO_CHAR(translate(ASSIGNMENT_TTL,chr(10)||chr(11)||chr(13),' ')) as ASSIGNMENT_TTL,
TO_CHAR(translate(TIME_TO_ACCEPT,chr(10)||chr(11)||chr(13),' ')) as TIME_TO_ACCEPT,
TO_CHAR(LAST_UPDATED,'YYYY-MM-DD HH24:MI:SS.FF') as LAST_UPDATED ,
TO_CHAR(RECEIVED,'YYYY-MM-DD HH24:MI:SS.FF') as RECEIVED ,
TO_CHAR(translate(REASON_RE,chr(10)||chr(11)||chr(13),' ')) as REASON_RE,
TO_CHAR(translate(TRK_LAT_RE,chr(10)||chr(11)||chr(13),' ')) as TRK_LAT_RE,
TO_CHAR(translate(TRK_LON_RE,chr(10)||chr(11)||chr(13),' ')) as TRK_LON_RE,
TO_CHAR(ACCEPTED,'YYYY-MM-DD HH24:MI:SS.FF') as ACCEPTED ,
TO_CHAR(translate(REASON_ACCEPT,chr(10)||chr(11)||chr(13),' ')) as REASON_ACCEPT,
TO_CHAR(translate(RE_TO_ACCEPT,chr(10)||chr(11)||chr(13),' ')) as RE_TO_ACCEPT,
TO_CHAR(ARRIVED,'YYYY-MM-DD HH24:MI:SS.FF') as ARRIVED ,
TO_CHAR(translate(REASON_OL,chr(10)||chr(11)||chr(13),' ')) as REASON_OL,
TO_CHAR(translate(TRK_LAT_OL,chr(10)||chr(11)||chr(13),' ')) as TRK_LAT_OL,
TO_CHAR(translate(TRK_LON_OL,chr(10)||chr(11)||chr(13),' ')) as TRK_LON_OL,
TO_CHAR(translate(RE_TO_OL,chr(10)||chr(11)||chr(13),' ')) as RE_TO_OL,
TO_CHAR(translate(ACCEPT_TO_OL,chr(10)||chr(11)||chr(13),' ')) as ACCEPT_TO_OL,
TO_CHAR(translate(DISTANCE_TRAVELED_OL,chr(10)||chr(11)||chr(13),' ')) as DISTANCE_TRAVELED_OL,
TO_CHAR(DID_NOT_COMPLETE,'YYYY-MM-DD HH24:MI:SS.FF') as DID_NOT_COMPLETE ,
TO_CHAR(translate(REASON_DNC,chr(10)||chr(11)||chr(13),' ')) as REASON_DNC,
TO_CHAR(translate(TRK_LAT_DNC,chr(10)||chr(11)||chr(13),' ')) as TRK_LAT_DNC,
TO_CHAR(translate(TRK_LON_DNC,chr(10)||chr(11)||chr(13),' ')) as TRK_LON_DNC,
TO_CHAR(translate(CALL_ID,chr(10)||chr(11)||chr(13),' ')) as CALL_ID,
TO_CHAR(CALL_DATE,'YYYY-MM-DD HH24:MI:SS') as CALL_DATE ,
TO_CHAR(translate(BL_LATITUDE,chr(10)||chr(11)||chr(13),' ')) as BL_LATITUDE,
TO_CHAR(translate(BL_LONGITUDE,chr(10)||chr(11)||chr(13),' ')) as BL_LONGITUDE,
TO_CHAR(translate(DISTANCE_TO_BL,chr(10)||chr(11)||chr(13),' ')) as DISTANCE_TO_BL,
TO_CHAR(translate(DISTANCE_TRAVELED_DNC,chr(10)||chr(11)||chr(13),' ')) as DISTANCE_TRAVELED_DNC,
TO_CHAR(DECLINED,'YYYY-MM-DD HH24:MI:SS.FF') as DECLINED ,
TO_CHAR(translate(REASON_DC,chr(10)||chr(11)||chr(13),' ')) as REASON_DC,
TO_CHAR(translate(TRK_LAT_DC,chr(10)||chr(11)||chr(13),' ')) as TRK_LAT_DC,
TO_CHAR(translate(TRK_LON_DC,chr(10)||chr(11)||chr(13),' ')) as TRK_LON_DC,
TO_CHAR(DID_NOT_RESPOND,'YYYY-MM-DD HH24:MI:SS.FF') as DID_NOT_RESPOND ,
TO_CHAR(translate(REASON_DNR,chr(10)||chr(11)||chr(13),' ')) as REASON_DNR
 from  NCA_ERS_HIST.PREDICTIVE_TRUCK_ASSIGNMENT