SELECT ARCH_CALL.COMM_CTR_ID,
TO_CHAR (ARCH_CALL.SC_DT,'YYYY-MM-DD HH24:MI:SS') AS SC_DT,
ARCH_CALL.SC_ID, 
TO_CHAR (ARCH_CALL.ARCH_DATE,'YYYY-MM-DD HH24:MI:SS') AS ARCH_DATE,
ARCH_CALL.SC_CALL_CLB_CD, ARCH_CALL.SC_CALL_MBR_ID, ARCH_CALL.SC_CALL_ASC_ID, ARCH_CALL.SC_CSH_RQR_IN, ARCH_CALL.SC_CNTC_FST_NM, ARCH_CALL.SC_CNTC_LST_NM, ARCH_CALL.SC_CNTC_SUFFIX, ARCH_CALL.SC_PRTY_CD, ARCH_CALL.SC_WAIT_TM,
TO_CHAR (ARCH_CALL.SC_PRMS_ARR_TM,'YYYY-MM-DD HH24:MI:SS') AS SC_PRMS_ARR_TM,
ARCH_CALL.SC_RED_FLAG_IN, ARCH_CALL.STATUS_CD, ARCH_CALL.SC_STS_RSN_CD, ARCH_CALL.CB_FLAG, ARCH_CALL.SC_RCVD_TM, ARCH_CALL.HIST_FLAG, ARCH_CALL.SC_POLICY, ARCH_CALL.SC_SRC_CD, ARCH_CALL.HOLD_FOR_CALLBK, ARCH_CALL.CB_MEMBER, ARCH_CALL.CB_REQ_MIN, ARCH_CALL.SC_VEH_LIC_ST_CD, ARCH_CALL.SC_VEH_LIC_TAG_NR, ARCH_CALL.SC_VEH_MANF_YR_DT, ARCH_CALL.SC_VEH_MANFR_NM, ARCH_CALL.SC_VEH_MDL_NM, ARCH_CALL.SC_VEH_COLR_NM, ARCH_CALL.BL_NEAR_CTY_NM, ARCH_CALL.BL_N_LNDMRK_TX, ARCH_CALL.BL_OOT_IN, ARCH_CALL.BL_TEL_NR_EXT, ARCH_CALL.BL_TYP_CD, ARCH_CALL.BL_AREA, ARCH_CALL.BL_UPARS_TX, ARCH_CALL.BL_STATE_CD, ARCH_CALL.SVC_REGN_GRID_ID, ARCH_CALL.TOW_DST_UPRS_TX, ARCH_CALL.FACIL_INT_ID, ARCH_CALL.SC_A_SVC_TRK_ID, ARCH_CALL.SC_A_SVC_TRK_D_ID, ARCH_CALL.SC_REASGN_RSN_CD, ARCH_CALL.PROB1_CD, ARCH_CALL.PROB2_CD, ARCH_CALL.CSH_COLL, ARCH_CALL.STATUS_CHGS, ARCH_CALL.EMPLE_ID,
TO_CHAR (ARCH_CALL.SC_CNTC_EXP_DT_YR,'YYYY-MM-DD HH24:MI:SS') AS SC_CNTC_EXP_DT_YR,
ARCH_CALL.PLUS_IND, ARCH_CALL.CHG_ENTITLEMENT, ARCH_CALL.BATCH_CD, ARCH_CALL.MMP_CD, ARCH_CALL.SC_SVC_TIK_NO, ARCH_CALL.SC_TOD_IND, ARCH_CALL.SC_PROB_IND, ARCH_CALL.RATE_CATEGORY, ARCH_CALL.CALL_SOURCE, ARCH_CALL.CALL_COST, ARCH_CALL.MILES_START, ARCH_CALL.MILES_ONLC, ARCH_CALL.MILES_DEST, ARCH_CALL.PAY_ID, ARCH_CALL.SUSPENDED, ARCH_CALL.RECIPROCALIZED, ARCH_CALL.DTL_PROB1_CD, ARCH_CALL.DTL_PROB2_CD, ARCH_CALL.DTL_STS_RSN_CD, ARCH_CALL.SC_VEH_TYPE, ARCH_CALL.SPP_TKT, ARCH_CALL.SPP_CADJ, ARCH_CALL.SC_TRC_FLAG, ARCH_CALL.SC_TD_TYPE, ARCH_CALL.BL_TIMEZONE, ARCH_CALL.BL_ZIP, ARCH_CALL.BL_ZIP4, ARCH_CALL.HIGHWAY_CALL, ARCH_CALL.MILE_MARKER, ARCH_CALL.CALLBOX, ARCH_CALL.BL_VERIFIED_LOC, ARCH_CALL.AA_VERIFIED_LOC, ARCH_CALL.ACCIDENT_ASSIST_FLAG, ARCH_CALL.PUBLIC_FLAG, ARCH_CALL.TD_VERIFIED_LOC, ARCH_CALL.ER_DIRECTIONS, ARCH_CALL.TOW_DIRECTIONS, ARCH_CALL.SC_VEH_ODOMETER, ARCH_CALL.SC_VEH_VIN  ,
'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM
NCA_ERS_HIST.ARCH_CALL ARCH_CALL
WHERE EXTRACT(YEAR FROM SC_DT) = v_incr_date;