delete FROM `LANDING.WORK_ERS_GRID_ASSIGNMENTS` where true;
delete FROM `LANDING.WORK_ERS_STG_ARCH_CALL` where true;
delete FROM `LANDING.WORK_ERS_STG_ARCH_CALL_EXTD` where true;
delete FROM `LANDING.WORK_ERS_STG_SC_STATUS` where true;
delete FROM `LANDING.WORK_ERS_STG_SERVICE_PROVIDED` where true;
delete FROM `LANDING.WORK_ERS_STG_MILEAGE_HIST` where true
