SELECT 
TO_CHAR(translate(ARCH_CALL_EXTD.COMM_CTR_ID, chr(10)||chr(11)||chr(13),' ')) COMM_CTR_ID, 
TO_CHAR(ARCH_CALL_EXTD.SC_DT,'YYYY-MM-DD HH24:MI:SS') AS SC_DT,
TO_CHAR(translate(ARCH_CALL_EXTD.SC_ID, chr(10)||chr(11)||chr(13),' ')) SC_ID,
TO_CHAR(translate(ARCH_CALL_EXTD.EDS_INDIC, chr(10)||chr(11)||chr(13),' ')) EDS_INDIC,
TO_CHAR(translate(ARCH_CALL_EXTD.SCOC_INDIC, chr(10)||chr(11)||chr(13),' ')) SCOC_INDIC, 
TO_CHAR(translate(ARCH_CALL_EXTD.CUC_INDIC, chr(10)||chr(11)||chr(13),' ')) CUC_INDIC, 
TO_CHAR(translate(ARCH_CALL_EXTD.FLATBED_REQ_INDIC, chr(10)||chr(11)||chr(13),' ')) FLATBED_REQ_INDIC, 
TO_CHAR(translate(ARCH_CALL_EXTD.USE_THIS_FACL, chr(10)||chr(11)||chr(13),' ')) USE_THIS_FACL,
TO_CHAR(translate(ARCH_CALL_EXTD.NOT_THIS_FACL, chr(10)||chr(11)||chr(13),' ')) NOT_THIS_FACL,
TO_CHAR(translate(ARCH_CALL_EXTD.BILL_CODE, chr(10)||chr(11)||chr(13),' ')) BILL_CODE, 
TO_CHAR(translate(ARCH_CALL_EXTD.APT_CALL_INDIC, chr(10)||chr(11)||chr(13),' ')) APT_CALL_INDIC,
TO_CHAR(translate(ARCH_CALL_EXTD.TRK_ZONE, chr(10)||chr(11)||chr(13),' ')) TRK_ZONE, 
TO_CHAR(translate(ARCH_CALL_EXTD.BL_LAT, chr(10)||chr(11)||chr(13),' ')) BL_LAT,
TO_CHAR(translate(ARCH_CALL_EXTD.BL_LONG, chr(10)||chr(11)||chr(13),' ')) BL_LONG, 
TO_CHAR(translate(ARCH_CALL_EXTD.TD_LAT, chr(10)||chr(11)||chr(13),' ')) TD_LAT, 
TO_CHAR(translate(ARCH_CALL_EXTD.TD_LONG, chr(10)||chr(11)||chr(13),' ')) TD_LONG, 
TO_CHAR(translate(ARCH_CALL_EXTD.DRIVER_NAME, chr(10)||chr(11)||chr(13),' ')) DRIVER_NAME, 
TO_CHAR(translate(ARCH_CALL_EXTD.TOW_DEST_ID, chr(10)||chr(11)||chr(13),' ')) TOW_DEST_ID, 
TO_CHAR(translate(ARCH_CALL_EXTD.FLATBED_INDIC, chr(10)||chr(11)||chr(13),' ')) FLATBED_INDIC,
TO_CHAR(translate(ARCH_CALL_EXTD.FOUR_WHEEL_DRIVE, chr(10)||chr(11)||chr(13),' ')) FOUR_WHEEL_DRIVE, 
TO_CHAR(translate(ARCH_CALL_EXTD.REC_VEHICLE, chr(10)||chr(11)||chr(13),' ')) REC_VEHICLE,
TO_CHAR(translate(ARCH_CALL_EXTD.AWD_VEHICLE, chr(10)||chr(11)||chr(13),' ')) AWD_VEHICLE, 
TO_CHAR(translate(ARCH_CALL_EXTD.CASH_CALL_TYPE, chr(10)||chr(11)||chr(13),' ')) CASH_CALL_TYPE, 
TO_CHAR(translate(ARCH_CALL_EXTD.PO_TRACKING_NUMBER, chr(10)||chr(11)||chr(13),' ')) PO_TRACKING_NUMBER, 
TO_CHAR(translate(ARCH_CALL_EXTD.CC_NUMBER, chr(10)||chr(11)||chr(13),' ')) CC_NUMBER, 
TO_CHAR(translate(ARCH_CALL_EXTD.CC_EXPIRE_DATE, chr(10)||chr(11)||chr(13),' ')) CC_EXPIRE_DATE, 
TO_CHAR(translate(ARCH_CALL_EXTD.DISTRICT_NUM, chr(10)||chr(11)||chr(13),' ')) DISTRICT_NUM, 
TO_CHAR(translate(ARCH_CALL_EXTD.FACL_ONLOC_CHK_DGT, chr(10)||chr(11)||chr(13),' ')) FACL_ONLOC_CHK_DGT, 
TO_CHAR(translate(ARCH_CALL_EXTD.NUM_PASSENGERS, chr(10)||chr(11)||chr(13),' ')) NUM_PASSENGERS, 
TO_CHAR(translate(ARCH_CALL_EXTD.CALL_TYPE, chr(10)||chr(11)||chr(13),' ')) CALL_TYPE,
TO_CHAR(translate(ARCH_CALL_EXTD.RV_CLASS, chr(10)||chr(11)||chr(13),' ')) RV_CLASS, 
TO_CHAR(translate(ARCH_CALL_EXTD.MCYCLE_INDIC, chr(10)||chr(11)||chr(13),' ')) MCYCLE_INDIC,
TO_CHAR(translate(ARCH_CALL_EXTD.SVC_FACL_ID, chr(10)||chr(11)||chr(13),' ')) SVC_FACL_ID, 
TO_CHAR(translate(ARCH_CALL_EXTD.SVC_TICK_APPROVD, chr(10)||chr(11)||chr(13),' ')) SVC_TICK_APPROVD, 
TO_CHAR(translate(ARCH_CALL_EXTD.ACCOUNTING_DATE, chr(10)||chr(11)||chr(13),' ')) ACCOUNTING_DATE, 
TO_CHAR(translate(ARCH_CALL_EXTD.RESPONSE_INDIC, chr(10)||chr(11)||chr(13),' ')) RESPONSE_INDIC, 
TO_CHAR(translate(ARCH_CALL_EXTD.AUTH_CD, chr(10)||chr(11)||chr(13),' ')) AUTH_CD, 
TO_CHAR(translate(ARCH_CALL_EXTD.AUTH_LEVEL, chr(10)||chr(11)||chr(13),' ')) AUTH_LEVEL, 
TO_CHAR(translate(ARCH_CALL_EXTD.EMAIL_ADDR, chr(10)||chr(11)||chr(13),' ')) EMAIL_ADDR, 
TO_CHAR(translate(ARCH_CALL_EXTD.BL_TEL_TYP_CD, chr(10)||chr(11)||chr(13),' ')) BL_TEL_TYP_CD, 
TO_CHAR(translate(ARCH_CALL_EXTD.MILES_START_ORIG, chr(10)||chr(11)||chr(13),' ')) MILES_START_ORIG, 
TO_CHAR(translate(ARCH_CALL_EXTD.MILES_ONLC_ORIG, chr(10)||chr(11)||chr(13),' ')) MILES_ONLC_ORIG, 
TO_CHAR(translate(ARCH_CALL_EXTD.MILES_DEST_ORIG, chr(10)||chr(11)||chr(13),' ')) MILES_DEST_ORIG, 
TO_CHAR(translate(ARCH_CALL_EXTD.AUDIT_FLAG, chr(10)||chr(11)||chr(13),' ')) AUDIT_FLAG, 
TO_CHAR(translate(ARCH_CALL_EXTD.BATT_SVC_RESULT, chr(10)||chr(11)||chr(13),' ')) BATT_SVC_RESULT, 
TO_CHAR(translate(ARCH_CALL_EXTD.BATTERY_TESTED, chr(10)||chr(11)||chr(13),' ')) BATTERY_TESTED, 
TO_CHAR(translate(ARCH_CALL_EXTD.BATTERY_TESTNUMBER, chr(10)||chr(11)||chr(13),' ')) BATTERY_TESTNUMBER, 
TO_CHAR(translate(ARCH_CALL_EXTD.MBR_REQ_EMAIL, chr(10)||chr(11)||chr(13),' ')) MBR_REQ_EMAIL, 
TO_CHAR(translate(ARCH_CALL_EXTD.AUDITOR, chr(10)||chr(11)||chr(13),' ')) AUDITOR, 
TO_CHAR(translate(ARCH_CALL_EXTD.CC_INFO_FLG, chr(10)||chr(11)||chr(13),' ')) CC_INFO_FLG, 
TO_CHAR(translate(ARCH_CALL_EXTD.CC_RCPT_FLG, chr(10)||chr(11)||chr(13),' ')) CC_RCPT_FLG, 
TO_CHAR(translate(ARCH_CALL_EXTD.CC_CHRG_FLG, chr(10)||chr(11)||chr(13),' ')) CC_CHRG_FLG, 
TO_CHAR(translate(ARCH_CALL_EXTD.CC_AMT, chr(10)||chr(11)||chr(13),' ')) CC_AMT,
TO_CHAR(translate(ARCH_CALL_EXTD.USED_LONG_TOW, chr(10)||chr(11)||chr(13),' ')) USED_LONG_TOW,
TO_CHAR(translate(ARCH_CALL_EXTD.LONG_TOW_ELIG_INDIC, chr(10)||chr(11)||chr(13),' ')) LONG_TOW_ELIG_INDIC, 
TO_CHAR(translate(ARCH_CALL_EXTD.LONG_TOW_MILES_ALLOW, chr(10)||chr(11)||chr(13),' ')) LONG_TOW_MILES_ALLOW, 
TO_CHAR(translate(ARCH_CALL_EXTD.BL_N_LNDMRK_TX, chr(10)||chr(11)||chr(13),' ')) BL_N_LNDMRK_TX, 
TO_CHAR(translate(ARCH_CALL_EXTD.LANGUAGE, chr(10)||chr(11)||chr(13),' ')) LANGUAGE, 
TO_CHAR(translate(ARCH_CALL_EXTD.COLLISION_FLAG, chr(10)||chr(11)||chr(13),' ')) COLLISION_FLAG, 
TO_CHAR(translate(ARCH_CALL_EXTD.BATTERY_TEST_RESULTS, chr(10)||chr(11)||chr(13),' ')) BATTERY_TEST_RESULTS, 
TO_CHAR(translate(ARCH_CALL_EXTD.BATTERY_PART_NUMBER, chr(10)||chr(11)||chr(13),' ')) BATTERY_PART_NUMBER, 
TO_CHAR(translate(ARCH_CALL_EXTD.BATTERY_PRICE, chr(10)||chr(11)||chr(13),' ')) BATTERY_PRICE, 
TO_CHAR(translate(ARCH_CALL_EXTD.CALLMV_INDIC, chr(10)||chr(11)||chr(13),' ')) CALLMV_INDIC, 
TO_CHAR(translate(ARCH_CALL_EXTD.VEHICLE_ID, chr(10)||chr(11)||chr(13),' ')) VEHICLE_ID, 
TO_CHAR(translate(ARCH_CALL_EXTD.CC_CHRG_REVOK_FLG, chr(10)||chr(11)||chr(13),' ')) CC_CHRG_REVOK_FLG, 
TO_CHAR(translate(ARCH_CALL_EXTD.BASE_VEHICLE_ID, chr(10)||chr(11)||chr(13),' ')) BASE_VEHICLE_ID, 
TO_CHAR(translate(ARCH_CALL_EXTD.AVL_ETA, chr(10)||chr(11)||chr(13),' ')) AVL_ETA, 
TO_CHAR(translate(ARCH_CALL_EXTD.SMS_OPT_IN, chr(10)||chr(11)||chr(13),' ')) SMS_OPT_IN, 
TO_CHAR(translate(ARCH_CALL_EXTD.BLEND_RATE_INDIC, chr(10)||chr(11)||chr(13),' ')) BLEND_RATE_INDIC, 
TO_CHAR(translate(ARCH_CALL_EXTD.DTL_PROB1_CD_ORIG, chr(10)||chr(11)||chr(13),' ')) DTL_PROB1_CD_ORIG, 
TO_CHAR(translate(ARCH_CALL_EXTD.DTL_PROB2_CD_ORIG, chr(10)||chr(11)||chr(13),' ')) DTL_PROB2_CD_ORIG, 
TO_CHAR(translate(ARCH_CALL_EXTD.WORKFLOW, chr(10)||chr(11)||chr(13),' ')) WORKFLOW, 
TO_CHAR(translate(ARCH_CALL_EXTD.TWO_WHEEL_DRIVE, chr(10)||chr(11)||chr(13),' ')) TWO_WHEEL_DRIVE, 
TO_CHAR(translate(ARCH_CALL_EXTD.DOLLY_INDIC, chr(10)||chr(11)||chr(13),' ')) DOLLY_INDIC, 
TO_CHAR(translate(ARCH_CALL_EXTD.LOCKSMITH_INDIC, chr(10)||chr(11)||chr(13),' ')) LOCKSMITH_INDIC, 
TO_CHAR(translate(ARCH_CALL_EXTD.WHEEL_LIFT_REQ_INDIC, chr(10)||chr(11)||chr(13),' ')) WHEEL_LIFT_REQ_INDIC, 
TO_CHAR(translate(ARCH_CALL_EXTD.WHEEL_LIFT_INDIC, chr(10)||chr(11)||chr(13),' ')) WHEEL_LIFT_INDIC, 
TO_CHAR(translate(ARCH_CALL_EXTD.MC_TYPE, chr(10)||chr(11)||chr(13),' ')) MC_TYPE, 
TO_CHAR(translate(ARCH_CALL_EXTD.MC_ENG_TYPE, chr(10)||chr(11)||chr(13),' ')) MC_ENG_TYPE, 
TO_CHAR(translate(ARCH_CALL_EXTD.MC_COMMENT, chr(10)||chr(11)||chr(13),' ')) MC_COMMENT, 
TO_CHAR(translate(ARCH_CALL_EXTD.MC_PULLING_TRL, chr(10)||chr(11)||chr(13),' ')) MC_PULLING_TRL, 
TO_CHAR(translate(ARCH_CALL_EXTD.MC_LAID_DOWN, chr(10)||chr(11)||chr(13),' ')) MC_LAID_DOWN, 
TO_CHAR(translate(ARCH_CALL_EXTD.MC_WHEELS_ROLL, chr(10)||chr(11)||chr(13),' ')) MC_WHEELS_ROLL, 
TO_CHAR(translate(ARCH_CALL_EXTD.RV_LENGTH, chr(10)||chr(11)||chr(13),' ')) RV_LENGTH,
TO_CHAR(translate(ARCH_CALL_EXTD.RV_HEIGHT, chr(10)||chr(11)||chr(13),' ')) RV_HEIGHT, 
TO_CHAR(translate(ARCH_CALL_EXTD.RV_GOOSENECK, chr(10)||chr(11)||chr(13),' ')) RV_GOOSENECK, 
TO_CHAR(translate(ARCH_CALL_EXTD.RV_ENG_LOC, chr(10)||chr(11)||chr(13),' ')) RV_ENG_LOC, 
TO_CHAR(translate(ARCH_CALL_EXTD.RV_TOWING, chr(10)||chr(11)||chr(13),' ')) RV_TOWING, 
TO_CHAR(translate(ARCH_CALL_EXTD.RV_TYPE_TOWING, chr(10)||chr(11)||chr(13),' ')) RV_TYPE_TOWING, 
TO_CHAR(translate(ARCH_CALL_EXTD.FLAT_LOCATION, chr(10)||chr(11)||chr(13),' ')) FLAT_LOCATION, 
TO_CHAR(translate(ARCH_CALL_EXTD.TRL_INDIC, chr(10)||chr(11)||chr(13),' ')) TRL_INDIC, 
TO_CHAR(translate(ARCH_CALL_EXTD.TRL_TYPE, chr(10)||chr(11)||chr(13),' ')) TRL_TYPE, 
TO_CHAR(translate(ARCH_CALL_EXTD.TRL_LENGTH, chr(10)||chr(11)||chr(13),' ')) TRL_LENGTH, 
TO_CHAR(translate(ARCH_CALL_EXTD.TRL_NO_AXLES, chr(10)||chr(11)||chr(13),' ')) TRL_NO_AXLES, 
TO_CHAR(translate(ARCH_CALL_EXTD.TRL_CONDITION, chr(10)||chr(11)||chr(13),' ')) TRL_CONDITION, 
TO_CHAR(translate(ARCH_CALL_EXTD.TRL_PLUG_TYPE, chr(10)||chr(11)||chr(13),' ')) TRL_PLUG_TYPE, 
TO_CHAR(translate(ARCH_CALL_EXTD.TRL_HITCH_TYPE, chr(10)||chr(11)||chr(13),' ')) TRL_HITCH_TYPE, 
TO_CHAR(translate(ARCH_CALL_EXTD.TRL_HITCH_SIZE, chr(10)||chr(11)||chr(13),' ')) TRL_HITCH_SIZE, 
TO_CHAR(translate(ARCH_CALL_EXTD.TRL_GOOSENECK, chr(10)||chr(11)||chr(13),' ')) TRL_GOOSENECK, 
TO_CHAR(translate(ARCH_CALL_EXTD.TRL_LOADED, chr(10)||chr(11)||chr(13),' ')) TRL_LOADED, 
TO_CHAR(translate(ARCH_CALL_EXTD.TRL_LOAD_TYPE, chr(10)||chr(11)||chr(13),' ')) TRL_LOAD_TYPE, 
TO_CHAR(translate(ARCH_CALL_EXTD.TRL_LOAD_WEIGHT, chr(10)||chr(11)||chr(13),' ')) TRL_LOAD_WEIGHT, 
TO_CHAR(translate(ARCH_CALL_EXTD.HYBRID_VEHICLE, chr(10)||chr(11)||chr(13),' ')) HYBRID_VEHICLE, 
TO_CHAR(translate(ARCH_CALL_EXTD.ELECTRIC_VEHICLE, chr(10)||chr(11)||chr(13),' ')) ELECTRIC_VEHICLE, 
TO_CHAR(translate(ARCH_CALL_EXTD.IS_DIESEL, chr(10)||chr(11)||chr(13),' ')) IS_DIESEL, 
TO_CHAR(translate(ARCH_CALL_EXTD.AIR_SUSPENSION, chr(10)||chr(11)||chr(13),' ')) AIR_SUSPENSION, 
TO_CHAR(translate(ARCH_CALL_EXTD.SC_VEH_NOTES, chr(10)||chr(11)||chr(13),' ')) SC_VEH_NOTES, 
TO_CHAR(translate(ARCH_CALL_EXTD.RV_WEIGHT, chr(10)||chr(11)||chr(13),' ')) RV_WEIGHT, 
TO_CHAR(translate(ARCH_CALL_EXTD.PASSENGER_NOTES, chr(10)||chr(11)||chr(13),' ')) PASSENGER_NOTES, 
TO_CHAR(translate(ARCH_CALL_EXTD.PRIORITY_COMMENT, chr(10)||chr(11)||chr(13),' ')) PRIORITY_COMMENT, 
TO_CHAR(translate(ARCH_CALL_EXTD.KEY_LOCATION, chr(10)||chr(11)||chr(13),' ')) KEY_LOCATION, 
TO_CHAR(translate(ARCH_CALL_EXTD.SCRATCHPAD_CONTENT, chr(10)||chr(11)||chr(13),' ')) SCRATCHPAD_CONTENT, 
TO_CHAR(translate(ARCH_CALL_EXTD.D3_CALLBACK_STATE, chr(10)||chr(11)||chr(13),' ')) D3_CALLBACK_STATE, 
TO_CHAR(translate(ARCH_CALL_EXTD.ADDR2_PURPOSE, chr(10)||chr(11)||chr(13),' ')) ADDR2_PURPOSE, 
TO_CHAR(translate(ARCH_CALL_EXTD.ADDR2_BLOCK, chr(10)||chr(11)||chr(13),' ')) ADDR2_BLOCK, 
TO_CHAR(translate(ARCH_CALL_EXTD.ADDR2_STREET, chr(10)||chr(11)||chr(13),' ')) ADDR2_STREET, 
TO_CHAR(translate(ARCH_CALL_EXTD.ADDR2_CITY, chr(10)||chr(11)||chr(13),' ')) ADDR2_CITY, 
TO_CHAR(translate(ARCH_CALL_EXTD.ADDR2_STATE_CD, chr(10)||chr(11)||chr(13),' ')) ADDR2_STATE_CD, 
TO_CHAR(translate(ARCH_CALL_EXTD.ADDR2_ZIP, chr(10)||chr(11)||chr(13),' ')) ADDR2_ZIP, 
TO_CHAR(translate(ARCH_CALL_EXTD.ADDR2_ZIP4, chr(10)||chr(11)||chr(13),' ')) ADDR2_ZIP4, 
TO_CHAR(translate(ARCH_CALL_EXTD.ADDR2_COUNTY, chr(10)||chr(11)||chr(13),' ')) ADDR2_COUNTY, 
TO_CHAR(translate(ARCH_CALL_EXTD.ADDR2_COUNTRY, chr(10)||chr(11)||chr(13),' ')) ADDR2_COUNTRY, 
TO_CHAR(translate(ARCH_CALL_EXTD.ADDR2_HIGHWAY_CALL, chr(10)||chr(11)||chr(13),' ')) ADDR2_HIGHWAY_CALL, 
TO_CHAR(translate(ARCH_CALL_EXTD.ADDR2_MILE_MARKER, chr(10)||chr(11)||chr(13),' ')) ADDR2_MILE_MARKER, 
TO_CHAR(translate(ARCH_CALL_EXTD.ADDR2_CALLBOX, chr(10)||chr(11)||chr(13),' ')) ADDR2_CALLBOX, 
TO_CHAR(translate(ARCH_CALL_EXTD.ADDR2_LOCATION_CD, chr(10)||chr(11)||chr(13),' ')) ADDR2_LOCATION_CD, 
TO_CHAR(translate(ARCH_CALL_EXTD.ADDR2_LANDMARK, chr(10)||chr(11)||chr(13),' ')) ADDR2_LANDMARK, 
TO_CHAR(translate(ARCH_CALL_EXTD.ADDR2_PICKUP_POINT, chr(10)||chr(11)||chr(13),' ')) ADDR2_PICKUP_POINT, 
TO_CHAR(translate(ARCH_CALL_EXTD.SC_VEH_TRM, chr(10)||chr(11)||chr(13),' ')) SC_VEH_TRM, 
TO_CHAR(translate(ARCH_CALL_EXTD.SPECIAL_EQUIP_CD, chr(10)||chr(11)||chr(13),' ')) SPECIAL_EQUIP_CD ,
TO_CHAR(translate(ARCH_CALL_EXTD.DELIVERY_CONFIRMATION_CODE, chr(10)||chr(11)||chr(13),' ')) DELIVERY_CONFIRMATION_CODE,
TO_CHAR(translate(ARCH_CALL_EXTD.SALE_ID, chr(10)||chr(11)||chr(13),' ')) SALE_ID,
TO_CHAR(translate(ARCH_CALL_EXTD.ODOMETER_READING, chr(10)||chr(11)||chr(13),' ')) ODOMETER_READING,
TO_CHAR(translate(ARCH_CALL_EXTD.MISCELLANEOUS_COMMENT, chr(10)||chr(11)||chr(13),' ')) MISCELLANEOUS_COMMENT,
TO_CHAR(translate(ARCH_CALL_EXTD.INVENTORY_MISSING, chr(10)||chr(11)||chr(13),' ')) INVENTORY_MISSING,
TO_CHAR(translate(ARCH_CALL_EXTD.TOW_INDIC, chr(10)||chr(11)||chr(13),' ')) TOW_INDIC,
TO_CHAR(translate(ARCH_CALL_EXTD.URGENT_COMMENT_INDIC, chr(10)||chr(11)||chr(13),' ')) URGENT_COMMENT_INDIC,
'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM
NCA_ERS_HIST.ARCH_CALL_EXTD ARCH_CALL_EXTD
INNER JOIN
(
SELECT SC_ID, SC_DT , COMM_CTR_ID FROM NCA_ERS_HIST.ARCH_CALL  
WHERE  ARCH_DATE >=  TO_DATE('incr_date_arch','yyyy-mm-dd hh24:mi:ss')
UNION
SELECT  SC_ID, SC_DT , COMM_CTR_ID FROM NCA_ERS_HIST.SC_CALL_COMMENT SC 
WHERE  SC_COMM_ADD_TM >=  TO_DATE('incr_date_arch','yyyy-mm-dd hh24:mi:ss')
UNION 
SELECT  cast(KEY3_DA AS number)   AS SC_ID,TO_DATE(TRANSLATE(TRIM(KEY2_DA),chr(47),'-'),'mm-dd-yyyy hh24:mi:ss' ) AS SC_DT , KEY1_DA AS COMM_CTR_ID 
FROM NCA_APD.D2K_AUDIT 
WHERE   KEY1_DA =  '005' AND  TIMESTAMP_DT >=   TO_DATE('incr_date_arch','yyyy-mm-dd hh24:mi:ss') 
AND KEY3_DA IS NOT NULL AND trim(KEY3_DA) NOT IN ('0','1','2','3','4','5','6','7','8','9')
AND trim(KEY3_DA) NOT IN (0,1,2,3,4,5,6,7,8,9)
) CDC
ON ARCH_CALL_EXTD.SC_ID=CDC.SC_ID AND ARCH_CALL_EXTD.COMM_CTR_ID=CDC.COMM_CTR_ID AND ARCH_CALL_EXTD.SC_DT=CDC.SC_DT
