INSERT INTO CUSTOMER_PRODUCT.ERS_SERVICE_PROVIDED
(COMMUNICATION_CENTER_ID,
SC_DT,
SC_ID,
SERVICE_PROVIDED_ID,
SERVICE_PROVIDED_TOTAL_COST,
SERVICE_ITEM_CD,
ETL_JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATE_DT,
UPDATE_DT,
CREATE_BY)
SELECT
COMM_CTR_ID,
SC_DT,
  SC_ID,
  SVCP_ID,
  SVCP_TOT_COST,
  SVCP_CD,
  NULL,
  '',
  CURRENT_DATE(),
  CURRENT_DATE(),
  ''
FROM
     OPERATIONAL.ERS_STAGE_SERVICE_PROVIDED WHERE SC_DT>'2018-01-12'