SELECT
  TO_CHAR(SERVICE_PROVIDED.SVCP_ID) SVCP_ID,
  TO_CHAR(SERVICE_PROVIDED.COMM_CTR_ID) COMM_CTR_ID,
  TO_CHAR (SERVICE_PROVIDED.SC_DT,
    'YYYY-MM-DD HH24:MI:SS') SC_DT,
  TO_CHAR(SERVICE_PROVIDED.SC_ID) SC_ID,
  TO_CHAR(SERVICE_PROVIDED.SVCP_PAY_ID) SVCP_PAY_ID,
  TO_CHAR(SERVICE_PROVIDED.SVCP_CD) SVCP_CD,
  TO_CHAR(SERVICE_PROVIDED.SVCP_UNITS) SVCP_UNITS,
  TO_CHAR(SERVICE_PROVIDED.SVCP_UNIT_COST) SVCP_UNIT_COST,
  TO_CHAR(SERVICE_PROVIDED.SVCP_UOM_CD) SVCP_UOM_CD,
  TO_CHAR(SERVICE_PROVIDED.SVCP_ADD_CHRG) SVCP_ADD_CHRG,
  TO_CHAR(SERVICE_PROVIDED.SVCP_BASIC_COST) SVCP_BASIC_COST,
  TO_CHAR(SERVICE_PROVIDED.SVCP_OTHER_COST) SVCP_OTHER_COST,
  TO_CHAR(SERVICE_PROVIDED.SVCP_PLUS_COST) SVCP_PLUS_COST,
  TO_CHAR(SERVICE_PROVIDED.SVCP_ADJ_COST) SVCP_ADJ_COST,
  TO_CHAR(SERVICE_PROVIDED.SVCP_TOT_COST) SVCP_TOT_COST,
  TO_CHAR(SERVICE_PROVIDED.SVCP_DISP_APP) SVCP_DISP_APP,
  TO_CHAR(SERVICE_PROVIDED.EMPLE_ID) EMPLE_ID,
  TO_CHAR(SERVICE_PROVIDED.SVCP_DISP_PRICE) SVCP_DISP_PRICE,
  TO_CHAR(SERVICE_PROVIDED.SVCP_TIER_STATUS) SVCP_TIER_STATUS,
  TO_CHAR(SERVICE_PROVIDED.SVCP_RATEC_CD) SVCP_RATEC_CD,
  TO_CHAR(SERVICE_PROVIDED.SVCP_TOD_CD) SVCP_TOD_CD,
  TO_CHAR(SERVICE_PROVIDED.SC_PROB_CD) SC_PROB_CD,
  TO_CHAR(SERVICE_PROVIDED.EXCEPT_FLAG) EXCEPT_FLAG,
  TO_CHAR(SERVICE_PROVIDED.SVCP_PLUSRV_COST) SVCP_PLUSRV_COST,
  TO_CHAR(SERVICE_PROVIDED.SVCP_TAX1) SVCP_TAX1,
  TO_CHAR(SERVICE_PROVIDED.SVCP_TAX2) SVCP_TAX2,
  TO_CHAR(SERVICE_PROVIDED.SVCP_PREM_COST) SVCP_PREM_COST,
  TO_CHAR(SERVICE_PROVIDED.SVCP_PRRV_COST) SVCP_PRRV_COST,
  'jobrunid' AS JOB_RUN_ID,
  'jobname' AS CREATED_BY,
  'ers' AS SOURCE_SYSTEM_CD
FROM
  NCA_ERS_HIST.SERVICE_PROVIDED SERVICE_PROVIDED
INNER JOIN (
  SELECT
    SC_ID,
    SC_DT,
    COMM_CTR_ID
  FROM
    NCA_ERS_HIST.ARCH_CALL
  WHERE
    (ARCH_DATE >= TO_DATE('incr_date_arch',
        'yyyy-mm-dd hh24:mi:ss')
      OR SC_DT >= sysdate - 61) UNION
  SELECT
    SC_ID,
    SC_DT,
    COMM_CTR_ID
  FROM
    NCA_ERS_HIST.SC_CALL_COMMENT SC
  WHERE
    SC_COMM_ADD_TM >= TO_DATE('incr_date_arch',
      'yyyy-mm-dd hh24:mi:ss') UNION
  SELECT
    CAST(KEY3_DA AS number) AS SC_ID,
    TO_DATE(TRANSLATE(TRIM(KEY2_DA),
        chr(47),
        '-'),
      'mm-dd-yyyy hh24:mi:ss' ) AS SC_DT,
    KEY1_DA AS COMM_CTR_ID
  FROM
    NCA_APD.D2K_AUDIT
  WHERE
    KEY1_DA = '005'
    AND TIMESTAMP_DT >= TO_DATE('incr_date_arch',
      'yyyy-mm-dd hh24:mi:ss')
    AND KEY3_DA IS NOT NULL
    AND TRIM(KEY3_DA) NOT IN ('0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9')AND TRIM(KEY3_DA) NOT IN (0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9)) CDC
ON
  SERVICE_PROVIDED.SC_ID=CDC.SC_ID
  AND SERVICE_PROVIDED.COMM_CTR_ID=CDC.COMM_CTR_ID
  AND SERVICE_PROVIDED.SC_DT=CDC.SC_DT