INSERT INTO LANDING.WORK_ERS_CALL_VEHICLE_DIM
SELECT  
SAFE_CAST(M.CUSTOMER_MDM_KEY AS STRING),
M.MEMBER_NUM,
C.COMM_CTR_ID,
SAFE_CAST(EXTRACT (DATE FROM C.SC_DT) AS STRING),
SAFE_CAST(C.SC_ID AS STRING),
SC_CALL_CLB_CD,
C.SC_VEH_LIC_ST_CD,
C.SC_VEH_LIC_TAG_NR,
C.SC_VEH_MANF_YR_DT,
C.SC_VEH_MANFR_NM,
C.SC_VEH_MDL_NM,
C.SC_VEH_COLR_NM,
V.SC_VEH_UNSN_CHNG,
V.FLATBED_INDIC,
V.FOUR_WHEEL_DRIVE,
V.REC_VEHICLE,
V.AWD_VEHICLE,
V.MCYCLE_INDIC,
V.VEHICLE_ID,
V.BASE_VEHICLE_ID,
V.VEH_TYPE,
V.TWO_WHEEL_DRIVE,
V.SC_VEH_TRM,
SAFE_CAST(ARCH_DATETIME AS STRING),
SAFE_CAST(CURRENT_DATETIME() AS STRING)
FROM OPERATIONAL.ERS_STAGE_ARCH_CALL C
JOIN OPERATIONAL.ERS_STAGE_CAD_SVC_VEHICLE V ON C.SC_DT = V.SC_DT AND C.SC_ID = V.SC_ID
LEFT JOIN  CUSTOMERS.CONNECTSUITE_MEMBER M ON  SC_CALL_MBR_ID = M.MEMBERSHIP_NUM AND  SC_CALL_ASC_ID = SAFE_CAST(M.ASSOCIATE_ID AS STRING)
WHERE EXTRACT(DATE FROM C.LAST_UPDATE_DTTIME) > (SELECT MAX(EXTRACT(DATE FROM LAST_UPDATE_DTTIME)) FROM CUSTOMER_PRODUCT.ERS_CALL_VEHICLE_DIM)
