INSERT INTO `aaa-mwg-ersprod.MWGRoadService.SERVICE_TRUCK_HIST`(SC_FACILITY_ID
,TRUCK_DRIVER_ID
,SC_TRUCK_ID
,TRUCK_TYPE_CD
,SERVICE_VEHICLE_LATITUDE
,SERVICE_VEHICLE_LONGITUDE
,TRUCK_STATUS_DTTIME
,GPS_UPDATE_DTTIME
,TRUCK_DRIVER_STATUS_CD
,ETL_JOB_RUN_ID
,SOURCE_SYSTEM_CD
,CREATE_DTTIME
,CREATE_BY)
SELECT SC_FACILITY_ID
,TRUCK_DRIVER_ID
,SC_TRUCK_ID
,TRUCK_TYPE_CD
,SERVICE_VEHICLE_LATITUDE
,SERVICE_VEHICLE_LONGITUDE
,TRUCK_STATUS_DTTIME
,GPS_UPDATE_DTTIME
,TRUCK_DRIVER_STATUS_CD
,ETL_JOB_RUN_ID
,SOURCE_SYSTEM_CD
,CREATE_DTTIME
,CREATE_BY
FROM  `aaa-mwg-ersprod.MWGRoadService.SERVICE_TRUCK`
WHERE DATE(CREATE_DTTIME) = DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY);