-- UPDATE(MERGE)

--MERGE <target_table> [AS TARGET]
--USING <table_source> [AS SOURCE]
--ON <search_condition>
--[WHEN MATCHED 
--THEN <merge_matched> ]
--[WHEN NOT MATCHED [BY TARGET]
--THEN <merge_not_matched> ]
--[WHEN NOT MATCHED BY SOURCE
--THEN <merge_matched> ];
  
--ERS_STAGE_SC_STATUS
--WORK_ERS_STG_SC_STATUS
MERGE OPERATIONAL.ERS_STAGE_SC_STATUS AS TGT
USING LANDING.WORK_ERS_STG_SC_STATUS AS SRC
ON TGT.COMM_CTR_ID = SRC.COMM_CTR_ID AND
TGT.SC_DT = SAFE_CAST(SRC.SC_DT AS DATETIME) AND
TGT.SC_ID = SAFE_CAST(SRC.SC_ID AS INT64) AND
TGT.SC_STS_TM = SAFE_CAST(SRC.SC_STS_TM AS DATETIME) AND
TGT.SC_STS_UPD_CD = SRC.SC_STS_UPD_CD
WHEN MATCHED
THEN UPDATE SET
TGT.SC_STS_TM = SAFE_CAST(SRC.SC_STS_TM AS DATETIME) , 
TGT.SC_STS_CD = SRC.SC_STS_CD , 
TGT.SC_STS_UPD_CD = SRC.SC_STS_UPD_CD , 
TGT.SC_STS_RSN_CD = SRC.SC_STS_RSN_CD , 
TGT.SC_FACL_ID = SRC.SC_FACL_ID , 
TGT.SC_TRK_ID = SRC.SC_TRK_ID , 
TGT.SC_STS_SRC_CD = SRC.SC_STS_SRC_CD , 
TGT.SC_STS_TRK_NEW_ETA = SRC.SC_STS_TRK_NEW_ETA , 
TGT.EMPLE_ID = SRC.EMPLE_ID , 
TGT.AVL_ETA = SAFE_CAST(SRC.AVL_ETA AS INT64) , 
TGT.EMPLE_LOCATION = SRC.EMPLE_LOCATION , 
TGT.EMPLE_ROLE = SRC.EMPLE_ROLE , 
TGT.ETL_JOB_RUN_ID = SAFE_CAST(SRC.JOB_RUN_ID AS INT64) , 
TGT.SOURCE_SYSTEM_CD = SRC.SOURCE_SYSTEM_CD ,  
TGT.CREATE_DTTIME = current_datetime() ,
TGT.CREATE_BY = SRC.CREATED_BY 

WHEN NOT MATCHED THEN INSERT 
(
COMM_CTR_ID , 
SC_DT , 
SC_ID , 
SC_STS_TM , 
SC_STS_CD , 
SC_STS_UPD_CD , 
SC_STS_RSN_CD , 
SC_FACL_ID , 
SC_TRK_ID , 
SC_STS_SRC_CD , 
SC_STS_TRK_NEW_ETA , 
EMPLE_ID , 
AVL_ETA , 
EMPLE_LOCATION , 
EMPLE_ROLE , 
ETL_JOB_RUN_ID , 
SOURCE_SYSTEM_CD , 
CREATE_DTTIME , 
CREATE_BY )

VALUES

(
SRC.COMM_CTR_ID , 
SAFE_CAST(SRC.SC_DT AS DATETIME) , 
SAFE_CAST(SRC.SC_ID AS INT64) , 
SAFE_CAST(SRC.SC_STS_TM AS DATETIME) , 
SRC.SC_STS_CD , 
SRC.SC_STS_UPD_CD , 
SRC.SC_STS_RSN_CD , 
SRC.SC_FACL_ID , 
SRC.SC_TRK_ID , 
SRC.SC_STS_SRC_CD , 
SRC.SC_STS_TRK_NEW_ETA , 
SRC.EMPLE_ID , 
SAFE_CAST(SRC.AVL_ETA AS INT64), 
SRC.EMPLE_LOCATION , 
SRC.EMPLE_ROLE , 
SAFE_CAST(SRC.JOB_RUN_ID AS INT64), 
SRC.SOURCE_SYSTEM_CD , 
current_datetime(),
SRC.CREATED_BY )