SELECT PAYMENT.PAY_ID, PAYMENT.CHK_ID, PAYMENT.CLB_CD, PAYMENT.MBR_ID, PAYMENT.ASSOC_MBR_ID, 
TO_CHAR (PAYMENT.PAY_DATE,'YYYY-MM-DD HH24:MI:SS') AS PAY_DATE,
PAYMENT.PAY_TYPE, PAYMENT.CHECK_STUB_CD, PAYMENT.FACIL_INT_ID, PAYMENT.PAY_METHOD, PAYMENT.PAY_AMOUNT, 
TO_CHAR (PAYMENT.PAY_PERIOD_START, 'YYYY-MM-DD HH24:MI:SS') AS PAY_PERIOD_START,
TO_CHAR (PAYMENT.PAY_PERIOD_END, 'YYYY-MM-DD HH24:MI:SS') AS PAY_PERIOD_END,
PAYMENT.PAY_EIN, PAYMENT.PAID_IND, PAYMENT.TRANS_NUM, PAYMENT.PAY_BASIC, PAYMENT.PAY_PLUS, PAYMENT.PAY_DEBIT_ADJ, PAYMENT.PAY_RBASIC, PAYMENT.PAY_RPLUS, PAYMENT.PAY_PLUSRV, PAYMENT.PAY_TAX1, PAYMENT.PAY_TAX2, PAYMENT.PAY_CREDIT_ADJ, PAYMENT.PAY_PREM, PAYMENT.PAY_PRRV, PAYMENT.PAY_RPREM, PAYMENT.PAY_RPRRV, PAYMENT.PAY_OTHER
,'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM
NCA_APD.PAYMENT PAYMENT
WHERE EXTRACT(YEAR FROM PAY_DATE) = v_incr_date;