SELECT SC_STATUS.COMM_CTR_ID, 
TO_CHAR(SC_STATUS.SC_DT,'YYYY-MM-DD HH24:MI:SS') SC_DT, 
SC_STATUS.SC_ID,
TO_CHAR(SC_STATUS.SC_STS_TM , 'YYYY-MM-DD HH24:MI:SS') SC_STS_TM, 
SC_STATUS.SC_STS_CD,
SC_STATUS.SC_STS_UPD_CD,
SC_STATUS.SC_STS_RSN_CD,
SC_STATUS.SC_FACL_ID,
SC_STATUS.SC_TRK_ID,
SC_STATUS.SC_STS_SRC_CD, 
SC_STATUS.SC_STS_TRK_NEW_ETA, 
SC_STATUS.EMPLE_ID,
SC_STATUS.AVL_ETA,
SC_STATUS.EMPLE_LOCATION,
SC_STATUS.EMPLE_ROLE,
'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM
 NCA_ERS_HIST.SC_STATUS SC_STATUS
WHERE EXTRACT(YEAR FROM SC_DT) = v_incr_date AND rownum <= 5