SELECT SERVICE_PROVIDED.SVCP_ID, SERVICE_PROVIDED.COMM_CTR_ID, 
TO_CHAR (SERVICE_PROVIDED.SC_DT,'YYYY-MM-DD HH24:MI:SS') AS SC_DT
SERVICE_PROVIDED.SC_ID, SERVICE_PROVIDED.SVCP_PAY_ID, SERVICE_PROVIDED.SVCP_CD, SERVICE_PROVIDED.SVCP_UNITS, SERVICE_PROVIDED.SVCP_UNIT_COST, SERVICE_PROVIDED.SVCP_UOM_CD, SERVICE_PROVIDED.SVCP_ADD_CHRG, SERVICE_PROVIDED.SVCP_BASIC_COST, SERVICE_PROVIDED.SVCP_OTHER_COST, SERVICE_PROVIDED.SVCP_PLUS_COST, SERVICE_PROVIDED.SVCP_ADJ_COST, SERVICE_PROVIDED.SVCP_TOT_COST, SERVICE_PROVIDED.SVCP_DISP_APP, SERVICE_PROVIDED.EMPLE_ID, SERVICE_PROVIDED.SVCP_DISP_PRICE, SERVICE_PROVIDED.SVCP_TIER_STATUS, SERVICE_PROVIDED.SVCP_RATEC_CD, SERVICE_PROVIDED.SVCP_TOD_CD, SERVICE_PROVIDED.SC_PROB_CD, SERVICE_PROVIDED.EXCEPT_FLAG, SERVICE_PROVIDED.SVCP_PLUSRV_COST, SERVICE_PROVIDED.SVCP_TAX1, SERVICE_PROVIDED.SVCP_TAX2, SERVICE_PROVIDED.SVCP_PREM_COST, SERVICE_PROVIDED.SVCP_PRRV_COST
,'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM
 NCA_ERS_HIST.SERVICE_PROVIDED SERVICE_PROVIDED
WHERE 
EXTRACT(YEAR FROM SC_DT) = v_incr_date;