UPDATE
OPERATIONAL.ERS_STAGE_SERVICE_PROVIDED AS TGT
SET
TGT.DELETE_FLG = 'Y'
WHERE
NOT EXISTS (
SELECT
1
FROM
LANDING.WORK_ERS_STG_SERVICE_PROVIDED  SRC
WHERE
TGT.SVCP_ID = SAFE_CAST(SRC.SVCP_ID AS INT64))
AND 
EXISTS (
SELECT
1
FROM
LANDING.WORK_ERS_STG_ARCH_CALL  SRC
WHERE
TGT.COMM_CTR_ID = SRC.COMM_CTR_ID
AND TGT.SC_DT = SAFE_CAST(SRC.SC_DT AS DATETIME)
AND TGT.SC_ID = SAFE_CAST(SRC.SC_ID AS INT64))