SELECT SERVICE_FACILITY.FACIL_INT_ID, SERVICE_FACILITY.SVC_FACL_ID, SERVICE_FACILITY.SVC_FACL_BSC_AD, SERVICE_FACILITY.SVC_FACL_CTY_NM, SERVICE_FACILITY.SVC_FACL_D_S_E_TM, SERVICE_FACILITY.SVC_FACL_NM, SERVICE_FACILITY.SVC_FACL_ST_CD, SERVICE_FACILITY.SVC_FACL_STS_CD, SERVICE_FACILITY.SVC_FACL_SUPL_AD, SERVICE_FACILITY.SVC_FACL_ZIP_CD, SERVICE_FACILITY.SVC_FACL_FUNC_CD, SERVICE_FACILITY.SVC_FACL_REP_ID, SERVICE_FACILITY.SVC_FACL_FED_ID, SERVICE_FACILITY.SVC_FACL_ID_FLAG, SERVICE_FACILITY.SVC_FACL_DIR_DEP, 
TO_CHAR (SERVICE_FACILITY.SVC_FACL_START_DT,'YYYY-MM-DD HH24:MI:SS') AS SVC_FACL_START_DT,
SERVICE_FACILITY.SVC_FACL_ROUTE_NR, SERVICE_FACILITY.SVC_FACL_ACCT_NR, 
TO_CHAR (SERVICE_FACILITY.SVC_FACL_INACT_DT,'YYYY-MM-DD HH24:MI:SS') AS SVC_FACL_INACT_DT,
TO_CHAR (SERVICE_FACILITY.SVC_FACL_INS_EXP,'YYYY-MM-DD HH24:MI:SS') AS SVC_FACL_INS_EXP,
SERVICE_FACILITY.DONT_PRICE, SERVICE_FACILITY.COMM_CTR_ID, SERVICE_FACILITY.TAX_FLAG, SERVICE_FACILITY.SVC_FACL_BONUS_AMT, SERVICE_FACILITY.SVC_FACL_REC_BON, 
TO_CHAR (SERVICE_FACILITY.SVC_FACL_FED_START,'YYYY-MM-DD HH24:MI:SS') AS SVC_FACL_FED_START,
SERVICE_FACILITY.SVC_FACL_CONTACT, SERVICE_FACILITY.SUSPEND_STMT_FLAG, SERVICE_FACILITY.AUTO_SUSPEND_FLAG, SERVICE_FACILITY.SVC_FACL_PST_ID, 
TO_CHAR (SERVICE_FACILITY.SVC_FACL_PST_START,'YYYY-MM-DD HH24:MI:SS') AS SVC_FACL_PST_START,
SERVICE_FACILITY.DAILY_BALANCING, SERVICE_FACILITY.SVC_FACL_TYPE, SERVICE_FACILITY.SVC_FACL_TYPE2, SERVICE_FACILITY.SVC_FACL_EMAIL, SERVICE_FACILITY.ELECTRONIC_STMT_FLAG, SERVICE_FACILITY.CLUB_CONTRACT_FLAG, SERVICE_FACILITY.CALC_TOW_MILE_FLAG, SERVICE_FACILITY.CALC_ENROUTE_MILE_FLAG, SERVICE_FACILITY.TRUCK_ER_FLAG
,'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM
 NCA_ERS_HIST.SERVICE_FACILITY SERVICE_FACILITY