SELECT SERVICE_TRUCK.SVC_FACL_ID, SERVICE_TRUCK.TRK_ID, SERVICE_TRUCK.TRK_DRIVR_ID, SERVICE_TRUCK.TRK_CMNCT_TYP_CD, 
TO_CHAR (SERVICE_TRUCK.TRK_EST_AVAIL_TM,'YYYY-MM-DD HH24:MI:SS') AS TRK_EST_AVAIL_TM,
TO_CHAR (SERVICE_TRUCK.TRK_DRIVR_S_END_TM,'YYYY-MM-DD HH24:MI:SS') AS TRK_DRIVR_S_END_TM,
SERVICE_TRUCK.TRK_TERM, SERVICE_TRUCK.TRK_NETWORK, SERVICE_TRUCK.TRK_MDT_ID, SERVICE_TRUCK.TRK_STS_CD, SERVICE_TRUCK.TRK_DRIVR_STS_CD, 
TO_CHAR (SERVICE_TRUCK.TRK_STS_TM,'YYYY-MM-DD HH24:MI:SS') AS TRK_STS_TM,
TO_CHAR (SERVICE_TRUCK.STATUS_CHG_TIME,'YYYY-MM-DD HH24:MI:SS') AS STATUS_CHG_TIME,
SERVICE_TRUCK.TRK_TYP_CD, SERVICE_TRUCK.TRK_COMM_TX, SERVICE_TRUCK.TRK_GRID_CD, SERVICE_TRUCK.TRANSACT, SERVICE_TRUCK.CHANNEL, SERVICE_TRUCK.TRK_VHBROAD_1, SERVICE_TRUCK.TRK_VHBROAD_2, SERVICE_TRUCK.TRK_VHBROAD_3, SERVICE_TRUCK.TRK_ZONE, SERVICE_TRUCK.LAT, SERVICE_TRUCK.LONGX, SERVICE_TRUCK.ALTITUDE, SERVICE_TRUCK.SPEED, SERVICE_TRUCK.DIRECTION, SERVICE_TRUCK.TRK_PRIORITY, SERVICE_TRUCK.TRK_MAIN_SPOT_TYPE, SERVICE_TRUCK.TRK_2ND_SPOT_TYPE, SERVICE_TRUCK.TRK_3RD_SPOT_TYPE, SERVICE_TRUCK.FLEET_INDIC, SERVICE_TRUCK.TRK_STATUS_COMMENT, SERVICE_TRUCK.TRK_RV_INDIC, SERVICE_TRUCK.TRK_RV_CLASS, SERVICE_TRUCK.MOTORCYCLE_INDIC, SERVICE_TRUCK.BATTERY_INDIC, SERVICE_TRUCK.MDT_STS_CD, SERVICE_TRUCK.TRK_UNAVAIL_MINS, 
TO_CHAR (SERVICE_TRUCK.DRV_CHG_TIMESTAMP,'YYYY-MM-DD HH24:MI:SS') AS DRV_CHG_TIMESTAMP,
SERVICE_TRUCK.POS_ASSOC_CODE, SERVICE_TRUCK.POS_CLB_CODE, SERVICE_TRUCK.POS_OFC_ID, SERVICE_TRUCK.POS_USER, SERVICE_TRUCK.POS_PASSWORD, SERVICE_TRUCK.POS_LOCATION_CODE, SERVICE_TRUCK.TECH_LEVEL, SERVICE_TRUCK.SAFE_DRIVING_ON, SERVICE_TRUCK.ONBOARD_PRINTER_INDIC, SERVICE_TRUCK.LAST_UPDT_TS 
,'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM
 NCA_CAD.SERVICE_TRUCK SERVICE_TRUCK