SELECT 
TO_CHAR (STAT_GRP.START_DTM,'YYYY-MM-DD HH24:MI:SS') AS START_DTM,
TO_CHAR (STAT_GRP.END_DTM,'YYYY-MM-DD HH24:MI:SS') AS END_DTM,
STAT_GRP.GROUP_ID, STAT_GRP.FACIL_INT_ID, STAT_GRP.CATEGORY, STAT_GRP.ACCT, STAT_GRP.ACCT_NAME, STAT_GRP.NUM_CALLS, STAT_GRP.AMOUNT, STAT_GRP.CPC, STAT_GRP.F1099 
,,'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM
 NCA_APD.STAT_GRP STAT_GRP WHERE EXTRACT(YEAR FROM START_DTM) = v_incr_date