SELECT SVC_FAC_DBA.FACIL_INT_ID, SVC_FAC_DBA.SVCF_DBA_NM, SVC_FAC_DBA.SVC_FACL_FED_ID, SVC_FAC_DBA.SVCF_BSC_AD, SVC_FAC_DBA.SVCF_SUPL_AD, SVC_FAC_DBA.SVCF_CTY_NM, SVC_FAC_DBA.SVCF_ST_CD, SVC_FAC_DBA.SVCF_ZIP_CD, SVC_FAC_DBA.VENDOR_ID, SVC_FAC_DBA.SVCF_OWNER_NM
,'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM
 NCA_APD.SVC_FAC_DBA SVC_FAC_DBA