delete FROM `LANDING.WORK_ERS_STG_APD_REIMBURSEMENT` where true;
delete FROM `LANDING.WORK_ERS_STG_HIST_CALL_ADJ` where true;
delete FROM `LANDING.WORK_ERS_STG_CAD_TRUCK_SESSION_STATS` where true;
delete FROM `LANDING.WORK_ERS_STG_CAD_SERVICE_FACILITY` where true;
delete FROM `LANDING.WORK_ERS_STG_CAD_SC_CALL_COMMENT` where true;
delete FROM `LANDING.WORK_ERS_STG_MILEAGE_HIST` where true