SELECT TRUCK_GPS_HIST.SVC_FACL_ID, TRUCK_GPS_HIST.TRK_ID, TRUCK_GPS_HIST.TRK_DRIVR_ID, TRUCK_GPS_HIST.NEW_LAT, TRUCK_GPS_HIST.NEW_LONG, 
TO_CHAR (TRUCK_GPS_HIST.UPDAT_DT,'YYYY-MM-DD HH24:MI:SS') AS UPDAT_DT,
TRUCK_GPS_HIST.TRK_STS_CD, TRUCK_GPS_HIST.TRK_DRIVR_STS_CD, TRUCK_GPS_HIST.SPEED, TRUCK_GPS_HIST.CHECK_ENGINE ,
'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM
 NCA_ERS_HIST.TRUCK_GPS_HIST TRUCK_GPS_HIST