CREATE OR REPLACE TABLE `aaa-mwg-ersbackofficedev.OPERATIONAL.ERS_STAGE_CAD_SC_CALL_COMMENT` AS
SELECT * FROM `aaa-mwg-dwprod.OPERATIONAL.ERS_STAGE_CAD_SC_CALL_COMMENT` WHERE 
SC_DT > DATETIME_SUB(CURRENT_DATETIME(), INTERVAL 100 DAY)