CREATE OR REPLACE TABLE `aaa-mwg-ersbackofficeprod.OPERATIONAL.ERS_STAGE_HIST_DUP_CALL_LST` AS
SELECT * FROM `aaa-mwg-dwprod.OPERATIONAL.ERS_STAGE_HIST_DUP_CALL_LST` WHERE 
ORG_SC_DT > DATETIME_SUB(CURRENT_DATETIME(), INTERVAL 100 DAY) 