DELETE FROM LANDING.WORK_INDIVIDUAL_0 WHERE TRUE;
DELETE FROM LANDING.WORK_INDIVIDUAL_1 WHERE TRUE;
DELETE FROM LANDING.WORK_INDIVIDUAL_2 WHERE TRUE;
DELETE FROM LANDING.WORK_INDIVIDUAL_3 WHERE TRUE;
DELETE FROM LANDING.WORK_INDIVIDUAL_4 WHERE TRUE;
DELETE FROM LANDING.WORK_INDIVIDUAL_MD5 WHERE TRUE
