  --Audit sql to be put here
UPDATE LANDING.STAGE_MEMBERSHIP_BILL SET EXCEPTION_FLAG='Y',FILE_GENERATED = 'E',
EXCEPTION_REASON=case when EXCEPTION_REASON is null then 'Member Number is missing' ELSE CONCAT(EXCEPTION_REASON,',','Member Number is missing') END
WHERE MEMBER_NUM is null and CAST(CREATE_DTTIME AS DATE)=CURRENT_DATE() AND EVENT_TYPE='BILL1';