select 
CSB.BILL_KY as MEMBERSHIP_BILL_ID,
MEM.MEMBER_KEY,
CREDIT.MEMBERSHIP_KEY,
CASE WHEN CSB.BILL_STMT_NR = 1 THEN 'BILL1' 
     WHEN CSB.BILL_STMT_NR = 2 THEN 'BILL2'
     WHEN CSB.BILL_STMT_NR = 3 THEN 'BILL3'
       END  AS EVENT_TYPE,
CONCAT('PCS_',CAST(CSB.BILL_KY AS STRING),CAST(CSB.BILL_STMT_NR AS STRING))  AS STATEMENT_NO,
MEM.MEMBER_NUM, 
MEM.ASSOCIATE_ID AS MEMBER_SEQUENCE_NUM,
MEM.MEMBER_SINCE,
CAST (CSB.MBRS_EXPIR_DT AS DATE) as MBRS_EXPIR_DT,
NAME_ON_MEMBERSHIP_CARD,
CAST(CREDIT.BILL_PAY_METHOD AS STRING) AS BILL_PAY_METHOD,
FIRST_NAME, 
MIDDLE_INITIAL, 
LAST_NAME,
CONCAT(UPPER(SUBSTR(TRIM(PRM_BILLING_ADDRESS_LINE1), 1, 1)), LOWER(SUBSTR(TRIM(PRM_BILLING_ADDRESS_LINE1), 2)))  AS BILLING_ADDRESS_LINE1,
CONCAT(UPPER(SUBSTR(TRIM(PRM_BILLING_CITY), 1, 1)), LOWER(SUBSTR(TRIM(PRM_BILLING_CITY), 2))) AS BILLING_CITY,
PRM_BILLING_STATE AS BILLING_STATE,
PRM_BILLING_ZIP AS BILLING_ZIP,
'US' AS COUNTRY,
null as TOT_NUM_MEMBER,
CSB.bill_proc_dt AS BILL_DATE,
CSB.BILL_STMT_NR as BILL_LINE_NO, 
UPPER(CREDIT.MEMBERSHIP_LEVEL_DESC) AS MEMBERSHIP_LEVEL_DESC,
CSB.MEMBER_BILL_AMT AS BILL_AMT, 
	CASE WHEN (MEM.ASSOCIATE_ID=1 and CREDIT.MBRS_TYPE='Y') THEN 1 ELSE NULL end AS NI_BILL_ID,
	CSB.BILL_PROC_DT AS NI_BILL_DATE,
CASE WHEN (MEM.ASSOCIATE_ID=1 and CREDIT.MBRS_TYPE='Y') THEN 1 ELSE NULL end AS NI_BILL_LINE_NO, 
	CASE WHEN (MEM.ASSOCIATE_ID=1 and CREDIT.MBRS_TYPE='Y') THEN 'Membership Credit' 
	     ELSE NULL END as NI_BILL_DESC, 
	CASE WHEN (MEM.ASSOCIATE_ID=1 and CREDIT.MBRS_TYPE='Y') THEN  -1 * CREDIT.CREDIT_BILL_AMT ELSE 0 END AS NI_ARIA_BILL_AMT,	
	CASE WHEN (MEM.ASSOCIATE_ID=1 and CREDIT.MBRS_TYPE='Y') THEN  'Y' ELSE 'N' END AS NON_INV_ITEM_PRESENT, 
	CASE WHEN (MEM.ASSOCIATE_ID=1 and CREDIT.MBRS_TYPE='Y') THEN  '1' ELSE '0' END AS NON_INV_ITEMS, 
	0 AS ADDITIONAL_AMT, 
  0 AS ADDITIONAL_PAY_RECV,
  CASE WHEN EMPLOYEE_IND = 'Y' THEN 'AAA Club Employee' ELSE NULL END AS GROUP_TYPE, 
CASE WHEN MEM.ASSOCIATE_ID=1 THEN IFNULL(CREDIT.TOTAL_BILL_AMT, 0) ELSE 0 END AS TOTAL_AMT_DUE, 
	CAST(CSB.MBRS_EXPIR_DT AS DATE) as PAYMENT_DUE_DATE,
	0 AS PAYMENT_RECEIVED, 
	CASE WHEN MEM.ASSOCIATE_ID=1 THEN IFNULL(CREDIT.TOTAL_BILL_AMT, 0) ELSE 0 END AS TOTAL_RENEWAL_DUE,     
CREDIT.MEMBERSHIP_LEVEL,
'' as MEMBER_ROLE_CD,
MEM.SOURCE_SYSTEM_CD,
	CSB.LAST_UPDATE_DT,
  CSB.BILL_KY AS BILL_KY,
SECONDARY_MEMBER_IND AS SEC_MEMBER_DATA_PRESENT,
COUNT(CASE WHEN MEM.ASSOCIATE_ID>2 THEN 1 ELSE NULL END) OVER (PARTITION BY CSB.BILL_KY,CSB.MBRS_KY) AS 
NUM_ASSOC_MEMBER,
COUNT(CASE WHEN MEM.ASSOCIATE_ID>1 THEN 1 ELSE NULL END) OVER (PARTITION BY CSB.BILL_KY,CSB.MBRS_KY) AS 
TOTAL_DEPENDENT_MEMBER,
'N' AS DONOR_MEMBER_DATA_PRESENT,
'N' AS GROUP_DATA_PRESENT,
CREDIT_CARD_LAST_4_DIGITS AS CC_LAST_4_DIGITS,
NO_OF_ASSOCIATES_CNT,
CREDIT.PLUS_UPGRADE_AMT,
CREDIT.PREMIER_UPGRADE_AMT,
CREDIT.ASSOCIATE_CHARGE_AMT,
'' AS DONOR_FIRST_NAME,
'' AS DONOR_MI,
'' AS DONOR_LAST_NAME,
CURRENTLY_HAS_AUTO,
CURRENTLY_HAS_HOME,
'' as PRM_EMAIL_ADDRESS,
'' as PRM_HOME_PHONE_NUM,
'' as PAY_FAILED,
CASE WHEN SPRN_IND='1' then 'SPRINT' else null end  as PROMOCODE1, 
'' as PROMO1_AMOUNT,
'' as PROMOCODE2,
'' as PROMO2_AMOUNT,
'' as PROMOCODE3,
'' as PROMO3_AMOUNT,
case when NO_OF_ASSOCIATES_CNT>0 THEN 'Y' ELSE 'N' END AS ASSOC_MEMBER_DATA_PRESENT,
ISSUING_STATE,
MEM.MEMBERSHIP_LEVEL_DETAIL_DESC	 as BILL_DESC,
LANGUAGE AS PREFERRED_LANGUAGE 
from
(SELECT MB.MBRS_KY AS MBRS_KY,
			 MBD.MBR_KY AS MBR_KY,
			 MB.BILL_KY AS BILL_KY, 
			 MB.BILL_PROC_DT AS BILL_PROC_DT,
			 MB.BILL_STMT_NR AS BILL_STMT_NR,
			 MB.BILL_TYP_CD AS BILL_TYP_CD,
			 MB.BILL_AUTO_REN_IN AS BILL_AUTO_REN_IN,
			 MB.BILL_AT  AS TOTAL_BILL_AMT,
			 MB.MBRS_EXPIR_DT AS MBRS_EXPIR_DT,
       MB.LAST_UPDATE_DT AS LAST_UPDATE_DT,
       SUM(MBD.BDTL_AT) AS MEMBER_BILL_AMT			 
	  FROM OPERATIONAL.CONNECTSUITE_MBRSHIP_BILL  MB,
		   OPERATIONAL.CONNECTSUITE_MBRSHIP_BILL_DTL  MBD     
	  WHERE MB.BILL_PRNT_DT IS NULL
	  AND MB.MBRS_KY = MBD.MBRS_KY
	  AND TRIM(MB.BILL_TYP_CD) = 'R'
    AND MB.BILL_KY = MBD.BILL_KY
    AND MB.BILL_STMT_NR IN (1)
    AND MBD.BDTL_CMPT_CD NOT IN('PY','SF','UC')
    GROUP BY MB.MBRS_KY, MBD.MBR_KY, MB.BILL_KY, MB.BILL_TYP_CD, MB.BILL_AUTO_REN_IN, 
	           MB.BILL_AT, MB.BILL_PROC_DT, MB.BILL_STMT_NR, MB.MBRS_EXPIR_DT, MB.LAST_UPDATE_DT) CSB
INNER JOIN 
(select * from OPERATIONAL.CONNECTSUITE_MEMBER where STATUS_CD in ('A','P'))  MEM
ON CAST(MEM.MEMBER_KEY AS INT64)=CSB.MBR_KY
INNER JOIN
(
  SELECT
    MEMBERSHIP_NUM AS MEMBERSHIP_NUM,
    MEMBER_NUM AS PRM_MEMBER_NUM,
     ASSOCIATE_ID AS ASSOCIATE_ID,
     CONCAT(UPPER(SUBSTR(TRIM(FIRST_NM), 1, 1)), LOWER(SUBSTR(TRIM(FIRST_NM), 2))) As FIRST_NAME,
     CONCAT(UPPER(SUBSTR(TRIM(LAST_NM), 1, 1)), LOWER(SUBSTR(TRIM(LAST_NM), 2))) As LAST_NAME,
    MID_INITIAL_NM AS MIDDLE_INITIAL,
    EMAIL_ADDRESS AS PRM_EMAIL_ADDRESS,
    HOME_PHONE_NUM AS PRM_HOME_PHONE_NUM,
    CARD_NM AS NAME_ON_MEMBERSHIP_CARD,
     CASE
      WHEN CURRENT_DATE() BETWEEN TEMPORARY_ADDRESS_START_DT AND TEMPORARY_ADDRESS_END_DT THEN CONCAT(IFNULL(TEMPORARY_ADDRESS_LINE1,''),'',IFNULL(CASE
        WHEN TEMPORARY_ADDRESS_LINE2 IS NULL THEN NULL
        ELSE ', ' END,''),'',IFNULL(TEMPORARY_ADDRESS_LINE2,''))
      ELSE CONCAT(IFNULL(BILLING_ADDRESS_LINE1,''),'',IFNULL(CASE
        WHEN BILLING_ADDRESS_LINE2 IS NULL THEN NULL
        ELSE ', ' END,''),'', IFNULL(BILLING_ADDRESS_LINE2,''))
    END AS PRM_BILLING_ADDRESS_LINE1,
    CASE
      WHEN CURRENT_DATE() BETWEEN TEMPORARY_ADDRESS_START_DT AND TEMPORARY_ADDRESS_END_DT THEN TEMPORARY_CITY
      ELSE BILLING_CITY
    END AS PRM_BILLING_CITY,
    CASE
      WHEN CURRENT_DATE() BETWEEN TEMPORARY_ADDRESS_START_DT AND TEMPORARY_ADDRESS_END_DT THEN TEMPORARY_STATE
      ELSE BILLING_STATE
    END AS PRM_BILLING_STATE,
    CASE
      WHEN CURRENT_DATE() BETWEEN TEMPORARY_ADDRESS_START_DT AND TEMPORARY_ADDRESS_END_DT THEN TEMPORARY_ZIP
      ELSE BILLING_ZIP
    END AS PRM_BILLING_ZIP
  FROM
    CUSTOMERS.MEMBERSHIP_CUSTOMER_DIM AS CUST_DIM
  WHERE
    CUST_DIM.ACTIVE_FLG='Y'
        ) CUST
ON
  MEM.MEMBER_NUM = CUST.PRM_MEMBER_NUM			   
INNER JOIN 
(select MEMBERSHIP_NUM,MEMBERSHIP_KEY,MEMBERSHIP_LEVEL_DESC,MEMBERSHIP_LEVEL,PLUS_UPGRADE_AMT,PREMIER_UPGRADE_AMT,ASSOCIATE_CHARGE_AMT,
CREDIT_CARD_LAST_4_DIGITS,NO_OF_ASSOCIATES_CNT,CURRENTLY_HAS_AUTO,SECONDARY_MEMBER_IND,
CASE WHEN BILL_PAY_METHOD='Bill' THEN 0 ELSE 1 END AS BILL_PAY_METHOD,
CURRENTLY_HAS_HOME,CASE WHEN ISSUING_STATE='MONTANA' THEN 'MT'
     WHEN ISSUING_STATE='CALIFORNIA' THEN 'CA'
     WHEN ISSUING_STATE='NEVADA' THEN 'NV'
     WHEN ISSUING_STATE='ALASKA' THEN 'AK'
     WHEN ISSUING_STATE='ARIZONA' THEN 'AZ'
     WHEN ISSUING_STATE='WYOMING' THEN 'WY'
     WHEN ISSUING_STATE='UTAH' THEN 'UT'
     ELSE ISSUING_STATE END AS ISSUING_STATE,
 round((DUES_COST_AMT+DUES_ADJUSTMENT_AMT+ENTRANCE_FEE_AMT)-(CAST(TOTAL_PAYMENTS AS FLOAT64)+CAST(TOTAL_CREDITS AS FLOAT64)),2) AS TOTAL_BILL_AMT,
 CASE WHEN (CAST(TOTAL_PAYMENTS AS FLOAT64)+CAST(TOTAL_CREDITS AS FLOAT64)) <>0 THEN 'Y' ELSE 'N' end as MBRS_TYPE,
    round((CAST(TOTAL_PAYMENTS AS FLOAT64)+CAST(TOTAL_CREDITS AS FLOAT64)),2) as CREDIT_BILL_AMT  
 from OPERATIONAL.CONNECTSUITE_MEMBERSHIP) CREDIT
 ON CUST.MEMBERSHIP_NUM=CREDIT.MEMBERSHIP_NUM
