CREATE OR REPLACE TABLE   LANDING.EMPLOYEE(
CREATE_BY	STRING        ,
CREATE_DTTIME	DATETIME ,
EXT2	STRING           ,
PHONE2	STRING           ,
EMPLOYEE_NO	STRING       ,
RATE	INT64          ,
LOCATIONNO	STRING       ,
BNAME	STRING           )