CREATE OR REPLACE TABLE   LANDING.GLBUDJECT(
CREATE_BY	STRING       ,        
CREATE_DTTIME	DATETIME ,
BUDGETBALANCE	INT64    ,
LOCATION	STRING       ,
LOCATIONNO	STRING       ,
PERIODENDDATE	DATETIME  )