CREATE OR REPLACE TABLE   LANDING.HRO(
REOPENED	STRING         ,
DISCOUNTSUPPLIES	INT64   ,
DISCOUNTPARTS	INT64       ,
DISCOUNTLABOR	INT64       ,
PRIMARYTECH	STRING         ,
HOURS	INT64               ,
CLOSED	STRING             ,
WRITER	STRING             ,
MODEL	STRING             ,
MAKE	STRING             ,
YEAR	STRING             ,
SOURCE	STRING             ,
MILAGE	STRING             ,
TOTAL	INT64               ,
CHARGE	INT64               ,
CREDIT_CRD	INT64           ,
CHECKK	INT64               ,
CASH	INT64               ,
SUPPLIES	INT64           ,
TAX	INT64                   ,
RODATE	STRING             ,
STATUS	STRING             ,
CUST_NO	STRING             ,
RO_NO	STRING             ,
LOCATIONNO	STRING         ,
CREATE_BY	STRING         ,
CREATE_DTTIME	DATETIME 
)