UPDATE
  LANDING.DATA_LOAD_AUDIT A
SET
  A.TARGET_COUNT = B.TARGET_COUNT
FROM (
  SELECT
    TARGET_COUNT,
    JOB_ID
  FROM (
    SELECT
      COUNT(*) AS TARGET_COUNT,
      1 AS JOB_ID
    FROM
    CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM
     WHERE  ROW_START_DT  = DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)
    UNION ALL
    SELECT
      COUNT(*),
      2 AS JOB_ID
    FROM
      CUSTOMER_PRODUCT.CONNECTSUITE_MEMBERSHIP_DIM
     WHERE  ROW_START_DT  = DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)
    UNION ALL
    SELECT
      COUNT(*),
      3 AS JOB_ID
    FROM
      CUSTOMERS.MEMBERSHIP_CUSTOMER_DIM
      WHERE  ROW_START_DT  = DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)
    UNION ALL
    SELECT
      COUNT(*),
      4 AS JOB_ID
    FROM
      CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_TRANSACTIONS_FACT
      WHERE EXTRACT( DATE FROM UPDATE_DTTIME)  = CURRENT_DATE()
     ) ) B
WHERE
  A.JOB_ID = B.JOB_ID
  AND A.JOB_PROCESS_DTTIME = (
  SELECT
    MAX(JOB_PROCESS_DTTIME)
  FROM
    LANDING.DATA_LOAD_AUDIT)