MERGE`CUSTOMER_PRODUCT.CONNECTSUITE_NOTES` TGT
USING `LANDING.WORK_CS_NOTES` SRC
ON TGT.NOTE_ID = SAFE_CAST(SRC.NOTE_ID AS INT64)
WHEN MATCHED THEN
UPDATE SET
TGT.TABLE_NM = SRC.TABLE_NM,
TGT.PRIMARY_KEY = CAST(SRC.PRIMARY_KEY AS INT64),
TGT.USER_ID = SRC.USER_ID,
TGT.NOTE_DTTIME = PARSE_DATETIME("%Y-%m-%d %H:%M:%E*S",SRC.NOTE_DTTIME),
TGT.NOTE_TEXT = SRC.NOTE_TEXT,
TGT.JOB_RUN_ID = CAST('jobrunid' AS INT64),
TGT.LAST_UPDATE_DTTIME = CURRENT_DATETIME()

WHEN NOT MATCHED THEN INSERT 
(
NOTE_ID,
TABLE_NM,
PRIMARY_KEY,
USER_ID,
NOTE_DTTIME,
NOTE_TEXT,
JOB_RUN_ID,
SOURCE_SYSTEM_CD,
LAST_UPDATE_DTTIME,
CREATE_DTTIME )

VALUES (
CAST(SRC.NOTE_ID AS INT64),
SRC.TABLE_NM ,
CAST(SRC.PRIMARY_KEY AS INT64),
SRC.USER_ID,
PARSE_DATETIME("%Y-%m-%d %H:%M:%E*S",SRC.NOTE_DTTIME),
SRC.NOTE_TEXT,
CAST('jobrunid' AS INT64),
'SAM',
CURRENT_DATETIME(),
CURRENT_DATETIME())
