CREATE OR REPLACE TABLE `CUSTOMER_PRODUCT.CONNECTSUITE_OPPORTUNITY_TYPE` AS (
SELECT 
OPPORTUNITY_TYPE_ID AS OPPORTUNITY_TYPE_ID,
DESCRIPTION AS DESCRIPTION,
CAST(DAYS_UNTIL_DUE AS INT64) AS DAYS_UNTIL_DUE,
STATUS_DUE_CD AS STATUS_DUE_CD,
BUSINESS_LINE_CD AS BUSINESS_LINE_CD,
QUOTE_SYSTEM AS QUOTE_SYSTEM,
QUOTE_TYPE AS QUOTE_TYPE,
ROUTE_BY_ZIP AS ROUTE_BY_ZIP,
ROUTE_TO_SELECTABLE_ONLY AS ROUTE_TO_SELECTABLE_ONLY,
TRAVEL_TYPE AS TRAVEL_TYPE,
CAST('jobrunid'AS INT64) AS JOB_RUN_ID,
'SAM' AS SOURCE_SYSTEM_CD,
CURRENT_DATETIME() AS CURRENT_DATETIME
FROM `LANDING.WORK_CS_OPPORTUNITY_TYPE`)