CREATE OR REPLACE TABLE `CUSTOMER_PRODUCT.CONNECTSUITE_CAMPAIGNS` AS (
SELECT 
CAST(CAMPAIGN_ID  AS INT64) AS CAMPAIGN_ID,
NAME AS NAME,
BUSINESS_LINE_CD AS BUSINESS_LINE_CD,
CODE AS CODE,
DESCRIPTION AS DESCRIPTION,
PARSE_DATETIME("%Y-%m-%d %H:%M:%E*S",START_DT) AS START_DT,
PARSE_DATETIME("%Y-%m-%d %H:%M:%E*S",END_DT) AS END_DT,
ACTIVE AS ACTIVE,
CAST('jobrunid'AS INT64) AS JOB_RUN_ID,
'SAM' AS SOURCE_SYSTEM_CD,
CURRENT_DATETIME() AS CURRENT_DATETIME
FROM `LANDING.WORK_CS_CAMPAIGNS`)

