MERGE CUSTOMERS.SAM_CUSTOMER_ADDRESSES A
USING LANDING.WORK_SAM_CUSTOMER_ADDRESSES B
ON A.CUSTOMER_ID = SAFE_CAST(B.CUSTOMER_ID AS INT64)
WHEN MATCHED THEN
UPDATE SET
A.ADDRESS_ID= SAFE_CAST(B.ADDRESS_ID  AS INT64),
A.ADDRESS_TYPE= B.ADDRESS_TYPE,
A.ADDRESS1= B.ADDRESS1,
A.ADDRESS2= B.ADDRESS2,
A.CITY= B.CITY,
A.STATE= B.STATE,
A.ZIP= B.ZIP,
A.COUNTRY= B.COUNTRY,
A.COUNTY_NM= B.COUNTRY_NM,
A.COUNTY_CD= B.COUNTRY_CD,
A.AUDIT_DT= PARSE_DATETIME('%F %T',B.AUDIT_DT)
WHEN NOT MATCHED THEN
  INSERT (CUSTOMER_ID,
ADDRESS_ID,
ADDRESS_TYPE,
ADDRESS1,
ADDRESS2,
CITY,
STATE,
ZIP,
COUNTRY,
COUNTY_NM,
COUNTY_CD,
AUDIT_DT,
JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATE_DT,
CREATED_BY
) VALUES(
SAFE_CAST(CUSTOMER_ID AS INT64),
SAFE_CAST(ADDRESS_ID AS INT64),
ADDRESS_TYPE,
ADDRESS1,
ADDRESS2,
CITY,
STATE,
ZIP,
COUNTRY,
COUNTRY_NM,
COUNTRY_CD,
PARSE_DATETIME('%F %T',AUDIT_DT),
'jobrunid',
'SAM' ,
CURRENT_DATETIME(),
'jobname' )

