UPDATE CUSTOMERS.SAM_CUSTOMERS A
SET CUSTOMER_KEY = B.CUSTOMER_MDM_KEY 
FROM (SELECT * FROM (SELECT * ,ROW_NUMBER() OVER ( PARTITION BY SOURCE_KEY1, SOURCE_KEY2,SOURCE_KEY3) RN   FROM  CUSTOMER_PRODUCT.MDM_CUSTOMER_BRIDGE WHERE SOURCE_SYSTEM_CD='SAM' )  WHERE RN=1 )  B 
WHERE TRIM(B.SOURCE_KEY1)= TRIM(CAST(A.CUSTOMER_ID AS STRING))
