CREATE OR REPLACE TABLE OPERATIONAL.SAM_CAMPAIGNS AS (
	SELECT 
		campaignid AS CAMPAIGN_ID,
		name AS NAME,
		businesslinecode AS BUSINESS_LINE_CODE,
		code AS CODE,
		description AS DESCRIPTION,
		startdate AS START_DATE,
		enddate AS END_DATE,
		active AS ACTIVE
	FROM LANDING.WORK_SAM_CAMPAIGNS)