CREATE OR REPLACE TABLE
  LANDING.WORK_CONTACT_PREFERENCES AS (
  SELECT DISTINCT
    MDM.CUSTOMER_MDM_KEY,
    CUST.CUSTOMER_ID,
    MEM.MEMBER_NUM,
    0 AS DF_CUSTOMER_ID,
    CUST.MEMBERSHIP_NUM,
    CASE
      WHEN TRIM(DONOT_PHONE)='1' THEN 'Y'
      ELSE 'N'
    END AS DO_NOT_PHONE,
    CASE
      WHEN TRIM(DONOT_MAIL)='1' THEN 'Y'
      ELSE 'N'
    END AS DO_NOT_MAIL,
    CASE
      WHEN TRIM(DONOT_EMAIL)='1' THEN 'Y'
      ELSE 'N'
    END AS DO_NOT_EMAIL,
	CASE
	  WHEN TRIM(PRIVATE_EMAIL_ADDRESS)='0' THEN 'Y'
	  ELSE 'N'
	  END AS OK_TO_SOLICT,
	 DMA_PANDER_FLAG AS DMA_PANDER_FLAG 
  FROM (
    SELECT
      CUSTOMER_ID AS CUSTOMER_ID,
      TRIM(MEMBER_ID) AS MEMBERSHIP_NUM,
      TRIM(ASSOC_CD) AS ASSOC_CD,
      DONOT_PHONE,
      DONOT_EMAIL,
      DONOT_MAIL,PRIVATE_EMAIL_ADDRESS
    FROM
      LANDING.WORK_SAM_CUSTOMERS) CUST
  LEFT OUTER JOIN (
    SELECT
      DISTINCT TRIM(SOURCE_KEY1) AS CUSTOMER_ID,
      CUSTOMER_MDM_KEY,
	  ROW_NUMBER() OVER(PARTITION BY SOURCE_KEY1 ORDER BY CUSTOMER_MDM_KEY DESC) AS ROW_NUM
    FROM
      CUSTOMER_PRODUCT.MDM_CUSTOMER_BRIDGE
    WHERE
      SOURCE_SYSTEM_CD='SAM') MDM
  ON
    CAST(CUST.CUSTOMER_ID AS STRING)=MDM.CUSTOMER_ID
	AND ROW_NUM=1
  LEFT OUTER JOIN (
    SELECT
      TRIM(MEMBER_NUM) AS MEMBER_NUM,
      TRIM(CAST(ASSOCIATE_ID AS STRING)) AS ASSOCIATE_ID,
      TRIM(MEMBERSHIP_NUM) AS MEMBERSHIP_NUM
    FROM
      CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM
    WHERE
      ACTIVE_FLG='Y') MEM
  ON
    MEM.MEMBERSHIP_NUM=CUST.MEMBERSHIP_NUM
    AND MEM.ASSOCIATE_ID=CUST.ASSOC_CD
LEFT OUTER JOIN (
    SELECT
      MEMBER_NUM,
      TRIM(DMA_PANDER_FLAG) AS DMA_PANDER_FLAG
    FROM
      DIGITAL_MARKETING.DIRECT_FOCUS_INDIVIDUAL_DIM
    WHERE
      ACTIVE_FLG='Y') IND
  ON
    IND.MEMBER_NUM=MEM.MEMBER_NUM
	
union all 

SELECT
    MDM.CUSTOMER_MDM_KEY,
    CUST.CUSTOMER_ID,
    MEM.MEMBER_NUM,
    0 AS DF_CUSTOMER_ID,
    CUST.MEMBERSHIP_NUM,
    CASE
      WHEN TRIM(DONOT_PHONE)='1' THEN 'Y'
      ELSE 'N'
    END AS DO_NOT_PHONE,
    CASE
      WHEN TRIM(DONOT_MAIL)='1' THEN 'Y'
      ELSE 'N'
    END AS DO_NOT_MAIL,
    CASE
      WHEN TRIM(DONOT_EMAIL)='1' THEN 'Y'
      ELSE 'N'
    END AS DO_NOT_EMAIL,
	CASE
	  WHEN TRIM(PRIVATE_EMAIL_ADDRESS)='0' THEN 'Y'
	  ELSE 'N'
	  END AS OK_TO_SOLICT,
	DMA_PANDER_FLAG AS DMA_PANDER_FLAG  
  FROM 
  (SELECT MEMBER_NUM,
	  ACTIVE_FLG,
      TRIM(DMA_PANDER_FLAG) AS DMA_PANDER_FLAG,UPDATE_DTTIME,ROW_START_DT,
      LEAD(DMA_PANDER_FLAG)
	  OVER (PARTITION BY MEMBER_NUM ORDER BY ROW_START_DT DESC) PREV_DMA_PANDER_FLAG
    FROM
       DIGITAL_MARKETING.DIRECT_FOCUS_INDIVIDUAL_DIM where MEMBER_NUM is not null
              ) IND
  LEFT OUTER JOIN (
    SELECT
      TRIM(MEMBER_NUM) AS MEMBER_NUM,
      TRIM(CAST(ASSOCIATE_ID AS STRING)) AS ASSOCIATE_ID,
      TRIM(MEMBERSHIP_NUM) AS MEMBERSHIP_NUM
    FROM
      CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM
    WHERE
      ACTIVE_FLG='Y') MEM
	ON  IND.MEMBER_NUM=MEM.MEMBER_NUM
    AND PREV_DMA_PANDER_FLAG<>DMA_PANDER_FLAG 
    AND ROW_START_DT>CAST({{ prev_execution_date }} AS DATE)
	  AND IND.ACTIVE_FLG='Y'
	LEFT OUTER JOIN
  (SELECT
      CUSTOMER_ID AS CUSTOMER_ID,
      TRIM(MEMBER_ID) AS MEMBERSHIP_NUM,
      TRIM(ASSOC_CD) AS ASSOC_CD,
      DONOT_PHONE,
      DONOT_EMAIL,
      DONOT_MAIL,PRIVATE_EMAIL_ADDRESS
    FROM
      CUSTOMERS.SAM_CUSTOMERS) CUST
  ON
    MEM.MEMBERSHIP_NUM=CUST.MEMBERSHIP_NUM
    AND MEM.ASSOCIATE_ID=CUST.ASSOC_CD 
  LEFT OUTER JOIN (
    SELECT
      DISTINCT TRIM(SOURCE_KEY1) AS CUSTOMER_ID,
      CUSTOMER_MDM_KEY
    FROM
      CUSTOMER_PRODUCT.MDM_CUSTOMER_BRIDGE
    WHERE
      SOURCE_SYSTEM_CD='SAM') MDM
  ON
    CAST(CUST.CUSTOMER_ID AS STRING)=MDM.CUSTOMER_ID
 )
