SELECT 
TRIM(CONVERT(CHAR,opportunitytypeid,120)) AS OPPORTUNITY_TYPE_ID,
TRIM(CONVERT(CHAR,description,120)) AS DESCRIPTION,
TRIM(CONVERT(CHAR,daysuntildue,120))AS DAYS_UNTIL_DUE,
TRIM(CONVERT(CHAR(10),statusduecode)) AS STATUS_DUE_CD,
TRIM(CONVERT(CHAR(20),businesslinecode)) AS BUSINESS_LINE_CD,
TRIM(CONVERT(CHAR,quote_system,120)) AS QUOTE_SYSTEM,
TRIM(CONVERT(CHAR,quote_type,120)) AS QUOTE_TYPE,
TRIM(CONVERT(CHAR,route_by_zip,120)) AS ROUTE_BY_ZIP,
TRIM(CONVERT(CHAR,route_to_selectable_only,120)) AS ROUTE_TO_SELECTABLE_ONLY,
TRIM(CONVERT(CHAR,travel_type,120)) AS TRAVEL_TYPE
FROM mrm_sam_prd.dbo.opportunitytypes;