SELECT 
TRIM(CONVERT(CHAR,CAMPAIGNID,120)) AS CAMPAIGN_ID,
TRIM(CONVERT(CHAR(50),name)) AS NAME,
TRIM(CONVERT(CHAR(10),businesslinecode)) AS  BUSINESS_LINE_CD,
TRIM(CONVERT(CHAR(20),code)) AS CODE,
TRIM(CONVERT(CHAR(150),description)) AS DESCRIPTION,
CONVERT(CHAR,startdate,120) AS START_DT,
CONVERT(CHAR,enddate,120) AS END_DT,
TRIM(CONVERT(CHAR(10),active)) AS ACTIVE
FROM mrm_sam_prd.dbo.campaigns;