MERGE INTO OPERATIONAL.REVREC_MEMBERSHIP_PAYMENTS TGT
USING (SELECT ROW_NUMBER() OVER() as MEMBERSHIP_PAYMENT_ID, MP.* FROM ( SELECT
    MEMBERSHIP_PAYMENT_KEY,
  MEMBERSHIP_COST_KEY,
  DAILY_EVENT_KEY,
  RECORD_TYPE,
  MEMBERSHIP_NUM,
  PAYMENT_DT,
  PAYMENT_CHANNEL,
  VOID_DT,
  ORIGINAL_PAYMENT_KEY,
  TERM_EFFECTIVE_DT,
  TERM_EXPIRATION_DT,
  PAYMENT_AMOUNT,
  FEE_TYPE,
  FEES_EXPIRATION_DT,
  TRANSACTION_CATEGORY,
  ACCOUNTING_ENTRY_TYPE,
  ACC_PERIOD_EFFECTIVE_DT,
  ACC_PERIOD_EXPIRATION_DT,
  TRANSACTION_EFFECTIVE_DT,
  (SELECT MAX(JOB_RUN_ID)   FROM OPERATIONAL.REVREC_MEMBERSHIP_PAYMENTS)+1 AS JOB_RUN_ID,
  'Payment Script' as CREATE_BY,
  CURRENT_TIMESTAMP() AS CREATE_DTTIME,
  CURRENT_TIMESTAMP() AS UPDATE_DTTIME,
  SALES_CHANNEL,
  MEMBERSHIP_LEVEL,
  RESIDENTIAL_STATE,
  BRANCH_LOCATION,
  PAYMENT_METHOD,
  EMPLOYEE_NUM,
  MERCHANT_ORDER_NUM,
  MERCHANT_ID,
  BANK_ACCOUNT,
  CASE WHEN (ACC_PERIOD_EFFECTIVE_DT is null or ACC_PERIOD_EXPIRATION_DT is null or ACC_PERIOD_EFFECTIVE_DT>ACC_PERIOD_EXPIRATION_DT) THEN 'Y' ELSE 'N' END AS EXCEPTION_FLAG_IND,
  CASE WHEN (ACC_PERIOD_EFFECTIVE_DT is null or ACC_PERIOD_EXPIRATION_DT is null or ACC_PERIOD_EFFECTIVE_DT>ACC_PERIOD_EXPIRATION_DT) THEN 'Null Effective and Expiration dates/Expiration date prior to Effective date' ELSE NULL END AS EXCEPTION_REASON
FROM
  LANDING.WORK_REVREC_MEMBERSHIP_PAYMENT) MP 
  WHERE NOT EXISTS (SELECT '1' FROM OPERATIONAL.REVREC_MEMBERSHIP_PAYMENTS MSP where MP.MEMBERSHIP_PAYMENT_KEY=MSP.MEMBERSHIP_PAYMENT_KEY AND MP.EXCEPTION_FLAG_IND=MSP.EXCEPTION_FLAG_IND)) SRC
ON SRC.MEMBERSHIP_PAYMENT_KEY=TGT.MEMBERSHIP_PAYMENT_KEY
WHEN NOT MATCHED THEN
  INSERT (MEMBERSHIP_PAYMENT_ID,
  MEMBERSHIP_PAYMENT_KEY,
  MEMBERSHIP_COST_KEY,
  DAILY_EVENT_KEY,
  RECORD_TYPE,
  MEMBERSHIP_NUM,
  PAYMENT_DT,
  PAYMENT_CHANNEL,
  VOID_DT,
  ORIGINAL_PAYMENT_KEY,
  TERM_EFFECTIVE_DT,
  TERM_EXPIRATION_DT,
  PAYMENT_AMOUNT,
  FEE_TYPE,
  FEES_EXPIRATION_DT,
  TRANSACTION_CATEGORY,
  ACCOUNTING_ENTRY_TYPE,
  ACC_PERIOD_EFFECTIVE_DT,
  ACC_PERIOD_EXPIRATION_DT,
  TRANSACTION_EFFECTIVE_DT,
  JOB_RUN_ID,
  CREATE_BY,
  CREATE_DTTIME,
  UPDATE_DTTIME,
  SALES_CHANNEL,
  MEMBERSHIP_LEVEL,
  RESIDENTIAL_STATE,
  BRANCH_LOCATION,
  PAYMENT_METHOD,
  EMPLOYEE_NUM,
  MERCHANT_ORDER_NUM,
  MERCHANT_ID,
  BANK_ACCOUNT,
  EXCEPTION_FLAG_IND,
  EXCEPTION_REASON
  )
  VALUES(SRC.MEMBERSHIP_PAYMENT_ID + (SELECT IFNULL(MAX(MEMBERSHIP_PAYMENT_ID),0) FROM OPERATIONAL.REVREC_MEMBERSHIP_PAYMENTS),
  MEMBERSHIP_PAYMENT_KEY,
  MEMBERSHIP_COST_KEY,
  CAST(DAILY_EVENT_KEY AS INT64),
  RECORD_TYPE,
  MEMBERSHIP_NUM,
  PAYMENT_DT,
  PAYMENT_CHANNEL,
  NULL,
  CAST(ORIGINAL_PAYMENT_KEY AS INT64),
  TERM_EFFECTIVE_DT,
  TERM_EXPIRATION_DT,
  PAYMENT_AMOUNT,
  FEE_TYPE,
  FEES_EXPIRATION_DT,
  TRANSACTION_CATEGORY,
  ACCOUNTING_ENTRY_TYPE,
  ACC_PERIOD_EFFECTIVE_DT,
  ACC_PERIOD_EXPIRATION_DT,
  TRANSACTION_EFFECTIVE_DT,
  JOB_RUN_ID,
  CREATE_BY,
  CREATE_DTTIME,
  UPDATE_DTTIME,
  NULL,
  NULL,
  NULL,
  BRANCH_LOCATION,
  PAYMENT_METHOD,
  EMPLOYEE_NUM,
  MERCHANT_ORDER_NUM,
  MERCHANT_ID,
  BANK_ACCOUNT,
  EXCEPTION_FLAG_IND,
  EXCEPTION_REASON)  
WHEN MATCHED THEN  UPDATE SET
TGT.MEMBERSHIP_COST_KEY=SRC.MEMBERSHIP_COST_KEY
,TGT.DAILY_EVENT_KEY=CAST(SRC.DAILY_EVENT_KEY AS INT64)
,TGT.RECORD_TYPE=SRC.RECORD_TYPE
,TGT.MEMBERSHIP_NUM=SRC.MEMBERSHIP_NUM
,TGT.PAYMENT_DT=SRC.PAYMENT_DT
,TGT.PAYMENT_CHANNEL=SRC.PAYMENT_CHANNEL
,TGT.VOID_DT=null
,TGT.ORIGINAL_PAYMENT_KEY=CAST(SRC.ORIGINAL_PAYMENT_KEY AS INT64)
,TGT.TERM_EFFECTIVE_DT=SRC.TERM_EFFECTIVE_DT
,TGT.TERM_EXPIRATION_DT=SRC.TERM_EXPIRATION_DT
,TGT.PAYMENT_AMOUNT=SRC.PAYMENT_AMOUNT
,TGT.FEE_TYPE=SRC.FEE_TYPE
,TGT.FEES_EXPIRATION_DT=SRC.FEES_EXPIRATION_DT
,TGT.TRANSACTION_CATEGORY=SRC.TRANSACTION_CATEGORY
,TGT.ACCOUNTING_ENTRY_TYPE=SRC.ACCOUNTING_ENTRY_TYPE
,TGT.ACC_PERIOD_EFFECTIVE_DT=SRC.ACC_PERIOD_EFFECTIVE_DT
,TGT.ACC_PERIOD_EXPIRATION_DT=SRC.ACC_PERIOD_EXPIRATION_DT
,TGT.TRANSACTION_EFFECTIVE_DT=SRC.TRANSACTION_EFFECTIVE_DT
,TGT.JOB_RUN_ID=SRC.JOB_RUN_ID
,TGT.UPDATE_DTTIME=SRC.UPDATE_DTTIME
,TGT.BRANCH_LOCATION=SRC.BRANCH_LOCATION
,TGT.PAYMENT_METHOD=SRC.PAYMENT_METHOD
,TGT.EMPLOYEE_NUM=SRC.EMPLOYEE_NUM
,TGT.MERCHANT_ORDER_NUM=SRC.MERCHANT_ORDER_NUM
,TGT.MERCHANT_ID=SRC.MERCHANT_ID
,TGT.BANK_ACCOUNT=SRC.BANK_ACCOUNT
,TGT.EXCEPTION_FLAG_IND=SRC.EXCEPTION_FLAG_IND
,TGT.EXCEPTION_REASON=SRC.EXCEPTION_REASON;
