UPDATE `DIGITAL_MARKETING.DIRECT_FOCUS_INDIVIDUAL_DIM` DIM
SET DIM.ROW_END_DT = DATE_SUB(PARSE_DATE('%Y-%m-%d',SUBSTR(STG.ARCHIVE_DT,1,10)), INTERVAL 1 DAY),
ACTIVE_FLG = 'N'
FROM (SELECT CID,ARCHIVE_DT FROM 
(SELECT  CID,ARCHIVE_DT, ROW_NUMBER() OVER(PARTITION BY CID ORDER BY ARCHIVE_DT DESC) AS RNK
FROM `LANDING.WORK_INDIVIDUAL_MD5`)
WHERE RNK = 1)  STG
INNER JOIN (SELECT CID,ROW_START_DT,ACTIVE_FLG 
FROM (SELECT CID,ROW_START_DT,ACTIVE_FLG, ROW_NUMBER() OVER (PARTITION BY CID,ACTIVE_FLG ORDER BY ROW_START_DT DESC ) DUP_CHECK 
FROM `DIGITAL_MARKETING.DIRECT_FOCUS_INDIVIDUAL_DIM` WHERE ACTIVE_FLG = 'Y') 
WHERE DUP_CHECK=2) TEMP
ON TEMP.CID=STG.CID
WHERE TEMP.ROW_START_DT = DIM.ROW_START_DT AND DIM.CID = STG.CID