UPDATE
 DIGITAL_MARKETING.DIRECT_FOCUS_INDIVIDUAL_DIM A
SET
 A.ARCHIVE_DTTIME = PARSE_DATETIME('%Y-%m-%d %H:%M:%S',
   B.ARCHIVE_DT)
FROM (
 SELECT
   MD5_VALUE,
   ARCHIVE_DT
 FROM (
   SELECT
     MD5_VALUE,
     ARCHIVE_DT,
     ROW_NUMBER() OVER(PARTITION BY MD5_VALUE ORDER BY ARCHIVE_DT DESC) AS RNK
   FROM
     LANDING.WORK_INDIVIDUAL_MD5)
 WHERE
   RNK=1 ) B
WHERE
 A.MD5_VALUE= B .MD5_VALUE
 AND A.ARCHIVE_DTTIME != PARSE_DATETIME('%Y-%m-%d %H:%M:%S', B.ARCHIVE_DT)