CREATE TABLE LANDING.WORK_SAM_CUSTOMER_ADDRESSES(
ADDRESS_ID INT64,
CUSTOMER_ID INT64,
ADDRESS_TYPE STRING,
ADDRESS1 STRING,
ADDRESS2 STRING,
CITY STRING,
STATE STRING,
ZIP STRING,
COUNTRY STRING,
COUNTY_NM STRING,
COUNTY_CD STRING
)