steps:

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gsutil cp gs://shared-builderprod-bucket09750/sonarcloud/sonarcloud_DWH_key.encrypted .
    gcloud kms decrypt --location global --keyring aaa-devops-keyring --key aaa-devops-cryptokey --ciphertext-file sonarcloud_DWH_key.encrypted --plaintext-file sonarcloud_DWH_key

#- name: 'gcr.io/aaa-shared-builderprod/custom_image_sonarcloud-linux:v01'
#  entrypoint: 'bash'
#  args:
#  - '-c'
#  - |
#    sonar-scanner -Dsonar.projectKey=DWH-key -Dsonar.organization=github-svc-acct -Dsonar.exclusions=**.sql,GCPDWH/archive/* -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$(cat sonarcloud_DWH_key) -Dsonar.cpd.py.minimumLines=150

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    #dagBucket=gs://us-central1-prod-composer-860da7be-bucket/dags
    dagBucket=gs://us-central1-aaa-prod-compos-4312e4d9-bucket/dags
    #dataBucket=gs://us-central1-prod-composer-860da7be-bucket/data/GCPDWH
    dataBucket=gs://us-central1-aaa-prod-compos-4312e4d9-bucket/data/GCPDWH
    #keyBucket=gs://us-central1-prod-composer-860da7be-bucket/data/jsonkeys/
    keyBucket=gs://us-central1-aaa-prod-compos-4312e4d9-bucket/data/jsonkeys/
    mv GCPDWH/dags/ .
    ls -all dags/*
    
    #gsutil cp gs://shared-builderpreprod-bucket09750/dwh_json_keys/dw-prod-1d813c739a76.json.encrypted .
    gsutil cp gs://shared-builderprod-bucket09750/keys/dwh_json_keys/aaa-mwg-dwprod-247c8742715c.json.encrypted .
    #gcloud kms decrypt --location global --keyring aaa-devops-keyring --key aaa-devops-cryptokey --ciphertext-file dw-prod-1d813c739a76.json.encrypted --plaintext-file dw-prod-1d813c739a76.json
    gcloud kms decrypt --location global --keyring aaa-devops-keyring --key aaa-devops-cryptokey --ciphertext-file aaa-mwg-dwprod-247c8742715c.json.encrypted --plaintext-file aaa-mwg-dwprod-247c8742715c.json
    

    gsutil -m cp -r dags/"DAG_GCP_PIPELINE_CALENDAR.py" dags/"DAG_GCP_POS_LOAD2.py" dags/"DAG_GCP_SAM_LOAD.py" dags/"DAG_GCP_STATUS.py" dags/"DAG_GCP_SURVEY_LOAD.py" $dagBucket
    gsutil -m cp -r dags/"DAG_GCP_TRAVEL_TST_LOAD.py" dags/"DAG_GCS_ERS_REPAIR_SHOP_PORTAL.py" $dagBucket
    
    gsutil -m cp -r dags/"AMS_LANDING_GENERAL_LEDGER_LOAD.py" dags/"AMS_OPERATIONAL_GENERAL_LEDGER_AND_OUTBOUND_FILE_LOAD.py" dags/"DAG-A3_SMART_HOME-PIPELINE.py" dags/"DAG_GCP_AS400_LOAD.py" dags/"DAG_GCP_DIRECT_FOCUS_ENGAGE_JOURNEY_HISTORY_WEEKDAY_LOAD.py" $dagBucket
    gsutil -m cp -r dags/"DAG_GCP_ERS_DEV_TEST_BACK_OFFICE.py" dags/"DAG_GCP_ERS_LOAD.py" dags/"DAG_GCP_IE_MART_LOAD.py" dags/"DAG_GCP_OUTBOUND_CS_INSURANCE.py" dags/"DAG_GCP_OUTBOUND_IG_MBRS_FILE_LOAD.py" $dagBucket
    gsutil -m cp -r dags/"DAG_GCP_POS_LOAD.py" dags/"DAG_GCP_QUOTES_LOAD.py" dags/"DAG_OUTBOUND_MEMBERSHIP_NOTIFICATION_XML.py" dags/"TEST_DAG_GCP_ERS_LOAD.py" $dagBucket

    gsutil -m cp dw-prod-1d813c739a76.json $keyBucket 
    gsutil -m cp aaa-mwg-dwprod-247c8742715c.json $keyBucket
    ls -all
    cd GCPDWH
    ls -all
    gsutil -m cp -r * $dataBucket/
    
logsBucket: 'gs://shared-builderprod-bucket01/buildlogs/dwh/prod'
