steps:

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gsutil cp gs://shared-builderpreprod-bucket09750/sonarcloud/sonarcloud_DWH_key.encrypted .
    gcloud kms decrypt --location global --keyring aaa-devops-keyring --key aaa-devops-cryptokey --ciphertext-file sonarcloud_DWH_key.encrypted --plaintext-file sonarcloud_DWH_key

- name: 'gcr.io/aaa-shared-builderpreprod/custom_image_sonarcloud-linux:v02'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    sonar-scanner -Dsonar.projectKey=DWH-key -Dsonar.organization=github-svc-acct -Dsonar.exclusions=**.sql,GCPDWH/archive/* -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$(cat sonarcloud_DWH_key) -Dsonar.branch.name=TestBranch

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    dagBucket=gs://us-central1-qa-composer-ec66897d-bucket/dags
    dataBucket=gs://us-central1-qa-composer-ec66897d-bucket/data/GCPDWH
    keyBucket=gs://us-central1-qa-composer-ec66897d-bucket/data/jsonkeys
    mv GCPDWH/dags/ .
    ls -all dags/*
    
    gsutil cp gs://shared-builderpreprod-bucket09750/dwh_json_keys/AAAData-69668e42a7cf.json.encrypted .
    gsutil cp gs://shared-builderpreprod-bucket09750/dwh_json_keys/aaa-mwg-dwprod-247c8742715c.json.encrypted .
    gcloud kms decrypt --location global --keyring aaa-devops-keyring --key aaa-devops-cryptokey --ciphertext-file AAAData-69668e42a7cf.json.encrypted --plaintext-file AAAData-69668e42a7cf.json
    gcloud kms decrypt --location global --keyring aaa-devops-keyring --key aaa-devops-cryptokey --ciphertext-file aaa-mwg-dwprod-247c8742715c.json.encrypted --plaintext-file aaa-mwg-dwprod-247c8742715c.json
    
    #gsutil cp dags/DAG_GCP_OUTBOUND_CHECK_REFUNDS.py $dagBucket
    #gsutil cp dags/DAG_GCP_COM235.py $dagBucket
    gsutil -m cp -r dags/DAG_GCP_CCPA_CUSTOMER_LOAD.py $dagBucket	
    #gcloud composer environments run dev-composer --location=us-central1 variables -- --i /home/airflow/gcs/data/GCPDWH/config/composer/dev_variables.json
    #gsutil -m cp AAAData-69668e42a7cf.json $keyBucket 
    gsutil -m cp aaa-mwg-dwprod-247c8742715c.json $keyBucket #this key overrides the ERS-ML preprod key and fails jobs
    cd GCPDWH
    ls -all
    gsutil -m cp -r * $dataBucket/
    
logsBucket: 'gs://shared-builderpreprod-bucket01/buildlogs/dwh/qa'
