CREATE OR REPLACE TABLE CUSTOMER_PRODUCT.POS_BANK_DEPOSIT_DIM
AS (
select DISTINCT CUST_RECPT.SALE_ID AS TRANSACTION_NUM,
CUST_RECPT.SALE_COMPLETE_DTTIME  AS TRANSACTION_DTTIME,
CUST_RECPT.SALE_ID as POS_TRANSACTION_ID,
CUST_RECPT.OFFICE_ID AS LOCATION_ID,
case when REGEXP_CONTAINS(TRIM(CONSULTANT_ID), "[a-zA-Z]")
then ENT.EMPLOYEE_ID else EMP_ID.EMPLOYEE_ID end as EMPLOYEE_ID,
case when REGEXP_CONTAINS(TRIM(CONSULTANT_ID), "[a-zA-Z]")
then ENT.EMPLOYEE_NAME else EMP_ID.EMPLOYEE_NAME end as EMPLOYEE_NM,
'' as BANK,
'' as ACCOUNT,
MAX(ITEM.ADDITIONAL_TXT) OVER (PARTITION BY  CUST_RECPT.SALE_ID )  as BAG_ID,
CUST_RECPT.TENDER_TOTAL as TOTAL_AMT,
CASH_AMT as CASH_AMT,
CHECK_AMT as CHECK_AMT,
'' AS ADJUSTMENT,
'' as REASON,
'' as ORIGINAL_TRANSACTION_NUM,
CUST_RECPT.SALE_COMPLETE_DTTIME  as CREATE_DTTIME
FROM OPERATIONAL.POS_CUSTOMER_PAYMENTS as CUST_RECPT
INNER JOIN OPERATIONAL.POS_CUSTOMER_RECEIPT_LINE_ITEMS as ITEM
ON CUST_RECPT.SALE_ID=ITEM.SALE_ID
AND trim(ITEM.ITEM_TYPE_ID)='BANK DEPOSIT'
LEFT OUTER JOIN
(select distinct TRIM(EMPLOYEE_ID) as EMPLOYEE_ID,CONCAT(TRIM(LEGAL_FIRST_NM)," ",TRIM(LEGAL_LAST_NM)) as EMPLOYEE_NAME from CUSTOMERS.EMPLOYEE_PROFILE_DIM where ACTIVE_FLG='Y') as EMP_ID
ON TRIM(CUST_RECPT.CONSULTANT_ID) = TRIM(EMP_ID.EMPLOYEE_ID)
LEFT OUTER JOIN
(select DISTINCT TRIM(EMPLOYEE_ID) as EMPLOYEE_ID,TRIM(ENT_ID) as ENT_ID,CONCAT(TRIM(LEGAL_FIRST_NM)," ",TRIM(LEGAL_LAST_NM)) as EMPLOYEE_NAME from CUSTOMERS.EMPLOYEE_PROFILE_DIM where ACTIVE_FLG='Y') as ENT
ON TRIM(CUST_RECPT.CONSULTANT_ID) = TRIM(ENT.ENT_ID))
