CREATE OR REPLACE TABLE CUSTOMER_PRODUCT.POS_TENDER_SUMMARY_DIM 
AS (
SELECT DISTINCT
R10_TRANSACTION_ID AS POS_TRANSACTION_ID,
TRANSACTION_DTTIME,
STORE_NUM AS LOCATION_ID,
REGISTER_NUM,
EMPLOYEE_NUM AS EMPLOYEE_ID,
EMPLOYEE_NAME AS EMPLOYEE_NM,
MEMBER_NUM AS MEMBER_NUM_15,
--MEMBER_FIRST_NAME,
--MEMBER_LAST_NAME,
SKU_COMPANY,
ROUND(TOTAL_ITEM_SALES_AMOUNT,2) AS GRAND_TOTAL,
FULL_TICKET_VOID_FLAG,
LINE_ITEM_VOID_FLAG,
RETURN_FLAG,
TLOG_CREATE_DTTIME,
ROUND(CASE
    WHEN (GRAND_TOTAL - TOTAL_ITEM_SALES_AMOUNT) = 0
    THEN CASH_AMOUNT
    WHEN CASH_AMOUNT           = 0
    OR TOTAL_ITEM_SALES_AMOUNT = 0
    THEN 0
    WHEN SKU_COMPANY                               = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT *-1 - CASH_AMOUNT <= 0
    AND RETURN_FLAG                                = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                    < 0
    THEN TOTAL_ITEM_SALES_AMOUNT
    WHEN SKU_COMPANY                              = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT *-1 - CASH_AMOUNT > 0
    AND RETURN_FLAG                               = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                   < 0
    THEN CASH_AMOUNT *-1
    WHEN SKU_COMPANY                                = 'IG'
    AND (TOTAL_ITEM_SALES_AMOUNT *-1 -CHECK_AMOUNT) > 0
    AND RETURN_FLAG                                 = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                     < 0
    THEN TOTAL_ITEM_SALES_AMOUNT + CHECK_AMOUNT
    WHEN SKU_COMPANY                           = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT - CASH_AMOUNT <= 0
    THEN TOTAL_ITEM_SALES_AMOUNT
    WHEN SKU_COMPANY                          = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT - CASH_AMOUNT > 0
    THEN CASH_AMOUNT
	WHEN SKU_COMPANY                            = 'IG'
    AND (TOTAL_ITEM_SALES_AMOUNT - CHECK_AMOUNT - CASH_AMOUNT) <= 0
    THEN TOTAL_ITEM_SALES_AMOUNT - CHECK_AMOUNT
    WHEN SKU_COMPANY                            = 'IG'
    AND (TOTAL_ITEM_SALES_AMOUNT -CHECK_AMOUNT - CASH_AMOUNT) > 0
    THEN CASH_AMOUNT
  END,2) CASH_AMT,
  ROUND(CASE
    WHEN (GRAND_TOTAL - TOTAL_ITEM_SALES_AMOUNT) = 0
    THEN CHECK_AMOUNT
    WHEN CHECK_AMOUNT          = 0
    OR TOTAL_ITEM_SALES_AMOUNT = 0
    THEN 0
    WHEN SKU_COMPANY                                = 'IG'
    AND TOTAL_ITEM_SALES_AMOUNT *-1 - CHECK_AMOUNT <= 0
    AND RETURN_FLAG                                 = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                     < 0
    THEN TOTAL_ITEM_SALES_AMOUNT
    WHEN SKU_COMPANY                               = 'IG'
    AND TOTAL_ITEM_SALES_AMOUNT *-1 - CHECK_AMOUNT > 0
    AND RETURN_FLAG                                = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                    < 0
    THEN CHECK_AMOUNT *-1
    WHEN SKU_COMPANY                              = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT *-1 - CASH_AMOUNT > 0
    AND RETURN_FLAG                               = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                   < 0
    THEN TOTAL_ITEM_SALES_AMOUNT + CASH_AMOUNT
    WHEN SKU_COMPANY                            = 'IG'
    AND TOTAL_ITEM_SALES_AMOUNT - CHECK_AMOUNT <= 0
    THEN TOTAL_ITEM_SALES_AMOUNT
    WHEN SKU_COMPANY                           = 'IG'
    AND TOTAL_ITEM_SALES_AMOUNT - CHECK_AMOUNT > 0
    THEN CHECK_AMOUNT
    WHEN SKU_COMPANY                          = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT  - CASH_AMOUNT  - CHECK_AMOUNT > 0
    THEN CHECK_AMOUNT
	WHEN SKU_COMPANY                          = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT  - CASH_AMOUNT  - CHECK_AMOUNT <= 0
    THEN TOTAL_ITEM_SALES_AMOUNT  - CASH_AMOUNT
  END,2) CHECK_AMT,
  ROUND(CASE
    WHEN (GRAND_TOTAL - TOTAL_ITEM_SALES_AMOUNT) = 0
    THEN VISA_AMOUNT
    WHEN VISA_AMOUNT           = 0
    OR TOTAL_ITEM_SALES_AMOUNT = 0
    THEN 0
    WHEN SKU_COMPANY                               = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT *-1 - VISA_AMOUNT <= 0
    AND RETURN_FLAG                                = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                    < 0
    THEN TOTAL_ITEM_SALES_AMOUNT
    WHEN SKU_COMPANY                              = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT *-1 - VISA_AMOUNT > 0
    AND RETURN_FLAG                               = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                   < 0
    THEN VISA_AMOUNT *-1
    WHEN SKU_COMPANY                                = 'IG'
    AND (TOTAL_ITEM_SALES_AMOUNT *-1 -(CASH_AMOUNT+CHECK_AMOUNT)) > 0
    AND RETURN_FLAG                                 = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                     < 0
    THEN TOTAL_ITEM_SALES_AMOUNT + (CASH_AMOUNT+CHECK_AMOUNT)
    WHEN TOTAL_ITEM_SALES_AMOUNT -(CASH_AMOUNT+CHECK_AMOUNT) - VISA_AMOUNT <= 0
    THEN TOTAL_ITEM_SALES_AMOUNT -(CASH_AMOUNT+CHECK_AMOUNT)
    WHEN  TOTAL_ITEM_SALES_AMOUNT -(CASH_AMOUNT+CHECK_AMOUNT) - VISA_AMOUNT > 0
    THEN VISA_AMOUNT
END,2) VISA_AMT,
ROUND(CASE
    WHEN (GRAND_TOTAL - TOTAL_ITEM_SALES_AMOUNT) = 0
    THEN MASTERCARD_AMOUNT
    WHEN MASTERCARD_AMOUNT           = 0
    OR TOTAL_ITEM_SALES_AMOUNT = 0
    THEN 0
    WHEN SKU_COMPANY                               = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT *-1 - MASTERCARD_AMOUNT <= 0
    AND RETURN_FLAG                                = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                    < 0
    THEN TOTAL_ITEM_SALES_AMOUNT
    WHEN SKU_COMPANY                              = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT *-1 - MASTERCARD_AMOUNT > 0
    AND RETURN_FLAG                               = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                   < 0
    THEN MASTERCARD_AMOUNT *-1
    WHEN SKU_COMPANY                                = 'IG'
    AND (TOTAL_ITEM_SALES_AMOUNT *-1 -(CASH_AMOUNT+CHECK_AMOUNT)) > 0
    AND RETURN_FLAG                                 = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                     < 0
    THEN TOTAL_ITEM_SALES_AMOUNT + (CASH_AMOUNT+CHECK_AMOUNT)
    WHEN TOTAL_ITEM_SALES_AMOUNT -(CASH_AMOUNT+CHECK_AMOUNT) - MASTERCARD_AMOUNT <= 0
    THEN TOTAL_ITEM_SALES_AMOUNT -(CASH_AMOUNT+CHECK_AMOUNT)
    WHEN  TOTAL_ITEM_SALES_AMOUNT -(CASH_AMOUNT+CHECK_AMOUNT) - MASTERCARD_AMOUNT > 0
    THEN MASTERCARD_AMOUNT
END,2) AS MASTERCARD_AMT,
ROUND(CASE
    WHEN (GRAND_TOTAL - TOTAL_ITEM_SALES_AMOUNT) = 0
    THEN AMEX_AMOUNT
    WHEN AMEX_AMOUNT           = 0
    OR TOTAL_ITEM_SALES_AMOUNT = 0
    THEN 0
    WHEN SKU_COMPANY                               = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT *-1 - AMEX_AMOUNT <= 0
    AND RETURN_FLAG                                = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                    < 0
    THEN TOTAL_ITEM_SALES_AMOUNT
    WHEN SKU_COMPANY                              = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT *-1 - AMEX_AMOUNT > 0
    AND RETURN_FLAG                               = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                   < 0
    THEN AMEX_AMOUNT *-1
    WHEN SKU_COMPANY                                = 'IG'
    AND (TOTAL_ITEM_SALES_AMOUNT *-1 -(CASH_AMOUNT+CHECK_AMOUNT)) > 0
    AND RETURN_FLAG                                 = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                     < 0
    THEN TOTAL_ITEM_SALES_AMOUNT + (CASH_AMOUNT+CHECK_AMOUNT)
    WHEN TOTAL_ITEM_SALES_AMOUNT -(CASH_AMOUNT+CHECK_AMOUNT) - AMEX_AMOUNT <= 0
    THEN TOTAL_ITEM_SALES_AMOUNT -(CASH_AMOUNT+CHECK_AMOUNT)
    WHEN  TOTAL_ITEM_SALES_AMOUNT -(CASH_AMOUNT+CHECK_AMOUNT) - AMEX_AMOUNT > 0
    THEN AMEX_AMOUNT
END,2) AS AMEX_AMT,
ROUND(CASE
    WHEN (GRAND_TOTAL - TOTAL_ITEM_SALES_AMOUNT) = 0
    THEN DISCOVER_AMOUNT
    WHEN DISCOVER_AMOUNT           = 0
    OR TOTAL_ITEM_SALES_AMOUNT = 0
    THEN 0
    WHEN SKU_COMPANY                               = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT *-1 - DISCOVER_AMOUNT <= 0
    AND RETURN_FLAG                                = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                    < 0
    THEN TOTAL_ITEM_SALES_AMOUNT
    WHEN SKU_COMPANY                              = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT *-1 - DISCOVER_AMOUNT > 0
    AND RETURN_FLAG                               = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                   < 0
    THEN DISCOVER_AMOUNT *-1
    WHEN SKU_COMPANY                                = 'IG'
    AND (TOTAL_ITEM_SALES_AMOUNT *-1 -(CASH_AMOUNT+CHECK_AMOUNT)) > 0
    AND RETURN_FLAG                                 = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                     < 0
    THEN TOTAL_ITEM_SALES_AMOUNT + (CASH_AMOUNT+CHECK_AMOUNT)
    WHEN TOTAL_ITEM_SALES_AMOUNT -(CASH_AMOUNT+CHECK_AMOUNT) - DISCOVER_AMOUNT <= 0
    THEN TOTAL_ITEM_SALES_AMOUNT -(CASH_AMOUNT+CHECK_AMOUNT)
    WHEN  TOTAL_ITEM_SALES_AMOUNT -(CASH_AMOUNT+CHECK_AMOUNT) - DISCOVER_AMOUNT > 0
    THEN DISCOVER_AMOUNT
END,2) AS DISCOVER_AMT,
ROUND(CASE
    WHEN (GRAND_TOTAL - TOTAL_ITEM_SALES_AMOUNT) = 0
    THEN DEBIT_AMOUNT
    WHEN DEBIT_AMOUNT           = 0
    OR TOTAL_ITEM_SALES_AMOUNT = 0
    THEN 0
    WHEN SKU_COMPANY                               = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT *-1 - DEBIT_AMOUNT <= 0
    AND RETURN_FLAG                                = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                    < 0
    THEN TOTAL_ITEM_SALES_AMOUNT
    WHEN SKU_COMPANY                              = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT *-1 - DEBIT_AMOUNT > 0
    AND RETURN_FLAG                               = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                   < 0
    THEN DEBIT_AMOUNT *-1
    WHEN SKU_COMPANY                                = 'IG'
    AND (TOTAL_ITEM_SALES_AMOUNT *-1 -(CASH_AMOUNT+CHECK_AMOUNT)) > 0
    AND RETURN_FLAG                                 = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT                     < 0
    THEN TOTAL_ITEM_SALES_AMOUNT + (CASH_AMOUNT+CHECK_AMOUNT)
    WHEN TOTAL_ITEM_SALES_AMOUNT -(CASH_AMOUNT+CHECK_AMOUNT) - DEBIT_AMOUNT <= 0
    THEN TOTAL_ITEM_SALES_AMOUNT -(CASH_AMOUNT+CHECK_AMOUNT)
    WHEN  TOTAL_ITEM_SALES_AMOUNT -(CASH_AMOUNT+CHECK_AMOUNT) - DEBIT_AMOUNT > 0
    THEN DEBIT_AMOUNT
END,2) DEBIT_AMT,
ROUND(MISC_AMOUNT,2) AS MISC_AMT,
ROUND(TOTAL_ITEM_SALES_AMOUNT,2) AS TENDER_TOTAL,
  ROUND(CASE
    WHEN (GRAND_TOTAL - TOTAL_ITEM_SALES_AMOUNT) = 0
    THEN CASH_NET
    WHEN CASH_NET              = 0
    OR TOTAL_ITEM_SALES_AMOUNT = 0
    THEN 0
    WHEN SKU_COMPANY                        = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT - CASH_NET >= 0
    AND RETURN_FLAG                         = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT             < 0
    THEN TOTAL_ITEM_SALES_AMOUNT
    WHEN SKU_COMPANY                       = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT - CASH_NET < 0
    AND RETURN_FLAG                        = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT            < 0
    THEN CASH_NET
    WHEN SKU_COMPANY                          = 'IG'
    AND (TOTAL_ITEM_SALES_AMOUNT - CHECK_NET) > 0
    AND RETURN_FLAG                           = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT               < 0
    THEN 0
    WHEN SKU_COMPANY                          = 'IG'
    AND (TOTAL_ITEM_SALES_AMOUNT - CHECK_NET) < 0
    AND RETURN_FLAG                           = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT               < 0
    THEN TOTAL_ITEM_SALES_AMOUNT - CHECK_NET
    WHEN SKU_COMPANY                        = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT - CASH_NET <= 0
    THEN TOTAL_ITEM_SALES_AMOUNT
    WHEN SKU_COMPANY                       = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT - CASH_NET > 0
    THEN CASH_NET
    WHEN SKU_COMPANY                         = 'IG'
    AND (TOTAL_ITEM_SALES_AMOUNT - CHECK_NET - CASH_NET) <= 0
    THEN TOTAL_ITEM_SALES_AMOUNT - CHECK_NET
    WHEN SKU_COMPANY                            = 'IG'
    AND (TOTAL_ITEM_SALES_AMOUNT -CHECK_NET - CASH_NET) > 0
    THEN CASH_NET	
  END,2) AS CASH_NET,
  ROUND(CASE
    WHEN (GRAND_TOTAL - TOTAL_ITEM_SALES_AMOUNT) = 0
    THEN CHECK_NET
    WHEN CHECK_NET             = 0
    OR TOTAL_ITEM_SALES_AMOUNT = 0
    THEN 0
    WHEN SKU_COMPANY                         = 'IG'
    AND TOTAL_ITEM_SALES_AMOUNT - CHECK_NET >= 0
    AND RETURN_FLAG                          = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT              < 0
    THEN TOTAL_ITEM_SALES_AMOUNT
    WHEN SKU_COMPANY                        = 'IG'
    AND TOTAL_ITEM_SALES_AMOUNT - CHECK_NET < 0
    AND RETURN_FLAG                         = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT             < 0
    THEN CHECK_NET
    WHEN SKU_COMPANY                       = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT - CASH_NET > 0
    AND RETURN_FLAG                        = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT            < 0
    THEN 0
    WHEN SKU_COMPANY                       = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT - CASH_NET < 0
    AND RETURN_FLAG                        = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT            < 0
    THEN TOTAL_ITEM_SALES_AMOUNT - CASH_NET
    WHEN SKU_COMPANY                         = 'IG'
    AND TOTAL_ITEM_SALES_AMOUNT - CHECK_NET <= 0
    THEN TOTAL_ITEM_SALES_AMOUNT
    WHEN SKU_COMPANY                        = 'IG'
    AND TOTAL_ITEM_SALES_AMOUNT - CHECK_NET > 0
    THEN CHECK_NET
    WHEN SKU_COMPANY                       = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT  - CASH_NET - CHECK_NET <= 0
    THEN TOTAL_ITEM_SALES_AMOUNT - CASH_NET
	WHEN SKU_COMPANY                       = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT  - CASH_NET - CHECK_NET > 0
    THEN CHECK_NET	
  END,2) AS CHECK_NET,
  ROUND(CASE
    WHEN (GRAND_TOTAL - TOTAL_ITEM_SALES_AMOUNT) = 0
    THEN CC_NET
    WHEN CC_NET              = 0
    OR TOTAL_ITEM_SALES_AMOUNT = 0
    THEN 0
    WHEN SKU_COMPANY                        = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT - CC_NET >= 0
    AND RETURN_FLAG                         = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT             < 0
    THEN TOTAL_ITEM_SALES_AMOUNT
    WHEN SKU_COMPANY                       = 'Club'
    AND TOTAL_ITEM_SALES_AMOUNT - CC_NET < 0
    AND RETURN_FLAG                        = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT            < 0
    THEN CC_NET
    WHEN SKU_COMPANY                          = 'IG'
    AND (TOTAL_ITEM_SALES_AMOUNT - (CASH_NET+CHECK_NET)) > 0
    AND RETURN_FLAG                           = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT               < 0
    THEN 0
    WHEN SKU_COMPANY                          = 'IG'
    AND (TOTAL_ITEM_SALES_AMOUNT - (CASH_NET+CHECK_NET)) < 0
    AND RETURN_FLAG                           = 'Y'
    AND TOTAL_ITEM_SALES_AMOUNT               < 0
    THEN TOTAL_ITEM_SALES_AMOUNT - (CASH_NET+CHECK_NET)
	WHEN TOTAL_ITEM_SALES_AMOUNT -(CASH_NET+CHECK_NET) - CC_NET <= 0
    THEN TOTAL_ITEM_SALES_AMOUNT -(CASH_NET+CHECK_NET)
    WHEN  TOTAL_ITEM_SALES_AMOUNT - (CASH_NET+CHECK_NET) - CC_NET > 0
    THEN CC_NET	
  END,2) AS CC_NET,
ROUND(MISC_NET,2) AS MISC_NET,
CASE WHEN UPPER(SKU_COMPANY) = 'CLUB' THEN ROUND(CHANGE_AMOUNT,2) WHEN SKU_COUNT=2 and UPPER(SKU_COMPANY) <> 'CLUB' THEN 0 ELSE ROUND(CHANGE_AMOUNT,2) END AS CHANGE_AMT,
LAST_UPDATE_DTTIME,
IFNULL(PURCHASE_QUANTITY,0) AS PURCHASE_QUANTITY,
IFNULL(RETURN_QUANTITY,0) AS RETURN_QUANTITY,
IFNULL(VOID_TOTAL,0) AS VOID_TOTAL,
IFNULL(RETURN_TOTAL,0) AS RETURN_TOTAL
  FROM(
SELECT CUST_RECPT.SALE_ID AS R10_TRANSACTION_ID, 
CUST_RECPT.SALE_COMPLETE_DTTIME AS TRANSACTION_DTTIME, 
CUST_RECPT.OFFICE_ID AS STORE_NUM, 
NULL AS REGISTER_NUM, 
CUST_RECPT.CONSULTANT_ID AS EMPLOYEE_NUM, 
CASE
    WHEN REGEXP_CONTAINS(TRIM(CONSULTANT_ID), "[a-zA-Z]") THEN ENT.EMPLOYEE_NAME
    ELSE EMP_ID.EMPLOYEE_NAME
  END AS EMPLOYEE_NAME,
CASE WHEN UPPER(SUBSTR(CUST_RECPT.CUST_ID,1,1)) = 'M' THEN CONCAT('429',"",SUBSTR(CUST_RECPT.CUST_ID,2,12)) ELSE NULL END as MEMBER_NUM, 
CUST_RECPT.CUST_FIRST_NM AS MEMBER_FIRST_NAME, 
CUST_RECPT.CUST_LAST_NM AS MEMBER_LAST_NAME, 
CUST_RECPT.CUST_RECPT_TOT_SALES_AMT AS GRAND_TOTAL,
CASE WHEN UPPER(CUST_RECPT.CUST_RECPT_VOID_RET_IND)='V' THEN 'Y' ELSE 'N' END AS FULL_TICKET_VOID_FLAG, 
CASE WHEN UPPER(CUST_RECPT.CUST_RECPT_VOID_RET_IND)='V' THEN 'Y' ELSE 'N' END AS LINE_ITEM_VOID_FLAG,
CASE WHEN UPPER(CUST_RECPT.CUST_RECPT_VOID_RET_IND)='R' THEN 'Y' ELSE 'N' END AS RETURN_FLAG, 
CUST_RECPT.SALE_COMPLETE_DTTIME AS TLOG_CREATE_DTTIME, 
CASE WHEN AMT.COMPANY IS NOT NULL THEN AMT.COMPANY ELSE ' ' END AS SKU_COMPANY,
CASE WHEN UPPER(AMT.COMPANY) = 'CLUB'  THEN AMT.TOTAL_ITEM_SALES_AMOUNT + CUST_RECPT.CUST_RECPT_TAX_AMT ELSE TOTAL_ITEM_SALES_AMOUNT END AS TOTAL_ITEM_SALES_AMOUNT,
CASH_AMT AS CASH_AMOUNT,
CHECK_AMT AS CHECK_AMOUNT,
DEBIT_AMT AS DEBIT_AMOUNT,
AMEX_AMT AS AMEX_AMOUNT,
VISA_AMT AS VISA_AMOUNT,
MASTERCARD_AMT AS MASTERCARD_AMOUNT,
DISCOVER_AMT AS DISCOVER_AMOUNT,
MISC_AMT AS MISC_AMOUNT,
TENDER_TOTAL AS TENDER_TOTAL,
CASH_NET AS CASH_NET,
CHECK_NET AS CHECK_NET,
CC_NET AS CC_NET,
MISC_NET AS MISC_NET,
CUST_RECPT.CUST_PYMT_AMT-CUST_RECPT.CUST_RECPT_TOT_SALES_AMT AS CHANGE_AMOUNT,
CUST_RECPT.SALE_COMPLETE_DTTIME AS LAST_UPDATE_DTTIME,
RET.PURCHASE_QUANTITY,
RET.RETURN_QUANTITY,
RET.VOID_TOTAL,
RET.RETURN_TOTAL,
AMT.SKU_COUNT
 FROM OPERATIONAL.POS_CUSTOMER_PAYMENTS as CUST_RECPT 
LEFT OUTER JOIN (
  SELECT
    DISTINCT TRIM(EMPLOYEE_ID) AS EMPLOYEE_ID,
    CONCAT(TRIM(LEGAL_FIRST_NM)," ",TRIM(LEGAL_LAST_NM)) AS EMPLOYEE_NAME
  FROM
    CUSTOMERS.EMPLOYEE_PROFILE_DIM
  WHERE
    ACTIVE_FLG='Y') AS EMP_ID
ON
  TRIM(CUST_RECPT.CONSULTANT_ID) = TRIM(EMP_ID.EMPLOYEE_ID)
LEFT OUTER JOIN (
  SELECT
    DISTINCT TRIM(EMPLOYEE_ID) AS EMPLOYEE_ID,
    TRIM(ENT_ID) AS ENT_ID,
    CONCAT(TRIM(LEGAL_FIRST_NM)," ",TRIM(LEGAL_LAST_NM)) AS EMPLOYEE_NAME
  FROM
    CUSTOMERS.EMPLOYEE_PROFILE_DIM
  WHERE
    ACTIVE_FLG='Y') AS ENT
ON
  TRIM(CUST_RECPT.CONSULTANT_ID) = TRIM(ENT.ENT_ID)
INNER JOIN (select SALE_ID,PC.COMPANY as COMPANY,ROUND(SUM(SALE_PRC),2) as TOTAL_ITEM_SALES_AMOUNT,COUNT(distinct PC.COMPANY) over (partition by SALE_ID) as SKU_COUNT from
(select ITEM.SALE_ID , 
       ITEM.ITEM_TYPE_ID,
       ITEM.SALE_PRC * ITEM.QUANTITY AS SALE_PRC,
	   ITEM.ITEM_TYPE_ID as CS_SKU_TYPE
     FROM OPERATIONAL.POS_CUSTOMER_RECEIPT_LINE_ITEMS ITEM) ITEM,
     REFERENCE.CONNECTSUITE_PRODUCT_DIM PC
WHERE UPPER(TRIM(ITEM.CS_SKU_TYPE))=UPPER(PC.SKU)
AND UPPER(PC.SKU_TYPE)='TRANSACTION'
group by SALE_ID,PC.COMPANY) AMT
ON CUST_RECPT.SALE_ID=AMT.SALE_ID
LEFT OUTER JOIN
(SELECT SALE_ID      AS R10_TRANSACTION_ID,
  PURCHASE_QUANTITY AS PURCHASE_QUANTITY,
  RETURN_QUANTITY   AS RETURN_QUANTITY,
  VOID_TOTAL        AS VOID_TOTAL,
  RETURN_TOTAL      AS RETURN_TOTAL
FROM
(SELECT ITEM.SALE_ID,
    SUM(ITEM.QUANTITY) OVER(PARTITION BY ITEM.SALE_ID ) PURCHASE_QUANTITY,
    SUM(IFNULL(
    CASE
      WHEN UPPER(ITEM.CUST_RECPT_VD_RET_IND)='R'
      THEN ITEM.QUANTITY
      ELSE NULL
    END,0)) OVER(PARTITION BY ITEM.SALE_ID) RETURN_QUANTITY,
    CASE
      WHEN UPPER(CUST.CUST_RECPT_VOID_RET_IND) ='V'
      THEN CUST.CUST_RECPT_TOT_SALES_AMT
      WHEN UPPER(ITEM.CUST_RECPT_VD_RET_IND)='V'
      THEN SUM (IFNULL(
        CASE
          WHEN UPPER(ITEM.CUST_RECPT_VD_RET_IND)='V'
          THEN ITEM.SALE_PRC
          ELSE NULL
        END,0)) OVER(PARTITION BY ITEM.SALE_ID)
      ELSE NULL
    END AS VOID_TOTAL,
    SUM(IFNULL(
    CASE
      WHEN UPPER(ITEM.CUST_RECPT_VD_RET_IND)='R'
      THEN ITEM.SALE_PRC
      ELSE NULL
    END,0)) OVER(PARTITION BY ITEM.SALE_ID) RETURN_TOTAL,
    ROW_NUMBER() OVER(PARTITION BY ITEM.SALE_ID ORDER BY ITEM.SALE_ID) RN
  FROM OPERATIONAL.POS_CUSTOMER_RECEIPT_LINE_ITEMS ITEM,
    OPERATIONAL.POS_CUSTOMER_PAYMENTS CUST
  WHERE ITEM.SALE_ID=CUST.SALE_ID
    )
WHERE RN=1) RET
ON RET.R10_TRANSACTION_ID=CUST_RECPT.SALE_ID ))
