CREATE OR REPLACE TABLE CUSTOMER_PRODUCT.POS_TENDER_PICKUP_DIM 
AS (
select  DISTINCT CUST_RECPT.SALE_ID AS TRANSACTION_NUM, 
CUST_RECPT.SALE_COMPLETE_DTTIME  AS TRANSACTION_DTTIME, 
CUST_RECPT.SALE_ID as POS_TRANSACTION_ID,
CUST_RECPT.OFFICE_ID AS LOCATION_ID, 
'' as REGISTER_NUM,
'Safe Account' AS SAFE_ID,
case when REGEXP_CONTAINS(TRIM(CONSULTANT_ID), "[a-zA-Z]") 
then ENT.EMPLOYEE_ID else EMP_ID.EMPLOYEE_ID end as EMPLOYEE_ID,
case when REGEXP_CONTAINS(TRIM(CONSULTANT_ID), "[a-zA-Z]") 
then ENT.EMPLOYEE_NAME else EMP_ID.EMPLOYEE_NAME end as EMPLOYEE_NM,
case when CASH_AMT=0 then 0 else CASH_AMT*-1 end as CASH_AMT,
case when CHECK_AMT=0 then 0 else CHECK_AMT*-1 end as CHECK_AMT,
case when CC_NET=0 then 0 else CC_NET*-1 end as CREDITCARD_AMT,
'R' AS ADJUSTMENT,
'' as REASON,
'' as ORIGINAL_TRANSACTION_NUM,
CUST_RECPT.SALE_COMPLETE_DTTIME  as CREATE_DTTIME
FROM OPERATIONAL.POS_CUSTOMER_PAYMENTS as CUST_RECPT 
INNER JOIN OPERATIONAL.POS_CUSTOMER_RECEIPT_LINE_ITEMS as ITEM
ON CUST_RECPT.SALE_ID=ITEM.SALE_ID
AND  TRIM(CUST_RECPT.CUST_RECPT_VOID_RET_IND) IS NULL
AND TRIM(ITEM.ITEM_TYPE_ID)='TENDER PICKUP'
LEFT OUTER JOIN 
(select distinct TRIM(EMPLOYEE_ID) as EMPLOYEE_ID,CONCAT(TRIM(LEGAL_FIRST_NM)," ",TRIM(LEGAL_LAST_NM)) as EMPLOYEE_NAME from CUSTOMERS.EMPLOYEE_PROFILE_DIM where ACTIVE_FLG='Y') as EMP_ID
ON TRIM(CUST_RECPT.CONSULTANT_ID) = TRIM(EMP_ID.EMPLOYEE_ID)
LEFT OUTER JOIN 
(select DISTINCT TRIM(EMPLOYEE_ID) as EMPLOYEE_ID,TRIM(ENT_ID) as ENT_ID,CONCAT(TRIM(LEGAL_FIRST_NM)," ",TRIM(LEGAL_LAST_NM)) as EMPLOYEE_NAME from CUSTOMERS.EMPLOYEE_PROFILE_DIM where ACTIVE_FLG='Y') as ENT
ON TRIM(CUST_RECPT.CONSULTANT_ID) = TRIM(ENT.ENT_ID)
WHERE (CASH_AMT!=0 OR CHECK_AMT!=0 OR CC_NET!=0)
)
