SELECT 
LTRIM(RTRIM(CONVERT(CHAR, ASSOC_CD))) AS ASSOC_CD,
LTRIM(RTRIM(CONVERT(CHAR, CLB_CD))) AS CLB_CD,
LTRIM(RTRIM(CONVERT(CHAR, OFC_ID))) AS CHAR, OFC_ID,
LTRIM(RTRIM(CONVERT(CHAR, SALE_ID))) AS SALE_ID,
LTRIM(RTRIM(CONVERT(CHAR, PYMT_ID))) AS PYMT_ID,
LTRIM(RTRIM(CONVERT(CHAR, CUST_PYMT_AMT))) AS CUST_PYMT_AMT,
LTRIM(RTRIM(CONVERT(CHAR, CUST_PYMT_DT,121))) AS CUST_PYMT_DT,
LTRIM(RTRIM(CONVERT(CHAR, CUST_PYMT_TYP_ID))) AS CUST_PYMT_TYP_ID,
LTRIM(RTRIM(CONVERT(CHAR, CUST_BAL_CLR))) AS CUST_BAL_CLR,
LTRIM(RTRIM(CONVERT(CHAR, WKST_ID))) AS WKST_ID,
LTRIM(RTRIM(CONVERT(CHAR, CONSULTANT_ID))) AS CONSULTANT_ID,
LTRIM(RTRIM(CONVERT(CHAR, GL_ACCT_NR))) AS GL_ACCT_NR,
LTRIM(RTRIM(CONVERT(CHAR, UPLOAD_TRANS_NR))) AS UPLOAD_TRANS_NR,
LTRIM(RTRIM(CONVERT(CHAR, BAL_SET_ID))) AS BAL_SET_ID,
LTRIM(RTRIM(CONVERT(CHAR, PYMT_STATUS))) AS PYMT_STATUS,
LTRIM(RTRIM(CONVERT(CHAR, LAST_UPDATE,121))) AS LAST_UPDATE,
LTRIM(RTRIM(CONVERT(CHAR, NUMBER_OF_100S))) AS NUMBER_OF_100S
FROM pos_prd.dbo.cust_pymt
WHERE CONVERT(CHAR,LAST_UPDATE,127) >= 'max_date'
