select
LTRIM(RTRIM( ITEM.ASSOC_CD)) AS ASSOC_CD,
LTRIM(RTRIM( ITEM.CLB_CD)) AS CLB_CD,
LTRIM(RTRIM( ITEM.OFC_ID)) AS OFC_ID,
LTRIM(RTRIM(CONVERT(CHAR, ITEM.SALE_ID))) AS SALE_ID,
LTRIM(RTRIM(CONVERT(CHAR, ITEM.CUST_RECPT_LN_ITM_ID))) AS CUST_RECPT_LN_ITM_ID,
LTRIM(RTRIM(CONVERT(CHAR, GROUP_IND))) AS GROUP_IND,
LTRIM(RTRIM( SOURCE_CD)) AS SOURCE_CD,
LTRIM(RTRIM(CONVERT(CHAR, OFR_ID))) AS OFR_ID,
LTRIM(RTRIM( CUST_RECPT_LN_ITM_INV_ID)) AS CUST_RECPT_LN_ITM_INV_ID,
LTRIM(RTRIM( CUST_RECPT_LN_ITM_DSC_TX)) AS CUST_RECPT_LN_ITM_DSC_TX,
LTRIM(RTRIM(CONVERT(CHAR, CUST_RECPT_LN_ITM_QTY_CT))) AS CUST_RECPT_LN_ITM_QTY_CT,
LTRIM(RTRIM( CUST_RECPT_LN_ITM_UOM_CD)) AS CUST_RECPT_LN_ITM_UOM_CD,
LTRIM(RTRIM(CONVERT(CHAR, CUST_RECPT_LN_ITM_CHG_ITM))) AS CUST_RECPT_LN_ITM_CHG_ITM,
LTRIM(RTRIM(CONVERT(CHAR, CUST_RECPT_LN_ITM_TAX_ITM))) AS CUST_RECPT_LN_ITM_TAX_ITM,
LTRIM(RTRIM( CUST_RECPT_VD_RET_IND)) AS CUST_RECPT_VD_RET_IND,
LTRIM(RTRIM(CONVERT(CHAR, ITEM.CUST_RECPT_RET_RSN_CD))) AS CUST_RECPT_RET_RSN_CD,
LTRIM(RTRIM( CUST_RECPT_LN_ITM_SER_NR)) AS CUST_RECPT_LN_ITM_SER_NR,
LTRIM(RTRIM( GL_ACCT_NR)) AS GL_ACCT_NR,
LTRIM(RTRIM(CONVERT(CHAR, ITEM.UPLOAD_TRANS_NR))) AS UPLOAD_TRANS_NR,
LTRIM(RTRIM(CONVERT(CHAR, ITEM.SHIPPING_AMT))) AS SHIPPING_AMT,
LTRIM(RTRIM(CONVERT(CHAR, SHIPPING_QTY))) AS SHIPPING_QTY,
LTRIM(RTRIM(CONVERT(CHAR, ITEM.HANDLING_AMT))) AS HANDLING_AMT,
LTRIM(RTRIM(CONVERT(CHAR, HANDLING_QTY))) AS HANDLING_QTY,
LTRIM(RTRIM(CONVERT(CHAR, LIST_PRC))) AS LIST_PRC,
LTRIM(RTRIM(CONVERT(CHAR, NONMEMBER_PRC))) AS NONMEMBER_PRC,
LTRIM(RTRIM(CONVERT(CHAR, MEMBER_PRC))) AS MEMBER_PRC,
LTRIM(RTRIM(CONVERT(CHAR, EMPLOYEE_PRC))) AS EMPLOYEE_PRC,
LTRIM(RTRIM(CONVERT(CHAR, SALE_PRC))) AS SALE_PRC,
LTRIM(RTRIM(CONVERT(CHAR, SPECIAL_TAX_AMT))) AS SPECIAL_TAX_AMT,
LTRIM(RTRIM( INV_ITM_TYP)) AS INV_ITM_TYP,
LTRIM(RTRIM(CONVERT(CHAR, DYNAMIC_TYP))) AS DYNAMIC_TYP,
LTRIM(RTRIM( USER_STRING)) AS USER_STRING,
LTRIM(RTRIM(CONVERT(CHAR, USER_DT,121))) AS USER_DT,
LTRIM(RTRIM(CONVERT(CHAR, USER_DEC))) AS USER_DEC,
LTRIM(RTRIM( PRODUCT_INCPL_IND)) AS PRODUCT_INCPL_IND,
LTRIM(RTRIM( PRICE_OVERRIDE_IND)) AS PRICE_OVERRIDE_IND,
LTRIM(RTRIM(CONVERT(CHAR, ORD_FULFILLMENT_QTY))) AS ORD_FULFILLMENT_QTY,
LTRIM(RTRIM(CONVERT(CHAR, INV_SER_ID))) AS INV_SER_ID,
LTRIM(RTRIM(CONVERT(CHAR, INV_SKU_ID))) AS INV_SKU_ID,
LTRIM(RTRIM(CONVERT(CHAR, rcp.LAST_UPDATE,121))) AS LAST_UPDATE,
LTRIM(RTRIM(CONVERT(CHAR, INV_SKU_POSITION))) AS INV_SKU_POSITION,
LTRIM(RTRIM( ITM_ADDITIONAL_INFO_TXT)) AS ITM_ADDITIONAL_INFO_TXT,
LTRIM(RTRIM(CONVERT(CHAR,WARRANTY_ID))) AS WARRANTY_ID,
LTRIM(RTRIM(CONVERT(VARCHAR(100),cust_recpt_ln_itm_insurance_payment.insurance_payment_id ))) AS INSURANCE_PAYMENT_ID,
LTRIM(RTRIM(CONVERT(CHAR,cust_recpt_ln_itm_insurance_payment.company_id))) AS COMPANY_ID,
LTRIM(RTRIM(CONVERT(CHAR,cust_recpt_ln_itm_insurance_payment.source_system))) AS SOURCE_SYSTEM,
LTRIM(RTRIM(CONVERT(CHAR,cust_recpt_ln_itm_insurance_payment.product_type))) AS PRODUCT_TYPE,
LTRIM(RTRIM(CONVERT(CHAR,cust_recpt_ln_itm_insurance_payment.product_prefix))) AS PRODUCT_PREFIX,
LTRIM(RTRIM(CONVERT(CHAR,cust_recpt_ln_itm_insurance_payment.policy_number))) AS POLICY_NUM,
LTRIM(RTRIM(CONVERT(CHAR,cust_recpt_ln_itm_insurance_payment.state_code))) AS STATE_CD,
LTRIM(RTRIM(CONVERT(CHAR,cust_recpt_ln_itm_insurance_payment.payment_amt))) AS PAYMENT_AMT
FROM
pos_prd.dbo.cust_recpt_ln_itm ITEM
INNER JOIN
pos_prd.dbo.cust_recpt rcp
on rcp.sale_id=ITEM.sale_id
LEFT OUTER JOIN
pos_prd.dbo.cust_recpt_ln_itm_insurance_payment
on (
 ITEM.sale_id=cust_recpt_ln_itm_insurance_payment.sale_id
 and ITEM.cust_recpt_ln_itm_id=cust_recpt_ln_itm_insurance_payment.cust_recpt_ln_itm_id )
WHERE
CONVERT(CHAR,rcp.LAST_UPDATE,127) >= 'max_date'
and sale_complete_dt is not null
