INSERT INTO CUSTOMER_PRODUCT.INSURANCE_CLAIMS_DIM (
 RECORD_SOURCE	
,DATA_SOURCE_NM	
,CLAIM_NUM	
,CLAIM_OPEN_DT	
,CLAIM_CLOSED_DT	
,AGREEMENT_NUM	
,CLAIM_LOCATION	
,CLAIMANT_NM	
,CLAIMS_ADJUSTER_NM	
,CLAIMS_ADJUSTER_PHONE_NUM	
,EXPOSURE_OPEN_DT	
,EXPOSURE_CLOSED_DT	
,LOSS_DT	
,TYPE_OF_LOSS	
,EXPOSURE_STATUS	
,COVERAGE_CD	
,EXPOSURE_TYPE	
,CLAIMS_ADJUSTER_ID	
,LIABILITY	
,SUBROGATION_AMT	
,PAID_LOSS_AMT	
,TOTAL_LOSS_IND	
,LOAD_DT	
,FILE_ID	
,JOB_RUN_ID	
,SOURCE_SYSTEM_CD	
,CREATE_DTTIME
,UPDATE_DTTIME
)

SELECT RECORD_SOURCE	
,DATA_SOURCE_NM	
,CLAIM_NUM	
,CLAIM_OPEN_DT	
,CLAIM_CLOSED_DT	
,AGREEMENT_NUM	
,CLAIM_LOCATION	
,CLAIMANT_NM	
,CLAIMS_ADJUSTER_NM	
,CLAIMS_ADJUSTER_PHONE_NUM	
,EXPOSURE_OPEN_DT	
,EXPOSURE_CLOSED_DT	
,LOSS_DT	
,TYPE_OF_LOSS	
,EXPOSURE_STATUS	
,COVERAGE_CD	
,EXPOSURE_TYPE	
,CLAIMS_ADJUSTER_ID	
,LIABILITY	
,SUBROGATION_AMT	
,PAID_LOSS_AMT	
,TOTAL_LOSS_IND	
,LOAD_DT	
,FILE_ID	
,JOB_RUN_ID	
,SOURCE_SYSTEM_CD	
,CREATE_DTTIME
,UPDATE_DTTIME FROM (
SELECT RECORD_SOURCE		,	
DATA_SRC_NM		AS DATA_SOURCE_NM	,
CLAIM_NUM		,
SAFE.PARSE_DATE("%Y%m%d", CLAIM_OPEN_DT) AS CLAIM_OPEN_DT		,	
SAFE.PARSE_DATE("%Y%m%d", CLAIM_CLOSED_DT) AS CLAIM_CLOSED_DT		,	
POLICY_NUM	AS AGREEMENT_NUM	,	
CLAIM_LOCATION,
CLAIMANT_NM,
CLAIMS_ADJUSTER_NM,
ADJUSTER_CONTACT_INFO AS CLAIMS_ADJUSTER_PHONE_NUM,
SAFE.PARSE_DATE("%Y%m%d", EXPOSURE_OPEN_DT) AS EXPOSURE_OPEN_DT		,
SAFE.PARSE_DATE("%Y%m%d", EXPOSURE_CLOSED_DT) AS EXPOSURE_CLOSED_DT		,	
SAFE.PARSE_DATE("%Y%m%d", LOSS_DT) AS LOSS_DT			,
TYPE_OF_LOSS		,	
EXPOSURE_STATUS		,	
TRIM(COVERAGE_CD)	AS COVERAGE_CD	,	
EXPOSURE_TYPE		,	
CLAIMS_ADJUSTER_ID	,	
LIABILITY			,
SUBROGATION_AMT		,	
PAID_LOSS_AMT		,	
TRIM(TOTAL_LOSS_IND)	AS TOTAL_LOSS_IND	,	
SAFE.PARSE_DATETIME('%m/%d/%Y %H:%M:%S',LOAD_DT)	AS LOAD_DT		,
FILE_ID,
'V_JOB_RUN_ID' AS JOB_RUN_ID,
'CLAIMS' AS SOURCE_SYSTEM_CD,
CURRENT_DATETIME() AS CREATE_DTTIME,
CURRENT_DATETIME() AS UPDATE_DTTIME ,
ROW_NUMBER() OVER (PARTITION BY  RECORD_SOURCE, CLAIM_NUM, CLAIM_OPEN_DT,  POLICY_NUM, CLAIMANT_NM, EXPOSURE_OPEN_DT, EXPOSURE_STATUS, COVERAGE_CD  ORDER BY SAFE.PARSE_DATE("%Y%m%d", LOSS_DT) DESC) RN
FROM LANDING.WORK_INSURANCE_CLAIMS)
WHERE RN = 1