UPDATE CUSTOMER_PRODUCT.INSURANCE_CLAIMS_DIM A SET 
A.DATA_SOURCE_NM	 = B.DATA_SOURCE_NM	
,A.CLAIM_CLOSED_DT	 = B.CLAIM_CLOSED_DT	
,A.CLAIM_LOCATION	 = B.CLAIM_LOCATION	
,A.CLAIMS_ADJUSTER_NM	 = B.CLAIMS_ADJUSTER_NM	
,A.CLAIMS_ADJUSTER_PHONE_NUM	 = B.CLAIMS_ADJUSTER_PHONE_NUM	
,A.EXPOSURE_CLOSED_DT	 = B.EXPOSURE_CLOSED_DT	
,A.LOSS_DT	 = B.LOSS_DT	
,A.TYPE_OF_LOSS	 = B.TYPE_OF_LOSS	
,A.EXPOSURE_TYPE	 = B.EXPOSURE_TYPE	
,A.CLAIMS_ADJUSTER_ID	 = B.CLAIMS_ADJUSTER_ID	
,A.LIABILITY	 = B.LIABILITY	
,A.SUBROGATION_AMT	 = B.SUBROGATION_AMT	
,A.PAID_LOSS_AMT	 = B.PAID_LOSS_AMT	
,A.TOTAL_LOSS_IND	 = B.TOTAL_LOSS_IND	
,A.LOAD_DT	 = B.LOAD_DT	
,A.FILE_ID	 = B.FILE_ID	
,A.UPDATE_DTTIME = B.UPDATE_DTTIME
FROM (
SELECT RECORD_SOURCE		,	
DATA_SRC_NM		AS DATA_SOURCE_NM	,
CLAIM_NUM		,
SAFE.PARSE_DATE("%Y%m%d", CLAIM_OPEN_DT) AS CLAIM_OPEN_DT		,	
SAFE.PARSE_DATE("%Y%m%d", CLAIM_CLOSED_DT) AS CLAIM_CLOSED_DT		,	
POLICY_NUM	AS AGREEMENT_NUM	,	
CLAIM_LOCATION,
CLAIMANT_NM,
CLAIMS_ADJUSTER_NM,
ADJUSTER_CONTACT_INFO AS CLAIMS_ADJUSTER_PHONE_NUM,
SAFE.PARSE_DATE("%Y%m%d", EXPOSURE_OPEN_DT) AS EXPOSURE_OPEN_DT		,
SAFE.PARSE_DATE("%Y%m%d", EXPOSURE_CLOSED_DT) AS EXPOSURE_CLOSED_DT		,	
SAFE.PARSE_DATE("%Y%m%d", LOSS_DT) AS LOSS_DT			,
TYPE_OF_LOSS		,	
EXPOSURE_STATUS		,	
COVERAGE_CD		,	
EXPOSURE_TYPE		,	
CLAIMS_ADJUSTER_ID	,	
LIABILITY			,
SUBROGATION_AMT		,	
PAID_LOSS_AMT		,	
TOTAL_LOSS_IND		,	
SAFE.PARSE_DATETIME('%m/%d/%Y %H:%M:%S',LOAD_DT)	AS LOAD_DT		,
FILE_ID,
CURRENT_DATETIME() UPDATE_DTTIME ,
ROW_NUMBER() OVER (PARTITION BY  RECORD_SOURCE, CLAIM_NUM, CLAIM_OPEN_DT,  POLICY_NUM, CLAIMANT_NM, EXPOSURE_OPEN_DT, EXPOSURE_STATUS, COVERAGE_CD  ORDER BY SAFE.PARSE_DATE("%Y%m%d", LOSS_DT) DESC) RN
FROM LANDING.WORK_INSURANCE_CLAIMS
) B
WHERE A.RECORD_SOURCE = B.RECORD_SOURCE 
AND A.CLAIM_NUM = B.CLAIM_NUM 
AND A.CLAIM_OPEN_DT = B.CLAIM_OPEN_DT
AND A.AGREEMENT_NUM = B.AGREEMENT_NUM
AND A.CLAIMANT_NM = B.CLAIMANT_NM
AND A.EXPOSURE_OPEN_DT = B.EXPOSURE_OPEN_DT
AND A.EXPOSURE_STATUS = B.EXPOSURE_STATUS
AND A.COVERAGE_CD = B.COVERAGE_CD 
AND B.RN = 1
