DELETE FROM CUSTOMER_PRODUCT.INSURANCE_CLAIMS_DIM A
WHERE EXISTS 
(SELECT 1 FROM LANDING.WORK_INSURANCE_CLAIMS B
WHERE A.RECORD_SOURCE = B.RECORD_SOURCE 
AND A.CLAIM_NUM = B.CLAIM_NUM 
AND A.CLAIM_OPEN_DT = SAFE.PARSE_DATE("%Y%m%d", B.CLAIM_OPEN_DT)
AND A.AGREEMENT_NUM = B.POLICY_NUM
AND A.CLAIMANT_NM = B.CLAIMANT_NM
AND A.EXPOSURE_OPEN_DT = SAFE.PARSE_DATE("%Y%m%d", B.EXPOSURE_OPEN_DT)
AND A.EXPOSURE_STATUS = B.EXPOSURE_STATUS
AND A.COVERAGE_CD = B.COVERAGE_CD )