select ARO_PAYMENT_DECLINE_DESC from
(select 1 ROW_NUM,'ARIA_ACCT_ID	PAYMENT_DT	AMOUNT_CHARGED	PAYMENT_METHOD	BILLING_ADDRESS	CITY	STATE	ZIP	EMAIL_ADDRESS	DECLINE_REASON_CODE	DECLINE_REASON_DESCRIPTION	PHONE_NUMBER	TERM_EXPIRATION_DT	CREDIT_CARD	MEMBER_NUM	INSURANCE_PRODUCTS_OWNED	TENURE	MEMBERSHIP_LEVEL	NUMBER_OF_ASSOCIATES	AUTO_RENEWAL_ENROLLED_DT	NUM_OF_ERS_EVENTS	FIRST_NAME	LAST_NAME' AS ARO_PAYMENT_DECLINE_DESC
from  OPERATIONAL.MEMBERSHIP_AR_DECLINED_PAYMENTS where 1=1
UNION DISTINCT
select 2 ROW_NUM, 
 CONCAT('"',
IFNULL(CAST('' AS STRING),''),
'"',FORMAT('\t'),'"',
IFNULL(FORMAT_DATETIME("%Y/%m/%d %H:%M:%S",PAYMENT_DT),''),
'"',FORMAT('\t'),
IFNULL(FORMAT("%.*f",2,CAST(AMT_CHARGED AS FLOAT64) + .0001),''),
FORMAT('\t'),'"',
IFNULL(PAYMENT_METHOD,''),
'"',FORMAT('\t'),'"',
IFNULL(M.BILLING_ADDRESS_LINE1,''),
'"',FORMAT('\t'),'"',
IFNULL(BILLING_CITY,''),
'"',FORMAT('\t'),'"',
IFNULL(BILLING_STATE,''),
'"',FORMAT('\t'),'"',
IFNULL(BILLING_ZIP,''),
'"',FORMAT('\t'),'"',
IFNULL(EMAIL_ADDRESS,''),
'"',FORMAT('\t'),'"',
IFNULL(CAST(DECLINE_REASON_CD AS STRING),''),
'"',FORMAT('\t'),'"',
IFNULL(DECLINE_REASON_DESC,''),
'"',FORMAT('\t'),'"',
IFNULL(HOME_PHONE_NUM,''),
'"',FORMAT('\t'),'"',
IFNULL(FORMAT_DATE("%Y/%m/%d 00:00:00",D.TERM_EXPIRATION_DT),''),
'"',FORMAT('\t'),'"',
IFNULL(CREDIT_CARD_NUM_LAST_4,''),
'"',FORMAT('\t'),'"',
IFNULL(D.MEMBER_NUM,''),
'"',FORMAT('\t'),'"',
IFNULL(INSURANCE_PRODUCTS_OWNED,''),
'"',FORMAT('\t'),'"',
IFNULL(TENURE,''),
'"',FORMAT('\t'),'"',
IFNULL(D.MEMBERSHIP_LEVEL,''),
'"',FORMAT('\t'),
IFNULL(CAST(NUM_OF_ASSOCIATES AS STRING),''),
FORMAT('\t'),'"',
IFNULL(FORMAT_DATE("%Y/%m/%d 00:00:00",AUTO_RENEWAL_ENROLLED_DT),''),
'"',FORMAT('\t'),
IFNULL(CAST(NUM_OF_ERS_EVENTS AS STRING),''),
FORMAT('\t'),'"',
IFNULL(FIRST_NM,''),
'"',FORMAT('\t'),'"',
IFNULL(LAST_NM,'')) AS ARO_PAYMENT_DECLINE_DESC
 from OPERATIONAL.MEMBERSHIP_AR_DECLINED_PAYMENTS D
 LEFT OUTER JOIN
 CUSTOMERS.CONNECTSUITE_MEMBER M
 ON D.MEMBER_NUM=M.MEMBER_NUM
WHERE EVENT_TYPE_CD='HARD_DECLINE'
   and CREATE_DTTIME>'{{ prev_execution_date }}'
 ) 
 order by ROW_NUM asc
