CREATE OR REPLACE TABLE COMPLIANCE.CCPA_CUSTOMER_CONTACT  AS
SELECT DISTINCT  C.CUSTOMER_MDM_KEY
,CONCAT(FIRST_NM,' ', LAST_NM) AS REAL_NM
,FIRST_NM
,LAST_NM
,MIDDLE_NM
,PREFFERRED_NM AS ALLIAS_NM
,NAME_SUFFIX_CD
,SALUTATION_CD
,BIRTH_DT
,GENDER_CD
,MARITAL_STATUS
,DECEASED_IND
,CC.TYPE
,CASE WHEN IFNULL(TRIM(CC.ADDRESS_LINE1),'') = '' AND TRIM(C.ADDRESS_LINE1) IS NOT NULL  THEN  CONCAT(IFNULL(C.ADDRESS_LINE1,''),' ',IFNULL(C.ADDRESS_LINE2,''),', ',IFNULL(C.CITY,''),', ',IFNULL(C.STATE,''),', ',IFNULL(C.ZIP_CD,''))
     WHEN IFNULL(TRIM(C.ADDRESS_LINE1),'') = '' OR IFNULL(TRIM(CC.ADDRESS_LINE1),'') = '' THEN CONCAT(IFNULL(MCC.ADDRESS_LINE1,''),' ',IFNULL(MCC.ADDRESS_LINE2,''),', ',IFNULL(MCC.CITY,''),', ',IFNULL(MCC.STATE,''),', ',IFNULL(MCC.ZIP_CD,''))
ELSE CONCAT(IFNULL(CC.ADDRESS_LINE1,''),' ',IFNULL(CC.ADDRESS_LINE2,''),', ',IFNULL(CC.CITY,''),', ',IFNULL(CC.STATE,''),', ',IFNULL(CC.ZIP_CD,'')) END AS ADDRESS
,CASE WHEN IFNULL(TRIM(CC.ADDRESS_LINE1),'') = '' AND TRIM(C.ADDRESS_LINE1) IS NOT NULL THEN C.ADDRESS_LINE1
     WHEN IFNULL(TRIM(C.ADDRESS_LINE1),'') = '' OR IFNULL(TRIM(CC.ADDRESS_LINE1),'') = '' THEN MCC.ADDRESS_LINE1
ELSE CC.ADDRESS_LINE1 END AS ADDRESS_LINE1
,CASE WHEN IFNULL(TRIM(CC.ADDRESS_LINE1),'') = '' AND TRIM(C.ADDRESS_LINE1) IS NOT NULL  THEN C.ADDRESS_LINE2
     WHEN IFNULL(TRIM(C.ADDRESS_LINE1),'') = '' OR IFNULL(TRIM(CC.ADDRESS_LINE1),'') = '' THEN MCC.ADDRESS_LINE2
ELSE CC.ADDRESS_LINE2 END AS ADDRESS_LINE2
,CASE WHEN IFNULL(TRIM(CC.ADDRESS_LINE1),'') = '' AND TRIM(C.ADDRESS_LINE1) IS NOT NULL  THEN C.CITY
     WHEN IFNULL(TRIM(C.ADDRESS_LINE1),'') = '' OR IFNULL(TRIM(CC.ADDRESS_LINE1),'') = '' THEN MCC.CITY
ELSE CC.CITY END AS CITY
,CASE WHEN IFNULL(TRIM(CC.ADDRESS_LINE1),'') = '' AND TRIM(C.ADDRESS_LINE1) IS NOT NULL  THEN C.STATE
     WHEN IFNULL(TRIM(C.ADDRESS_LINE1),'') = '' OR IFNULL(TRIM(CC.ADDRESS_LINE1),'') = '' THEN MCC.STATE
ELSE CC.STATE END AS STATE
,CASE WHEN IFNULL(TRIM(CC.ADDRESS_LINE1),'') = '' AND TRIM(C.ADDRESS_LINE1) IS NOT NULL THEN C.ZIP_CD
      WHEN IFNULL(TRIM(C.ADDRESS_LINE1),'') = '' OR IFNULL(TRIM(CC.ADDRESS_LINE1),'') = '' THEN MCC.ZIP_CD
ELSE CC.ZIP_CD END AS ZIP_CD
,CASE WHEN IFNULL(TRIM(CC.EMAIL_ADDRESS),'') = '' AND TRIM(C.EMAIL_ADDRESS) IS NOT NULL  THEN C.EMAIL_ADDRESS
    WHEN IFNULL(TRIM(C.EMAIL_ADDRESS),'') = '' OR IFNULL(TRIM(CC.EMAIL_ADDRESS),'') = '' THEN MCC.EMAIL_ADDRESS
ELSE CC.EMAIL_ADDRESS END AS EMAIL_ADDRESS
,CASE WHEN IFNULL(TRIM(CC.PHONE_NUM),'') = '' AND TRIM(C.PHONE_NUM) IS NOT NULL THEN C.PHONE_NUM
     WHEN IFNULL(TRIM(C.PHONE_NUM),'') = '' OR IFNULL(TRIM(CC.PHONE_NUM),'') = '' THEN MCC.PHONE_NUM
ELSE CC.PHONE_NUM END AS PHONE_NUM
FROM CUSTOMERS.MDM_CUSTOMER_CONTACT_DIM CC
JOIN CUSTOMERS.MDM_CUSTOMER_DIM C ON C.CUSTOMER_MDM_KEY = CC.CUSTOMER_MDM_KEY
JOIN (SELECT CUSTOMER_MDM_KEY, MAX(ADDRESS_LINE1) AS ADDRESS_LINE1, MAX(ADDRESS_LINE2) AS ADDRESS_LINE2, MAX(CITY) AS CITY, MAX(STATE) AS STATE,
            MAX(ZIP_CD) AS ZIP_CD, MAX(EMAIL_ADDRESS) AS EMAIL_ADDRESS, MAX(PHONE_NUM) AS PHONE_NUM
     FROM CUSTOMERS.MDM_CUSTOMER_CONTACT_DIM GROUP BY CUSTOMER_MDM_KEY ) MCC ON MCC.CUSTOMER_MDM_KEY = CC.CUSTOMER_MDM_KEY 
