CREATE OR REPLACE TABLE LANDING.WORK_WD_EMPLOYEE AS  
SELECT E.EMPLOYEE_ID AS EMPLOYEE_ID
, ENT_ID AS ENT_ID
, LEGAL_FIRST_NM AS LEGAL_FIRST_NM
, LEGAL_MIDDLE_NM AS LEGAL_MIDDLE_NM
, LEGAL_LAST_NM AS LEGAL_LAST_NM
, LEGAL_SOCIAL_SUFFIX AS LEGAL_SUFFIX
, HIRE_DT AS HIRE_DT
, TERMINATION_DT AS TERMINATION_DT
, EMPLOYEE_STATUS AS EMPLOYEE_STATUS
, WORKER_TYPE AS WORKER_TYPE
, BRANCH_NUM AS LOCATION_ID
, E.EMAIL_ADDRESS AS EMAIL_ADDRESS
, E.SECONDARY_EMAIL AS SECONDARY_EMAIL_ADDRESS
, E.PHONE_NUM AS PHONE_NUM
, E.PHONE_EXTSN AS PHONE_EXTENSION
, E.LIFE_ID AS LIFE_ID
, E.PC10_ID AS PAS_ID
, E.PC03_ID AS INSURANCE_REP_ID
, E.TRAVEL_ID AS TRAVEL_ID
, E.COMPANY AS COMPANY
, E.CHANGE_EFFECTIVE_DT AS CHANGE_EFFECTIVE_DT
, E.LANGUAGE_TYPE_CD AS LANGUAGE_TYPE_CD
, E.PRFS_DESIG_EFFECTIVE_DT AS PRFS_DESIG_EFFECTIVE_DT
, E.PRFS_DESIG_EXPIRATION_DT AS PRFS_DESIG_EXPIRATION_DT
, E.PRFS_DESIG_TYPE_CD AS PRFS_DESIG_TYPE_CD
, E.COST_CENTER AS COST_CENTER_CD
--, COST_CENTER_DESC AS COST_CENTER_DESC
, RESIDENT_LICENSE_IND AS RESIDENT_LICENSE_IND
, LICENSE_NUM AS LICENSE_NUM
, LICENSE_ST AS LICENSE_STATE
, LICENSE_EFFECTIVE_DT AS LICENSE_EFFECTIVE_DT
, LICENSE_EXPIRATION_DT AS LICENSE_EXPIRATION_DT
, LICENSE_TYPE AS LICENSE_TYPE_CD
, E.JOB_CD AS JOB_CD
, J.JOB_CD_DESC AS JOB_CD_DESC
, J.JOB_CD_EFFECTIVE_DT AS JOB_CD_EFFECTIVE_DT
, E.SUPERVISOR_ID
, E.ORGANIZATION_ID AS ORGANIZATION_CD
, WORKER_AVAYA_ID AS WORKER_AVAYA_ID
/*, CASE 
   WHEN LEVEL_10 IS NOT NULL THEN 10
   WHEN LEVEL_09 IS NOT NULL THEN 9 
	 WHEN LEVEL_08 IS NOT NULL THEN 8
	 WHEN LEVEL_07 IS NOT NULL THEN 7
	 WHEN LEVEL_06 IS NOT NULL THEN 6
	 WHEN LEVEL_05 IS NOT NULL THEN 5
	 WHEN LEVEL_04 IS NOT NULL THEN 4
	 WHEN LEVEL_03 IS NOT NULL THEN 3
	 WHEN LEVEL_02 IS NOT NULL THEN 2
	 WHEN LEVEL_01 IS NOT NULL THEN 1
	 ELSE 0
   END	- 1  AS HIERARCHY_LEVEL*/
, CASE 
   WHEN LEVEL_10 IS NOT NULL THEN '10'
   WHEN LEVEL_09 IS NOT NULL THEN '9' 
	 WHEN LEVEL_08 IS NOT NULL THEN '8'
	 WHEN LEVEL_07 IS NOT NULL THEN '7'
	 WHEN LEVEL_06 IS NOT NULL THEN '6'
	 WHEN LEVEL_05 IS NOT NULL THEN '5'
	 WHEN LEVEL_04 IS NOT NULL THEN '4'
	 WHEN LEVEL_03 IS NOT NULL THEN '3'
	 WHEN LEVEL_02 IS NOT NULL THEN '2'
	 WHEN LEVEL_01 IS NOT NULL THEN '1'
	 ELSE '0'
   END AS SUPERVISOR_HIERARCHY_LEVEL
, SE.ROLE_ID AS SAM_ROLE_ID
,SR.NAME  AS SAM_ROLE_DESC
,SE.LOGIN_ENABLED AS SAM_LOGIN_STATUS
,SA.SALES_AGENT_KEY AS SALES_AGENT_KEY 
,CASE WHEN SA.INACTIVE_IND = 'Y' THEN 'INACTIVE' ELSE 'ACTIVE' END AS SALES_AGENT_STATUS
, E.WD_ID AS WD_ID
, 'V_FILE_ID' AS FILE_ID  
, CAST(NULL AS BYTES) MD5_VALUE
FROM LANDING.CUR_WD_EMPLOYEE E
LEFT OUTER JOIN LANDING.WORKDAY_COST_CENTER C ON CAST(E.COST_CENTER AS STRING) = C.COST_CENTER_CD
LEFT OUTER JOIN LANDING.WORKDAY_JOB_CODES J ON E.JOB_CD = J.JOB_CD
LEFT JOIN (SELECT DISTINCT SUPERVISOR_ID,EMPLOYEE_ID,WD_ID FROM  LANDING.CUR_WD_EMPLOYEE) SUPERVISIOR ON E.SUPERVISOR_ID=SUPERVISIOR.WD_ID 
LEFT OUTER JOIN (
SELECT * FROM (
SELECT * , ROW_NUMBER() OVER ( PARTITION BY MANAGER,ORG_CD ) RN   FROM  LANDING.WORKDAY_SUPERVISORY_HIERARCHY ) SH
WHERE RN=1 ) SH ON (CAST(SUPERVISIOR.EMPLOYEE_ID AS STRING) = SUBSTR(SUBSTR(SH.MANAGER, -7),1,6) AND E.ORGANIZATION_ID=SH.ORG_CD)
LEFT OUTER JOIN LANDING.SAM_EMPLOYEE_DIM SE ON E.EMPLOYEE_ID  = SE.EMPLOYEE_ID
LEFT JOIN LANDING.SAM_ROLES SR ON SE.ROLE_ID  = SR.ROLE_ID
LEFT JOIN 
(SELECT * FROM 
(SELECT EMPLOYEE_ID,SALES_AGENT_KEY,INACTIVE_IND, ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY SALES_AGENT_UPDATE_DT DESC) RN  FROM CUSTOMERS.SALES_AGENT)
WHERE RN=1) SA ON E.EMPLOYEE_ID  = SA.EMPLOYEE_ID;