INSERT INTO CUSTOMER_PRODUCT.LOCATION_DIM (
LOCATION_ID	,		
LOCATION_NM	,		
LOCATION_STATUS,			
LOCATION_TYPE_CD,			
--LOCATION_OPEN_DT,		
LOCATION_EFFECTIVE_DT,
CS_M_BRANCH_KEY	,		
DIVISON_KEY	,		
SAM_BRANCH_KEY	,		
CHANNEL_NM		,	
ADDRESS_LINE1	,		
ADDRESS_LINE2	,		
ADDRESS_LINE3	,		
CITY			,
STATE_CD		,	
ZIP_CD			,
PHONE_NUM		,	
PHONE_EXTENSION	,		
LOCATION_HIERARCHY_NM,			
FILE_ID	,		
EFFECTIVE_START_DT,
EFFECTIVE_END_DT,
ACTIVE_FLG,
MD5_VALUE,
UPDATE_DTTIME)
SELECT LOCATION_ID	,		
LOCATION_NM	,		
LOCATION_STATUS,			
LOCATION_TYPE_CD,			
--LOCATION_OPEN_DT,	
LOCATION_EFFECTIVE_DT,
CS_M_BRANCH_KEY	,		
DIVISON_KEY	,		
SAM_BRANCH_KEY	,		
CHANNEL_NM		,	
ADDRESS_LINE1	,		
ADDRESS_LINE2	,		
ADDRESS_LINE3	,		
CITY			,
STATE_CD		,	
ZIP_CD			,
PHONE_NUM		,	
PHONE_EXTENSION	,		
LOCATION_HIERARCHY_NM,			
FILE_ID	,	
PARSE_DATE("%Y%m%d",'V_FILE_ID'),
CAST('9999-12-31' AS DATE),
'Y',
MD5_VALUE,
current_datetime()
FROM (
SELECT WORK_DIM.*,
MD5(CONCAT(COALESCE(CAST(LOCATION_ID AS STRING), ''),
COALESCE(CAST(LOCATION_NM AS STRING), ''),
COALESCE(CAST(LOCATION_STATUS AS STRING), ''),
COALESCE(CAST(LOCATION_TYPE_CD AS STRING), ''),
COALESCE(CAST(CS_M_BRANCH_KEY AS STRING), ''),
COALESCE(CAST(DIVISON_KEY AS STRING), ''),
COALESCE(CAST(SAM_BRANCH_KEY AS STRING), ''),
COALESCE(CAST(CHANNEL_NM AS STRING), ''),
COALESCE(CAST(ADDRESS_LINE1 AS STRING), ''),
COALESCE(CAST(ADDRESS_LINE2 AS STRING), ''),
COALESCE(CAST(ADDRESS_LINE3 AS STRING), ''),
COALESCE(CAST(CITY AS STRING), ''),
COALESCE(CAST(STATE_CD AS STRING), ''),
COALESCE(CAST(ZIP_CD AS STRING), ''),
COALESCE(CAST(PHONE_NUM AS STRING), ''),
COALESCE(CAST(PHONE_EXTENSION AS STRING), ''),
COALESCE(CAST(LOCATION_HIERARCHY_NM AS STRING), '')
)) MD5_VALUE 
FROM
(SELECT 
LPAD(B.WD_LOCATION_ID,3,'0') AS LOCATION_ID,
LOCATION_NM AS LOCATION_NM,
SAFE_CAST(LOCATION_STATUS  AS STRING) AS  LOCATION_STATUS,
LOCATION_TYPE_CD  AS LOCATION_TYPE_CD,
--PARSE_DATE('%Y%m%d','V_FILE_ID') AS LOCATION_OPEN_DT,
B.EFFECTIVE_DT AS LOCATION_EFFECTIVE_DT,
SAFE_CAST(MB.BRN_KY AS STRING) AS CS_M_BRANCH_KEY,
MB.DIV_KY  AS DIVISON_KEY,
SAFE_CAST(SB.BRN_KY AS STRING) AS SAM_BRANCH_KEY,
CASE WHEN UPPER(LOCATION_TYPE_CD)='ONLINEJOIN'THEN 'Internet'
 WHEN UPPER(LOCATION_TYPE_CD)='HEADQUARTERS'THEN 'Main Office'
 WHEN UPPER(LOCATION_TYPE_CD) LIKE 'BRANCH%' THEN  'Field'
 WHEN UPPER(LOCATION_TYPE_CD)='CALL CENTER' THEN 'Contact Center'
 WHEN UPPER(LOCATION_TYPE_CD)='CONTACT CENTER' THEN 'Contact Center'
 --WHEN TRIM(UPPER(LOCATION_TYPE_CD)) = 'CLUB OWNED REPAIR' THEN 'Field'
 ELSE 'Other' END  AS CHANNEL_NM,
STR_ADDRESS_1 AS ADDRESS_LINE1,
STR_ADDRESS_2 AS ADDRESS_LINE2,
STR_ADDRESS_3 AS ADDRESS_LINE3,
CITY_NM AS CITY,
UPPER(STATE_CD) AS STATE_CD,
ZIP_CD AS ZIP_CD,
PHONE_NUM AS PHONE_NUM,
PHONE_EXTNSN AS PHONE_EXTENSION,
CASE WHEN UPPER(LOCATION_TYPE_CD)='CALL CENTER' THEN 'Contact Center'
WHEN UPPER(LOCATION_TYPE_CD)='CONTACT CENTER' THEN 'Contact Center'
ELSE M.MARKET END AS  LOCATION_HIERARCHY_NM,
SAFE_CAST('V_FILE_ID' AS INT64) AS FILE_ID,
'9999-12-31' AS LOCATION_END_DT
FROM LANDING.WORKDAY_LOCATION B
LEFT OUTER JOIN LANDING.WORKDAY_MARKET_HEIRARCHY M ON B.WD_LOCATION_ID = M.BRANCH_NUM
LEFT OUTER JOIN  REFERENCE.CONNECTSUITE_M_BRANCH MB
ON (CASE WHEN  LPAD(B.WD_LOCATION_ID,3,'0') = '999' THEN '998' ELSE WD_LOCATION_ID END) =  LPAD(MB.BRN_CD,3,'0') AND MB.DIV_KY in (1, 104, 105,106,107, 108) AND BRN_KY NOT IN (46062,46061) 
LEFT OUTER JOIN REFERENCE.CONNECTSUITE_CS_BRANCH SB ON LPAD(B.WD_LOCATION_ID,3,'0') = LPAD(SB.BRANCH_NUMBER,3,'0') ) WORK_DIM ) WORK_DIM
WHERE
NOT  EXISTS (SELECT 1 FROM CUSTOMER_PRODUCT.LOCATION_DIM T1 WHERE TO_BASE64(T1.MD5_VALUE) = TO_BASE64(WORK_DIM.MD5_VALUE))