WITH part1 AS (
SELECT
    WD_LOCATION_ID,
    PARSE_DATE('%Y%m%d',REGEXP_EXTRACT(CAST(fileid AS String),r'(\d{2}\d{2}\d{2,4})')) AS file_date,
  STRUCT(
    LOCATION_NAME,
    STR_ADDRESS_1,
    STR_ADDRESS_2,
    STR_ADDRESS_3,
    CITY_NM,
    STATE_CD,
    ZIP_CD,
    EMAIL_ADDRESS,
    PHONE_NUMBER,
    PHONE_EXTNSN,
    LOCATION_STATUS,
    EFFECTIVE_DATE_FOR_LOCATION,
    LOCATION_TYPES,
    PARSE_DATE('%Y%m%d',REGEXP_EXTRACT(CAST(fileid AS String),r'(\d{2}\d{2}\d{2,4})')) AS file_date,
    fileid
   ) AS row_data,
  FARM_FINGERPRINT(
    CONCAT(
        COALESCE(CAST(LOCATION_NAME AS STRING),''),
        COALESCE(CAST( STR_ADDRESS_1 AS STRING),''),
        COALESCE(CAST( STR_ADDRESS_2 AS STRING),''),
        COALESCE(CAST( STR_ADDRESS_3 AS STRING),''),
        COALESCE(CAST( CITY_NM AS STRING),''),
        COALESCE(CAST( STATE_CD AS STRING),''),
        COALESCE(CAST( ZIP_CD AS STRING),''),
        COALESCE(CAST( EMAIL_ADDRESS AS STRING),''),
        COALESCE(CAST( PHONE_NUMBER AS STRING),''),
        COALESCE(CAST( PHONE_EXTNSN AS STRING),''),
        COALESCE(CAST( LOCATION_STATUS AS STRING),''),
        COALESCE(CAST( EFFECTIVE_DATE_FOR_LOCATION AS STRING),''),
        COALESCE(CAST( ARRAY_LENGTH(LOCATION_TYPES) AS STRING),'')  
        )
    ) AS row_hash
FROM LANDING.WD_LOCATION_DAILY_HISTORY
), part2 AS (
SELECT
    WD_LOCATION_ID, 
    row_hash,
    array_agg(row_data ORDER BY file_date) AS loc_hist
FROM part1
GROUP BY 1,2
)
SELECT
  WD_LOCATION_ID,
  row_hash,
  (SELECT AS STRUCT 
    LOCATION_NAME,
    STR_ADDRESS_1,
    STR_ADDRESS_2,
    STR_ADDRESS_3,
    CITY_NM,
    STATE_CD,
    ZIP_CD,
    EMAIL_ADDRESS,
    PHONE_NUMBER,
    PHONE_EXTNSN,
    LOCATION_STATUS,
    EFFECTIVE_DATE_FOR_LOCATION,
    LOCATION_TYPES,
    file_date,
    fileid
   FROM unnest(loc_hist)
   ORDER BY file_date 
   LIMIT 1).*
FROM part2
ORDER BY 1,16