WITH base AS (
SELECT 
  cast('{{ ds_nodash }}' as int64) as fileid, 
  WD_LOCATION_ID,
  LOCATION_NAME,
  COALESCE(LOCATION_TYPE_CD,'Unknown') AS LOCATION_TYPE_CD,
  STR_ADDRESS_1,
  STR_ADDRESS_2,
  STR_ADDRESS_3,
  CITY_NM,
  STATE_CD,
  ZIP_CD,
  EMAIL_ADDRESS,
  PHONE_NUMBER,
  PHONE_EXTNSN,
  LOCATION_STATUS,
  EFFECTIVE_DATE_FOR_LOCATION
FROM LANDING.WD_LOCATION_RAW_{{ ds_nodash }}
WHERE 1=1
), location_type_cleanup AS (
SELECT 
  fileid,
  WD_LOCATION_ID,
  ARRAY_AGG(LOCATION_TYPE_CD) AS LOCATION_TYPES
FROM base
WHERE WD_LOCATION_ID IS NOT NULL
GROUP BY 
  fileid,
  WD_LOCATION_ID
), location_cleanup AS (
SELECT
  DISTINCT
  fileid, 
  WD_LOCATION_ID,
  LOCATION_NAME,
  STR_ADDRESS_1,
  STR_ADDRESS_2,
  STR_ADDRESS_3,
  CITY_NM,
  STATE_CD,
  ZIP_CD,
  EMAIL_ADDRESS,
  PHONE_NUMBER,
  PHONE_EXTNSN,
  LOCATION_STATUS,
  EFFECTIVE_DATE_FOR_LOCATION
FROM base
)
SELECT
  aa.fileid, 
  aa.WD_LOCATION_ID,
  aa.LOCATION_NAME,
  aa.STR_ADDRESS_1,
  aa.STR_ADDRESS_2,
  aa.STR_ADDRESS_3,
  aa.CITY_NM,
  aa.STATE_CD,
  aa.ZIP_CD,
  aa.EMAIL_ADDRESS,
  aa.PHONE_NUMBER,
  aa.PHONE_EXTNSN,
  aa.LOCATION_STATUS,
  aa.EFFECTIVE_DATE_FOR_LOCATION,
  bb.LOCATION_TYPES
FROM location_cleanup aa
LEFT JOIN location_type_cleanup bb ON (aa.fileid = bb.fileid AND aa.WD_LOCATION_ID = bb.WD_LOCATION_ID)
ORDER BY 1,2;