UPDATE  CUSTOMER_PRODUCT.LOCATION_DIM LOC
SET LOC.EFFECTIVE_END_DT = TEMP.END_DT,
LOC.ACTIVE_FLG=TEMP.ACTV_FL
FROM (
SELECT LOCATION_ID,EFFECTIVE_START_DT,EFFECTIVE_END_DT ,ACTIVE_FLG, MD5_VALUE,
CASE WHEN 
LEAD(DATE_SUB(EFFECTIVE_START_DT, INTERVAL 1 DAY)) OVER (PARTITION BY LOCATION_ID ORDER BY EFFECTIVE_START_DT)  IS NULL
THEN 
'9999-12-31'
ELSE
LEAD(DATE_SUB(EFFECTIVE_START_DT, INTERVAL 1 DAY)) OVER (PARTITION BY LOCATION_ID ORDER BY EFFECTIVE_START_DT) END END_DT,
CASE WHEN 
LEAD(DATE_SUB(EFFECTIVE_START_DT, INTERVAL 1 DAY)) OVER (PARTITION BY LOCATION_ID ORDER BY EFFECTIVE_START_DT)  IS NOT NULL
THEN 
'N'
ELSE
ACTIVE_FLG END ACTV_FL
FROM 
CUSTOMER_PRODUCT.LOCATION_DIM
ORDER BY 1 ) TEMP
WHERE LOC.MD5_VALUE=TEMP.MD5_VALUE AND LOC.EFFECTIVE_START_DT=TEMP.EFFECTIVE_START_DT
