CREATE OR REPLACE TABLE LANDING.AAA_LIFE_INS_AGYPOLE AS 
SELECT
TRIM(COMPANY_CD) AS COMPANY_CD,
TRIM(CLUB_CD) AS CLUB_CD,
TRIM(POLICY_NUM) AS POLICY_NUM,
TRIM(APPLICATION_ID) AS APPLICATION_ID,
TRIM(DISTRIBUTION_SYSTEM) AS DISTRIBUTION_SYSTEM,
TRIM(LEAD_SOURCE_CD) AS LEAD_SOURCE_CD,
TRIM(DIRECT_MAIL_FINDER_NUM) AS DIRECT_MAIL_FINDER_NUM,
TRIM(DIRECT_MAIL_KEY_CD) AS DIRECT_MAIL_KEY_CD,
TRIM(INSURANCE_TYPE) AS INSURANCE_TYPE,
TRIM(PRODUCT_CD) AS PRODUCT_CD,
TRIM(PLAN_CD) AS PLAN_CD,
TRIM(RECORD_STATUS) AS RECORD_STATUS,
TRIM(CONTRACT_STATUS) AS CONTRACT_STATUS,
TRIM(WITHDRAW_OR_DECLINE_REASON_CD) AS WITHDRAW_OR_DECLINE_REASON_CD,
TRIM(MEMBER_NUM) AS MEMBER_NUM,
TRIM(INSURED_FIRST_NM) AS INSURED_FIRST_NM,
TRIM(INSURED_MIDDLE_NM) AS INSURED_MIDDLE_NM,
TRIM(INSURED_LAST_NM) AS INSURED_LAST_NM,
TRIM(INSURED_SUFFIX) AS INSURED_SUFFIX,
TRIM(INSURED_ADDRESS_LINE_ONE) AS INSURED_ADDRESS_LINE_ONE,
TRIM(INSURED_ADDRESS_LINE_TWO) AS INSURED_ADDRESS_LINE_TWO,
TRIM(INSURED_ADDRESS_CITY) AS INSURED_ADDRESS_CITY,
TRIM(INSURED_ADDRESS_STATE) AS INSURED_ADDRESS_STATE,
TRIM(INSURED_ADDRESS_ZIP_CD) AS INSURED_ADDRESS_ZIP_CD,
TRIM(INSURED_HOME_TELEPHONE_NUM) AS INSURED_HOME_TELEPHONE_NUM,
TRIM(INSURED_BUSINESS_TELEPHONE_NUM) AS INSURED_BUSINESS_TELEPHONE_NUM,
TRIM(INSURED_DO_NOT_CALL_IND) AS INSURED_DO_NOT_CALL_IND,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(INSURED_ADDRESS_EFFECTIVE_YEAR),4,"0") ='0001' OR LPAD(TRIM(INSURED_ADDRESS_EFFECTIVE_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(INSURED_ADDRESS_EFFECTIVE_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(INSURED_ADDRESS_EFFECTIVE_MONTH),2,"0")='00' THEN '01' ELSE LPAD(TRIM(INSURED_ADDRESS_EFFECTIVE_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(INSURED_ADDRESS_EFFECTIVE_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(INSURED_ADDRESS_EFFECTIVE_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(INSURED_ADDRESS_EFFECTIVE_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(INSURED_ADDRESS_EFFECTIVE_MONTH),2,"0") IN('02') AND LPAD(TRIM(INSURED_ADDRESS_EFFECTIVE_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(INSURED_ADDRESS_EFFECTIVE_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(INSURED_ADDRESS_EFFECTIVE_MONTH),2,"0") IN('02') AND LPAD(TRIM(INSURED_ADDRESS_EFFECTIVE_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(INSURED_ADDRESS_EFFECTIVE_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(INSURED_ADDRESS_EFFECTIVE_DAY),2,"0") END)))  AS INSURED_ADDRESS_EFF_DT,
TRIM(INSURED_EMAIL_ADDRESS) AS INSURED_EMAIL_ADDRESS,
TRIM(INSURED_CLIENT_NUM) AS INSURED_CLIENT_NUM,
TRIM(INSURED_MARITAL_STATUS) AS INSURED_MARITAL_STATUS,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(INSURED_DT_OF_BIRTH_YEAR),4,"0") ='0001' OR LPAD(TRIM(INSURED_DT_OF_BIRTH_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(INSURED_DT_OF_BIRTH_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(INSURED_DT_OF_BIRTH_MONTH),2,"0")='00' THEN '01' ELSE LPAD(TRIM(INSURED_DT_OF_BIRTH_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(INSURED_DT_OF_BIRTH_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(INSURED_DT_OF_BIRTH_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(INSURED_DT_OF_BIRTH_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(INSURED_DT_OF_BIRTH_MONTH),2,"0") IN('02') AND LPAD(TRIM(INSURED_DT_OF_BIRTH_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(INSURED_DT_OF_BIRTH_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(INSURED_DT_OF_BIRTH_MONTH),2,"0") IN('02') AND LPAD(TRIM(INSURED_DT_OF_BIRTH_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(INSURED_DT_OF_BIRTH_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(INSURED_DT_OF_BIRTH_DAY),2,"0") END)))  AS INSURED_DATE_OF_BIRTH_DT,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(INSURED_DT_OF_DEATH_YEAR),4,"0") ='0001' OR LPAD(TRIM(INSURED_DT_OF_DEATH_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(INSURED_DT_OF_DEATH_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(INSURED_DT_OF_DEATH_MONTH),2,"0")='00' THEN '01' ELSE LPAD(TRIM(INSURED_DT_OF_DEATH_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(INSURED_DT_OF_DEATH_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(INSURED_DT_OF_DEATH_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(INSURED_DT_OF_DEATH_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(INSURED_DT_OF_DEATH_MONTH),2,"0") IN('02') AND LPAD(TRIM(INSURED_DT_OF_DEATH_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(INSURED_DT_OF_DEATH_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(INSURED_DT_OF_DEATH_MONTH),2,"0") IN('02') AND LPAD(TRIM(INSURED_DT_OF_DEATH_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(INSURED_DT_OF_DEATH_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(INSURED_DT_OF_DEATH_DAY),2,"0") END)))  AS INSURED_DATE_OF_DEATH_DT,
TRIM(OWNER_FIRST_NM) AS OWNER_FIRST_NM,
TRIM(OWNER_MIDDLE_NM) AS OWNER_MIDDLE_NM,
TRIM(OWNER_LAST_NM) AS OWNER_LAST_NM,
TRIM(OWNER_SUFFIX) AS OWNER_SUFFIX,
TRIM(OWNER_ADDRESS_LINE_ONE) AS OWNER_ADDRESS_LINE_ONE,
TRIM(OWNER_ADDRESS_LINE_TWO) AS OWNER_ADDRESS_LINE_TWO,
TRIM(OWNER_ADDRESS_CITY) AS OWNER_ADDRESS_CITY,
TRIM(OWNER_ADDRESS_STATE) AS OWNER_ADDRESS_STATE,
TRIM(OWNER_ADDRESS_ZIP) AS OWNER_ADDRESS_ZIP,
TRIM(OWNER_HOME_TELEPHONE_NUM) AS OWNER_HOME_TELEPHONE_NUM,
TRIM(OWNER_BUSINESS_TELEPHONE_NUM) AS OWNER_BUSINESS_TELEPHONE_NUM,
TRIM(OWNER_DO_NOT_CALL_IND) AS OWNER_DO_NOT_CALL_IND,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(OWNER_ADDRESS_EFFECTIVE_YEAR),4,"0") ='0001' OR LPAD(TRIM(OWNER_ADDRESS_EFFECTIVE_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(OWNER_ADDRESS_EFFECTIVE_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(OWNER_ADDRESS_EFFECTIVE_MONTH),2,"0")='00' THEN '01' ELSE LPAD(TRIM(OWNER_ADDRESS_EFFECTIVE_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(OWNER_ADDRESS_EFFECTIVE_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(OWNER_ADDRESS_EFFECTIVE_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(OWNER_ADDRESS_EFFECTIVE_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(OWNER_ADDRESS_EFFECTIVE_MONTH),2,"0") IN('02') AND LPAD(TRIM(OWNER_ADDRESS_EFFECTIVE_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(OWNER_ADDRESS_EFFECTIVE_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(OWNER_ADDRESS_EFFECTIVE_MONTH),2,"0") IN('02') AND LPAD(TRIM(OWNER_ADDRESS_EFFECTIVE_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(OWNER_ADDRESS_EFFECTIVE_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(OWNER_ADDRESS_EFFECTIVE_DAY),2,"0") END)))  AS OWNER_ADDRESS_EFF_DT,
TRIM(OWNER_EMAIL) AS OWNER_EMAIL,
TRIM(OWNER_CLIENT_NUM) AS OWNER_CLIENT_NUM,
UNITS_OF_INSURANCE AS UNITS_OF_INSURANCE,
FACE_AMT AS FACE_AMT,
ANNUAL_PREMIUM AS ANNUAL_PREMIUM,
ANNUAL_POLICY_FEE AS ANNUAL_POLICY_FEE,
TRIM(PAYMENT_CD) AS PAYMENT_CD,
TRIM(BILLING_MODE) AS BILLING_MODE,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(PAID_TO_YEAR),4,"0") ='0001' OR LPAD(TRIM(PAID_TO_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(PAID_TO_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(PAID_TO_MONTH),2,"0")='00' THEN '01' ELSE LPAD(TRIM(PAID_TO_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(PAID_TO_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(PAID_TO_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(PAID_TO_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(PAID_TO_MONTH),2,"0") IN('02') AND LPAD(TRIM(PAID_TO_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(PAID_TO_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(PAID_TO_MONTH),2,"0") IN('02') AND LPAD(TRIM(PAID_TO_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(PAID_TO_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(PAID_TO_DAY),2,"0") END)))  AS PAID_TO_DT,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(BILL_TO_DT_YEAR),4,"0") ='0001' OR LPAD(TRIM(BILL_TO_DT_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(BILL_TO_DT_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(BILL_TO_DT_MONTH),2,"0")='00' THEN '01' ELSE LPAD(TRIM(BILL_TO_DT_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(BILL_TO_DT_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(BILL_TO_DT_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(BILL_TO_DT_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(BILL_TO_DT_MONTH),2,"0") IN('02') AND LPAD(TRIM(BILL_TO_DT_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(BILL_TO_DT_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(BILL_TO_DT_MONTH),2,"0") IN('02') AND LPAD(TRIM(BILL_TO_DT_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(BILL_TO_DT_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(BILL_TO_DT_DAY),2,"0") END)))  AS BILL_TO_DT,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(LAST_BILLING_STMT_YEAR),4,"0") ='0001' OR LPAD(TRIM(LAST_BILLING_STMT_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(LAST_BILLING_STMT_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(LAST_BILLING_STMT_MONTH),2,"0")='00' THEN '01' ELSE LPAD(TRIM(LAST_BILLING_STMT_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(LAST_BILLING_STMT_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(LAST_BILLING_STMT_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(LAST_BILLING_STMT_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(LAST_BILLING_STMT_MONTH),2,"0") IN('02') AND LPAD(TRIM(LAST_BILLING_STMT_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(LAST_BILLING_STMT_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(LAST_BILLING_STMT_MONTH),2,"0") IN('02') AND LPAD(TRIM(LAST_BILLING_STMT_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(LAST_BILLING_STMT_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(LAST_BILLING_STMT_DAY),2,"0") END)))  AS LAST_BILLING_STMT_DT,
MINIMUM_REQUIRED_PREMIUM AS MINIMUM_REQUIRED_PREMIUM,
MODAL_PREMIUM AS MODAL_PREMIUM,
MODAL_POLICY_FEE AS MODAL_POLICY_FEE,
ANNUAL_NO_LAPSE_PREMIUM AS ANNUAL_NO_LAPSE_PREMIUM,
MONTHLY_NO_LAPSE_PREMIUM AS MONTHLY_NO_LAPSE_PREMIUM,
TARGET_PREMIUM_AMT AS TARGET_PREMIUM_AMT,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(LAST_PREMIUM_PAID_YEAR),4,"0") ='0001' OR LPAD(TRIM(LAST_PREMIUM_PAID_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(LAST_PREMIUM_PAID_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(LAST_PREMIUM_PAID_MONTH),2,"0")='00' THEN '01' ELSE LPAD(TRIM(LAST_PREMIUM_PAID_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(LAST_PREMIUM_PAID_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(LAST_PREMIUM_PAID_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(LAST_PREMIUM_PAID_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(LAST_PREMIUM_PAID_MONTH),2,"0") IN('02') AND LPAD(TRIM(LAST_PREMIUM_PAID_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(LAST_PREMIUM_PAID_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(LAST_PREMIUM_PAID_MONTH),2,"0") IN('02') AND LPAD(TRIM(LAST_PREMIUM_PAID_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(LAST_PREMIUM_PAID_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(LAST_PREMIUM_PAID_DAY),2,"0") END)))  AS LAST_PREMIUM_PAID_DT,
TOTAL_PREMIUMS_PAID AS TOTAL_PREMIUMS_PAID,
TRIM(AGENT_NUM) AS AGENT_NUM,
TRIM(AGENT_FIRST_NM) AS AGENT_FIRST_NM,
TRIM(AGENT_LAST_NM) AS AGENT_LAST_NM,
TRIM(AGENT_STATUS) AS AGENT_STATUS,
AGENT_PERCENT AS AGENT_PERCENT,
TRIM(PRIMARY_AGENT_IND) AS PRIMARY_AGENT_IND,
AGENT_CLUB_CD AS AGENT_CLUB_CD,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(APPLICATION_DT_YEAR),4,"0") ='0001' OR LPAD(TRIM(APPLICATION_DT_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(APPLICATION_DT_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(APPLICATION_DT_MONTH),2,"0")='00' THEN '01' ELSE LPAD(TRIM(APPLICATION_DT_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(APPLICATION_DT_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(APPLICATION_DT_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(APPLICATION_DT_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(APPLICATION_DT_MONTH),2,"0") IN('02') AND LPAD(TRIM(APPLICATION_DT_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(APPLICATION_DT_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(APPLICATION_DT_MONTH),2,"0") IN('02') AND LPAD(TRIM(APPLICATION_DT_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(APPLICATION_DT_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(APPLICATION_DT_DAY),2,"0") END)))  AS APPLICATION_DT,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(EFFECTIVE_DT_YEAR),4,"0") ='0001' OR LPAD(TRIM(EFFECTIVE_DT_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(EFFECTIVE_DT_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(EFFECTIVE_DT_MONTH),2,"0")='00' THEN '01' ELSE LPAD(TRIM(EFFECTIVE_DT_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(EFFECTIVE_DT_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(EFFECTIVE_DT_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(EFFECTIVE_DT_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(EFFECTIVE_DT_MONTH),2,"0") IN('02') AND LPAD(TRIM(EFFECTIVE_DT_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(EFFECTIVE_DT_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(EFFECTIVE_DT_MONTH),2,"0") IN('02') AND LPAD(TRIM(EFFECTIVE_DT_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(EFFECTIVE_DT_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(EFFECTIVE_DT_DAY),2,"0") END)))  AS EFF_DT,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(PAY_UP_YEAR),4,"0") ='0001' OR LPAD(TRIM(PAY_UP_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(PAY_UP_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(PAY_UP_MONTH),2,"0")='00' THEN '01' ELSE LPAD(TRIM(PAY_UP_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(PAY_UP_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(PAY_UP_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(PAY_UP_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(PAY_UP_MONTH),2,"0") IN('02') AND LPAD(TRIM(PAY_UP_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(PAY_UP_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(PAY_UP_MONTH),2,"0") IN('02') AND LPAD(TRIM(PAY_UP_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(PAY_UP_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(PAY_UP_DAY),2,"0") END)))  AS PAY_UP_DT,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(EXPIRY_DT_YEAR),4,"0") ='0001' OR LPAD(TRIM(EXPIRY_DT_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(EXPIRY_DT_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(EXPIRY_DT_MONTH),2,"0")='00' THEN '01' ELSE LPAD(TRIM(EXPIRY_DT_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(EXPIRY_DT_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(EXPIRY_DT_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(EXPIRY_DT_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(EXPIRY_DT_MONTH),2,"0") IN('02') AND LPAD(TRIM(EXPIRY_DT_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(EXPIRY_DT_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(EXPIRY_DT_MONTH),2,"0") IN('02') AND LPAD(TRIM(EXPIRY_DT_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(EXPIRY_DT_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(EXPIRY_DT_DAY),2,"0") END)))  AS EXPIRY_DT,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(SETTLE_YEAR),4,"0") ='0001' OR LPAD(TRIM(SETTLE_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(SETTLE_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(SETTLE_MONTH),2,"0")='00' THEN '01' ELSE LPAD(TRIM(SETTLE_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(SETTLE_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(SETTLE_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(SETTLE_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(SETTLE_MONTH),2,"0") IN('02') AND LPAD(TRIM(SETTLE_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(SETTLE_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(SETTLE_MONTH),2,"0") IN('02') AND LPAD(TRIM(SETTLE_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(SETTLE_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(SETTLE_DAY),2,"0") END)))  AS SETTLE_DT,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(TERMINATION_YEAR),4,"0") ='0001' OR LPAD(TRIM(TERMINATION_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(TERMINATION_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(TERMINATION_MONTH),2,"0")='00' THEN '01' ELSE LPAD(TRIM(TERMINATION_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(TERMINATION_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(TERMINATION_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(TERMINATION_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(TERMINATION_MONTH),2,"0") IN('02') AND LPAD(TRIM(TERMINATION_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(TERMINATION_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(TERMINATION_MONTH),2,"0") IN('02') AND LPAD(TRIM(TERMINATION_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(TERMINATION_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(TERMINATION_DAY),2,"0") END)))  AS TERMINATION_DT,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(LAST_STATUS_CHANGE_YEAR),4,"0") ='0001' OR LPAD(TRIM(LAST_STATUS_CHANGE_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(LAST_STATUS_CHANGE_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(LAST_STATUS_CHANGE_MONTH),2,"0")='00' THEN '01' ELSE LPAD(TRIM(LAST_STATUS_CHANGE_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(LAST_STATUS_CHANGE_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(LAST_STATUS_CHANGE_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(LAST_STATUS_CHANGE_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(LAST_STATUS_CHANGE_MONTH),2,"0") IN('02') AND LPAD(TRIM(LAST_STATUS_CHANGE_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(LAST_STATUS_CHANGE_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(LAST_STATUS_CHANGE_MONTH),2,"0") IN('02') AND LPAD(TRIM(LAST_STATUS_CHANGE_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(LAST_STATUS_CHANGE_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(LAST_STATUS_CHANGE_DAY),2,"0") END)))  AS LAST_STATUS_CHANGE_DT,
TRIM(GENDER_CD) AS GENDER_CD,
ISSUE_AGE AS ISSUE_AGE,
TRIM(DEATH_BENEFIT_OPTION) AS DEATH_BENEFIT_OPTION,
TRIM(NON_FORFEITURE_OPTION) AS NON_FORFEITURE_OPTION,
TRIM(SMOKE_CD) AS SMOKE_CD,
TRIM(TAX_QUALIFIED_CD) AS TAX_QUALIFIED_CD,
TRIM(POLICY_CONVERTED_FLAG) AS POLICY_CONVERTED_FLAG,
TRIM(OLD_POLICY_NUM) AS OLD_POLICY_NUM,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(ACCOUNT_VALUE_YEAR),4,"0") ='0001' OR LPAD(TRIM(ACCOUNT_VALUE_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(ACCOUNT_VALUE_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(ACCOUNT_VALUE_MONTH),2,"0")='00' OR LPAD(TRIM(ACCOUNT_VALUE_MONTH),2,"0")>'12' THEN '01' ELSE LPAD(TRIM(ACCOUNT_VALUE_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(ACCOUNT_VALUE_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(ACCOUNT_VALUE_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(ACCOUNT_VALUE_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(ACCOUNT_VALUE_MONTH),2,"0") IN('02') AND LPAD(TRIM(ACCOUNT_VALUE_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(ACCOUNT_VALUE_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(ACCOUNT_VALUE_MONTH),2,"0") IN('02') AND LPAD(TRIM(ACCOUNT_VALUE_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(ACCOUNT_VALUE_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(ACCOUNT_VALUE_DAY),2,"0") END)))  AS ACCOUNT_VALUE_DT,
ACCOUNT_VALUE AS ACCOUNT_VALUE,
CASH_VALUE AS CASH_VALUE,
LOAN_BALANCE AS LOAN_BALANCE,
parse_date("%Y-%m-%d",CONCAT((CASE WHEN LPAD(TRIM(LOAN_INTEREST_DUE_YEAR),4,"0") ='0001' OR LPAD(TRIM(LOAN_INTEREST_DUE_YEAR),4,"0") ='0000' THEN '1900' ELSE LPAD(TRIM(LOAN_INTEREST_DUE_YEAR),4,"0")END),
'-',(CASE WHEN LPAD(TRIM(LOAN_INTEREST_DUE_MONTH),2,"0")='00' OR LPAD(TRIM(LOAN_INTEREST_DUE_MONTH),2,"0")>'12' THEN '01' ELSE LPAD(TRIM(LOAN_INTEREST_DUE_MONTH),2,"0") END),
'-',(CASE WHEN LPAD(TRIM(LOAN_INTEREST_DUE_DAY),2,"0")='00' THEN '01' WHEN (LPAD(TRIM(LOAN_INTEREST_DUE_MONTH),2,"0") IN('04','06','09','11') AND LPAD(TRIM(LOAN_INTEREST_DUE_DAY),2,"0")='31') THEN '30'
WHEN (LPAD(TRIM(LOAN_INTEREST_DUE_MONTH),2,"0") IN('02') AND LPAD(TRIM(LOAN_INTEREST_DUE_DAY),2,"0") IN('31','30') AND MOD(safe_cast(LPAD(TRIM(LOAN_INTEREST_DUE_YEAR),4,"0") as INT64),4) = 0) THEN '29'
WHEN (LPAD(TRIM(LOAN_INTEREST_DUE_MONTH),2,"0") IN('02') AND LPAD(TRIM(LOAN_INTEREST_DUE_DAY),2,"0") IN('31','30','29') AND MOD(safe_cast(LPAD(TRIM(LOAN_INTEREST_DUE_YEAR),4,"0") as INT64),4) != 0) THEN '28'
ELSE LPAD(TRIM(LOAN_INTEREST_DUE_DAY),2,"0") END)))  AS LOAN_INTEREST_DUE_DT,
LOAN_INTEREST_BILL_AMT AS LOAN_INTEREST_BILL_AMT,
CURRENT_INTEREST_RATE AS CURRENT_INTEREST_RATE,
TRIM(MEMBERSHIP_CARD_NUM) AS MEMBERSHIP_CARD_NUM,
"v_job_run_id" AS JOB_RUN_ID,
"AGYPOLE" AS SOURCE_SYSTEM_CD,
CURRENT_TIMESTAMP() AS CREATE_DTTIME,
"v_job_name" AS CREATE_BY
FROM LANDING.WORK_LIFE_INS_AGYPOLE