SELECT COMPANY,
EMPLOYEE,
VEHICLE,
CASE WHEN START_DTTIME IS NULL THEN CONCAT(CAST(DATE(END_DTTIME) as STRING) , ' 00:00:00')
ELSE CAST(START_DTTIME as STRING) END AS START_DTTIME,
CASE WHEN END_DTTIME IS NULL THEN CONCAT(CAST(DATE(START_DTTIME) as STRING) , ' 23:59:59')
WHEN CAST(END_DTTIME AS DATETIME) < CAST(START_DTTIME AS DATETIME) THEN CONCAT(CAST(DATE(START_DTTIME) as STRING) , ' 23:59:59')
ELSE CAST(END_DTTIME as STRING) END AS END_DTTIME,
TRIM(REGEXP_REPLACE(FIRST_NAME,'[^a-zA-Z0-9 ]','')) as FIRST_NAME,
TRIM(REGEXP_REPLACE(LAST_NAME,'[^a-zA-Z0-9 ]','')) as LAST_NAME,
TRIM(REGEXP_REPLACE(MIDDLE_NAME,'[^a-zA-Z0-9 ]','')) as MIDDLE_NAME
FROM (
select '5JWU' as COMPANY,
CONCAT(tss.FACILITY , '-', driver) as EMPLOYEE,
truck as VEHICLE,
MIN(DATE(INSERT_TM)) AS INSERT_TM ,
MIN(CASE WHEN UPPER(STAT_NM) = 'LOGIN' THEN LOG_TM ELSE NULL END) as START_DTTIME,
MAX(CASE WHEN UPPER(STAT_NM) = 'LOGOUT' THEN LOG_TM ELSE NULL END) as END_DTTIME,
drv.TRK_DRIVR_FST_NM as FIRST_NAME,
drv.TRK_DRIVR_LST_NM as LAST_NAME,
'' as MIDDLE_NAME
from OPERATIONAL.ERS_STAGE_CAD_TRUCK_SESSION_STATS tss
inner join REFERENCE.ERS_STAGE_CAD_SERVICE_FACILITY csf ON tss.FACILITY = csf.SVC_FACL_ID --and csf.active_indic = 'y'
LEFT join OPERATIONAL.ERS_STAGE_SERVICE_FACILITY sf ON csf.SVC_FACL_ID = sf. SVC_FACL_ID and sf.svc_facl_sts_cd='a' -- and sf.active_indic='y'
LEFT join REFERENCE.ERS_SVC_TRK_DRIVER drv ON UPPER(TRIM(tss.FACILITY)) = UPPER(TRIM(drv.svc_facl_id)) and UPPER(TRIM(tss.DRIVER)) = UPPER(TRIM(safe_cast(drv.trk_drivr_id as STRING))) --and drv.active_indic='y'
where CASE WHEN EXTRACT(HOUR FROM INSERT_TM ) < 1 then DATE_SUB(DATE(INSERT_TM), INTERVAL 1 DAY) ELSE DATE(INSERT_TM) END >= DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)
and UPPER(STAT_NM) in ('LOGIN', 'LOGOUT')
group by truck, driver, tss.FACILITY, CASE WHEN EXTRACT(HOUR FROM INSERT_TM ) < 1 then DATE_SUB(DATE(INSERT_TM), INTERVAL 1 DAY) ELSE DATE(INSERT_TM) END ,drv.TRK_DRIVR_FST_NM,drv.TRK_DRIVR_LST_NM
order by driver, truck
)
