CREATE OR REPLACE TABLE CUSTOMERS.MDM_WORK_COMMENTS_STG AS
SELECT 
INVOICE_PAY_ID,
CAST(MAX(CASE WHEN (SUBSTR(CAST(INVOICE_PAY_ID AS STRING),1,6) = '438255' and LENGTH(CAST(INVOICE_PAY_ID AS STRING)) > 12)
	 THEN SUBSTR(CAST(INVOICE_PAY_ID AS STRING),7,8)
	 WHEN (SUBSTR(CAST(INVOICE_PAY_ID AS STRING),1,3) = '255' and LENGTH (CAST(INVOICE_PAY_ID AS STRING)) > 10)
	 THEN SUBSTR(CAST(INVOICE_PAY_ID AS STRING),4,8)
     WHEN LENGTH(CAST(INVOICE_PAY_ID AS STRING)) = 8
	 THEN CAST(INVOICE_PAY_ID AS STRING) 
	 WHEN LENGTH(CAST(INVOICE_PAY_ID AS STRING)) = 9 
	 THEN SUBSTR(CAST(INVOICE_PAY_ID AS STRING),1,8)
	 WHEN SUBSTR(CAST(INVOICE_PAY_ID AS STRING),1,6) = '005429' 
	 THEN SUBSTR(CAST(INVOICE_PAY_ID AS STRING),7,8)
	 WHEN (SUBSTR(CAST(INVOICE_PAY_ID AS STRING),1,9) = '005429005' and (LENGTH(CAST(INVOICE_PAY_ID AS STRING))=17 OR LENGTH(CAST(INVOICE_PAY_ID AS STRING))=19))
	 THEN SUBSTR(CAST(INVOICE_PAY_ID AS STRING),10,8)
	 WHEN SUBSTR(CAST(INVOICE_PAY_ID AS STRING),1,6) = '429005' 
	 THEN SUBSTR(CAST(INVOICE_PAY_ID AS STRING),7,8)
	 WHEN (LENGTH(CAST(INVOICE_PAY_ID AS STRING)) = 10 and (SUBSTR(CAST(INVOICE_PAY_ID AS STRING),9,2)='14' OR SUBSTR(CAST(INVOICE_PAY_ID AS STRING),9,2)='22') )
	 THEN SUBSTR(CAST(INVOICE_PAY_ID AS STRING),1,8)
	 WHEN (LENGTH(CAST(INVOICE_PAY_ID AS STRING)) = 11 and SUBSTR(CAST(INVOICE_PAY_ID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INVOICE_PAY_ID AS STRING),4,8)
	 WHEN (LENGTH(CAST(INVOICE_PAY_ID AS STRING)) = 12 and SUBSTR(CAST(INVOICE_PAY_ID AS STRING),1,3) = '005') 
	 THEN SUBSTR(CAST(INVOICE_PAY_ID AS STRING),5,8)
	 WHEN (LENGTH(CAST(INVOICE_PAY_ID AS STRING)) = 13 and SUBSTR(CAST(INVOICE_PAY_ID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INVOICE_PAY_ID AS STRING),6,8)
	 WHEN (LENGTH(CAST(INVOICE_PAY_ID AS STRING)) = 14 and SUBSTR(CAST(INVOICE_PAY_ID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INVOICE_PAY_ID AS STRING),7,8)
	 WHEN (LENGTH(CAST(INVOICE_PAY_ID AS STRING)) = 15 and SUBSTR(CAST(INVOICE_PAY_ID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INVOICE_PAY_ID AS STRING),8,8)
	 WHEN (LENGTH(CAST(INVOICE_PAY_ID AS STRING)) >= 15 and LENGTH(CAST(INVOICE_PAY_ID AS STRING)) <= 16 and SUBSTR(CAST(INVOICE_PAY_ID AS STRING),1,6) = '005005')
	 THEN SUBSTR(CAST(INVOICE_PAY_ID AS STRING),8,8)
	 WHEN (LENGTH(CAST(INVOICE_PAY_ID AS STRING)) > 16 and SUBSTR(CAST(INVOICE_PAY_ID AS STRING),1,9) = '005005429')
	 THEN SUBSTR(CAST(INVOICE_PAY_ID AS STRING),11,8)
	 ELSE NULL
	 END) AS INT64) MEMBERSHIP_ID,
MAX(CASE WHEN LINE_NUM = '20'
THEN
SUBSTR(DATA,1,(STRPOS(DATA,' ')-1))
ELSE 
NULL
END) FIRST_NM,
MAX(CASE WHEN LINE_NUM = '20' AND STRPOS(SUBSTR(DATA,(STRPOS(DATA,' ')+1)),' ')-1 <>0
THEN
SUBSTR(SUBSTR(DATA,(STRPOS(DATA,' ')+1)),1,STRPOS(SUBSTR(DATA,(STRPOS(DATA,' ')+1)),' '))
ELSE
NULL
END) MIDDLE_NAME,
MAX(CASE WHEN LINE_NUM = '20' 
THEN
(CASE WHEN STRPOS(SUBSTR(DATA,(STRPOS(DATA,' ')+1)),' ')-1 <>0
THEN
SUBSTR(SUBSTR(DATA,(STRPOS(DATA,' ')+1)),STRPOS(SUBSTR(DATA,(STRPOS(DATA,' ')+1)),' ')+1)
ELSE
SUBSTR(DATA,(STRPOS(DATA,' ')+1))
END
)
ELSE
NULL
END) LAST_NM,
MAX(CASE WHEN LINE_NUM='21' THEN DATA ELSE NULL END) ADDRESS_LINE_1,
MAX(CASE WHEN LINE_NUM='22' THEN DATA ELSE NULL END) ADDRESS_LINE_2,
MAX(CASE WHEN LINE_NUM='23' THEN DATA ELSE NULL END) CITY,
MAX(CASE WHEN LINE_NUM='27' THEN DATA ELSE NULL END) STATE,
MAX(CASE WHEN LINE_NUM='24' THEN DATA ELSE NULL END) ZIP,
MAX(CASE WHEN LINE_NUM='28' THEN REPLACE(DATA,'//','@') ELSE NULL END) EMAIL,
MAX(CASE WHEN LINE_NUM='25' THEN DATA ELSE NULL END) COMMENTS_PHONE_NUMBER,
MAX(CASE WHEN LINE_NUM='21' THEN DATA ELSE NULL END) COMMENTS_ADDRESS_LINE1,
MAX(CASE WHEN LINE_NUM='22' THEN DATA ELSE NULL END) COMMENTS_ADDRESS_LINE2,
MAX(CASE WHEN LINE_NUM='23' THEN DATA ELSE NULL END) COMMENTS_CITY,
MAX(CASE WHEN LINE_NUM='27' THEN DATA ELSE NULL END) COMMENTS_STATE,
MAX(CASE WHEN LINE_NUM='24' THEN DATA ELSE NULL END) COMMENTS_ZIP,
CURRENT_DATE AS COMMENTS_CREATE_DATE
FROM 
LANDING.TRAVEL_COMMENTS
GROUP BY 1