SELECT
CAST(INVMVID AS INT64) INVMV_ID,
CAST(SEQNUM AS INT64) SEQ_NUM,
CAST(ITEMID AS INT64) ITEM_ID,
CAST(QTY AS FLOAT64) QTY,
CAST(COST AS FLOAT64) COST,
CAST(BALQTY AS FLOAT64) BAL_QTY
FROM
  `aaadata-181822.COR_ANALYTICS.STG_NAPATRACKS_INVMVITEM`