SELECT
  CAST(RATEID AS INT64)RATE_ID,
  RATE AS RATE_NAME,
  CAST(RATE AS FLOAT64) RATE,
  RATEBASIS AS RATE_BASIS,
  ACTIVEFLAG AS ACTIVE_FLAG
FROM
  `aaadata-181822.COR_ANALYTICS.STG_NAPATRACKS_RATE`