SELECT 
CAST(ARID AS INT64) AR_ID, 
CAST(CUSTID AS INT64) CUST_ID, 
PARSE_DATETIME('%m/%d/%Y %H:%M %p', TRXDATE) TRX_DATETIME,
AUTHOR, 
AUTHORSTATION AUTHOR_STATION,
ARTRXTYPE AR_TRX_TYPE,
CHECKNBR CHECK_NBR,
CARDTYPE CARD_TYPE,
NOTE,
ARACCT AR_ACCT,
CASHACCT CASH_ACCT,
CAST(TRXAMT AS FLOAT64) TRX_AMT
FROM `aaadata-181822.COR_ANALYTICS.STG_NAPATRACKS_ARH`