SELECT
CAST (ACTIONID AS INT64) ACTION_ID,
CAST(FUNCTIONCODE AS INT64) FUNCTION_CODE,
CAST(ACTIONCODE AS INT64) ACTION_CODE,
ACTIONNAME AS ACTION_NAME,
DEFAULTVAL AS DEFAULT_VAL
FROM
  `aaadata-181822.COR_ANALYTICS.STG_NAPATRACKS_SECURITYLIST`