SELECT 
cast (RSID as INT64 )  as RS_ID ,
cast (CUSTID as STRING )  as CUST_ID ,
cast (VEHID as INT64 )  as VEH_ID ,
cast (ITEMID as INT64 )  as ITEM_ID ,
cast (MLGINC as INT64 )  as MLG_INC ,
cast (DAYINC as INT64 )  as DAY_INC ,
cast (MLGDLIN as INT64 )  as MLG_DLIN ,
PARSE_DATETIME('%m/%d/%Y %H:%M %p', DAYDLIN) DAY_DLIN,
PARSE_DATETIME('%m/%d/%Y %H:%M %p', MDAYDLIN) MDAYDLIN,
PARSE_DATETIME('%m/%d/%Y %H:%M %p', NEXTDAYDLIN) NEXTDAYDLIN,
cast (CYCLIC as INT64 )  as CYCLIC ,
cast (DATLSRP as STRING )  as DATLSRP ,
cast (PERFORMED as INT64 )  as PERFORMED ,
PARSE_DATETIME('%m/%d/%Y %H:%M %p', PERFDATE) PERF_DATE,
cast (ROID as INT64 )  as RO_ID ,
cast (NOTE as STRING )  as NOTE ,
cast (PROJECTED as INT64 )  as PROJECTED 
FROM COR_ANALYTICS.STG_NAPATRACKS_RECSERV