SELECT 
cast (CVMVID as INT64 )  as CVMV_ID ,
cast (MVTYPE as STRING )  as MV_TYPE ,
cast (AFFECTEDTABLE as STRING )  as AFFECTED_TABLE ,
cast (AFFECTEDID as INT64 )  as AFFECTED_ID ,
cast (ORGID as INT64 )  as ORG_ID ,
cast (MOVEDTOID as INT64 )  as MOVED_TO_ID ,
cast (AFFECTEDTYPE as STRING )  as AFFECTED_TYPE ,
PARSE_DATETIME('%m/%d/%Y %H:%M %p', TRXTIME) TRX_TIME
FROM COR_ANALYTICS.STG_NAPATRACKS_CVMV