SELECT
  EMPCODE AS EMP_CODE,
  NAME,
  EMPPASSWORD  AS EMP_PASSWORD,
  CAST (COST AS FLOAT64) AS COST,
  CAST ( EMPLOYEEID AS INT64) AS EMPLOYEE_ID,
  ACTIVEFLAG
FROM
  `aaadata-181822.COR_ANALYTICS.STG_NAPATRACKS_EMPLOYEE`