SELECT
  CAST (OBJID AS INT64) OBJ_ID,
  CAST (VERSION AS INT64) VERSION,
  NAME,
  CAST (TYPEID AS INT64) TYPE_ID,
  CAST (MISCINFO1 AS INT64) MISC_INFO1,
  CAST(MISCINFO2 AS INT64) MISC_INFO2,
  CAST(SRCOBJID AS INT64) SRC_OBJ_ID,
  CAST(DESTOBJID AS INT64) DEST_OBJ_ID,
  CAST(DESTVERSION AS INT64) DEST_VERSION,
  MISCINFO3 AS MISC_INFO3
FROM
  `aaadata-181822.COR_ANALYTICS.STG_NAPATRACKS_TRACS`