SELECT 
CAST (ROID AS INT64) AS RO_ID,
CAST (APPROVID AS INT64) AS APPROV_ID,
PARSE_DATETIME('%m/%d/%Y %H:%M %p', APPROVALDATE) APPROVAL_DATE,
CAST (TOTAL AS FLOAT64) AS TOTAL,
METHOD,
CONTACT,
EMPLOYEE,
NOTE,
CONTACTPHONE,
REASON
FROM COR_ANALYTICS.STG_NAPATRACKS_ROAPPROVAL