SELECT *,PARSE_DATETIME('%m/%d/%y %H:%M %p',TRXDATE) AS TRX_DATETIME
FROM
(SELECT
  ACCTTRXTYPE AS ACCT_TRX_TYPE,
  REFID AS REF_ID, 
  TRIM(TRXDATE)TRXDATE,
 -- PARSE_DATETIME('%x %R. %p',
 --   TRXDATE) AS TRX_DATETIME,
  POSTED AS POSTED_FLAG,
  CUSTID AS CUST_ID,
  VENDID AS VEND_ID,
  TRXTYPE AS TRX_TYPE,
  CAST (TRXAMT AS FLOAT64) AS TRX_AMT
FROM
  `aaadata-181822.COR_ANALYTICS.STG_NAPATRACKS_ACCTTRX`)