SELECT ICD.CUSTOMER_MDM_KEY AS ENTERPRISE_ID
,'005' AS CLUB_CODE	
,SUBSTR(ICD.MEMBER_NUM,7,8) AS MEMBER_ID	
,SUBSTR(ICD.MEMBER_NUM,15,1) ASSOCIATE_ID
,IPD.AGREEMENT_NUM AS  POLICY_NUM	
,IPD.SOURCE_PRODUCT_CD AS POLICY_TYPE	
,CASE WHEN IPD.DATA_SOURCE='EXIGEN' then 'PAS' 
	  ELSE IPD.DATA_SOURCE 
	  END AS SOURCE_SYSTEM	
,IPD.STATUS_CD AS POLICY_STATUS	
,IPD.TERM_EFFECTIVE_DT AS TERM_EFFECTIVE_DATE
,IPD.TERM_EXPIRATION_DT AS TERM_EXPIRATION_DATE
,IPD.CANCEL_DT AS  CANCEL_DATE	
,NULL AS DURATION	
,MCD.LAST_NM AS LAST_NAME	
,MCD.FIRST_NM FIRST_NAME	
,MCD.SALUTATION_CD SALUTATION	
,NULL AS MARITAL_STATUS_CD	
,MCD.GENDER_CD AS  GENDER_CODE	
,MCD.BIRTH_DATE AS BIRTH_DATE	
,MCD.IVANS_IE_OTHER_PHONE_NUM AS CELL_PHONE_NUMBER	
,MCD.IVANS_IE_RESIDENTIAL_PHONE_NUM AS HOME_PHONE_NUMBER	
,MCD.IVANS_IE_EMAIL_ADDRESS AS EMAIL_ADDRESS	
,MCD.IVANS_IE_RESIDENTIAL_ADDRESS_LINE1 RESIDENTAIL_ADDRESS_LINE1	
,MCD.IVANS_IE_RESIDENTIAL_ADDRESS_LINE2 RESIDENTIAL_ADDRESS_LINE2	
,MCD.IVANS_IE_RESIDENTIAL_CITY RESIDENTIAL_CITY	
,MCD.IVANS_IE_RESIDENTIAL_STATE RESIDENTIAL_STATE	
,MCD.IVANS_IE_RESIDENTIAL_ZIP RESIDENTIAL_ZIP_CODE
,NULL AS RESIDENTIAL_COUNTRY	
,MCD.IVANS_IE_BILLING_ADDRESS_LINE1 BILLING_ADDRES_LINE1
,MCD.IVANS_IE_BILLING_ADDRESS_LINE2 BILLING_ADDRES_LINE2
,MCD.IVANS_IE_BILLING_CITY BILLING_CITY	
,MCD.IVANS_IE_BILLING_STATE BILLING_STATE	
,MCD.IVANS_IE_BILLING_ZIP BILLING_ZIP_CODE	
,NULL AS BILLING_COUNTRY	
,CASE WHEN IPD.PRODUCT_TYPE = 'Home' THEN COMPENSATION_EMPLOYEE_ID ELSE NULL END AS  HOME_INSURANCE_AGENT	
,CASE WHEN IPD.PRODUCT_TYPE = 'Auto' THEN COMPENSATION_EMPLOYEE_ID ELSE NULL END AS  AUTO_INSURANCE_AGENT	
,CASE WHEN IPD.PRODUCT_TYPE = 'life' THEN COMPENSATION_EMPLOYEE_ID ELSE NULL END AS  LIFE_INSURANCE_AGENT 
FROM  (SELECT * FROM CUSTOMER_PRODUCT.INSURANCE_POLICY_DIM WHERE ACTIVE_FLG = 'Y') IPD
INNER JOIN CUSTOMER_PRODUCT.INSURANCE_CUSTOMER_DIM ICD ON IPD.AGREEMENT_NUM = ICD.AGREEMENT_NUM
INNER JOIN CUSTOMERS.MDM_CUSTOMER_DIM  MCD  ON MCD.CUSTOMER_MDM_KEY = ICD.CUSTOMER_MDM_KEY
LEFT OUTER JOIN (SELECT * FROM ( SELECT * , ROW_NUMBER() OVER (PARTITION BY POLICY_NUM ORDER BY TRANSACTION_DT DESC) AS DUP_CHECK 
FROM  CUSTOMER_PRODUCT.INSURANCE_TRANSACTION_FACT 
WHERE TRANSACTION_TERM = 'New' AND TRANSACTION_TYPE =  'Issue' 
AND PRODUCT_TYPE IN ('Home','Auto', 'life')
) FACT WHERE FACT.DUP_CHECK=1 ) ITF  ON ITF.POLICY_NUM = IPD.POLICY_NUM
AND IPD.UPDATE_DTTIME>'{{ prev_execution_date }}'
