CREATE OR REPLACE TABLE  OPERATIONAL.AV_AG_AGROUPS AS ( SELECT

SAFE_CAST(ACD_NUM AS INT64) AS ACD_NUM,
ITEM_TYPE AS ITEM_TYPE,
ITEM_NM AS ITEM_NM,
SAFE_CAST(AGROUPS_VALUE  AS INT64)AS AGROUPS_VALUE,
'jobrunid' AS JOB_RUN_ID,
"AVAYA" AS SOURCE_SYSTEM_CD,
current_datetime() AS CREATE_DTTIME,
current_datetime() AS LAST_UPDATE_DTTIME
FROM LANDING.WORK_AV_AGROUPS)