INSERT INTO CUSTOMER_PRODUCT.GIG_APPOPEN_RESERVATION_BOOKING
(APPOPEN_DT , 
TOTAL_APPOPEN_COUNT , 
REGISTERED_USER_APPOPEN_COUNT , 
RESERVATION_COUNT , 
BOOKING_COUNT , 
JOB_RUN_ID , 
SOURCE_SYSTEM_CD , 
CREATE_DTTIME , 
CREATE_BY )
(SELECT
SAFE_CAST(APPOPEN_DATE AS DATE) , 
SAFE_CAST(TOTAL_APPOPEN_COUNT AS INT64), 
SAFE_CAST(REGISTERED_USER_APPOPEN_COUNT AS INT64), 
SAFE_CAST(RESERVATION_COUNT AS INT64), 
SAFE_CAST(BOOKING_COUNT AS INT64), 
"8912",
"GIG",
CURRENT_DATETIME() ,
"v_job_name" from LANDING.WORK_GIG_APPOPEN_RESERVATION_BOOKING);