----------------------------------------------------------------------
--Overall flow of these script is
--Step1     Prepare the SAM Customer data for the MDM process
--Step2     Update the MERGE_FLAG column using the MERGE_CHECK1_CTL and MERGE_CHECK2_CTL.
--Step2.1   If MERGE_CHECK1_CTL=0 and MERGE_CHECK2_CTL=0 Then Dont Consider those records for MDM Process. All Required Column are having Null Values.
--Step2.2   If MERGE_CHECK1_CTL=1 and MERGE_CHECK2_CTL=1 Then treat that records as Golden record specific to Source System. Adress and Email Id are Unique. It is not merged to any transaction in given source system data.
--Step2.3.0 If MERGE_CHECK1_CTL+MERGE_CHECK2_CTL>=2 Then Identify the Golden and Merge Records from data set. 
--Step2.3.1 To Take the Latest transaction and It is based on Source record creation date and Source record Id (Example: Customer_ID). 
--Step2.3.2 Identify the First record in the Group as "Golden" and the remaining transaction in that group as "Merge".
--Step2.4   If MERGE_CHECK1_CTL=1 and MERGE_CHECK2_CTL=0 Then consider all these transaction as "Golden". It is due to the transaction are unique and not merged with any other records in that group. The Primary Email Address is Null for all these transactions.
--Step2.5   If MERGE_CHECK1_CTL=0 and MERGE_CHECK2_CTL=1 Then consider all these transaction as "Golden". It is due to the transaction are unique and not merged with any other records in that group. The Primary Address Line1 is Null for all these transactions. 
--Step2.6   Delete the records which are not required for MDM Process.[It Could be Source Data Issue and they are not providing all required information for MDM process or Report these transaction as an Issue]
----------------------------------------------------------------------
--STEP1
----------------------------------------------------------------------
CREATE OR REPLACE TABLE LANDING.WORK_MDM_MEMBERSHIP AS
SELECT DISTINCT
  CAST(SOURCE_KEY1 AS STRING) AS SOURCE_KEY1,
  CAST(SOURCE_KEY2 AS STRING) AS SOURCE_KEY2,
  CAST(SOURCE_KEY3 AS STRING) AS SOURCE_KEY3,
  SOURCE_KEY1_DESC,
  SOURCE_KEY2_DESC,
  SOURCE_KEY3_DESC,
  SOURCE_SYSTEM_CD,
  FIRST_NM,
  LAST_NM,
  MIDDLE_NM,
  PREFFERRED_NM,
  NAME_SUFFIX_CD,
  SALUTATION_CD,
  BIRTH_DT,
  GENDER_CD,
  MARITAL_STATUS,
  DECEASED_IND,
  PRIMARY_ADDRESS_LINE1,
  PRIMARY_ADDRESS_LINE2,
  PRIMARY_CITY,
  PRIMARY_STATE,
  PRIMARY_ZIP,
  PRIMARY_EMAIL_ADDRESS,
  COALESCE(HOME_TELEPHONE_NUM, WORK_PHONE_NUM, OTHER_PHONE_NUM) AS PRIMARY_PHONE_NUM,
  RESIDENTIAL_ADDRESS_LINE1,
  RESIDENTIAL_ADDRESS_LINE2,
  RESIDENTIAL_CITY,
  RESIDENTIAL_STATE,
   RESIDENTIAL_ZIP,
  BILLING_ADDRESS_LINE1,
  BILLING_ADDRESS_LINE2,
  BILLING_CITY,
  BILLING_STATE,
  BILLING_ZIP,
  OTHER_ADDRESS_LINE1,
  OTHER_ADDRESS_LINE2,
  OTHER_CITY,
  OTHER_STATE,
  OTHER_ZIP,
  OTHER_EMAIL_ADDRESS,
  HOME_TELEPHONE_NUM,
  WORK_PHONE_NUM,
  OTHER_PHONE_NUM,
  SOURCE_CREATE_DATE,
  COUNT(CASE
      WHEN (TRIM(PRIMARY_ADDRESS_LINE1) IS NULL OR TRIM(PRIMARY_ADDRESS_LINE1)='') THEN NULL
      ELSE 1 END) OVER(PARTITION BY UPPER(FIRST_NM),
    UPPER(LAST_NM),
    BIRTH_DT,
    UPPER(PRIMARY_ADDRESS_LINE1),
    UPPER(PRIMARY_ADDRESS_LINE2),
    UPPER(PRIMARY_CITY),
    UPPER(PRIMARY_STATE),
    UPPER(PRIMARY_ZIP)) AS MERGE_CHECK1_CTL,
  COUNT(CASE
      WHEN (TRIM(PRIMARY_EMAIL_ADDRESS) IS NULL OR TRIM(PRIMARY_EMAIL_ADDRESS)='') THEN NULL
      ELSE 1 END) OVER(PARTITION BY UPPER(FIRST_NM),
    UPPER(LAST_NM),
    UPPER(PRIMARY_EMAIL_ADDRESS)) AS MERGE_CHECK2_CTL,
  '      ' AS MERGE_FLAG,
    TERM_EXPIRATION_DT,
	CAST(NULL AS STRING) as ADDRESS_MATCH_SOURCE_KEY,  -- RENAMED
	CAST(NULL AS INT64) AS CUSTOMER_MDM_KEY,
	CAST(NULL AS STRING) AS WORK_MATCH_GROUP,
	CAST(NULL AS STRING) AS MDM_MATCH_GROUP,
	CAST(NULL AS BYTES) AS HOME_MD5_KEY,
	CAST(NULL AS BYTES) AS MAILING_MD5_KEY,
	CAST(NULL AS BYTES) AS OTHER_MD5_KEY,
	CAST(NULL AS STRING) AS EMAIL_MATCH_SOURCE_KEY, -- New Column
	CAST(NULL AS STRING) AS ADDRESS_MATCH_DESC, -- New Column
	CAST(NULL AS STRING) AS EMAIL_MATCH_DESC, -- New Column
	CAST(NULL AS STRING) AS GOLDEN_MATCH_KEY, -- New Column
	REGEXP_REPLACE(CONCAT( IFNULL(UPPER(TRIM(RESIDENTIAL_ADDRESS_LINE1)),''),
                          IFNULL(UPPER(TRIM(RESIDENTIAL_ADDRESS_LINE2)),''), 
						  IFNULL(UPPER(TRIM(RESIDENTIAL_CITY)),''), 
						  IFNULL(UPPER(TRIM(RESIDENTIAL_STATE)),''), 
						  IFNULL(UPPER(TRIM(RESIDENTIAL_ZIP)),'')),
				  '[^a-zA-Z0-9]','') AS ADDRESS_MATCH_KEY1, -- New Column
    REGEXP_REPLACE(CONCAT( IFNULL(UPPER(TRIM(BILLING_ADDRESS_LINE1)),''),
                          IFNULL(UPPER(TRIM(BILLING_ADDRESS_LINE2)),''), 
						  IFNULL(UPPER(TRIM(BILLING_CITY)),''), 
						  IFNULL(UPPER(TRIM(BILLING_STATE)),''), 
						  IFNULL(UPPER(TRIM(BILLING_ZIP)),'')),
				  '[^a-zA-Z0-9]','') AS ADDRESS_MATCH_KEY2 -- New Column
  FROM (
  SELECT
    MEMBER_NUM AS SOURCE_KEY1,
    TERM_EXPIRATION_DT AS SOURCE_KEY2,
    CAST(NULL AS STRING) AS SOURCE_KEY3,
    'MEMBER_NUM' AS SOURCE_KEY1_DESC,
    'TERM_EXPIRATION_DT' AS SOURCE_KEY2_DESC,
    CAST(NULL AS STRING) AS SOURCE_KEY3_DESC,
    'MEMBERSHIP' AS SOURCE_SYSTEM_CD,
    UPPER(TRIM(FIRST_NM)) AS FIRST_NM,
    UPPER(TRIM(LAST_NM)) AS LAST_NM,
    UPPER(TRIM(NAME_SUFFIX_CD)) AS NAME_SUFFIX_CD,
    UPPER(TRIM(SALUTATION_CD)) AS SALUTATION_CD,
    BIRTH_DT,
    UPPER(TRIM(GENDER_CD)) AS GENDER_CD,
    UPPER(TRIM(MARITAL_STATUS)) AS MARITAL_STATUS,
	UPPER(TRIM(PREFFERRED_NM)) AS PREFFERRED_NM,
    UPPER(TRIM(MIDDLE_NM)) AS MIDDLE_NM,
    UPPER(TRIM(DECEASED_IND)) AS DECEASED_IND,
    UPPER(TRIM(PRIMARY_ADDRESS_LINE1)) AS PRIMARY_ADDRESS_LINE1,
    UPPER(TRIM(PRIMARY_ADDRESS_LINE2)) AS PRIMARY_ADDRESS_LINE2,
    UPPER(TRIM(PRIMARY_CITY)) AS PRIMARY_CITY,
    UPPER(TRIM(PRIMARY_STATE)) AS PRIMARY_STATE,
     UPPER(TRIM(CASE
    WHEN LENGTH(REGEXP_REPLACE(PRIMARY_ZIP,'[^a-zA-Z0-9]','')) = 6 THEN REGEXP_REPLACE(PRIMARY_ZIP,'[^a-zA-Z0-9]','')
    WHEN LENGTH(REGEXP_REPLACE(REGEXP_REPLACE(PRIMARY_ZIP,'[^a-zA-Z0-9]',''),'[^0-9]','')) < 5 
    THEN LPAD(REGEXP_REPLACE(REGEXP_REPLACE(PRIMARY_ZIP,'[^a-zA-Z0-9]',''),'[^0-9]',''),5,'0')
    ELSE SUBSTR(REGEXP_REPLACE(REGEXP_REPLACE(PRIMARY_ZIP,'[^a-zA-Z0-9]',''),'[^0-9]',''),0,5)
    END)) AS PRIMARY_ZIP,
    UPPER(TRIM(PRIMARY_EMAIL_ADDRESS)) AS PRIMARY_EMAIL_ADDRESS,
    UPPER(TRIM(MEM_RESIDENTIAL_ADDRESS_LINE1)) AS RESIDENTIAL_ADDRESS_LINE1,
    UPPER(TRIM(MEM_RESIDENTIAL_ADDRESS_LINE2)) AS RESIDENTIAL_ADDRESS_LINE2,
    UPPER(TRIM(MEM_RESIDENTIAL_CITY)) AS RESIDENTIAL_CITY,
    UPPER(TRIM(MEM_RESIDENTIAL_STATE)) AS RESIDENTIAL_STATE,
	UPPER(TRIM(CASE
    WHEN LENGTH(REGEXP_REPLACE(MEM_RESIDENTIAL_ZIP,'[^a-zA-Z0-9]','')) = 6 THEN REGEXP_REPLACE(MEM_RESIDENTIAL_ZIP,'[^a-zA-Z0-9]','')
    WHEN LENGTH(REGEXP_REPLACE(REGEXP_REPLACE(MEM_RESIDENTIAL_ZIP,'[^a-zA-Z0-9]',''),'[^0-9]','')) < 5 
    THEN LPAD(REGEXP_REPLACE(REGEXP_REPLACE(MEM_RESIDENTIAL_ZIP,'[^a-zA-Z0-9]',''),'[^0-9]',''),5,'0')
    ELSE SUBSTR(REGEXP_REPLACE(REGEXP_REPLACE(MEM_RESIDENTIAL_ZIP,'[^a-zA-Z0-9]',''),'[^0-9]',''),0,5)
    END)) AS  RESIDENTIAL_ZIP,
    UPPER(TRIM(MEM_BILLING_ADDRESS_LINE1)) AS BILLING_ADDRESS_LINE1,
    UPPER(TRIM(MEM_BILLING_ADDRESS_LINE2)) AS BILLING_ADDRESS_LINE2,
    UPPER(TRIM(MEM_BILLING_CITY)) AS BILLING_CITY,
    UPPER(TRIM(MEM_BILLING_STATE)) AS BILLING_STATE,
	UPPER(TRIM(CASE
    WHEN LENGTH(REGEXP_REPLACE(MEM_BILLING_ZIP,'[^a-zA-Z0-9]','')) = 6 THEN REGEXP_REPLACE(MEM_BILLING_ZIP,'[^a-zA-Z0-9]','')
    WHEN LENGTH(REGEXP_REPLACE(REGEXP_REPLACE(MEM_BILLING_ZIP,'[^a-zA-Z0-9]',''),'[^0-9]','')) < 5 
    THEN LPAD(REGEXP_REPLACE(REGEXP_REPLACE(MEM_BILLING_ZIP,'[^a-zA-Z0-9]',''),'[^0-9]',''),5,'0')
	ELSE SUBSTR(REGEXP_REPLACE(REGEXP_REPLACE(MEM_BILLING_ZIP,'[^a-zA-Z0-9]',''),'[^0-9]',''),0,5)
	END)) AS BILLING_ZIP,
    UPPER(TRIM(MEM_OTHER_ADDRESS_LINE1)) AS OTHER_ADDRESS_LINE1,
    UPPER(TRIM(MEM_OTHER_ADDRESS_LINE2)) AS OTHER_ADDRESS_LINE2,
    UPPER(TRIM(MEM_OTHER_CITY)) AS OTHER_CITY,
    UPPER(TRIM(MEM_OTHER_STATE)) AS OTHER_STATE,
	UPPER(TRIM(CASE
    WHEN LENGTH(REGEXP_REPLACE(MEM_OTHER_ZIP,'[^a-zA-Z0-9]','')) = 6 THEN REGEXP_REPLACE(MEM_OTHER_ZIP,'[^a-zA-Z0-9]','')
    WHEN LENGTH(REGEXP_REPLACE(REGEXP_REPLACE(MEM_OTHER_ZIP,'[^a-zA-Z0-9]',''),'[^0-9]','')) < 5 
    THEN LPAD(REGEXP_REPLACE(REGEXP_REPLACE(MEM_OTHER_ZIP,'[^a-zA-Z0-9]',''),'[^0-9]',''),5,'0')
	ELSE SUBSTR(REGEXP_REPLACE(REGEXP_REPLACE(MEM_OTHER_ZIP,'[^a-zA-Z0-9]',''),'[^0-9]',''),0,5)
	END)) AS OTHER_ZIP,
    UPPER(TRIM(MEM_EMAIL_ADDRESS)) AS OTHER_EMAIL_ADDRESS,	
	CASE WHEN HOME_TELEPHONE_NUM='' THEN NULL ELSE   CASE
    WHEN LENGTH(REGEXP_REPLACE(HOME_TELEPHONE_NUM,'[^a-zA-Z0-9]','')) <= 10 THEN REGEXP_REPLACE(HOME_TELEPHONE_NUM,'[^a-zA-Z0-9]','')
    WHEN SUBSTR(REGEXP_REPLACE(HOME_TELEPHONE_NUM,'[^a-zA-Z0-9]',''),1,1) = '1' THEN SUBSTR(REGEXP_REPLACE(HOME_TELEPHONE_NUM,'[^a-zA-Z0-9]',''),2,11)
  ELSE
  SUBSTR(REGEXP_REPLACE(HOME_TELEPHONE_NUM,'[^a-zA-Z0-9]',''),1,10)
END END AS HOME_TELEPHONE_NUM ,
CASE WHEN WORK_PHONE_NUM='' THEN NULL ELSE   CASE
    WHEN LENGTH(REGEXP_REPLACE(WORK_PHONE_NUM,'[^a-zA-Z0-9]','')) <= 10 THEN REGEXP_REPLACE(WORK_PHONE_NUM,'[^a-zA-Z0-9]','')
    WHEN SUBSTR(REGEXP_REPLACE(WORK_PHONE_NUM,'[^a-zA-Z0-9]',''),1,1) = '1' THEN SUBSTR(REGEXP_REPLACE(WORK_PHONE_NUM,'[^a-zA-Z0-9]',''),2,11)
  ELSE
  SUBSTR(REGEXP_REPLACE(WORK_PHONE_NUM,'[^a-zA-Z0-9]',''),1,10)
END END AS WORK_PHONE_NUM ,
CASE WHEN OTHER_PHONE_NUM='' THEN NULL ELSE   CASE
    WHEN LENGTH(REGEXP_REPLACE(OTHER_PHONE_NUM,'[^a-zA-Z0-9]','')) <= 10 THEN REGEXP_REPLACE(OTHER_PHONE_NUM,'[^a-zA-Z0-9]','')
    WHEN SUBSTR(REGEXP_REPLACE(OTHER_PHONE_NUM,'[^a-zA-Z0-9]',''),1,1) = '1' THEN SUBSTR(REGEXP_REPLACE(OTHER_PHONE_NUM,'[^a-zA-Z0-9]',''),2,11)
  ELSE
  SUBSTR(REGEXP_REPLACE(OTHER_PHONE_NUM,'[^a-zA-Z0-9]',''),1,10)
END END AS OTHER_PHONE_NUM ,
    MEM_CREATE_DATE AS SOURCE_CREATE_DATE,
	TERM_EXPIRATION_DT
  FROM (
    SELECT
    CONCAT(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),1,15),SAFE_CAST( (CASE
          WHEN MOD ( CASE
            WHEN CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),1,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),1,1) AS INT64)*2,10)
            ELSE CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),1,1) AS INT64)*2
          END +CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),2,1) AS INT64) + (CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),3,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),3,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),3,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),4,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),5,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),5,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),5,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),6,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),7,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),7,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),7,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),8,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),9,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),9,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),9,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),10,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),11,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),11,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),11,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),12,1) AS INT64) + (CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),13,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),13,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),13,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),14,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),15,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),15,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),15,1) AS INT64)*2 END),10)= 0 THEN 0
          ELSE 10 - MOD (CASE
            WHEN CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),1,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),1,1) AS INT64)*2,10)
            ELSE CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),1,1) AS INT64)*2
          END +CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),2,1) AS INT64) + (CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),3,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),3,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),3,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),4,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),5,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),5,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),5,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),6,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),7,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),7,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),7,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),8,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),9,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),9,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),9,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),10,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),11,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),11,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),11,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),12,1) AS INT64) + (CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),13,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),13,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),13,1) AS INT64)*2
            END ) +CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),14,1) AS INT64) +(CASE
              WHEN CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),15,1) AS INT64) *2 >9 THEN 1+MOD(CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),15,1) AS INT64)*2,10)
              ELSE CAST(SUBSTR(CONCAT('429005',TRIM(A.MEMBER_NUM),TRIM(A.ASSOCIATE_ID)),15,1) AS INT64)*2 END),10)
        END ) AS STRING ))
       AS MEMBER_NUM,
      A.MEMBER_NUM AS MEMBERSHIP_ID,
      A.ASSOCIATE_ID AS ASSOC_CODE,
      UPPER(A.MBR_FST_NM) AS FIRST_NM,
      UPPER(A.MBR_LST_NM ) AS LAST_NM,
      UPPER(A.MBR_NM_SUFX_CD ) AS NAME_SUFFIX_CD,
      UPPER(A.MBR_SLTN_CD ) AS SALUTATION_CD,
	  UPPER(MBR_CARD_NAME)  AS PREFFERRED_NM,
      UPPER(MBR_MID_INIT_NM) AS MIDDLE_NM,
      UPPER(DECEASED_IND) AS DECEASED_IND,
       CASE
        WHEN PARSE_DATE('%Y-%m-%d',SUBSTR(A.MBR_BRTH_DT,0,10)) < PARSE_DATE('%Y-%m-%d', '1910-01-01') OR PARSE_DATE('%Y-%m-%d',SUBSTR(A.MBR_BRTH_DT,0,10)) > DATE_SUB(CURRENT_DATE(),INTERVAL 10 YEAR) THEN SAFE_CAST(NULL AS DATE)
        ELSE PARSE_DATE('%Y-%m-%d',SUBSTR(A.MBR_BRTH_DT,0,10))
      END AS BIRTH_DT,
      UPPER(A.MBR_GNDR_CD ) AS GENDER_CD,
      CAST(NULL AS STRING) AS MARITAL_STATUS,
      CASE
        WHEN RESIDENTIAL_ADDRESS_LINE1 IS NULL 
			THEN CASE
			WHEN BILLING_ADDRESS_LINE1 IS NULL 
				THEN UPPER(TEMPORARY_ADDRESS_LINE1)
				ELSE UPPER(BILLING_ADDRESS_LINE1)
				END
        ELSE UPPER(RESIDENTIAL_ADDRESS_LINE1)
      END AS PRIMARY_ADDRESS_LINE1,
      CASE
        WHEN RESIDENTIAL_ADDRESS_LINE1 IS NULL THEN CASE
        WHEN BILLING_ADDRESS_LINE1 IS NULL THEN UPPER(TEMPORARY_ADDRESS_LINE2)
        ELSE UPPER(BILLING_ADDRESS_LINE2)
      END
        ELSE UPPER(RESIDENTIAL_ADDRESS_LINE2)
      END AS PRIMARY_ADDRESS_LINE2,
      CASE
        WHEN RESIDENTIAL_ADDRESS_LINE1 IS NULL THEN CASE
        WHEN BILLING_ADDRESS_LINE1 IS NULL THEN UPPER(TEMPORARY_CITY)
        ELSE UPPER(BILLING_CITY)
      END
        ELSE UPPER(RESIDENTIAL_CITY)
      END AS PRIMARY_CITY,
      CASE
        WHEN RESIDENTIAL_ADDRESS_LINE1 IS NULL THEN CASE
        WHEN BILLING_ADDRESS_LINE1 IS NULL THEN UPPER(TEMPORARY_STATE)
        ELSE UPPER(BILLING_STATE)
      END
        ELSE UPPER(RESIDENTIAL_STATE)
      END AS PRIMARY_STATE,
      CASE
        WHEN RESIDENTIAL_ADDRESS_LINE1 IS NULL THEN CASE
        WHEN BILLING_ADDRESS_LINE1 IS NULL THEN UPPER(TEMPORARY_ZIP)
        ELSE UPPER(BILLING_ZIP)
      END
        ELSE UPPER(RESIDENTIAL_ZIP)
      END AS PRIMARY_ZIP,
      UPPER(EMAIL_ADDRESS) AS PRIMARY_EMAIL_ADDRESS,
      UPPER(RESIDENTIAL_ADDRESS_LINE1) AS MEM_RESIDENTIAL_ADDRESS_LINE1,
      UPPER(RESIDENTIAL_ADDRESS_LINE2) AS MEM_RESIDENTIAL_ADDRESS_LINE2,
      UPPER(RESIDENTIAL_CITY) AS MEM_RESIDENTIAL_CITY,
      UPPER(RESIDENTIAL_STATE) AS MEM_RESIDENTIAL_STATE,
      RESIDENTIAL_ZIP AS MEM_RESIDENTIAL_ZIP,
      UPPER(BILLING_ADDRESS_LINE1) AS MEM_BILLING_ADDRESS_LINE1,
      UPPER(BILLING_ADDRESS_LINE2) AS MEM_BILLING_ADDRESS_LINE2,
      UPPER(BILLING_CITY) AS MEM_BILLING_CITY,
      UPPER(BILLING_STATE) AS MEM_BILLING_STATE,
      BILLING_ZIP AS MEM_BILLING_ZIP,
      UPPER(TEMPORARY_ADDRESS_LINE1) AS MEM_OTHER_ADDRESS_LINE1,
      UPPER(TEMPORARY_ADDRESS_LINE2) AS MEM_OTHER_ADDRESS_LINE2,
      UPPER(TEMPORARY_CITY) AS MEM_OTHER_CITY,
      UPPER(TEMPORARY_STATE) AS MEM_OTHER_STATE,
      TEMPORARY_ZIP AS MEM_OTHER_ZIP,
      CAST(NULL AS STRING) AS MEM_EMAIL_ADDRESS,
      HOME_PHONE_NUM AS HOME_TELEPHONE_NUM,
      MOBILE_PHONE_NUM AS WORK_PHONE_NUM,
      WORK_PHONE_NUM AS OTHER_PHONE_NUM,
      PARSE_DATE('%Y-%m-%d',MBRS_UPDATE_DT) AS MEM_CREATE_DATE,
	  C.TERM_EXPIRATION_DT AS TERM_EXPIRATION_DT
    FROM
     LANDING.WORK_CS_MEMBERSHIP_CUSTOMER_DIM A
	  LEFT OUTER JOIN
    (
  select * from
 ( select DISTINCT MEMBERSHIP_NUM,TERM_EXPIRATION_DT, row_number() over (partition by MEMBERSHIP_NUM order by row_start_dt desc )  AS rownum from CUSTOMER_PRODUCT.CONNECTSUITE_MEMBERSHIP_DIM  where ACTIVE_FLG='Y') where rownum = 1
  
  ) C
	on A.MEMBER_NUM=C.MEMBERSHIP_NUM
)); 

----------------------------------------------------------------------
--STEP 1.2
---------------------------------------------------------------------- 

INSERT INTO
  LANDING.MDM_CUSTOMER_EXCEPTIONS ( SOURCE_KEY1,
    SOURCE_KEY2,
    SOURCE_KEY3,
    SOURCE_KEY1_DESC,
    SOURCE_KEY2_DESC,
    SOURCE_KEY3_DESC,
    SOURCE_SYSTEM_CD,
    FIRST_NM,
    LAST_NM,
    MIDDLE_NM,
    PREFFERRED_NM,
    NAME_SUFFIX_CD,
    SALUTATION_CD,
    BIRTH_DT,
    GENDER_CD,
    MARITAL_STATUS,
    DECEASED_IND,
    PRIMARY_ADDRESS_LINE1,
    PRIMARY_ADDRESS_LINE2,
    PRIMARY_CITY,
    PRIMARY_STATE,
    PRIMARY_ZIP,
    PRIMARY_EMAIL_ADDRESS,
	PRIMARY_PHONE_NUM,
    RESIDENTIAL_ADDRESS_LINE1,
    RESIDENTIAL_ADDRESS_LINE2,
    RESIDENTIAL_CITY,
    RESIDENTIAL_STATE,
    RESIDENTIAL_ZIP,
    BILLING_ADDRESS_LINE1,
    BILLING_ADDRESS_LINE2,
    BILLING_CITY,
    BILLING_STATE,
    BILLING_ZIP,
    OTHER_ADDRESS_LINE1,
    OTHER_ADDRESS_LINE2,
    OTHER_CITY,
    OTHER_STATE,
    OTHER_ZIP,
    OTHER_EMAIL_ADDRESS,
    HOME_TELEPHONE_NUM,
    WORK_PHONE_NUM,
    OTHER_PHONE_NUM,
    SOURCE_CREATE_DATE,
    CREATE_DTTIME
    )
SELECT
    SOURCE_KEY1,
    SOURCE_KEY2,
    SOURCE_KEY3,
    SOURCE_KEY1_DESC,
    SOURCE_KEY2_DESC,
    SOURCE_KEY3_DESC,
    SOURCE_SYSTEM_CD,
    FIRST_NM,
    LAST_NM,
    MIDDLE_NM,
    PREFFERRED_NM,
    NAME_SUFFIX_CD,
    SALUTATION_CD,
    BIRTH_DT,
    GENDER_CD,
    MARITAL_STATUS,
    DECEASED_IND,
    PRIMARY_ADDRESS_LINE1,
    PRIMARY_ADDRESS_LINE2,
    PRIMARY_CITY,
    PRIMARY_STATE,
    PRIMARY_ZIP,
    PRIMARY_EMAIL_ADDRESS,
	PRIMARY_PHONE_NUM,
    RESIDENTIAL_ADDRESS_LINE1,
    RESIDENTIAL_ADDRESS_LINE2,
    RESIDENTIAL_CITY,
    RESIDENTIAL_STATE,
    RESIDENTIAL_ZIP,
    BILLING_ADDRESS_LINE1,
    BILLING_ADDRESS_LINE2,
    BILLING_CITY,
    BILLING_STATE,
    BILLING_ZIP,
    OTHER_ADDRESS_LINE1,
    OTHER_ADDRESS_LINE2,
    OTHER_CITY,
    OTHER_STATE,
    OTHER_ZIP,
    OTHER_EMAIL_ADDRESS,
    HOME_TELEPHONE_NUM,
    WORK_PHONE_NUM,
    OTHER_PHONE_NUM,
    SOURCE_CREATE_DATE,
    CURRENT_DATETIME() AS CREATE_DTTIME
FROM
  LANDING.WORK_MDM_MEMBERSHIP
WHERE
  REGEXP_CONTAINS(PRIMARY_CITY, '[0-9]')
  OR LENGTH(PRIMARY_ZIP) < 5
  OR LENGTH(PRIMARY_ZIP) >10
  OR REGEXP_CONTAINS(FIRST_NM, '[0-9]')
  OR REGEXP_CONTAINS(LAST_NM, '[0-9]')
  OR FIRST_NM IS NULL
  OR LAST_NM IS NULL
  OR PRIMARY_ADDRESS_LINE1 IS NULL
  OR TRIM(PRIMARY_ADDRESS_LINE1)='';
----------------------------------------------------------------------
--STEP 1.3
----------------------------------------------------------------------  
DELETE
FROM
  LANDING.WORK_MDM_MEMBERSHIP
WHERE
  REGEXP_CONTAINS(PRIMARY_CITY, '[0-9]')
  OR LENGTH(PRIMARY_ZIP) < 5
  OR LENGTH(PRIMARY_ZIP) >10
  OR REGEXP_CONTAINS(FIRST_NM, '[0-9]')
  OR REGEXP_CONTAINS(LAST_NM, '[0-9]')
  OR FIRST_NM IS NULL
  OR LAST_NM IS NULL
  OR PRIMARY_ADDRESS_LINE1 IS NULL
  OR TRIM(PRIMARY_ADDRESS_LINE1)='';

----------------------------------------------------------------------
--STEP2.1
----------------------------------------------------------------------
update  LANDING.WORK_MDM_MEMBERSHIP set MERGE_FLAG='Ignore'
where MERGE_FLAG ='      ' and (MERGE_CHECK2_CTL+MERGE_CHECK1_CTL)=0
and not (HOME_TELEPHONE_NUM is not null or WORK_PHONE_NUM is not null or OTHER_PHONE_NUM is not null);
----------------------------------------------------------------------
--STEP2.2
----------------------------------------------------------------------
update  LANDING.WORK_MDM_MEMBERSHIP set MERGE_FLAG='Golden',GOLDEN_MATCH_KEY=SOURCE_KEY1
where MERGE_FLAG ='      ' 
AND MERGE_CHECK2_CTL in (0,1) and MERGE_CHECK1_CTL in (0,1);

----------------------------------------------------------------------
--STEP2.3 -- This Update statement to identify the group where FIRST_NAME,LAST_NAME and BIRTH_DT are same.
----------------------------------------------------------------------
UPDATE LANDING.WORK_MDM_MEMBERSHIP D
SET D.WORK_MATCH_GROUP=C.MATCH_SOURCE_KEY
FROM (select SOURCE_KEY1,
FIRST_VALUE(SOURCE_KEY1) OVER (PARTITION BY UPPER(FIRST_NM),UPPER(LAST_NM),
BIRTH_DT ORDER BY SOURCE_CREATE_DATE DESC,SOURCE_KEY1 DESC) MATCH_SOURCE_KEY
from LANDING.WORK_MDM_MEMBERSHIP where MERGE_FLAG ='      '  
and (MERGE_CHECK2_CTL+MERGE_CHECK1_CTL)>=2) C
WHERE C.SOURCE_KEY1=D.SOURCE_KEY1
and D.MERGE_FLAG ='      ';
----------------------------------------------------------------------
--STEP2.4 -- Below Updates statement to identify the groups where FIRST_NAME,LAST_NAME, BIRTH_DT and ADDRESS are same from STEP2.3.
----------------------------------------------------------------------
UPDATE LANDING.WORK_MDM_MEMBERSHIP D
SET D.ADDRESS_MATCH_SOURCE_KEY=C.ADDRESS_MATCH_SOURCE_KEY,D.ADDRESS_MATCH_DESC='Merge' -- ADDRESS_MATCH
FROM (select SOURCE_KEY1,
FIRST_VALUE(SOURCE_KEY1) OVER (PARTITION BY WORK_MATCH_GROUP,UPPER(FIRST_NM),UPPER(LAST_NM),
BIRTH_DT,UPPER(PRIMARY_ADDRESS_LINE1),UPPER(PRIMARY_ADDRESS_LINE2),UPPER(PRIMARY_CITY),UPPER(PRIMARY_STATE),UPPER(PRIMARY_ZIP)
ORDER BY SOURCE_CREATE_DATE DESC,SOURCE_KEY1 DESC) ADDRESS_MATCH_SOURCE_KEY
from LANDING.WORK_MDM_MEMBERSHIP where MERGE_FLAG ='      '  
and (MERGE_CHECK2_CTL+MERGE_CHECK1_CTL)>=2
) C
WHERE C.SOURCE_KEY1=D.SOURCE_KEY1
and D.MERGE_FLAG ='      ';
-----------
update  LANDING.WORK_MDM_MEMBERSHIP A set A.ADDRESS_MATCH_DESC ='Golden' -- ADDRESS_MATCH Golden Record
where exists (select 1 from 
(select SOURCE_KEY1,ROW_NUMBER() OVER (PARTITION BY UPPER(FIRST_NM),UPPER(LAST_NM),
BIRTH_DT,UPPER(PRIMARY_ADDRESS_LINE1),UPPER(PRIMARY_ADDRESS_LINE2),UPPER(PRIMARY_CITY),UPPER(PRIMARY_STATE),UPPER(PRIMARY_ZIP)
ORDER BY SOURCE_CREATE_DATE DESC,SOURCE_KEY1 DESC) AS ROW_NUM  from LANDING.WORK_MDM_MEMBERSHIP where 
MERGE_FLAG ='      '  
and (MERGE_CHECK2_CTL+MERGE_CHECK1_CTL)>=2) B
where B.SOURCE_KEY1=A.SOURCE_KEY1 and ROW_NUM=1)
and MERGE_FLAG ='      ';

update LANDING.WORK_MDM_MEMBERSHIP SET EMAIL_MATCH_SOURCE_KEY=ADDRESS_MATCH_SOURCE_KEY, EMAIL_MATCH_DESC=ADDRESS_MATCH_DESC
where MERGE_FLAG ='      ' and MERGE_CHECK2_CTL=0 and MERGE_CHECK1_CTL>=2
and PRIMARY_EMAIL_ADDRESS is null;
 
----------------------------------------------------------------------
--STEP2.5 -- Below Updates statement to identify the groups where FIRST_NAME,LAST_NAME, BIRTH_DT and EMAIL are same from STEP2.3.
----------------------------------------------------------------------
UPDATE LANDING.WORK_MDM_MEMBERSHIP D
SET D.EMAIL_MATCH_SOURCE_KEY=C.EMAIL_MATCH_SOURCE_KEY,D.EMAIL_MATCH_DESC='Merge' -- EMAIL MATCH
FROM (select SOURCE_KEY1,
FIRST_VALUE(SOURCE_KEY1) OVER (PARTITION BY WORK_MATCH_GROUP,UPPER(FIRST_NM),UPPER(LAST_NM),
BIRTH_DT,UPPER(PRIMARY_EMAIL_ADDRESS)
ORDER BY SOURCE_CREATE_DATE DESC,SOURCE_KEY1 DESC) EMAIL_MATCH_SOURCE_KEY
from LANDING.WORK_MDM_MEMBERSHIP where MERGE_FLAG ='      '  
and (MERGE_CHECK2_CTL+MERGE_CHECK1_CTL)>=2
) C
WHERE C.SOURCE_KEY1=D.SOURCE_KEY1
and D.MERGE_FLAG ='      '
and PRIMARY_EMAIL_ADDRESS is not null;

---------------

update  LANDING.WORK_MDM_MEMBERSHIP A set A.EMAIL_MATCH_DESC ='Golden' -- EMAIL_MATCH Golden Record
where exists (select 1 from 
(select SOURCE_KEY1,ROW_NUMBER() OVER (PARTITION BY UPPER(FIRST_NM),UPPER(LAST_NM),
BIRTH_DT,UPPER(PRIMARY_EMAIL_ADDRESS)
ORDER BY SOURCE_CREATE_DATE DESC,SOURCE_KEY1 DESC) AS ROW_NUM  from LANDING.WORK_MDM_MEMBERSHIP where 
MERGE_FLAG ='      '  
and (MERGE_CHECK2_CTL+MERGE_CHECK1_CTL)>=2) B
where B.SOURCE_KEY1=A.SOURCE_KEY1 and ROW_NUM=1)
and MERGE_FLAG ='      '
and PRIMARY_EMAIL_ADDRESS is not null;

----------------------------------------------------------------------
--STEP2.5 -- Below Updates statement to identify the Golden Match Key Based on Address and Email Match Keys Values.
----------------------------------------------------------------------

update  LANDING.WORK_MDM_MEMBERSHIP A 
SET A.GOLDEN_MATCH_KEY=B.GOLDEN_MATCH_KEY
FROM (select SOURCE_KEY1,ADDRESS_MATCH_SOURCE_KEY,EMAIL_MATCH_SOURCE_KEY as GOLDEN_MATCH_KEY from LANDING.WORK_MDM_MEMBERSHIP where ADDRESS_MATCH_DESC ='Golden' and EMAIL_MATCH_DESC  in ('Golden','Merge')
and (MERGE_CHECK2_CTL+MERGE_CHECK1_CTL)>=2) B
where A.SOURCE_KEY1=B.SOURCE_KEY1
and A.MERGE_FLAG ='      ';
---------------
update  LANDING.WORK_MDM_MEMBERSHIP A 
SET A.GOLDEN_MATCH_KEY=B.GOLDEN_MATCH_KEY
FROM (select M.SOURCE_KEY1,G.GOLDEN_MATCH_KEY from
(select SOURCE_KEY1,ADDRESS_MATCH_SOURCE_KEY,EMAIL_MATCH_SOURCE_KEY as GOLDEN_MATCH_KEY from LANDING.WORK_MDM_MEMBERSHIP where ADDRESS_MATCH_DESC ='Golden' and EMAIL_MATCH_DESC  in ('Golden','Merge') and (MERGE_CHECK2_CTL+MERGE_CHECK1_CTL)>=2) G,
(select SOURCE_KEY1,ADDRESS_MATCH_SOURCE_KEY,EMAIL_MATCH_SOURCE_KEY as GOLDEN_MATCH_KEY from LANDING.WORK_MDM_MEMBERSHIP where ADDRESS_MATCH_DESC ='Merge' and (MERGE_CHECK2_CTL+MERGE_CHECK1_CTL)>=2) M
WHERE G.ADDRESS_MATCH_SOURCE_KEY=M.ADDRESS_MATCH_SOURCE_KEY
) B
where A.SOURCE_KEY1=B.SOURCE_KEY1
and A.MERGE_FLAG ='      ';

----------------------------------------------------------------------
--STEP2.6 -- Below Updates statement to identify the Golden and Merge Records Based on Golden Match Key Values.
----------------------------------------------------------------------


update  LANDING.WORK_MDM_MEMBERSHIP A 
SET A.MERGE_FLAG='Golden'
Where ADDRESS_MATCH_DESC ='Golden' and EMAIL_MATCH_DESC  in ('Golden')
and A.MERGE_FLAG ='      ';


update  LANDING.WORK_MDM_MEMBERSHIP A 
SET A.MERGE_FLAG='Merge'
FROM (select M.SOURCE_KEY1,G.GOLDEN_MATCH_KEY from
(select SOURCE_KEY1,GOLDEN_MATCH_KEY from LANDING.WORK_MDM_MEMBERSHIP where ADDRESS_MATCH_DESC ='Golden' and EMAIL_MATCH_DESC  in ('Golden')) G,
(select SOURCE_KEY1,GOLDEN_MATCH_KEY from LANDING.WORK_MDM_MEMBERSHIP where WORK_MATCH_GROUP<>'Golden'  ) M
WHERE G.GOLDEN_MATCH_KEY=M.GOLDEN_MATCH_KEY) B
WHERE A.SOURCE_KEY1=B.SOURCE_KEY1
and A.MERGE_FLAG ='      ';

update LANDING.WORK_MDM_MEMBERSHIP A  
SET A.MERGE_FLAG='Merge' , A.GOLDEN_MATCH_KEY=A.WORK_MATCH_GROUP
where MERGE_FLAG ='      ';

----------------------------------------------------------------------
--STEP2.7 -- DOB Merge , If Incase any DOB is null
----------------------------------------------------------------------
update  LANDING.WORK_MDM_MEMBERSHIP A 
SET A.MERGE_FLAG='DOB_Merge',A.GOLDEN_MATCH_KEY=B.GOLDEN_MATCH_KEY
FROM (
select C.SOURCE_KEY1 as SOURCE_KEY1,D.SOURCE_KEY1 as GOLDEN_MATCH_KEY FROM
(select * from LANDING.WORK_MDM_MEMBERSHIP where BIRTH_DT IS NULL and MERGE_FLAG='Golden' )C
INNER JOIN (select *,
ROW_NUMBER() OVER(PARTITION BY UPPER(FIRST_NM),UPPER(LAST_NM),UPPER(PRIMARY_ADDRESS_LINE1),UPPER(PRIMARY_ADDRESS_LINE2),UPPER(PRIMARY_CITY),
    UPPER(PRIMARY_STATE),UPPER(PRIMARY_ZIP) ORDER BY SOURCE_CREATE_DATE DESC,SOURCE_KEY1 DESC) as ROW_NUM
    FROM LANDING.WORK_MDM_MEMBERSHIP where MERGE_FLAG='Golden' and BIRTH_DT IS NOT NULL ) D
ON COALESCE(C.FIRST_NM,'~')=COALESCE(D.FIRST_NM,'~')
AND COALESCE(C.LAST_NM,'~')=COALESCE(D.LAST_NM,'~')
AND COALESCE(C.PRIMARY_ADDRESS_LINE1,'~')=COALESCE(D.PRIMARY_ADDRESS_LINE1,'~')
AND COALESCE(C.PRIMARY_ADDRESS_LINE2,'~')=COALESCE(D.PRIMARY_ADDRESS_LINE2,'~') 
AND COALESCE(C.PRIMARY_CITY,'~')=COALESCE(D.PRIMARY_CITY,'~') 
AND COALESCE(C.PRIMARY_STATE,'~')=COALESCE(D.PRIMARY_STATE,'~')
AND COALESCE(C.PRIMARY_ZIP,'~')=COALESCE(D.PRIMARY_ZIP,'~')
and D.ROW_NUM=1) B
where A.SOURCE_KEY1=B.SOURCE_KEY1;
----------------------------------------------------------------------
--STEP2.8 DOB Merge
----------------------------------------------------------------------
update  LANDING.WORK_MDM_MEMBERSHIP A 
SET A.GOLDEN_MATCH_KEY=B.GOLDEN_MATCH_KEY
FROM (select DOB.GOLDEN_MATCH_KEY AS GOLDEN_MATCH_KEY,
M.SOURCE_KEY1 as SOURCE_KEY1 FROM
(select SOURCE_KEY1,GOLDEN_MATCH_KEY from LANDING.WORK_MDM_MEMBERSHIP  
where MERGE_FLAG='DOB_Merge') DOB,
(select SOURCE_KEY1,GOLDEN_MATCH_KEY from LANDING.WORK_MDM_MEMBERSHIP 
where MERGE_FLAG='Merge') M
where DOB.SOURCE_KEY1=M.GOLDEN_MATCH_KEY) B
where A.MERGE_FLAG='Merge'
AND A.SOURCE_KEY1=B.SOURCE_KEY1;
----------------------------------------------------------------------
--STEP2.9 DOB Merge
----------------------------------------------------------------------
update LANDING.WORK_MDM_MEMBERSHIP SET MERGE_FLAG='Merge'
where MERGE_FLAG='DOB_Merge'
