SELECT 
TO_CHAR(CSH.BRANCH_CD) BRANCH_CD, 
TO_CHAR(CSH.RECEIVED_DT,'YYYY-MM-DD HH:MM:SS') AS RECEIVED_DT, 
TO_CHAR(CSH.CMPLNT_ID) CMPLNT_ID, 
TO_CHAR(CSH.STATUS_CD) STATUS_CD, 
TO_CHAR(CSH.STATUS_DTIME_DT,'YYYY-MM-DD HH:MM:SS') AS STATUS_DTIME_DT, 
TO_CHAR(CSH.STATUS_EMPLE_ID) STATUS_EMPLE_ID, 
TO_CHAR(CSH.STATUS_TX) STATUS_TX, 
TO_CHAR(CSH.STATUS_SEQ_NBR) STATUS_SEQ_NBR
FROM
 NCA_CTS.CMPLNT_STATUS_HIST CSH
WHERE TRUNC(CSH.RECEIVED_DT)>=to_date('v_input','yyyy-mm-dd')