SELECT TO_CHAR(INCD_ROUTING_LIST.BRANCH_CD)  BRANCH_CD, 
TO_CHAR(INCD_ROUTING_LIST.RECEIVED_DT,'YYYY-MM-DD HH:MM:SS') AS RECEIVED_DT, 
TO_CHAR(INCD_ROUTING_LIST.CMPLNT_ID) CMPLNT_ID, 
TO_CHAR(INCD_ROUTING_LIST.INCD_ID) INCD_ID, 
TO_CHAR(INCD_ROUTING_LIST.RTE_SEQ_NBR) RTE_SEQ_NBR, 
TO_CHAR(INCD_ROUTING_LIST.RTE_EMPLE_ID) RTE_EMPLE_ID, 
TO_CHAR(INCD_ROUTING_LIST.IS_GROUP)  IS_GROUP
FROM
NCA_CTS.INCD_ROUTING_LIST INCD_ROUTING_LIST 
WHERE TRUNC(INCD_ROUTING_LIST.RECEIVED_DT)>= to_date('v_input','yyyy-mm-dd')