SELECT  
TO_CHAR(COMPLAINT.CMPLNT_ID) CMPLNT_ID , 
TO_CHAR(VICTIMS.MBR_ID) MBR_ID, 
TO_CHAR(COMPLAINT.RECEIVED_DT,'YYYY-MM-DD HH:MM:SS') AS RECEIVED_DT, 
TO_CHAR(COMPLAINT.BRANCH_CD) BRANCH_CD, 
TO_CHAR(COMPLAINT.CATEGORY_CD) CATEGORY_CD, 
TO_CHAR(COMPLAINT.CURR_STATUS_CD) CURR_STATUS_CD, 
TO_CHAR(COMPLAINT.ORIGIN_CD) ORIGIN_CD, 
TO_CHAR(SUBSTR (REGEXP_REPLACE(NARRATIVE, '[^0-9A-Za-z :-]', ' '),1,4000)) AS NARRATIVE,
TO_CHAR(COMPLAINT.ORIG_CLB_CD) ORIG_CLB_CD, 
TO_CHAR(VICTIMS.FIRST_NM) FIRST_NM, 
TO_CHAR(VICTIMS.LAST_NM) LAST_NM, 
TO_CHAR(VICTIMS.BASIC_ADR) BASIC_ADR, 
TO_CHAR(VICTIMS.CITY_NM) CITY_NM, 
TO_CHAR(VICTIMS.ST_CD) ST_CD, 
TO_CHAR(VICTIMS.ZIP_CD) ZIP_CD, 
TO_CHAR(VICTIMS.TELEPHONE_NBR) TELEPHONE_NBR, 
TO_CHAR(VICTIMS.EMAIL_ADR) EMAIL_ADR, 
TO_CHAR(COMPLAINT.RECV_EMPLE_ID) RECV_EMPLE_ID, 
REGEXP_REPLACE(CODES.DESCRIPTION_TX,'[^0-9A-Za-z :-]', ' ') DESCRIPTION_TX, 
TO_CHAR(VICTIMS.ASC_ID) ASC_ID, 
TO_CHAR(VICTIMS.CLUB_CD) CLUB_CD 
FROM NCA_CTS.COMPLAINT  COMPLAINT 
INNER JOIN NCA_CTS.CMPLNT_VICTIMS  VICTIMS
ON COMPLAINT.CMPLNT_ID  = VICTIMS.CMPLNT_ID AND COMPLAINT.RECEIVED_DT = VICTIMS.RECEIVED_DT AND COMPLAINT.BRANCH_CD = VICTIMS.BRANCH_CD
LEFT JOIN NCA_CTS.CTS_KEY_TYPES CODES
ON COMPLAINT.CATEGORY_CD = CODES.KEY_TYPE_CD
WHERE TRUNC(COMPLAINT.RECEIVED_DT)>=to_date('v_input','yyyy-mm-dd')
