SELECT TO_CHAR(INCIDENT.BRANCH_CD) BRANCH_CD, 
TO_CHAR(INCIDENT.RECEIVED_DT,'YYYY-MM-DD HH:MM:SS') AS RECEIVED_DT,
TO_CHAR(INCIDENT.CMPLNT_ID) CMPLNT_ID, 
TO_CHAR(INCIDENT.INCD_ID) INCD_ID, 
TO_CHAR(INCIDENT.KEY_TYPE_CD) KEY_TYPE_CD, 
TO_CHAR(INCIDENT.SC_DT,'YYYY-MM-DD HH:MM:SS') AS SC_DT,
TO_CHAR(INCIDENT.SC_ID) SC_ID,
TO_CHAR(INCIDENT.INCD_DATE_DT,'YYYY-MM-DD HH:MM:SS') AS INCD_DATE_DT,
TO_CHAR(INCIDENT.CURR_RTE_EMPLE_ID) CURR_RTE_EMPLE_ID, 
TO_CHAR(INCIDENT.CURR_STATUS_CD) CURR_STATUS_CD, 
REGEXP_REPLACE(INCIDENT.DESCRIPTION_TX, '[^0-9A-Za-z :-]', ' ') AS DESCRIPTION_TX,
TO_CHAR(INCIDENT.PRIORITY_CD) PRIORITY_CD,
TO_CHAR(PRIORITY.LEVEL_TX) AS PRIORITY_DESCRIPTION,
TO_CHAR(INCIDENT.COMPLAINT_FLG) COMPLAINT_FLG, 
TO_CHAR(INCIDENT.INCD_CLUB_CD) INCD_CLUB_CD,
TO_CHAR(INCIDENT.CATEGORY_CD) CATEGORY_CD, 
REGEXP_REPLACE(COMMENT1.DESCRIPTION,'[^0-9A-Za-z :-]', ' ') AS CATEGORY_DESCRIPTION,
TO_CHAR(INCIDENT.CLOSE_EMPLE_ID) CLOSE_EMPLE_ID, 
TO_CHAR(INCIDENT.DEPT_CD) DEPT_CD, 
TO_CHAR(INCIDENT.CHARGEBACK_AMT) CHARGEBACK_AMT, 
TO_CHAR(INCIDENT.TRUCK_ID) TRUCK_ID,
TO_CHAR(INCIDENT.DRIVER_ID) DRIVER_ID,
TO_CHAR(INCD_RESOLUTION.RSLUTN_CD) RSLUTN_CD,
REGEXP_REPLACE(RESOLUTION.DESCRIPTION_TX,'[^0-9A-Za-z :-]', ' ') AS RSLUTN_DESCRIPTION,
TO_CHAR(INCD_RESOLUTION.RSLUTN_AMT) RSLUTN_AMT,
TO_CHAR(INCD_RESOLUTION.AMT_REQUESTED) AMT_REQUESTED,
REGEXP_REPLACE(KEY_TYPES.DESCRIPTION_TX, '[^0-9A-Za-z :-]', ' ') KEY_TYPE_DESC
FROM
NCA_CTS.INCIDENT INCIDENT LEFT OUTER JOIN 
NCA_CTS.INCD_RESOLUTION INCD_RESOLUTION
ON INCIDENT.BRANCH_CD = INCD_RESOLUTION.BRANCH_CD AND 
INCIDENT.RECEIVED_DT = INCD_RESOLUTION.RECEIVED_DT AND 
INCIDENT.CMPLNT_ID = INCD_RESOLUTION.CMPLNT_ID AND 
INCIDENT.INCD_ID=INCD_RESOLUTION.INCD_ID
LEFT OUTER JOIN NCA_CTS.CTS_PRIORITY_CODES PRIORITY  
ON INCIDENT.PRIORITY_CD = PRIORITY.PRIORITY_CD
LEFT OUTER JOIN NCA_CTS.COMMENT_CATEGORY COMMENT1 
ON COMMENT1.CODE = INCIDENT.CATEGORY_CD
LEFT OUTER JOIN NCA_CTS.CTS_RESOLUTION_CDS RESOLUTION ON RESOLUTION.RSLUTN_CD = INCD_RESOLUTION.RSLUTN_CD
LEFT OUTER JOIN NCA_CTS.CTS_KEY_TYPES KEY_TYPES ON KEY_TYPES.KEY_TYPE_CD = INCIDENT.KEY_TYPE_CD
WHERE TRUNC(INCIDENT.RECEIVED_DT)>=to_date('v_input','yyyy-mm-dd')