CREATE OR REPLACE TABLE REFERENCE.CONNECTSUITE_M_SALES_AGENT AS
(select
CAST(SAGT_KY AS INT64) AS SAGT_KY,
SAGT_ID,
SAGT_FST_NM,
SAGT_LST_NM,
SAGT_COMP_METH_CD,
CAST(SAGT_MTD_COMP_AM AS FLOAT64) AS SAGT_MTD_COMP_AM,
CAST(SAGT_PTD_COMP_AM AS FLOAT64) AS SAGT_PTD_COMP_AM,
CAST(SAGT_YTD_COMP_AM AS FLOAT64) AS SAGT_YTD_COMP_AM,
SAGT_SSN_NR,
SAGT_COMM_IN,
CAST(TRIM(SAGT_HIRE_DT) AS DATETIME) AS SAGT_HIRE_DT,
CAST(SAGT_DRAW_AMT AS FLOAT64) AS SAGT_DRAW_AMT,
SAGT_COST_CNTR,
CAST(BRN_KY AS INT64) AS BRN_KY,
SAGT_TYP_CD,
INACTIVE_IND,
EMPLOYEE_ID,
SAGT_UPDT_ID,
CAST(TRIM(SAGT_UPDT_DT) AS DATETIME) AS SAGT_UPDT_DT,
"jobrunid" as JOB_RUN_ID,
'CONNECT SUITE' as SOURCE_SYSTEM_CD,
CURRENT_DATETIME() as CREATE_DT
from
LANDING.WORK_M_SALES_AGENT)