CREATE OR REPLACE TABLE REFERENCE.CONNECTSUITE_M_CLUB AS
(select
CAST(CLB_KY AS INT64) AS CLB_KY,
CLB_CD,
CLB_NM,
CLB_BSC_AD,
CLB_SUPL_AD,
CLB_CTY_NM,
CLB_ST_PROV_CD,
CLB_ZIP_CD,
CLB_MRCHT_NB,
CLB_GEN_MRCHT_NB,
CLB_TEL_NR,
CLB_ISO_NR,
CLB_RT_MRCHT_NB,
CLB_OLJ_MRCHT_NB,
"jobrunid" as JOB_RUN_ID,
'CONNECT SUITE' as SOURCE_SYSTEM_CD,
CURRENT_DATETIME() as CREATE_DT
from
LANDING.WORK_M_CLUB)