CREATE OR REPLACE TABLE REFERENCE.CONNECTSUITE_SAM_WORKGROUP_SUPERVISORS_MAP AS
(select
CAST(WORKGROUPID AS INT64) AS WORKGROUPID,
USERID,
"jobrunid" as JOB_RUN_ID,
'CONNECT SUITE' as SOURCE_SYSTEM_CD,
CURRENT_DATETIME() as CREATE_DT
from
LANDING.WORK_SAM_WORKGROUP_SUPERVISORS_MAP)