CREATE OR REPLACE TABLE REFERENCE.CONNECTSUITE_SAM_WORKGROUPS AS
(select
CAST(WORKGROUPID AS INT64) AS WORKGROUPID,
DESCRIPTION,
BUSINESSLINECODE,
LAST_USER_AUTO_ASSIGNED_OPP,
"jobrunid" as JOB_RUN_ID,
'CONNECT SUITE' as SOURCE_SYSTEM_CD,
CURRENT_DATETIME() as CREATE_DT
from
LANDING.WORK_SAM_WORKGROUPS)