CREATE OR REPLACE TABLE REFERENCE.CONNECTSUITE_CS_EMPLOYEES AS
(select
EMPLOYEE_ID,
FIRST_NAME,
LAST_NAME,
PASSWORD,
LOGIN_ENABLED,
ROLE_ID,
EMAIL_ADDRESS,
CLUB_CD,
BRANCH,
CAST(TRIM(INVALIDLOGINATTEMPTS) AS INT64) AS INVALIDLOGINATTEMPTS,
CAST(TRIM(PASSWORDCHANGEDDATE) AS DATETIME) AS PASSWORDCHANGEDDATE,
TMM_ROLE_ID,
CAST(PASSWORD_KEY_ID AS INT64) AS PASSWORD_KEY_ID,
PASSWORD_TYPE,
LAST_ADMIN_USER_ID,
CAST(TRIM(LAST_LOGIN_DT) AS DATETIME) AS LAST_LOGIN_DT,
"jobrunid" as JOB_RUN_ID,
'CONNECT SUITE' as SOURCE_SYSTEM_CD,
CURRENT_DATETIME() as CREATE_DT
from
LANDING.WORK_CS_EMPLOYEES)
