CREATE OR REPLACE TABLE REFERENCE.CONNECTSUITE_M_PAYMENT_TYPE AS
(select
CAST(PAY_TYPE_KY AS INT64) AS PAY_TYPE_KY,
PAY_METH_CD,
CAST(GLACT_KY AS INT64) AS GLACT_KY,
PAY_TYPE_CD,
PAY_TYPE_DESC,
INACT_IND,
CAST(PAY_TYPE_SORT_NR AS INT64) AS PAY_TYPE_SORT_NR,
NO_JE_IND,
"jobrunid" as JOB_RUN_ID,
'CONNECT SUITE' as SOURCE_SYSTEM_CD,
CURRENT_DATETIME() as CREATE_DT
from
LANDING.WORK_M_PAYMENT_TYPE)