CREATE OR REPLACE TABLE REFERENCE.CONNECTSUITE_M_BRANCH_CLUB AS
(select
CAST(BRN_KY AS INT64) AS BRN_KY,
CLUB_CD,
"jobrunid" as JOB_RUN_ID,
'CONNECT SUITE' as SOURCE_SYSTEM_CD,
CURRENT_DATETIME() as CREATE_DT
from
LANDING.WORK_M_BRANCH_CLUB)