CREATE OR REPLACE TABLE REFERENCE.CONNECTSUITE_CS_BRANCH AS
(select
CLUB_CD,
BRANCH,
NAME,
BRANCH_NUMBER,
BRANCH_DESCRIPTION,
BRANCH_ADDR1,
BRANCH_ADDR2,
BRANCH_CITY_NM,
BRANCH_STATE_CD,
BRANCH_ZIP,
BRANCH_COUNTRY_CD,
EMPLOYEE_ID,
CAST(TRIM(LAST_UPDATE) AS DATETIME) AS LAST_UPDATE,
CAST(BRN_KY AS INT64) AS BRN_KY,
BRANCH_PHONE,
"jobrunid" as JOB_RUN_ID,
'CONNECT SUITE' as SOURCE_SYSTEM_CD,
CURRENT_DATETIME() as CREATE_DT
from
LANDING.WORK_CS_BRANCH)