CREATE OR REPLACE TABLE REFERENCE.CONNECTSUITE_SAM_WORKGROUP_BRANCHES_MAP AS
(select
CAST(WORKGROUPID AS INT64) AS WORKGROUPID,
CLUB_CD,
BRANCH_CD,
"jobrunid" as JOB_RUN_ID,
'CONNECT SUITE' as SOURCE_SYSTEM_CD,
CURRENT_DATETIME() as CREATE_DT
from
LANDING.WORK_SAM_WORKGROUP_BRANCHES_MAP)