CREATE OR REPLACE TABLE REFERENCE.CONNECTSUITE_CS_BRANCHZIPS AS
(select
CLUB_CD,
BRANCH,
ZIP_CODE,
DISTANCE_FROM_BRANCH,
EMPLOYEE_ID,
CAST(TRIM(LAST_UPDATE) AS DATETIME) AS LAST_UPDATE,
"jobrunid" as JOB_RUN_ID,
'CONNECT SUITE' as SOURCE_SYSTEM_CD,
CURRENT_DATETIME() as CREATE_DT
from
LANDING.WORK_CS_BRANCHZIPS)