CREATE OR REPLACE TABLE REFERENCE.CONNECTSUITE_POS_CLB_OFC_SLS_TAX AS
(select
ASSOC_CD,
CLUB_CD,
OFC_ID,
CAST(CNTY_TAX_PCT AS FLOAT64) AS CNTY_TAX_PCT,
CNTY_TAX_DSC,
CAST(LCL_TAX_PCT AS FLOAT64) AS LCL_TAX_PCT,
LCL_TAX_DSC,
CAST(OTH_TAX_PCT AS FLOAT64) AS OTH_TAX_PCT,
OTH_TAX_DSC,
CAST(ST_TAX_PCT AS FLOAT64) AS ST_TAX_PCT,
ST_TAX_DSC,
TAX_GL,
"jobrunid" as JOB_RUN_ID,
'CONNECT SUITE' as SOURCE_SYSTEM_CD,
CURRENT_DATETIME() as CREATE_DT
from
LANDING.WORK_POS_CLB_OFC_SLS_TAX)