select
LTRIM(RTRIM( EMPLOYEE_ID)) AS EMPLOYEE_ID,
LTRIM(RTRIM( FIRST_NAME)) AS FIRST_NAME,
LTRIM(RTRIM( LAST_NAME)) AS LAST_NAME,
LTRIM(RTRIM( PASSWORD)) AS PASSWORD,
LTRIM(RTRIM( LOGIN_ENABLED)) AS LOGIN_ENABLED,
LTRIM(RTRIM( ROLE_ID)) AS ROLE_ID,
LTRIM(RTRIM( EMAIL_ADDRESS)) AS EMAIL_ADDRESS,
LTRIM(RTRIM( CLUB_CD)) AS CLUB_CD,
LTRIM(RTRIM( BRANCH)) AS BRANCH,
LTRIM(RTRIM(CONVERT(CHAR, INVALIDLOGINATTEMPTS) )) AS INVALIDLOGINATTEMPTS,
LTRIM(RTRIM(CONVERT(CHAR, PASSWORDCHANGEDDATE, 121))) AS PASSWORDCHANGEDDATE,
LTRIM(RTRIM( TMM_ROLE_ID)) AS TMM_ROLE_ID,
LTRIM(RTRIM(CONVERT(CHAR, PASSWORD_KEY_ID) )) AS PASSWORD_KEY_ID,
LTRIM(RTRIM( PASSWORD_TYPE)) AS PASSWORD_TYPE,
LTRIM(RTRIM( LAST_ADMIN_USER_ID)) AS LAST_ADMIN_USER_ID,
LTRIM(RTRIM(CONVERT(CHAR, LAST_LOGIN_DT, 121))) AS LAST_LOGIN_DT
from [connect_suite_prd].[dbo].[employees]