select
LTRIM(RTRIM(CONVERT(CHAR, WORKGROUPID) )) AS WORKGROUPID,
LTRIM(RTRIM( DESCRIPTION)) AS DESCRIPTION,
LTRIM(RTRIM( BUSINESSLINECODE)) AS BUSINESSLINECODE,
LTRIM(RTRIM( LAST_USER_AUTO_ASSIGNED_OPP)) AS LAST_USER_AUTO_ASSIGNED_OPP
FROM [mrm_sam_prd].[dbo].[workgroups]