SELECT LTRIM(RTRIM(CONVERT(CHAR, "START DATE", 121))) AS START_DATE,
LTRIM(RTRIM(CONVERT(CHAR, "END DATE", 121))) AS END_DATE,
LTRIM(RTRIM( BRANCH)) AS BRANCH,
LTRIM(RTRIM( ZIP)) AS ZIP,
LTRIM(RTRIM( STATE)) AS STATE
  FROM [connect_suite_prd].[dbo].[branch_zip_map]