SELECT 
LTRIM(RTRIM( CLUB_CD)) AS CLUB_CD,
LTRIM(RTRIM( BRANCH)) AS BRANCH,
LTRIM(RTRIM( NAME)) AS NAME,
LTRIM(RTRIM( BRANCH_NUMBER)) AS BRANCH_NUMBER,
LTRIM(RTRIM( BRANCH_DESCRIPTION)) AS BRANCH_DESCRIPTION,
LTRIM(RTRIM( BRANCH_ADDR1)) AS BRANCH_ADDR1,
LTRIM(RTRIM( BRANCH_ADDR2)) AS BRANCH_ADDR2,
LTRIM(RTRIM( BRANCH_CITY_NM)) AS BRANCH_CITY_NM,
LTRIM(RTRIM( BRANCH_STATE_CD)) AS BRANCH_STATE_CD,
LTRIM(RTRIM( BRANCH_ZIP)) AS BRANCH_ZIP,
LTRIM(RTRIM( BRANCH_COUNTRY_CD)) AS BRANCH_COUNTRY_CD,
LTRIM(RTRIM( EMPLOYEE_ID)) AS EMPLOYEE_ID,
LTRIM(RTRIM(CONVERT(CHAR, LAST_UPDATE, 121))) AS LAST_UPDATE,
LTRIM(RTRIM(CONVERT(CHAR, BRN_KY) )) AS BRN_KY,
LTRIM(RTRIM( BRANCH_PHONE)) AS BRANCH_PHONE
FROM [connect_suite_prd].[dbo].[branch]