select
LTRIM(RTRIM(CONVERT(CHAR, CLB_KY) )) AS CLB_KY,
LTRIM(RTRIM( CLB_CD)) AS CLB_CD,
LTRIM(RTRIM( CLB_NM)) AS CLB_NM,
LTRIM(RTRIM( CLB_BSC_AD)) AS CLB_BSC_AD,
LTRIM(RTRIM( CLB_SUPL_AD)) AS CLB_SUPL_AD,
LTRIM(RTRIM( CLB_CTY_NM)) AS CLB_CTY_NM,
LTRIM(RTRIM( CLB_ST_PROV_CD)) AS CLB_ST_PROV_CD,
LTRIM(RTRIM( CLB_ZIP_CD)) AS CLB_ZIP_CD,
LTRIM(RTRIM( CLB_MRCHT_NB)) AS CLB_MRCHT_NB,
LTRIM(RTRIM( CLB_GEN_MRCHT_NB)) AS CLB_GEN_MRCHT_NB,
LTRIM(RTRIM( CLB_TEL_NR)) AS CLB_TEL_NR,
LTRIM(RTRIM( CLB_ISO_NR)) AS CLB_ISO_NR,
LTRIM(RTRIM( CLB_RT_MRCHT_NB)) AS CLB_RT_MRCHT_NB,
LTRIM(RTRIM( CLB_OLJ_MRCHT_NB)) AS CLB_OLJ_MRCHT_NB
FROM [m_prd].[dbo].[club]