Select
LTRIM(RTRIM( CLUB_CD)) AS CLUB_CD,
LTRIM(RTRIM( BRANCH)) AS BRANCH,
LTRIM(RTRIM( ZIP_CODE)) AS ZIP_CODE,
LTRIM(RTRIM( DISTANCE_FROM_BRANCH)) AS DISTANCE_FROM_BRANCH,
LTRIM(RTRIM( EMPLOYEE_ID)) AS EMPLOYEE_ID,
LTRIM(RTRIM(CONVERT(CHAR, LAST_UPDATE, 121))) AS LAST_UPDATE
from [connect_suite_prd].[dbo].[branchzips]