CREATE OR REPLACE TABLE LANDING.SAM_QUOTE_LDG(
QUOTE_ID INT64,
OPPORTUNITY_ID INT64,
CUSTOMER_ID INT64,
SOURCE_CUSTOMER_ID STRING,
SOURCE_QUOTE_ID STRING,
POLICY_STATUS STRING,
PRODUCT_TYPE STRING,
PRODUCT_CD STRING,
POLICY_STATE STRING,
EFFECTIVE_DT DATETIME,
CREATE_DTTIME DATETIME,
PREMIUM FLOAT64,
POLICY_TERM_MONTHS INT64,
POLICY_NUM STRING,
SOURCE_SYSTEM STRING,
LAST_MODIFIED_DTTIME DATETIME,
POLICY_CARRIER STRING
)