  --Audit sql to be put here
SELECT
  FORMAT("%.*f",2,CAST(SUM(TOTAL_AMT_DUE) AS FLOAT64) + .0001) AS sum_of_amt_due
FROM
  LANDING.STAGE_MEMBERSHIP_BILL
  WHERE EVENT_TYPE='BILL3'
  AND cast(UPDATE_DTTIME as date)=CURRENT_DATE()
  --AND FILE_GENERATED='N'
  ;
