  --Audit sql to be put here
UPDATE LANDING.STAGE_MEMBERSHIP_BILL TGT SET EXCEPTION_FLAG='Y',FILE_GENERATED = 'E', 
EXCEPTION_REASON=case when EXCEPTION_REASON is null then 'Bill3 cannot be generated as Bill1/Bill2 was not generated' 
ELSE CONCAT(EXCEPTION_REASON,',','Bill3 cannot be generated as Bill1/Bill2 was not generated') END
WHERE EVENT_TYPE='BILL3' AND NOT EXISTS (SELECT 1 FROM LANDING.STAGE_MEMBERSHIP_BILL SRC WHERE SRC.EVENT_TYPE in ('BILL1','BILL2') 
AND TGT.MEMBER_NUM=SRC.MEMBER_NUM 
and CAST(SRC.CREATE_DTTIME AS DATE)>=DATE_SUB(CURRENT_DATE(), INTERVAL 70 DAY))