MERGE OPERATIONAL.HOUSE_MANAGER_REFUNDS AS TGT
USING (select * from LANDING.WORK_ZUORA_REFUNDS WHERE DATE(REFUND_UPDATED_DT) >= DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)) AS SRC
ON TGT.REFUND_NUM = SRC.REFUND_NUM and
 TGT.REFUND_ID = SRC.ID 
 WHEN MATCHED THEN UPDATE SET 
TGT.REFERENCE_ID = SRC.REFERENCE_ID
,TGT.ACCOUNTING_CD = SRC.ACCOUNTING_CD
,TGT.REFUND_DT = DATE(SRC.REFUND_DT)
,TGT.REFUND_TRANSACTION_TIME = SRC.REFUND_TRANSACTION_TIME
,TGT.REFUND_AMT = SAFE_CAST(SRC.AMOUNT AS FLOAT64)
,TGT.CANCELLED_DT = DATE(SRC.CANCELLED_DT)
,TGT.COMMENT = SRC.COMMENT
,TGT.GATEWAY = SRC.GATEWAY
,TGT.GATEWAY_RESPONSE = SRC.GATEWAY_RESPONSE
,TGT.GATEWAY_RESPONSE_CD = SRC.GATEWAY_RESPONSE_CD
,TGT.GATEWAY_STATE = SRC.GATEWAY_STATE
,TGT.MARKED_FOR_SUBMISSION_ON = SRC.MARKED_FOR_SUBMISSION_ON
,TGT.SECOND_REFUND_REFERENCE_ID = SRC.SECOND_REFUND_REFERENCE_ID
,TGT.SETTLED_ON_DTTIME = SRC.SETTLED_ON
,TGT.SOFT_DESCRIPTOR = SRC.SOFT_DESCRIPTOR
,TGT.SOFT_DESCRIPTOR_PHONE_NUM = SRC.SOFT_DESCRIPTOR_PHONE_NUM
,TGT.SOURCE_TYPE = SRC.SOURCE_TYPE
,TGT.STATUS = SRC.STATUS
,TGT.SUBMITTED_ON_DTTIME = SRC.SUBMITTED_ON
,TGT.TRANSFERRED_TO_ACCOUNTING = SRC.TRANSFERRED_TO_ACCOUNTING
,TGT.PAYMENT_METHOD_ID = SRC.PAYMENT_METHOD_ID
,TGT.METHOD_TYPE = SRC.METHOD_TYPE
,TGT.REASON_CD = SRC.REASON_CD
,TGT.TYPE = SRC.TYPE
,TGT.CREDIT_CARD_TYPE = SRC.CREDIT_CARD_TYPE
,TGT.CREATED_BY_ID = SRC.CREATED_BY_ID
,TGT.SOURCE_CREATED_DTTIME = SRC.CREATED_DT
,TGT.REFUND_UPDATED_BY_ID = SRC.REFUND_UPDATED_BY_ID
,TGT.SOURCE_REFUND_UPDATED_DTTIME = SRC.REFUND_UPDATED_DT
,TGT.UPDATE_DTTIME =  CURRENT_DATETIME()
WHEN NOT MATCHED THEN INSERT 
(REFUND_ID
,REFUND_NUM
,REFERENCE_ID
,ACCOUNTING_CD
,REFUND_DT
,REFUND_TRANSACTION_TIME
,REFUND_AMT
,CANCELLED_DT
,COMMENT
,GATEWAY
,GATEWAY_RESPONSE
,GATEWAY_RESPONSE_CD
,GATEWAY_STATE
,MARKED_FOR_SUBMISSION_ON
,SECOND_REFUND_REFERENCE_ID
,SETTLED_ON_DTTIME
,SOFT_DESCRIPTOR
,SOFT_DESCRIPTOR_PHONE_NUM
,SOURCE_TYPE
,STATUS
,SUBMITTED_ON_DTTIME
,TRANSFERRED_TO_ACCOUNTING
,PAYMENT_METHOD_ID
,METHOD_TYPE
,REASON_CD
,TYPE
,CREDIT_CARD_TYPE
,CREATED_BY_ID
,SOURCE_CREATED_DTTIME
,REFUND_UPDATED_BY_ID
,SOURCE_REFUND_UPDATED_DTTIME
,SOURCE_SYSTEM_CD
,CREATE_DTTIME
,UPDATE_DTTIME)
VALUES(
ID 
,REFUND_NUM
,REFERENCE_ID
,ACCOUNTING_CD
,DATE(REFUND_DT)
,REFUND_TRANSACTION_TIME
,SAFE_CAST(AMOUNT AS FLOAT64) 
,DATE(CANCELLED_DT)
,COMMENT
,GATEWAY
,GATEWAY_RESPONSE
,GATEWAY_RESPONSE_CD
,GATEWAY_STATE
,MARKED_FOR_SUBMISSION_ON
,SECOND_REFUND_REFERENCE_ID
,SETTLED_ON
,SOFT_DESCRIPTOR
,SOFT_DESCRIPTOR_PHONE_NUM
,SOURCE_TYPE
,STATUS
,SUBMITTED_ON
,TRANSFERRED_TO_ACCOUNTING
,PAYMENT_METHOD_ID
,METHOD_TYPE
,REASON_CD
,TYPE
,CREDIT_CARD_TYPE
,CREATED_BY_ID
,CREATED_DT
,REFUND_UPDATED_BY_ID
,REFUND_UPDATED_DT
,'HOUSE_MANAGER'
,CURRENT_DATETIME()
,CURRENT_DATETIME())
