SELECT
PAYMENT_AMT as AMOUNT, APPLIED_AMT, APPLIED_CREDIT_BALANCE_AMT, CANCELLED_DT, CURRENCY, EFFECTIVE_DT, GATEWAY, GATEWAY_RESPONSE, GATEWAY_STATE,
PAYMENT_NUM, REFERENCE_ID, REFUND_AMT, SOURCE, SOURCE_NM, STATUS, SUBMITTED_ON_DTTIME as SUBMITTED_ON, UNAPPLIED_AMT, CREDIT_CARD_TYPE, PAYMENT_TYPE
FROM OPERATIONAL.HOUSE_MANAGER_PAYMENTS
WHERE DATE(UPDATE_DTTIME) >= CURRENT_DATE()
