SELECT
REFUND_AMT as AMOUNT, CANCELLED_DT, GATEWAY, GATEWAY_RESPONSE, GATEWAY_STATE, REFERENCE_ID, REFUND_DT, REFUND_NUM, SECOND_REFUND_REFERENCE_ID, SOURCE_TYPE, STATUS, SUBMITTED_ON_DTTIME as SUBMITTED_ON, TYPE, CREDIT_CARD_TYPE
FROM OPERATIONAL.HOUSE_MANAGER_REFUNDS
WHERE DATE(UPDATE_DTTIME) >= CURRENT_DATE()
