SELECT
TO_CHAR(translate(TD_ID,chr(10)||chr(11)||chr(13),' ')) as TD_ID,
TO_CHAR(translate(TD_NAME,chr(10)||chr(11)||chr(13),' ')) as TD_NAME,
TO_CHAR(translate(TD_ADDRESS,chr(10)||chr(11)||chr(13),' ')) as TD_ADDRESS,
TO_CHAR(translate(TD_PHONE_NR,chr(10)||chr(11)||chr(13),' ')) as TD_PHONE_NR,
TO_CHAR(translate(TD_PHONE_EXT,chr(10)||chr(11)||chr(13),' ')) as TD_PHONE_EXT,
TO_CHAR(translate(TD_PHONE_TYPE,chr(10)||chr(11)||chr(13),' ')) as TD_PHONE_TYPE,
TO_CHAR(translate(TD_CITY,chr(10)||chr(11)||chr(13),' ')) as TD_CITY,
TO_CHAR(translate(TD_STATE,chr(10)||chr(11)||chr(13),' ')) as TD_STATE,
TO_CHAR(translate(TD_ZIP,chr(10)||chr(11)||chr(13),' ')) as TD_ZIP,
TO_CHAR(translate(TD_CONTACT,chr(10)||chr(11)||chr(13),' ')) as TD_CONTACT,
TO_CHAR(translate(TD_LATITUDE,chr(10)||chr(11)||chr(13),' ')) as TD_LATITUDE,
TO_CHAR(translate(TD_LONGITUDE,chr(10)||chr(11)||chr(13),' ')) as TD_LONGITUDE,
TO_CHAR(translate(TD_USE_DEFAULT_TM,chr(10)||chr(11)||chr(13),' ')) as TD_USE_DEFAULT_TM,
TO_CHAR(translate(TD_AAA_APPROVED,chr(10)||chr(11)||chr(13),' ')) as TD_AAA_APPROVED,
TO_CHAR(translate(TD_DEALER_INDIC,chr(10)||chr(11)||chr(13),' ')) as TD_DEALER_INDIC,
TO_CHAR(translate(TD_SHOW_CARD_SAVE,chr(10)||chr(11)||chr(13),' ')) as TD_SHOW_CARD_SAVE,
TO_CHAR(translate(TD_GRID,chr(10)||chr(11)||chr(13),' ')) as TD_GRID,
TO_CHAR(translate(TD_CLB_CD,chr(10)||chr(11)||chr(13),' ')) as TD_CLB_CD,
TO_CHAR(translate(TD_SECURE_LOT,chr(10)||chr(11)||chr(13),' ')) as TD_SECURE_LOT,
TO_CHAR(translate(TD_DROP_BOX_LOC,chr(10)||chr(11)||chr(13),' ')) as TD_DROP_BOX_LOC,
TO_CHAR(translate(TD_EXT_DEALER_ID,chr(10)||chr(11)||chr(13),' ')) as TD_EXT_DEALER_ID,
TO_CHAR(translate(TD_FAX_PHONE,chr(10)||chr(11)||chr(13),' ')) as TD_FAX_PHONE,
TO_CHAR(translate(MOBILE_TECH,chr(10)||chr(11)||chr(13),' ')) as MOBILE_TECH,
TO_CHAR(translate(TD_DEST_TYPE,chr(10)||chr(11)||chr(13),' ')) as TD_DEST_TYPE,
TO_CHAR(LAST_UPDATE,'YYYY-MM-DD') as LAST_UPDATE ,
TO_CHAR(translate(TD_SPP_FLAG,chr(10)||chr(11)||chr(13),' ')) as TD_SPP_FLAG,
TO_CHAR(translate(TD_AAR_TOW_DEST_ID,chr(10)||chr(11)||chr(13),' ')) as TD_AAR_TOW_DEST_ID,
TO_CHAR(translate(TD_AAA_DOLLARS,chr(10)||chr(11)||chr(13),' ')) as TD_AAA_DOLLARS,
'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM NCA_CADTRAIN.TOW_DEST_LIST
WHERE LAST_UPDATE  >=  TO_DATE('incrdate_tow_dest_list','yyyy-mm-dd hh24:mi:ss')