SELECT
TO_CHAR(SC_DT,'YYYY-MM-DD HH24:MI:SS') as SC_DT ,
TO_CHAR(translate(SC_ID,chr(10)||chr(11)||chr(13),' ')) as SC_ID,
TO_CHAR(translate(SC_VEH_SEQ_ID,chr(10)||chr(11)||chr(13),' ')) as SC_VEH_SEQ_ID,
TO_CHAR(translate(SC_VEH_LIC_ST_CD,chr(10)||chr(11)||chr(13),' ')) as SC_VEH_LIC_ST_CD,
TO_CHAR(translate(SC_VEH_COLR_NM,chr(10)||chr(11)||chr(13),' ')) as SC_VEH_COLR_NM,
TO_CHAR(translate(SC_VEH_LIC_TAG_NR,chr(10)||chr(11)||chr(13),' ')) as SC_VEH_LIC_TAG_NR,
TO_CHAR(translate(SC_VEH_MANF_YR_DT,chr(10)||chr(11)||chr(13),' ')) as SC_VEH_MANF_YR_DT,
TO_CHAR(translate(SC_VEH_MANFR_NM,chr(10)||chr(11)||chr(13),' ')) as SC_VEH_MANFR_NM,
TO_CHAR(translate(SC_VEH_MDL_NM,chr(10)||chr(11)||chr(13),' ')) as SC_VEH_MDL_NM,
TO_CHAR(LAST_UPDATE,'YYYY-MM-DD') as LAST_UPDATE ,
TO_CHAR(translate(SC_VEH_UNSN_CHNG,chr(10)||chr(11)||chr(13),' ')) as SC_VEH_UNSN_CHNG,
TO_CHAR(translate(EMPLE_ID,chr(10)||chr(11)||chr(13),' ')) as EMPLE_ID,
TO_CHAR(translate(FLATBED_INDIC,chr(10)||chr(11)||chr(13),' ')) as FLATBED_INDIC,
TO_CHAR(translate(FOUR_WHEEL_DRIVE,chr(10)||chr(11)||chr(13),' ')) as FOUR_WHEEL_DRIVE,
TO_CHAR(translate(REC_VEHICLE,chr(10)||chr(11)||chr(13),' ')) as REC_VEHICLE,
TO_CHAR(translate(AWD_VEHICLE,chr(10)||chr(11)||chr(13),' ')) as AWD_VEHICLE,
TO_CHAR(translate(MCYCLE_INDIC,chr(10)||chr(11)||chr(13),' ')) as MCYCLE_INDIC,
TO_CHAR(translate(VEHICLE_ID,chr(10)||chr(11)||chr(13),' ')) as VEHICLE_ID,
TO_CHAR(translate(BASE_VEHICLE_ID,chr(10)||chr(11)||chr(13),' ')) as BASE_VEHICLE_ID,
TO_CHAR(translate(VEH_TYPE,chr(10)||chr(11)||chr(13),' ')) as VEH_TYPE,
TO_CHAR(translate(SC_VEH_TRM,chr(10)||chr(11)||chr(13),' ')) as SC_VEH_TRM,
TO_CHAR(translate(TWO_WHEEL_DRIVE,chr(10)||chr(11)||chr(13),' ')) as TWO_WHEEL_DRIVE,
TO_CHAR(translate(DOLLY_INDIC,chr(10)||chr(11)||chr(13),' ')) as DOLLY_INDIC,
TO_CHAR(translate(LOCKSMITH_INDIC,chr(10)||chr(11)||chr(13),' ')) as LOCKSMITH_INDIC,
TO_CHAR(translate(WHEEL_LIFT_REQ_INDIC,chr(10)||chr(11)||chr(13),' ')) as WHEEL_LIFT_REQ_INDIC,
TO_CHAR(translate(WHEEL_LIFT_INDIC,chr(10)||chr(11)||chr(13),' ')) as WHEEL_LIFT_INDIC,
TO_CHAR(translate(MC_TYPE,chr(10)||chr(11)||chr(13),' ')) as MC_TYPE,
TO_CHAR(translate(MC_ENG_TYPE,chr(10)||chr(11)||chr(13),' ')) as MC_ENG_TYPE,
TO_CHAR(translate(MC_COMMENT,chr(10)||chr(11)||chr(13),' ')) as MC_COMMENT,
TO_CHAR(translate(MC_PULLING_TRL,chr(10)||chr(11)||chr(13),' ')) as MC_PULLING_TRL,
TO_CHAR(translate(MC_LAID_DOWN,chr(10)||chr(11)||chr(13),' ')) as MC_LAID_DOWN,
TO_CHAR(translate(MC_WHEELS_ROLL,chr(10)||chr(11)||chr(13),' ')) as MC_WHEELS_ROLL,
TO_CHAR(translate(RV_LENGTH,chr(10)||chr(11)||chr(13),' ')) as RV_LENGTH,
TO_CHAR(translate(RV_HEIGHT,chr(10)||chr(11)||chr(13),' ')) as RV_HEIGHT,
TO_CHAR(translate(RV_GOOSENECK,chr(10)||chr(11)||chr(13),' ')) as RV_GOOSENECK,
TO_CHAR(translate(RV_ENG_LOC,chr(10)||chr(11)||chr(13),' ')) as RV_ENG_LOC,
TO_CHAR(translate(RV_TOWING,chr(10)||chr(11)||chr(13),' ')) as RV_TOWING,
TO_CHAR(translate(RV_TYPE_TOWING,chr(10)||chr(11)||chr(13),' ')) as RV_TYPE_TOWING,
TO_CHAR(translate(FLAT_LOCATION,chr(10)||chr(11)||chr(13),' ')) as FLAT_LOCATION,
TO_CHAR(translate(TRL_INDIC,chr(10)||chr(11)||chr(13),' ')) as TRL_INDIC,
TO_CHAR(translate(TRL_TYPE,chr(10)||chr(11)||chr(13),' ')) as TRL_TYPE,
TO_CHAR(translate(TRL_LENGTH,chr(10)||chr(11)||chr(13),' ')) as TRL_LENGTH,
TO_CHAR(translate(TRL_NO_AXLES,chr(10)||chr(11)||chr(13),' ')) as TRL_NO_AXLES,
TO_CHAR(translate(TRL_CONDITION,chr(10)||chr(11)||chr(13),' ')) as TRL_CONDITION,
TO_CHAR(translate(TRL_PLUG_TYPE,chr(10)||chr(11)||chr(13),' ')) as TRL_PLUG_TYPE,
TO_CHAR(translate(TRL_HITCH_TYPE,chr(10)||chr(11)||chr(13),' ')) as TRL_HITCH_TYPE,
TO_CHAR(translate(TRL_HITCH_SIZE,chr(10)||chr(11)||chr(13),' ')) as TRL_HITCH_SIZE,
TO_CHAR(translate(TRL_GOOSENECK,chr(10)||chr(11)||chr(13),' ')) as TRL_GOOSENECK,
TO_CHAR(translate(TRL_LOADED,chr(10)||chr(11)||chr(13),' ')) as TRL_LOADED,
TO_CHAR(translate(TRL_LOAD_TYPE,chr(10)||chr(11)||chr(13),' ')) as TRL_LOAD_TYPE,
TO_CHAR(translate(TRL_LOAD_WEIGHT,chr(10)||chr(11)||chr(13),' ')) as TRL_LOAD_WEIGHT,
TO_CHAR(translate(HYBRID_VEHICLE,chr(10)||chr(11)||chr(13),' ')) as HYBRID_VEHICLE,
TO_CHAR(translate(ELECTRIC_VEHICLE,chr(10)||chr(11)||chr(13),' ')) as ELECTRIC_VEHICLE,
TO_CHAR(translate(IS_DIESEL,chr(10)||chr(11)||chr(13),' ')) as IS_DIESEL,
TO_CHAR(translate(AIR_SUSPENSION,chr(10)||chr(11)||chr(13),' ')) as AIR_SUSPENSION,
TO_CHAR(translate(SC_VEH_NOTES,chr(10)||chr(11)||chr(13),' ')) as SC_VEH_NOTES,
TO_CHAR(translate(RV_WEIGHT,chr(10)||chr(11)||chr(13),' ')) as RV_WEIGHT,
TO_CHAR(translate(SC_VEH_ODOMETER,chr(10)||chr(11)||chr(13),' ')) as SC_VEH_ODOMETER,
TO_CHAR(translate(SC_VEH_VIN,chr(10)||chr(11)||chr(13),' ')) as SC_VEH_VIN,
TO_CHAR(translate(IS_ONLINE_GARAGE,chr(10)||chr(11)||chr(13),' ')) as IS_ONLINE_GARAGE,
TO_CHAR(translate(PREFERRED_SHOP_ID,chr(10)||chr(11)||chr(13),' ')) as PREFERRED_SHOP_ID,
TO_CHAR(translate(LAST_USED_SHOP_ID,chr(10)||chr(11)||chr(13),' ')) as LAST_USED_SHOP_ID,
'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM NCA_CAD.SVC_VEHICLE
WHERE LAST_UPDATE  >=  TO_DATE('incr_date_svc_vehicle','yyyy-mm-dd')