SELECT
TO_CHAR(translate(COMM_CTR_ID,chr(10)||chr(11)||chr(13),' ')) as COMM_CTR_ID,
TO_CHAR(SC_DT,'YYYY-MM-DD') as SC_DT ,
TO_CHAR(translate(SC_ID,chr(10)||chr(11)||chr(13),' ')) as SC_ID,
TO_CHAR(translate(FAC_NAME,chr(10)||chr(11)||chr(13),' ')) as FAC_NAME,
TO_CHAR(translate(AAA_CALL,chr(10)||chr(11)||chr(13),' ')) as AAA_CALL,
TO_CHAR(translate(REASON_CODE,chr(10)||chr(11)||chr(13),' ')) as REASON_CODE,
TO_CHAR(translate(TOTAL_REQUEST,chr(10)||chr(11)||chr(13),' ')) as TOTAL_REQUEST,
TO_CHAR(RECEIVED_DATE,'YYYY-MM-DD') as RECEIVED_DATE ,
TO_CHAR(FOLLOWUP_DATE,'YYYY-MM-DD') as FOLLOWUP_DATE ,
TO_CHAR(REPLY_DATE,'YYYY-MM-DD') as REPLY_DATE ,
TO_CHAR(APPROVED_DATE,'YYYY-MM-DD') as APPROVED_DATE ,
TO_CHAR(translate(APPROVAL_ID,chr(10)||chr(11)||chr(13),' ')) as APPROVAL_ID,
TO_CHAR(translate(CHECK_STUB_CD,chr(10)||chr(11)||chr(13),' ')) as CHECK_STUB_CD,
TO_CHAR(PAY_DATE,'YYYY-MM-DD') as PAY_DATE ,
TO_CHAR(translate(PAY_ID,chr(10)||chr(11)||chr(13),' ')) as PAY_ID,
TO_CHAR(translate(COMMENTX,chr(10)||chr(11)||chr(13),' ')) as COMMENTX,
TO_CHAR(translate(ADDR_CHG_IND,chr(10)||chr(11)||chr(13),' ')) as ADDR_CHG_IND,
TO_CHAR(translate(DIST_CODE,chr(10)||chr(11)||chr(13),' ')) as DIST_CODE,
TO_CHAR(translate(BSC_AD,chr(10)||chr(11)||chr(13),' ')) as BSC_AD,
TO_CHAR(translate(SUPL_AD,chr(10)||chr(11)||chr(13),' ')) as SUPL_AD,
TO_CHAR(translate(CTY_NM,chr(10)||chr(11)||chr(13),' ')) as CTY_NM,
TO_CHAR(translate(ST_CD,chr(10)||chr(11)||chr(13),' ')) as ST_CD,
TO_CHAR(translate(ZIP_CD,chr(10)||chr(11)||chr(13),' ')) as ZIP_CD,
TO_CHAR(translate(REIMB_INT_ID,chr(10)||chr(11)||chr(13),' ')) as REIMB_INT_ID,
TO_CHAR(translate(CASH_REMB,chr(10)||chr(11)||chr(13),' ')) as CASH_REMB,
TO_CHAR(translate(PAYEE_NAME,chr(10)||chr(11)||chr(13),' ')) as PAYEE_NAME,
TO_CHAR(translate(PAYEE_STREET1,chr(10)||chr(11)||chr(13),' ')) as PAYEE_STREET1,
TO_CHAR(translate(PAYEE_STREET2,chr(10)||chr(11)||chr(13),' ')) as PAYEE_STREET2,
TO_CHAR(translate(PAYEE_CITY,chr(10)||chr(11)||chr(13),' ')) as PAYEE_CITY,
TO_CHAR(translate(PAYEE_STATE,chr(10)||chr(11)||chr(13),' ')) as PAYEE_STATE,
TO_CHAR(translate(PAYEE_ZIP,chr(10)||chr(11)||chr(13),' ')) as PAYEE_ZIP,
TO_CHAR(translate(SPECIAL_ENTITLEMENT_REQ,chr(10)||chr(11)||chr(13),' ')) as SPECIAL_ENTITLEMENT_REQ,
'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM NCA_APD.REIMBURSEMENT 
WHERE (RECEIVED_DATE >= TO_DATE('incr_date_reim','yyyy-mm-dd hh24:mi:ss') OR FOLLOWUP_DATE >= TO_DATE('incr_date_reim','yyyy-mm-dd hh24:mi:ss') OR APPROVED_DATE >= TO_DATE('incr_date_reim','yyyy-mm-dd hh24:mi:ss') OR PAY_DATE >= TO_DATE('incr_date_reim','yyyy-mm-dd hh24:mi:ss'))