SELECT
TO_CHAR(translate(FACIL_INT_ID,chr(10)||chr(11)||chr(13),' ')) as FACIL_INT_ID,
TO_CHAR(translate(SCADJ_ID,chr(10)||chr(11)||chr(13),' ')) as SCADJ_ID,
TO_CHAR(translate(SCADJ_ACCT,chr(10)||chr(11)||chr(13),' ')) as SCADJ_ACCT,
TO_CHAR(translate(SCADJ_TYPE,chr(10)||chr(11)||chr(13),' ')) as SCADJ_TYPE,
TO_CHAR(translate(SCADJ_REASON,chr(10)||chr(11)||chr(13),' ')) as SCADJ_REASON,
TO_CHAR(translate(SCADJ_NUM_TOTAL,chr(10)||chr(11)||chr(13),' ')) as SCADJ_NUM_TOTAL,
TO_CHAR(translate(SCADJ_NUM_TODATE,chr(10)||chr(11)||chr(13),' ')) as SCADJ_NUM_TODATE,
TO_CHAR(translate(SCADJ_DESC,chr(10)||chr(11)||chr(13),' ')) as SCADJ_DESC,
TO_CHAR(translate(SCADJ_CURRENT_PMNT,chr(10)||chr(11)||chr(13),' ')) as SCADJ_CURRENT_PMNT,
TO_CHAR(translate(SCADJ_LAST_PYMNT,chr(10)||chr(11)||chr(13),' ')) as SCADJ_LAST_PYMNT,
TO_CHAR(translate(SCADJ_AMOUNT,chr(10)||chr(11)||chr(13),' ')) as SCADJ_AMOUNT,
TO_CHAR(translate(SCADJ_SKIP_TODATE,chr(10)||chr(11)||chr(13),' ')) as SCADJ_SKIP_TODATE,
TO_CHAR(translate(SCADJ_SKIP_TOTAL,chr(10)||chr(11)||chr(13),' ')) as SCADJ_SKIP_TOTAL,
TO_CHAR(translate(SCADJ_SKIP_FLAG,chr(10)||chr(11)||chr(13),' ')) as SCADJ_SKIP_FLAG,
TO_CHAR(translate(SCADJ_TOTAL,chr(10)||chr(11)||chr(13),' ')) as SCADJ_TOTAL,
TO_CHAR(translate(SCADJ_TODATE,chr(10)||chr(11)||chr(13),' ')) as SCADJ_TODATE,
TO_CHAR(translate(SCADJ_1099,chr(10)||chr(11)||chr(13),' ')) as SCADJ_1099,
TO_CHAR(translate(SCADJ_INF_REOCCUR,chr(10)||chr(11)||chr(13),' ')) as SCADJ_INF_REOCCUR,
TO_CHAR(translate(SCADJ_PAYID,chr(10)||chr(11)||chr(13),' ')) as SCADJ_PAYID,
TO_CHAR(SCADJ_START,'YYYY-MM-DD') as SCADJ_START ,
TO_CHAR(SCADJ_END,'YYYY-MM-DD') as SCADJ_END ,
TO_CHAR(translate(SCADJ_ACTIVE,chr(10)||chr(11)||chr(13),' ')) as SCADJ_ACTIVE,
TO_CHAR(translate(SCADJ_PROC_FLAG,chr(10)||chr(11)||chr(13),' ')) as SCADJ_PROC_FLAG,
TO_CHAR(translate(SCADJ_CALL_QTY,chr(10)||chr(11)||chr(13),' ')) as SCADJ_CALL_QTY,
'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD
FROM NCA_APD.SVC_FAC_ADJ_ITEM