SELECT
TO_CHAR(translate(ADJ_SEQ_ID,chr(10)||chr(11)||chr(13),' ')) as ADJ_SEQ_ID,
TO_CHAR(translate(COMM_CTR_ID,chr(10)||chr(11)||chr(13),' ')) as COMM_CTR_ID,
TO_CHAR(SC_DT,'YYYY-MM-DD') as SC_DT ,
TO_CHAR(translate(SC_ID,chr(10)||chr(11)||chr(13),' ')) as SC_ID,
TO_CHAR(translate(DEL_FLAG,chr(10)||chr(11)||chr(13),' ')) as DEL_FLAG,
TO_CHAR(translate(ACCT_TYPE,chr(10)||chr(11)||chr(13),' ')) as ACCT_TYPE,
TO_CHAR(translate(EMPLE_ID,chr(10)||chr(11)||chr(13),' ')) as EMPLE_ID,
TO_CHAR(translate(PAY_ID,chr(10)||chr(11)||chr(13),' ')) as PAY_ID,
TO_CHAR(translate(FACIL_INT_ID,chr(10)||chr(11)||chr(13),' ')) as FACIL_INT_ID,
TO_CHAR(ADJ_RECORD_DATE,'YYYY-MM-DD') as ADJ_RECORD_DATE ,
TO_CHAR(translate(PAY_FACIL,chr(10)||chr(11)||chr(13),' ')) as PAY_FACIL,
TO_CHAR(translate(PAY_RECIP,chr(10)||chr(11)||chr(13),' ')) as PAY_RECIP,
TO_CHAR(translate(PAY_1099,chr(10)||chr(11)||chr(13),' ')) as PAY_1099,
TO_CHAR(translate(CHARGE_ENTL,chr(10)||chr(11)||chr(13),' ')) as CHARGE_ENTL,
TO_CHAR(RECIP_PAY_DATE,'YYYY-MM-DD') as RECIP_PAY_DATE ,
TO_CHAR(translate(ADJ_DESCRIPTION,chr(10)||chr(11)||chr(13),' ')) as ADJ_DESCRIPTION,
TO_CHAR(translate(ADJ_SVCP_CD,chr(10)||chr(11)||chr(13),' ')) as ADJ_SVCP_CD,
TO_CHAR(translate(ADJ_UNITS,chr(10)||chr(11)||chr(13),' ')) as ADJ_UNITS,
TO_CHAR(translate(ADJ_UNIT_COST,chr(10)||chr(11)||chr(13),' ')) as ADJ_UNIT_COST,
TO_CHAR(translate(ADJ_UOM_CD,chr(10)||chr(11)||chr(13),' ')) as ADJ_UOM_CD,
TO_CHAR(translate(ADJ_ADD_CHRG,chr(10)||chr(11)||chr(13),' ')) as ADJ_ADD_CHRG,
TO_CHAR(translate(ADJ_BASIC_COST,chr(10)||chr(11)||chr(13),' ')) as ADJ_BASIC_COST,
TO_CHAR(translate(ADJ_OTHER_COST,chr(10)||chr(11)||chr(13),' ')) as ADJ_OTHER_COST,
TO_CHAR(translate(ADJ_PLUS_COST,chr(10)||chr(11)||chr(13),' ')) as ADJ_PLUS_COST,
TO_CHAR(translate(ADJ_PLUSRV_COST,chr(10)||chr(11)||chr(13),' ')) as ADJ_PLUSRV_COST,
TO_CHAR(translate(ADJ_TOT_COST,chr(10)||chr(11)||chr(13),' ')) as ADJ_TOT_COST,
TO_CHAR(translate(ADJ_DISP_APP,chr(10)||chr(11)||chr(13),' ')) as ADJ_DISP_APP,
TO_CHAR(translate(ADJ_DISP_PRICE,chr(10)||chr(11)||chr(13),' ')) as ADJ_DISP_PRICE,
TO_CHAR(translate(ADJ_TIER_STATUS,chr(10)||chr(11)||chr(13),' ')) as ADJ_TIER_STATUS,
TO_CHAR(translate(ADJ_RATEC_CD,chr(10)||chr(11)||chr(13),' ')) as ADJ_RATEC_CD,
TO_CHAR(translate(ADJ_TOD_CD,chr(10)||chr(11)||chr(13),' ')) as ADJ_TOD_CD,
TO_CHAR(translate(SC_PROB_CD,chr(10)||chr(11)||chr(13),' ')) as SC_PROB_CD,
TO_CHAR(translate(EXCEPT_FLAG,chr(10)||chr(11)||chr(13),' ')) as EXCEPT_FLAG,
TO_CHAR(translate(ADJ_TAX1,chr(10)||chr(11)||chr(13),' ')) as ADJ_TAX1,
TO_CHAR(translate(ADJ_TAX2,chr(10)||chr(11)||chr(13),' ')) as ADJ_TAX2,
TO_CHAR(translate(ADJ_ACCT_DT,chr(10)||chr(11)||chr(13),' ')) as ADJ_ACCT_DT,
TO_CHAR(translate(FEED_PROCESSED,chr(10)||chr(11)||chr(13),' ')) as FEED_PROCESSED,
TO_CHAR(translate(ADJ_PREM_COST,chr(10)||chr(11)||chr(13),' ')) as ADJ_PREM_COST,
TO_CHAR(translate(ADJ_PRRV_COST,chr(10)||chr(11)||chr(13),' ')) as ADJ_PRRV_COST,
'jobrunid' AS JOB_RUN_ID,
'jobname' AS CREATED_BY,
'ers' AS SOURCE_SYSTEM_CD	
FROM NCA_ERS_HIST.CALL_ADJ CALL 
WHERE ADJ_RECORD_DATE  >=  TO_DATE('incr_date_adj','yyyy-mm-dd hh24:mi:ss')