CREATE OR REPLACE TABLE  `aaa-mwg-dwprod.REFERENCE.ERS_SERVICE_FACILTY_GRID`AS
SELECT 
G.ID AS GRID_ID, 
TRIM(GA.FACILITY_ID) AS SC_FACILITY_ID, 
TRIM(GRID_NM) AS GRID_NAME, 
GRID_GROUP_ID AS GRID_GROUP_ID, 
G.GEOMETRY AS GEOMETRY,
TRIM(COLOR) as COLOR,
TRIM(GA.SPOT_TYPE) AS SPOT_TYPE,
CAST(TRIM(GA.BACKUP_LEVEL) AS INT64) AS BACKUP_LEVEL, 
TRIM(GA.CALL_PERCENTAGE) AS CALL_PERCENTAGE, 
TRIM(TO_DELETE) as TO_DELETE,
CAST(LAST_MODIFIED AS DATETIME) as LAST_MODIFIED_DTTIME
FROM `aaa-mwg-dwprod.LANDING.WORK_ERS_GRID_ASSIGNMENTS` GA
LEFT OUTER JOIN `aaa-mwg-dwprod.OPERATIONAL.ERS_STAGE_SPOT_GRID` G ON G.ID = SAFE_CAST(GA.GRID_ID AS INT64)
WHERE GA.FACILITY_ID IS NOT NULL