-- UPDATE(MERGE)

--MERGE <target_table> [AS TARGET]
--USING <table_source> [AS SOURCE]
--ON <search_condition>
--[WHEN MATCHED 
--THEN <merge_matched> ]
--[WHEN NOT MATCHED [BY TARGET]
--THEN <merge_not_matched> ]
--[WHEN NOT MATCHED BY SOURCE
--THEN <merge_matched> ];
  
--ERS_STAGE_CAD_TOW_DEST
--WORK_ERS_STG_CAD_TOW_DEST
MERGE OPERATIONAL.ERS_STAGE_CAD_TOW_DEST AS TGT
USING LANDING.WORK_ERS_STG_CAD_TOW_DEST AS SRC
ON CAST(TGT.TOW_DEST_SEQ_ID AS STRING) = SRC.TOW_DEST_SEQ_ID and
TGT.SC_DT = CAST(SRC.SC_DT AS DATETIME) and
CAST(TGT.SC_ID AS STRING) = SRC.SC_ID
WHEN MATCHED
THEN UPDATE SET
TGT.TOW_DEST_SEQ_ID = CAST(SRC.TOW_DEST_SEQ_ID AS INT64) , 
TGT.SC_DT = CAST(SRC.SC_DT AS DATETIME) , 
TGT.SC_ID = CAST(SRC.SC_ID AS INT64), 
TGT.TOW_DST_UPRS_TX = SRC.TOW_DST_UPRS_TX, 
TGT.LAST_UPDATE =  CAST(SRC.LAST_UPDATE AS DATE),
TGT.TOW_UNSEEN_CHNG = SRC.TOW_UNSEEN_CHNG,
TGT.EMPLE_ID = SRC.EMPLE_ID,
TGT.TOW_DEST_LATITUDE = CAST(SRC.TOW_DEST_LATITUDE AS FLOAT64),
TGT.TOW_DEST_LONGITUDE = CAST(SRC.TOW_DEST_LONGITUDE AS FLOAT64),
TGT.TOW_DEST_ID = CAST(SRC.TOW_DEST_ID AS INT64),
TGT.TOW_DEST_GRID = SRC.TOW_DEST_GRID,
TGT.TD_VERIFIED_LOC = SRC.TD_VERIFIED_LOC,
TGT.TOW_DEST_ADDITIONAL_INFO = SRC.TOW_DEST_ADDITIONAL_INFO,
TGT.ETL_JOB_RUN_ID = CAST(SRC.JOB_RUN_ID AS INT64), 
TGT.SOURCE_SYSTEM_CD = SRC.SOURCE_SYSTEM_CD ,  
TGT.CREATED_DTTIME = current_datetime() ,
TGT.CREATED_BY = SRC.CREATED_BY
WHEN NOT MATCHED THEN INSERT 
(
SC_DT,
SC_ID,
TOW_DEST_SEQ_ID,
TOW_DST_UPRS_TX,
LAST_UPDATE,
TOW_UNSEEN_CHNG,
EMPLE_ID,
TOW_DEST_LATITUDE,
TOW_DEST_LONGITUDE,
TOW_DEST_ID,
TOW_DEST_GRID,
TD_VERIFIED_LOC,
TOW_DEST_ADDITIONAL_INFO,
ETL_JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATED_BY,
CREATED_DTTIME)
VALUES
(
CAST(SRC.SC_DT AS DATETIME) , 
CAST(SRC.SC_ID AS INT64), 
CAST(SRC.TOW_DEST_SEQ_ID AS INT64) , 
SRC.TOW_DST_UPRS_TX, 
CAST(SRC.LAST_UPDATE AS DATE),
SRC.TOW_UNSEEN_CHNG,
SRC.EMPLE_ID,
CAST(SRC.TOW_DEST_LATITUDE AS FLOAT64),
CAST(SRC.TOW_DEST_LONGITUDE AS FLOAT64),
CAST(SRC.TOW_DEST_ID AS INT64),
SRC.TOW_DEST_GRID,
SRC.TD_VERIFIED_LOC,
SRC.TOW_DEST_ADDITIONAL_INFO, 
CAST(SRC.JOB_RUN_ID AS INT64),
SOURCE_SYSTEM_CD,
CREATED_BY,
current_datetime()
)

