-- UPDATE(MERGE)

--MERGE <target_table> [AS TARGET]
--USING <table_source> [AS SOURCE]
--ON <search_condition>
--[WHEN MATCHED 
--THEN <merge_matched> ]
--[WHEN NOT MATCHED [BY TARGET]
--THEN <merge_not_matched> ]
--[WHEN NOT MATCHED BY SOURCE
--THEN <merge_matched> ]
  
--ERS_STAGE_CAD_TOW_DEST
--WORK_ERS_STG_CAD_TOW_DEST
MERGE OPERATIONAL.ERS_STAGE_TOW_DEST_LIST AS TGT
USING LANDING.WORK_ERS_STG_TOW_DEST_LIST AS SRC
ON CAST(TGT.TD_ID AS STRING) = SRC.TD_ID
WHEN MATCHED
THEN UPDATE SET
TGT.TD_ID = CAST(SRC.TD_ID AS INT64) , 
TGT.TD_NAME = SRC.TD_NAME , 
TGT.TD_ADDRESS = SRC.TD_ADDRESS, 
TGT.TD_PHONE_NR = SRC.TD_PHONE_NR, 
TGT.TD_PHONE_EXT = SRC.TD_PHONE_EXT,
TGT.TD_PHONE_TYPE = SRC.TD_PHONE_TYPE,
TGT.TD_CITY = SRC.TD_CITY,
TGT.TD_STATE = SRC.TD_STATE,
TGT.TD_ZIP = SRC.TD_ZIP,
TGT.TD_CONTACT = SRC.TD_CONTACT,
TGT.TD_LATITUDE = CAST(SRC.TD_LATITUDE AS FLOAT64),
TGT.TD_LONGITUDE = CAST(SRC.TD_LONGITUDE AS FLOAT64),
TGT.TD_USE_DEFAULT_TM = SRC.TD_USE_DEFAULT_TM,
TGT.TD_AAA_APPROVED = SRC.TD_AAA_APPROVED,
TGT.TD_DEALER_INDIC = SRC.TD_DEALER_INDIC,
TGT.TD_SHOW_CARD_SAVE = SRC.TD_SHOW_CARD_SAVE,
TGT.TD_GRID = SRC.TD_GRID,
TGT.TD_CLB_CD = SRC.TD_CLB_CD,
TGT.TD_SECURE_LOT = SRC.TD_SECURE_LOT,
TGT.TD_DROP_BOX_LOC = SRC.TD_DROP_BOX_LOC,
TGT.TD_EXT_DEALER_ID = SRC.TD_EXT_DEALER_ID,
TGT.TD_FAX_PHONE = SRC.TD_FAX_PHONE,
TGT.MOBILE_TECH = SRC.MOBILE_TECH,
TGT.TD_DEST_TYPE = SRC.TD_DEST_TYPE,
TGT.LAST_UPDATE =  CAST(SRC.LAST_UPDATE AS DATETIME),
TGT.TD_SPP_FLAG = SRC.TD_SPP_FLAG,
TGT.TD_AAR_TOW_DEST_ID = CAST(SRC.TD_AAR_TOW_DEST_ID AS INT64),
TGT.TD_AAA_DOLLARS = SRC.TD_AAA_DOLLARS,
TGT.ETL_JOB_RUN_ID = CAST(SRC.JOB_RUN_ID AS INT64), 
TGT.SOURCE_SYSTEM_CD = SRC.SOURCE_SYSTEM_CD ,  
TGT.CREATED_DTTIME = current_datetime() ,
TGT.CREATED_BY = SRC.CREATED_BY
WHEN NOT MATCHED THEN INSERT 
(
TD_ID,
TD_NAME,
TD_ADDRESS,
TD_PHONE_NR,
TD_PHONE_EXT,
TD_PHONE_TYPE,
TD_CITY,
TD_STATE,
TD_ZIP,
TD_CONTACT,
TD_LATITUDE,
TD_LONGITUDE,
TD_USE_DEFAULT_TM,
TD_AAA_APPROVED,
TD_DEALER_INDIC,
TD_SHOW_CARD_SAVE,
TD_GRID,
TD_CLB_CD,
TD_SECURE_LOT,
TD_DROP_BOX_LOC,
TD_EXT_DEALER_ID,
TD_FAX_PHONE,
MOBILE_TECH,
TD_DEST_TYPE,
LAST_UPDATE,
TD_SPP_FLAG,
TD_AAR_TOW_DEST_ID,
TD_AAA_DOLLARS,
ETL_JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATED_BY,
CREATED_DTTIME	)
VALUES
(
CAST(SRC.TD_ID AS INT64),
TD_NAME,
TD_ADDRESS,
TD_PHONE_NR,
TD_PHONE_EXT,
TD_PHONE_TYPE,
TD_CITY,
TD_STATE,
TD_ZIP,
TD_CONTACT,
CAST(TD_LATITUDE AS FLOAT64),
CAST(TD_LONGITUDE AS FLOAT64),
TD_USE_DEFAULT_TM,
TD_AAA_APPROVED,
TD_DEALER_INDIC,
TD_SHOW_CARD_SAVE,
TD_GRID,
TD_CLB_CD,
TD_SECURE_LOT,
TD_DROP_BOX_LOC,
TD_EXT_DEALER_ID,
TD_FAX_PHONE,
MOBILE_TECH,
TD_DEST_TYPE,
CAST(SRC.LAST_UPDATE AS DATETIME),
TD_SPP_FLAG,
CAST(TD_AAR_TOW_DEST_ID AS INT64),
TD_AAA_DOLLARS,
CAST(SRC.JOB_RUN_ID AS INT64),
SOURCE_SYSTEM_CD,
CREATED_BY,
current_datetime()
)

