INSERT INTO `OPERATIONAL.ERS_STAGE_STAT_GRP` (
START_DTM,
END_DTM,
GROUP_ID,
FACIL_INT_ID,
CATEGORY,
ACCT,
ACCT_NAME,
NUM_CALLS,
AMOUNT,
CPC,
F1099,
ETL_JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATE_DT,
CREATE_BY
)
SELECT 
SAFE_CAST(START_DTM AS DATETIME),
SAFE_CAST(END_DTM AS DATETIME),
GROUP_ID,
SAFE_CAST(FACIL_INT_ID AS INT64),
CATEGORY,
ACCT,
ACCT_NAME,
SAFE_CAST(NUM_CALLS AS INT64),
SAFE_CAST(AMOUNT AS FLOAT64),
SAFE_CAST(CPC as FLOAT64),
F1099,
SAFE_CAST(JOB_RUN_ID AS INT64),
SOURCE_SYSTEM_CD,
CURRENT_DATETIME(),
CREATED_BY
FROM 
`LANDING.WORK_ERS_STG_STAT_GRP`