-- UPDATE(MERGE)

--MERGE <target_table> [AS TARGET]
--USING <table_source> [AS SOURCE]
--ON <search_condition>
--[WHEN MATCHED 
--THEN <merge_matched> ]
--[WHEN NOT MATCHED [BY TARGET]
--THEN <merge_not_matched> ]
--[WHEN NOT MATCHED BY SOURCE
--THEN <merge_matched> ];
  
--ERS_STAGE_INQ_ENTITLEMENT_PERIODS
--WORK_ERS_STG_INQ_ENTITLEMENT_PERIODS
MERGE OPERATIONAL.ERS_STAGE_INQ_ENTITLEMENT_PERIODS AS TGT
USING (SELECT DISTINCT * FROM  LANDING.WORK_ERS_STG_INQ_ENTITLEMENT_PERIODS) AS SRC
ON TGT.CLB_CD =  SRC.CLB_CD and
TGT.MBR_ID =  SRC.MBR_ID and
TGT.ASSOC_MBR_ID =  SRC.ASSOC_MBR_ID and
CAST(TGT.SEQ_NUM AS STRING) = SRC.SEQ_NUM and
TGT.ENT_START_DATE = CAST(SRC.ENT_START_DATE AS DATE) and
TGT.ENT_END_DATE = CAST(SRC.ENT_END_DATE AS DATE)
WHEN MATCHED
THEN UPDATE SET
TGT.CLB_CD = SRC.CLB_CD , 
TGT.MBR_ID = SRC.MBR_ID , 
TGT.ASSOC_MBR_ID = SRC.ASSOC_MBR_ID , 
TGT.SEQ_NUM = CAST(SRC.SEQ_NUM AS INT64),
TGT.ENT_START_DATE = CAST(SRC.ENT_START_DATE AS DATE) , 
TGT.ENT_END_DATE = CAST(SRC.ENT_END_DATE AS DATE), 
TGT.PERIOD_STATUS = SRC.PERIOD_STATUS, 
TGT.MBRSHP_TYPE = SRC.MBRSHP_TYPE, 
TGT.YTD = CAST(SRC.YTD AS INT64),
TGT.ENTITLEMENTS = CAST(SRC.ENTITLEMENTS AS INT64),
TGT.ENT_DELTA = CAST(SRC.ENT_DELTA AS INT64),
TGT.GRACE_USAGE = CAST(SRC.GRACE_USAGE AS INT64),
TGT.ETL_JOB_RUN_ID = CAST(SRC.JOB_RUN_ID AS INT64), 
TGT.SOURCE_SYSTEM_CD = SRC.SOURCE_SYSTEM_CD ,  
TGT.CREATED_DTTIME = current_datetime() ,
TGT.CREATED_BY = SRC.CREATED_BY
WHEN NOT MATCHED THEN INSERT 
(
CLB_CD,
MBR_ID,
ASSOC_MBR_ID,
SEQ_NUM,
ENT_START_DATE,
ENT_END_DATE,
PERIOD_STATUS,
MBRSHP_TYPE,
YTD,
ENTITLEMENTS,
ENT_DELTA,
GRACE_USAGE,
ETL_JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATED_BY,
CREATED_DTTIME)
VALUES
(
SRC.CLB_CD , 
SRC.MBR_ID , 
SRC.ASSOC_MBR_ID , 
CAST(SEQ_NUM AS INT64),
CAST(SRC.ENT_START_DATE AS DATE) , 
CAST(SRC.ENT_END_DATE AS DATE), 
SRC.PERIOD_STATUS, 
SRC.MBRSHP_TYPE, 
CAST(SRC.YTD AS INT64),
CAST(SRC.ENTITLEMENTS AS INT64),
CAST(SRC.ENT_DELTA AS INT64),
CAST(SRC.GRACE_USAGE AS INT64), 
CAST(SRC.JOB_RUN_ID AS INT64),
SOURCE_SYSTEM_CD,
CREATED_BY,
current_datetime()
)

