-- UPDATE(MERGE)

--MERGE <target_table> [AS TARGET]
--USING <table_source> [AS SOURCE]
--ON <search_condition>
--[WHEN MATCHED 
--THEN <merge_matched> ]
--[WHEN NOT MATCHED [BY TARGET]
--THEN <merge_not_matched> ]
--[WHEN NOT MATCHED BY SOURCE
--THEN <merge_matched> ];
  
--ERS_STAGE_APD_REMB_DETAIL
--WORK_ERS_STG_APD_REMB_DETAIL
MERGE OPERATIONAL.ERS_STAGE_APD_REMB_DETAIL AS TGT
USING (SELECT DISTINCT * FROM  LANDING.WORK_ERS_STG_APD_REMB_DETAIL) AS SRC
ON TGT.COMM_CTR_ID = SRC.COMM_CTR_ID and
TGT.SC_DT = CAST(SRC.SC_DT AS DATETIME) and
CAST(TGT.SC_ID AS STRING) = SRC.SC_ID and
TGT.ACCOUNT = SRC.ACCOUNT
WHEN MATCHED
THEN UPDATE SET
TGT.COMM_CTR_ID = SRC.COMM_CTR_ID , 
TGT.SC_DT = CAST(SRC.SC_DT AS DATETIME) , 
TGT.SC_ID = CAST(SRC.SC_ID AS INT64), 
TGT.ACCOUNT = SRC.ACCOUNT, 
TGT.APPROVED_AMOUNT = CAST(SRC.APPROVED_AMOUNT AS FLOAT64),  
TGT.ETL_JOB_RUN_ID = CAST(SRC.JOB_RUN_ID AS INT64), 
TGT.SOURCE_SYSTEM_CD = SRC.SOURCE_SYSTEM_CD ,  
TGT.CREATED_DTTIME = current_datetime() ,
TGT.CREATED_BY = SRC.CREATED_BY
WHEN NOT MATCHED THEN INSERT 
(
COMM_CTR_ID,
SC_DT,
SC_ID,
ACCOUNT,
APPROVED_AMOUNT,
ETL_JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATED_BY,
CREATED_DTTIME)
VALUES
(
SRC.COMM_CTR_ID , 
CAST(SRC.SC_DT AS DATETIME) , 
CAST(SRC.SC_ID AS INT64), 
SRC.ACCOUNT, 
CAST(SRC.APPROVED_AMOUNT AS FLOAT64),  
CAST(SRC.JOB_RUN_ID AS INT64),
SOURCE_SYSTEM_CD,
CREATED_BY,
current_datetime()
)

