-- UPDATE(MERGE)

--MERGE <target_table> [AS TARGET]
--USING <table_source> [AS SOURCE]
--ON <search_condition>
--[WHEN MATCHED 
--THEN <merge_matched> ]
--[WHEN NOT MATCHED [BY TARGET]
--THEN <merge_not_matched> ]
--[WHEN NOT MATCHED BY SOURCE
--THEN <merge_matched> ];
  
--ERS_STAGE_APD_REIMBURSEMENT
--WORK_ERS_STG_APD_REIMBURSEMENT
MERGE OPERATIONAL.ERS_STAGE_APD_REIMBURSEMENT AS TGT
USING LANDING.WORK_ERS_STG_APD_REIMBURSEMENT AS SRC
ON 
CAST(TGT.REIMB_INT_ID AS STRING) = SRC.REIMB_INT_ID
WHEN MATCHED
THEN UPDATE SET
TGT.COMM_CTR_ID = SRC.COMM_CTR_ID ,  
TGT.SC_DT = CAST(SRC.SC_DT AS DATETIME) , 
TGT.SC_ID = CAST(SRC.SC_ID AS INT64), 
TGT.FAC_NM = SRC.FAC_NAME, 
TGT.AAA_CALL = SRC.AAA_CALL , 
TGT.REASON_CD = SRC.REASON_CODE , 
TGT.TOTAL_REQUEST = CAST(SRC.TOTAL_REQUEST AS FLOAT64), 
TGT.RECEIVED_DT = CAST(SRC.RECEIVED_DATE AS DATETIME) , 
TGT.FOLLOWUP_DT = CAST(SRC.FOLLOWUP_DATE AS DATETIME) , 
TGT.REPLY_DT = CAST(SRC.REPLY_DATE AS DATETIME) , 
TGT.APPROVED_DT = CAST(SRC.APPROVED_DATE AS DATETIME) , 
TGT.APPROVAL_ID = SRC.APPROVAL_ID , 
TGT.CHECK_STUB_CD = SRC.CHECK_STUB_CD , 
TGT.PAY_DT = CAST(SRC.PAY_DATE AS DATETIME) , 
TGT.PAY_ID = CAST(SRC.PAY_ID AS INT64) , 
TGT.COMMENTX = SRC.COMMENTX, 
TGT.ADDR_CHG_IND = SRC.ADDR_CHG_IND, 
TGT.DIST_CD = SRC.DIST_CODE , 
TGT.BSC_AD = SRC.BSC_AD , 
TGT.SUPL_AD = SRC.SUPL_AD , 
TGT.CTY_NM = SRC.CTY_NM , 
TGT.ST_CD = SRC.ST_CD, 
TGT.ZIP_CD = SRC.ZIP_CD , 
TGT.REIMB_INT_ID = CAST(SRC.REIMB_INT_ID AS INT64) , 
TGT.CASH_REMB = SRC.CASH_REMB , 
TGT.PAYEE_NM = SRC.PAYEE_NAME , 
TGT.PAYEE_STREET1 = SRC.PAYEE_STREET1 , 
TGT.PAYEE_STREET2 = SRC.PAYEE_STREET2 , 
TGT.PAYEE_CITY = SRC.PAYEE_CITY , 
TGT.PAYEE_STATE = SRC.PAYEE_STATE , 
TGT.PAYEE_ZIP = SRC.PAYEE_ZIP , 
TGT.SPECIAL_ENTITLEMENT_REQ = SRC.SPECIAL_ENTITLEMENT_REQ , 
TGT.ETL_JOB_RUN_ID = CAST(SRC.JOB_RUN_ID AS INT64), 
TGT.SOURCE_SYSTEM_CD = SRC.SOURCE_SYSTEM_CD ,  
TGT.CREATED_DTTIME = current_datetime() ,
TGT.CREATED_BY = SRC.CREATED_BY
WHEN NOT MATCHED THEN INSERT 
(
COMM_CTR_ID,
SC_DT,
SC_ID,
FAC_NM,
AAA_CALL,
REASON_CD,
TOTAL_REQUEST,
RECEIVED_DT,
FOLLOWUP_DT,
REPLY_DT,
APPROVED_DT,
APPROVAL_ID,
CHECK_STUB_CD,
PAY_DT,
PAY_ID,
COMMENTX,
ADDR_CHG_IND,
DIST_CD,
BSC_AD,
SUPL_AD,
CTY_NM,
ST_CD,
ZIP_CD,
REIMB_INT_ID,
CASH_REMB,
PAYEE_NM,
PAYEE_STREET1,
PAYEE_STREET2,
PAYEE_CITY,
PAYEE_STATE,
PAYEE_ZIP,
SPECIAL_ENTITLEMENT_REQ,
ETL_JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATED_BY,
CREATED_DTTIME)
VALUES
(
SRC.COMM_CTR_ID,
CAST(SRC.SC_DT AS DATETIME),
CAST(SRC.SC_ID AS INT64),
SRC.FAC_NAME,
SRC.AAA_CALL,
SRC.REASON_CODE,
CAST(SRC.TOTAL_REQUEST AS FLOAT64),
CAST(SRC.RECEIVED_DATE AS DATETIME),
CAST(SRC.FOLLOWUP_DATE AS DATETIME),
CAST(SRC.REPLY_DATE AS DATETIME),
CAST(SRC.APPROVED_DATE AS DATETIME),
APPROVAL_ID,
CHECK_STUB_CD,
CAST(SRC.PAY_DATE AS DATETIME),
CAST(SRC.PAY_ID AS INT64),
COMMENTX,
ADDR_CHG_IND,
DIST_CODE,
BSC_AD,
SUPL_AD,
CTY_NM,
ST_CD,
ZIP_CD,
CAST(SRC.REIMB_INT_ID AS INT64),
CASH_REMB,
PAYEE_NAME,
PAYEE_STREET1,
PAYEE_STREET2,
PAYEE_CITY,
PAYEE_STATE,
PAYEE_ZIP,
SPECIAL_ENTITLEMENT_REQ,
CAST(SRC.JOB_RUN_ID AS INT64),
SOURCE_SYSTEM_CD,
CREATED_BY,
current_datetime()
)
