INSERT INTO LANDING.PCOMP_HO_LEGACY(
STAGEKEY,
BATCH_NM,
SOURCE_SYSTEM,
LOAD_DT,
POL_PREFIX,
POL_NUM,
STREET_ADDR_NUM,
MEMBERSHIP_NUM,
MEMB_STREET_NUM,
EFF_DT,
FIRST_EFF_DT,
CANCEL_DT,
RENEWED,
POL_TYPE,
FILLER,
PRODUCT_CD,
ETL_JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATE_DT,
CREATED_BY
)
SELECT 
CASE
     WHEN PCOMP.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
     ELSE PCOMP.MAX_ID+(ROW_NUMBER() OVER ())
   END AS STAGEKEY,
CONCAT('BATCH',CAST(CURRENT_DATE() AS STRING)),
'Legacy',
CURRENT_DATE(),
POL_PREFIX,
POL_NUM,
STREET_ADDR_NUM,
MEMBERSHIP_NUM,
MEMB_STREET_NUM,
PARSE_DATE('%m%d%Y',EFF_DT),
PARSE_DATE('%m%d%Y',FIRST_EFF_DT),
CASE WHEN CANCEL_DT='00000000'
    THEN '2999-12-31'
   ELSE
     PARSE_DATE('%m%d%Y',CANCEL_DT)
    END AS CANCEL_DT,
RENEWED,
POL_TYPE,
FILLER,
CAST(NULL AS STRING) AS PRODUCT_CD,
 "v_job_run_id" AS ETL_JOB_RUN_ID,
 "HO_LEGACY" AS SOURCE_SYSTEM_CD,
    CURRENT_DATE() AS CREATE_DT,
    "v_job_name" AS CREATED_BY
FROM `LANDING.WORK_PCOMP_HO_LEGACY_XSDLYSTB`,
(
   SELECT
     MAX(STAGEKEY) MAX_ID
   FROM
     LANDING.PCOMP_HO_LEGACY ) PCOMP