INSERT INTO LANDING.PCOMP_HO_LEGACY(
STAGEKEY,
BATCH_NM,
SOURCE_SYSTEM,
LOAD_DT,
POL_PREFIX,
POL_NUM,
STREET_ADDR_NUM,
MEMBERSHIP_NUM,
MEMB_STREET_NUM,
EFF_DT,
FIRST_EFF_DT,
CANCEL_DT,
RENEWED,
POL_TYPE,
FILLER,
PRODUCT_CD,
ETL_JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATE_DT,
CREATED_BY
)
SELECT  
CASE
     WHEN PCOMP.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
     ELSE PCOMP.MAX_ID+(ROW_NUMBER() OVER ())
   END AS STAGEKEY,
CONCAT('BATCH',CAST(CURRENT_DATE() AS STRING)),
'Exigen Home',
CURRENT_DATE(),
CAST(NULL AS STRING) AS POL_PREFIX,
SUBSTR(TRIM(POLICY_NUM),5,10),
ADDRESS_STREET,
MEMBERSHIP_NUM,
CONCAT(MEMBERSHIP_NUM,'_',ADDRESS_STREET),
PARSE_DATE('%m%d%Y',LPAD(TERM_EFFECTIVE_DT,8,'0')),
PARSE_DATE('%m%d%Y',LPAD(FIRST_TERM_EFFECTIVE_DT,8,'0')),
CASE WHEN CANCELLATION_DT IS NULL
  THEN NULL
 ELSE PARSE_DATE('%m%d%Y',LPAD(CANCELLATION_DT,8,'0'))
END AS CANCEL_DT,
CASE WHEN DATE_DIFF(PARSE_DATE('%m%d%Y',LPAD(TERM_EFFECTIVE_DT,8,'0')),PARSE_DATE('%m%d%Y',LPAD(FIRST_TERM_EFFECTIVE_DT,8,'0')),day) <=364
  THEN 'N'
  ELSE 'Y'
  END AS RENEWED,
POLICY_STATUS_CD,
CAST(NULL AS STRING) AS FILLER,
PROD.CLUB_PRODUCT_CODE AS PRODUCT_CD,
 "v_job_run_id" AS ETL_JOB_RUN_ID,
 "HO_LEGACY" AS SOURCE_SYSTEM_CD,
    CURRENT_DATE() AS CREATE_DT,
    "v_job_name" AS CREATED_BY
FROM LANDING.WORK_PCOMP_HO_LEGACY HO
LEFT OUTER JOIN
LANDING.PAS_PRODUCT PROD
ON (SUBSTR(TRIM(HO.POLICY_NUM),1,4))= TRIM(PROD.POLICY_STATE_PREFIX),
(
   SELECT
     MAX(STAGEKEY) MAX_ID
   FROM
     LANDING.PCOMP_HO_LEGACY ) PCOMP