INSERT INTO LANDING.PCOMP_HO_2K8_RECLASSIFY
(
STAGEKEY,
BATCH_NM,
SOURCE_SYSTEM,
LOAD_DT,
POL_PREFIX,
OLD_POL_NUM,
STREET_ADDR_NUM,
MEMBERSHIP_NUM,
MEMB_STREET_NUM,
EFF_DT,
FIRST_EFF_DT,
CANCEL_DT,
RENEWED,
OLD_POL_TYPE,
FILLER,
NEW_POL_NUM,
NEW_POL_TYPE,
RECLASSIFY_ELIGIBLE,
ETL_JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATE_DT,
CREATED_BY
)
SELECT
   CASE
     WHEN PCOMP.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
     ELSE PCOMP.MAX_ID+(ROW_NUMBER() OVER ())
   END AS STAGEKEY,
   CONCAT('BATCH',CAST(CURRENT_DATE() AS STRING)) AS BATCH_NAME,
'AS400',
CURRENT_DATE(),
STG.POLICY_PREFIX,
HO.POL_NUM,
STG.STREET_NUM,
STG.MEMBERSHIP_NUM,
CONCAT( STG.MEMBERSHIP_NUM,'_', STG.STREET_NUM),
PARSE_DATE('%m%d%Y',LPAD( STG.TERM_EFFECTIVE_DT , 8, '0')),
CAST(NULL AS DATE) AS FIRST_EFF_DT,
CASE WHEN STG.CANCELLATION_DT = "10101"
	THEN PARSE_DATE('%Y%m%d','29991231')
ELSE
	PARSE_DATE('%Y%m%d',STG.CANCELLATION_DT)
END AS CANCEL_DT,
STG.RENEWED,
HO.POL_TYPE,
STG.FILLER,
CASE WHEN LENGTH(TRIM(STG.POLICY_NUM)) > 8
then 
CONCAT('00',SUBSTR(SUBSTR( TRIM(STG.POLICY_NUM), 3, 7 ),0,LENGTH(SUBSTR( TRIM(STG.POLICY_NUM), 3, 7 ))-1),'-',SUBSTR(SUBSTR( TRIM(STG.POLICY_NUM), 3, 7 ),-1))
ELSE
CONCAT('00',SUBSTR(TRIM(STG.POLICY_NUM),0,LENGTH(TRIM(STG.POLICY_NUM))-1),'-',SUBSTR(TRIM(STG.POLICY_NUM),-1))
END AS NEW_POL_NUM,
CASE WHEN STG.TRANSACTION_TYPE = 'NB' AND STG.RENEWED='Y'
  THEN 'RN'
 ELSE
  (
  CASE WHEN CONCAT( STG.MEMBERSHIP_NUM,'_', STG.STREET_NUM)=HO. MEMB_STREET_NUM AND HO.POL_TYPE='Cancel' AND
      (
      CASE WHEN CONCAT( STG.MEMBERSHIP_NUM,'_', STG.STREET_NUM)=HO. MEMB_STREET_NUM AND HO.SOURCE_SYSTEM = 'AS400' AND HO.CANCEL_DT IS NOT NULL AND DATE_DIFF(HO.EFF_DT,HO.CANCEL_DT,day) <=364
           THEN FALSE
           ELSE (CASE WHEN CONCAT( STG.MEMBERSHIP_NUM,'_', STG.STREET_NUM)=HO. MEMB_STREET_NUM AND HO.SOURCE_SYSTEM = 'AS400' AND HO.RENEWED = 'Y'
	                    THEN TRUE
                      ELSE FALSE
                  END)
      END)
  THEN 'RN'
  ELSE STG.TRANSACTION_TYPE
  END
  )
  END AS NEW_POL_TYPE,
CASE WHEN STG.TRANSACTION_TYPE = 'NB' AND STG.RENEWED='Y'
  THEN 'RN'
 ELSE
  (
  CASE WHEN CONCAT( STG.MEMBERSHIP_NUM,'_', STG.STREET_NUM)=HO. MEMB_STREET_NUM AND HO.POL_TYPE='Cancel' AND
      (
      CASE WHEN CONCAT( STG.MEMBERSHIP_NUM,'_', STG.STREET_NUM)=HO. MEMB_STREET_NUM AND HO.SOURCE_SYSTEM = 'AS400' AND HO.CANCEL_DT IS NOT NULL AND DATE_DIFF(HO.EFF_DT,HO.CANCEL_DT,day) <=364
           THEN FALSE
           ELSE (CASE WHEN CONCAT( STG.MEMBERSHIP_NUM,'_', STG.STREET_NUM)=HO. MEMB_STREET_NUM AND HO.SOURCE_SYSTEM = 'AS400' AND HO.RENEWED = 'Y'
	                    THEN TRUE
                      ELSE FALSE
                  END)
      END)
  THEN 'Y'
  ELSE 'N'
  END
  )
  END AS RECLASSIFY_ELIGIBLE,
 "v_job_run_id" AS ETL_JOB_RUN_ID,
 "PCOMP" AS SOURCE_SYSTEM_CD,
    CURRENT_DATE() AS CREATE_DT,
    "v_job_name" AS CREATED_BY
FROM LANDING.WORK_PCOMP_HO_HISTORY STG
LEFT OUTER JOIN
LANDING.PCOMP_HO_HISTORY HO
ON CONCAT( STG.MEMBERSHIP_NUM,'_', STG.STREET_NUM) = CONCAT( HO.MEMBERSHIP_NUM,'_',HO. STREET_ADDR_NUM)
 AND (CASE WHEN LENGTH(TRIM(STG.POLICY_NUM)) > 8
  THEN SUBSTR( TRIM(STG.POLICY_NUM), 3, 7 )
 ELSE STG.POLICY_NUM
END) = HO.POL_NUM,
    (
   SELECT
     MAX(STAGEKEY) MAX_ID
   FROM
     LANDING.PCOMP_HO_2K8_RECLASSIFY) PCOMP
WHERE STG.Transaction_Type = 'NB'
