INSERT INTO
  LANDING.PCOMP_INSURANCE_TRANSACTION ( INSURANCE_TRANSACTION_ID,
    BATCH_NM,
    PRODUCT_CD,
    POLICY_NUM,
    POLICY_EFFECTIVE_DT,
    POLICY_ENDORSEMENT_DT,
    POLICY_STATE,
    POLICY_HOLDER_LAST_NM,
    TRANSACTION_EFFECTIVE_DT,
    MAILING_ZIP_CD,
    RESIDENTIAL_ZIP_CD,
    TRANSACTION_CD,
    SOURCE_SYSTEM,
    TRANSACTION_TYPE,
    TRANSACTION_DT,
    TRANSACTION_AMT,
    SALES_REP_ID,
    SALES_REP_DO,
    PROCESS_TYPE,
    INCEPTION_DT,
    TERM_IND,
    RENEW_COUNT,
    ERROR_FLAG,
    ETL_JOB_RUN_ID,
    CREATED_DT,
    CREATED_BY)
SELECT
  INSURANCE_TRANSACTION_ID,
  BATCH_NAME,
  PRODUCT_CD,
  POLICY_NUM,
  POLICY_EFFECTIVE_DT,
  POLICY_ENDORSEMENT_DT,
  POLICY_STATE,
  POLICY_HOLDER_LAST_NAME,
  TRANSACTION_EFFECTIVE_DT,
  MAILING_ZIP_CD,
  RESIDENTIAL_ZIP_CD,
  TRANSACTION_CD,
  SOURCE_SYSTEM,
  TRANSACTION_TYPE,
  TRANSACTION_DT,
  TRANSACTION_AMOUNT,
  SALESREP_ID,
  CASE
    WHEN UPPER(INC_POLICY_STATE) = 'UT' THEN CASE
    WHEN (CASE
      WHEN DONO_DSU_V IS NULL THEN DONO_PNC_SRC
      ELSE DONO_DSU_V END= '90'
    OR
    CASE
      WHEN DONO_DSU_V IS NULL THEN DONO_PNC_SRC
      ELSE DONO_DSU_V END= '92'
    OR
    CASE
      WHEN DONO_DSU_V IS NULL THEN DONO_PNC_SRC
      ELSE DONO_DSU_V END= '98'
    OR
    CASE
      WHEN DONO_DSU_V IS NULL THEN DONO_PNC_SRC
      ELSE DONO_DSU_V END= '91') THEN LPAD(LTRIM(RTRIM(CASE
          WHEN DONO_DSU_V IS NULL THEN DONO_PNC_SRC
          ELSE DONO_DSU_V END)),
    2,
    '0')
    ELSE CONCAT('1',CASE
      WHEN DONO_DSU_V IS NULL THEN DONO_PNC_SRC
      ELSE DONO_DSU_V END)
  END
    ELSE LPAD(LTRIM(RTRIM(CASE
          WHEN DONO_DSU_V IS NULL THEN DONO_PNC_SRC
          ELSE DONO_DSU_V END)),
    2,
    '0')
  END AS SALESREP_DO,
  PROCESS_TYPE,
  INCEPTION_DT,
  TERM_IND,
  RENEW_COUNT,
  CASE
    WHEN TRANS_CD_FLAG = '1' AND (TRANSACTION_AMOUNT_FLAG = '0' OR (CASE
        WHEN PREMIUM IS NULL
      OR POLICY_NUM IS NULL
      OR TRANSACTION_AMOUNT IS NULL
      OR SALESREP_ID IS NULL
      OR (CASE
          WHEN UPPER(INC_POLICY_STATE) = 'UT' THEN CASE
          WHEN (CASE
            WHEN DONO_DSU_V IS NULL THEN DONO_PNC_SRC
            ELSE DONO_DSU_V END= '90'
          OR
          CASE
            WHEN DONO_DSU_V IS NULL THEN DONO_PNC_SRC
            ELSE DONO_DSU_V END= '92'
          OR
          CASE
            WHEN DONO_DSU_V IS NULL THEN DONO_PNC_SRC
            ELSE DONO_DSU_V END= '98'
          OR
          CASE
            WHEN DONO_DSU_V IS NULL THEN DONO_PNC_SRC
            ELSE DONO_DSU_V END= '91') THEN LPAD(LTRIM(RTRIM(CASE
                WHEN DONO_DSU_V IS NULL THEN DONO_PNC_SRC
                ELSE DONO_DSU_V END)),
          2,
          '0')
          ELSE CONCAT('1',CASE
            WHEN DONO_DSU_V IS NULL THEN DONO_PNC_SRC
            ELSE DONO_DSU_V END)
        END
          ELSE LPAD(LTRIM(RTRIM(CASE
                WHEN DONO_DSU_V IS NULL THEN DONO_PNC_SRC
                ELSE DONO_DSU_V END)),
          2,
          '0') END) IS NULL
      OR TRANSACTION_DT IS NULL
      OR TRANSACTION_TYPE IS NULL
      OR PROCESS_TYPE IS NULL THEN '0'
        ELSE '1' END) = '0'
    OR (CASE
        WHEN V_TRM_IND = 'FALSE' THEN 0
        WHEN V_POL_TYP = 'FALSE' THEN 0
        WHEN V_TRAN_TYP = 'FALSE' THEN 0
        ELSE 1 END) = 0
    OR PREMIUM IS NULL ) THEN 'Load Validation Error'
    WHEN TRANS_CD_FLAG = '0' THEN 'Invalid Transactioncode'
    WHEN PRODUCT_CD IS NULL THEN 'Product Code is not found'
  END AS ERROR_FLAG,
  ETL_JOB_RUN_ID,
  CREATED_DT,
  CREATED_BY
FROM (
  SELECT
    CASE
      WHEN PCOMP.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
      ELSE PCOMP.MAX_ID+(ROW_NUMBER() OVER ())
    END AS INSURANCE_TRANSACTION_ID,
    CONCAT('BATCH',CAST(CURRENT_DATE() AS STRING)) AS BATCH_NAME,
    CASE
      WHEN PCHI.PRODUCT_CD = 'FH' AND POLICY_PREFIX = 'CAW' THEN 'FN'
      ELSE PCHI.PRODUCT_CD
    END AS PRODUCT_CD,
    LTRIM(RTRIM(POL_NUM)) AS POLICY_NUM,
    CASE
      WHEN LPAD(LTRIM(RTRIM(EFF_DT)),  8,  '0') = '00000000' THEN NULL
      ELSE PARSE_DATE('%m%d%Y',
      LPAD(LTRIM(RTRIM(EFF_DT)),
        8,
        '0'))
    END AS POLICY_EFFECTIVE_DT,
    CASE
      WHEN LPAD(LTRIM(RTRIM(TRN_DT)),  8,  '0') = '00000000' THEN NULL
      ELSE PARSE_DATE('%m%d%Y',
      LPAD(LTRIM(RTRIM(TRN_DT)),
        8,
        '0'))
    END AS POLICY_ENDORSEMENT_DT,
    GCCSC.COMP_STATE_CD AS POLICY_STATE,
    PHS.POL_STATE AS INC_POLICY_STATE,
    LTRIM(RTRIM(INSURED_NM)) AS POLICY_HOLDER_LAST_NAME,
    PARSE_DATE('%m%d%Y',
      LPAD(LTRIM(RTRIM(ENDMDY)),
        8,
        '0')) AS TRANSACTION_EFFECTIVE_DT,
    CASE
      WHEN LTRIM(RTRIM(MAILING_ZIP_CD))='000000000' OR LTRIM(RTRIM(MAILING_ZIP_CD))='000099999' THEN NULL
      WHEN LENGTH(LTRIM(RTRIM(MAILING_ZIP_CD)))<5 THEN LPAD(LTRIM(RTRIM(MAILING_ZIP_CD)),
      5,
      '0')
      ELSE SUBSTR(TRIM(MAILING_ZIP_CD),5,9)
    END AS MAILING_ZIP_CD,
    CASE
      WHEN LTRIM(RTRIM(RES_ZIP_CD))='000000000' OR LTRIM(RTRIM(RES_ZIP_CD))='000099999' OR LPAD(LTRIM(RTRIM(RES_ZIP_CD)), 5, '0')='00000' THEN NULL
      WHEN LENGTH(LTRIM(RTRIM(RES_ZIP_CD)))<5 THEN LPAD(LTRIM(RTRIM(RES_ZIP_CD)),
      5,
      '0')
      ELSE SUBSTR(TRIM(RES_ZIP_CD),5,9)
    END AS RESIDENTIAL_ZIP_CD,
    TRAN_CD TRANSACTION_CD,
    'Western United' AS SOURCE_SYSTEM,
    CASE
      WHEN TRAN_CD='NB' THEN 'New'
      WHEN TRAN_CD='NA' THEN 'New'
      WHEN TRAN_CD='NC' THEN 'New'
      WHEN TRAN_CD='NE' THEN 'New'
      WHEN TRAN_CD='NR' THEN 'New'
      WHEN TRAN_CD='RN' THEN 'Renewal'
      WHEN TRAN_CD='RC' THEN 'Renewal'
      WHEN TRAN_CD='RE' THEN 'Renewal'
      WHEN TRAN_CD='RR' THEN 'Renewal'
      WHEN TRAN_CD='CN' THEN 'Renewal'
      WHEN TRAN_CD='CC' THEN 'Renewal'
      WHEN TRAN_CD='CE' THEN 'Renewal'
      WHEN TRAN_CD='CR' THEN 'Renewal'
      WHEN TRAN_CD='CA' THEN 'Renewal'
      WHEN TRAN_CD='RA' THEN 'Renewal'
      ELSE NULL
    END AS TRANSACTION_TYPE,
     (CASE
      WHEN PARSE_DATE('%m%d%Y',  LPAD(LTRIM(RTRIM(ENDMDY)),  8,  '0')) >= (SELECT max(start_date) FROM `LANDING.PIPELINE_CALENDAR` where flag=True) AND PARSE_DATE('%m%d%Y',  LPAD(LTRIM(RTRIM(ENDMDY)),  8,  '0')) <=(SELECT max(end_date) FROM `LANDING.PIPELINE_CALENDAR` where flag=True)
	  THEN  PARSE_DATE('%m%d%Y',  LPAD(LTRIM(RTRIM(ENDMDY)),  8,  '0'))
      else 
	  case 
	  when PARSE_DATE('%m%d%Y', LPAD(LTRIM(RTRIM(TRN_DT)), 8,'0')) >= (SELECT max(start_date) FROM `LANDING.PIPELINE_CALENDAR` where flag=True)AND 
    PARSE_DATE('%m%d%Y', LPAD(LTRIM(RTRIM(TRN_DT)),8,'0')) <= (SELECT max(end_date) FROM `LANDING.PIPELINE_CALENDAR` where flag=True)
	  THEN PARSE_DATE('%m%d%Y', LPAD(LTRIM(RTRIM(TRN_DT)),   8,        '0'))    
	  ELSE (SELECT max(start_date) FROM `LANDING.PIPELINE_CALENDAR` where flag=True)
      END  
	END) AS TRANSACTION_DT,
    CASE
      WHEN CAST(PREMIUM AS FLOAT64) IS NULL THEN 0
      ELSE CAST(PREMIUM AS FLOAT64)
    END AS TRANSACTION_AMOUNT,
    CASE
      WHEN CAST(PREMIUM AS FLOAT64) <= CP1.PAR_VALUE_NUM_1 THEN '1'
      ELSE '0'
    END AS TRANSACTION_AMOUNT_FLAG,
    CASE
      WHEN TRIM(RTRIM(PHS.POL_STATE))='AZ' OR LTRIM(RTRIM(PHS.POL_STATE))='MT' OR LTRIM(RTRIM(PHS.POL_STATE))='WY' THEN AGENT_6_LVL
      ELSE LPAD(LTRIM(RTRIM(PHS.REP_NUM)),
      3,
      '0')
    END AS SALESREP_ID,
    CASE
      WHEN HIP.NEW_DONO IS NULL THEN CASE
      WHEN PHS.POL_STATE = 'NV' THEN
    CASE
      WHEN CASE
      WHEN PHS.POL_STATE = 'CA' THEN
    CASE
      WHEN AGENT_ID IS NULL THEN '000'
      ELSE AGENT_ID
    END WHEN PHS.POL_STATE = 'NV' THEN CASE
      WHEN AGENT_ID IS NULL THEN '000'
      ELSE AGENT_ID
    END WHEN PHS.POL_STATE = 'UT' THEN CASE
      WHEN AGENT_ID IS NULL THEN '000'
      ELSE AGENT_ID
    END
      ELSE AGENT_ID END='000'
    OR
    CASE
      WHEN PHS.POL_STATE = 'CA' THEN CASE
      WHEN REP_NUM IS NULL THEN '000'
      ELSE REP_NUM
    END WHEN PHS.POL_STATE = 'NV' THEN CASE
      WHEN REP_NUM IS NULL THEN '000'
      ELSE REP_NUM
    END WHEN PHS.POL_STATE = 'UT' THEN CASE
      WHEN REP_NUM IS NULL THEN '000'
      ELSE REP_NUM
    END
      ELSE REP_NUM END='000'
    AND (PHS.DONO ='00'
      OR PHS.DONO IS NULL) THEN '80'
      WHEN PHS.DONO IS NULL THEN '80'
      ELSE PHS.DONO
    END WHEN PHS.POL_STATE = 'UT' THEN CASE
      WHEN CASE
      WHEN PHS.POL_STATE = 'CA' THEN CASE
      WHEN AGENT_ID IS NULL THEN '000'
      ELSE AGENT_ID
    END WHEN PHS.POL_STATE = 'NV' THEN CASE
      WHEN AGENT_ID IS NULL THEN '000'
      ELSE AGENT_ID
    END WHEN PHS.POL_STATE = 'UT' THEN CASE
      WHEN AGENT_ID IS NULL THEN '000'
      ELSE AGENT_ID
    END
      ELSE AGENT_ID END='000'
    OR
    CASE
      WHEN PHS.POL_STATE = 'CA' THEN CASE
      WHEN REP_NUM IS NULL THEN '000'
      ELSE REP_NUM
    END WHEN PHS.POL_STATE = 'NV' THEN CASE
      WHEN REP_NUM IS NULL THEN '000'
      ELSE REP_NUM
    END WHEN PHS.POL_STATE = 'UT' THEN CASE
      WHEN REP_NUM IS NULL THEN '000'
      ELSE REP_NUM
    END
      ELSE REP_NUM END='000'
    AND (PHS.DONO ='00'
      OR PHS.DONO IS NULL) THEN '60'
      WHEN PHS.DONO IS NULL THEN '60'
      ELSE PHS.DONO
    END WHEN PHS.POL_STATE='CA' THEN CASE
      WHEN PHS.DONO IS NULL THEN '00'
      ELSE PHS.DONO
    END
      ELSE PHS.DONO
    END
      ELSE HIP.NEW_DONO
    END AS DONO_PNC_SRC,
    CASE
      WHEN HIP.NEW_REP_NUM IS NULL THEN PHS.DONO
      ELSE HIP.NEW_REP_NUM
    END AS AGENT_ID_PNC_SRC,
    CASE
      WHEN PHS.POL_STATE<>'CA' AND PHS.POL_STATE<>'NV' AND PHS.POL_STATE<>'UT' AND (CASE
        WHEN HIP.NEW_DONO IS NULL THEN PHS.DONO
        ELSE HIP.NEW_DONO
      END IS NULL
      OR
      CASE
        WHEN HIP.NEW_DONO IS NULL THEN PHS.DONO
        ELSE HIP.NEW_DONO END='00')
    AND
    CASE
      WHEN HIP.NEW_REP_NUM IS NULL THEN PHS.DONO
      ELSE HIP.NEW_REP_NUM
    END IS NOT NULL
    AND HID.DONO IS NULL THEN '92'
      WHEN (PHS.POL_STATE<>'CA' AND PHS.POL_STATE<>'NV' AND PHS.POL_STATE<>'UT' AND HID.DONO IS NULL AND CASE
        WHEN HIP.NEW_REP_NUM IS NULL THEN PHS.DONO
        ELSE HIP.NEW_REP_NUM
      END IS NULL
      AND
      CASE
        WHEN HIP.NEW_DONO IS NULL THEN PHS.DONO
        ELSE HIP.NEW_DONO
      END IS NULL) THEN '92'
      ELSE HID.DONO
    END DONO_DSU_V,
    CASE
      WHEN (TRAN_CD='NB' OR TRAN_CD='RN' OR TRAN_CD='CN') THEN 'Issue'
      WHEN (TRAN_CD='NC'
      OR TRAN_CD='RC'
      OR TRAN_CD='CC') THEN 'Cancel'
      WHEN (TRAN_CD='NE' OR TRAN_CD='RE' OR TRAN_CD='CE' OR TRAN_CD='NA' OR TRAN_CD='CA' OR TRAN_CD='RA') THEN 'Endorse'
      WHEN (TRAN_CD='NR'
      OR TRAN_CD='RR'
      OR TRAN_CD='CR') THEN 'Reinstate'
      ELSE NULL
    END AS PROCESS_TYPE,
    PARSE_DATE('%m%d%Y',
      ORIG_EFF_DT) AS INCEPTION_DT,
    CAST(TRM_IND AS INT64) AS TERM_IND,
    CAST(RNW_CNT AS INT64) RENEW_COUNT,
    "v_job_run_id" AS ETL_JOB_RUN_ID,
    CURRENT_DATETIME() AS CREATED_DT,
    "v_job_name" AS CREATED_BY,
    CASE
      WHEN CP.PAR_VALUE_CHAR_1 IS NULL THEN '0'
      ELSE '1'
    END AS TRANS_CD_FLAG,
    CASE
      WHEN ( CAST(TRM_IND AS INT64) = 3 OR CAST(TRM_IND AS INT64) = 6 OR CAST(TRM_IND AS INT64) = 12) THEN 'TRUE'
      ELSE 'FALSE'
    END AS V_TRM_IND,
    CASE
      WHEN ( ( TRAN_CD = 'NC' OR TRAN_CD = 'RC' OR TRAN_CD = 'CC' ) AND CAST(PREMIUM AS FLOAT64) < 0 ) OR ((TRAN_CD = 'NB' OR TRAN_CD = 'CN' OR TRAN_CD = 'RN') AND CAST(PREMIUM AS FLOAT64) > 0)OR ((TRAN_CD = 'NR' OR TRAN_CD = 'CR' OR TRAN_CD = 'RR') AND CAST(PREMIUM AS FLOAT64) > 0) OR ((TRAN_CD = 'NA' OR TRAN_CD = 'CA' OR TRAN_CD = 'RA') AND CAST(PREMIUM AS FLOAT64) != 0) OR ((TRAN_CD = 'NE' OR TRAN_CD = 'CE' OR TRAN_CD = 'RE') AND CAST(PREMIUM AS FLOAT64) != 0) THEN 'TRUE'ELSE 'FALSE'
    END AS V_TRAN_TYP,
    CASE
      WHEN PLTY IN ('H3',  'H4',  'H5',  'H6',  'D3',  'MA',  'MB',  'AU',  'WC',  '11',  '12',  '17',  '26',  '41',  '42',  '45',  '46',  'AP',  '52',  '54',  '63',  '56',  '13',  '58',  'MP') THEN 'TRUE'
      ELSE 'FALSE'
    END AS V_POL_TYP,
    SAFE_CAST(PREMIUM AS FLOAT64) AS PREMIUM
	
  FROM
    LANDING.WORK_PCOMP_HOMEINCENTIVE PHS
  LEFT OUTER JOIN
    REFERENCE.PRODUCT_CD_HOME_INC PCHI
  ON
    CASE
      WHEN LENGTH(PHS.COMP_NUM)=1 THEN CONCAT('0',PHS.COMP_NUM)
      ELSE PHS.COMP_NUM
    END = PCHI.DL_COMPANY
    AND PHS.POL_STATE = PCHI.POL_STATE
    AND PHS.POL_TYP = PCHI.PLTY
  LEFT OUTER JOIN
    REFERENCE.GA_CD_COMP_STATE_CD GCCSC
  ON
    CASE
      WHEN LENGTH(PHS.AGENT_3_LVL)=1 THEN CONCAT('00',PHS.AGENT_3_LVL)
      WHEN LENGTH(PHS.AGENT_3_LVL)=2 THEN CONCAT('0',PHS.AGENT_3_LVL)
      ELSE PHS.AGENT_3_LVL
    END = GCCSC.GA_CD
  LEFT OUTER JOIN
    REFERENCE.HOME_INCENTIVES_PNC HIP
  ON
    CASE
      WHEN PHS.POL_STATE = 'NV' THEN CASE
      WHEN CASE
      WHEN PHS.POL_STATE = 'CA' THEN CASE
      WHEN AGENT_ID IS NULL THEN '000'
      ELSE AGENT_ID
    END WHEN PHS.POL_STATE = 'NV' THEN CASE
      WHEN AGENT_ID IS NULL THEN '000'
      ELSE AGENT_ID
    END WHEN PHS.POL_STATE = 'UT' THEN CASE
      WHEN AGENT_ID IS NULL THEN '000'
      ELSE AGENT_ID
    END
      ELSE AGENT_ID END='000'
    OR
    CASE
      WHEN PHS.POL_STATE = 'CA' THEN CASE
      WHEN REP_NUM IS NULL THEN '000'
      ELSE REP_NUM
    END WHEN PHS.POL_STATE = 'NV' THEN CASE
      WHEN REP_NUM IS NULL THEN '000'
      ELSE REP_NUM
    END WHEN PHS.POL_STATE = 'UT' THEN CASE
      WHEN REP_NUM IS NULL THEN '000'
      ELSE REP_NUM
    END
      ELSE REP_NUM END='000'
    AND (PHS.DONO ='00'
      OR PHS.DONO IS NULL) THEN '80'
      WHEN PHS.DONO IS NULL THEN '80'
      ELSE PHS.DONO
    END WHEN PHS.POL_STATE = 'UT' THEN CASE
      WHEN CASE
      WHEN PHS.POL_STATE = 'CA' THEN CASE
      WHEN AGENT_ID IS NULL THEN '000'
      ELSE AGENT_ID
    END WHEN PHS.POL_STATE = 'NV' THEN CASE
      WHEN AGENT_ID IS NULL THEN '000'
      ELSE AGENT_ID
    END WHEN PHS.POL_STATE = 'UT' THEN CASE
      WHEN AGENT_ID IS NULL THEN '000'
      ELSE AGENT_ID
    END
      ELSE AGENT_ID END='000'
    OR
    CASE
      WHEN PHS.POL_STATE = 'CA' THEN CASE
      WHEN REP_NUM IS NULL THEN '000'
      ELSE REP_NUM
    END WHEN PHS.POL_STATE = 'NV' THEN CASE
      WHEN REP_NUM IS NULL THEN '000'
      ELSE REP_NUM
    END WHEN PHS.POL_STATE = 'UT' THEN CASE
      WHEN REP_NUM IS NULL THEN '000'
      ELSE REP_NUM
    END
      ELSE REP_NUM END='000'
    AND (PHS.DONO ='00'
      OR PHS.DONO IS NULL) THEN '60'
      WHEN PHS.DONO IS NULL THEN '60'
      ELSE PHS.DONO
    END WHEN PHS.POL_STATE='CA' THEN CASE
      WHEN PHS.DONO IS NULL THEN '00'
      ELSE PHS.DONO
    END
      ELSE PHS.DONO
    END = HIP.OLD_DONO
    AND
    CASE
      WHEN PHS.POL_STATE = 'CA' THEN CASE
      WHEN REP_NUM IS NULL THEN '000'
      ELSE REP_NUM
    END WHEN PHS.POL_STATE = 'NV' THEN CASE
      WHEN REP_NUM IS NULL THEN '000'
      ELSE REP_NUM
    END WHEN PHS.POL_STATE = 'UT' THEN CASE
      WHEN REP_NUM IS NULL THEN '000'
      ELSE REP_NUM
    END
      ELSE REP_NUM
    END = HIP.OLD_REP_NUM
  LEFT OUTER JOIN
    REFERENCE.HOME_INCENTIVES_DSU HID
  ON
    PHS.POL_STATE = HID.STATE
    AND PHS.AGENT_6_LVL = HID.AGT6_LVL
  LEFT OUTER JOIN
    `REFERENCE.COMMON_PARAMETERS` CP
  ON
    CP.FILE_TYPE = 'HOMEINCE'
    AND CP.PARAMETER_TYPE='VALID_TRANS_CODES'
    AND TRAN_CD = CP.PAR_VALUE_CHAR_1
  LEFT OUTER JOIN
    `REFERENCE.COMMON_PARAMETERS` CP1
  ON
    CP1.FILE_TYPE = 'HOMEINCE'
    AND CP1.PARAMETER_TYPE='VALID_TRANS_AMT',
    (
    SELECT
      MAX(INSURANCE_TRANSACTION_ID) MAX_ID
    FROM
      LANDING.PCOMP_INSURANCE_TRANSACTION) PCOMP
  WHERE
    CASE
      WHEN UPPER(PHS.POL_STATE)='AZ' AND (UPPER(POLICY_PREFIX) ='MAZ' OR UPPER(POLICY_PREFIX) ='WAC') THEN 'Y'
      ELSE 'N'
    END ='N'
    AND
    CASE
      WHEN CP.PAR_VALUE_CHAR_1 IS NULL THEN '0'
      ELSE '1'
    END = '1' )