INSERT INTO LANDING.PCOMP_AUTO_AS400
(
STAGEKEY,
BATCH_NM,
SOURCE_SYSTEM,
LOAD_DT,
POL_NUM,
MEMBERSHIP_NUM,
EFF_DT,
CANCEL_DT,
RENEW_COUNT,
RENEWED,
POL_TYPE,
TRANSACTION_TYPE,
DL01,
DL02,
DL03,
DL04,
DL05,
DL06,
DL07,
DL08,
DL09,
DL10,
VIN01,
VIN02,
VIN03,
VIN04,
VIN05,
VIN06,
VIN07,
VIN08,
VIN09,
VIN10,
FILLER,
ETL_JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATE_DT,
CREATED_BY
)
SELECT
   CASE
     WHEN PCOMP.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
     ELSE PCOMP.MAX_ID+(ROW_NUMBER() OVER ())
   END AS STAGEKEY,
CONCAT('BATCH',CAST(CURRENT_DATE() AS STRING)),
'AS400',
CURRENT_DATE(),
CONCAT(SUBSTR(TRIM(POLICY_NUM),1,(Length(TRIM(POLICY_NUM))-1)),'-',SUBSTR(TRIM(POLICY_NUM),-1,1)),
MEMBERSHIP_NUM,
PARSE_DATE('%m%d%Y',LPAD(TERM_EFFECTIVE_DT,8,'0')),
CASE WHEN CANCELLATION_DT = "10101"
	THEN PARSE_DATE('%Y%m%d','29991231')
ELSE
	PARSE_DATE('%Y%m%d',CANCELLATION_DT)
END AS CANCEL_DT,
NULL AS RENEW_COUNT,
IS_THE_POLICY_EVER_RENEWED,
POLICY_PREFIX,
TRANSACTION_TYPE,
DRIVER_LICENSE01,
DRIVER_LICENSE02,
DRIVER_LICENSE03,
DRIVER_LICENSE04,
DRIVER_LICENSE05,
DRIVER_LICENSE06,
DRIVER_LICENSE07,
DRIVER_LICENSE08,
DRIVER_LICENSE09,
DRIVER_LICENSE10,
VIN_NUMBER01,
VIN_NUMBER02,
VIN_NUMBER03,
VIN_NUMBER04,
VIN_NUMBER05,
VIN_NUMBER06,
VIN_NUMBER07,
VIN_NUMBER08,
VIN_NUMBER09,
VIN_NUMBER10,
FILLER,
"v_job_run_id" AS ETL_JOB_RUN_ID,
 "PCOMP" AS SOURCE_SYSTEM_CD,
    CURRENT_DATE() AS CREATE_DT,
    "v_job_name" AS CREATED_BY
FROM LANDING.WORK_PCOMP_AUTO_AS400,
 (
   SELECT
     MAX(STAGEKEY) MAX_ID
   FROM
     LANDING.PCOMP_AUTO_AS400) PCOMP
WHERE (TRANSACTION_TYPE)= 'NB'