CREATE OR REPLACE TABLE OPERATIONAL.GLOBALWARE_AIRPORT_CITY AS (
SELECT 
CD,
CITY_CD,
AIRPORT_NM,
CITY_NM,
STATE,
COUNTRY,
DOMINT,
SAFE_CAST(LAT AS FLOAT64) AS LAT ,
SAFE_CAST(LNG AS FLOAT64) AS LNG,
ADDRESS_1,
ADDRESS_2,
REVENUE_TYPE,
POSTAL_CD,
"jobrunid" AS JOB_RUN_ID,
"GLOBALWARE" AS SOURCE_SYSTEM_CD,
CURRENT_DATE() AS CREATE_DT 
FROM LANDING.WORK_GW_AIRPORT_CITY
)