CREATE OR REPLACE TABLE OPERATIONAL.GLOBALWARE_ARC_TABLE AS (
SELECT 
ARC_NUM,
BR_NUM,
STP_NUM,
ARC_TABLE_NM,
ADDR_1,
ADDR_2,
ADDR_3,
SAFE_CAST(BR_LOGO AS INT64) AS BR_LOGO,
USE_BR_LOGO,
USE_BR_ONAR,
LOGO_NM,
"jobrunid" AS JOB_RUN_ID,
"GLOBALWARE" AS SOURCE_SYSTEM_CD,
CURRENT_DATE() AS CREATE_DT 
FROM LANDING.WORK_GW_ARC_TABLE

)