MERGE OPERATIONAL.GLOBALWARE_COMMENTS A
USING LANDING.WORK_GW_COMMENTS B
ON A.INVOICE_PAY_ID = CAST(B.INVPAYID
 AS INT64)
 AND A.LINE_NUM = B.INVPAYID
WHEN MATCHED THEN
UPDATE SET
A.DATA = B.DATA
WHEN NOT MATCHED THEN
  INSERT (INVOICE_PAY_ID,
LINE_NUM,
DATA,
JOB_RUN_ID,
SOURCE_SYSTEM_CD,
LAST_UPDATE_DTTIME
)
VALUES
(SAFE_CAST(INVPAYID AS INT64),
LINENUM,
DATA,
"jobrunid",
'GLOBALWARE' ,
CURRENT_DATETIME())


