CREATE OR REPLACE TABLE OPERATIONAL.GLOBALWARE_CUST_TYPES AS (
SELECT 
CD,
DESCRIBE,
SAFE_CAST(CREATE_MARKET_ID AS INT64) AS CREATE_MARKET_ID,
SAFE_CAST(TYPE_FOR_MARKET_ID AS INT64) AS TYPE_FOR_MARKET_ID,
SAFE_CAST(EXCLUDE_FROM_ACCOUNT_ID AS INT64) AS EXCLUDE_FROM_ACCOUNT_ID,
"jobrunid" AS JOB_RUN_ID,
"GLOBALWARE" AS SOURCE_SYSTEM_CD,
CURRENT_DATE() AS CREATE_DT 
FROM LANDING.WORK_GW_CUSTTYPES
)