CREATE OR REPLACE TABLE OPERATIONAL.GLOBALWARE_DUP_PROV AS (
SELECT 
RES_CD AS RES_CD,
TRAV_TYPE AS TRAV_TYPE,
ACCOUNT_ID AS ACCOUNT_ID,
"jobrunid" AS JOB_RUN_ID,
"GLOBALWARE" AS SOURCE_SYSTEM_CD,
CURRENT_DATE() AS CREATE_DT 
FROM LANDING.WORK_GW_DUP_PROV
)