CREATE OR REPLACE TABLE OPERATIONAL.GLOBALWARE_FORMS_OF_PAYMENT AS (
SELECT 
CD ,
DESCRIPTION ,
"jobrunid" AS JOB_RUN_ID,
"GLOBALWARE" AS SOURCE_SYSTEM_CD,
CURRENT_DATE() AS CREATE_DT 
FROM LANDING.WORK_GW_FORMS_PAYMENTS


)