CREATE OR REPLACE TABLE OPERATIONAL.GLOBALWARE_PSEUDOCITY
AS (
SELECT 
TKT_LOC,
PSEUDO_CITY,
"jobrunid" AS JOB_RUN_ID,
"GLOBALWARE" AS SOURCE_SYSTEM_CD,
CURRENT_DATE() AS CREATE_DT 
FROM LANDING.WORK_GW_PSEUDOCITY
)