CREATE OR REPLACE TABLE OPERATIONAL.GLOBALWARE_REV_TYPES
AS (
SELECT 
REV_TYPE ,
TRAV_TYPE ,
DESCRIPTION,
"jobrunid" AS JOB_RUN_ID,
"GLOBALWARE" AS SOURCE_SYSTEM_CD,
CURRENT_DATE() AS CREATE_DT 
FROM LANDING.WORK_GW_REV_TYPES
)