SELECT DISTINCT 
TRIM(CONVERT(char,INVPAYID)) AS INVPAYID,
TRIM(CONVERT(char,LINENUM)) AS LINENUM,
TRIM(CONVERT(char,DATA)) AS DATA
FROM DBA.COMMENTS
WHERE INVPAYID IN (SELECT DISTINCT PAYID FROM DBA.INVCHANGELOG WHERE UPPER(TableName) = 'COMMENTS' AND CONVERT(DATE,ChangeDate) >= CONVERT(DATE,'v_startdate'))
OR INVPAYID > 'max_payid'
