SELECT 
TRIM(CONVERT(CHAR,Ctrl)) AS CTRL,
TRIM(CONVERT(CHAR,"Source")) AS GL_SOURCE,
TRIM(CONVERT(CHAR,PostDate,120)) AS POST_DT,
TRIM(CONVERT(CHAR,CashAcct)) AS CASH_ACCT,
TRIM(CONVERT(CHAR,"Comment")) AS GL_COMMENTS
FROM DBA.GLHeader
WHERE PostDate >= CONVERT(DATE,'v_startdate')