SELECT 
TRIM(CONVERT(CHAR,Ctrl  )) AS CTRL,
TRIM(CONVERT(CHAR,PostDate,120  )) AS POST_DT,
TRIM(CONVERT(CHAR,CashAccount)) AS CASH_ACCOUNT,
TRIM(CONVERT(CHAR,AccountId )) AS ACCOUNT_ID,
TRIM(CONVERT(CHAR,replace(replace("From", char(13), ''),char(10),''))) AS  CASH_RECIPETS_FROM        ,    
TRIM(CONVERT(CHAR,CheckNumber)) AS CHECK_NUM,
TRIM(CONVERT(CHAR,ReceiptNum)) AS RECIEPT_NUM,
TRIM(CONVERT(CHAR,Amount  )) AS AMT,
TRIM(CONVERT(CHAR,Applied)) AS APPLIED,
TRIM(CONVERT(CHAR,Branch)) AS BRANCH,
TRIM(CONVERT(CHAR,PrevBilled)) AS PREV_BILLED,
TRIM(CONVERT(CHAR,Type)) AS TYPE,
TRIM(CONVERT(CHAR,Remaining)) AS REMAINING,
TRIM(CONVERT(CHAR,InUseFlag)) AS IN_USE_FLG,
TRIM(CONVERT(CHAR,Status)) AS STATUS
FROM DBA.CashReceipts
WHERE PostDate >= CONVERT(DATE,'v_startdate')
