SELECT 
TRIM(CONVERT(CHAR,CCRAccountId)) AS CC_RACCOUNT_ID,
TRIM(CONVERT(CHAR,CCCompany)) AS CC_COMPANY,
TRIM(CONVERT(CHAR,CCNum)) AS CC_NUM,
TRIM(CONVERT(CHAR,CCName)) AS CC_NAME,
TRIM(CONVERT(CHAR,LastBillDate)) AS LAST_BILL_DT,
TRIM(CONVERT(CHAR,CCGenericCompany)) AS CC_GENERIC_COMPANY,
TRIM(CONVERT(CHAR,ID)) AS CCRAccountCC_ID
FROM DBA.CCRAccountCC
