INSERT INTO CUSTOMERS.TRAVEL_TRANSACTION_FACT(
TRAVELER_EMAIL,
TST_TRIP_ID,
INVENTORY_SUPPLIER,
SOURCE_SYSTEM_CD,
SOURCE_SYSTEM_ID,
MEMBERSHIP_NUM,
ASSOCIATE_ID,
CLUB_CD,
INVOICE_NUM,
INVOICE_DT,
SALE_TYPE_CD,
SALE_TYPE_DESC,
SALE_POSTED_AMOUNT,
TRAVEL_TYPE_CD,
TRAVEL_TYPE_DESC,
SALE_NUM,
BOOKING_AGENT_ID,
TICKETING_AGENT_ID,
SELLING_AGENT_ID,
NCNU_BRANCH_CD,
DEPARTURE_DT,
RETURN_DT,
BASE_FARE,
TOTAL_COST,
ANTICIPATED_COMMISSION_AMOUNT,
ANTICIPATED_SALE_AMOUNT,
DESTINATION_CITY,
PASSENGER_COUNT,
AIRLINE,
TICKET_NUM,
PROVIDER,
BOOKING_DT,
BOOKING_TYPE,
CHANGE_DT,
CANCELLATION_DT,
SALE_POSTING_DT,
STATUS_CD,
STATUS_CD_DESC,
PNR_LOCATOR,
MDM_CUSTOMER_KEY,
SETTLE_CD,
SETTLE_CD_DESC,
SOJOURN_CD,
CUSTOMER_TYPE_CD,
CUSTOMER_TYPE_DESC,
COMMISSION_PERCENT,
COMMISSION_AMOUNT,
REVENUE_TYPE_CD,
REVENUE_TYPE_DESC,
INVOICE_POSTED_FLAG,
PROMOTION_CD,
AUTO_TRAVEL_FLAG,
SOURCE_SYSTEM_BRANCH_CD,
STP,
DESTINATION_REGION,
ITINERARY,
RECORD_LOAD_DT,
RECORD_LOAD_ID) 
SELECT
COMMENTS.EMAIL TRAVELER_EMAIL,
NULL TST_TRIP_ID,
SAFE_CAST(NULL AS STRING) INVENTORY_SUPPLIER,
"GLOBALWARE" SOURCE_SYSTEM_CD,
INV.PAYID SOURCE_SYSTEM_ID,
CASE WHEN (SUBSTR(CAST(INV.PAYID AS STRING),1,6) = '438255' and LENGTH(CAST(INV.PAYID AS STRING)) > 12)
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),7,8)
	 WHEN (SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '255' and LENGTH (CAST(INV.PAYID AS STRING)) > 10)
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),4,8)
    WHEN LENGTH(CAST(INV.PAYID AS STRING)) = 8
	 THEN CAST(INV.PAYID AS STRING) 
	 WHEN LENGTH(CAST(INV.PAYID AS STRING)) = 9 
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),1,8)
	 WHEN SUBSTR(CAST(INV.PAYID AS STRING),1,6) = '005429' 
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),7,8)
	 WHEN (SUBSTR(CAST(INV.PAYID AS STRING),1,9) = '005429005' and (LENGTH(CAST(INV.PAYID AS STRING))=17 OR LENGTH(CAST(INV.PAYID AS STRING))=19))
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),10,8)
	 WHEN SUBSTR(CAST(INV.PAYID AS STRING),1,6) = '429005' 
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),7,8)
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 10 and (SUBSTR(CAST(INV.PAYID AS STRING),9,2)='14' OR SUBSTR(CAST(INV.PAYID AS STRING),9,2)='22') )
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),1,8)
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 11 and SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),4,8)
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 12 and SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '005') 
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),5,8)
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 13 and SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),6,8)
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 14 and SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),7,8)
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 15 and SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),8,8)
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) >= 15 and LENGTH(CAST(INV.PAYID AS STRING)) <= 16 and SUBSTR(CAST(INV.PAYID AS STRING),1,6) = '005005')
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),8,8)
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) > 16 and SUBSTR(CAST(INV.PAYID AS STRING),1,9) = '005005429')
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),11,8)
	 ELSE NULL
	 END MEMBERSHIP_NUM,
CASE WHEN (SUBSTR(CAST(INV.PAYID AS STRING),1,6) = '438255' and LENGTH(CAST(INV.PAYID AS STRING)) > 12)
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),15,1)
	 WHEN (SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '255' and LENGTH (CAST(INV.PAYID AS STRING)) > 10)
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),12,1)
    WHEN LENGTH(CAST(INV.PAYID AS STRING)) = 8
	 THEN '1'
	 WHEN LENGTH(CAST(INV.PAYID AS STRING)) = 9 
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),1,1)
	 WHEN SUBSTR(CAST(INV.PAYID AS STRING),1,6) = '005429' 
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),15,1)
	 WHEN (SUBSTR(CAST(INV.PAYID AS STRING),1,9) = '005429005' and (LENGTH(CAST(INV.PAYID AS STRING))=17 OR LENGTH(CAST(INV.PAYID AS STRING))=19))
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),18,1)
	 WHEN SUBSTR(CAST(INV.PAYID AS STRING),1,6) = '429005' 
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),15,1)
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 10 and (SUBSTR(CAST(INV.PAYID AS STRING),9,2)='14' OR SUBSTR(CAST(INV.PAYID AS STRING),9,2)='22') )
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),9,1)
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 11 and SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '005')
	 THEN '1'
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 12 and SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '005') 
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),4,1)
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 13 and SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),4,1)
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 14 and SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),4,1)
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 15 and SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INV.PAYID AS STRING),4,1)
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) >= 15 and LENGTH(CAST(INV.PAYID AS STRING)) <= 16 and SUBSTR(CAST(INV.PAYID AS STRING),1,6) = '005005')
	 THEN '1'
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) > 16 and SUBSTR(CAST(INV.PAYID AS STRING),1,9) = '005005429')
	 THEN '1'
	 ELSE NULL
	 END   ASSOCIATE_ID ,
CASE WHEN (SUBSTR(CAST(INV.PAYID AS STRING),1,6) = '438255' and LENGTH(CAST(INV.PAYID AS STRING)) > 12)
	 THEN '255'
	 WHEN (SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '255' and LENGTH (CAST(INV.PAYID AS STRING)) > 10)
	 THEN  '255'
    WHEN LENGTH(CAST(INV.PAYID AS STRING)) = 8
	 THEN '005'
	 WHEN LENGTH(CAST(INV.PAYID AS STRING)) = 9 
	 THEN '005'
	 WHEN SUBSTR(CAST(INV.PAYID AS STRING),1,6) = '005429' 
	 THEN '005'
	 WHEN (SUBSTR(CAST(INV.PAYID AS STRING),1,9) = '005429005' and (LENGTH(CAST(INV.PAYID AS STRING))=17 OR LENGTH(CAST(INV.PAYID AS STRING))=19))
	 THEN '005'
	 WHEN SUBSTR(CAST(INV.PAYID AS STRING),1,6) = '429005' 
	 THEN '005'
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 10 and (SUBSTR(CAST(INV.PAYID AS STRING),9,2)='14' OR SUBSTR(CAST(INV.PAYID AS STRING),9,2)='22') )
	 THEN '005'
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 11 and SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '005')
	 THEN '005'
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 12 and SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '005') 
	 THEN '005'
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 13 and SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '005')
	 THEN '005'
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 14 and SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '005')
	 THEN '005'
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) = 15 and SUBSTR(CAST(INV.PAYID AS STRING),1,3) = '005')
	 THEN '005'
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) >= 15 and LENGTH(CAST(INV.PAYID AS STRING)) <= 16 and SUBSTR(CAST(INV.PAYID AS STRING),1,6) = '005005')
	 THEN '005'
	 WHEN (LENGTH(CAST(INV.PAYID AS STRING)) > 16 and SUBSTR(CAST(INV.PAYID AS STRING),1,9) = '005005429')
	 THEN '005'
	 ELSE NULL
	 END CLUB_CD,
CAST(INVOICENUMBER AS INT64) AS INVOICE_NUM,
INVOICEDATE AS INVOICE_DT,
SALETYPE SALE_TYPE_CD,
(SELECT DESCRIPTION FROM LANDING.GLOBALWARE_CODES GW_CODE WHERE GW_CODE.CODE_VALUE=INV.SALETYPE AND GW_CODE.GLOBALWARE_COLUMN='SALETYPE' ) SALE_TYPE_DESC,
SALESPOSTEDAMOUNT SALE_POSTED_AMOUNT,
TRAVELTYPE TRAVEL_TYPE_CD,
(SELECT DESCRIPTION FROM LANDING.GLOBALWARE_CODES GW_CODE WHERE GW_CODE.CODE_VALUE=INV.TRAVELTYPE AND GW_CODE.GLOBALWARE_COLUMN='TRAVELTYPE' ) TRAVEL_TYPE_DESC,
CAST(SALENUM AS INT64) SALE_NUM,
BKAGT BOOKING_AGENT_ID, 
TKTAGT TICKETING_AGENT_ID,
SELLAGT SELLING_AGENT_ID,
CASE WHEN COMMENTS.AUTO_TRAVEL_FLAG ='T' THEN CAST(BRANCH.BRANCH AS STRING) ELSE SUBSTR(INV.BRANCH,2,3) END NCNU_BRANCH_CD,
INV.DEPARTDATE DEPARTURE_DT,
RETURNDATE RETURN_DT,
BASEFARE BASE_FARE,
TOTALCOST TOTAL_COST,
CAST(COMMENTS.ANTICIPATED_COMMISSION_AMOUNT AS FLOAT64) ANTICIPATED_COMMISSION_AMOUNT ,
CAST(COMMENTS.ANTICIPATED_SALE_AMOUNT AS FLOAT64) ANTICIPATED_SALE_AMOUNT,
DESTINATION DESTINATION_CITY ,
CAST(COMMENTS.PASSENGER_COUNT AS INT64) PASSENGER_COUNT,
INV.AIRLINE, 
INV.TICKETNUM TICKET_NUM,
INV.PROVIDER ,
INV.BOOKDATE BOOKING_DT,
COMMENTS.BOOKING_TYPE,
INV.CHANGEDATE CHANGE_DT,
CAST(COMMENTS.CANCELLATION_DT AS DATE) CANCELLATION_DT,
INV.SALESPOSTEDDATE SALE_POSTING_DT, 
STATUS AS STATUS_CD,
(SELECT DESCRIPTION FROM LANDING.GLOBALWARE_CODES GW_CODE WHERE GW_CODE.CODE_VALUE=INV.STATUS AND GW_CODE.GLOBALWARE_COLUMN='STATUS' ) STATUS_CD_DESC,
INV.PNRLOCATOR PNR_LOCATOR,
MDM.CUSTOMER_MDM_KEY MDM_CUSTOMER_KEY,
SETTLE AS SETTLE_CD, 
(SELECT DESCRIPTION FROM LANDING.GLOBALWARE_CODES GW_CODE WHERE GW_CODE.CODE_VALUE=INV.SETTLE AND GW_CODE.GLOBALWARE_COLUMN='SETTLETYPE' )  SETTLE_CD_DESC,
COMMENTS.SOJOURN_CD,
CUSTTYPE AS CUSTOMER_TYPE_CD,
(SELECT DESCRIPTION FROM LANDING.GLOBALWARE_CODES GW_CODE WHERE GW_CODE.CODE_VALUE=INV.CUSTTYPE AND GW_CODE.GLOBALWARE_COLUMN='CUSTTYPE' ) AS CUSTOMER_TYPE_DESC,
COMMPERCENT AS COMMISSION_PERCENT,
COMMAMOUNT AS COMMISSION_AMOUNT,
REVTYPE AS REVENUE_TYPE_CD,
(SELECT DESCRIPTION FROM LANDING.GLOBALWARE_CODES GW_CODE WHERE GW_CODE.CODE_VALUE=INV.REVTYPE AND GW_CODE.GLOBALWARE_COLUMN='REVTYPE' )  AS REVENUE_TYPE_DESC,
INV.INVOICEPOSTED AS INVOICE_POSTED_FLAG,
COMMENTS.PROMOTION_CD,
COMMENTS.AUTO_TRAVEL_FLAG,
INV.BRANCH SOURCE_SYSTEM_BRANCH_CD,
STP AS STP,
COMMENTS.DESTINATION_REGION,
ITINERARY AS ITINERARY,
CURRENT_DATE() RECORD_LOAD_DT,
CAST(ROW_NUMBER() OVER () AS STRING) RECORD_LOAD_ID
FROM 
LANDING.TRAVEL_INVOICE INV
LEFT JOIN CUSTOMERS.BRANCH_DIM BRANCH
ON INV.BRANCH =LPAD(BRANCH.BRANCH_NUMBER,1,'0')
LEFT JOIN (SELECT DISTINCT CUSTOMER_MDM_KEY, SOURCE_KEY1 FROM  CUSTOMERS.MDM_CUSTOMER_BRIDGE WHERE SOURCE_SYSTEM='COMMENTS') MDM
ON MDM.SOURCE_KEY1=INV.PAYID
LEFT JOIN (SELECT 
INVOICE_PAY_ID,
MAX(CASE WHEN LINE_NUM='28' THEN REPLACE(DATA,'//','@') ELSE NULL END) EMAIL,
MAX(CASE WHEN LINE_NUM='2' THEN DATA ELSE NULL END) ANTICIPATED_SALE_AMOUNT,
MAX(CASE WHEN LINE_NUM='82' THEN DATA ELSE NULL END )SOJOURN_CD,
MAX(CASE WHEN LINE_NUM='10' THEN DATA ELSE NULL END) ANTICIPATED_COMMISSION_AMOUNT,
MAX(CASE WHEN LINE_NUM='102' THEN DATA ELSE NULL END) DESTINATION_REGION,
MAX(CASE WHEN LINE_NUM='1' THEN DATA ELSE NULL END) PASSENGER_COUNT,
MAX(CASE WHEN LINE_NUM='31' THEN DATA ELSE NULL END) BOOKING_TYPE,
MAX(CASE WHEN LINE_NUM='30' THEN DATA ELSE NULL END) CANCELLATION_DT,
MAX(CASE WHEN LINE_NUM='8' THEN DATA ELSE NULL END) PROMOTION_CD,
MAX(CASE WHEN LINE_NUM='14' THEN DATA ELSE NULL END) AUTO_TRAVEL_FLAG
FROM 
LANDING.TRAVEL_COMMENTS
GROUP BY 1
) COMMENTS
ON INV.PAYID=COMMENTS.INVOICE_PAY_ID
Where  INV.PAYID  NOT IN ( SELECT SOURCE_SYSTEM_ID FROM CUSTOMERS.TRAVEL_TRANSACTION_FACT WHERE SOURCE_SYSTEM_CD = 'GLOBALWARE' )