CREATE OR REPLACE TABLE LANDING.WORK_TRAVEL_GLOBALWARE_TRANSACTIONS
 AS (SELECT DISTINCT 
INV.PAY_ID AS SOURCE_TRANSACTION_ID,
INVOICE_NUM AS TRIP_TRANSACTION_NUM,
INVOICE_DT AS TRANSACTION_DT,
MDM.CUSTOMER_MDM_KEY MDM_CUSTOMER_KEY,
CASE WHEN SUBSTR(COMMENTS.MEMBER_NUM,1,3)='005' THEN CONCAT('429', COMMENTS.MEMBER_NUM) ELSE NULL END AS MEMBER_NUM,
CASE WHEN (SUBSTR(CAST(INV.PAY_ID AS STRING),1,6) = '438255' and LENGTH(CAST(INV.PAY_ID AS STRING)) > 12)
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),7,8)
	 WHEN (SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '255' and LENGTH (CAST(INV.PAY_ID AS STRING)) > 10)
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),4,8)
    WHEN LENGTH(CAST(INV.PAY_ID AS STRING)) = 8
	 THEN CAST(INV.PAY_ID AS STRING) 
	 WHEN LENGTH(CAST(INV.PAY_ID AS STRING)) = 9 
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),1,8)
	 WHEN SUBSTR(CAST(INV.PAY_ID AS STRING),1,6) = '005429' 
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),7,8)
	 WHEN (SUBSTR(CAST(INV.PAY_ID AS STRING),1,9) = '005429005' and (LENGTH(CAST(INV.PAY_ID AS STRING))=17 OR LENGTH(CAST(INV.PAY_ID AS STRING))=19))
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),10,8)
	 WHEN SUBSTR(CAST(INV.PAY_ID AS STRING),1,6) = '429005' 
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),7,8)
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 10 and (SUBSTR(CAST(INV.PAY_ID AS STRING),9,2)='14' OR SUBSTR(CAST(INV.PAY_ID AS STRING),9,2)='22') )
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),1,8)
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 11 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),4,8)
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 12 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '005') 
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),5,8)
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 13 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),6,8)
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 14 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),7,8)
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 15 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),8,8)
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) >= 15 and LENGTH(CAST(INV.PAY_ID AS STRING)) <= 16 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,6) = '005005')
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),8,8)
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) > 16 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,9) = '005005429')
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),11,8)
	 ELSE NULL
	 END TRAVELER_MEMBERSHIP_NUM,
CASE WHEN (SUBSTR(CAST(INV.PAY_ID AS STRING),1,6) = '438255' and LENGTH(CAST(INV.PAY_ID AS STRING)) > 12)
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),15,1)
	 WHEN (SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '255' and LENGTH (CAST(INV.PAY_ID AS STRING)) > 10)
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),12,1)
    WHEN LENGTH(CAST(INV.PAY_ID AS STRING)) = 8
	 THEN '1'
	 WHEN LENGTH(CAST(INV.PAY_ID AS STRING)) = 9 
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),1,1)
	 WHEN SUBSTR(CAST(INV.PAY_ID AS STRING),1,6) = '005429' 
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),15,1)
	 WHEN (SUBSTR(CAST(INV.PAY_ID AS STRING),1,9) = '005429005' and (LENGTH(CAST(INV.PAY_ID AS STRING))=17 OR LENGTH(CAST(INV.PAY_ID AS STRING))=19))
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),18,1)
	 WHEN SUBSTR(CAST(INV.PAY_ID AS STRING),1,6) = '429005' 
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),15,1)
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 10 and (SUBSTR(CAST(INV.PAY_ID AS STRING),9,2)='14' OR SUBSTR(CAST(INV.PAY_ID AS STRING),9,2)='22') )
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),9,1)
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 11 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '005')
	 THEN '1'
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 12 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '005') 
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),4,1)
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 13 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),4,1)
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 14 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),4,1)
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 15 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(INV.PAY_ID AS STRING),4,1)
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) >= 15 and LENGTH(CAST(INV.PAY_ID AS STRING)) <= 16 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,6) = '005005')
	 THEN '1'
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) > 16 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,9) = '005005429')
	 THEN '1'
	 ELSE NULL
	 END   TRAVELER_ASSOCIATE_ID ,
CASE WHEN (SUBSTR(CAST(INV.PAY_ID AS STRING),1,6) = '438255' and LENGTH(CAST(INV.PAY_ID AS STRING)) > 12)
	 THEN '255'
	 WHEN (SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '255' and LENGTH (CAST(INV.PAY_ID AS STRING)) > 10)
	 THEN  '255'
    WHEN LENGTH(CAST(INV.PAY_ID AS STRING)) = 8
	 THEN '005'
	 WHEN LENGTH(CAST(INV.PAY_ID AS STRING)) = 9 
	 THEN '005'
	 WHEN SUBSTR(CAST(INV.PAY_ID AS STRING),1,6) = '005429' 
	 THEN '005'
	 WHEN (SUBSTR(CAST(INV.PAY_ID AS STRING),1,9) = '005429005' and (LENGTH(CAST(INV.PAY_ID AS STRING))=17 OR LENGTH(CAST(INV.PAY_ID AS STRING))=19))
	 THEN '005'
	 WHEN SUBSTR(CAST(INV.PAY_ID AS STRING),1,6) = '429005' 
	 THEN '005'
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 10 and (SUBSTR(CAST(INV.PAY_ID AS STRING),9,2)='14' OR SUBSTR(CAST(INV.PAY_ID AS STRING),9,2)='22') )
	 THEN '005'
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 11 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '005')
	 THEN '005'
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 12 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '005') 
	 THEN '005'
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 13 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '005')
	 THEN '005'
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 14 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '005')
	 THEN '005'
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) = 15 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,3) = '005')
	 THEN '005'
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) >= 15 and LENGTH(CAST(INV.PAY_ID AS STRING)) <= 16 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,6) = '005005')
	 THEN '005'
	 WHEN (LENGTH(CAST(INV.PAY_ID AS STRING)) > 16 and SUBSTR(CAST(INV.PAY_ID AS STRING),1,9) = '005005429')
	 THEN '005'
	 ELSE NULL
	 END CLUB_CD,
SALE_TYPE SALE_TYPE_CD,
(SELECT DISTINCT DESCRIPTION FROM LANDING.GLOBALWARE_CODES GW_CODE WHERE GW_CODE.CODE_VALUE=INV.SALE_TYPE AND GW_CODE.GLOBALWARE_COLUMN='SALETYPE' ) SALE_TYPE_DESC,
SALES_POSTED_AMOUNT SALE_POSTED_AMT,
TRAVEL_TYPE TRAVEL_TYPE_CD,
(SELECT DISTINCT DESCRIPTION FROM LANDING.GLOBALWARE_CODES GW_CODE WHERE GW_CODE.CODE_VALUE=INV.TRAVEL_TYPE AND GW_CODE.GLOBALWARE_COLUMN='TRAVELTYPE' ) TRAVEL_TYPE_DESC,
   SPLIT(COMMENTS.FIRST_NM, ' ')[safe_ordinal(1)] AS TRAVELER_FIRST_NAME,
   SPLIT(COMMENTS.FIRST_NM, ' ')[safe_ordinal(2)] AS TRAVELER_LAST_NAME,
   COMMENTS.TRAVELER_ADDRESS_LINE_1,
   COMMENTS.TRAVELER_ADDRESS_LINE_2,
   COMMENTS.TRAVELER_CITY,
   COMMENTS.TRAVELER_STATE,
   COMMENTS.TRAVELER_ZIP_CD,
   COMMENTS.TRAVELER_PHONE_NUM,  
   COMMENTS.EMAIL AS TRAVELER_EMAIL_ADDRESS, 
CAST(SALE_NUM AS INT64) SALE_NUM,
--SALE_NUM AS SALE_NUM,
INV.BOOK_DT BOOKING_DT,
COMMENTS.BOOKING_TYPE,
INV.DEPART_DT DEPARTURE_DT,
RETURN_DT RETURN_DT,
INV.CHANGE_DT CHANGE_DT,
--CAST(COMMENTS.CANCELLATION_DT AS DATE) CANCELLATION_DT,
COMMENTS.CANCELLATION_DT AS CANCELLATION_DT,
INV.SALES_POSTED_DT SALE_POSTING_DT, 
BKAGT BOOKING_AGENT_ID, 
ED1.EMPLOYEE_ID AS BOOKING_EMPLOYEE_ID, 
ED1.LOCATION_ID AS BOOKING_LOCATION_ID,
TKTAGT TICKETING_AGENT_ID,
ED2.EMPLOYEE_ID AS TICKETING_EMPLOYEE_ID,
ED2.LOCATION_ID AS TICKETING_LOCATION_ID,
SELLAGT SELLING_AGENT_ID,
ED2.EMPLOYEE_ID AS COMPENSATION_EMPLOYEE_ID, 
ED3.LOCATION_ID AS SELLING_LOCATION_ID,
TRIM(LZD.LOCATION_ID) AS REVENUE_LOCATION_ID, 
CASE WHEN COMMENTS.AUTO_TRAVEL_FLAG ='T' THEN LD1.LOCATION_ID ELSE SUBSTR(INV.BRANCH,2,3) END TRAVEL_LOCATION_ID,
BASEFARE BASE_FARE,
TOTAL_COST TOTAL_COST,
COMM_PERCENT AS COMMISSION_PERCENT,
COMM_AMOUNT AS COMMISSION_AMOUNT,
--CAST(COMMENTS.ANTICIPATED_SALE_AMOUNT AS FLOAT64) ANTICIPATED_SALE_AMOUNT,
COMMENTS.ANTICIPATED_SALE_AMOUNT AS ANTICIPATED_SALE_AMT,
--CAST(COMMENTS.ANTICIPATED_COMMISSION_AMOUNT AS FLOAT64) ANTICIPATED_COMMISSION_AMOUNT ,
COMMENTS.ANTICIPATED_COMMISSION_AMOUNT AS ANTICIPATED_COMMISSION_AMT,
DESTINATION DESTINATION_CITY ,
COMMENTS.DESTINATION_REGION,
--CAST(COMMENTS.PASSENGER_COUNT AS INT64) PASSENGER_COUNT,
COMMENTS.PASSENGER_COUNT AS PASSENGER_COUNT,
INV.AIRLINE, 
INV.TICKET_NUM TICKET_NUM,
ITINERARY AS ITINERARY,
INV.PROVIDER ,
STATUS AS STATUS_CD,
(SELECT DISTINCT DESCRIPTION FROM LANDING.GLOBALWARE_CODES GW_CODE WHERE GW_CODE.CODE_VALUE=INV.STATUS AND GW_CODE.GLOBALWARE_COLUMN='STATUS' ) STATUS_CD_DESC,
INV.PNR_LOCATOR PNR_LOCATOR,
SETTLE AS SETTLE_CD, 
(SELECT DISTINCT  DESCRIPTION FROM LANDING.GLOBALWARE_CODES GW_CODE WHERE GW_CODE.CODE_VALUE=INV.SETTLE AND GW_CODE.GLOBALWARE_COLUMN='SETTLETYPE' )  SETTLE_CD_DESC,
COMMENTS.SOJOURN_CD,
CUSTOMER_TYPE AS CUSTOMER_TYPE_CD,
(SELECT DISTINCT DESCRIPTION FROM LANDING.GLOBALWARE_CODES GW_CODE WHERE GW_CODE.CODE_VALUE=INV.CUSTOMER_TYPE AND GW_CODE.GLOBALWARE_COLUMN='CUSTTYPE' ) AS CUSTOMER_TYPE_DESC,
REV_TYPE AS REVENUE_TYPE_CD,
(SELECT DISTINCT DESCRIPTION FROM LANDING.GLOBALWARE_CODES GW_CODE WHERE GW_CODE.CODE_VALUE=INV.REV_TYPE AND GW_CODE.GLOBALWARE_COLUMN='REVTYPE' )  AS REVENUE_TYPE_DESC,
INV.INVOICE_POSTED AS INVOICE_POSTED_FLAG,
COMMENTS.PROMOTION_CD,
COMMENTS.AUTO_TRAVEL_FLAG,
INV.BRANCH SOURCE_SYSTEM_BRANCH_CD,
STP AS STP,
SAFE_CAST(NULL AS STRING) INVENTORY_SUPPLIER,


DOMINT AS DOMINT,
TAX1 AS TAX1,
TAX2 AS TAX2,
TAX3 AS TAX3,
TAX4 AS TAX4,
MISCCHARGE AS MISC_CHARGE,
DISCOUNT AS DISCOUNT,
EXCHANGE, 
FOP,


"GLOBALWARE" SOURCE_SYSTEM_CD,
CURRENT_DATETIME() CREATE_DTTIME
FROM OPERATIONAL.GLOBALWARE_INVOICE INV 
--LANDING.TRAVEL_INVOICE INV
LEFT JOIN (SELECT DISTINCT CUSTOMER_MDM_KEY, SOURCE_KEY1,SOURCE_KEY2 FROM  CUSTOMER_PRODUCT.MDM_CUSTOMER_BRIDGE WHERE SOURCE_SYSTEM_CD='TRAVEL_GLOBALWARE') MDM
ON MDM.SOURCE_KEY1=SAFE_CAST(INV.PAY_ID AS STRING)
AND MDM.SOURCE_KEY2=SAFE_CAST(INVOICE_NUM AS STRING)
LEFT JOIN (SELECT DISTINCT 
INVOICE_PAY_ID,
MAX(CASE WHEN LINE_NUM='28' THEN REPLACE(DATA,'//','@') ELSE NULL END) EMAIL,
MAX(CASE WHEN LINE_NUM='20' THEN REPLACE(DATA,'//','@') ELSE NULL END) FIRST_NM,
MAX(CASE WHEN LINE_NUM='9' THEN REPLACE(DATA,'//','@') ELSE NULL END) MEMBER_NUM,
MAX(CASE WHEN LINE_NUM='21' THEN REPLACE(DATA,'//','@') ELSE NULL END) TRAVELER_ADDRESS_LINE_1,
MAX(CASE WHEN LINE_NUM='22' THEN REPLACE(DATA,'//','@') ELSE NULL END) TRAVELER_ADDRESS_LINE_2,
MAX(CASE WHEN LINE_NUM='23' THEN REPLACE(DATA,'//','@') ELSE NULL END) TRAVELER_CITY,
MAX(CASE WHEN LINE_NUM='27' THEN REPLACE(DATA,'//','@') ELSE NULL END) TRAVELER_STATE,
MAX(CASE WHEN LINE_NUM='24' THEN REPLACE(DATA,'//','@') ELSE NULL END) TRAVELER_ZIP_CD,
MAX(CASE WHEN LINE_NUM='25' THEN REPLACE(DATA,'//','@') ELSE NULL END) TRAVELER_PHONE_NUM,   
MAX(CASE WHEN LINE_NUM='2' THEN DATA ELSE NULL END) ANTICIPATED_SALE_AMOUNT,
MAX(CASE WHEN LINE_NUM='82' THEN DATA ELSE NULL END )SOJOURN_CD,
MAX(CASE WHEN LINE_NUM='10' THEN DATA ELSE NULL END) ANTICIPATED_COMMISSION_AMOUNT,
MAX(CASE WHEN LINE_NUM='102' THEN DATA ELSE NULL END) DESTINATION_REGION,
MAX(CASE WHEN LINE_NUM='1' THEN DATA ELSE NULL END) PASSENGER_COUNT,
MAX(CASE WHEN LINE_NUM='31' THEN DATA ELSE NULL END) BOOKING_TYPE,
MAX(CASE WHEN LINE_NUM='30' THEN DATA ELSE NULL END) CANCELLATION_DT,
MAX(CASE WHEN LINE_NUM='8' THEN DATA ELSE NULL END) PROMOTION_CD,
MAX(CASE WHEN LINE_NUM='14' THEN DATA ELSE NULL END) AUTO_TRAVEL_FLAG
FROM OPERATIONAL.GLOBALWARE_COMMENTS
--LANDING.TRAVEL_COMMENTS
GROUP BY 1
) COMMENTS ON INV.PAY_ID=COMMENTS.INVOICE_PAY_ID
LEFT OUTER JOIN CUSTOMER_PRODUCT.EMPLOYEE_DIM ED1 ON  TRIM(INV.BKAGT) = ED1.TRAVEL_ID AND INV.BOOK_DT BETWEEN ED1.ROW_START_DT  AND ED1.ROW_END_DT
LEFT OUTER JOIN CUSTOMER_PRODUCT.EMPLOYEE_DIM ED2 ON  TRIM(INV.TKTAGT) = ED2.TRAVEL_ID AND INV.BOOK_DT BETWEEN ED2.ROW_START_DT  AND ED2.ROW_END_DT
LEFT OUTER JOIN CUSTOMER_PRODUCT.EMPLOYEE_DIM ED3 ON  TRIM(INV.SELLAGT) = ED3.TRAVEL_ID AND INV.BOOK_DT BETWEEN ED3.ROW_START_DT  AND ED3.ROW_END_DT
LEFT OUTER JOIN CUSTOMER_PRODUCT.LOCATION_ZIP_DIM LZD ON TRIM(COMMENTS.TRAVELER_ZIP_CD) = LZD.ZIP_CD
LEFT OUTER JOIN CUSTOMER_PRODUCT.LOCATION_DIM LD1 ON LD1.LOCATION_ID = LPAD(INV.BRANCH,3,'0') AND LD1.ACTIVE_FLG = 'Y'
WHERE INV.PAY_ID NOT IN ( SELECT SOURCE_TRANSACTION_ID  FROM CUSTOMERS.TRAVEL_TRANSACTION_FACT WHERE SOURCE_SYSTEM_CD = 'GLOBALWARE' ))
