MERGE `OPERATIONAL.AMS_CONTACT_ADDRESS` AS TGT
USING `LANDING.WORK_AMS_CONTACT_ADDRESS` AS SRC
ON TGT.UNIQUE_CONTACT_ADDRESS = SAFE_CAST(SRC.UNIQCONTACTADDRESS AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_CONTACT_ADDRESS = SAFE_CAST(SRC.UNIQCONTACTADDRESS AS INT64)
,TGT.UNIQUE_FIXED_CONTACT_ADDRESS = SAFE_CAST(SRC.UNIQFIXEDCONTACTADDRESS AS INT64)
,TGT.UNIQUE_ENTITY = SAFE_CAST(SRC.UNIQENTITY AS INT64)
,TGT.DESC_OF = SAFE_CAST(SRC.DESCRIPTIONOF AS STRING)
,TGT.ADDRESS_1 = SAFE_CAST(SRC.ADDRESS1 AS STRING)
,TGT.ADDRESS_2 = SAFE_CAST(SRC.ADDRESS2 AS STRING)
,TGT.ADDRESS_3 = SAFE_CAST(SRC.ADDRESS3 AS STRING)
,TGT.CITY = SAFE_CAST(SRC.CITY AS STRING)
,TGT.CD_STATE_CD = SAFE_CAST(SRC.CDSTATECODE AS STRING)
,TGT.POSTAL_CD = SAFE_CAST(SRC.POSTALCODE AS STRING)
,TGT.COUNTY = SAFE_CAST(SRC.COUNTY AS STRING)
,TGT.CD_COUNTRY_CD = SAFE_CAST(SRC.CDCOUNTRYCODE AS STRING)
,TGT.INSERTED_BY_CD = SAFE_CAST(SRC.INSERTEDBYCODE AS STRING)
,TGT.INSERTED_DT = SAFE_CAST(SRC.INSERTEDDATE AS DATETIME)
,TGT.UPDATED_BY_CD = SAFE_CAST(SRC.UPDATEDBYCODE AS STRING)
,TGT.UPDATED_DT = SAFE_CAST(SRC.UPDATEDDATE AS DATETIME)
,TGT.FLGS = SAFE_CAST(SRC.FLAGS AS INT64)
,TGT.SITE_ID = SAFE_CAST(SRC.SITEID AS STRING)
,TGT.REGION_PROVINCE = SAFE_CAST(SRC.REGIONPROVINCE AS STRING)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_CONTACT_ADDRESS
,UNIQUE_FIXED_CONTACT_ADDRESS
,UNIQUE_ENTITY
,DESC_OF
,ADDRESS_1
,ADDRESS_2
,ADDRESS_3
,CITY
,CD_STATE_CD
,POSTAL_CD
,COUNTY
,CD_COUNTRY_CD
,INSERTED_BY_CD
,INSERTED_DT
,UPDATED_BY_CD
,UPDATED_DT
,FLGS
,SITE_ID
,REGION_PROVINCE
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQCONTACTADDRESS AS INT64)
,SAFE_CAST(UNIQFIXEDCONTACTADDRESS AS INT64)
,SAFE_CAST(UNIQENTITY AS INT64)
,SAFE_CAST(DESCRIPTIONOF AS STRING)
,SAFE_CAST(ADDRESS1 AS STRING)
,SAFE_CAST(ADDRESS2 AS STRING)
,SAFE_CAST(ADDRESS3 AS STRING)
,SAFE_CAST(CITY AS STRING)
,SAFE_CAST(CDSTATECODE AS STRING)
,SAFE_CAST(POSTALCODE AS STRING)
,SAFE_CAST(COUNTY AS STRING)
,SAFE_CAST(CDCOUNTRYCODE AS STRING)
,SAFE_CAST(INSERTEDBYCODE AS STRING)
,SAFE_CAST(INSERTEDDATE AS DATETIME)
,SAFE_CAST(UPDATEDBYCODE AS STRING)
,SAFE_CAST(UPDATEDDATE AS DATETIME)
,SAFE_CAST(FLAGS AS INT64)
,SAFE_CAST(SITEID AS STRING)
,SAFE_CAST(REGIONPROVINCE AS STRING)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
