MERGE `OPERATIONAL.AMS_LINE` AS TGT
USING `LANDING.WORK_AMS_LINE` AS SRC
ON TGT.UNIQUE_LINE = SAFE_CAST(SRC.UNIQLINE AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_LINE = SAFE_CAST(SRC.UNIQLINE AS INT64)
,TGT.UNIQUE_POLICY = SAFE_CAST(SRC.UNIQPOLICY AS INT64)
,TGT.UNIQUE_ENTITY = SAFE_CAST(SRC.UNIQENTITY AS INT64)
,TGT.UNIQUE_PROFIT_CENTER = SAFE_CAST(SRC.UNIQPROFITCENTER AS INT64)
,TGT.UNIQUE_CD_POLICY_LINE_TYPE = SAFE_CAST(SRC.UNIQCDPOLICYLINETYPE AS INT64)
,TGT.UNIQUE_FORM_CATEGORY = SAFE_CAST(SRC.UNIQFORMCATEGORY AS INT64)
,TGT.UNIQUE_FORM_EDITION = SAFE_CAST(SRC.UNIQFORMEDITION AS INT64)
,TGT.UNIQUE_FORM_EDITION_GROUP = SAFE_CAST(SRC.UNIQFORMEDITIONGROUP AS INT64)
,TGT.FORM_EDITION_DT = SAFE_CAST(SRC.FORMEDITIONDATE AS STRING)
,TGT.UNIQUE_CD_LINE_STATUS = SAFE_CAST(SRC.UNIQCDLINESTATUS AS INT64)
,TGT.UNIQUE_PREFILL = SAFE_CAST(SRC.UNIQPREFILL AS INT64)
,TGT.BILL_MODE_CD = SAFE_CAST(SRC.BILLMODECODE AS STRING)
,TGT.LK_LINE_BILLING_PLAN = SAFE_CAST(SRC.LKLINEBILLINGPLAN AS STRING)
,TGT.ENTITY_KEY_BILL_TO = SAFE_CAST(SRC.ENTITYKEYBILLTO AS STRING)
,TGT.UNIQUE_ENTITY_BILL_TO = SAFE_CAST(SRC.UNIQENTITYBILLTO AS INT64)
,TGT.UNIQUE_CONTACT_NAME_BILL_TO = SAFE_CAST(SRC.UNIQCONTACTNAMEBILLTO AS INT64)
,TGT.CONTACT_NAME_BILL_TO = SAFE_CAST(SRC.CONTACTNAMEBILLTO AS STRING)
,TGT.UNIQUE_CONTACT_ADDRESS_BILL_TO = SAFE_CAST(SRC.UNIQCONTACTADDRESSBILLTO AS INT64)
,TGT.ADDRESS_1_BILL_TO = SAFE_CAST(SRC.ADDRESS1BILLTO AS STRING)
,TGT.ADDRESS_2_BILL_TO = SAFE_CAST(SRC.ADDRESS2BILLTO AS STRING)
,TGT.ADDRESS_3_BILL_TO = SAFE_CAST(SRC.ADDRESS3BILLTO AS STRING)
,TGT.CITY_BILL_TO = SAFE_CAST(SRC.CITYBILLTO AS STRING)
,TGT.CD_STATE_CD_BILL_TO = SAFE_CAST(SRC.CDSTATECODEBILLTO AS STRING)
,TGT.POSTAL_CD_BILL_TO = SAFE_CAST(SRC.POSTALCODEBILLTO AS STRING)
,TGT.COUNTY_BILL_TO = SAFE_CAST(SRC.COUNTYBILLTO AS STRING)
,TGT.CD_COUNTRY_CD_BILL_TO = SAFE_CAST(SRC.CDCOUNTRYCODEBILLTO AS STRING)
,TGT.DELIVERY_METHOD_CD = SAFE_CAST(SRC.DELIVERYMETHODCODE AS STRING)
,TGT.EMAIL = SAFE_CAST(SRC.EMAIL AS STRING)
,TGT.FAX = SAFE_CAST(SRC.FAX AS STRING)
,TGT.FAX_EXTENSION = SAFE_CAST(SRC.FAXEXTENSION AS STRING)
,TGT.LOAN_NUM = SAFE_CAST(SRC.LOANNUMBER AS STRING)
,TGT.CD_CURRENCY_CD = SAFE_CAST(SRC.CDCURRENCYCODE AS STRING)
,TGT.UNIQUE_ENTITY_COMPANY_BILLING = SAFE_CAST(SRC.UNIQENTITYCOMPANYBILLING AS INT64)
,TGT.UNIQUE_ENTITY_COMPANY_ISSUING = SAFE_CAST(SRC.UNIQENTITYCOMPANYISSUING AS INT64)
,TGT.UNIQUE_ENTITY_COMPANY_ISSUING_MASTER = SAFE_CAST(SRC.UNIQENTITYCOMPANYISSUINGMASTER AS INT64)
,TGT.FIRST_WRITTEN_DT = SAFE_CAST(SRC.FIRSTWRITTENDATE AS DATETIME)
,TGT.EFFECTIVE_DT = SAFE_CAST(SRC.EFFECTIVEDATE AS DATETIME)
,TGT.EXPIRATION_DT = SAFE_CAST(SRC.EXPIRATIONDATE AS DATETIME)
,TGT.UNIQUE_COMMISSION_AGREEMENT = SAFE_CAST(SRC.UNIQCOMMISSIONAGREEMENT AS INT64)
,TGT.COMMISSION_TYPE_CD = SAFE_CAST(SRC.COMMISSIONTYPECODE AS STRING)
,TGT.COMMISSION_PERCENT = SAFE_CAST(SRC.COMMISSIONPERCENT AS FLOAT64)
,TGT.COMMISSION = SAFE_CAST(SRC.COMMISSION AS FLOAT64)
,TGT.CD_STATE_CD_ISSUING = SAFE_CAST(SRC.CDSTATECODEISSUING AS STRING)
,TGT.CD_COUNTRY_CD_ISSUING = SAFE_CAST(SRC.CDCOUNTRYCODEISSUING AS STRING)
,TGT.ESTIMATED_PREMIUM = SAFE_CAST(SRC.ESTIMATEDPREMIUM AS FLOAT64)
,TGT.ESTIMATED_COMMISSION = SAFE_CAST(SRC.ESTIMATEDCOMMISSION AS FLOAT64)
,TGT.BILLED_PREMIUM = SAFE_CAST(SRC.BILLEDPREMIUM AS FLOAT64)
,TGT.BILLED_COMMISSION = SAFE_CAST(SRC.BILLEDCOMMISSION AS FLOAT64)
,TGT.ANNUALIZED_PREMIUM = SAFE_CAST(SRC.ANNUALIZEDPREMIUM AS FLOAT64)
,TGT.ANNUALIZED_COMMISSION = SAFE_CAST(SRC.ANNUALIZEDCOMMISSION AS FLOAT64)
,TGT.COMMENTS = SAFE_CAST(SRC.COMMENTS AS STRING)
,TGT.INSERTED_BY_CD = SAFE_CAST(SRC.INSERTEDBYCODE AS STRING)
,TGT.INSERTED_DT = SAFE_CAST(SRC.INSERTEDDATE AS DATETIME)
,TGT.UPDATED_BY_CD = SAFE_CAST(SRC.UPDATEDBYCODE AS STRING)
,TGT.UPDATED_DT = SAFE_CAST(SRC.UPDATEDDATE AS DATETIME)
,TGT.FLGS = SAFE_CAST(SRC.FLAGS AS INT64)
,TGT.TS = SAFE_CAST(SRC.TS AS DATETIME)
,TGT.ADDRESS_DESC = SAFE_CAST(SRC.ADDRESSDESCRIPTION AS STRING)
,TGT.SITE_ID = SAFE_CAST(SRC.SITEID AS STRING)
,TGT.PPE_TYPE_CD = SAFE_CAST(SRC.PPETYPECODE AS STRING)
,TGT.UNIQUE_ENTITY_BROKER_BILLING = SAFE_CAST(SRC.UNIQENTITYBROKERBILLING AS INT64)
,TGT.UNIQUE_CONTACT_NUM_FAX = SAFE_CAST(SRC.UNIQCONTACTNUMBERFAX AS INT64)
,TGT.UNIQUE_CONTACT_NUM_EMAIL = SAFE_CAST(SRC.UNIQCONTACTNUMBEREMAIL AS INT64)
,TGT.LAST_DOWNLOADED_PREMIUM = SAFE_CAST(SRC.LASTDOWNLOADEDPREMIUM AS FLOAT64)
,TGT.UNIQUE_COMPANY_CONTRACT = SAFE_CAST(SRC.UNIQCOMPANYCONTRACT AS INT64)
,TGT.FAX_PHONE_COUNTRY_CD = SAFE_CAST(SRC.FAXPHONECOUNTRYCODE AS STRING)
,TGT.BILL_TO_REGION_PROVINCE = SAFE_CAST(SRC.BILLTOREGIONPROVINCE AS STRING)
,TGT.LINE_ID_NUM = SAFE_CAST(SRC.LINEIDNUMBER AS STRING)
,TGT.RISKS_INSURED = SAFE_CAST(SRC.RISKSINSURED AS INT64)
,TGT.RISKS_DESC = SAFE_CAST(SRC.RISKSDESCRIPTION AS STRING)
,TGT.ELIGIBLE_TOTAL = SAFE_CAST(SRC.ELIGIBLETOTAL AS INT64)
,TGT.ELIGIBLE_DESC = SAFE_CAST(SRC.ELIGIBLEDESCRIPTION AS STRING)
,TGT.ESTIMATED_MONTHLY_PREMIUM = SAFE_CAST(SRC.ESTIMATEDMONTHLYPREMIUM AS FLOAT64)
,TGT.ESTIMATED_MONTHLY_PREMIUM_DT = SAFE_CAST(SRC.ESTIMATEDMONTHLYPREMIUMDATE AS DATETIME)
,TGT.ESTIMATED_MONTHLY_COMMISSION = SAFE_CAST(SRC.ESTIMATEDMONTHLYCOMMISSION AS FLOAT64)
,TGT.UNIQUE_COPY_LINE = SAFE_CAST(SRC.UNIQCOPYLINE AS INT64)
,TGT.MIGRATED_BILLED_PREMIUM = SAFE_CAST(SRC.MIGRATEDBILLEDPREMIUM AS FLOAT64)
,TGT.MIGRATED_BILLED_COMMISSION = SAFE_CAST(SRC.MIGRATEDBILLEDCOMMISSION AS FLOAT64)
,TGT.TAX_OPTION = SAFE_CAST(SRC.TAXOPTION AS STRING)
,TGT.LINE_ID = SAFE_CAST(SRC.LINEID AS STRING)
,TGT.UNIQUE_CD_LINE_STATUS_PRIOR = SAFE_CAST(SRC.UNIQCDLINESTATUSPRIOR AS INT64)
,TGT.CARRIER_QUOTE_NUM = SAFE_CAST(SRC.CARRIERQUOTENUMBER AS STRING)
,TGT.UNIQUE_ADD_ON_MANAGEMENT = SAFE_CAST(SRC.UNIQADDONMANAGEMENT AS INT64)
,TGT.RATING_COMPANY_ID = SAFE_CAST(SRC.RATINGCOMPANYID AS STRING)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_LINE
,UNIQUE_POLICY
,UNIQUE_ENTITY
,UNIQUE_PROFIT_CENTER
,UNIQUE_CD_POLICY_LINE_TYPE
,UNIQUE_FORM_CATEGORY
,UNIQUE_FORM_EDITION
,UNIQUE_FORM_EDITION_GROUP
,FORM_EDITION_DT
,UNIQUE_CD_LINE_STATUS
,UNIQUE_PREFILL
,BILL_MODE_CD
,LK_LINE_BILLING_PLAN
,ENTITY_KEY_BILL_TO
,UNIQUE_ENTITY_BILL_TO
,UNIQUE_CONTACT_NAME_BILL_TO
,CONTACT_NAME_BILL_TO
,UNIQUE_CONTACT_ADDRESS_BILL_TO
,ADDRESS_1_BILL_TO
,ADDRESS_2_BILL_TO
,ADDRESS_3_BILL_TO
,CITY_BILL_TO
,CD_STATE_CD_BILL_TO
,POSTAL_CD_BILL_TO
,COUNTY_BILL_TO
,CD_COUNTRY_CD_BILL_TO
,DELIVERY_METHOD_CD
,EMAIL
,FAX
,FAX_EXTENSION
,LOAN_NUM
,CD_CURRENCY_CD
,UNIQUE_ENTITY_COMPANY_BILLING
,UNIQUE_ENTITY_COMPANY_ISSUING
,UNIQUE_ENTITY_COMPANY_ISSUING_MASTER
,FIRST_WRITTEN_DT
,EFFECTIVE_DT
,EXPIRATION_DT
,UNIQUE_COMMISSION_AGREEMENT
,COMMISSION_TYPE_CD
,COMMISSION_PERCENT
,COMMISSION
,CD_STATE_CD_ISSUING
,CD_COUNTRY_CD_ISSUING
,ESTIMATED_PREMIUM
,ESTIMATED_COMMISSION
,BILLED_PREMIUM
,BILLED_COMMISSION
,ANNUALIZED_PREMIUM
,ANNUALIZED_COMMISSION
,COMMENTS
,INSERTED_BY_CD
,INSERTED_DT
,UPDATED_BY_CD
,UPDATED_DT
,FLGS
,TS
,ADDRESS_DESC
,SITE_ID
,PPE_TYPE_CD
,UNIQUE_ENTITY_BROKER_BILLING
,UNIQUE_CONTACT_NUM_FAX
,UNIQUE_CONTACT_NUM_EMAIL
,LAST_DOWNLOADED_PREMIUM
,UNIQUE_COMPANY_CONTRACT
,FAX_PHONE_COUNTRY_CD
,BILL_TO_REGION_PROVINCE
,LINE_ID_NUM
,RISKS_INSURED
,RISKS_DESC
,ELIGIBLE_TOTAL
,ELIGIBLE_DESC
,ESTIMATED_MONTHLY_PREMIUM
,ESTIMATED_MONTHLY_PREMIUM_DT
,ESTIMATED_MONTHLY_COMMISSION
,UNIQUE_COPY_LINE
,MIGRATED_BILLED_PREMIUM
,MIGRATED_BILLED_COMMISSION
,TAX_OPTION
,LINE_ID
,UNIQUE_CD_LINE_STATUS_PRIOR
,CARRIER_QUOTE_NUM
,UNIQUE_ADD_ON_MANAGEMENT
,RATING_COMPANY_ID
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQLINE AS INT64)
,SAFE_CAST(UNIQPOLICY AS INT64)
,SAFE_CAST(UNIQENTITY AS INT64)
,SAFE_CAST(UNIQPROFITCENTER AS INT64)
,SAFE_CAST(UNIQCDPOLICYLINETYPE AS INT64)
,SAFE_CAST(UNIQFORMCATEGORY AS INT64)
,SAFE_CAST(UNIQFORMEDITION AS INT64)
,SAFE_CAST(UNIQFORMEDITIONGROUP AS INT64)
,SAFE_CAST(FORMEDITIONDATE AS STRING)
,SAFE_CAST(UNIQCDLINESTATUS AS INT64)
,SAFE_CAST(UNIQPREFILL AS INT64)
,SAFE_CAST(BILLMODECODE AS STRING)
,SAFE_CAST(LKLINEBILLINGPLAN AS STRING)
,SAFE_CAST(ENTITYKEYBILLTO AS STRING)
,SAFE_CAST(UNIQENTITYBILLTO AS INT64)
,SAFE_CAST(UNIQCONTACTNAMEBILLTO AS INT64)
,SAFE_CAST(CONTACTNAMEBILLTO AS STRING)
,SAFE_CAST(UNIQCONTACTADDRESSBILLTO AS INT64)
,SAFE_CAST(ADDRESS1BILLTO AS STRING)
,SAFE_CAST(ADDRESS2BILLTO AS STRING)
,SAFE_CAST(ADDRESS3BILLTO AS STRING)
,SAFE_CAST(CITYBILLTO AS STRING)
,SAFE_CAST(CDSTATECODEBILLTO AS STRING)
,SAFE_CAST(POSTALCODEBILLTO AS STRING)
,SAFE_CAST(COUNTYBILLTO AS STRING)
,SAFE_CAST(CDCOUNTRYCODEBILLTO AS STRING)
,SAFE_CAST(DELIVERYMETHODCODE AS STRING)
,SAFE_CAST(EMAIL AS STRING)
,SAFE_CAST(FAX AS STRING)
,SAFE_CAST(FAXEXTENSION AS STRING)
,SAFE_CAST(LOANNUMBER AS STRING)
,SAFE_CAST(CDCURRENCYCODE AS STRING)
,SAFE_CAST(UNIQENTITYCOMPANYBILLING AS INT64)
,SAFE_CAST(UNIQENTITYCOMPANYISSUING AS INT64)
,SAFE_CAST(UNIQENTITYCOMPANYISSUINGMASTER AS INT64)
,SAFE_CAST(FIRSTWRITTENDATE AS DATETIME)
,SAFE_CAST(EFFECTIVEDATE AS DATETIME)
,SAFE_CAST(EXPIRATIONDATE AS DATETIME)
,SAFE_CAST(UNIQCOMMISSIONAGREEMENT AS INT64)
,SAFE_CAST(COMMISSIONTYPECODE AS STRING)
,SAFE_CAST(COMMISSIONPERCENT AS FLOAT64)
,SAFE_CAST(COMMISSION AS FLOAT64)
,SAFE_CAST(CDSTATECODEISSUING AS STRING)
,SAFE_CAST(CDCOUNTRYCODEISSUING AS STRING)
,SAFE_CAST(ESTIMATEDPREMIUM AS FLOAT64)
,SAFE_CAST(ESTIMATEDCOMMISSION AS FLOAT64)
,SAFE_CAST(BILLEDPREMIUM AS FLOAT64)
,SAFE_CAST(BILLEDCOMMISSION AS FLOAT64)
,SAFE_CAST(ANNUALIZEDPREMIUM AS FLOAT64)
,SAFE_CAST(ANNUALIZEDCOMMISSION AS FLOAT64)
,SAFE_CAST(COMMENTS AS STRING)
,SAFE_CAST(INSERTEDBYCODE AS STRING)
,SAFE_CAST(INSERTEDDATE AS DATETIME)
,SAFE_CAST(UPDATEDBYCODE AS STRING)
,SAFE_CAST(UPDATEDDATE AS DATETIME)
,SAFE_CAST(FLAGS AS INT64)
,SAFE_CAST(TS AS DATETIME)
,SAFE_CAST(ADDRESSDESCRIPTION AS STRING)
,SAFE_CAST(SITEID AS STRING)
,SAFE_CAST(PPETYPECODE AS STRING)
,SAFE_CAST(UNIQENTITYBROKERBILLING AS INT64)
,SAFE_CAST(UNIQCONTACTNUMBERFAX AS INT64)
,SAFE_CAST(UNIQCONTACTNUMBEREMAIL AS INT64)
,SAFE_CAST(LASTDOWNLOADEDPREMIUM AS FLOAT64)
,SAFE_CAST(UNIQCOMPANYCONTRACT AS INT64)
,SAFE_CAST(FAXPHONECOUNTRYCODE AS STRING)
,SAFE_CAST(BILLTOREGIONPROVINCE AS STRING)
,SAFE_CAST(LINEIDNUMBER AS STRING)
,SAFE_CAST(RISKSINSURED AS INT64)
,SAFE_CAST(RISKSDESCRIPTION AS STRING)
,SAFE_CAST(ELIGIBLETOTAL AS INT64)
,SAFE_CAST(ELIGIBLEDESCRIPTION AS STRING)
,SAFE_CAST(ESTIMATEDMONTHLYPREMIUM AS FLOAT64)
,SAFE_CAST(ESTIMATEDMONTHLYPREMIUMDATE AS DATETIME)
,SAFE_CAST(ESTIMATEDMONTHLYCOMMISSION AS FLOAT64)
,SAFE_CAST(UNIQCOPYLINE AS INT64)
,SAFE_CAST(MIGRATEDBILLEDPREMIUM AS FLOAT64)
,SAFE_CAST(MIGRATEDBILLEDCOMMISSION AS FLOAT64)
,SAFE_CAST(TAXOPTION AS STRING)
,SAFE_CAST(LINEID AS STRING)
,SAFE_CAST(UNIQCDLINESTATUSPRIOR AS INT64)
,SAFE_CAST(CARRIERQUOTENUMBER AS STRING)
,SAFE_CAST(UNIQADDONMANAGEMENT AS INT64)
,SAFE_CAST(RATINGCOMPANYID AS STRING)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
