MERGE `OPERATIONAL.AMS_TRANS_HEAD` AS TGT
USING `LANDING.WORK_AMS_TRANS_HEAD` AS SRC
ON TGT.UNIQUE_TRANS_HEAD = SAFE_CAST(SRC.UNIQTRANSHEAD AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_TRANS_HEAD = SAFE_CAST(SRC.UNIQTRANSHEAD AS INT64)
,TGT.ITEM_NUM = SAFE_CAST(SRC.ITEMNUMBER AS STRING)
,TGT.CD = SAFE_CAST(SRC.CODE AS STRING)
,TGT.BILL_MODE_CD = SAFE_CAST(SRC.BILLMODECODE AS STRING)
,TGT.ENTITY_KEY = SAFE_CAST(SRC.ENTITYKEY AS STRING)
,TGT.UNIQUE_ENTITY = SAFE_CAST(SRC.UNIQENTITY AS INT64)
,TGT.ENTITY_KEY_BILL_TO = SAFE_CAST(SRC.ENTITYKEYBILLTO AS STRING)
,TGT.UNIQUE_ENTITY_BILL_TO = SAFE_CAST(SRC.UNIQENTITYBILLTO AS INT64)
,TGT.UNIQUE_POLICY = SAFE_CAST(SRC.UNIQPOLICY AS INT64)
,TGT.UNIQUE_TRANS_HEAD_REVERSAL = SAFE_CAST(SRC.UNIQTRANSHEADREVERSAL AS INT64)
,TGT.REVERSE_REASON = SAFE_CAST(SRC.REVERSEREASON AS STRING)
,TGT.INVOICE_NUM = SAFE_CAST(SRC.INVOICENUMBER AS INT64)
,TGT.INVOICE_BATCH_NUM = SAFE_CAST(SRC.INVOICEBATCHNUMBER AS INT64)
,TGT.PRINTED_DT = SAFE_CAST(SRC.PRINTEDDATE AS DATETIME)
,TGT.UNIQUE_AGENCY = SAFE_CAST(SRC.UNIQAGENCY AS INT64)
,TGT.UNIQUE_BRANCH = SAFE_CAST(SRC.UNIQBRANCH AS INT64)
,TGT.UNIQUE_DEPARTMENT = SAFE_CAST(SRC.UNIQDEPARTMENT AS INT64)
,TGT.UNIQUE_PROFIT_CENTER = SAFE_CAST(SRC.UNIQPROFITCENTER AS INT64)
,TGT.UNIQUE_GL_ACCOUNT = SAFE_CAST(SRC.UNIQGLACCOUNT AS INT64)
,TGT.EFFECTIVE_DT = SAFE_CAST(SRC.EFFECTIVEDATE AS DATETIME)
,TGT.UNIQUE_CONTACT_NAME = SAFE_CAST(SRC.UNIQCONTACTNAME AS INT64)
,TGT.UNIQUE_CONTACT_ADDRESS = SAFE_CAST(SRC.UNIQCONTACTADDRESS AS INT64)
,TGT.CONTACT_NAME_BILL_TO = SAFE_CAST(SRC.CONTACTNAMEBILLTO AS STRING)
,TGT.ADDRESS_1_BILL_TO = SAFE_CAST(SRC.ADDRESS1BILLTO AS STRING)
,TGT.ADDRESS_2_BILL_TO = SAFE_CAST(SRC.ADDRESS2BILLTO AS STRING)
,TGT.ADDRESS_3_BILL_TO = SAFE_CAST(SRC.ADDRESS3BILLTO AS STRING)
,TGT.CITY_BILL_TO = SAFE_CAST(SRC.CITYBILLTO AS STRING)
,TGT.CD_STATE_CD_BILL_TO = SAFE_CAST(SRC.CDSTATECODEBILLTO AS STRING)
,TGT.POSTAL_CD_BILL_TO = SAFE_CAST(SRC.POSTALCODEBILLTO AS STRING)
,TGT.COUNTY_BILL_TO = SAFE_CAST(SRC.COUNTYBILLTO AS STRING)
,TGT.CD_COUNTRY_CD_BILL_TO = SAFE_CAST(SRC.CDCOUNTRYCODEBILLTO AS STRING)
,TGT.LOAN_NUM = SAFE_CAST(SRC.LOANNUMBER AS STRING)
,TGT.DELIVERY_METHOD_CD = SAFE_CAST(SRC.DELIVERYMETHODCODE AS STRING)
,TGT.EMAIL = SAFE_CAST(SRC.EMAIL AS STRING)
,TGT.FAX = SAFE_CAST(SRC.FAX AS STRING)
,TGT.FAX_EXTENSION = SAFE_CAST(SRC.FAXEXTENSION AS STRING)
,TGT.INVOICE_MESSAGE = SAFE_CAST(SRC.INVOICEMESSAGE AS STRING)
,TGT.RECEIVABLE_STATUS_CD = SAFE_CAST(SRC.RECEIVABLESTATUSCODE AS STRING)
,TGT.ATTACH_TO = SAFE_CAST(SRC.ATTACHTO AS STRING)
,TGT.INSERTED_BY_CD = SAFE_CAST(SRC.INSERTEDBYCODE AS STRING)
,TGT.INSERTED_DT = SAFE_CAST(SRC.INSERTEDDATE AS DATETIME)
,TGT.UPDATED_BY_CD = SAFE_CAST(SRC.UPDATEDBYCODE AS STRING)
,TGT.UPDATED_DT = SAFE_CAST(SRC.UPDATEDDATE AS DATETIME)
,TGT.FLGS = SAFE_CAST(SRC.FLAGS AS INT64)
,TGT.TS = SAFE_CAST(SRC.TS AS DATETIME)
,TGT.ADDRESS_DESC = SAFE_CAST(SRC.ADDRESSDESCRIPTION AS STRING)
,TGT.BILL_NUM = SAFE_CAST(SRC.BILLNUMBER AS INT64)
,TGT.SITE_ID = SAFE_CAST(SRC.SITEID AS STRING)
,TGT.REVERSE_REASON_CD = SAFE_CAST(SRC.REVERSEREASONCODE AS STRING)
,TGT.UNIQUE_CONTACT_NUM_FAX = SAFE_CAST(SRC.UNIQCONTACTNUMBERFAX AS INT64)
,TGT.UNIQUE_CONTACT_NUM_EMAIL = SAFE_CAST(SRC.UNIQCONTACTNUMBEREMAIL AS INT64)
,TGT.REGION_PROVINCE_BILL_TO = SAFE_CAST(SRC.REGIONPROVINCEBILLTO AS STRING)
,TGT.FAX_PHONE_COUNTRY_CD = SAFE_CAST(SRC.FAXPHONECOUNTRYCODE AS STRING)
,TGT.INST_EFF_DT = SAFE_CAST(SRC.INSTEFFDATE AS DATETIME)
,TGT.UNIQUE_PAYMENT_INFO = SAFE_CAST(SRC.UNIQPAYMENTINFO AS INT64)
,TGT.PAYMENT_PROCESS_CD = SAFE_CAST(SRC.PAYMENTPROCESSCODE AS STRING)
,TGT.PAYMENT_ID = SAFE_CAST(SRC.PAYMENTID AS STRING)
,TGT.TRANSMITTED_DT = SAFE_CAST(SRC.TRANSMITTEDDATE AS DATETIME)
,TGT.UNIQUE_TAXABLE_ITEM = SAFE_CAST(SRC.UNIQTAXABLEITEM AS INT64)
,TGT.UNIQUE_TAX_FEE_RATE = SAFE_CAST(SRC.UNIQTAXFEERATE AS INT64)
,TGT.UNIQUE_PENDING_PAYMENT_RECEIVING_AGENCY = SAFE_CAST(SRC.UNIQPENDINGPAYMENTRECEIVINGAGENCY AS INT64)
,TGT.UNIQUE_PENDING_PAYMENT_RECEIVING_BRANCH = SAFE_CAST(SRC.UNIQPENDINGPAYMENTRECEIVINGBRANCH AS INT64)
,TGT.UNIQUE_CD_PAYMENT_METHOD = SAFE_CAST(SRC.UNIQCDPAYMENTMETHOD AS INT64)
,TGT.TRANSACTION_ID = SAFE_CAST(SRC.TRANSACTIONID AS STRING)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_TRANS_HEAD
,ITEM_NUM
,CD
,BILL_MODE_CD
,ENTITY_KEY
,UNIQUE_ENTITY
,ENTITY_KEY_BILL_TO
,UNIQUE_ENTITY_BILL_TO
,UNIQUE_POLICY
,UNIQUE_TRANS_HEAD_REVERSAL
,REVERSE_REASON
,INVOICE_NUM
,INVOICE_BATCH_NUM
,PRINTED_DT
,UNIQUE_AGENCY
,UNIQUE_BRANCH
,UNIQUE_DEPARTMENT
,UNIQUE_PROFIT_CENTER
,UNIQUE_GL_ACCOUNT
,EFFECTIVE_DT
,UNIQUE_CONTACT_NAME
,UNIQUE_CONTACT_ADDRESS
,CONTACT_NAME_BILL_TO
,ADDRESS_1_BILL_TO
,ADDRESS_2_BILL_TO
,ADDRESS_3_BILL_TO
,CITY_BILL_TO
,CD_STATE_CD_BILL_TO
,POSTAL_CD_BILL_TO
,COUNTY_BILL_TO
,CD_COUNTRY_CD_BILL_TO
,LOAN_NUM
,DELIVERY_METHOD_CD
,EMAIL
,FAX
,FAX_EXTENSION
,INVOICE_MESSAGE
,RECEIVABLE_STATUS_CD
,ATTACH_TO
,INSERTED_BY_CD
,INSERTED_DT
,UPDATED_BY_CD
,UPDATED_DT
,FLGS
,TS
,ADDRESS_DESC
,BILL_NUM
,SITE_ID
,REVERSE_REASON_CD
,UNIQUE_CONTACT_NUM_FAX
,UNIQUE_CONTACT_NUM_EMAIL
,REGION_PROVINCE_BILL_TO
,FAX_PHONE_COUNTRY_CD
,INST_EFF_DT
,UNIQUE_PAYMENT_INFO
,PAYMENT_PROCESS_CD
,PAYMENT_ID
,TRANSMITTED_DT
,UNIQUE_TAXABLE_ITEM
,UNIQUE_TAX_FEE_RATE
,UNIQUE_PENDING_PAYMENT_RECEIVING_AGENCY
,UNIQUE_PENDING_PAYMENT_RECEIVING_BRANCH
,UNIQUE_CD_PAYMENT_METHOD
,TRANSACTION_ID
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQTRANSHEAD AS INT64)
,SAFE_CAST(ITEMNUMBER AS STRING)
,SAFE_CAST(CODE AS STRING)
,SAFE_CAST(BILLMODECODE AS STRING)
,SAFE_CAST(ENTITYKEY AS STRING)
,SAFE_CAST(UNIQENTITY AS INT64)
,SAFE_CAST(ENTITYKEYBILLTO AS STRING)
,SAFE_CAST(UNIQENTITYBILLTO AS INT64)
,SAFE_CAST(UNIQPOLICY AS INT64)
,SAFE_CAST(UNIQTRANSHEADREVERSAL AS INT64)
,SAFE_CAST(REVERSEREASON AS STRING)
,SAFE_CAST(INVOICENUMBER AS INT64)
,SAFE_CAST(INVOICEBATCHNUMBER AS INT64)
,SAFE_CAST(PRINTEDDATE AS DATETIME)
,SAFE_CAST(UNIQAGENCY AS INT64)
,SAFE_CAST(UNIQBRANCH AS INT64)
,SAFE_CAST(UNIQDEPARTMENT AS INT64)
,SAFE_CAST(UNIQPROFITCENTER AS INT64)
,SAFE_CAST(UNIQGLACCOUNT AS INT64)
,SAFE_CAST(EFFECTIVEDATE AS DATETIME)
,SAFE_CAST(UNIQCONTACTNAME AS INT64)
,SAFE_CAST(UNIQCONTACTADDRESS AS INT64)
,SAFE_CAST(CONTACTNAMEBILLTO AS STRING)
,SAFE_CAST(ADDRESS1BILLTO AS STRING)
,SAFE_CAST(ADDRESS2BILLTO AS STRING)
,SAFE_CAST(ADDRESS3BILLTO AS STRING)
,SAFE_CAST(CITYBILLTO AS STRING)
,SAFE_CAST(CDSTATECODEBILLTO AS STRING)
,SAFE_CAST(POSTALCODEBILLTO AS STRING)
,SAFE_CAST(COUNTYBILLTO AS STRING)
,SAFE_CAST(CDCOUNTRYCODEBILLTO AS STRING)
,SAFE_CAST(LOANNUMBER AS STRING)
,SAFE_CAST(DELIVERYMETHODCODE AS STRING)
,SAFE_CAST(EMAIL AS STRING)
,SAFE_CAST(FAX AS STRING)
,SAFE_CAST(FAXEXTENSION AS STRING)
,SAFE_CAST(INVOICEMESSAGE AS STRING)
,SAFE_CAST(RECEIVABLESTATUSCODE AS STRING)
,SAFE_CAST(ATTACHTO AS STRING)
,SAFE_CAST(INSERTEDBYCODE AS STRING)
,SAFE_CAST(INSERTEDDATE AS DATETIME)
,SAFE_CAST(UPDATEDBYCODE AS STRING)
,SAFE_CAST(UPDATEDDATE AS DATETIME)
,SAFE_CAST(FLAGS AS INT64)
,SAFE_CAST(TS AS DATETIME)
,SAFE_CAST(ADDRESSDESCRIPTION AS STRING)
,SAFE_CAST(BILLNUMBER AS INT64)
,SAFE_CAST(SITEID AS STRING)
,SAFE_CAST(REVERSEREASONCODE AS STRING)
,SAFE_CAST(UNIQCONTACTNUMBERFAX AS INT64)
,SAFE_CAST(UNIQCONTACTNUMBEREMAIL AS INT64)
,SAFE_CAST(REGIONPROVINCEBILLTO AS STRING)
,SAFE_CAST(FAXPHONECOUNTRYCODE AS STRING)
,SAFE_CAST(INSTEFFDATE AS DATETIME)
,SAFE_CAST(UNIQPAYMENTINFO AS INT64)
,SAFE_CAST(PAYMENTPROCESSCODE AS STRING)
,SAFE_CAST(PAYMENTID AS STRING)
,SAFE_CAST(TRANSMITTEDDATE AS DATETIME)
,SAFE_CAST(UNIQTAXABLEITEM AS INT64)
,SAFE_CAST(UNIQTAXFEERATE AS INT64)
,SAFE_CAST(UNIQPENDINGPAYMENTRECEIVINGAGENCY AS INT64)
,SAFE_CAST(UNIQPENDINGPAYMENTRECEIVINGBRANCH AS INT64)
,SAFE_CAST(UNIQCDPAYMENTMETHOD AS INT64)
,SAFE_CAST(TRANSACTIONID AS STRING)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
