MERGE `OPERATIONAL.AMS_BRANCH` AS TGT
USING `LANDING.WORK_AMS_BRANCH` AS SRC
ON TGT.UNIQUE_BRANCH = SAFE_CAST(SRC.UNIQBRANCH AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_BRANCH = SAFE_CAST(SRC.UNIQBRANCH AS INT64)
,TGT.BRANCH_CD = SAFE_CAST(SRC.BRANCHCODE AS STRING)
,TGT.NAME_OF = SAFE_CAST(SRC.NAMEOF AS STRING)
,TGT.LICENSE_NUM = SAFE_CAST(SRC.LICENSENUMBER AS STRING)
,TGT.ISSUER_KEY = SAFE_CAST(SRC.ISSUERKEY AS STRING)
,TGT.PIN = SAFE_CAST(SRC.PIN AS STRING)
,TGT.INSERTED_BY_CD = SAFE_CAST(SRC.INSERTEDBYCODE AS STRING)
,TGT.INSERTED_DT = SAFE_CAST(SRC.INSERTEDDATE AS DATETIME)
,TGT.UPDATED_BY_CD = SAFE_CAST(SRC.UPDATEDBYCODE AS STRING)
,TGT.UPDATED_DT = SAFE_CAST(SRC.UPDATEDDATE AS DATETIME)
,TGT.FLGS = SAFE_CAST(SRC.FLAGS AS INT64)
,TGT.NY_LICENSE_NUM = SAFE_CAST(SRC.NYLICENSENUMBER AS STRING)
,TGT.UNIQUE_MAIN_ADDRESS = SAFE_CAST(SRC.UNIQMAINADDRESS AS INT64)
,TGT.UNIQUE_MAILING_ADDRESS = SAFE_CAST(SRC.UNIQMAILINGADDRESS AS INT64)
,TGT.UNIQUE_ORGANIZATION_PHONE = SAFE_CAST(SRC.UNIQORGANIZATIONPHONE AS INT64)
,TGT.UNIQUE_ORGANIZATION_FAX = SAFE_CAST(SRC.UNIQORGANIZATIONFAX AS INT64)
,TGT.UNIQUE_ORGANIZATION_EMAIL = SAFE_CAST(SRC.UNIQORGANIZATIONEMAIL AS INT64)
,TGT.UNIQUE_ORGANIZATION_WEBSITE = SAFE_CAST(SRC.UNIQORGANIZATIONWEBSITE AS INT64)
,TGT.UNIQUE_OTHER_ADDRESS = SAFE_CAST(SRC.UNIQOTHERADDRESS AS INT64)
,TGT.UNIQUE_ORGANIZATION_SMS = SAFE_CAST(SRC.UNIQORGANIZATIONSMS AS INT64)
,TGT.BRANCH_ID = SAFE_CAST(SRC.BRANCHID AS STRING)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_BRANCH
,BRANCH_CD
,NAME_OF
,LICENSE_NUM
,ISSUER_KEY
,PIN
,INSERTED_BY_CD
,INSERTED_DT
,UPDATED_BY_CD
,UPDATED_DT
,FLGS
,NY_LICENSE_NUM
,UNIQUE_MAIN_ADDRESS
,UNIQUE_MAILING_ADDRESS
,UNIQUE_ORGANIZATION_PHONE
,UNIQUE_ORGANIZATION_FAX
,UNIQUE_ORGANIZATION_EMAIL
,UNIQUE_ORGANIZATION_WEBSITE
,UNIQUE_OTHER_ADDRESS
,UNIQUE_ORGANIZATION_SMS
,BRANCH_ID
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQBRANCH AS INT64)
,SAFE_CAST(BRANCHCODE AS STRING)
,SAFE_CAST(NAMEOF AS STRING)
,SAFE_CAST(LICENSENUMBER AS STRING)
,SAFE_CAST(ISSUERKEY AS STRING)
,SAFE_CAST(PIN AS STRING)
,SAFE_CAST(INSERTEDBYCODE AS STRING)
,SAFE_CAST(INSERTEDDATE AS DATETIME)
,SAFE_CAST(UPDATEDBYCODE AS STRING)
,SAFE_CAST(UPDATEDDATE AS DATETIME)
,SAFE_CAST(FLAGS AS INT64)
,SAFE_CAST(NYLICENSENUMBER AS STRING)
,SAFE_CAST(UNIQMAINADDRESS AS INT64)
,SAFE_CAST(UNIQMAILINGADDRESS AS INT64)
,SAFE_CAST(UNIQORGANIZATIONPHONE AS INT64)
,SAFE_CAST(UNIQORGANIZATIONFAX AS INT64)
,SAFE_CAST(UNIQORGANIZATIONEMAIL AS INT64)
,SAFE_CAST(UNIQORGANIZATIONWEBSITE AS INT64)
,SAFE_CAST(UNIQOTHERADDRESS AS INT64)
,SAFE_CAST(UNIQORGANIZATIONSMS AS INT64)
,SAFE_CAST(BRANCHID AS STRING)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
