MERGE `OPERATIONAL.AMS_SECURITY_USER_STRUCTURE_COMBINATION_JT` AS TGT
USING `LANDING.WORK_AMS_SECURITY_USER_STRUCTURE_COMBINATION_JT` AS SRC
ON TGT.UNIQUE_SECURITY_USER = SAFE_CAST(SRC.UNIQSECURITYUSER AS INT64)
AND TGT.UNIQUE_STRUCTURE = SAFE_CAST(SRC.UNIQSTRUCTURE AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_SECURITY_USER = SAFE_CAST(SRC.UNIQSECURITYUSER AS INT64)
,TGT.UNIQUE_STRUCTURE = SAFE_CAST(SRC.UNIQSTRUCTURE AS INT64)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_SECURITY_USER
,UNIQUE_STRUCTURE
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQSECURITYUSER AS INT64)
,SAFE_CAST(UNIQSTRUCTURE AS INT64)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
