MERGE `OPERATIONAL.AMS_TRANS_DETAIL` AS TGT
USING `LANDING.WORK_AMS_TRANS_DETAIL` AS SRC
ON TGT.UNIQUE_TRANS_HEAD = SAFE_CAST(SRC.UNIQTRANSHEAD AS INT64)
AND TGT.TRANS_DETAIL_NUM = SAFE_CAST(SRC.TRANSDETAILNUMBER AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_TRANS_HEAD = SAFE_CAST(SRC.UNIQTRANSHEAD AS INT64)
,TGT.TRANS_DETAIL_NUM = SAFE_CAST(SRC.TRANSDETAILNUMBER AS INT64)
,TGT.DESC_OF = SAFE_CAST(SRC.DESCRIPTIONOF AS STRING)
,TGT.AR_DUE_DT = SAFE_CAST(SRC.ARDUEDATE AS DATETIME)
,TGT.PRINT_DT = SAFE_CAST(SRC.PRINTDATE AS DATETIME)
,TGT.ACCOUNTING_MONTH = SAFE_CAST(SRC.ACCOUNTINGMONTH AS STRING)
,TGT.MONTH_SOLD = SAFE_CAST(SRC.MONTHSOLD AS STRING)
,TGT.PROCESS_CD = SAFE_CAST(SRC.PROCESSCODE AS STRING)
,TGT.CLASS_CD = SAFE_CAST(SRC.CLASSCODE AS STRING)
,TGT.ITEM_AMT = SAFE_CAST(SRC.ITEMAMOUNT AS FLOAT64)
,TGT.APPLYMENT_AMT = SAFE_CAST(SRC.APPLYMENTAMOUNT AS FLOAT64)
,TGT.UNIQUE_TRANS_HEAD_FINANCE = SAFE_CAST(SRC.UNIQTRANSHEADFINANCE AS INT64)
,TGT.UNIQUE_TRANS_HEAD_DEBIT_CREDIT = SAFE_CAST(SRC.UNIQTRANSHEADDEBITCREDIT AS INT64)
,TGT.TRANS_DETAIL_NUM_DEBIT_CREDIT = SAFE_CAST(SRC.TRANSDETAILNUMBERDEBITCREDIT AS INT64)
,TGT.UNIQUE_RECEIPT = SAFE_CAST(SRC.UNIQRECEIPT AS INT64)
,TGT.UNIQUE_RECEIPT_LINE = SAFE_CAST(SRC.UNIQRECEIPTLINE AS INT64)
,TGT.UNIQUE_DISBURSEMENT = SAFE_CAST(SRC.UNIQDISBURSEMENT AS INT64)
,TGT.UNIQUE_DISBURSEMENT_LINE = SAFE_CAST(SRC.UNIQDISBURSEMENTLINE AS INT64)
,TGT.UNIQUE_COMPANY_RECONCILIATION_CASH_ON_ACCOUNT = SAFE_CAST(SRC.UNIQCOMPANYRECONCILIATIONCASHONACCOUNT AS INT64)
,TGT.UNIQUE_TRANS_HEAD_CASH_ON_ACCOUNT = SAFE_CAST(SRC.UNIQTRANSHEADCASHONACCOUNT AS INT64)
,TGT.TRANS_COMPANY_NUM_CASH_ON_ACCOUNT = SAFE_CAST(SRC.TRANSCOMPANYNUMBERCASHONACCOUNT AS INT64)
,TGT.ITEM_BALANCE_CALC = SAFE_CAST(SRC.ITEMBALANCECALC AS FLOAT64)
,TGT.TRANSACTION_AMT_CALC = SAFE_CAST(SRC.TRANSACTIONAMOUNTCALC AS FLOAT64)
,TGT.INSERTED_BY_CD = SAFE_CAST(SRC.INSERTEDBYCODE AS STRING)
,TGT.INSERTED_DT = SAFE_CAST(SRC.INSERTEDDATE AS DATETIME)
,TGT.UPDATED_BY_CD = SAFE_CAST(SRC.UPDATEDBYCODE AS STRING)
,TGT.UPDATED_DT = SAFE_CAST(SRC.UPDATEDDATE AS DATETIME)
,TGT.FLGS = SAFE_CAST(SRC.FLAGS AS INT64)
,TGT.UNIQUE_TRANS_HEAD_SPLIT_RECEIVABLE = SAFE_CAST(SRC.UNIQTRANSHEADSPLITRECEIVABLE AS INT64)
,TGT.TRANS_DETAIL_NUM_SPLIT_RECEIVABLE = SAFE_CAST(SRC.TRANSDETAILNUMBERSPLITRECEIVABLE AS INT64)
,TGT.UNIQUE_VOUCHER = SAFE_CAST(SRC.UNIQVOUCHER AS INT64)
,TGT.UNIQUE_VOUCHER_LINE = SAFE_CAST(SRC.UNIQVOUCHERLINE AS INT64)
,TGT.TRANS_DETAIL_NUM_CASH_ON_ACCOUNT = SAFE_CAST(SRC.TRANSDETAILNUMBERCASHONACCOUNT AS INT64)
,TGT.TRANS_DETAIL_NUM_REVERSED = SAFE_CAST(SRC.TRANSDETAILNUMBERREVERSED AS INT64)
,TGT.PAYMENT_DT = SAFE_CAST(SRC.PAYMENTDATE AS DATETIME)
,TGT.DT_RECEIVED = SAFE_CAST(SRC.DATERECEIVED AS DATETIME)
,TGT.UNIQUE_PAYMENT_INFO = SAFE_CAST(SRC.UNIQPAYMENTINFO AS INT64)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_TRANS_HEAD
,TRANS_DETAIL_NUM
,DESC_OF
,AR_DUE_DT
,PRINT_DT
,ACCOUNTING_MONTH
,MONTH_SOLD
,PROCESS_CD
,CLASS_CD
,ITEM_AMT
,APPLYMENT_AMT
,UNIQUE_TRANS_HEAD_FINANCE
,UNIQUE_TRANS_HEAD_DEBIT_CREDIT
,TRANS_DETAIL_NUM_DEBIT_CREDIT
,UNIQUE_RECEIPT
,UNIQUE_RECEIPT_LINE
,UNIQUE_DISBURSEMENT
,UNIQUE_DISBURSEMENT_LINE
,UNIQUE_COMPANY_RECONCILIATION_CASH_ON_ACCOUNT
,UNIQUE_TRANS_HEAD_CASH_ON_ACCOUNT
,TRANS_COMPANY_NUM_CASH_ON_ACCOUNT
,ITEM_BALANCE_CALC
,TRANSACTION_AMT_CALC
,INSERTED_BY_CD
,INSERTED_DT
,UPDATED_BY_CD
,UPDATED_DT
,FLGS
,UNIQUE_TRANS_HEAD_SPLIT_RECEIVABLE
,TRANS_DETAIL_NUM_SPLIT_RECEIVABLE
,UNIQUE_VOUCHER
,UNIQUE_VOUCHER_LINE
,TRANS_DETAIL_NUM_CASH_ON_ACCOUNT
,TRANS_DETAIL_NUM_REVERSED
,PAYMENT_DT
,DT_RECEIVED
,UNIQUE_PAYMENT_INFO
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQTRANSHEAD AS INT64)
,SAFE_CAST(TRANSDETAILNUMBER AS INT64)
,SAFE_CAST(DESCRIPTIONOF AS STRING)
,SAFE_CAST(ARDUEDATE AS DATETIME)
,SAFE_CAST(PRINTDATE AS DATETIME)
,SAFE_CAST(ACCOUNTINGMONTH AS STRING)
,SAFE_CAST(MONTHSOLD AS STRING)
,SAFE_CAST(PROCESSCODE AS STRING)
,SAFE_CAST(CLASSCODE AS STRING)
,SAFE_CAST(ITEMAMOUNT AS FLOAT64)
,SAFE_CAST(APPLYMENTAMOUNT AS FLOAT64)
,SAFE_CAST(UNIQTRANSHEADFINANCE AS INT64)
,SAFE_CAST(UNIQTRANSHEADDEBITCREDIT AS INT64)
,SAFE_CAST(TRANSDETAILNUMBERDEBITCREDIT AS INT64)
,SAFE_CAST(UNIQRECEIPT AS INT64)
,SAFE_CAST(UNIQRECEIPTLINE AS INT64)
,SAFE_CAST(UNIQDISBURSEMENT AS INT64)
,SAFE_CAST(UNIQDISBURSEMENTLINE AS INT64)
,SAFE_CAST(UNIQCOMPANYRECONCILIATIONCASHONACCOUNT AS INT64)
,SAFE_CAST(UNIQTRANSHEADCASHONACCOUNT AS INT64)
,SAFE_CAST(TRANSCOMPANYNUMBERCASHONACCOUNT AS INT64)
,SAFE_CAST(ITEMBALANCECALC AS FLOAT64)
,SAFE_CAST(TRANSACTIONAMOUNTCALC AS FLOAT64)
,SAFE_CAST(INSERTEDBYCODE AS STRING)
,SAFE_CAST(INSERTEDDATE AS DATETIME)
,SAFE_CAST(UPDATEDBYCODE AS STRING)
,SAFE_CAST(UPDATEDDATE AS DATETIME)
,SAFE_CAST(FLAGS AS INT64)
,SAFE_CAST(UNIQTRANSHEADSPLITRECEIVABLE AS INT64)
,SAFE_CAST(TRANSDETAILNUMBERSPLITRECEIVABLE AS INT64)
,SAFE_CAST(UNIQVOUCHER AS INT64)
,SAFE_CAST(UNIQVOUCHERLINE AS INT64)
,SAFE_CAST(TRANSDETAILNUMBERCASHONACCOUNT AS INT64)
,SAFE_CAST(TRANSDETAILNUMBERREVERSED AS INT64)
,SAFE_CAST(PAYMENTDATE AS DATETIME)
,SAFE_CAST(DATERECEIVED AS DATETIME)
,SAFE_CAST(UNIQPAYMENTINFO AS INT64)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
