MERGE `OPERATIONAL.AMS_CONTACT_CLASS` AS TGT
USING `LANDING.WORK_AMS_CONTACT_CLASS` AS SRC
ON TGT.UNIQUE_CONTACT_NAME = SAFE_CAST(SRC.UNIQCONTACTNAME AS INT64)
AND UPPER(TRIM(TGT.LK_CONTACT_CLASS)) = SAFE_CAST(UPPER(TRIM(SRC.LKCONTACTCLASS)) AS STRING)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_CONTACT_NAME = SAFE_CAST(SRC.UNIQCONTACTNAME AS INT64)
,TGT.LK_CONTACT_CLASS = SAFE_CAST(SRC.LKCONTACTCLASS AS STRING)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_CONTACT_NAME
,LK_CONTACT_CLASS
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQCONTACTNAME AS INT64)
,SAFE_CAST(LKCONTACTCLASS AS STRING)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
