MERGE `OPERATIONAL.AMS_LINE_IMAGE` AS TGT
USING `LANDING.WORK_AMS_LINE_IMAGE` AS SRC
ON TGT.UNIQUE_LINE_IMAGE = SAFE_CAST(SRC.UNIQLINEIMAGE AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_LINE_IMAGE = SAFE_CAST(SRC.UNIQLINEIMAGE AS INT64)
,TGT.UNIQUE_LINE = SAFE_CAST(SRC.UNIQLINE AS INT64)
,TGT.EFFECTIVE_DT = SAFE_CAST(SRC.EFFECTIVEDATE AS DATETIME)
,TGT.UNIQUE_PERSONAL_APPLICATION = SAFE_CAST(SRC.UNIQPERSONALAPPLICATION AS INT64)
,TGT.UNIQUE_COMMERCIAL_APPLICATION = SAFE_CAST(SRC.UNIQCOMMERCIALAPPLICATION AS INT64)
,TGT.UNIQUE_MARKETING_LINE = SAFE_CAST(SRC.UNIQMARKETINGLINE AS INT64)
,TGT.UNIQUE_AGRICULTURE_APPLICATION = SAFE_CAST(SRC.UNIQAGRICULTUREAPPLICATION AS INT64)
,TGT.UNIQUE_CF_POLICY_INFORMATION = SAFE_CAST(SRC.UNIQCFPOLICYINFORMATION AS INT64)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_LINE_IMAGE
,UNIQUE_LINE
,EFFECTIVE_DT
,UNIQUE_PERSONAL_APPLICATION
,UNIQUE_COMMERCIAL_APPLICATION
,UNIQUE_MARKETING_LINE
,UNIQUE_AGRICULTURE_APPLICATION
,UNIQUE_CF_POLICY_INFORMATION
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQLINEIMAGE AS INT64)
,SAFE_CAST(UNIQLINE AS INT64)
,SAFE_CAST(EFFECTIVEDATE AS DATETIME)
,SAFE_CAST(UNIQPERSONALAPPLICATION AS INT64)
,SAFE_CAST(UNIQCOMMERCIALAPPLICATION AS INT64)
,SAFE_CAST(UNIQMARKETINGLINE AS INT64)
,SAFE_CAST(UNIQAGRICULTUREAPPLICATION AS INT64)
,SAFE_CAST(UNIQCFPOLICYINFORMATION AS INT64)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
