MERGE `OPERATIONAL.AMS_CD_POLICY_LINE_TYPE` AS TGT
USING `LANDING.WORK_AMS_CD_POLICY_LINE_TYPE` AS SRC
ON TGT.UNIQUE_CD_POLICY_LINE_TYPE = SAFE_CAST(SRC.UNIQCDPOLICYLINETYPE AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_CD_POLICY_LINE_TYPE = SAFE_CAST(SRC.UNIQCDPOLICYLINETYPE AS INT64)
,TGT.CD_POLICY_LINE_TYPE_CD = SAFE_CAST(SRC.CDPOLICYLINETYPECODE AS STRING)
,TGT.TYPE_OF_BUSINESS_CD = SAFE_CAST(SRC.TYPEOFBUSINESSCODE AS STRING)
,TGT.TERM_DEFAULT_CD = SAFE_CAST(SRC.TERMDEFAULTCODE AS STRING)
,TGT.UNIQUE_FORM_CATEGORY = SAFE_CAST(SRC.UNIQFORMCATEGORY AS INT64)
,TGT.UNIQUE_DEPARTMENT = SAFE_CAST(SRC.UNIQDEPARTMENT AS INT64)
,TGT.UNIQUE_PROFIT_CENTER = SAFE_CAST(SRC.UNIQPROFITCENTER AS INT64)
,TGT.FLGS = SAFE_CAST(SRC.FLAGS AS INT64)
,TGT.UNIQUE_CD_POLICY_TYPE_CLASSIFICATION = SAFE_CAST(SRC.UNIQCDPOLICYTYPECLASSIFICATION AS INT64)
,TGT.STANDARDS_BODY_CD = SAFE_CAST(SRC.STANDARDSBODYCODE AS STRING)
,TGT.CONFIGURE_LK_LANGUAGE_RESOURCE_ID = SAFE_CAST(SRC.CONFIGURELKLANGUAGERESOURCEID AS STRING)
,TGT.RATING_LINE_DEFINITION_ID = SAFE_CAST(SRC.RATINGLINEDEFINITIONID AS STRING)
,TGT.RATING_LINE_DEFINITION_CONFIGURE_LK_LANGUAGE_RESOURCE_ID = SAFE_CAST(SRC.RATINGLINEDEFINITIONCONFIGURELKLANGUAGERESOURCEID AS STRING)
,TGT.TAX_OPTION = SAFE_CAST(SRC.TAXOPTION AS STRING)
,TGT.RENEWAL_MANAGER_DAYS_TO_EXPIRATION = SAFE_CAST(SRC.RENEWALMANAGERDAYSTOEXPIRATION AS INT64)
,TGT.LOSS_NOTICE_CD = SAFE_CAST(SRC.LOSSNOTICECODE AS STRING)
,TGT.UNIQUE_LK_CLAIM_TYPE = SAFE_CAST(SRC.UNIQLKCLAIMTYPE AS INT64)
,TGT.CD_POLICY_LINE_TYPE_ID = SAFE_CAST(SRC.CDPOLICYLINETYPEID AS STRING)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_CD_POLICY_LINE_TYPE
,CD_POLICY_LINE_TYPE_CD
,TYPE_OF_BUSINESS_CD
,TERM_DEFAULT_CD
,UNIQUE_FORM_CATEGORY
,UNIQUE_DEPARTMENT
,UNIQUE_PROFIT_CENTER
,FLGS
,UNIQUE_CD_POLICY_TYPE_CLASSIFICATION
,STANDARDS_BODY_CD
,CONFIGURE_LK_LANGUAGE_RESOURCE_ID
,RATING_LINE_DEFINITION_ID
,RATING_LINE_DEFINITION_CONFIGURE_LK_LANGUAGE_RESOURCE_ID
,TAX_OPTION
,RENEWAL_MANAGER_DAYS_TO_EXPIRATION
,LOSS_NOTICE_CD
,UNIQUE_LK_CLAIM_TYPE
,CD_POLICY_LINE_TYPE_ID
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQCDPOLICYLINETYPE AS INT64)
,SAFE_CAST(CDPOLICYLINETYPECODE AS STRING)
,SAFE_CAST(TYPEOFBUSINESSCODE AS STRING)
,SAFE_CAST(TERMDEFAULTCODE AS STRING)
,SAFE_CAST(UNIQFORMCATEGORY AS INT64)
,SAFE_CAST(UNIQDEPARTMENT AS INT64)
,SAFE_CAST(UNIQPROFITCENTER AS INT64)
,SAFE_CAST(FLAGS AS INT64)
,SAFE_CAST(UNIQCDPOLICYTYPECLASSIFICATION AS INT64)
,SAFE_CAST(STANDARDSBODYCODE AS STRING)
,SAFE_CAST(CONFIGURELKLANGUAGERESOURCEID AS STRING)
,SAFE_CAST(RATINGLINEDEFINITIONID AS STRING)
,SAFE_CAST(RATINGLINEDEFINITIONCONFIGURELKLANGUAGERESOURCEID AS STRING)
,SAFE_CAST(TAXOPTION AS STRING)
,SAFE_CAST(RENEWALMANAGERDAYSTOEXPIRATION AS INT64)
,SAFE_CAST(LOSSNOTICECODE AS STRING)
,SAFE_CAST(UNIQLKCLAIMTYPE AS INT64)
,SAFE_CAST(CDPOLICYLINETYPEID AS STRING)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
