MERGE `OPERATIONAL.AMS_SECURITY_USER` AS TGT
USING `LANDING.WORK_AMS_SECURITY_USER` AS SRC
ON TGT.UNIQUE_SECURITY_USER = SAFE_CAST(SRC.UNIQSECURITYUSER AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_SECURITY_USER = SAFE_CAST(SRC.UNIQSECURITYUSER AS INT64)
,TGT.USER_CD = SAFE_CAST(SRC.USERCODE AS STRING)
,TGT.FULL_NAME = SAFE_CAST(SRC.FULLNAME AS STRING)
,TGT.TYPE_CD = SAFE_CAST(SRC.TYPECODE AS STRING)
,TGT.UNIQUE_EMPLOYEE = SAFE_CAST(SRC.UNIQEMPLOYEE AS INT64)
--,TGT.PROGRAM_ACCESS = SAFE_CAST(SRC.PROGRAMACCESS AS STRING)
,TGT.FLGS = SAFE_CAST(SRC.FLAGS AS INT64)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_SECURITY_USER
,USER_CD
,FULL_NAME
,TYPE_CD
,UNIQUE_EMPLOYEE
--,PROGRAM_ACCESS
,FLGS
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQSECURITYUSER AS INT64)
,SAFE_CAST(USERCODE AS STRING)
,SAFE_CAST(FULLNAME AS STRING)
,SAFE_CAST(TYPECODE AS STRING)
,SAFE_CAST(UNIQEMPLOYEE AS INT64)
--,SAFE_CAST(PROGRAMACCESS AS STRING)
,SAFE_CAST(FLAGS AS INT64)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
