MERGE `OPERATIONAL.AMS_EMPLOYEE` AS TGT
USING `LANDING.WORK_AMS_EMPLOYEE` AS SRC
ON TGT.UNIQUE_ENTITY = SAFE_CAST(SRC.UNIQENTITY AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_ENTITY = SAFE_CAST(SRC.UNIQENTITY AS INT64)
,TGT.LOOKUP_CD = SAFE_CAST(SRC.LOOKUPCODE AS STRING)
,TGT.NAME_OF = SAFE_CAST(SRC.NAMEOF AS STRING)
,TGT.UNIQUE_CONTACT_NAME_ACCOUNT = SAFE_CAST(SRC.UNIQCONTACTNAMEACCOUNT AS INT64)
,TGT.UNIQUE_CONTACT_ADDRESS_ACCOUNT = SAFE_CAST(SRC.UNIQCONTACTADDRESSACCOUNT AS INT64)
,TGT.UNIQUE_CONTACT_NUM_RESIDENCE_ACCOUNT = SAFE_CAST(SRC.UNIQCONTACTNUMBERRESIDENCEACCOUNT AS INT64)
,TGT.UNIQUE_CONTACT_NUM_MOBILE_ACCOUNT = SAFE_CAST(SRC.UNIQCONTACTNUMBERMOBILEACCOUNT AS INT64)
,TGT.UNIQUE_CONTACT_NUM_FAX_ACCOUNT = SAFE_CAST(SRC.UNIQCONTACTNUMBERFAXACCOUNT AS INT64)
,TGT.UNIQUE_CONTACT_NUM_EMAIL_ACCOUNT = SAFE_CAST(SRC.UNIQCONTACTNUMBEREMAILACCOUNT AS INT64)
,TGT.DEPARTMENT = SAFE_CAST(SRC.DEPARTMENT AS STRING)
,TGT.JOB_TITLE = SAFE_CAST(SRC.JOBTITLE AS STRING)
,TGT.UNIQUE_DOCUMENT_SIGNATURE = SAFE_CAST(SRC.UNIQDOCUMENTSIGNATURE AS INT64)
,TGT.COMMENTS = SAFE_CAST(SRC.COMMENTS AS STRING)
,TGT.BATCH_PAYMENT_METHOD_CD = SAFE_CAST(SRC.BATCHPAYMENTMETHODCODE AS STRING)
,TGT.UNIQUE_GL_ACCOUNT_PAY = SAFE_CAST(SRC.UNIQGLACCOUNTPAY AS INT64)
,TGT.UNIQUE_GL_ACCOUNT_DEF = SAFE_CAST(SRC.UNIQGLACCOUNTDEF AS INT64)
,TGT.UNIQUE_GL_ACCOUNT_EXP = SAFE_CAST(SRC.UNIQGLACCOUNTEXP AS INT64)
,TGT.UNIQUE_GL_ACCOUNT_ABILL = SAFE_CAST(SRC.UNIQGLACCOUNTABILL AS INT64)
,TGT.UNIQUE_GL_ACCOUNT_DBILL = SAFE_CAST(SRC.UNIQGLACCOUNTDBILL AS INT64)
,TGT.EMERGENCY_CONTACT_NAME_1 = SAFE_CAST(SRC.EMERGENCYCONTACTNAME1 AS STRING)
,TGT.EMERGENCY_CONTACT_NUM_1 = SAFE_CAST(SRC.EMERGENCYCONTACTNUMBER1 AS STRING)
,TGT.EMERGENCY_CONTACT_EXTENSION_1 = SAFE_CAST(SRC.EMERGENCYCONTACTEXTENSION1 AS STRING)
,TGT.EMERGENCY_CONTACT_DESC_1 = SAFE_CAST(SRC.EMERGENCYCONTACTDESCRIPTION1 AS STRING)
,TGT.EMERGENCY_CONTACT_EMAIL_1 = SAFE_CAST(SRC.EMERGENCYCONTACTEMAIL1 AS STRING)
,TGT.EMERGENCY_CONTACT_NAME_2 = SAFE_CAST(SRC.EMERGENCYCONTACTNAME2 AS STRING)
,TGT.EMERGENCY_CONTACT_NUM_2 = SAFE_CAST(SRC.EMERGENCYCONTACTNUMBER2 AS STRING)
,TGT.EMERGENCY_CONTACT_EXTENSION_2 = SAFE_CAST(SRC.EMERGENCYCONTACTEXTENSION2 AS STRING)
,TGT.EMERGENCY_CONTACT_DESC_2 = SAFE_CAST(SRC.EMERGENCYCONTACTDESCRIPTION2 AS STRING)
,TGT.EMERGENCY_CONTACT_EMAIL_2 = SAFE_CAST(SRC.EMERGENCYCONTACTEMAIL2 AS STRING)
,TGT.HIRED_DT = SAFE_CAST(SRC.HIREDDATE AS DATETIME)
,TGT.FULL_PART_TIME_CD = SAFE_CAST(SRC.FULLPARTTIMECODE AS STRING)
,TGT.NUM_HOURS = SAFE_CAST(SRC.NUMBERHOURS AS INT64)
,TGT.LAST_REVIEW_DT = SAFE_CAST(SRC.LASTREVIEWDATE AS DATETIME)
,TGT.NEXT_REVIEW_DT = SAFE_CAST(SRC.NEXTREVIEWDATE AS DATETIME)
,TGT.LAST_RAISE_DT = SAFE_CAST(SRC.LASTRAISEDATE AS DATETIME)
,TGT.TERMINATED_DT = SAFE_CAST(SRC.TERMINATEDDATE AS DATETIME)
,TGT.COMPENSATION_TYPE_CD = SAFE_CAST(SRC.COMPENSATIONTYPECODE AS STRING)
,TGT.YEARLY_SALARY = SAFE_CAST(SRC.YEARLYSALARY AS FLOAT64)
,TGT.HOURLY_WAGE = SAFE_CAST(SRC.HOURLYWAGE AS FLOAT64)
,TGT.INACTIVE_DT = SAFE_CAST(SRC.INACTIVEDATE AS DATETIME)
,TGT.INACTIVE_REASON = SAFE_CAST(SRC.INACTIVEREASON AS STRING)
,TGT.EXPIRATION_DT = SAFE_CAST(SRC.EXPIRATIONDATE AS DATETIME)
,TGT.CONVERSION_DT = SAFE_CAST(SRC.CONVERSIONDATE AS DATETIME)
,TGT.CONVERSION_PRIOR_ACCOUNT_ID = SAFE_CAST(SRC.CONVERSIONPRIORACCOUNTID AS STRING)
,TGT.INSERTED_BY_CD = SAFE_CAST(SRC.INSERTEDBYCODE AS STRING)
,TGT.INSERTED_DT = SAFE_CAST(SRC.INSERTEDDATE AS DATETIME)
,TGT.UPDATED_BY_CD = SAFE_CAST(SRC.UPDATEDBYCODE AS STRING)
,TGT.UPDATED_DT = SAFE_CAST(SRC.UPDATEDDATE AS DATETIME)
,TGT.ROLE_FLGS = SAFE_CAST(SRC.ROLEFLAGS AS INT64)
,TGT.FLGS = SAFE_CAST(SRC.FLAGS AS INT64)
,TGT.TS = SAFE_CAST(SRC.TS AS DATETIME)
,TGT.INACTIVATED_BY_CD = SAFE_CAST(SRC.INACTIVATEDBYCODE AS STRING)
,TGT.EMERGENCY_CONTACT_PHONE_COUNTRY_CD_1 = SAFE_CAST(SRC.EMERGENCYCONTACTPHONECOUNTRYCODE1 AS STRING)
,TGT.EMERGENCY_CONTACT_PHONE_COUNTRY_CD_2 = SAFE_CAST(SRC.EMERGENCYCONTACTPHONECOUNTRYCODE2 AS STRING)
,TGT.UNIQUE_GL_ACCOUNT_PAY_WRITE_OFF = SAFE_CAST(SRC.UNIQGLACCOUNTPAYWRITEOFF AS INT64)
,TGT.UNIQUE_CONTACT_NUM_BUSINESS_ACCOUNT = SAFE_CAST(SRC.UNIQCONTACTNUMBERBUSINESSACCOUNT AS INT64)
,TGT.UNIQUE_CONTACT_NUM_EMAIL_ACCOUNT_2 = SAFE_CAST(SRC.UNIQCONTACTNUMBEREMAILACCOUNT2 AS INT64)
,TGT.UNIQUE_SMS_NUM = SAFE_CAST(SRC.UNIQSMSNUMBER AS INT64)
,TGT.EMPLOYEE_ID = SAFE_CAST(SRC.EMPLOYEEID AS STRING)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_ENTITY
,LOOKUP_CD
,NAME_OF
,UNIQUE_CONTACT_NAME_ACCOUNT
,UNIQUE_CONTACT_ADDRESS_ACCOUNT
,UNIQUE_CONTACT_NUM_RESIDENCE_ACCOUNT
,UNIQUE_CONTACT_NUM_MOBILE_ACCOUNT
,UNIQUE_CONTACT_NUM_FAX_ACCOUNT
,UNIQUE_CONTACT_NUM_EMAIL_ACCOUNT
,DEPARTMENT
,JOB_TITLE
,UNIQUE_DOCUMENT_SIGNATURE
,COMMENTS
,BATCH_PAYMENT_METHOD_CD
,UNIQUE_GL_ACCOUNT_PAY
,UNIQUE_GL_ACCOUNT_DEF
,UNIQUE_GL_ACCOUNT_EXP
,UNIQUE_GL_ACCOUNT_ABILL
,UNIQUE_GL_ACCOUNT_DBILL
,EMERGENCY_CONTACT_NAME_1
,EMERGENCY_CONTACT_NUM_1
,EMERGENCY_CONTACT_EXTENSION_1
,EMERGENCY_CONTACT_DESC_1
,EMERGENCY_CONTACT_EMAIL_1
,EMERGENCY_CONTACT_NAME_2
,EMERGENCY_CONTACT_NUM_2
,EMERGENCY_CONTACT_EXTENSION_2
,EMERGENCY_CONTACT_DESC_2
,EMERGENCY_CONTACT_EMAIL_2
,HIRED_DT
,FULL_PART_TIME_CD
,NUM_HOURS
,LAST_REVIEW_DT
,NEXT_REVIEW_DT
,LAST_RAISE_DT
,TERMINATED_DT
,COMPENSATION_TYPE_CD
,YEARLY_SALARY
,HOURLY_WAGE
,INACTIVE_DT
,INACTIVE_REASON
,EXPIRATION_DT
,CONVERSION_DT
,CONVERSION_PRIOR_ACCOUNT_ID
,INSERTED_BY_CD
,INSERTED_DT
,UPDATED_BY_CD
,UPDATED_DT
,ROLE_FLGS
,FLGS
,TS
,INACTIVATED_BY_CD
,EMERGENCY_CONTACT_PHONE_COUNTRY_CD_1
,EMERGENCY_CONTACT_PHONE_COUNTRY_CD_2
,UNIQUE_GL_ACCOUNT_PAY_WRITE_OFF
,UNIQUE_CONTACT_NUM_BUSINESS_ACCOUNT
,UNIQUE_CONTACT_NUM_EMAIL_ACCOUNT_2
,UNIQUE_SMS_NUM
,EMPLOYEE_ID
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQENTITY AS INT64)
,SAFE_CAST(LOOKUPCODE AS STRING)
,SAFE_CAST(NAMEOF AS STRING)
,SAFE_CAST(UNIQCONTACTNAMEACCOUNT AS INT64)
,SAFE_CAST(UNIQCONTACTADDRESSACCOUNT AS INT64)
,SAFE_CAST(UNIQCONTACTNUMBERRESIDENCEACCOUNT AS INT64)
,SAFE_CAST(UNIQCONTACTNUMBERMOBILEACCOUNT AS INT64)
,SAFE_CAST(UNIQCONTACTNUMBERFAXACCOUNT AS INT64)
,SAFE_CAST(UNIQCONTACTNUMBEREMAILACCOUNT AS INT64)
,SAFE_CAST(DEPARTMENT AS STRING)
,SAFE_CAST(JOBTITLE AS STRING)
,SAFE_CAST(UNIQDOCUMENTSIGNATURE AS INT64)
,SAFE_CAST(COMMENTS AS STRING)
,SAFE_CAST(BATCHPAYMENTMETHODCODE AS STRING)
,SAFE_CAST(UNIQGLACCOUNTPAY AS INT64)
,SAFE_CAST(UNIQGLACCOUNTDEF AS INT64)
,SAFE_CAST(UNIQGLACCOUNTEXP AS INT64)
,SAFE_CAST(UNIQGLACCOUNTABILL AS INT64)
,SAFE_CAST(UNIQGLACCOUNTDBILL AS INT64)
,SAFE_CAST(EMERGENCYCONTACTNAME1 AS STRING)
,SAFE_CAST(EMERGENCYCONTACTNUMBER1 AS STRING)
,SAFE_CAST(EMERGENCYCONTACTEXTENSION1 AS STRING)
,SAFE_CAST(EMERGENCYCONTACTDESCRIPTION1 AS STRING)
,SAFE_CAST(EMERGENCYCONTACTEMAIL1 AS STRING)
,SAFE_CAST(EMERGENCYCONTACTNAME2 AS STRING)
,SAFE_CAST(EMERGENCYCONTACTNUMBER2 AS STRING)
,SAFE_CAST(EMERGENCYCONTACTEXTENSION2 AS STRING)
,SAFE_CAST(EMERGENCYCONTACTDESCRIPTION2 AS STRING)
,SAFE_CAST(EMERGENCYCONTACTEMAIL2 AS STRING)
,SAFE_CAST(HIREDDATE AS DATETIME)
,SAFE_CAST(FULLPARTTIMECODE AS STRING)
,SAFE_CAST(NUMBERHOURS AS INT64)
,SAFE_CAST(LASTREVIEWDATE AS DATETIME)
,SAFE_CAST(NEXTREVIEWDATE AS DATETIME)
,SAFE_CAST(LASTRAISEDATE AS DATETIME)
,SAFE_CAST(TERMINATEDDATE AS DATETIME)
,SAFE_CAST(COMPENSATIONTYPECODE AS STRING)
,SAFE_CAST(YEARLYSALARY AS FLOAT64)
,SAFE_CAST(HOURLYWAGE AS FLOAT64)
,SAFE_CAST(INACTIVEDATE AS DATETIME)
,SAFE_CAST(INACTIVEREASON AS STRING)
,SAFE_CAST(EXPIRATIONDATE AS DATETIME)
,SAFE_CAST(CONVERSIONDATE AS DATETIME)
,SAFE_CAST(CONVERSIONPRIORACCOUNTID AS STRING)
,SAFE_CAST(INSERTEDBYCODE AS STRING)
,SAFE_CAST(INSERTEDDATE AS DATETIME)
,SAFE_CAST(UPDATEDBYCODE AS STRING)
,SAFE_CAST(UPDATEDDATE AS DATETIME)
,SAFE_CAST(ROLEFLAGS AS INT64)
,SAFE_CAST(FLAGS AS INT64)
,SAFE_CAST(TS AS DATETIME)
,SAFE_CAST(INACTIVATEDBYCODE AS STRING)
,SAFE_CAST(EMERGENCYCONTACTPHONECOUNTRYCODE1 AS STRING)
,SAFE_CAST(EMERGENCYCONTACTPHONECOUNTRYCODE2 AS STRING)
,SAFE_CAST(UNIQGLACCOUNTPAYWRITEOFF AS INT64)
,SAFE_CAST(UNIQCONTACTNUMBERBUSINESSACCOUNT AS INT64)
,SAFE_CAST(UNIQCONTACTNUMBEREMAILACCOUNT2 AS INT64)
,SAFE_CAST(UNIQSMSNUMBER AS INT64)
,SAFE_CAST(EMPLOYEEID AS STRING)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
