MERGE `OPERATIONAL.AMS_COVERAGE` AS TGT
USING `LANDING.WORK_AMS_COVERAGE` AS SRC
ON TGT.UNIQUE_COVERAGE = SAFE_CAST(SRC.UNIQCOVERAGE AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_COVERAGE = SAFE_CAST(SRC.UNIQCOVERAGE AS INT64)
,TGT.CD = SAFE_CAST(SRC.CODE AS STRING)
,TGT.DESC_OF = SAFE_CAST(SRC.DESCRIPTIONOF AS STRING)
,TGT.UNIQUE_FORM_EDITION = SAFE_CAST(SRC.UNIQFORMEDITION AS INT64)
,TGT.LEVEL_CD = SAFE_CAST(SRC.LEVELCODE AS STRING)
,TGT.UNIQUE_FORM_EDITION_LANGUAGE_RESOURCE = SAFE_CAST(SRC.UNIQFORMEDITIONLANGUAGERESOURCE AS INT64)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_COVERAGE
,CD
,DESC_OF
,UNIQUE_FORM_EDITION
,LEVEL_CD
,UNIQUE_FORM_EDITION_LANGUAGE_RESOURCE
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQCOVERAGE AS INT64)
,SAFE_CAST(CODE AS STRING)
,SAFE_CAST(DESCRIPTIONOF AS STRING)
,SAFE_CAST(UNIQFORMEDITION AS INT64)
,SAFE_CAST(LEVELCODE AS STRING)
,SAFE_CAST(UNIQFORMEDITIONLANGUAGERESOURCE AS INT64)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
