MERGE `OPERATIONAL.AMS_CONFIGURE_LK_LANGUAGE_RESOURCE` AS TGT
USING `LANDING.WORK_AMS_CONFIGURE_LK_LANGUAGE_RESOURCE` AS SRC
ON UPPER(TRIM(TGT.CONFIGURE_LK_LANGUAGE_RESOURCE_ID)) = SAFE_CAST(UPPER(TRIM(SRC.CONFIGURELKLANGUAGERESOURCEID)) AS STRING)
AND UPPER(TRIM(TGT.CULTURE_CD)) = SAFE_CAST(UPPER(TRIM(SRC.CULTURECODE)) AS STRING)

WHEN MATCHED
THEN UPDATE SET
TGT.CONFIGURE_LK_LANGUAGE_RESOURCE_ID = SAFE_CAST(SRC.CONFIGURELKLANGUAGERESOURCEID AS STRING)
,TGT.CULTURE_CD = SAFE_CAST(SRC.CULTURECODE AS STRING)
,TGT.RESOURCE_TEXT = SAFE_CAST(SRC.RESOURCETEXT AS STRING)
,TGT.TABLE_NAME = SAFE_CAST(SRC.TABLENAME AS STRING)
,TGT.COLUMN_NAME = SAFE_CAST(SRC.COLUMNNAME AS STRING)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
CONFIGURE_LK_LANGUAGE_RESOURCE_ID
,CULTURE_CD
,RESOURCE_TEXT
,TABLE_NAME
,COLUMN_NAME
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(CONFIGURELKLANGUAGERESOURCEID AS STRING)
,SAFE_CAST(CULTURECODE AS STRING)
,SAFE_CAST(RESOURCETEXT AS STRING)
,SAFE_CAST(TABLENAME AS STRING)
,SAFE_CAST(COLUMNNAME AS STRING)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
