MERGE `OPERATIONAL.AMS_GENERAL_LEDGER` AS TGT
USING `LANDING.WORK_AMS_GENERAL_LEDGER` AS SRC
ON UPPER(TRIM(TGT.TYPE_REFER)) = SAFE_CAST(UPPER(TRIM(SRC.TYPEREFER)) AS STRING)
AND TGT.PAYMENT_GROUP_NUM = SAFE_CAST(SRC.PAYMENTGROUPNUMBER AS INT64)
AND TGT.LINE_NUM = SAFE_CAST(SRC.LINENUM AS INT64)
AND TGT.EFFECTIVE_DT = DATE(SAFE_CAST(SRC.EFFECTIVEDATE AS DATETIME))
AND UPPER(TRIM(TGT.GL_ACCOUNT)) = SAFE_CAST(UPPER(TRIM(SRC.GLACCOUNT)) AS STRING)
AND UPPER(TRIM(TGT.AGENCY_CD)) = SAFE_CAST(UPPER(TRIM(SRC.AGENCYCODE)) AS STRING)
AND UPPER(TRIM(TGT.DETAIL_DESC)) = SAFE_CAST(UPPER(TRIM(SRC.DETAILDESCRIPTION)) AS STRING)
AND TGT.DEBIT_AMT = SAFE_CAST(SRC.DEBITAMOUNT AS FLOAT64)
AND TGT.CREDIT_AMT = SAFE_CAST(SRC.CREDITAMOUNT AS FLOAT64)

WHEN MATCHED
THEN UPDATE SET
TGT.TYPE_REFER = SAFE_CAST(SRC.TYPEREFER AS STRING)
,TGT.PAYMENT_GROUP_NUM = SAFE_CAST(SRC.PAYMENTGROUPNUMBER AS INT64)
,TGT.LINE_NUM = SAFE_CAST(SRC.LINENUM AS INT64)
,TGT.SECURITY_FIELD = SAFE_CAST(SRC.SECURITYFIELD AS STRING)
,TGT.GL_ENTRY_TYPE = SAFE_CAST(SRC.GLENTRYTYPE AS STRING)
,TGT.REFER_NUM = SAFE_CAST(SRC.REFERNUMBER AS INT64)
,TGT.REVERSED_FLG = SAFE_CAST(SRC.REVERSEDFLAG AS STRING)
,TGT.EFFECTIVE_DT = DATE(SAFE_CAST(SRC.EFFECTIVEDATE AS DATETIME))
,TGT.ACCOUNTING_MONTH = SAFE_CAST(SRC.ACCOUNTINGMONTH AS STRING)
,TGT.CHECK_NUM_PAY_ID = SAFE_CAST(SRC.CHECKNUMBERPAYID AS STRING)
,TGT.GL_ACCOUNT = SAFE_CAST(SRC.GLACCOUNT AS STRING)
,TGT.AGENCY_CD = SAFE_CAST(SRC.AGENCYCODE AS STRING)
,TGT.BRANCH_CD = SAFE_CAST(SRC.BRANCHCODE AS STRING)
,TGT.DEPARTMENT_CD = SAFE_CAST(SRC.DEPARTMENTCODE AS STRING)
,TGT.PROFIT_CENTER_CD = SAFE_CAST(SRC.PROFITCENTERCODE AS STRING)
,TGT.PAY_EE_CD = SAFE_CAST(SRC.PAYEECODE AS STRING)
,TGT.VOID_NUM = SAFE_CAST(SRC.VOIDNUMBER AS STRING)
,TGT.SCHEDULE_CD = SAFE_CAST(SRC.SCHEDULECODE AS STRING)
,TGT.DETAIL_DESC = SAFE_CAST(SRC.DETAILDESCRIPTION AS STRING)
,TGT.DEBIT_AMT = SAFE_CAST(SRC.DEBITAMOUNT AS FLOAT64)
,TGT.CREDIT_AMT = SAFE_CAST(SRC.CREDITAMOUNT AS FLOAT64)
,TGT.GL_ENTRY_TYPE_DESC = SAFE_CAST(SRC.GLENTRYTYPEDESCRIPTION AS STRING)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
TYPE_REFER
,PAYMENT_GROUP_NUM
,LINE_NUM
,SECURITY_FIELD
,GL_ENTRY_TYPE
,REFER_NUM
,REVERSED_FLG
,EFFECTIVE_DT
,ACCOUNTING_MONTH
,CHECK_NUM_PAY_ID
,GL_ACCOUNT
,AGENCY_CD
,BRANCH_CD
,DEPARTMENT_CD
,PROFIT_CENTER_CD
,PAY_EE_CD
,VOID_NUM
,SCHEDULE_CD
,DETAIL_DESC
,DEBIT_AMT
,CREDIT_AMT
,GL_ENTRY_TYPE_DESC
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(TYPEREFER AS STRING)
,SAFE_CAST(PAYMENTGROUPNUMBER AS INT64)
,SAFE_CAST(LINENUM AS INT64)
,SAFE_CAST(SECURITYFIELD AS STRING)
,SAFE_CAST(GLENTRYTYPE AS STRING)
,SAFE_CAST(REFERNUMBER AS INT64)
,SAFE_CAST(REVERSEDFLAG AS STRING)
,DATE(SAFE_CAST(EFFECTIVEDATE AS DATETIME))
,SAFE_CAST(ACCOUNTINGMONTH AS STRING)
,SAFE_CAST(CHECKNUMBERPAYID AS STRING)
,SAFE_CAST(GLACCOUNT AS STRING)
,SAFE_CAST(AGENCYCODE AS STRING)
,SAFE_CAST(BRANCHCODE AS STRING)
,SAFE_CAST(DEPARTMENTCODE AS STRING)
,SAFE_CAST(PROFITCENTERCODE AS STRING)
,SAFE_CAST(PAYEECODE AS STRING)
,SAFE_CAST(VOIDNUMBER AS STRING)
,SAFE_CAST(SCHEDULECODE AS STRING)
,SAFE_CAST(DETAILDESCRIPTION AS STRING)
,SAFE_CAST(DEBITAMOUNT AS FLOAT64)
,SAFE_CAST(CREDITAMOUNT AS FLOAT64)
,SAFE_CAST(GLENTRYTYPEDESCRIPTION AS STRING)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
