MERGE `OPERATIONAL.AMS_CLIENT` AS TGT
USING `LANDING.WORK_AMS_CLIENT` AS SRC
ON TGT.UNIQUE_ENTITY = SAFE_CAST(SRC.UNIQENTITY AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_ENTITY = SAFE_CAST(SRC.UNIQENTITY AS INT64)
,TGT.LOOKUP_CD = SAFE_CAST(SRC.LOOKUPCODE AS STRING)
,TGT.NAME_OF = SAFE_CAST(SRC.NAMEOF AS STRING)
,TGT.TYPE_CD = SAFE_CAST(SRC.TYPECODE AS STRING)
,TGT.UNIQUE_CONTACT_NAME_PRIMARY = SAFE_CAST(SRC.UNIQCONTACTNAMEPRIMARY AS INT64)
,TGT.UNIQUE_CONTACT_ADDRESS_ACCOUNT = SAFE_CAST(SRC.UNIQCONTACTADDRESSACCOUNT AS INT64)
,TGT.UNIQUE_CONTACT_NUM_ACCOUNT = SAFE_CAST(SRC.UNIQCONTACTNUMBERACCOUNT AS INT64)
,TGT.UNIQUE_CONTACT_NAME_BUSINESS = SAFE_CAST(SRC.UNIQCONTACTNAMEBUSINESS AS INT64)
,TGT.UNIQUE_CONTACT_NUM_FAX_ACCOUNT = SAFE_CAST(SRC.UNIQCONTACTNUMBERFAXACCOUNT AS INT64)
,TGT.UNIQUE_CONTACT_NUM_WEB_ACCOUNT = SAFE_CAST(SRC.UNIQCONTACTNUMBERWEBACCOUNT AS INT64)
,TGT.UNIQUE_REPORT_INSTANCE_INVOICE_LAYOUT = SAFE_CAST(SRC.UNIQREPORTINSTANCEINVOICELAYOUT AS INT64)
,TGT.UNIQUE_REPORT_INSTANCE_STATEMENT_LAYOUT = SAFE_CAST(SRC.UNIQREPORTINSTANCESTATEMENTLAYOUT AS INT64)
,TGT.CD_COUNTRY_CD = SAFE_CAST(SRC.CDCOUNTRYCODE AS STRING)
,TGT.CD_CURRENCY_CD = SAFE_CAST(SRC.CDCURRENCYCODE AS STRING)
,TGT.COMMENTS = SAFE_CAST(SRC.COMMENTS AS STRING)
,TGT.IMPORT_MATCH_ID = SAFE_CAST(SRC.IMPORTMATCHID AS STRING)
,TGT.UNIQUE_BROKER = SAFE_CAST(SRC.UNIQBROKER AS INT64)
,TGT.CONVERSION_DT = SAFE_CAST(SRC.CONVERSIONDATE AS DATETIME)
,TGT.CONVERSION_PRIOR_ACCOUNT_ID = SAFE_CAST(SRC.CONVERSIONPRIORACCOUNTID AS STRING)
,TGT.STATEMENT_PAGE_BREAK_CD = SAFE_CAST(SRC.STATEMENTPAGEBREAKCODE AS STRING)
,TGT.INVOICE_PAGE_BREAK_CD = SAFE_CAST(SRC.INVOICEPAGEBREAKCODE AS STRING)
,TGT.INACTIVE_DT = SAFE_CAST(SRC.INACTIVEDATE AS DATETIME)
,TGT.INACTIVE_REASON = SAFE_CAST(SRC.INACTIVEREASON AS STRING)
,TGT.EXPIRATION_DT = SAFE_CAST(SRC.EXPIRATIONDATE AS DATETIME)
,TGT.INSERTED_BY_CD = SAFE_CAST(SRC.INSERTEDBYCODE AS STRING)
,TGT.INSERTED_DT = SAFE_CAST(SRC.INSERTEDDATE AS DATETIME)
,TGT.UPDATED_BY_CD = SAFE_CAST(SRC.UPDATEDBYCODE AS STRING)
,TGT.UPDATED_DT = SAFE_CAST(SRC.UPDATEDDATE AS DATETIME)
,TGT.FLGS = SAFE_CAST(SRC.FLAGS AS INT64)
,TGT.TS = SAFE_CAST(SRC.TS AS DATETIME)
,TGT.INACTIVATED_BY_CD = SAFE_CAST(SRC.INACTIVATEDBYCODE AS STRING)
,TGT.CLIENT_ID = SAFE_CAST(SRC.CLIENTID AS STRING)
,TGT.UNIQUE_CD_ACCOUNT_SOURCE = SAFE_CAST(SRC.UNIQCDACCOUNTSOURCE AS INT64)
,TGT.UNIQUE_CONTACT_NUM_EMAIL_ACCOUNT = SAFE_CAST(SRC.UNIQCONTACTNUMBEREMAILACCOUNT AS INT64)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_ENTITY
,LOOKUP_CD
,NAME_OF
,TYPE_CD
,UNIQUE_CONTACT_NAME_PRIMARY
,UNIQUE_CONTACT_ADDRESS_ACCOUNT
,UNIQUE_CONTACT_NUM_ACCOUNT
,UNIQUE_CONTACT_NAME_BUSINESS
,UNIQUE_CONTACT_NUM_FAX_ACCOUNT
,UNIQUE_CONTACT_NUM_WEB_ACCOUNT
,UNIQUE_REPORT_INSTANCE_INVOICE_LAYOUT
,UNIQUE_REPORT_INSTANCE_STATEMENT_LAYOUT
,CD_COUNTRY_CD
,CD_CURRENCY_CD
,COMMENTS
,IMPORT_MATCH_ID
,UNIQUE_BROKER
,CONVERSION_DT
,CONVERSION_PRIOR_ACCOUNT_ID
,STATEMENT_PAGE_BREAK_CD
,INVOICE_PAGE_BREAK_CD
,INACTIVE_DT
,INACTIVE_REASON
,EXPIRATION_DT
,INSERTED_BY_CD
,INSERTED_DT
,UPDATED_BY_CD
,UPDATED_DT
,FLGS
,TS
,INACTIVATED_BY_CD
,CLIENT_ID
,UNIQUE_CD_ACCOUNT_SOURCE
,UNIQUE_CONTACT_NUM_EMAIL_ACCOUNT
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQENTITY AS INT64)
,SAFE_CAST(LOOKUPCODE AS STRING)
,SAFE_CAST(NAMEOF AS STRING)
,SAFE_CAST(TYPECODE AS STRING)
,SAFE_CAST(UNIQCONTACTNAMEPRIMARY AS INT64)
,SAFE_CAST(UNIQCONTACTADDRESSACCOUNT AS INT64)
,SAFE_CAST(UNIQCONTACTNUMBERACCOUNT AS INT64)
,SAFE_CAST(UNIQCONTACTNAMEBUSINESS AS INT64)
,SAFE_CAST(UNIQCONTACTNUMBERFAXACCOUNT AS INT64)
,SAFE_CAST(UNIQCONTACTNUMBERWEBACCOUNT AS INT64)
,SAFE_CAST(UNIQREPORTINSTANCEINVOICELAYOUT AS INT64)
,SAFE_CAST(UNIQREPORTINSTANCESTATEMENTLAYOUT AS INT64)
,SAFE_CAST(CDCOUNTRYCODE AS STRING)
,SAFE_CAST(CDCURRENCYCODE AS STRING)
,SAFE_CAST(COMMENTS AS STRING)
,SAFE_CAST(IMPORTMATCHID AS STRING)
,SAFE_CAST(UNIQBROKER AS INT64)
,SAFE_CAST(CONVERSIONDATE AS DATETIME)
,SAFE_CAST(CONVERSIONPRIORACCOUNTID AS STRING)
,SAFE_CAST(STATEMENTPAGEBREAKCODE AS STRING)
,SAFE_CAST(INVOICEPAGEBREAKCODE AS STRING)
,SAFE_CAST(INACTIVEDATE AS DATETIME)
,SAFE_CAST(INACTIVEREASON AS STRING)
,SAFE_CAST(EXPIRATIONDATE AS DATETIME)
,SAFE_CAST(INSERTEDBYCODE AS STRING)
,SAFE_CAST(INSERTEDDATE AS DATETIME)
,SAFE_CAST(UPDATEDBYCODE AS STRING)
,SAFE_CAST(UPDATEDDATE AS DATETIME)
,SAFE_CAST(FLAGS AS INT64)
,SAFE_CAST(TS AS DATETIME)
,SAFE_CAST(INACTIVATEDBYCODE AS STRING)
,SAFE_CAST(CLIENTID AS STRING)
,SAFE_CAST(UNIQCDACCOUNTSOURCE AS INT64)
,SAFE_CAST(UNIQCONTACTNUMBEREMAILACCOUNT AS INT64)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
