MERGE `OPERATIONAL.AMS_VEHICLE_COVERAGE` AS TGT
USING `LANDING.WORK_AMS_VEHICLE_COVERAGE` AS SRC
ON TGT.UNIQUE_VEHICLE_COVERAGE = SAFE_CAST(SRC.UNIQVEHICLECOVERAGE AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_VEHICLE_COVERAGE = SAFE_CAST(SRC.UNIQVEHICLECOVERAGE AS INT64)
,TGT.UNIQUE_LINE_IMAGE = SAFE_CAST(SRC.UNIQLINEIMAGE AS INT64)
,TGT.UNIQUE_COVERAGE = SAFE_CAST(SRC.UNIQCOVERAGE AS INT64)
,TGT.UNIQUE_VEHICLE = SAFE_CAST(SRC.UNIQVEHICLE AS INT64)
,TGT.RATE_1 = SAFE_CAST(SRC.RATE1 AS FLOAT64)
,TGT.RATE_2 = SAFE_CAST(SRC.RATE2 AS FLOAT64)
,TGT.FULL_TERM_PREMIUM = SAFE_CAST(SRC.FULLTERMPREMIUM AS FLOAT64)
,TGT.NET_CHANGE_PREMIUM = SAFE_CAST(SRC.NETCHANGEPREMIUM AS FLOAT64)
,TGT.PREMIUM_1 = SAFE_CAST(SRC.PREMIUM1 AS FLOAT64)
,TGT.PREMIUM_2 = SAFE_CAST(SRC.PREMIUM2 AS FLOAT64)
,TGT.LIMIT_1 = SAFE_CAST(SRC.LIMIT1 AS STRING)
,TGT.LIMIT_2 = SAFE_CAST(SRC.LIMIT2 AS STRING)
,TGT.LIMIT_3 = SAFE_CAST(SRC.LIMIT3 AS STRING)
,TGT.LIMIT_4 = SAFE_CAST(SRC.LIMIT4 AS STRING)
,TGT.DED_1 = SAFE_CAST(SRC.DED1 AS STRING)
,TGT.DED_2 = SAFE_CAST(SRC.DED2 AS STRING)
,TGT.DED_3 = SAFE_CAST(SRC.DED3 AS STRING)
,TGT.DED_4 = SAFE_CAST(SRC.DED4 AS STRING)
,TGT.DED_TYPE_1 = SAFE_CAST(SRC.DEDTYPE1 AS STRING)
,TGT.DED_TYPE_2 = SAFE_CAST(SRC.DEDTYPE2 AS STRING)
,TGT.DED_TYPE_3 = SAFE_CAST(SRC.DEDTYPE3 AS STRING)
,TGT.DED_TYPE_4 = SAFE_CAST(SRC.DEDTYPE4 AS STRING)
,TGT.NUM_OF_1 = SAFE_CAST(SRC.NUMBEROF1 AS INT64)
,TGT.NUM_OF_2 = SAFE_CAST(SRC.NUMBEROF2 AS INT64)
,TGT.NUM_OF_3 = SAFE_CAST(SRC.NUMBEROF3 AS INT64)
,TGT.TYPE_OF_1 = SAFE_CAST(SRC.TYPEOF1 AS STRING)
,TGT.TYPE_OF_2 = SAFE_CAST(SRC.TYPEOF2 AS STRING)
,TGT.TYPE_OF_3 = SAFE_CAST(SRC.TYPEOF3 AS STRING)
,TGT.OPTION_CD_1 = SAFE_CAST(SRC.OPTIONCODE1 AS STRING)
,TGT.OPTION_CD_2 = SAFE_CAST(SRC.OPTIONCODE2 AS STRING)
,TGT.OPTION_CD_3 = SAFE_CAST(SRC.OPTIONCODE3 AS STRING)
,TGT.BEN_CD_1 = SAFE_CAST(SRC.BENCODE1 AS STRING)
,TGT.BEN_CD_2 = SAFE_CAST(SRC.BENCODE2 AS STRING)
,TGT.BEN_CD_3 = SAFE_CAST(SRC.BENCODE3 AS STRING)
,TGT.TERRITORY = SAFE_CAST(SRC.TERRITORY AS STRING)
,TGT.NUM_VALUE_1 = SAFE_CAST(SRC.NUMVALUE1 AS FLOAT64)
,TGT.NUM_VALUE_2 = SAFE_CAST(SRC.NUMVALUE2 AS FLOAT64)
,TGT.NUM_VALUE_3 = SAFE_CAST(SRC.NUMVALUE3 AS FLOAT64)
,TGT.DESC_1 = SAFE_CAST(SRC.DESCRIPTION1 AS STRING)
,TGT.DESC_2 = SAFE_CAST(SRC.DESCRIPTION2 AS STRING)
,TGT.DESC_3 = SAFE_CAST(SRC.DESCRIPTION3 AS STRING)
,TGT.LIMIT_TYPE_1 = SAFE_CAST(SRC.LIMITTYPE1 AS STRING)
,TGT.LIMIT_TYPE_2 = SAFE_CAST(SRC.LIMITTYPE2 AS STRING)
,TGT.LIMIT_TYPE_3 = SAFE_CAST(SRC.LIMITTYPE3 AS STRING)
,TGT.LIMIT_BASIS_1 = SAFE_CAST(SRC.LIMITBASIS1 AS STRING)
,TGT.LIMIT_BASIS_2 = SAFE_CAST(SRC.LIMITBASIS2 AS STRING)
,TGT.LIMIT_BASIS_3 = SAFE_CAST(SRC.LIMITBASIS3 AS STRING)
,TGT.DED_BASIS_1 = SAFE_CAST(SRC.DEDBASIS1 AS STRING)
,TGT.DED_BASIS_2 = SAFE_CAST(SRC.DEDBASIS2 AS STRING)
,TGT.DED_BASIS_3 = SAFE_CAST(SRC.DEDBASIS3 AS STRING)
,TGT.DED_BASIS_4 = SAFE_CAST(SRC.DEDBASIS4 AS STRING)
,TGT.DED_FACTOR = SAFE_CAST(SRC.DEDFACTOR AS INT64)
,TGT.YES_NO_1 = SAFE_CAST(SRC.YESNO1 AS STRING)
,TGT.YES_NO_2 = SAFE_CAST(SRC.YESNO2 AS STRING)
,TGT.INDUSTRY_CD_1 = SAFE_CAST(SRC.INDUSTRYCODE1 AS STRING)
,TGT.INDUSTRY_CD_2 = SAFE_CAST(SRC.INDUSTRYCODE2 AS STRING)
,TGT.INDUSTRY_CD_3 = SAFE_CAST(SRC.INDUSTRYCODE3 AS STRING)
,TGT.MISC_OPTION_CD_1 = SAFE_CAST(SRC.MISCOPTIONCODE1 AS STRING)
,TGT.MISC_OPTION_CD_2 = SAFE_CAST(SRC.MISCOPTIONCODE2 AS STRING)
,TGT.MISC_OPTION_CD_3 = SAFE_CAST(SRC.MISCOPTIONCODE3 AS STRING)
,TGT.RATING_BASIS_CD = SAFE_CAST(SRC.RATINGBASISCODE AS STRING)
,TGT.PERCENT_OF_COINS = SAFE_CAST(SRC.PERCENTOFCOINS AS FLOAT64)
,TGT.SYMBOL_1 = SAFE_CAST(SRC.SYMBOL1 AS STRING)
,TGT.SYMBOL_2 = SAFE_CAST(SRC.SYMBOL2 AS STRING)
,TGT.SYMBOL_3 = SAFE_CAST(SRC.SYMBOL3 AS STRING)
,TGT.SYMBOL_4 = SAFE_CAST(SRC.SYMBOL4 AS STRING)
,TGT.SYMBOL_5 = SAFE_CAST(SRC.SYMBOL5 AS STRING)
,TGT.SYMBOL_6 = SAFE_CAST(SRC.SYMBOL6 AS STRING)
,TGT.SYMBOL_7 = SAFE_CAST(SRC.SYMBOL7 AS STRING)
,TGT.SYMBOL_8 = SAFE_CAST(SRC.SYMBOL8 AS STRING)
,TGT.SYMBOL_9 = SAFE_CAST(SRC.SYMBOL9 AS STRING)
,TGT.MISC_PERCENT_1 = SAFE_CAST(SRC.MISCPERCENT1 AS FLOAT64)
,TGT.MISC_PERCENT_2 = SAFE_CAST(SRC.MISCPERCENT2 AS FLOAT64)
,TGT.MISC_PERCENT_3 = SAFE_CAST(SRC.MISCPERCENT3 AS FLOAT64)
,TGT.MISC_PERCENT_4 = SAFE_CAST(SRC.MISCPERCENT4 AS FLOAT64)
,TGT.DT_1 = SAFE_CAST(SRC.DATE1 AS DATETIME)
,TGT.DT_2 = SAFE_CAST(SRC.DATE2 AS DATETIME)
,TGT.INSERTED_BY_CD = SAFE_CAST(SRC.INSERTEDBYCODE AS STRING)
,TGT.INSERTED_DT = SAFE_CAST(SRC.INSERTEDDATE AS DATETIME)
,TGT.UPDATED_BY_CD = SAFE_CAST(SRC.UPDATEDBYCODE AS STRING)
,TGT.UPDATED_DT = SAFE_CAST(SRC.UPDATEDDATE AS DATETIME)
,TGT.FLGS = SAFE_CAST(SRC.FLAGS AS INT64)
,TGT.DT_3 = SAFE_CAST(SRC.DATE3 AS DATETIME)
,TGT.FORM_NUM = SAFE_CAST(SRC.FORMNUMBER AS STRING)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_VEHICLE_COVERAGE
,UNIQUE_LINE_IMAGE
,UNIQUE_COVERAGE
,UNIQUE_VEHICLE
,RATE_1
,RATE_2
,FULL_TERM_PREMIUM
,NET_CHANGE_PREMIUM
,PREMIUM_1
,PREMIUM_2
,LIMIT_1
,LIMIT_2
,LIMIT_3
,LIMIT_4
,DED_1
,DED_2
,DED_3
,DED_4
,DED_TYPE_1
,DED_TYPE_2
,DED_TYPE_3
,DED_TYPE_4
,NUM_OF_1
,NUM_OF_2
,NUM_OF_3
,TYPE_OF_1
,TYPE_OF_2
,TYPE_OF_3
,OPTION_CD_1
,OPTION_CD_2
,OPTION_CD_3
,BEN_CD_1
,BEN_CD_2
,BEN_CD_3
,TERRITORY
,NUM_VALUE_1
,NUM_VALUE_2
,NUM_VALUE_3
,DESC_1
,DESC_2
,DESC_3
,LIMIT_TYPE_1
,LIMIT_TYPE_2
,LIMIT_TYPE_3
,LIMIT_BASIS_1
,LIMIT_BASIS_2
,LIMIT_BASIS_3
,DED_BASIS_1
,DED_BASIS_2
,DED_BASIS_3
,DED_BASIS_4
,DED_FACTOR
,YES_NO_1
,YES_NO_2
,INDUSTRY_CD_1
,INDUSTRY_CD_2
,INDUSTRY_CD_3
,MISC_OPTION_CD_1
,MISC_OPTION_CD_2
,MISC_OPTION_CD_3
,RATING_BASIS_CD
,PERCENT_OF_COINS
,SYMBOL_1
,SYMBOL_2
,SYMBOL_3
,SYMBOL_4
,SYMBOL_5
,SYMBOL_6
,SYMBOL_7
,SYMBOL_8
,SYMBOL_9
,MISC_PERCENT_1
,MISC_PERCENT_2
,MISC_PERCENT_3
,MISC_PERCENT_4
,DT_1
,DT_2
,INSERTED_BY_CD
,INSERTED_DT
,UPDATED_BY_CD
,UPDATED_DT
,FLGS
,DT_3
,FORM_NUM
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQVEHICLECOVERAGE AS INT64)
,SAFE_CAST(UNIQLINEIMAGE AS INT64)
,SAFE_CAST(UNIQCOVERAGE AS INT64)
,SAFE_CAST(UNIQVEHICLE AS INT64)
,SAFE_CAST(RATE1 AS FLOAT64)
,SAFE_CAST(RATE2 AS FLOAT64)
,SAFE_CAST(FULLTERMPREMIUM AS FLOAT64)
,SAFE_CAST(NETCHANGEPREMIUM AS FLOAT64)
,SAFE_CAST(PREMIUM1 AS FLOAT64)
,SAFE_CAST(PREMIUM2 AS FLOAT64)
,SAFE_CAST(LIMIT1 AS STRING)
,SAFE_CAST(LIMIT2 AS STRING)
,SAFE_CAST(LIMIT3 AS STRING)
,SAFE_CAST(LIMIT4 AS STRING)
,SAFE_CAST(DED1 AS STRING)
,SAFE_CAST(DED2 AS STRING)
,SAFE_CAST(DED3 AS STRING)
,SAFE_CAST(DED4 AS STRING)
,SAFE_CAST(DEDTYPE1 AS STRING)
,SAFE_CAST(DEDTYPE2 AS STRING)
,SAFE_CAST(DEDTYPE3 AS STRING)
,SAFE_CAST(DEDTYPE4 AS STRING)
,SAFE_CAST(NUMBEROF1 AS INT64)
,SAFE_CAST(NUMBEROF2 AS INT64)
,SAFE_CAST(NUMBEROF3 AS INT64)
,SAFE_CAST(TYPEOF1 AS STRING)
,SAFE_CAST(TYPEOF2 AS STRING)
,SAFE_CAST(TYPEOF3 AS STRING)
,SAFE_CAST(OPTIONCODE1 AS STRING)
,SAFE_CAST(OPTIONCODE2 AS STRING)
,SAFE_CAST(OPTIONCODE3 AS STRING)
,SAFE_CAST(BENCODE1 AS STRING)
,SAFE_CAST(BENCODE2 AS STRING)
,SAFE_CAST(BENCODE3 AS STRING)
,SAFE_CAST(TERRITORY AS STRING)
,SAFE_CAST(NUMVALUE1 AS FLOAT64)
,SAFE_CAST(NUMVALUE2 AS FLOAT64)
,SAFE_CAST(NUMVALUE3 AS FLOAT64)
,SAFE_CAST(DESCRIPTION1 AS STRING)
,SAFE_CAST(DESCRIPTION2 AS STRING)
,SAFE_CAST(DESCRIPTION3 AS STRING)
,SAFE_CAST(LIMITTYPE1 AS STRING)
,SAFE_CAST(LIMITTYPE2 AS STRING)
,SAFE_CAST(LIMITTYPE3 AS STRING)
,SAFE_CAST(LIMITBASIS1 AS STRING)
,SAFE_CAST(LIMITBASIS2 AS STRING)
,SAFE_CAST(LIMITBASIS3 AS STRING)
,SAFE_CAST(DEDBASIS1 AS STRING)
,SAFE_CAST(DEDBASIS2 AS STRING)
,SAFE_CAST(DEDBASIS3 AS STRING)
,SAFE_CAST(DEDBASIS4 AS STRING)
,SAFE_CAST(DEDFACTOR AS INT64)
,SAFE_CAST(YESNO1 AS STRING)
,SAFE_CAST(YESNO2 AS STRING)
,SAFE_CAST(INDUSTRYCODE1 AS STRING)
,SAFE_CAST(INDUSTRYCODE2 AS STRING)
,SAFE_CAST(INDUSTRYCODE3 AS STRING)
,SAFE_CAST(MISCOPTIONCODE1 AS STRING)
,SAFE_CAST(MISCOPTIONCODE2 AS STRING)
,SAFE_CAST(MISCOPTIONCODE3 AS STRING)
,SAFE_CAST(RATINGBASISCODE AS STRING)
,SAFE_CAST(PERCENTOFCOINS AS FLOAT64)
,SAFE_CAST(SYMBOL1 AS STRING)
,SAFE_CAST(SYMBOL2 AS STRING)
,SAFE_CAST(SYMBOL3 AS STRING)
,SAFE_CAST(SYMBOL4 AS STRING)
,SAFE_CAST(SYMBOL5 AS STRING)
,SAFE_CAST(SYMBOL6 AS STRING)
,SAFE_CAST(SYMBOL7 AS STRING)
,SAFE_CAST(SYMBOL8 AS STRING)
,SAFE_CAST(SYMBOL9 AS STRING)
,SAFE_CAST(MISCPERCENT1 AS FLOAT64)
,SAFE_CAST(MISCPERCENT2 AS FLOAT64)
,SAFE_CAST(MISCPERCENT3 AS FLOAT64)
,SAFE_CAST(MISCPERCENT4 AS FLOAT64)
,SAFE_CAST(DATE1 AS DATETIME)
,SAFE_CAST(DATE2 AS DATETIME)
,SAFE_CAST(INSERTEDBYCODE AS STRING)
,SAFE_CAST(INSERTEDDATE AS DATETIME)
,SAFE_CAST(UPDATEDBYCODE AS STRING)
,SAFE_CAST(UPDATEDDATE AS DATETIME)
,SAFE_CAST(FLAGS AS INT64)
,SAFE_CAST(DATE3 AS DATETIME)
,SAFE_CAST(FORMNUMBER AS STRING)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
