MERGE `OPERATIONAL.AMS_PA_ADDITIONAL_COVERAGE` AS TGT
USING `LANDING.WORK_AMS_PA_ADDITIONAL_COVERAGE` AS SRC
ON TGT.UNIQUE_PA_ADDITIONAL_COVERAGE = SAFE_CAST(SRC.UNIQPAADDITIONALCOVERAGE AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_PA_ADDITIONAL_COVERAGE = SAFE_CAST(SRC.UNIQPAADDITIONALCOVERAGE AS INT64)
,TGT.UNIQUE_PA_IMAGE = SAFE_CAST(SRC.UNIQPAIMAGE AS INT64)
,TGT.UNIQUE_PA_VEHICLE = SAFE_CAST(SRC.UNIQPAVEHICLE AS INT64)
,TGT.LK_ADDITIONAL_COVERAGE_CD = SAFE_CAST(SRC.LKADDITIONALCOVERAGECODE AS STRING)
,TGT.DESC_OF = SAFE_CAST(SRC.DESCRIPTIONOF AS STRING)
,TGT.LIMIT_1 = SAFE_CAST(SRC.LIMIT1 AS STRING)
,TGT.LIMIT_2 = SAFE_CAST(SRC.LIMIT2 AS STRING)
,TGT.DEDUCTIBLE_1 = SAFE_CAST(SRC.DEDUCTIBLE1 AS STRING)
,TGT.DED_TYPE_1 = SAFE_CAST(SRC.DEDTYPE1 AS STRING)
,TGT.OPTION_CD_1 = SAFE_CAST(SRC.OPTIONCODE1 AS STRING)
,TGT.OPTION_CD_2 = SAFE_CAST(SRC.OPTIONCODE2 AS STRING)
,TGT.OPTION_CD_3 = SAFE_CAST(SRC.OPTIONCODE3 AS STRING)
,TGT.BEN_CD_1 = SAFE_CAST(SRC.BENCODE1 AS STRING)
,TGT.PREMIUM_1 = SAFE_CAST(SRC.PREMIUM1 AS FLOAT64)
,TGT.TYPE_OF_1 = SAFE_CAST(SRC.TYPEOF1 AS STRING)
,TGT.TYPE_OF_2 = SAFE_CAST(SRC.TYPEOF2 AS STRING)
,TGT.INSERTED_BY_CD = SAFE_CAST(SRC.INSERTEDBYCODE AS STRING)
,TGT.INSERTED_DT = SAFE_CAST(SRC.INSERTEDDATE AS DATETIME)
,TGT.UPDATED_BY_CD = SAFE_CAST(SRC.UPDATEDBYCODE AS STRING)
,TGT.UPDATED_DT = SAFE_CAST(SRC.UPDATEDDATE AS DATETIME)
,TGT.BEN_CD_2 = SAFE_CAST(SRC.BENCODE2 AS STRING)
,TGT.BEN_CD_3 = SAFE_CAST(SRC.BENCODE3 AS STRING)
,TGT.NUM_OF = SAFE_CAST(SRC.NUMBEROF AS INT64)
,TGT.COV_EFFECTIVE_DT = SAFE_CAST(SRC.COVEFFECTIVEDATE AS DATETIME)
,TGT.COV_EXPIRATION_DT = SAFE_CAST(SRC.COVEXPIRATIONDATE AS DATETIME)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_PA_ADDITIONAL_COVERAGE
,UNIQUE_PA_IMAGE
,UNIQUE_PA_VEHICLE
,LK_ADDITIONAL_COVERAGE_CD
,DESC_OF
,LIMIT_1
,LIMIT_2
,DEDUCTIBLE_1
,DED_TYPE_1
,OPTION_CD_1
,OPTION_CD_2
,OPTION_CD_3
,BEN_CD_1
,PREMIUM_1
,TYPE_OF_1
,TYPE_OF_2
,INSERTED_BY_CD
,INSERTED_DT
,UPDATED_BY_CD
,UPDATED_DT
,BEN_CD_2
,BEN_CD_3
,NUM_OF
,COV_EFFECTIVE_DT
,COV_EXPIRATION_DT
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQPAADDITIONALCOVERAGE AS INT64)
,SAFE_CAST(UNIQPAIMAGE AS INT64)
,SAFE_CAST(UNIQPAVEHICLE AS INT64)
,SAFE_CAST(LKADDITIONALCOVERAGECODE AS STRING)
,SAFE_CAST(DESCRIPTIONOF AS STRING)
,SAFE_CAST(LIMIT1 AS STRING)
,SAFE_CAST(LIMIT2 AS STRING)
,SAFE_CAST(DEDUCTIBLE1 AS STRING)
,SAFE_CAST(DEDTYPE1 AS STRING)
,SAFE_CAST(OPTIONCODE1 AS STRING)
,SAFE_CAST(OPTIONCODE2 AS STRING)
,SAFE_CAST(OPTIONCODE3 AS STRING)
,SAFE_CAST(BENCODE1 AS STRING)
,SAFE_CAST(PREMIUM1 AS FLOAT64)
,SAFE_CAST(TYPEOF1 AS STRING)
,SAFE_CAST(TYPEOF2 AS STRING)
,SAFE_CAST(INSERTEDBYCODE AS STRING)
,SAFE_CAST(INSERTEDDATE AS DATETIME)
,SAFE_CAST(UPDATEDBYCODE AS STRING)
,SAFE_CAST(UPDATEDDATE AS DATETIME)
,SAFE_CAST(BENCODE2 AS STRING)
,SAFE_CAST(BENCODE3 AS STRING)
,SAFE_CAST(NUMBEROF AS INT64)
,SAFE_CAST(COVEFFECTIVEDATE AS DATETIME)
,SAFE_CAST(COVEXPIRATIONDATE AS DATETIME)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
