MERGE `OPERATIONAL.AMS_PA_IMAGE` AS TGT
USING `LANDING.WORK_AMS_PA_IMAGE` AS SRC
ON TGT.UNIQUE_PA_IMAGE = SAFE_CAST(SRC.UNIQPAIMAGE AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_PA_IMAGE = SAFE_CAST(SRC.UNIQPAIMAGE AS INT64)
,TGT.UNIQUE_LINE_IMAGE = SAFE_CAST(SRC.UNIQLINEIMAGE AS INT64)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_PA_IMAGE
,UNIQUE_LINE_IMAGE
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQPAIMAGE AS INT64)
,SAFE_CAST(UNIQLINEIMAGE AS INT64)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
