MERGE `OPERATIONAL.AMS_LINE_BROKER_PRODUCER` AS TGT
USING `LANDING.WORK_AMS_LINE_BROKER_PRODUCER` AS SRC
ON TGT.UNIQUE_LINE_BROKER_PRODUCER = SAFE_CAST(SRC.UNIQLINEBROKERPRODUCER AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_LINE_BROKER_PRODUCER = SAFE_CAST(SRC.UNIQLINEBROKERPRODUCER AS INT64)
,TGT.UNIQUE_LINE = SAFE_CAST(SRC.UNIQLINE AS INT64)
,TGT.UNIQUE_BROKER = SAFE_CAST(SRC.UNIQBROKER AS INT64)
,TGT.UNIQUE_PRODUCER = SAFE_CAST(SRC.UNIQPRODUCER AS INT64)
,TGT.COMMISSION_TYPE_CD = SAFE_CAST(SRC.COMMISSIONTYPECODE AS STRING)
,TGT.COMMISSION_PERCENT = SAFE_CAST(SRC.COMMISSIONPERCENT AS FLOAT64)
,TGT.COMMISSION = SAFE_CAST(SRC.COMMISSION AS FLOAT64)
,TGT.PRODUCTION_CREDIT_PERCENT = SAFE_CAST(SRC.PRODUCTIONCREDITPERCENT AS FLOAT64)
,TGT.UNIQUE_COMMISSION_AGREEMENT = SAFE_CAST(SRC.UNIQCOMMISSIONAGREEMENT AS INT64)
,TGT.BILLED_COMMISSION = SAFE_CAST(SRC.BILLEDCOMMISSION AS FLOAT64)
,TGT.ANNUALIZED_COMMISSION = SAFE_CAST(SRC.ANNUALIZEDCOMMISSION AS FLOAT64)
,TGT.ESTIMATED_COMMISSION = SAFE_CAST(SRC.ESTIMATEDCOMMISSION AS FLOAT64)
,TGT.SCREEN_ORDER = SAFE_CAST(SRC.SCREENORDER AS INT64)
,TGT.FLGS = SAFE_CAST(SRC.FLAGS AS INT64)
,TGT.UNIQUE_COMPANY_CONTRACT = SAFE_CAST(SRC.UNIQCOMPANYCONTRACT AS INT64)
,TGT.REVENUE_PERCENT = SAFE_CAST(SRC.REVENUEPERCENT AS FLOAT64)
,TGT.UNIQUE_REVENUE_AGENCY = SAFE_CAST(SRC.UNIQREVENUEAGENCY AS INT64)
,TGT.UNIQUE_REVENUE_BRANCH = SAFE_CAST(SRC.UNIQREVENUEBRANCH AS INT64)
,TGT.UNIQUE_REVENUE_DEPARTMENT = SAFE_CAST(SRC.UNIQREVENUEDEPARTMENT AS INT64)
,TGT.UNIQUE_REVENUE_PROFIT_CENTER = SAFE_CAST(SRC.UNIQREVENUEPROFITCENTER AS INT64)
,TGT.INSERTED_BY_CD = SAFE_CAST(SRC.INSERTEDBYCODE AS STRING)
,TGT.INSERTED_DT = SAFE_CAST(SRC.INSERTEDDATE AS DATETIME)
,TGT.UPDATED_BY_CD = SAFE_CAST(SRC.UPDATEDBYCODE AS STRING)
,TGT.UPDATED_DT = SAFE_CAST(SRC.UPDATEDDATE AS DATETIME)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_LINE_BROKER_PRODUCER
,UNIQUE_LINE
,UNIQUE_BROKER
,UNIQUE_PRODUCER
,COMMISSION_TYPE_CD
,COMMISSION_PERCENT
,COMMISSION
,PRODUCTION_CREDIT_PERCENT
,UNIQUE_COMMISSION_AGREEMENT
,BILLED_COMMISSION
,ANNUALIZED_COMMISSION
,ESTIMATED_COMMISSION
,SCREEN_ORDER
,FLGS
,UNIQUE_COMPANY_CONTRACT
,REVENUE_PERCENT
,UNIQUE_REVENUE_AGENCY
,UNIQUE_REVENUE_BRANCH
,UNIQUE_REVENUE_DEPARTMENT
,UNIQUE_REVENUE_PROFIT_CENTER
,INSERTED_BY_CD
,INSERTED_DT
,UPDATED_BY_CD
,UPDATED_DT
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQLINEBROKERPRODUCER AS INT64)
,SAFE_CAST(UNIQLINE AS INT64)
,SAFE_CAST(UNIQBROKER AS INT64)
,SAFE_CAST(UNIQPRODUCER AS INT64)
,SAFE_CAST(COMMISSIONTYPECODE AS STRING)
,SAFE_CAST(COMMISSIONPERCENT AS FLOAT64)
,SAFE_CAST(COMMISSION AS FLOAT64)
,SAFE_CAST(PRODUCTIONCREDITPERCENT AS FLOAT64)
,SAFE_CAST(UNIQCOMMISSIONAGREEMENT AS INT64)
,SAFE_CAST(BILLEDCOMMISSION AS FLOAT64)
,SAFE_CAST(ANNUALIZEDCOMMISSION AS FLOAT64)
,SAFE_CAST(ESTIMATEDCOMMISSION AS FLOAT64)
,SAFE_CAST(SCREENORDER AS INT64)
,SAFE_CAST(FLAGS AS INT64)
,SAFE_CAST(UNIQCOMPANYCONTRACT AS INT64)
,SAFE_CAST(REVENUEPERCENT AS FLOAT64)
,SAFE_CAST(UNIQREVENUEAGENCY AS INT64)
,SAFE_CAST(UNIQREVENUEBRANCH AS INT64)
,SAFE_CAST(UNIQREVENUEDEPARTMENT AS INT64)
,SAFE_CAST(UNIQREVENUEPROFITCENTER AS INT64)
,SAFE_CAST(INSERTEDBYCODE AS STRING)
,SAFE_CAST(INSERTEDDATE AS DATETIME)
,SAFE_CAST(UPDATEDBYCODE AS STRING)
,SAFE_CAST(UPDATEDDATE AS DATETIME)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
