MERGE `OPERATIONAL.AMS_CLIENT_AGENCY_BRANCH_JT` AS TGT
USING `LANDING.WORK_AMS_CLIENT_AGENCY_BRANCH_JT` AS SRC
ON TGT.UNIQUE_ENTITY = SAFE_CAST(SRC.UNIQENTITY AS INT64)
AND TGT.UNIQUE_AGENCY = SAFE_CAST(SRC.UNIQAGENCY AS INT64)
AND TGT.UNIQUE_BRANCH = SAFE_CAST(SRC.UNIQBRANCH AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_ENTITY = SAFE_CAST(SRC.UNIQENTITY AS INT64)
,TGT.UNIQUE_AGENCY = SAFE_CAST(SRC.UNIQAGENCY AS INT64)
,TGT.UNIQUE_BRANCH = SAFE_CAST(SRC.UNIQBRANCH AS INT64)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_ENTITY
,UNIQUE_AGENCY
,UNIQUE_BRANCH
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQENTITY AS INT64)
,SAFE_CAST(UNIQAGENCY AS INT64)
,SAFE_CAST(UNIQBRANCH AS INT64)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
