MERGE `OPERATIONAL.AMS_RS_ADDITIONAL_INTEREST` AS TGT
USING `LANDING.WORK_AMS_RS_ADDITIONAL_INTEREST` AS SRC
ON TGT.UNIQUE_RS_ADDITIONAL_INTEREST = SAFE_CAST(SRC.UNIQRSADDITIONALINTEREST AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_RS_ADDITIONAL_INTEREST = SAFE_CAST(SRC.UNIQRSADDITIONALINTEREST AS INT64)
,TGT.UNIQUE_FIXED_RS_ADDITIONAL_INTEREST = SAFE_CAST(SRC.UNIQFIXEDRSADDITIONALINTEREST AS INT64)
,TGT.UNIQUE_RS_IMAGE = SAFE_CAST(SRC.UNIQRSIMAGE AS INT64)
,TGT.UNIQUE_ENTITY = SAFE_CAST(SRC.UNIQENTITY AS INT64)
,TGT.NAME_OF = SAFE_CAST(SRC.NAMEOF AS STRING)
,TGT.ADDRESS_1 = SAFE_CAST(SRC.ADDRESS1 AS STRING)
,TGT.ADDRESS_2 = SAFE_CAST(SRC.ADDRESS2 AS STRING)
,TGT.ADDRESS_3 = SAFE_CAST(SRC.ADDRESS3 AS STRING)
,TGT.CITY = SAFE_CAST(SRC.CITY AS STRING)
,TGT.POSTAL_CD = SAFE_CAST(SRC.POSTALCODE AS STRING)
,TGT.CD_STATE_CD = SAFE_CAST(SRC.CDSTATECODE AS STRING)
,TGT.COUNTY = SAFE_CAST(SRC.COUNTY AS STRING)
,TGT.CD_COUNTRY_CD = SAFE_CAST(SRC.CDCOUNTRYCODE AS STRING)
,TGT.PHONE_NUM = SAFE_CAST(SRC.PHONENUMBER AS STRING)
,TGT.PHONE_EXTENSION = SAFE_CAST(SRC.PHONEEXTENSION AS STRING)
,TGT.RANK_NUM = SAFE_CAST(SRC.RANKNUMBER AS INT64)
,TGT.INTEREST_CD = SAFE_CAST(SRC.INTERESTCODE AS STRING)
,TGT.INTEREST_OTHER = SAFE_CAST(SRC.INTERESTOTHER AS STRING)
,TGT.REFERENCE_LOAN_NUM = SAFE_CAST(SRC.REFERENCELOANNUMBER AS STRING)
,TGT.INSERTED_BY_CD = SAFE_CAST(SRC.INSERTEDBYCODE AS STRING)
,TGT.INSERTED_DT = SAFE_CAST(SRC.INSERTEDDATE AS DATETIME)
,TGT.UPDATED_BY_CD = SAFE_CAST(SRC.UPDATEDBYCODE AS STRING)
,TGT.UPDATED_DT = SAFE_CAST(SRC.UPDATEDDATE AS DATETIME)
,TGT.FLGS = SAFE_CAST(SRC.FLAGS AS INT64)
,TGT.UNIQUE_RS_INSURANCE_REQUESTED = SAFE_CAST(SRC.UNIQRSINSURANCEREQUESTED AS INT64)
,TGT.FAX_NUM = SAFE_CAST(SRC.FAXNUMBER AS STRING)
,TGT.EMAIL = SAFE_CAST(SRC.EMAIL AS STRING)
,TGT.REASON_FOR_INT = SAFE_CAST(SRC.REASONFORINT AS STRING)
,TGT.LIEN_AMT = SAFE_CAST(SRC.LIENAMOUNT AS INT64)
,TGT.INTEREST_END_DT = SAFE_CAST(SRC.INTERESTENDDATE AS DATETIME)
,TGT.PHONE_COUNTRY_CD = SAFE_CAST(SRC.PHONECOUNTRYCODE AS STRING)
,TGT.FAX_PHONE_COUNTRY_CD = SAFE_CAST(SRC.FAXPHONECOUNTRYCODE AS STRING)
,TGT.REGION_PROVINCE = SAFE_CAST(SRC.REGIONPROVINCE AS STRING)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_RS_ADDITIONAL_INTEREST
,UNIQUE_FIXED_RS_ADDITIONAL_INTEREST
,UNIQUE_RS_IMAGE
,UNIQUE_ENTITY
,NAME_OF
,ADDRESS_1
,ADDRESS_2
,ADDRESS_3
,CITY
,POSTAL_CD
,CD_STATE_CD
,COUNTY
,CD_COUNTRY_CD
,PHONE_NUM
,PHONE_EXTENSION
,RANK_NUM
,INTEREST_CD
,INTEREST_OTHER
,REFERENCE_LOAN_NUM
,INSERTED_BY_CD
,INSERTED_DT
,UPDATED_BY_CD
,UPDATED_DT
,FLGS
,UNIQUE_RS_INSURANCE_REQUESTED
,FAX_NUM
,EMAIL
,REASON_FOR_INT
,LIEN_AMT
,INTEREST_END_DT
,PHONE_COUNTRY_CD
,FAX_PHONE_COUNTRY_CD
,REGION_PROVINCE
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQRSADDITIONALINTEREST AS INT64)
,SAFE_CAST(UNIQFIXEDRSADDITIONALINTEREST AS INT64)
,SAFE_CAST(UNIQRSIMAGE AS INT64)
,SAFE_CAST(UNIQENTITY AS INT64)
,SAFE_CAST(NAMEOF AS STRING)
,SAFE_CAST(ADDRESS1 AS STRING)
,SAFE_CAST(ADDRESS2 AS STRING)
,SAFE_CAST(ADDRESS3 AS STRING)
,SAFE_CAST(CITY AS STRING)
,SAFE_CAST(POSTALCODE AS STRING)
,SAFE_CAST(CDSTATECODE AS STRING)
,SAFE_CAST(COUNTY AS STRING)
,SAFE_CAST(CDCOUNTRYCODE AS STRING)
,SAFE_CAST(PHONENUMBER AS STRING)
,SAFE_CAST(PHONEEXTENSION AS STRING)
,SAFE_CAST(RANKNUMBER AS INT64)
,SAFE_CAST(INTERESTCODE AS STRING)
,SAFE_CAST(INTERESTOTHER AS STRING)
,SAFE_CAST(REFERENCELOANNUMBER AS STRING)
,SAFE_CAST(INSERTEDBYCODE AS STRING)
,SAFE_CAST(INSERTEDDATE AS DATETIME)
,SAFE_CAST(UPDATEDBYCODE AS STRING)
,SAFE_CAST(UPDATEDDATE AS DATETIME)
,SAFE_CAST(FLAGS AS INT64)
,SAFE_CAST(UNIQRSINSURANCEREQUESTED AS INT64)
,SAFE_CAST(FAXNUMBER AS STRING)
,SAFE_CAST(EMAIL AS STRING)
,SAFE_CAST(REASONFORINT AS STRING)
,SAFE_CAST(LIENAMOUNT AS INT64)
,SAFE_CAST(INTERESTENDDATE AS DATETIME)
,SAFE_CAST(PHONECOUNTRYCODE AS STRING)
,SAFE_CAST(FAXPHONECOUNTRYCODE AS STRING)
,SAFE_CAST(REGIONPROVINCE AS STRING)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
