MERGE `OPERATIONAL.AMS_PA_DRIVER` AS TGT
USING `LANDING.WORK_AMS_PA_DRIVER` AS SRC
ON TGT.UNIQUE_PA_DRIVER = SAFE_CAST(SRC.UNIQPADRIVER AS INT64)

WHEN MATCHED
THEN UPDATE SET
TGT.UNIQUE_PA_DRIVER = SAFE_CAST(SRC.UNIQPADRIVER AS INT64)
,TGT.UNIQUE_FIXED_PA_DRIVER = SAFE_CAST(SRC.UNIQFIXEDPADRIVER AS INT64)
,TGT.UNIQUE_PA_IMAGE = SAFE_CAST(SRC.UNIQPAIMAGE AS INT64)
,TGT.DRIVER_NUM = SAFE_CAST(SRC.DRIVERNUMBER AS INT64)
,TGT.COMPANY_DRIVER_NUM = SAFE_CAST(SRC.COMPANYDRIVERNUMBER AS INT64)
,TGT.NAME_OF = SAFE_CAST(SRC.NAMEOF AS STRING)
,TGT.LK_PREFIX = SAFE_CAST(SRC.LKPREFIX AS STRING)
,TGT.FIRST_NAME = SAFE_CAST(SRC.FIRSTNAME AS STRING)
,TGT.MIDDLE_NAME = SAFE_CAST(SRC.MIDDLENAME AS STRING)
,TGT.LAST_NAME = SAFE_CAST(SRC.LASTNAME AS STRING)
,TGT.LK_SUFFIX = SAFE_CAST(SRC.LKSUFFIX AS STRING)
,TGT.GENDER_CD = SAFE_CAST(SRC.GENDERCODE AS STRING)
,TGT.MARITAL_STATUS_CD = SAFE_CAST(SRC.MARITALSTATUSCODE AS STRING)
,TGT.RELATION_TO_APPLICANT_CD = SAFE_CAST(SRC.RELATIONTOAPPLICANTCODE AS STRING)
,TGT.BIRTH_DT = SAFE_CAST(SRC.BIRTHDATE AS DATETIME)
,TGT.OCCUPATION = SAFE_CAST(SRC.OCCUPATION AS STRING)
,TGT.SSN = SAFE_CAST(SRC.SSN AS STRING)
,TGT.LICENSE_NUM = SAFE_CAST(SRC.LICENSENUMBER AS STRING)
,TGT.LICENSED_STATE = SAFE_CAST(SRC.LICENSEDSTATE AS STRING)
,TGT.DRIVER_TYPE_CD = SAFE_CAST(SRC.DRIVERTYPECODE AS STRING)
,TGT.LICENSED_DT = SAFE_CAST(SRC.LICENSEDDATE AS DATETIME)
,TGT.FIRST_LICENSED_MA_DT = SAFE_CAST(SRC.FIRSTLICENSEDMADATE AS DATETIME)
,TGT.FIRST_LICENSED_OTHER_DT = SAFE_CAST(SRC.FIRSTLICENSEDOTHERDATE AS DATETIME)
,TGT.FIRST_LICENSED_MOTORCYCLE_DT = SAFE_CAST(SRC.FIRSTLICENSEDMOTORCYCLEDATE AS DATETIME)
,TGT.GOOD_STUDENT_CD = SAFE_CAST(SRC.GOODSTUDENTCODE AS STRING)
,TGT.DRIVER_TRAINING_CD = SAFE_CAST(SRC.DRIVERTRAININGCODE AS STRING)
,TGT.ACCIDENT_PREVENTION_COURSE_DT = SAFE_CAST(SRC.ACCIDENTPREVENTIONCOURSEDATE AS DATETIME)
,TGT.SDIP_POINTS = SAFE_CAST(SRC.SDIPPOINTS AS INT64)
,TGT.INSERTED_BY_CD = SAFE_CAST(SRC.INSERTEDBYCODE AS STRING)
,TGT.INSERTED_DT = SAFE_CAST(SRC.INSERTEDDATE AS DATETIME)
,TGT.UPDATED_BY_CD = SAFE_CAST(SRC.UPDATEDBYCODE AS STRING)
,TGT.UPDATED_DT = SAFE_CAST(SRC.UPDATEDDATE AS DATETIME)
,TGT.FLGS = SAFE_CAST(SRC.FLAGS AS INT64)
,TGT.JOB_RUN_ID = SAFE_CAST(SRC.JOBRUNID AS STRING)
--,TGT.CREATE_DTTIME = CURRENT_DATETIME()
,TGT.UPDATE_DTTIME = CURRENT_DATETIME()
--,TGT.SOURCE_SYSTEM_CD = 'AMS'

WHEN NOT MATCHED
THEN INSERT ( --Target column names
UNIQUE_PA_DRIVER
,UNIQUE_FIXED_PA_DRIVER
,UNIQUE_PA_IMAGE
,DRIVER_NUM
,COMPANY_DRIVER_NUM
,NAME_OF
,LK_PREFIX
,FIRST_NAME
,MIDDLE_NAME
,LAST_NAME
,LK_SUFFIX
,GENDER_CD
,MARITAL_STATUS_CD
,RELATION_TO_APPLICANT_CD
,BIRTH_DT
,OCCUPATION
,SSN
,LICENSE_NUM
,LICENSED_STATE
,DRIVER_TYPE_CD
,LICENSED_DT
,FIRST_LICENSED_MA_DT
,FIRST_LICENSED_OTHER_DT
,FIRST_LICENSED_MOTORCYCLE_DT
,GOOD_STUDENT_CD
,DRIVER_TRAINING_CD
,ACCIDENT_PREVENTION_COURSE_DT
,SDIP_POINTS
,INSERTED_BY_CD
,INSERTED_DT
,UPDATED_BY_CD
,UPDATED_DT
,FLGS
,JOB_RUN_ID
,CREATE_DTTIME
,UPDATE_DTTIME
,SOURCE_SYSTEM_CD
)

VALUES ( --Source values
SAFE_CAST(UNIQPADRIVER AS INT64)
,SAFE_CAST(UNIQFIXEDPADRIVER AS INT64)
,SAFE_CAST(UNIQPAIMAGE AS INT64)
,SAFE_CAST(DRIVERNUMBER AS INT64)
,SAFE_CAST(COMPANYDRIVERNUMBER AS INT64)
,SAFE_CAST(NAMEOF AS STRING)
,SAFE_CAST(LKPREFIX AS STRING)
,SAFE_CAST(FIRSTNAME AS STRING)
,SAFE_CAST(MIDDLENAME AS STRING)
,SAFE_CAST(LASTNAME AS STRING)
,SAFE_CAST(LKSUFFIX AS STRING)
,SAFE_CAST(GENDERCODE AS STRING)
,SAFE_CAST(MARITALSTATUSCODE AS STRING)
,SAFE_CAST(RELATIONTOAPPLICANTCODE AS STRING)
,SAFE_CAST(BIRTHDATE AS DATETIME)
,SAFE_CAST(OCCUPATION AS STRING)
,SAFE_CAST(SSN AS STRING)
,SAFE_CAST(LICENSENUMBER AS STRING)
,SAFE_CAST(LICENSEDSTATE AS STRING)
,SAFE_CAST(DRIVERTYPECODE AS STRING)
,SAFE_CAST(LICENSEDDATE AS DATETIME)
,SAFE_CAST(FIRSTLICENSEDMADATE AS DATETIME)
,SAFE_CAST(FIRSTLICENSEDOTHERDATE AS DATETIME)
,SAFE_CAST(FIRSTLICENSEDMOTORCYCLEDATE AS DATETIME)
,SAFE_CAST(GOODSTUDENTCODE AS STRING)
,SAFE_CAST(DRIVERTRAININGCODE AS STRING)
,SAFE_CAST(ACCIDENTPREVENTIONCOURSEDATE AS DATETIME)
,SAFE_CAST(SDIPPOINTS AS INT64)
,SAFE_CAST(INSERTEDBYCODE AS STRING)
,SAFE_CAST(INSERTEDDATE AS DATETIME)
,SAFE_CAST(UPDATEDBYCODE AS STRING)
,SAFE_CAST(UPDATEDDATE AS DATETIME)
,SAFE_CAST(FLAGS AS INT64)
,SAFE_CAST(JOBRUNID AS STRING)
,CURRENT_DATETIME()
,CURRENT_DATETIME()
,'AMS'
)
