INSERT INTO CUSTOMER_PRODUCT.LIFE_COM235
(COMPANY                      ,
POLICY                       ,
AGENT                        ,
COMMISSION_OVERWRITE_LVL     ,
COMMISSION_TYPE              ,
ADVANCE_TRANSACTION_TYPE     ,
INSURE_TYPE                  ,
PLAN                         ,
ISSUE_DT_MONTH               ,
ISSUE_DT_DAY                 ,
ISSUE_DT_YEAR                ,
ISSUE_AGE                    ,
PREMIUM_PAID                 ,
SPLIT_PERCENT                ,
COMMISSION_RATE              ,
COMMISSION_AMT               ,
COMMISSION_ADVANCE_AMT       ,
PAYMENT_CD                   ,
DURATION                     ,
BILLING_MODE                 ,
PAID_TO_DT_MONTH             ,
PAID_TO_DT_DAY               ,
PAID_TO_DT_YEAR              ,
FIRST_NM                     ,
MIDDLE_NM                    ,
LAST_NM                      ,
PROCESSING_DT_MONTH          ,
PROCESSING_DT_DAY            ,
PROCESSING_DT_YEAR           ,
UNPAID_FIRST_YEAR_COMMISSION ,
CLUB                         ,
AGENT_STATEMENT_DISTRIBUTION ,
JOB_RUN_ID                   ,
CREATE_DT                                       
)
SELECT 
COMPANY                      ,
POLICY                       ,
AGENT                        ,
SAFE_CAST(COMMISSION_OVERWRITE_LVL   AS INT64)   ,
COMMISSION_TYPE              ,
ADVANCE_TRANSACTION_TYPE     ,
INSURE_TYPE                  ,
PLAN                         ,
SAFE_CAST(ISSUE_DT_MONTH  AS INT64)             ,
SAFE_CAST(ISSUE_DT_DAY    AS INT64)              ,
SAFE_CAST(ISSUE_DT_YEAR   AS INT64)              ,
SAFE_CAST(ISSUE_AGE  AS INT64)                   ,
SAFE_CAST(PREMIUM_PAID  AS FLOAT64)               ,
SAFE_CAST(SPLIT_PERCENT  AS INT64)               ,
SAFE_CAST(COMMISSION_RATE AS FLOAT64)               ,
SAFE_CAST(COMMISSION_AMT  AS FLOAT64)              ,
SAFE_CAST(COMMISSION_ADVANCE_AMT AS FLOAT64)         ,
PAYMENT_CD                   ,
SAFE_CAST(DURATION   AS INT64)                  ,
BILLING_MODE                 ,
SAFE_CAST(PAID_TO_DT_MONTH   AS INT64)              ,
SAFE_CAST(PAID_TO_DT_DAY    AS INT64)               ,
SAFE_CAST(PAID_TO_DT_YEAR   AS INT64)               ,
FIRST_NM                     ,
MIDDLE_NM                    ,
LAST_NM                      ,
SAFE_CAST(PROCESSING_DT_MONTH   AS INT64)           ,
SAFE_CAST(PROCESSING_DT_DAY    AS INT64)            ,
SAFE_CAST(PROCESSING_DT_YEAR   AS INT64)            ,
SAFE_CAST(UNPAID_FIRST_YEAR_COMMISSION  AS INT64)    ,
SAFE_CAST(CLUB    AS INT64)                         ,
AGENT_STATEMENT_DISTRIBUTION ,
'20200117'                   ,
current_date()                   
FROM LANDING.WORK_LIFE_COM235
