--UPDATE EFF_END_DATE FOR INSURANCE_POLICY_DIM
UPDATE `CUSTOMER_PRODUCT.INSURANCE_POLICY_DIM` DIM
SET DIM.ROW_END_DT = DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY),
ACTIVE_FLG = 'N'
FROM `LANDING.WORK_INSURANCE_POLICY_DIM`  STG
INNER JOIN (SELECT INSURANCE_DIM_KEY,ROW_START_DT,ACTIVE_FLG FROM (SELECT INSURANCE_DIM_KEY,ROW_START_DT,ACTIVE_FLG, ROW_NUMBER() OVER (PARTITION BY INSURANCE_DIM_KEY,ACTIVE_FLG ORDER BY ROW_START_DT DESC ) DUP_CHECK FROM `CUSTOMER_PRODUCT.INSURANCE_POLICY_DIM` WHERE ACTIVE_FLG = 'Y') 
WHERE DUP_CHECK=2) TEMP
ON TEMP.INSURANCE_DIM_KEY=STG.INSURANCE_DIM_KEY
WHERE TEMP.ROW_START_DT = DIM.ROW_START_DT AND DIM.INSURANCE_DIM_KEY = STG.INSURANCE_DIM_KEY



  