INSERT INTO CUSTOMER_PRODUCT.INSURANCE_TRANSACTION_FACT
(
INSURANCE_TRANSACTION_ID,
BATCH_NM,
SOURCE_PRODUCT_CD,
PRODUCT_CD,
PRODUCT_TYPE,
POLICY_NUM,
AGREEMENT_NUM,
AGENT_NM,
TRANSACTION_TYPE,
TRANSACTION_DT,
TRANSACTION_AMT,
COMPENSATION_EMPLOYEE_ID,
SELLING_LOCATION_ID,
REVENUE_LOCATION_ID,
SALES_CHANNEL,
POLICY_STATE,
RISK_STATE,
RISK_CITY,
RISK_ZIP_CD,
PAYMENT_PLAN_CD,
LIFE_AGENT_SPLIT_PERCENTAGE,
LIFE_COMMISSION_RATE,
LIFE_COMMISSION_AMT,
LIFE_COMMISSION_OVERWRITE_LEVEL,
LIFE_COMMISSION_TYPE,
LIFE_ADVANCE_TRANSACTION_TYPE,
LIFE_INSURE_TYPE,
LIFE_UNPAID_FIRST_YEAR_COMMISSION,
LIFE_AGENT_STATEMENT_DISTRIBUTION,
SOURCE_SYSTEM
)
SELECT 
CASE
     WHEN FACT.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
     ELSE FACT.MAX_ID+(ROW_NUMBER() OVER ())
   END AS INSURANCE_TRANSACTION_ID,
CONCAT('BATCH',CAST(current_date AS STRING)),
COM.INSURE_TYPE,
S_DIM.PRODUCT_CD ,
S_DIM.PRODUCT_TYPE,
COM.POLICY,
CONCAT(I_DIM.POLICY_STATE,'_',S_DIM.PRODUCT_CD,'_',COM.POLICY),
COM.AGENT,
"Renew",
COM.PROCESSING_DT,
COM.PREMIUM_PAID ,
DIM.EMPLOYEE_ID,
DIM.LOCATION_ID,
B.LOCATION_ID ,
LOC.CHANNEL_NM,
I_DIM.POLICY_STATE,
I_DIM.RISK_STATE,
I_DIM.RISK_CITY,
I_DIM.RSIK_ZIP_CD, 
COM.PLAN,
COM.SPLIT_PERCENT,
COM.COMMISSION_RATE,
COM.COMMISSION_AMT,
COM.COMMISSION_OVERWRITE_LVL,
COM.COMMISSION_TYPE,
COM.ADVANCE_TRANSACTION_TYPE,
COM.INSURE_TYPE ,
COM.UNPAID_FIRST_YEAR_COMMISSION,
COM.AGENT_STATEMENT_DISTRIBUTION,
"LIFE INS COM235"
FROM LANDING.LIFE_COM235 COM
LEFT OUTER JOIN CUSTOMERS.EMPLOYEE_DIM DIM
ON COM.AGENT = DIM.INSURANCE_REP_ID
LEFT OUTER JOIN CUSTOMER_PRODUCT.LOCATION_DIM LOC
ON LOC.LOCATION_ID = DIM.LOCATION_ID
LEFT OUTER JOIN REFERENCE.SALES_PRODUCT_DIM S_DIM
ON S_DIM.SOURCE_PRODUCT_CD = COM.INSURE_TYPE
LEFT OUTER JOIN 
(
SELECT ZIP.LOCATION_ID,A.PRIMARY_ZIP,ZIP.ZIP_CD,A.SOURCE_KEY1
FROM
(SELECT BRIDGE.CUSTOMER_MDM_KEY, CUST.PRIMARY_ZIP, BRIDGE.SOURCE_KEY1
FROM `CUSTOMERS.MDM_CUSTOMER_BRIDGE` BRIDGE
JOIN
CUSTOMERS.MDM_CUSTOMER_DIM CUST ON BRIDGE.CUSTOMER_MDM_KEY= CUST.CUSTOMER_MDM_KEY
WHERE SOURCE_SYSTEM = 'AGYPOLE_OWNER' OR SOURCE_SYSTEM = 'AGYPOLE_INSURED') A
JOIN CUSTOMER_PRODUCT.LOCATION_ZIP_DIM ZIP
ON ZIP.ZIP_CD = A.PRIMARY_ZIP ) B
ON B.SOURCE_KEY1 = COM.POLICY
LEFT OUTER JOIN CUSTOMER_PRODUCT.INSURANCE_DIM I_DIM
ON I_DIM.PRODUCT_CD = S_DIM.PRODUCT_CD AND I_DIM.POLICY_NUM = COM.POLICY,
 (
   SELECT
     MAX(INSURANCE_TRANSACTION_ID) MAX_ID
   FROM
     CUSTOMER_PRODUCT.INSURANCE_TRANSACTION_FACT) FACT