UPDATE `CUSTOMER_PRODUCT.INSURANCE_TRANSACTION_FACT` ITF
SET COMPENSATION_EMPLOYEE_ID = A.EMPLOYEE_ID,
SELLING_LOCATION_ID	=	 CASE WHEN A.EMPLOYEE_ID = '999999' THEN A.LOCATION_ID ELSE A.LOCATION_ID END,
SALES_CHANNEL	= CASE WHEN A.EMPLOYEE_ID = '999999' THEN 'Field' ELSE A.CHANNEL_NM END  -- Modified
FROM ( SELECT PPA.EMPLOYEE_ID, PPA.PAS_AGENT_ID, PPA.LOCATION_ID, PPA.LOCATION_NM, B1.CHANNEL_NM, 
CASE WHEN E1.ROW_START_DT IS NOT NULL THEN E1.ROW_START_DT
     ELSE DATE('1900-01-01') END AS ROW_START_DT , 
CASE WHEN E1.ROW_END_DT IS NOT NULL THEN E1.ROW_END_DT
     ELSE DATE('9999-12-12') END AS ROW_END_DT 
FROM  REFERENCE.PCOMP_PAS_AGENT PPA
LEFT OUTER JOIN `CUSTOMER_PRODUCT.EMPLOYEE_DIM` E1 ON TRIM(PPA.EMPLOYEE_ID) = TRIM(E1.EMPLOYEE_ID) 
LEFT OUTER JOIN `CUSTOMER_PRODUCT.LOCATION_DIM` B1  ON TRIM(E1.LOCATION_ID) = TRIM(B1.LOCATION_ID) AND B1.ACTIVE_FLG = 'Y'
) A
WHERE ITF.COMPENSATION_EMPLOYEE_ID IS NULL
AND ITF.PAS_AGENT_ID  IS NOT NULL
--AND TRIM(ITF.PAS_AGENT_ID) = TRIM(A.PAS_AGENT_ID)
AND LPAD(TRIM(ITF.PAS_AGENT_ID),10, '0') = LPAD(TRIM(A.PAS_AGENT_ID),10, '0') 
AND ITF.TRANSACTION_DT BETWEEN A.ROW_START_DT AND  A.ROW_END_DT
