
INSERT INTO CUSTOMER_PRODUCT.INSURANCE_TRANSACTION_FACT(
INSURANCE_TRANSACTION_ID	,	
TRANSACTION_DT			,
TRANSACTION_EFFECTIVE_DT,	
TRANSACTION_TERM			,
TRANSACTION_TYPE			,
TRANSACTION_AMT			,
TRANSACTION_CD			,
SOURCE_PRODUCT_CD	,
PRODUCT_CD,
PRODUCT_TYPE,
SUB_PRODUCT_TYPE,
POLICY_PREFIX			,
POLICY_NUM			,
AGREEMENT_NUM		,
CEA_POLICY_NUM,	
POLICY_ENDORSEMENT_DT,	
INCEPTION_DT			,
TERM_EFFECTIVE_DT,		
TERM_EXPIRATION_DT,
TERM_IND			,
RENEW_COUNT			,
MAILING_ZIP_CD			,
RESIDENTIAL_ZIP_CD		,			
PAS_AGENT_ID		,	
SALES_REP_ID			,
SALES_REP_DO			,		
SOURCE_AGENT_NM		,
COMPENSATION_EMPLOYEE_ID,	
COMPENSATION_EMPLOYEE_FIRST_NM,			
COMPENSATION_EMPLOYEE_LAST_NM	,
SELLING_LOCATION_ID			,
REVENUE_LOCATION_ID,
SALES_CHANNEL		,
POLICY_STATE		,	
AGENCY_NM			,
SELLING_AGENCY_NUM	,		
AGENCY_OF_RECORD	,		
AGENT_OF_TRANSACTION,			
UNDERWRITING_COMPANY,					
CANCEL_TYPE			,
LINE_NUM			,
DUPLICATE_ORDER_NUM_FLAG,	
PRIOR_CARRIER	,
NUMBER_OF_UNITS		,	
ERROR_FLAG			,
GA_CD			,		
CAMPAIGN_SOURCE_CD,
PRODUCT_SUB_CATEGORY	,		
SOURCE_SYSTEM_TRANSACTION_ID		,
SOURCE_SYSTEM			,	
BATCH_NM			,
CREATE_DTTIME 
)
SELECT T1.INSURANCE_TRANSACTION_ID,
T1.TRANSACTION_DT,
CASE WHEN T1.TRANSACTION_EFFECTIVE_DT IS NOT NULL THEN T1.TRANSACTION_EFFECTIVE_DT
	 ELSE DATE('1900-01-01') END TRANSACTION_EFFECTIVE_DT,
T1.TRANSACTION_TYPE,
T1.PROCESS_TYPE AS TRANSACTION_SUB_TYPE	,
T1.TRANSACTION_AMT,
T1.TRANSACTION_CD,
T1.PRODUCT_CD AS SOURCE_PRODUCT_CD,
S.PRODUCT_CD AS PRODUCT_CD, 
S.PRODUCT_TYPE AS PRODUCT_TYPE,
S.SUB_PRODUCT_TYPE AS SUB_PRODUCT_TYPE,
T1.POLICY_PREFIX,
T1.POLICY_NUM AS POLICY_NUM			,
CASE WHEN T1.SOURCE_SYSTEM IN ('Exigen Pup', 'Exigen Home', 'Exigen Auto') AND TRIM(T1.POLICY_PREFIX) IS NOT NULL  THEN CONCAT(TRIM(T1.POLICY_PREFIX), TRIM(T1.POLICY_NUM))
	   WHEN TRIM(T1.POLICY_STATE) IS NULL THEN CONCAT('CA',S.PRODUCT_CD,T1.POLICY_NUM)
	   ELSE CONCAT(T1.POLICY_STATE,S.PRODUCT_CD,T1.POLICY_NUM) 
END AS  AGREEMENT_NUM,
T1.CEA_POLICY_NUM AS CEA_POLICY_NUM			,
T1.POLICY_ENDORSEMENT_DT,	 
T1.INCEPTION_DT,	 
T1.POLICY_EFFECTIVE_DT AS TERM_EFFECTIVE_DT,
T1.EXPIRATION_DT AS TERM_EXPIRATION_DT,
T1.TERM_IND,
T1.RENEW_COUNT,
T1.MAILING_ZIP_CD,
T1.RESIDENTIAL_ZIP_CD,
T1.PAS_AGENT_ID,
T1.SALES_REP_ID,
T1.SALES_REP_DO,
T1.AGENT_NM AS SOURCE_AGENT_NM,
CASE WHEN ( T1.SALES_REP_ID in ('000','00','0', '0.0', '') OR TRIM(T1.SALES_REP_ID) IS NULL) AND TRIM(T1.PAS_AGENT_ID) IS NULL THEN '999999'
     WHEN TRIM(E1.EMPLOYEE_ID) IS NOT NULL THEN E1.EMPLOYEE_ID
	 WHEN TRIM(E2.EMPLOYEE_ID) IS NOT NULL THEN E2.EMPLOYEE_ID
     ELSE NULL
END AS COMPENSATION_EMPLOYEE_ID,
CASE WHEN TRIM(E1.EMPLOYEE_ID) IS NOT NULL THEN E1.LEGAL_FIRST_NM
     WHEN TRIM(E2.EMPLOYEE_ID) IS NOT NULL THEN E2.LEGAL_FIRST_NM
     ELSE NULL
END AS COMPENSATION_EMPLOYEE_FIRST_NM,
CASE WHEN TRIM(E1.EMPLOYEE_ID) IS NOT NULL THEN E1.LEGAL_LAST_NM
     WHEN TRIM(E2.EMPLOYEE_ID) IS NOT NULL THEN E2.LEGAL_LAST_NM
     ELSE NULL
END AS COMPENSATION_EMPLOYEE_LAST_NM,
CASE WHEN (TRIM(T1.SALES_REP_ID) in ('000','00','0', '0.0', '') OR TRIM(T1.SALES_REP_ID) IS NULL) AND TRIM(T1.PAS_AGENT_ID) IS NULL THEN '999'
     WHEN TRIM(E1.EMPLOYEE_ID) IS NOT NULL THEN E1.LOCATION_ID
     ELSE TRIM(E2.LOCATION_ID)
END AS SELLING_LOCATION_ID,
LZD.LOCATION_ID AS REVENUE_LOCATION_ID,
CASE WHEN (TRIM(T1.SALES_REP_ID) in ('000','00','0', '0.0', '') OR TRIM(T1.SALES_REP_ID) IS NULL) AND TRIM(T1.PAS_AGENT_ID) IS NULL THEN 'Main Office'
     ELSE B1.CHANNEL_NM END AS SALES_CHANNEL,
CASE WHEN TRIM(T1.POLICY_STATE) IS NULL THEN 'CA'
ELSE T1.POLICY_STATE END AS POLICY_STATE,
T1.AGENCY_NM,
T1.SELLING_AGENCY_NUM,
T1.AGENCY_OF_RECORD,
T1.AGENT_OF_TRANSACTION,
T1.UNDER_WRITING_COMPANY AS UNDERWRITING_COMPANY,
T1.CANCEL_TYPE,
T1.LINE_NUM,
T1.DUPLICATE_ORDER_NUM_FLAG,
T1.PRIOR_CARRIER,
T1.NUMBER_OF_UNITS,
T1.ERROR_FLAG,
T1.GA_CD,
T1.CAMPAIGN_SOURCE_CD,
T1.PRODUCT_SUB_CATEGORY,
T1.SOURCE_SYSTEM_TRANSACTION_ID,
UPPER(T1.SOURCE_SYSTEM) AS SOURCE_SYSTEM,
T1.BATCH_NM,
DATETIME(CURRENT_TIMESTAMP()) AS CREATE_DTTIME
FROM `LANDING.PCOMP_INSURANCE_TRANSACTION` T1
LEFT OUTER JOIN `CUSTOMER_PRODUCT.EMPLOYEE_DIM` E1 ON TRIM(T1.SALES_REP_ID) = TRIM(E1.INSURANCE_REP_ID) AND T1.TRANSACTION_DT BETWEEN E1.EFFECTIVE_START_DT AND  E1.EFFECTIVE_END_DT
LEFT OUTER JOIN `CUSTOMER_PRODUCT.EMPLOYEE_DIM` E2 ON TRIM(T1.PAS_AGENT_ID) = TRIM(E2.PAS_ID) AND T1.TRANSACTION_DT BETWEEN E2.EFFECTIVE_START_DT AND  E2.EFFECTIVE_END_DT
LEFT OUTER JOIN `CUSTOMER_PRODUCT.LOCATION_DIM` B1  ON TRIM(E1.LOCATION_ID) = TRIM(B1.LOCATION_ID) AND B1.ACTIVE_FLG = 'Y'
LEFT OUTER JOIN `CUSTOMER_PRODUCT.LOCATION_ZIP_DIM` LZD ON TRIM(T1.RESIDENTIAL_ZIP_CD) =CAST(LZD.ZIP_CD as STRING)
LEFT OUTER JOIN `REFERENCE.SALES_PRODUCT_DIM` S ON TRIM(S.SOURCE_PRODUCT_CD)= TRIM(T1.PRODUCT_CD) AND TRIM(S.SOURCE_SYSTEM_CD) = 'PCOMP'
WHERE T1.INSURANCE_TRANSACTION_ID NOT IN (SELECT DISTINCT INSURANCE_TRANSACTION_ID FROM CUSTOMER_PRODUCT.INSURANCE_TRANSACTION_FACT)