INSERT INTO CUSTOMER_PRODUCT.INSURANCE_TRANSACTION_FACT
(
INSURANCE_TRANSACTION_ID,
BATCH_NM,
SOURCE_PRODUCT_CD,
PRODUCT_CD,
PRODUCT_TYPE,
POLICY_NUM,
AGREEMENT_NUM,
AGENT_NM,
TRANSACTION_TYPE,
TRANSACTION_DT,
TRANSACTION_AMT,
COMPENSATION_EMPLOYEE_ID,
SELLING_LOCATION_ID,
REVENUE_LOCATION_ID,
SALES_CHANNEL,
POLICY_STATE,
RISK_STATE,
RISK_CITY,
RISK_ZIP_CD,
PAYMENT_PLAN_CD,
SOURCE_SYSTEM
)
SELECT 
CASE
     WHEN FACT.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
     ELSE FACT.MAX_ID+(ROW_NUMBER() OVER ())
   END AS INSURANCE_TRANSACTION_ID,
CONCAT('BATCH',CAST(current_date AS STRING)),
DLY.PRODUCT_TYPE,
S_DIM.PRODUCT_CD ,
S_DIM.PRODUCT_TYPE,
DLY.POLICY_NUM,
CONCAT(I_DIM.POLICY_STATE,'_',S_DIM.PRODUCT_CD,'_',DLY.POLICY_NUM),
DLY.AGENT_NUM,
"New",
DLY.PROCESSING_DT,
DLY.PRODUCTION_AMT,
DIM.EMPLOYEE_ID,
DIM.LOCATION_ID,
CAST(ZIP.LOCATION_TERRITORY_KEY AS STRING),
LOC.CHANNEL_NM,
I_DIM.POLICY_STATE,
I_DIM.RISK_STATE,
I_DIM.RISK_CITY,
I_DIM.RSIK_ZIP_CD,
DLY.BILLING_MODE,
"LIFE INS"
FROM LANDING.LIFE_INS_CSAPRDLY_DAILY DLY
LEFT OUTER JOIN CUSTOMERS.EMPLOYEE_DIM DIM
ON DLY.AGENT_NUM = DIM.INSURANCE_REP_ID
LEFT OUTER JOIN CUSTOMER_PRODUCT.LOCATION_DIM LOC
ON LOC.LOCATION_ID = DIM.LOCATION_ID
LEFT OUTER JOIN REFERENCE.SALES_PRODUCT_DIM S_DIM
ON S_DIM.SOURCE_PRODUCT_CD = DLY.PRODUCT_TYPE
LEFT OUTER JOIN CUSTOMER_PRODUCT.LOCATION_ZIP_DIM ZIP
ON ZIP.ZIP_CD = DLY.ZIP_CD
LEFT OUTER JOIN CUSTOMER_PRODUCT.INSURANCE_DIM I_DIM
ON I_DIM.PRODUCT_CD = S_DIM.PRODUCT_CD AND I_DIM.POLICY_NUM = DLY.POLICY_NUM,
 (
   SELECT
     MAX(INSURANCE_TRANSACTION_ID) MAX_ID
   FROM
     CUSTOMER_PRODUCT.INSURANCE_TRANSACTION_FACT) FACT