--DELETE FROM CUSTOMER_PRODUCT.INSURANCE_TRANSACTION_DIM WHERE TRUE
INSERT INTO LANDING.IVANS_INSURANCE_TRANSACTIONS(
INSURANCE_TRANSACTION_ID,
SOURCE_TRANSACTION_ID,
POLICY_PREFIX,
SOURCE_PRODUCT_CD,
PRODUCT_CD,
PRODUCT_TYPE,
POLICY_NUM,
AGREEMENT_NUM,
TERM_EFFECTIVE_DT,
TERM_EXPIRATION_DT,
TRANSACTION_EFFECTIVE_DT,
TRANSACTION_TYPE,
TRANSACTION_DT,
TRANSACTION_AMT,
COMPENSATION_EMPLOYEE_ID,
SELLING_LOCATION_ID,
REVENUE_LOCATION_ID,
SALES_CHANNEL,
POLICY_STATE,
PAYMENT_PLAN_CD,
CANCEL_REASON_CD,
CANCEL_TYPE_CD,
CANCEL_DT,
TIER_FACTOR,
TERM_PREMIUM_AMT,
RENEWAL_MIN_AMT_DUE,
RENEWAL_TOTAL_PREMIUM_AMT,
ENDORSEMENT_FORM_NAME_CD,
JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATE_DTTIME)
SELECT 
CASE
    WHEN INS.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
    ELSE INS.MAX_ID+(ROW_NUMBER() OVER ())
  END AS INSURANCE_TRANSACTION_ID, 
SOURCE_TRANSACTION_ID,
POLICY_PREFIX,
SOURCE_PRODUCT_CD,
PRODUCT_CD,
PRODUCT_TYPE,
POLICY_NUM,
AGREEMENT_NUM,
TERM_EFFECTIVE_DT,
TERM_EXPIRATION_DT,
TRANSACTION_EFFECTIVE_DT,
TRANSACTION_TYPE,
TRANSACTION_DT,
TRANSACTION_AMOUNT,
COMPENSATION_EMPLOYEE_ID,  
SELLING_LOCATION_ID, 
REVENUE_LOCATION_ID,
SALES_CHANNEL,
POLICY_STATE,
PAYMENT_PLAN_CD,
CANCEL_REASON_CD,
CANCEL_TYPE_CD,
CANCEL_DT,
TIER_FACTOR,
TERM_PREMIUM_AMOUNT,
RENEWAL_MIN_AMOUNT_DUE,
RENEWAL_TOTAL_PREMIUM_AMOUNT,
ENDORSEMENT_FORM_NAME_CD,
'V_JOB_RUN_ID',
"insurance",
CURRENT_DATETIME()
FROM (
SELECT 
CONCAT("IE~",CAST(C1.FILE_ID AS STRING),"~",CAST(C1.TRANS_NUM AS STRING),"~",CAST(C1.ITEM_NUM AS STRING),"~",CAST(C1.OCUR_NUM AS STRING)) SOURCE_TRANSACTION_ID,
C1.PLCY_PRFX AS POLICY_PREFIX,
SUBSTR(C1.PLCY_PRFX,3,2) AS  SOURCE_PRODUCT_CD,
P1.PRODUCT_CD AS PRODUCT_CD,
P1.PRODUCT_TYPE AS PRODUCT_TYPE,
C1.PLCY_NUM AS POLICY_NUM,
CONCAT(C1.PLCY_PRFX,C1.PLCY_NUM) AS AGREEMENT_NUM,
C2.TRM_EFF_DT AS TERM_EFFECTIVE_DT,
C2.EXPR_DT AS TERM_EXPIRATION_DT,
C2.TRANS_EFF_DT AS TRANSACTION_EFFECTIVE_DT,
C1.TRANS_TYP_CD AS TRANSACTION_TYPE,
C1.LST_ENDR_DT AS TRANSACTION_DT,
C1.NET_PREM_AMT/100 AS TRANSACTION_AMOUNT,
COALESCE(SAFE_CAST(ED.EMPLOYEE_ID AS INT64),SAFE_CAST(ED1.EMPLOYEE_ID AS INT64)) AS COMPENSATION_EMPLOYEE_ID,
COALESCE(ED.LOCATION_ID,ED1.LOCATION_ID) AS  SELLING_LOCATION_ID,
LZD.LOCATION_ID AS REVENUE_LOCATION_ID,
LOC.CHANNEL_NM AS SALES_CHANNEL,
B1.ST_CD AS POLICY_STATE, 
C2.PAY_PLN_CD AS PAYMENT_PLAN_CD,
C2.CAN_RSN_CD AS CANCEL_REASON_CD,
C2.CAN_TYP_CD AS CANCEL_TYPE_CD,
CASE WHEN (A1.DATA_SOURCE_FILE IN ('EXIGEN', 'ADES', 'HDES', 'HUON', 'PUP')  AND C1.TRANS_TYP_CD   = 'CN')  THEN C2.TRANS_EFF_DT
     END AS CANCEL_DT,
C2.TIER_FCTR AS TIER_FACTOR,
C1.TRM_PREM_AMT AS TERM_PREMIUM_AMOUNT,
C1.RO_MIN_AMT AS RENEWAL_MIN_AMOUNT_DUE,
C1.RO_TOTAL_AMT AS RENEWAL_TOTAL_PREMIUM_AMOUNT,
D1. ENDORSEMENT_FORM_NAME_CD AS ENDORSEMENT_FORM_NAME_CD
FROM `LANDING.IE_C1_LDG`  C1
INNER JOIN  `LANDING.IE_C2_LDG`  C2 ON  C1.TRANS_NUM=C2.TRANS_NUM and C1.FILE_ID = C2.FILE_ID
INNER JOIN `LANDING.IE_A1_LDG`  A1 ON A1.TRANS_NUM =C1.TRANS_NUM and A1.FILE_ID = C1.FILE_ID AND DATA_SOURCE_FILE = 'EXIGEN'
LEFT OUTER JOIN `LANDING.IE_D1_LDG`  D1 ON  C1.TRANS_NUM=D1.TRANS_NUM and C1.FILE_ID= D1.FILE_ID AND  C1.OCUR_NUM = D1.OCUR_NUM
LEFT OUTER JOIN `LANDING.IE_B1_LDG`  B1 ON B1.TRANS_NUM =C1.TRANS_NUM and B1.FILE_ID = C1.FILE_ID
LEFT OUTER JOIN `REFERENCE.SALES_PRODUCT_DIM` P1 ON SUBSTR(C1.PLCY_PRFX,3,2) = P1.PRODUCT_CD AND P1.SOURCE_SYSTEM_CD='IVANS'
LEFT OUTER JOIN CUSTOMER_PRODUCT.EMPLOYEE_DIM ED  ON TRIM(C2.SUB_PRDCNG_AGNT_NUM) = ED.PAS_AGENT_ID AND C1.LST_ENDR_DT BETWEEN ED.ROW_START_DT and ED.ROW_END_DT 
LEFT OUTER JOIN CUSTOMER_PRODUCT.EMPLOYEE_DIM ED1 ON TRIM(C2.SUB_PRDCNG_AGNT_NUM) = ED1.INSURANCE_REP_ID AND C1.LST_ENDR_DT BETWEEN ED1.ROW_START_DT and ED1.ROW_END_DT 
LEFT OUTER JOIN `CUSTOMER_PRODUCT.LOCATION_DIM` LOC  ON TRIM(coalesce(ED.LOCATION_ID, ED1.LOCATION_ID)) = TRIM(LOC.LOCATION_ID) AND LOC.ACTIVE_FLG = 'Y'
LEFT OUTER JOIN `CUSTOMER_PRODUCT.LOCATION_ZIP_DIM` LZD ON TRIM(B1.ZP_CD) =CAST(LZD.ZIP_CD as STRING) 
WHERE C1.FILE_ID = (SELECT MAX(FILE_ID) FROM LANDING.IE_C1_LDG)
) IE,
(SELECT     MAX(INSURANCE_TRANSACTION_ID) MAX_ID   FROM      LANDING.IVANS_INSURANCE_TRANSACTIONS) INS
