INSERT INTO CUSTOMER_PRODUCT.INSURANCE_CUSTOMER_DIM (
CUSTOMER_MDM_KEY ,
AGREEMENT_NUM,
PRODUCT_CD,
MEMBER_NUM,
--OWNER_CUSTOMER_MDM_KEY,
STATUS_CD )
SELECT 
MDM_BRIDGE_INSURED.CUSTOMER_MDM_KEY CUSTOMER_MDM_KEY,
CONCAT(INSURED_ADDRESS_STATE,PRODUCT_CD,POLICY_NUM) AGREEMENT_NUM ,
PRODUCT_CD,
CAST(MEMBER_NUM AS INT64),
--MDM_BRIDGE_OWNER.CUSTOMER_MDM_KEY OWNER_CUSTOMER_MDM_KEY,
CONTRACT_STATUS
FROM
LANDING.AAA_LIFE_INS_AGYPOLE LIFE_INS
LEFT OUTER JOIN CUSTOMER_PRODUCT.MDM_CUSTOMER_BRIDGE MDM_BRIDGE_INSURED
ON (LIFE_INS.POLICY_NUM=MDM_BRIDGE_INSURED.SOURCE_KEY1 AND MDM_BRIDGE_INSURED.SOURCE_SYSTEM_CD = 'AGYPOLE_INSURED')
LEFT OUTER JOIN CUSTOMER_PRODUCT.MDM_CUSTOMER_BRIDGE MDM_BRIDGE_OWNER
ON (LIFE_INS.POLICY_NUM=MDM_BRIDGE_OWNER.SOURCE_KEY1 AND MDM_BRIDGE_OWNER.SOURCE_SYSTEM_CD = 'AGYPOLE_OWNER' )
WHERE 
LIFE_INS.PRIMARY_AGENT_IND='Y'
