SELECT 
INS_MDM.CUSTOMER_MDM_KEY CUSTOMER_MDM_KEY,
DIM.AGMT_NUM AGMT_NUM,
DIM.PRODUCT_CD AS PRODUCT_CD,
COALESCE(LPAD(CONCAT(CAST(MEMBER_DIM.MEMBERSHIP_NUM AS STRING) ,CAST(MEMBER_DIM.ASSOCIATE_ID AS STRING)),16,'429005')) AS MEMBER_NUM ,
MEMBER_DIM.STATUS_CD MEMBER_STATUS,
DIM.POLICY_STATUS AS POLICY_STATUS,
CLAIM.COUNT_OF_CLAIMS AS COUNT_OF_CLAIMS,
IG_MDM.ROLE_STATUS_FLAG AS INSURANCE_ROLE_STATUS,
E1.DRIVER_TYP_CD AS DRIVER_TYP_CD,
CAST(NULL AS STRING) AS YAF,
E1.LICENSE_STATE AS LICENSE_STATE,
E1.LICENSE_DT AS LICENSE_DT,
CAST(NULL AS STRING) AS LICENSE_VALID_IND,
E1.STUDENT_DISCOUNT_IND AS STUDENT_DISCOUNT_IND,
E1.DRIVING_TRAINING_IND AS DRIVING_TRAINING_IND,
E1.DEFENSIVE_DRIVER_DT AS DEFENSIVE_DRIVER_DT
FROM
(SELECT ACTIVE_FLG,DATA_SOURCE,  AGMT_NUM, PRODUCT_CD, POLICY_STATUS,
         CASE WHEN  DATA_SOURCE = 'EXIGEN' THEN AGMT_NUM
              WHEN  (DATA_SOURCE = 'AS400' OR DATA_SOURCE = 'PUP') THEN CONCAT(POLICY_PREFIX, POLICY_NUM)
              WHEN  (DATA_SOURCE = 'HUON' OR DATA_SOURCE = 'HDES') THEN POLICY_NUM END AS MODS_AGMT_NUM,
              SOURCE_TRANSACTION_ID
 FROM  CUSTOMER_PRODUCT.INSURANCE_DIM WHERE ACTIVE_FLG = 'Y')  DIM
LEFT OUTER JOIN 
(SELECT * FROM 
(SELECT *, ROW_NUMBER() OVER(PARTITION BY MODS_AGMT_NUM) DUP_CHK FROM 
(SELECT  CUSTOMER_MDM_KEY, SOURCE_KEY1, R.SOURCE_SYSTEM, ROW_NUMBER() OVER(PARTITION BY R.ENTERPRISE_ID,R.AGREEMENT_NUMBER) RN ,SOURCE_KEY2 ,
R.AGREEMENT_NUMBER AS MODS_AGMT_NUM 
FROM `CUSTOMERS.MDM_CUSTOMER_BRIDGE` B,  `CUSTOMERS.INS_ROLE`  R
WHERE B.SOURCE_SYSTEM='INS'
AND  CAST(R.ENTERPRISE_ID  AS STRING) =  B.SOURCE_KEY1 AND R.SOURCE_SYSTEM<>'MNCNU'
--AND R.AGREEMENT_NUMBER = B.SOURCE_KEY2
) INS_MDM
WHERE INS_MDM.RN=1
) INS_MDM
WHERE INS_MDM.DUP_CHK=1) INS_MDM
ON DIM.MODS_AGMT_NUM = INS_MDM.MODS_AGMT_NUM
LEFT OUTER JOIN 
(SELECT * FROM ( SELECT MEMBERSHIP_NUM,ASSOCIATE_ID,STATUS_CD,CUSTOMER_MDM_KEY, ROW_NUMBER() OVER (PARTITION BY CUSTOMER_MDM_KEY ORDER BY TERM_EFFECTIVE_DT DESC ) RN FROM `CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM`  ) M
WHERE M.RN=1)  MEMBER_DIM
ON INS_MDM.CUSTOMER_MDM_KEY=MEMBER_DIM.CUSTOMER_MDM_KEY
LEFT OUTER JOIN 
(SELECT POLICY_NUM, COUNT(CLAIM_NUM) AS COUNT_OF_CLAIMS FROM  
( SELECT POLICY_NUM, CLAIM_NUM, CLAIM_OPEN_DT ,ROW_NUMBER() OVER(PARTITION BY CLAIM_NUM, CLAIM_OPEN_DT) RN FROM `CUSTOMER_PRODUCT.INSURANCE_CLAIMS_FACT` ) CLAIM
WHERE CLAIM.RN= 1 GROUP BY POLICY_NUM) CLAIM 
ON DIM.AGMT_NUM= CLAIM.POLICY_NUM 
LEFT OUTER JOIN 
(SELECT * FROM (SELECT ENTERPRISE_ID, AGREEMENT_NUMBER, ROLE_STATUS_FLAG , ROW_NUMBER() OVER(PARTITION BY ENTERPRISE_ID, AGREEMENT_NUMBER ORDER BY UPDATE_DATE DESC) RN
FROM `CUSTOMERS.INS_ROLE`) WHERE  RN=1 ) IG_MDM
ON --IG_MDM.AGREEMENT_NUMBER= INS_MDM.SOURCE_KEY2 AND 
CAST(IG_MDM.ENTERPRISE_ID AS STRING)= INS_MDM.SOURCE_KEY1
LEFT OUTER JOIN (SELECT CONCAT("IE~",CAST(E1.FILE_ID AS STRING),"~",CAST(E1.TRANS_NUM AS STRING),"~",CAST(E1.ITEM_NUM AS STRING),"~",CAST(E1.OCUR_NUM AS STRING))   AS SOURCE_TRANSACTION_ID,
DRVR_TYP_CD AS DRIVER_TYP_CD , LIC_ST_CD AS LICENSE_STATE , LIC_DT AS LICENSE_DT, STU_DISC_CD AS STUDENT_DISCOUNT_IND , DRVR_TRN_IND AS DRIVING_TRAINING_IND, DFNS_DRVR_DT AS DEFENSIVE_DRIVER_DT
FROM `LANDING.IE_E1_LDG` E1
UNION ALL
SELECT  CONCAT("AS400~",CAST(E1.FILE_ID AS STRING),"~",CAST(E1.TRANS_NO AS STRING),"~",CAST(E1.ITEM_NO AS STRING),"~",CAST(E1.OCUR_NO AS STRING)) AS  SOURCE_TRANSACTION_ID,
DRSTS AS DRIVER_TYP_CD, DRLCST AS LICENSE_STATE , DRLIDTE AS LICENSE_DT, DRGST AS STUDENT_DISCOUNT_IND, DRDTR AS DRIVING_TRAINING_IND, DRDDTE AS DEFENSIVE_DRIVER_DT  FROM `LANDING.AS400_E1_LDG`E1 )	E1
 ON E1.SOURCE_TRANSACTION_ID = DIM.SOURCE_TRANSACTION_ID