select CONCAT(MEMBER_NUM,OK_TO_PHONE,OK_TO_MAIL,OK_TO_EMAIL,
OK_TO_SOLICT,DMA_PANDER_FLAG,CURR_DATE) AS IG_MKT_DESC
FROM (
select 
RPAD(IFNULL(CP.MEMBER_NUM,' '),16,' ') AS MEMBER_NUM,
RPAD(IFNULL((CASE WHEN DO_NOT_PHONE = 'N' THEN 'Y' ELSE 'N' END),' '),1,' ') AS OK_TO_PHONE,
RPAD(IFNULL((CASE WHEN DO_NOT_MAIL = 'N' THEN 'Y' ELSE 'N' END),' '),1,' ') AS OK_TO_MAIL,
RPAD(IFNULL((CASE WHEN DO_NOT_EMAIL = 'N' THEN 'Y' ELSE 'N' END),' '),1,' ') AS OK_TO_EMAIL,
RPAD(IFNULL(OK_TO_SOLICT,' '),1,' ') AS OK_TO_SOLICT,
RPAD(IFNULL(DMA_PANDER_FLAG,' '),1,' ') AS DMA_PANDER_FLAG,
RPAD(UPPER(IFNULL(cast(CURRENT_DATETIME() as string),'')),23,' ') CURR_DATE
from
(select MEMBER_NUM,DO_NOT_PHONE,DO_NOT_MAIL,DO_NOT_EMAIL,OK_TO_SOLICT,DMA_PANDER_FLAG,UPDATE_DTTIME,
LEAD(OK_TO_SOLICT) OVER(PARTITION BY MEMBER_NUM ORDER BY CUSTOMER_ID DESC,ROW_START_DT DESC) as PREV_OK_TO_SOLICT,
ROW_START_DT,ACTIVE_FLG,ROW_NUM 
FROM
(select *,ROW_NUMBER() OVER(PARTITION BY MEMBER_NUM ORDER BY CUSTOMER_ID DESC) as ROW_NUM
FROM CUSTOMER_PRODUCT.CUSTOMER_CONTACT_PREFERENCE_DIM CP WHERE MEMBER_NUM IS NOT NULL)
) CP
INNER JOIN
(select  MEMBER_NUM,ASSOCIATE_ID,EMPLOYEE_IND,ROW_START_DT,UPDATE_DTTIME,
LEAD(EMPLOYEE_IND)
OVER (PARTITION BY MEMBER_NUM ORDER BY ROW_START_DT DESC) PREV_EMPLOYEE_IND,ACTIVE_FLG
from CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM 
) EMP
ON CP.MEMBER_NUM=EMP.MEMBER_NUM
AND ROW_NUM=1 and CP.ACTIVE_FLG='Y' AND EMP.ACTIVE_FLG='Y'
WHERE GREATEST(CP.UPDATE_DTTIME,EMP.UPDATE_DTTIME)>'{{ prev_execution_date }}'
and (IFNULL(PREV_OK_TO_SOLICT,'@') <>OK_TO_SOLICT or IFNULL(PREV_EMPLOYEE_IND,'@')<>EMPLOYEE_IND))