SELECT 
CONCAT(MS_CPMS_CHG_BASE_SEG,
MS_CPMS_HH_NO,
MS_CPMS_HH_PFX,
MS_CPMS_NAME_LAST,
MS_CPMS_NAME_FIRST,
MS_CPMS_MAIL_ADDR_LN1,
MS_CPMS_MAIL_ADDR_LN2,
MS_CPMS_MAIL_CITY,
MS_CPMS_MAIL_STATE,
MS_CPMS_MAIL_ZIP,
MS_CPMS_MEMBER_STATUS,
MS_CPMS_PRI_PHONE,
MS_CPMS_CSAA_BASE_YEAR,
MS_CPMS_EXP_DATE,
MS_CPMS_SVC_COVERAGE,
MS_CPMS_ACTIVE_DATE,
MS_CPMS_CXL_DATE,
MS_CPMS_PRI_EMAIL,
MS_CPMS_FULL_MEMNO,
MS_CPMS_UPGRADE_DATE,
MS_CPMS_DOWNGRADE_DATE,
MS_CPMS_CXL_RSN,
MS_CPMS_DOB,
MS_CPMS_GENDER,
MS_CPMS_HOM_PHONE,
MS_CPMS_WRK_PHONE,
MS_CPMS_MOB_PHONE,
MS_CPMS_NAME_PREFIX,
MS_CPMS_NAME_FIRSTONLY,
MS_CPMS_NAME_MIDONLY,
MS_CPMS_NAME_LASTONLY,
MS_CPMS_NAME_SUFFIX,
MS_CPMS_RES_ADDR_LN1,
MS_CPMS_RES_ADDR_LN2,
MS_CPMS_RES_CITY,
MS_CPMS_RES_STATE,
MS_CPMS_RES_ZIP,
MS_CPMS_PROD_STATE,
MS_CPMS_TIMESTAMP) AS CONCAT_STRING
FROM (
SELECT
'005' AS MS_CPMS_CHG_BASE_SEG,
LPAD(MEMBERSHIP_DIM.MEMBERSHIP_NUM,8,'0') AS MS_CPMS_HH_NO,
RPAD(UPPER(IFNULL(CAST(CUST_DIM.ASSOCIATE_ID AS STRING),'')),1,' ') AS MS_CPMS_HH_PFX,
RPAD(UPPER(IFNULL(CUST_DIM.LAST_NM,'')),16,' ') AS MS_CPMS_NAME_LAST,
RPAD(UPPER(IFNULL(CUST_DIM.FIRST_NM,'')),12,' ') AS MS_CPMS_NAME_FIRST,
RPAD(UPPER(IFNULL(CUST_DIM.BILLING_ADDRESS_LINE1,'')),60,' ') AS MS_CPMS_MAIL_ADDR_LN1,
RPAD(UPPER(IFNULL(CUST_DIM.BILLING_ADDRESS_LINE2,'')),60,' ')  AS MS_CPMS_MAIL_ADDR_LN2,
RPAD(UPPER(IFNULL(CUST_DIM.BILLING_CITY,'')),40,' ')  AS MS_CPMS_MAIL_CITY,
RPAD(UPPER(IFNULL(CUST_DIM.BILLING_STATE,'')),2,' ')  AS MS_CPMS_MAIL_STATE,
RPAD(UPPER(IFNULL(CUST_DIM.BILLING_ZIP,'')),5,' ') AS MS_CPMS_MAIL_ZIP,
RPAD(UPPER(IFNULL(CASE WHEN MEMBERSHIP_DIM.TRANSFER_IN_IND         ='Y' THEN 'T'
      WHEN CUST_DIM.STATUS_CD ='C' THEN 'I'
      WHEN upper(MEMBERSHIP_DIM.DERIVED_MEMBERSHIP_STATUS)='ACTIVE' THEN 'A'
	WHEN upper(MEMBERSHIP_DIM.DERIVED_MEMBERSHIP_STATUS)='CANCELLED' THEN 'I'
	WHEN upper(MEMBERSHIP_DIM.DERIVED_MEMBERSHIP_STATUS)='LAPSED' THEN 'I'
	WHEN upper(MEMBERSHIP_DIM.DERIVED_MEMBERSHIP_STATUS)='PENDING' THEN 'A'
	WHEN upper(MEMBERSHIP_DIM.DERIVED_MEMBERSHIP_STATUS)='GRACE' THEN 'P'   
  else CUST_DIM.STATUS_CD   END,'')),1,' ') AS MS_CPMS_MEMBER_STATUS,
RPAD(UPPER(IFNULL(case WHEN TRIM(CUST_DIM.HOME_PHONE_NUM) is null 
THEN REGEXP_REPLACE(CUST_DIM.WORK_PHONE_NUM, r'\D', '')
else REGEXP_REPLACE(CUST_DIM.HOME_PHONE_NUM, r'\D', '') end,'')),10,' ') as MS_CPMS_PRI_PHONE,
RPAD(UPPER(IFNULL(CUST_DIM.MEMBER_SINCE,'')),4,' ') AS MS_CPMS_CSAA_BASE_YEAR,
RPAD(UPPER(IFNULL(FORMAT_DATE("%m/%d/%Y",MEMBERSHIP_DIM.TERM_EXPIRATION_DT),'')),10,' ') as MS_CPMS_EXP_DATE, 
RPAD(UPPER(IFNULL(IG_PRODUCT_CD,'')),2,' ') as MS_CPMS_SVC_COVERAGE, -- Create the Membership Proudct Lookup table  
RPAD(UPPER(IFNULL(FORMAT_DATE("%m/%d/%Y",CUST_DIM.INCEPTION_DT),'')),10,' ')  as MS_CPMS_ACTIVE_DATE,
RPAD(UPPER(IFNULL(FORMAT_DATE("%m/%d/%Y",CUST_DIM.CANCEL_DT),'')),10,' ')  as MS_CPMS_CXL_DATE,
RPAD(UPPER(IFNULL(CUST_DIM.EMAIL_ADDRESS,'')),100,' ')  as MS_CPMS_PRI_EMAIL,
RPAD(UPPER(IFNULL(CUST_DIM.MEMBER_NUM,'')),16,' ')  as MS_CPMS_FULL_MEMNO,
RPAD(UPPER(IFNULL(FORMAT_DATE("%m/%d/%Y",MEMBERSHIP_DIM.LAST_UPGRADE_DT),'')),10,' ')  as MS_CPMS_UPGRADE_DATE,
RPAD(UPPER(IFNULL(FORMAT_DATE("%m/%d/%Y",MEMBERSHIP_DIM.LAST_DOWNGRADE_DT),'')),10,' ')  as MS_CPMS_DOWNGRADE_DATE,
RPAD(UPPER(IFNULL(CUST_DIM.DO_NOT_RENEW_REASON,'')),100,' ')  as MS_CPMS_CXL_RSN,
RPAD(UPPER(IFNULL(FORMAT_DATE("%m/%d/%Y",CUST_DIM.BIRTH_DT),'')),10,' ')  as MS_CPMS_DOB,
RPAD(UPPER(IFNULL(CUST_DIM.GENDER_CD,'')),1,' ')  as MS_CPMS_GENDER,
RPAD(UPPER(IFNULL(REGEXP_REPLACE(CUST_DIM.HOME_PHONE_NUM, r'\D', ''),'')),10,' ') AS MS_CPMS_HOM_PHONE,
RPAD(UPPER(IFNULL(REGEXP_REPLACE(CUST_DIM.WORK_PHONE_NUM, r'\D', ''),'')),10,' ') AS MS_CPMS_WRK_PHONE,
RPAD(UPPER(IFNULL(REGEXP_REPLACE(CUST_DIM.MOBILE_PHONE_NUM, r'\D', ''),'')),10,' ') AS MS_CPMS_MOB_PHONE,
RPAD(UPPER(IFNULL(CUST_DIM.SALUTATION_CD,'')),10,' ') AS MS_CPMS_NAME_PREFIX,
RPAD(UPPER(IFNULL(CUST_DIM.FIRST_NM,'')),40,' ') AS MS_CPMS_NAME_FIRSTONLY,
RPAD(UPPER(IFNULL(CUST_DIM.MID_INITIAL_NM,'')),50,' ') AS MS_CPMS_NAME_MIDONLY,
RPAD(UPPER(IFNULL(CUST_DIM.LAST_NM,'')),80,' ') AS MS_CPMS_NAME_LASTONLY,
'          '  AS MS_CPMS_NAME_SUFFIX, -- TITTLE Column is not connected in Member Informatica Mapping
RPAD(UPPER(IFNULL(CASE WHEN TRIM(CUST_DIM.RESIDENTIAL_ADDRESS_LINE1) is null 
THEN UPPER(CUST_DIM.BILLING_ADDRESS_LINE1)
ELSE UPPER(CUST_DIM.RESIDENTIAL_ADDRESS_LINE1) END,'')),60,' ') as MS_CPMS_RES_ADDR_LN1,
RPAD(UPPER(IFNULL(CASE WHEN TRIM(CUST_DIM.RESIDENTIAL_ADDRESS_LINE2) is null
THEN UPPER(CUST_DIM.BILLING_ADDRESS_LINE2)
ELSE UPPER(CUST_DIM.RESIDENTIAL_ADDRESS_LINE2) END,'')),60,' ') AS MS_CPMS_RES_ADDR_LN2,
RPAD(UPPER(IFNULL(CASE WHEN TRIM(CUST_DIM.RESIDENTIAL_CITY) is null
THEN UPPER(CUST_DIM.BILLING_CITY) 
ELSE UPPER(CUST_DIM.RESIDENTIAL_CITY) END,'')),40,' ') AS MS_CPMS_RES_CITY,
RPAD(UPPER(IFNULL(CASE WHEN TRIM(CUST_DIM.RESIDENTIAL_STATE) is null
THEN UPPER(CUST_DIM.BILLING_STATE) 
ELSE UPPER(CUST_DIM.RESIDENTIAL_STATE) END,'')),2,' ') AS MS_CPMS_RES_STATE,
RPAD(UPPER(IFNULL(CASE WHEN TRIM(CUST_DIM.RESIDENTIAL_ZIP) is null
THEN CUST_DIM.BILLING_ZIP
ELSE CUST_DIM.RESIDENTIAL_ZIP END,'')),5,' ') AS MS_CPMS_RES_ZIP,
RPAD(UPPER(IFNULL(UPPER(MEMBERSHIP_DIM.ISSUING_STATE),'')),2,' ') AS MS_CPMS_PROD_STATE,
RPAD(UPPER(IFNULL(cast(CURRENT_DATETIME() as string),'')),23,' ') AS MS_CPMS_TIMESTAMP
FROM 
CUSTOMERS.CONNECTSUITE_MEMBER as CUST_DIM 
INNER JOIN
OPERATIONAL.CONNECTSUITE_MEMBERSHIP as MEMBERSHIP_DIM
on CUST_DIM.MEMBERSHIP_NUM =MEMBERSHIP_DIM.MEMBERSHIP_NUM
INNER JOIN
REFERENCE.CONNECTSUITE_PRODUCT_DIM PD
on PD.PRODUCT_CD=MEMBERSHIP_DIM.MEMBERSHIP_LEVEL
AND CS_MODULE='M'
WHERE GREATEST(MEMBERSHIP_DIM.UPDATE_DTTIME,CUST_DIM.PROFILE_UPDATE_DTTIME , CUST_DIM.UPDATE_DTTIME)>'{{ prev_execution_date }}'
)
