SELECT distinct 
'005' AS Club
,TRIM(BRANCH_NM) AS fac
,TRIM(CONTACT_FIRST_NM) AS first_name
,TRIM(CONTACT_LAST_NM) AS last_name
,REGEXP_REPLACE(IFNULL(TRIM(ADDRESS_STREET),' '),r"\r\n",' ') AS address1
,NULL AS address2
,TRIM(CITY) AS city
,TRIM(STATE_CD) AS state
,TRIM(POSTAL_CD) AS zipcode
,TRIM(CONTACT_EMAIL) AS email
,CASE WHEN INVOICE_DTTIME is null then null
ELSE RPAD(CONCAT(LPAD(CAST(EXTRACT(MONTH FROM INVOICE_DTTIME) AS STRING),2,'0'),LPAD(CAST(EXTRACT(DAY FROM INVOICE_DTTIME) AS STRING),2,'0'),SUBSTR(CAST(EXTRACT(YEAR FROM INVOICE_DTTIME) AS STRING),3,2)),6,' ')
END AS tran_date
,INVOICE_KEY AS tran_id
,INVOICE_KEY AS inv_no
,IFNULL(TRIM(MEMBERSHIP_NUM),NULL) AS mem_no
,IFNULL(TRIM(SERVICE_ADVISOR_NM),NULL) AS clubopt1
,TECHNICIAN_NM AS clubopt2
,INVOICE_NUM AS clubopt3
,NULL AS clubopt4
,NULL AS clubopt5
,NULL AS clubopt6
,NULL AS clubopt7
,NULL AS clubopt8
,NULL AS clubopt9
,NULL AS clubopt10
,NULL AS age
,NULL AS gender
,CASE WHEN COALESCE(UPPER(CONTACT_PHONE1_TYPE),UPPER(CONTACT_PHONE2_TYPE)) IS NOT NULL
THEN COALESCE(REGEXP_REPLACE(CONTACT_PHONE1,'[^0-9]',''),REGEXP_REPLACE(CONTACT_PHONE2,'[^0-9]',''))
WHEN  SUBSTR(REGEXP_REPLACE(CONTACT_NOTE,'[^0-9]',''),0,10) IS NOT NULL 
		THEN SUBSTR(REGEXP_REPLACE(CONTACT_NOTE,'[^0-9]',''),0,10)   
ELSE NULL     
  END AS cell
,NULL AS textconsent
FROM  LANDING.PROTRACTOR_STAGE_INVOICE
where SURVEY_SENT_IND<>'Y'
and CREATE_DTTIME >'{{ prev_execution_date }}'
