SELECT DISTINCT 
   '005' AS AAAClubNumber,
   INV.INVOICE_DT AS InvoiceDate,
   INV.INVOICE_NUM AS InvoiceNumber,
   INV.TRAVELER as Traveler,
   MBR.MEMBER_NUM AS MemberNbr,
   null as MemberOTH,
   null as MemberACID,
   'Y' as MemberFlag,
   INV.TRAVEL_TYPE AS TravelType,
   INV.REV_TYPE AS RevType,
   PROVIDER AS Provider,
  SALE_TYPE AS Independent_or_Group,
  Case WHEN TRAVEL_TYPE in ('S','T') THEN TRAVEL_TYPE ELSE NULL END AS Ship_or_Tour,
  null as Air_Rail_Origin, -- Need to confirm with Business
  null as Air_Rail_Destination, -- Need to confirm with Business
  INV.DESTINATION as Destination,
  DESTINATION_REGION as MarketCode,
  DOMINT as DomInt,
  INV.DEPART_DT as DepartDate,
  INV.RETURN_DT as ReturnDate,
 DATE_DIFF(RETURN_DT,DEPART_DT,DAY) AS NbrDays,
  INV.BASEFARE as BaseFare,
 INV.TAX1 as Tax1,
 INV.TAX2 as Tax2,
 INV.TAX3 as Tax3,
 INV.TAX4 as Tax4,
 INV.MISCCHARGE as MiscCharge,
 INV.DISCOUNT as Discount,
 INV.EXCHANGE as Exchange,
 INV.TOTAL_COST as TotalCost,
 INV.STATUS as V_E_R,
 INV.ITINERARY as Deposit_Full_Final,
 COMM_PERCENT as CommPercent,
 COMM_AMOUNT as CommAmount,
  FOP,
  null as CCCompany,
  PNR_LOCATOR as PnrLocator,
  PASSENGER_COUNT as Count,
  BRANCH as Branch,
  BKAGT as BkAgt,
  PROMOTION_CD AS WhereHeard,
  PASSENGER_COUNT as NbrPax,
  TRAVELER_ADDRESS_LINE_1 AS MailingAddressLine1,
  TRAVELER_ADDRESS_LINE_2 AS MailingAddressLine2,
  TRAVELER_CITY AS MailingCity,
  TRAVELER_STATE AS MailingState,
  TRAVELER_ZIP_CD AS MailingZip,
  EMAIL AS EmailAddress,
  Null as EmailEligibilityFlg,
  Null as ConsumerOnlineTrxFlg,
  STATE_CD AS BranchState,
  CONCAT(IFNULL(LEGAL_FIRST_NM,''),' ',IFNULL(LEGAL_MIDDLE_NM,''),' ',IFNULL(LEGAL_LAST_NM,'')) as OPTIONAL_1,
  Null as OPTIONAL_2,
  Null as OPTIONAL_3,
  Null as OPTIONAL_4,
  Null as  OPTIONAL_5,
  'Y' as TravelAgentflg
  FROM (SELECT * FROM (
select INVOICE.*,ROW_NUMBER() OVER (partition by PNR_LOCATOR order by PAY_ID desc) as ROW_NUM
FROM OPERATIONAL.GLOBALWARE_INVOICE  INVOICE where INVOICE_DT>=DATE_SUB(CURRENT_DATE(),INTERVAL 7 DAY) 
AND  INVOICE_DT<=DATE_SUB(CURRENT_DATE(),INTERVAL 2 DAY)
AND TRAVEL_TYPE in ('S','T') AND STATUS<>'V' and BKAGT is not null
AND SURVEY_IND<>'Y')  where ROW_NUM=1 )INV
INNER JOIN
(SELECT INVOICE_PAY_ID,EMAIL,TRAVELER_ADDRESS_LINE_1,TRAVELER_ADDRESS_LINE_2,TRAVELER_CITY,
TRAVELER_STATE,TRAVELER_ZIP_CD,TRAVELER_PHONE_NUM,ANTICIPATED_SALE_AMOUNT,SOJOURN_CD,
ANTICIPATED_COMMISSION_AMOUNT,DESTINATION_REGION,PASSENGER_COUNT,BOOKING_TYPE,CANCELLATION_DT,PROMOTION_CD,AUTO_TRAVEL_FLAG,
CASE WHEN (SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,6) = '438255' and LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) > 12)
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),7,8)
	 WHEN (SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,3) = '255' and LENGTH (CAST(COMMENTS.MEMBER_NUM AS STRING)) > 10)
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),4,8)
    WHEN LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) = 8
	 THEN CAST(COMMENTS.MEMBER_NUM AS STRING) 
	 WHEN LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) = 9 
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,8)
	 WHEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,6) = '005429' 
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),7,8)
	 WHEN (SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,9) = '005429005' and (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING))=17 OR LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING))=19))
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),10,8)
	 WHEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,6) = '429005' 
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),7,8)
	 WHEN (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) = 10 and (SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),9,2)='14' OR SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),9,2)='22') )
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,8)
	 WHEN (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) = 11 and SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),4,8)
	 WHEN (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) = 12 and SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,3) = '005') 
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),5,8)
	 WHEN (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) = 13 and SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),6,8)
	 WHEN (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) = 14 and SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),7,8)
	 WHEN (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) = 15 and SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),8,8)
	 WHEN (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) >= 15 and LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) <= 16 and SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,6) = '005005')
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),8,8)
	 WHEN (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) > 16 and SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,9) = '005005429')
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),11,8)
	 ELSE NULL
	 END MEMBERSHIP_NUM,
CASE WHEN (SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,6) = '438255' and LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) > 12)
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),15,1)
	 WHEN (SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,3) = '255' and LENGTH (CAST(COMMENTS.MEMBER_NUM AS STRING)) > 10)
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),12,1)
    WHEN LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) = 8
	 THEN '1'
	 WHEN LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) = 9 
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,1)
	 WHEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,6) = '005429' 
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),15,1)
	 WHEN (SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,9) = '005429005' and (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING))=17 OR LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING))=19))
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),18,1)
	 WHEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,6) = '429005' 
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),15,1)
	 WHEN (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) = 10 and (SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),9,2)='14' OR SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),9,2)='22') )
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),9,1)
	 WHEN (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) = 11 and SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,3) = '005')
	 THEN '1'
	 WHEN (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) = 12 and SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,3) = '005') 
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),4,1)
	 WHEN (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) = 13 and SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),4,1)
	 WHEN (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) = 14 and SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),4,1)
	 WHEN (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) = 15 and SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,3) = '005')
	 THEN SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),4,1)
	 WHEN (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) >= 15 and LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) <= 16 and SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,6) = '005005')
	 THEN '1'
	 WHEN (LENGTH(CAST(COMMENTS.MEMBER_NUM AS STRING)) > 16 and SUBSTR(CAST(COMMENTS.MEMBER_NUM AS STRING),1,9) = '005005429')
	 THEN '1'
	 ELSE NULL
	 END   ASSOCIATE_ID 
FROM (SELECT DISTINCT 
INVOICE_PAY_ID,
MAX(CASE WHEN LINE_NUM='28' THEN REPLACE(DATA,'//','@') ELSE NULL END) EMAIL,
MAX(CASE WHEN LINE_NUM='9' THEN REPLACE(TRIM(DATA),'//','@') ELSE NULL END) MEMBER_NUM,
MAX(CASE WHEN LINE_NUM='21' THEN REPLACE(DATA,'//','@') ELSE NULL END) TRAVELER_ADDRESS_LINE_1,
MAX(CASE WHEN LINE_NUM='22' THEN REPLACE(DATA,'//','@') ELSE NULL END) TRAVELER_ADDRESS_LINE_2,
MAX(CASE WHEN LINE_NUM='23' THEN REPLACE(DATA,'//','@') ELSE NULL END) TRAVELER_CITY,
MAX(CASE WHEN LINE_NUM='27' THEN REPLACE(TRIM(DATA),'//','@') ELSE NULL END) TRAVELER_STATE,
MAX(CASE WHEN LINE_NUM='24' THEN REPLACE(DATA,'//','@') ELSE NULL END) TRAVELER_ZIP_CD,
MAX(CASE WHEN LINE_NUM='25' THEN REPLACE(DATA,'//','@') ELSE NULL END) TRAVELER_PHONE_NUM,   
MAX(CASE WHEN LINE_NUM='2' THEN DATA ELSE NULL END) ANTICIPATED_SALE_AMOUNT,
MAX(CASE WHEN LINE_NUM='82' THEN DATA ELSE NULL END )SOJOURN_CD,
MAX(CASE WHEN LINE_NUM='10' THEN DATA ELSE NULL END) ANTICIPATED_COMMISSION_AMOUNT,
MAX(CASE WHEN LINE_NUM='102' THEN DATA ELSE NULL END) DESTINATION_REGION,
MAX(CASE WHEN LINE_NUM='1' THEN DATA ELSE NULL END) PASSENGER_COUNT,
MAX(CASE WHEN LINE_NUM='31' THEN DATA ELSE NULL END) BOOKING_TYPE,
MAX(CASE WHEN LINE_NUM='30' THEN DATA ELSE NULL END) CANCELLATION_DT,
MAX(CASE WHEN LINE_NUM='8' THEN DATA ELSE NULL END) PROMOTION_CD,
MAX(CASE WHEN LINE_NUM='14' THEN TRIM(DATA) ELSE NULL END) AUTO_TRAVEL_FLAG
FROM OPERATIONAL.GLOBALWARE_COMMENTS 
where INVOICE_PAY_ID in (select distinct PAY_ID from OPERATIONAL.GLOBALWARE_INVOICE 
where INVOICE_DT>=DATE_SUB(CURRENT_DATE(),INTERVAL 7 DAY) AND TRAVEL_TYPE in ('S','T') AND STATUS<>'V')
GROUP BY 1) COMMENTS ) C
ON C.INVOICE_PAY_ID=INV.PAY_ID
INNER JOIN CUSTOMERS.CONNECTSUITE_MEMBER MBR
ON MBR.MEMBERSHIP_NUM=C.MEMBERSHIP_NUM AND CAST(MBR.ASSOCIATE_ID AS STRING)=C.ASSOCIATE_ID
LEFT OUTER JOIN LANDING.CUR_WD_EMPLOYEE ED1 ON  TRIM(INV.BKAGT) = ED1.TRAVEL_ID 
LEFT OUTER JOIN (select DISTINCT LOCATION_ID,SL.STATE_CD from CUSTOMER_PRODUCT.LOCATION_DIM L,REFERENCE.STATE_LOOKUP SL
WHERE L.STATE_CD=SL.STATE
AND ACTIVE_FLG='Y') LD
ON  SUBSTR(INV.BRANCH,-3)=LOCATION_ID
where 
NOT EXISTS (SELECT 1 FROM  OPERATIONAL.GLOBALWARE_INVOICE INV_CHK where SURVEY_IND='Y' and INV.PNR_LOCATOR=INV_CHK.PNR_LOCATOR) 
