SELECT
  MEMBERSHIP_ID,
  EVENT_TYPE,
  EVENT_DATE,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN MEMBER_NUM
      ELSE NULL END) AS MEMBER_NUM,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN MEMBER_SINCE
      ELSE NULL END) AS MEMBER_SINCE,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN TERM_EXPIRATION_DT
      ELSE NULL END) AS MEMBER_EXPIRY_DT,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN PLAN
      ELSE NULL END) AS PLAN,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN FIRST_NAME
      ELSE NULL END) AS FIRST_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN MIDDLE_INITIAL
      ELSE NULL END) AS MI,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN LAST_NAME
      ELSE NULL END) AS LAST_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN PRM_EMAIL_ADDRESS
      ELSE NULL END) AS EMAIL,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN PRM_HOME_PHONE_NUM
      ELSE NULL END) AS PHONE,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN PRM_BILLING_ADDRESS_LINE1
      ELSE NULL END) AS ADDRESS1,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN PRM_BILLING_CITY
      ELSE NULL END) AS CITY,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN PRM_BILLING_STATE
      ELSE NULL END) AS STATE,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN PRM_BILLING_ZIP
      ELSE NULL END) AS ZIP,
  'USA' AS COUNTRY,
  NULL AS CC_LAST_4_DIGITS,
  NULL AS SEC_MEMBER_DATA_PRESENT,
  -- Need to look
  NULL AS ASSOC_MEMBER_DATA_PRESENT,
  -- Need to look
  NULL AS NUM_ASSOC_MEMBERS,
  -- Need to look
  NULL AS DONOR_MEMBER_DATA_PRESENT,
  -- Need to look
  NULL AS GROUP_DATA_PRESENT,
  -- Need to look
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN MEMBER_NUM
      ELSE NULL END) AS PRIMARY_MEMBER_NUM,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN MEMBER_SINCE
      ELSE NULL END) AS PRIMARY_MEMBER_SINCE,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN TERM_EXPIRATION_DT
      ELSE NULL END) AS PRIMARY_MEMBER_EXPIRY_DT,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN FIRST_NAME
      ELSE NULL END) AS PRIMARY_MEMBER_FIRST_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN MIDDLE_INITIAL
      ELSE NULL END) AS PRIMARY_MEMBER_MI,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=1 THEN LAST_NAME
      ELSE NULL END) AS PRIMARY_MEMBER_LAST_NAME,
  -- MAX(CASE WHEN MEMBER_SEQUENCE_NUM=1 THEN NAME_ON_MEMBERSHIP_CARD ELSE NULL END) AS PRIMARY_MEMBER_FULL_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=2 THEN MEMBER_NUM
      ELSE NULL END) AS SEC_MEMBER_NUM,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=2 THEN MEMBER_SINCE
      ELSE NULL END) AS SEC_MEMBER_SINCE,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=2 THEN TERM_EXPIRATION_DT
      ELSE NULL END) AS SEC_MEMBER_EXPIRY_DT,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=2 THEN FIRST_NAME
      ELSE NULL END) AS SEC_MEMBER_FIRST_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=2 THEN MIDDLE_INITIAL
      ELSE NULL END) AS SEC_MEMBER_MI,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=2 THEN LAST_NAME
      ELSE NULL END) AS SEC_MEMBER_LAST_NAME,
  -- MAX(CASE WHEN MEMBER_SEQUENCE_NUM=2 THEN NAME_ON_MEMBERSHIP_CARD ELSE NULL END) AS SEC_MEMBER_FULL_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=3 THEN MEMBER_NUM
      ELSE NULL END) AS ASSOC_1_MEMBER_NUM,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=3 THEN MEMBER_SINCE
      ELSE NULL END) AS ASSOC_1_MEMBER_SINCE,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=3 THEN TERM_EXPIRATION_DT
      ELSE NULL END) AS ASSOC_1_MEMBER_EXPIRY_DT,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=3 THEN FIRST_NAME
      ELSE NULL END) AS ASSOC_1_MEMBER_FIRST_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=3 THEN MIDDLE_INITIAL
      ELSE NULL END) AS ASSOC_1_MEMBER_MI,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=3 THEN LAST_NAME
      ELSE NULL END) AS ASSOC_1_MEMBER_LAST_NAME,
  -- MAX(CASE WHEN MEMBER_SEQUENCE_NUM=3 THEN NAME_ON_MEMBERSHIP_CARD ELSE NULL END) AS ASSOC_1_MEMBER_FULL_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=4 THEN MEMBER_NUM
      ELSE NULL END) AS ASSOC_2_MEMBER_NUM,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=4 THEN MEMBER_SINCE
      ELSE NULL END) AS ASSOC_2_MEMBER_SINCE,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=4 THEN TERM_EXPIRATION_DT
      ELSE NULL END) AS ASSOC_2_MEMBER_EXPIRY_DT,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=4 THEN FIRST_NAME
      ELSE NULL END) AS ASSOC_2_MEMBER_FIRST_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=4 THEN MIDDLE_INITIAL
      ELSE NULL END) AS ASSOC_2_MEMBER_MI,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=4 THEN LAST_NAME
      ELSE NULL END) AS ASSOC_2_MEMBER_LAST_NAME,
  -- MAX(CASE WHEN MEMBER_SEQUENCE_NUM=4 THEN NAME_ON_MEMBERSHIP_CARD ELSE NULL END) AS ASSOC_2_MEMBER_FULL_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=5 THEN MEMBER_NUM
      ELSE NULL END) AS ASSOC_3_MEMBER_NUM,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=5 THEN MEMBER_SINCE
      ELSE NULL END) AS ASSOC_3_MEMBER_SINCE,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=5 THEN TERM_EXPIRATION_DT
      ELSE NULL END) AS ASSOC_3_MEMBER_EXPIRY_DT,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=5 THEN FIRST_NAME
      ELSE NULL END) AS ASSOC_3_MEMBER_FIRST_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=5 THEN MIDDLE_INITIAL
      ELSE NULL END) AS ASSOC_3_MEMBER_MI,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=5 THEN LAST_NAME
      ELSE NULL END) AS ASSOC_3_MEMBER_LAST_NAME,
  -- MAX(CASE WHEN MEMBER_SEQUENCE_NUM=5 THEN NAME_ON_MEMBERSHIP_CARD ELSE NULL END) AS ASSOC_3_MEMBER_FULL_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=6 THEN MEMBER_NUM
      ELSE NULL END) AS ASSOC_4_MEMBER_NUM,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=6 THEN MEMBER_SINCE
      ELSE NULL END) AS ASSOC_4_MEMBER_SINCE,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=6 THEN TERM_EXPIRATION_DT
      ELSE NULL END) AS ASSOC_4_MEMBER_EXPIRY_DT,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=6 THEN FIRST_NAME
      ELSE NULL END) AS ASSOC_4_MEMBER_FIRST_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=6 THEN MIDDLE_INITIAL
      ELSE NULL END) AS ASSOC_4_MEMBER_MI,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=6 THEN LAST_NAME
      ELSE NULL END) AS ASSOC_4_MEMBER_LAST_NAME,
  -- MAX(CASE WHEN MEMBER_SEQUENCE_NUM=6 THEN NAME_ON_MEMBERSHIP_CARD ELSE NULL END) AS ASSOC_4_MEMBER_FULL_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=7 THEN MEMBER_NUM
      ELSE NULL END) AS ASSOC_5_MEMBER_NUM,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=7 THEN MEMBER_SINCE
      ELSE NULL END) AS ASSOC_5_MEMBER_SINCE,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=7 THEN TERM_EXPIRATION_DT
      ELSE NULL END) AS ASSOC_5_MEMBER_EXPIRY_DT,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=7 THEN FIRST_NAME
      ELSE NULL END) AS ASSOC_5_MEMBER_FIRST_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=7 THEN MIDDLE_INITIAL
      ELSE NULL END) AS ASSOC_5_MEMBER_MI,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=7 THEN LAST_NAME
      ELSE NULL END) AS ASSOC_5_MEMBER_LAST_NAME,
  -- MAX(CASE WHEN MEMBER_SEQUENCE_NUM=7 THEN NAME_ON_MEMBERSHIP_CARD ELSE NULL END) AS ASSOC_5_MEMBER_FULL_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=8 THEN MEMBER_NUM
      ELSE NULL END) AS ASSOC_6_MEMBER_NUM,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=8 THEN MEMBER_SINCE
      ELSE NULL END) AS ASSOC_6_MEMBER_SINCE,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=8 THEN TERM_EXPIRATION_DT
      ELSE NULL END) AS ASSOC_6_MEMBER_EXPIRY_DT,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=8 THEN FIRST_NAME
      ELSE NULL END) AS ASSOC_6_MEMBER_FIRST_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=8 THEN MIDDLE_INITIAL
      ELSE NULL END) AS ASSOC_6_MEMBER_MI,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=8 THEN LAST_NAME
      ELSE NULL END) AS ASSOC_6_MEMBER_LAST_NAME,
  -- MAX(CASE WHEN MEMBER_SEQUENCE_NUM=8 THEN NAME_ON_MEMBERSHIP_CARD ELSE NULL END) AS ASSOC_6_MEMBER_FULL_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=9 THEN MEMBER_NUM
      ELSE NULL END) AS ASSOC_7_MEMBER_NUM,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=9 THEN MEMBER_SINCE
      ELSE NULL END) AS ASSOC_7_MEMBER_SINCE,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=9 THEN TERM_EXPIRATION_DT
      ELSE NULL END) AS ASSOC_7_MEMBER_EXPIRY_DT,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=9 THEN FIRST_NAME
      ELSE NULL END) AS ASSOC_7_MEMBER_FIRST_NAME,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=9 THEN MIDDLE_INITIAL
      ELSE NULL END) AS ASSOC_7_MEMBER_MI,
  MAX(CASE
      WHEN MEMBER_SEQUENCE_NUM=9 THEN LAST_NAME
      ELSE NULL END) AS ASSOC_7_MEMBER_LAST_NAME,
  -- MAX(CASE WHEN MEMBER_SEQUENCE_NUM=9 THEN NAME_ON_MEMBERSHIP_CARD ELSE NULL END) AS ASSOC_7_MEMBER_FULL_NAME,
  NULL AS DONOR_FIRST_NAME,
  -- No Source Column
  NULL AS DONOR_MI,
  -- No Source Column
  NULL AS DONOR_LAST_NAME,
  -- No Source Column
  NULL AS GROUP_NAME,
  -- No Source Column
  NULL AS SOURCE_KEY,
  -- Need to look
  NULL AS SOURCE_CREATE_DTTIME,
  -- Need to look
  NULL AS SOURCE_LAST_UPDATE_DTTIME,
  -- Need to look
  NULL AS FILE_GENERATED,
  -- Need to look
  NULL AS OUTPUT_FILE_NAME,
  -- Need to look
  NULL AS ETL_JOB_RUN_ID,
  -- Need to look
  NULL AS SOURCE_SYSTEM_CD,
  -- Need to look
  CURRENT_DATE() AS CREATE_DTTIME,
  -- Need to look
  NULL AS AR_ENROLL_FLAG -- Need to look
FROM
  LANDING.WORK_MEMBERSHIP_NOTIFICATION
GROUP BY
  MEMBERSHIP_ID,
  EVENT_TYPE,
  EVENT_DATE;