CREATE VIEW IF NOT EXISTS `usps-bigquery.data_warehouse.dim_anp_opportunities`
AS
SELECT
    mac_id,
    opportunity_id,
    -- opportunity_name,
    -- account_name,
    -- address_physical_location_line_!,
    account_city,
    account_state,
    account_zip_code,
    lead_source_category,
    lead_source_type,
    mac_description,
    media,
    product_category,
    product_group,
    -- opportunity_owner,
    -- opportunity_owner_title,
    -- manager,
    -- area_manager,
    opportunity_district,
    opportunity_area,
    amount, 
    stage,
    closed_lost_reason,
    close_won_reason,
    opportunistic_strategy,
    description,
    created_date,
    expected_start_mail_date,
    current_stage_entry_date,
    last_activity,
    actual_start_mail_date,
    approval_status,
    user_type,
    opportunity_owner_user_type,
    closed_user_type,
    load_timestamp
FROM 
    `usps-bigquery.operational.anp_opportunities`