CREATE VIEW IF NOT EXISTS `usps-bigquery.data_warehouse.dim_medallia_survey`
AS
SELECT
    browser,
	browser_language,
	browser_version,
	city,
	country,
	delivery_feedback__reason,
	delivery_mailpackage,
	delivery_senderreceiver,
	device_marketing_name,
	device_model,
	device_vendor,
	digital_google_analytics_id__ga,
	digital_google_analytics_id__gid,
	digital_survey,
	ip_address,
	is_mobile_device ,
	is_mobile_phone ,
	is_tablet ,
	likelihood_to_recommend_0_10,
	operating_system,
	os_version,
	osat_gen_intercept_and_always_on_0_10,
	osat_npa_1_6,
	primary_tracking_category,
	region,
	response_date ,
	retail_feedback_reason,
	screen_resolution,
	secondary_tracking_category,
	survey_id,
	tracking_personal_or_business_customer,
	tracking_product_name,
	tracking_sender_or_receiver,
	unique_record_id,
	url,
	url_anchor,
	url_host,
	url_path,
	usable_screen_resolution,
	usps_digital_abandon_comment,
	usps_digital_abandon_reason,
	usps_digital_accomplish_issue_comment,
	usps_digital_always_on_delivery_comment,
	usps_digital_always_on_delivery_osat,
	usps_digital_always_on_delivery_reason_comment,
	usps_digital_always_on_delivery_reason_other,
	usps_digital_always_on_delivery_zip,
	usps_digital_always_on_feedback_type,
	usps_digital_always_on_main_issue_website,
	usps_digital_always_on_retail_comment,
	usps_digital_always_on_retail_osat,
	usps_digital_always_on_retail_reason_comment,
	usps_digital_always_on_retail_reason_other,
	usps_digital_always_on_retail_zip,
	usps_digital_always_on_site_issue ,
	usps_digital_permission_to_contact ,
	usps_digital_primary_reason_for_visit,
	usps_digital_primary_reason_for_visit___other_text,
	usps_digital_reason_for_score_comment,
	usps_digital_task_accomplishment,
	usps_digital_tracking_additional_information_comment,
	usps_digital_tracking_destination_location,
	usps_digital_tracking_easy_to_find,
	usps_digital_tracking_easy_to_understand,
	usps_digital_tracking_id,
	usps_digital_tracking_osat_0_10,
	usps_digital_tracking_where_to_go,
	uuid,
	load_timestamp
FROM
    `usps-bigquery.operational.medallia_survey` --paramterize query