delete FROM `LANDING.WORK_AMEX_ADJUSTMENT_RECORD` where true;
delete FROM `LANDING.WORK_AMEX_CHARGEBACK_RECORD` where true;
delete FROM `LANDING.WORK_AMEX_FEES_AND_REVENUES_RECORD` where true;
delete FROM `LANDING.WORK_AMEX_SUBMISSION_RECORD` where true;
delete FROM `LANDING.WORK_AMEX_SUMMARY_RECORD` where true;
delete FROM `LANDING.WORK_AMEX_TAX_RECORD` where true;
delete FROM `LANDING.WORK_AMEX_TRANSACTION_PRICING_RECORD` where true;
delete FROM `LANDING.WORK_AMEX_TRANSACTION_RECORD` where true
