INSERT INTO OPERATIONAL.AMEX_PAYMENT_TAX
(
RECORD_TYPE,
PAYEE_MERCHANT_ID,
SETTLEMENT_ACCOUNT_TYPE_CD,
AMERICAN_EXPRESS_PAYMENT_NUM,
PAYMENT_DT,
PAYMENT_CURRENCY,
TAX_TYPE_CD,
TAX_DESC,
TAX_BASE_AMT,
TAX_PRESENT_DT,
TAX_RT,
TAX_AMT,
FILLER,
JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATED_BY,
CREATE_DTTIME
)
SELECT 
RECORD_TYPE,
PAYEE_MERCHANT_ID,
SETTLEMENT_ACCOUNT_TYPE_CD,
AMERICAN_EXPRESS_PAYMENT_NUM,
PARSE_DATE('%Y%m%d',PAYMENT_DT) AS PAYMENT_DT,
PAYMENT_CURRENCY,
TAX_TYPE_CD,
TAX_DESC,
CASE WHEN TAX_BASE_AMT ='' THEN NULL ELSE
CAST(TAX_BASE_AMT AS FLOAT64) END AS  TAX_BASE_AMT,
PARSE_DATE('%Y%m%d', TAX_PRESENT_DT ) AS TAX_PRESENT_DT,
CASE WHEN TAX_RATE ='' THEN NULL ELSE
CAST(TAX_RATE AS FLOAT64) END AS  TAX_RT,
CASE WHEN TAX_AMT ='' THEN NULL ELSE
CAST( TAX_AMT AS FLOAT64) END AS TAX_AMT,
FILLER,
'v_job_run_id' AS JOB_RUN_ID,
'amex' AS SOURCE_SYSTEM_CD,
'v_job_name' AS CREATED_BY,
CURRENT_DATETIME() AS CREATE_DTTIME
FROM LANDING.WORK_AMEX_TAX_RECORD