INSERT INTO OPERATIONAL.AMEX_PAYMENT_TRANSACTION_PRICING 
(
RECORD_TYPE,
PAYEE_MERCHANT_ID,
SETTLEMENT_ACCOUNT_TYPE_CD,
AMERICAN_EXPRESS_PAYMENT_NUM,
PAYMENT_DT,
PAYMENT_CURRENCY,
SUBMISSION_MERCHANT_ID,
MERCHANT_LOCATION_ID,
FILLER,
INVOICE_REFERENCE_NUM,
SELLER_ID,
CARDMEMBER_ACCOUNT_NUM,
TRANSACTION_AMT,
TRANSACTION_DT,
FEE_CD,
FILLER_1,
FEE_AMT,
DISCOUNT_RT,
DISCOUNT_AMT,
FILLER_2,
JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATED_BY,
CREATE_DTTIME
)
SELECT 
RECORD_TYPE,
PAYEE_MERCHANT_ID,
SETTLEMENT_ACCOUNT_TYPE_CD,
AMERICAN_EXPRESS_PAYMENT_NUM,
PARSE_DATE('%Y%m%d',PAYMENT_DT) AS PAYMENT_DT,
PAYMENT_CURRENCY,
SUBMISSION_MERCHANT_ID,
MERCHANT_LOCATION_ID,
FILLER,
INVOICE_REFERENCE_NUM,
SELLER_ID,
CARDMEMBER_ACCOUNT_NUM,
CASE WHEN TRANSACTION_AMT ='' THEN NULL ELSE
CAST( TRANSACTION_AMT AS FLOAT64) END AS TRANSACTION_AMT,
PARSE_DATE('%Y%m%d',TRANSACTION_DT) AS TRANSACTION_DT,
FEE_CD,
FILLER_1,
CASE WHEN FEE_AMT ='' THEN NULL ELSE
CAST( FEE_AMT AS FLOAT64) END AS FEE_AMT,
CASE WHEN DISCOUNT_RATE ='' THEN NULL ELSE
CAST( DISCOUNT_RATE AS FLOAT64) END AS DISCOUNT_RT,
CASE WHEN DISCOUNT_AMT ='' THEN NULL ELSE
CAST( DISCOUNT_AMT AS FLOAT64) END AS DISCOUNT_AMT,
FILLER_2,
'v_job_run_id' AS JOB_RUN_ID,
'amex' AS SOURCE_SYSTEM_CD,
'v_job_name' AS CREATED_BY,
CURRENT_DATETIME() AS CREATE_DTTIME
FROM LANDING.WORK_AMEX_TRANSACTION_PRICING_RECORD