SELECT DISTINCT 
MEMBERSHIP_NUM as MEMBERSHIP_ID,
MEMBER_NUM as MEMBER_NUM,
NULL as ENTERPRISE_ID,
UPPER(FIRST_NM) AS FIRST_NAME,
UPPER(MID_INITIAL_NM) AS  MIDDLE_INITIAL,
UPPER(LAST_NM) AS LAST_NAME,
UPPER(BILLING_ADDRESS_LINE1) AS ADDRESS_LINE1,
UPPER(BILLING_CITY) AS CITY,
UPPER(BILLING_STATE) AS STATE,
UPPER(BILLING_ZIP) AS ZIP,
NULL AS ZIP4,
ASSOCIATE_ID AS MEMBER_SEQUENCE_NUM,
HOME_PHONE_NUM AS PHONENUM
FROM CUSTOMERS.CONNECTSUITE_MEMBER 
WHERE TERM_EXPIRY_DT >= DATE_SUB(CURRENT_DATE(),INTERVAL 72 DAY)
