SELECT
    COMMUNICATION_ID,
    COMMUNICATION_DT,
    FULL_MEMBERSHIP_NUMBER,
    UPPER(CELL_CODE) CELL_CODE,
    UPPER (FIRST_NAME)FIRST_NAME,
    UPPER(LAST_NAME)LAST_NAME,
    UPPER(ADDRESS_LINE_1) ADDRESS_LINE_1,
    UPPER(ADDRESS_LINE_2)ADDRESS_LINE_2,
    UPPER(CITY)CITY,
    UPPER(STATE) STATE,
    POSTCODE,
    SEGMENTATION_ID,
    SEGMENTATION_TITLE,
    UPPER(MEMBERSHIP_SOURCE_CODE) MEMBERSHIP_SOURCE_CODE,
    SOURCE,
    PARSE_DATE('%F', SOURCE_DT)SOURCE_DT
FROM `COR_ANALYTICS.STG_COR_MKT_DMC_2`