SELECT
    MEMBER_NUMBER_16_DIGITS,
    FIRST_NAME,
    LAST_NAME,
    ADDRESS_MAIL_ADDRESS_1,
    ADDRESS_MAIL_ADDRESS_2,
    ADDRESS_MAIL_CITY,
    ADDRESS_MAIL_STATE,
    ADDRESS_MAIL_ZIP,
    SOURCE,
    PARSE_DATE('%F', SOURCE_DT ) AS SOURCE_DT
FROM `COR_ANALYTICS.STG_COR_MKT_DMC`