SELECT
    SEGMENT_NAME,
    AC_CUSTOMER_ID,
    MEMBER_NUMBER_16_DIGITS,
    FIRST_NAME,
    LAST_NAME,
    ADDRESS,
    ADDRESS_LINE_2,
    CITY,
    STATE,
    POSTCODE,
    SOURCE,
    PARSE_DATE('%F', SOURCE_DT)SOURCE_DT
FROM `COR_ANALYTICS.STG_COR_MKT_DMC_3`