SELECT
    SEGMENT_NAME,
    AC_CUSTOMER_ID,
    SUBSCRIBER_KEY,
    MEMBER_NUMBER_16_DIGITS,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    CAST (JOIN_YEAR AS INT64) JOIN_YEAR,
    GENMF,
    CLUBCODE,
    ZIPCODE,
    ST,
    CAST(AGE AS INT64) AGE,
    PARSE_DATE('%F', SOURCE_DT ) AS SOURCE_DT
FROM `COR_ANALYTICS.STG_COR_EMC_06112017_092114`