-- used to load COR_ANALYTICS.SALESFORCE_DM_2018
SELECT *, 'PHX' AS MARKET, DATE(2018,5,10) AS MAIL_DATE
FROM `COR_ANALYTICS.STG_SALESFORCE_DMC_AUT_MKT_MONTH_CORAZQ2_PHXFINAL` ,
UNNEST(['DM996','DM997','DM998', 'DM998']) PROMO_CODE
UNION ALL
SELECT *, 'TUC' AS MARKET, DATE(2018,5,10) AS MAIL_DATE
FROM `COR_ANALYTICS.STG_SALESFORCE_DMC_AUT_MKT_MONTH_CORAZQ2_TUCFINAL` ,
UNNEST(['DM996','DM997','DM998', 'DM998']) PROMO_CODE
UNION ALL
SELECT MEMBERSHIP_NUMBER AS MEMBER_NUMBER,
FIRST_NAME, LAST_NAME, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, STATE, ZIP, PROMO_CODE,
'PHX' AS MARKET, DATE(2018,2,21) AS MAIL_DATE
FROM `COR_ANALYTICS.STG_SALESFORCE_DMC_CORAZ_FEB2018_PHX_FINAL` ,
UNNEST(['DM993','DM994','DM995', 'DM998']) PROMO_CODE
UNION ALL
SELECT MEMBERSHIP_NUMBER AS MEMBER_NUMBER,
FIRST_NAME, LAST_NAME, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, STATE, ZIP, PROMO_CODE,
'TUC' AS MARKET, DATE(2018,2,21) AS MAIL_DATE
FROM `COR_ANALYTICS.STG_SALESFORCE_DMC_CORAZ_FEB2018_TUC_FINAL` ,
UNNEST(['DM993','DM994','DM995', 'DM998']) PROMO_CODE
UNION ALL
SELECT MEMBER_NUMBER, FIRST_NAME, LAST_NAME, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, STATE, ZIP, PROMO_CODE,
'PHX' AS MARKET, DATE(2018,8,14) AS MAIL_DATE
FROM `COR_ANALYTICS.STG_SALESFORCE_DMC_COR_AZ_Q3_PHX` ,
UNNEST(['DM1005','DM1006','DM1007', 'DM1008']) PROMO_CODE
UNION ALL
SELECT MEMBER_NUMBER, FIRST_NAME, LAST_NAME, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, STATE, ZIP, PROMO_CODE,
'TUC' AS MARKET, DATE(2018,8,14) AS MAIL_DATE
FROM `COR_ANALYTICS.STG_SALESFORCE_DMC_COR_AZ_Q3_TUC` ,
UNNEST(['DM1005','DM1006','DM1007', 'DM1008']) PROMO_CODE
UNION ALL
SELECT MEMBER_NUMBER, FIRST_NAME, LAST_NAME, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, STATE, ZIP, PROMO_CODE,
'PHX' AS MARKET, DATE(2018,10,8) AS MAIL_DATE
FROM `COR_ANALYTICS.STG_SALESFORCE_DMC_AUT_MKT_MONTH_CORAZSep18FirstMailPHXHOG` ,
UNNEST(['DM1009','DM1010','DM1011', 'DM1012']) PROMO_CODE
UNION ALL
SELECT MEMBER_NUMBER, FIRST_NAME, LAST_NAME, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, STATE, ZIP, PROMO_CODE,
'PHX' AS MARKET, DATE(2018,10,8) AS MAIL_DATE
FROM `COR_ANALYTICS.STG_SALESFORCE_DMC_AUT_MKT_MONTH_CORAZSep18FirstMailPHX` ,
UNNEST(['DM1009','DM1010','DM1011', 'DM1012']) PROMO_CODE
UNION ALL
SELECT MEMBER_NUMBER, FIRST_NAME, LAST_NAME, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, STATE, ZIP, PROMO_CODE,
'TUC' AS MARKET, DATE(2018,10,8) AS MAIL_DATE
FROM `COR_ANALYTICS.STG_SALESFORCE_DMC_AUT_MKT_MONTH_CORAZSep18FirstMailTUCHOG` ,
UNNEST(['DM1009','DM1010','DM1011', 'DM1012']) PROMO_CODE
UNION ALL
SELECT MEMBER_NUMBER, FIRST_NAME, LAST_NAME, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, STATE, ZIP, PROMO_CODE,
'TUC' AS MARKET, DATE(2018,10,8) AS MAIL_DATE
FROM `COR_ANALYTICS.STG_SALESFORCE_DMC_AUT_MKT_MONTH_CORAZSep18FirstMailTUC` ,
UNNEST(['DM1009','DM1010','DM1011', 'DM1012']) PROMO_CODE