SELECT DISTINCT
    CUSTOMER_ID,
    MEMBER_NUM,
    MEMBERSHIP_NUM,
    UPPER(FIRST_NM) AS FIRST_NM,
    UPPER(LAST_NM) AS LAST_NM,
    BILLING_STATE,
    RESIDENTIAL_CITY,
    RESIDENTIAL_STATE
FROM COR_ANALYTICS.MEMBERSHIP_CUSTOMER_DIM
WHERE UPPER(ACTIVE_FLG) = 'Y'