--average number of cars per agreement number

SELECT
    AVG(COUNT_CAR)AVG_COUNT_CAR
FROM (
    SELECT
        AGMT_NUM,
        COUNT(DISTINCT VIN) AS COUNT_CAR
    FROM `COR_ANALYTICS.INSURANCE_UNIT_DETAILS_DIM`
-- HAD TO USE THE WHERE CAUSE LOT OF AGREEMENTS NOS DOESN'T HAVE A VIN CORRESPONDING TO IT
    WHERE UPPER(PRODUCT_TYPE) = 'AUTO'
    GROUP BY
        AGMT_NUM
    )