WITH CTE AS (
    SELECT
        CUST_NO,
        LOCATIONNO,
        RO_DATE,
        ROW_NUMBER() OVER(PARTITION BY CUST_NO, LOCATIONNO ORDER BY RO_DATE) AS ROWNUM
    FROM `COR_ANALYTICS.RO_WRITER_HRO`
    )
SELECT
    LOCATIONNO,
    CUST_NO,
    AVG(NOOFDAYS) AVG_TIME_BTW_VISITS,
    MAX(NOOFDAYS) MAX_TIME_BTW_VISITS
FROM (
    SELECT
        R1.LOCATIONNO,
        R1.CUST_NO,
        R1.RO_DATE,
        R1.ROWNUM,
        DATE_DIFF(R1.RO_DATE, R2.RO_DATE, DAY) AS NOOFDAYS  --THIS IS DAYS SINCE LAST VISIT
    FROM CTE R1  --CURRENT ROW
    LEFT JOIN CTE R2 --PREVIOUS VISIT - WILL RESULT IN NULL DAYS FOR 1ST ROW.
    ON
        R1.CUST_NO = R2.CUST_NO
        AND R1.LOCATIONNO = R2.LOCATIONNO
        AND R1.ROWNUM - 1 = R2.ROWNUM
    )
WHERE
    ROWNUM > 1
GROUP BY
    LOCATIONNO,
    CUST_NO
HAVING
    AVG_TIME_BTW_VISITS > 365
--HAVING MAX_TIME_BTW_VISITS > 365