SELECT
    COUNT(DISTINCT CUST_ID ) CUST_COUNT,
    INVOICE_DATE,
    FACILITY
FROM (
    SELECT
        CUST_ID,
        EXTRACT(DATE FROM PARSE_DATETIME('%m/%d/%Y %H:%M', INVOICE_DT)) INVOICE_DATE,
        FACILITY,
        RO_NUM
    FROM `COR_ANALYTICS.WORK_NAPA`
    GROUP BY
        CUST_ID,
        EXTRACT(DATE FROM PARSE_DATETIME('%m/%d/%Y %H:%M', INVOICE_DT)),
        FACILITY,
        RO_NUM
    )
GROUP BY
    INVOICE_DATE,
    FACILITY
ORDER BY
    FACILITY,
    INVOICE_DATE