SELECT DISTINCT
    CUSTOMER_ID,
    DIM.MEMBER_NUM,
    DIM.MEMBERSHIP_NUM,
    UPPER(FIRST_NM) AS FIRST_NM,
    UPPER(LAST_NM) AS LAST_NM,
    BILLING_STATE,
    RESIDENTIAL_CITY,
    RESIDENTIAL_STATE
FROM COR_ANALYTICS.MEMBERSHIP_CUSTOMER_DIM DIM
LEFT OUTER JOIN COR_ANALYTICS.RO_WRITER_CUSTOMER CUST
ON DIM.MEMBER_NUM = CUST.MEMBER_NUM
AND DIM.MEMBERSHIP_NUM = CUST.MEMBERSHIP_NUM
WHERE
    UPPER(BILLING_STATE) IN ('CA', 'AZ')
    AND UPPER(RESIDENTIAL_STATE) IN ('CA', 'AZ')
    AND UPPER(ACTIVE_FLG) = 'Y'