WITH UNIQUE_EVENTS AS (
    SELECT
        CUST_ID,
        FACILITY,
        PARSE_DATETIME('%m/%d/%Y %H:%M',
        INVOICE_DT) INVOICE_DATETIME,
        RO_NUM
    FROM
        `COR_ANALYTICS.WORK_NAPA`
    GROUP BY
        CUST_ID,
        FACILITY,
        INVOICE_DT,
        RO_NUM
    )
SELECT
    AVG(CUST_DIFF) AVG_DURATION_BETWEEN_VISITS
FROM (
    SELECT
    CUST_ID,
    DATETIME_DIFF(INVOICE_DATETIME, INVOICE_DT_2, DAY) CUST_DIFF
    FROM (
        SELECT
            CUST_ID,
            INVOICE_DATETIME,
            LAG(INVOICE_DATETIME) OVER (PARTITION BY CUST_ID ORDER BY INVOICE_DATETIME ASC ) INVOICE_DT_2
        FROM UNIQUE_EVENTS
        )
    WHERE INVOICE_DT_2 IS NOT NULL
    )