SELECT
    FACILITY,
    EXTRACT(MONTH FROM INVOICE_DT) AS MONTH,
    EXTRACT(YEAR FROM INVOICE_DT) AS YEAR,
    COUNT(CUST_ID) AS CAR_COUNT,
    AVG(TOTAL_FL) AS ARO
FROM (
    SELECT
        CUST_ID,
        FIRST_NM,
        LAST_NM,
        FACILITY,
        PARSE_DATETIME('%m/%d/%Y %H:%M', INVOICE_DT) AS INVOICE_DT,
        RO_NUM,
        CAST(TOTAL AS FLOAT64) TOTAL_FL
    FROM `COR_ANALYTICS.WORK_NAPA`
    GROUP BY
        CUST_ID,
        FIRST_NM,
        LAST_NM,
        FACILITY,
        INVOICE_DT,
        RO_NUM,
        TOTAL_FL
    )
GROUP BY
    FACILITY,
    MONTH,
    YEAR
ORDER BY
    FACILITY,
    YEAR,
    MONTH