  --most frequent, at how many cars
SELECT DISTINCT
    MODEL_NM,
    MAKE_NM,
    COUNT(VIN) MOST_FREQ
FROM `COR_ANALYTICS.INSURANCE_UNIT_DETAILS_DIM`
WHERE UPPER(PRODUCT_TYPE) = 'AUTO'
GROUP BY
    MODEL_NM,
    MAKE_NM