SELECT
    CUST.CUSTOMER_MDM_KEY,
    INS.AGMT_NUM,
    INS.PRODUCT_TYPE,
    CUST.POLICY_STATUS
FROM `COR_ANALYTICS.INSURANCE_CUSTOMER_DIM` CUST
INNER JOIN `COR_ANALYTICS.INSURANCE_DIM` INS
ON CUST.AGMT_NUM = INS.AGMT_NUM
WHERE
    UPPER(INS.PRODUCT_TYPE) = 'AUTO'
    AND UPPER(CUST.POLICY_STATUS) = 'A'