WITH CAR_MODEL AS (
    SELECT DISTINCT
        AGRMNT_NUM,
        MEM_NUM,
        MODEL_NM,
        MAKE_NM
    FROM (
        SELECT DISTINCT
            AGMT_NUM AS AGRMNT_NUM,
            MEMBER_NUM AS MEM_NUM
        FROM `COR_ANALYTICS.INSURANCE_CUSTOMER_DIM`
    ) DISTINCT_AGMTS
    INNER JOIN `COR_ANALYTICS.INSURANCE_UNIT_DETAILS_DIM` UNIT
    ON DISTINCT_AGMTS.AGRMNT_NUM = UNIT.AGMT_NUM
),
CUST_VISITS AS (
    SELECT
        CUST_ID,
        MEMBER_NUM,
        COUNT(*) VISITS
    FROM (
        SELECT DISTINCT
            CUST_ID,
            MEMBER_NUM,
            INVOICE_DATETIME
        FROM `COR_ANALYTICS.NAPA_TRACKS`
        WHERE UPPER(FACILITY) = 'BROKAW'
    )
    GROUP BY
        CUST_ID,
        MEMBER_NUM
)
SELECT
    MODEL_NM,
    VISIT_GROUP_COUNT,
    COUNT(MODEL_NM) COUNTS
FROM (
    SELECT DISTINCT
        CUST_VISITS.CUST_ID,
        CUST_VISITS.MEMBER_NUM,
        CAR_MODEL.MODEL_NM,
        CAR_MODEL.MAKE_NM,
        CASE
            WHEN CUST_VISITS.VISITS = 1 THEN '1 VISIT'
            ELSE '>1 VISIT'
            END VISIT_GROUP_COUNT
    FROM CAR_MODEL
    INNER JOIN CUST_VISITS
    ON CAR_MODEL.MEM_NUM = CUST_VISITS.MEMBER_NUM
    WHERE
        CAR_MODEL.MODEL_NM IS NOT NULL
        AND CAR_MODEL.MAKE_NM IS NOT NULL
)
GROUP BY
    MODEL_NM,
    VISIT_GROUP_COUNT
HAVING
    COUNT(MODEL_NM) > 2
ORDER BY
    MODEL_NM,
    VISIT_GROUP_COUNT