DELETE FROM LANDING.WORK_DF_ENGAGE_JOURNEY_HISTORY_0 WHERE TRUE ;
DELETE FROM LANDING.WORK_DF_ENGAGE_JOURNEY_HISTORY_1 WHERE TRUE ;
DELETE FROM LANDING.WORK_DF_ENGAGE_JOURNEY_HISTORY_2 WHERE TRUE ;
DELETE FROM LANDING.WORK_DF_ENGAGE_JOURNEY_HISTORY_3 WHERE TRUE ;
DELETE FROM LANDING.WORK_DF_ENGAGE_JOURNEY_HISTORY_4 WHERE TRUE ;
DELETE FROM LANDING.WORK_DF_ENGAGE_JOURNEY_HISTORY_5 WHERE TRUE ;
DELETE FROM DIGITAL_MARKETING.DIRECT_FOCUS_ENGAGE_JOURNEY_HISTORY WHERE TRUE