-- Query to load COR_ANALYTICS.RO_WRITER_GLBUDGET
SELECT
PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p', PERIODENDDATE) AS PERIOD_END_DATE, 
CAST(LOCATIONNO AS INT64) AS LOCATION_NO,
LOCATION,
BUDGETBALANCE AS BUDGET_BALANCE,
PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p', CREATE_DTTIME) AS CREATE_DTTIME, 
CREATE_BY 
FROM `aaadata-181822.COR_ANALYTICS.STG_GLBUDJECT`