SELECT 
CAST(LOCATIONNO AS INT64) AS LOCATION_NO,
LOCATION AS SHOP_NAME,
ADDRESS,
CITY,
STATE,
ZIP,
PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p', CREATE_DTTIME) AS CREATE_DTTIME, 
CREATE_BY 
FROM `aaadata-181822.COR_RO_WRITER.STG_LOCATION`  L
INNER JOIN `aaadata-181822.COR_RO_WRITER.STG_SHOP_ADDRESSES` A 
ON CAST(L.LOCATIONNO AS INT64) = A.NO