SELECT CAST(LOCATIONNO AS INT64) LOCATION_NO, 
DEPARTMENT,
DEP_NAME DEPT_NAME,
PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p', CREATE_DTTIME) AS CREATE_DTTIME, 
CREATE_BY 
FROM `aaadata-181822.COR_RO_WRITER.STG_DEPARTMENT` 