select CONCAT(RECORD_TYPE,'" "',ACCOUNT_NUMBER,'" "',IFNULL(FIRST_NAME,''),'" "',IFNULL(MIDDLE_NAME,''),'" "',IFNULL(LAST_NAME,''),'" "',IFNULL(ADDRESS_LINE_1,''),'" "',IFNULL(MEMBERSHIP_NO,''),'" "',IFNULL(CITY,''),'" "',IFNULL(STATE,''),'" "',IFNULL(ZIP_CODE,''),'" "',IFNULL(COUNTY,''),'" "',IFNULL(COMP_NAME,''),'" ',IFNULL(FORMAT("%.*f",2,CAST(AMOUNT_DUE AS FLOAT64) + .0001),''),' "',IFNULL(MISC_1,''),'" "',IFNULL(MISC_2,'')) from (
SELECT DISTINCT 
'A' AS RECORD_TYPE,
CONCAT('999999999990','',substr(IFNULL(MEMBER_NUM,''),7,8)) AS ACCOUNT_NUMBER,
UPPER(CUST_DIM.FIRST_NM) AS FIRST_NAME,
UPPER(CUST_DIM.MID_INITIAL_NM) AS  MIDDLE_NAME,
UPPER(CUST_DIM.LAST_NM) AS LAST_NAME,
UPPER(CUST_DIM.BILLING_ADDRESS_LINE1) AS ADDRESS_LINE_1,
MEMBER_NUM AS MEMBERSHIP_NO,
UPPER(BILLING_CITY) AS CITY,
UPPER(BILLING_STATE) AS STATE,
UPPER(BILLING_ZIP) AS ZIP_CODE,
'' AS COUNTY,
'' AS COMP_NAME,
BALANCE_DUE_AMT AS AMOUNT_DUE,
'' AS  MISC_1,
'' AS  MISC_2
FROM CUSTOMERS.CONNECTSUITE_MEMBER   AS CUST_DIM
INNER JOIN OPERATIONAL.CONNECTSUITE_MEMBERSHIP AS MEMBERSHIP_DIM
ON CUST_DIM.MEMBERSHIP_NUM         =MEMBERSHIP_DIM.MEMBERSHIP_NUM
WHERE ASSOCIATE_ID=1
AND MEMBERSHIP_STATUS_CD in ('A','P'))
