MERGE INTO
  OPERATIONAL.CONNECTSUITE_MBRSHIP_BILL TGT
USING
(SELECT 
CAST(BILL_KY AS INT64) AS BILL_KY,
CAST(BILL_STMT_NR AS INT64) AS BILL_STMT_NR,
CAST(BILL_PROC_DT AS DATETIME) AS BILL_PROC_DT,
CAST(BILL_PRNT_DT AS DATETIME) AS BILL_PRNT_DT,
CAST(BILL_AT AS FLOAT64) AS BILL_AT,
CAST(MBRS_KY AS INT64) AS MBRS_KY,
CAST(MBRS_DNR_KY AS INT64) AS MBRS_DNR_KY,
BILL_MRKT_TRK_CD,
BILL_AUTO_REN_IN,
CAST(BILL_CRED_AT AS FLOAT64) AS BILL_CRED_AT,
CAST(BILL_BAL_AT AS FLOAT64) AS BILL_BAL_AT,
BILL_PAYEE_CD,
BILL_REPRT_REQ_IN,
BILL_FST_IN,
BILL_TYP_CD,
EMAILED_IND,
CAST(MBRS_EXPIR_DT AS DATETIME) AS MBRS_EXPIR_DT
FROM LANDING.WORK_CS_MBRSHIP_BILL) STG
ON STG.BILL_KY=TGT.BILL_KY
WHEN MATCHED  THEN  UPDATE   SET
TGT.BILL_KY=STG.BILL_KY,
TGT.BILL_STMT_NR=STG.BILL_STMT_NR,
TGT.BILL_PROC_DT=STG.BILL_PROC_DT,
TGT.BILL_PRNT_DT=STG.BILL_PRNT_DT,
TGT.BILL_AT=STG.BILL_AT,
TGT.MBRS_KY=STG.MBRS_KY,
TGT.MBRS_DNR_KY=STG.MBRS_DNR_KY,
TGT.BILL_MRKT_TRK_CD=STG.BILL_MRKT_TRK_CD,
TGT.BILL_AUTO_REN_IN=STG.BILL_AUTO_REN_IN,
TGT.BILL_CRED_AT=STG.BILL_CRED_AT,
TGT.BILL_BAL_AT=STG.BILL_BAL_AT,
TGT.BILL_PAYEE_CD=STG.BILL_PAYEE_CD,
TGT.BILL_REPRT_REQ_IN=STG.BILL_REPRT_REQ_IN,
TGT.BILL_FST_IN=STG.BILL_FST_IN,
TGT.BILL_TYP_CD=STG.BILL_TYP_CD,
TGT.EMAILED_IND=STG.EMAILED_IND,
TGT.MBRS_EXPIR_DT=STG.MBRS_EXPIR_DT,
TGT.JOB_RUN_ID ='jobrunid', -- Need to change
TGT.LAST_UPDATE_DT=CURRENT_DATETIME()
WHEN NOT MATCHED
  THEN
INSERT(
BILL_KY,
BILL_STMT_NR,
BILL_PROC_DT,
BILL_PRNT_DT,
BILL_AT,
MBRS_KY,
MBRS_DNR_KY,
BILL_MRKT_TRK_CD,
BILL_AUTO_REN_IN,
BILL_CRED_AT,
BILL_BAL_AT,
BILL_PAYEE_CD,
BILL_REPRT_REQ_IN,
BILL_FST_IN,
BILL_TYP_CD,
EMAILED_IND,
MBRS_EXPIR_DT,
JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATE_DT,
LAST_UPDATE_DT
)  
VALUES
(
STG.BILL_KY,
STG.BILL_STMT_NR,
STG.BILL_PROC_DT,
STG.BILL_PRNT_DT,
STG.BILL_AT,
STG.MBRS_KY,
STG.MBRS_DNR_KY,
STG.BILL_MRKT_TRK_CD,
STG.BILL_AUTO_REN_IN,
STG.BILL_CRED_AT,
STG.BILL_BAL_AT,
STG.BILL_PAYEE_CD,
STG.BILL_REPRT_REQ_IN,
STG.BILL_FST_IN,
STG.BILL_TYP_CD,
STG.EMAILED_IND,
STG.MBRS_EXPIR_DT,
'jobrunid',
'CONNECT SUITE',
CURRENT_DATETIME(),
CURRENT_DATETIME()
) 