CREATE OR REPLACE TABLE OPERATIONAL.CONNECTSUITE_MBRSHIP_E_PAYMENT_PROFILE
AS (SELECT
CAST(MBRSHIP_E_PMT_KY AS INT64) AS MBRSHIP_E_PMT_KY,
CAST(MBRS_KY AS INT64) AS MBRS_KY,
CAST(E_PMT_KY AS INT64) AS E_PMT_KY,
CAST(CREATE_DATE AS DATETIME) AS CREATE_DATE,
RENEW_METHOD,
"jobrunid" as JOB_RUN_ID,
'CONNECT SUITE' as SOURCE_SYSTEM_CD,
CURRENT_DATETIME() as CREATE_DT
from
LANDING.WORK_CS_MBRSHIP_E_PAYMENT_PROFILE)

