MERGE INTO OPERATIONAL.CONNECTSUITE_BATCH_REJECT M
USING LANDING.WORK_CS_BATCH_REJECT W
ON M.BATCH_REJECT_KEY=SAFE_CAST(W.BATCH_REJECT_KEY AS INT64)
WHEN NOT MATCHED THEN
INSERT
(
BATCH_REJECT_MEMBERSHIP_ID,
BATCH_REJECT_REASON_TX,
BATCH_REJECT_KEY,
BATCH_KEY,
BATCH_REJECT_AMT,
BATCH_REJECT_CREATE_DTTIME,
MEMBERSHIP_KEY,
BATCH_REJECT_EXTRACT_DT,
MEMBERSHIP_EXPIRE_DT,
BATCH_REJECT_EXTERN_EXTRACT_DT,
E_PAYMENT_BILL_KEY,
ETL_JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATE_DTTIME,
CREATED_BY,
UPDATE_DTTIME
)
VALUES(
BATCH_REJECT_MEMBERSHIP_ID,
BATCH_REJECT_REASON_TX,
SAFE_CAST(BATCH_REJECT_KEY AS INT64),
SAFE_CAST(BATCH_KEY AS INT64),
SAFE_CAST(BATCH_REJECT_AMT AS FLOAT64),
PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S',BATCH_REJECT_CREATE_DT),
SAFE_CAST(MEMBERSHIP_KEY  AS INT64),
PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S',BATCH_REJECT_EXTRACT_DT),
PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S',MEMBERSHIP_EXPIRE_DT),
PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S',BATCH_REJECT_EXTERN_EXTRACT_DT),
SAFE_CAST(E_PAYMENT_BILL_KEY AS INT64),
CAST('jobrunid' AS INT64),
'CONNECT SUITE',
CURRENT_DATETIME(),
'jobname',
CURRENT_DATETIME()
)
WHEN MATCHED THEN 
UPDATE
SET
BATCH_REJECT_MEMBERSHIP_ID = W.BATCH_REJECT_MEMBERSHIP_ID,
BATCH_REJECT_REASON_TX = W.BATCH_REJECT_REASON_TX,
BATCH_KEY = SAFE_CAST(W.BATCH_KEY AS INT64),
BATCH_REJECT_AMT = SAFE_CAST(W.BATCH_REJECT_AMT AS FLOAT64),
BATCH_REJECT_CREATE_DTTIME = PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S',W.BATCH_REJECT_CREATE_DT),
MEMBERSHIP_KEY = SAFE_CAST(W.MEMBERSHIP_KEY  AS INT64),
BATCH_REJECT_EXTRACT_DT = PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S',W.BATCH_REJECT_EXTRACT_DT),
MEMBERSHIP_EXPIRE_DT = PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S',W.MEMBERSHIP_EXPIRE_DT),
BATCH_REJECT_EXTERN_EXTRACT_DT = PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S',W.BATCH_REJECT_EXTERN_EXTRACT_DT),
E_PAYMENT_BILL_KEY = SAFE_CAST(W.E_PAYMENT_BILL_KEY AS INT64),
ETL_JOB_RUN_ID = CAST('jobrunid' AS INT64),
SOURCE_SYSTEM_CD = 'CONNECT SUITE',
CREATED_BY = 'jobname',
UPDATE_DTTIME = CURRENT_DATETIME()