MERGE INTO OPERATIONAL.CONNECTSUITE_MEMBER_SOLICITATION M
USING LANDING.WORK_CS_MEMBER_SOLICITATION W
ON M.MEMBERSHIP_SOLICITATION_KEY =SAFE_CAST(W.MEMBERSHIP_SOLICITATION_KEY AS INT64)
WHEN NOT MATCHED THEN
INSERT
(
MEMBERSHIP_SOLICITATION_KEY,
MEMBER_KEY,
RIDE_KEY,
MEMBERSHIP_SOLICITATION_SRC_SLS_CD,
MEMBERSHIP_SOLICITATION_CD,
MEMBERSHIP_SOLICITATION_ENTER_DTTIME,
ETL_JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATE_DTTIME,
CREATED_BY,
UPDATE_DTTIME
)
VALUES
(
CAST(MEMBERSHIP_SOLICITATION_KEY AS INT64),
CAST(MEMBER_KEY AS INT64),
CAST(RIDE_KEY AS INT64),
MEMBERSHIP_SOLICITATION_SRC_SLS_CD,
MEMBERSHIP_SOLICITATION_CD,
PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S',MEMBERSHIP_SOLICITATION_ENTER_DTTIME),
CAST('jobrunid' AS INT64),
'CONNECT SUITE',
CURRENT_DATETIME(),
'jobname',
CURRENT_DATETIME()
)
WHEN MATCHED THEN 
UPDATE
SET
MEMBER_KEY = CAST(W.MEMBER_KEY AS INT64),
RIDE_KEY = CAST(W.RIDE_KEY AS INT64),
MEMBERSHIP_SOLICITATION_SRC_SLS_CD = W.MEMBERSHIP_SOLICITATION_SRC_SLS_CD,
MEMBERSHIP_SOLICITATION_CD = W.MEMBERSHIP_SOLICITATION_CD,
MEMBERSHIP_SOLICITATION_ENTER_DTTIME = PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S',W.MEMBERSHIP_SOLICITATION_ENTER_DTTIME),
ETL_JOB_RUN_ID = CAST('jobrunid' AS INT64),
SOURCE_SYSTEM_CD = 'CONNECT SUITE',
CREATED_BY = 'jobname',
UPDATE_DTTIME = CURRENT_DATETIME()