 --CONNECTSUITE_MEMBERSHIP_DONOR
 SELECT TRIM(CONVERT(CHAR,MDNR_KY)) AS MEMBERSHIP_DONOR_KEY, 
 TRIM(CONVERT(CHAR,MBRS_KY)) AS MEMBERSHIP_KEY, 
 TRIM(CONVERT(CHAR,DNR_KY)) AS DONOR_KEY, 
 TRIM(CONVERT(CHAR,MDNR_CRD_SHP_CD)) AS MEMBERSHIP_DONOR_CRD_SHP_CD, 
 TRIM(CONVERT(CHAR,MDNR_GFT_MSG_TX)) AS MEMBERSHIP_DONOR_GFT_MSG_TX, 
 TRIM(CONVERT(CHAR,MDNR_INCENT_TYP_CD)) AS MEMBERSHIP_DONOR_INCENT_TYP_CD,
 TRIM(CONVERT(CHAR,MDNR_REN_METH_CD)) AS MEMBERSHIP_DONOR_REN_METH_CD, 
 TRIM(CONVERT(CHAR,MDNR_REN_CD)) AS MEMBERSHIP_DONOR_REN_CD, 
 TRIM(CONVERT(CHAR,MDNR_GFT_TYP_CD)) AS MEMBERSHIP_DONOR_GFT_TYP_CD, 
 TRIM(CONVERT(CHAR,MDNR_GFT_TO)) AS MEMBERSHIP_DONOR_GFT_TO, 
 TRIM(CONVERT(CHAR,MDNR_GFT_FROM)) AS MEMBERSHIP_DONOR_GFT_FROM, 
 TRIM(CONVERT(CHAR,MDNR_INSTRUCTIONS_TX)) AS MEMBERSHIP_DONOR_INSTRUCTIONS_TX,
 TRIM(CONVERT(CHAR,HOLIDAY_GIFT)) AS HOLIDAY_GIFT
FROM
 "v_database_name".dbo.MBRSHIP_DONOR;
