SELECT LTRIM(RTRIM(CONVERT(CHAR, MBRSHIP_E_PMT_KY))) AS MBRSHIP_E_PMT_KY,
LTRIM(RTRIM(CONVERT(CHAR, MBRS_KY))) AS MBRS_KY,
LTRIM(RTRIM(CONVERT(CHAR, E_PMT_KY))) AS E_PMT_KY,
LTRIM(RTRIM(CONVERT(CHAR, CREATE_DATE,121))) AS CREATE_DATE,
LTRIM(RTRIM( RENEW_METHOD)) AS RENEW_METHOD
from [m_prd].[dbo].[mbrship_e_payment_profile]