 SELECT 
 TRIM(CONVERT(CHAR,JRNL_KY)) AS JOURNAL_KEY, 
 TRIM(CONVERT(CHAR,JRNL_POST_DT,121)) AS JOURNAL_POST_DTTIME, 
 TRIM(CONVERT(CHAR,JRNL_PROC_DT,121)) AS JOURNAL_PROC_DTTIME, 
 TRIM(CONVERT(CHAR,JRNL_AT)) AS JOURNAL_AT, 
 TRIM(CONVERT(CHAR,JRNL_DR_CR_IN)) AS JOURNAL_DR_CR_IND, 
 TRIM(CONVERT(CHAR,JRNL_CREAT_DT,121)) AS JOURNAL_CREAT_DT, 
 TRIM(CONVERT(CHAR,JRNL_GL_PROC_IN)) AS JOURNAL_GL_PROC_IND, 
 TRIM(CONVERT(CHAR,MBRS_KY)) AS MEMBERSHIP_KEY, 
 TRIM(CONVERT(CHAR,GLACT_KY)) AS GLACT_KEY, 
 TRIM(CONVERT(CHAR,MPMT_KY)) AS MEMBERSHIP_PAYMENT_KEY, 
 TRIM(CONVERT(CHAR,MCST_KY)) AS MEMBERSHIP_COST_KEY
FROM
 "v_database_name".dbo.JOURNAL_ENTRY
 WHERE CONVERT(date,JRNL_CREAT_DT) >= DATEADD(day,-1,convert(date, 'v_inputdate'))
AND CONVERT(date,JRNL_CREAT_DT) < CONVERT(date,'v_inputdate');
