 --CONNECTSUITE_MEMBER_SOLICITATION
SELECT TRIM(CONVERT(CHAR,MSLCT_KY)) AS MEMBERSHIP_SOLICITATION_KEY, 
TRIM(CONVERT(CHAR,MBR_KY)) AS MEMBER_KEY, 
TRIM(CONVERT(CHAR,RIDE_KY)) AS RIDE_KEY, 
TRIM(CONVERT(CHAR,MSLCT_SRC_SLS_CD)) AS MEMBERSHIP_SOLICITATION_SRC_SLS_CD, 
TRIM(CONVERT(CHAR,MSLCT_SLCT_CD)) AS MEMBERSHIP_SOLICITATION_CD,
TRIM(CONVERT(CHAR,MSLCT_ENTER_DT,121)) AS MEMBERSHIP_SOLICITATION_ENTER_DTTIME
FROM
"v_database_name".dbo.MBR_SOLICITATION
WHERE CONVERT(date,MSLCT_ENTER_DT) >= DATEADD(day,-1,convert(date, 'v_inputdate'))
AND CONVERT(date,MSLCT_ENTER_DT) < CONVERT(date,'v_inputdate');
