SELECT 
TRIM(CONVERT(CHAR,DNR_KY)) AS DONOR_KEY, 
TRIM(CONVERT(CHAR,DNR_CLB_CD)) AS DONOR_CLUB_CD, 
TRIM(CONVERT(CHAR,DNR_CORP_NM)) AS DONOR_CORPORATE_NM, 
TRIM(CONVERT(CHAR,DNR_NM_SLTN_CD)) AS DONOR_NAME_SALUTATION_CD, 
TRIM(CONVERT(CHAR,DNR_FST_NM)) AS DONOR_FIRST_NM, 
TRIM(CONVERT(CHAR,DNR_MID_INIT_NM)) AS DONOR_MIDDLE_INIT_NM, 
TRIM(CONVERT(CHAR,DNR_LST_NM)) AS DONOR_LAST_NM, 
TRIM(CONVERT(CHAR,DNR_NM_SUFX_CD)) AS DONOR_NM_SUFFIX_CD, 
TRIM(CONVERT(CHAR,DNR_ATTN_AD)) AS DONOR_ALTERNATE_ADDRESS, 
TRIM(CONVERT(CHAR,DNR_BSC_AD)) AS DONOR_BASIC_ADDRESS, 
TRIM(CONVERT(CHAR,DNR_SUPL_AD)) AS DONOR_SUPLLEMENT_ADDRESS,
TRIM(CONVERT(CHAR,DNR_CTY_NM)) AS DONOR_CITY_NM,
TRIM(CONVERT(CHAR,DNR_ST_PROV_CD)) AS DONOR_STATE_PROV_CD, 
TRIM(CONVERT(CHAR,DNR_ZIP_CD)) AS DONOR_ZIP_CD, 
TRIM(CONVERT(CHAR,DNR_ADDR_CHG_DT,120)) AS DONOR_ADDRESS_CHANGE_DTTIME, 
TRIM(CONVERT(CHAR,DNR_TEL_NR)) AS DONOR_TEL_NUM, 
TRIM(CONVERT(CHAR,DNR_TYP_CD)) AS DONOR_TYPE_CD, 
TRIM(CONVERT(CHAR,DNR_BILL_TYP_CD)) AS DONOR_BILL_TYPE_CD, 
TRIM(CONVERT(CHAR,DNR_MBRS_KY)) AS DONOR_MEMBERSHIP_KEY, 
TRIM(CONVERT(CHAR,DNR_CREATE_DT,120)) AS DONOR_CREATE_DTTIME, 
TRIM(CONVERT(CHAR,DNR_EXT_NR)) AS DONOR_EXT_NUM, 
TRIM(CONVERT(CHAR,DNR_EMAIL_ADDR)) AS DONOR_EMAIL_ADDRESS, 
TRIM(CONVERT(CHAR,DNR_MBR_KY)) AS DONOR_MEMBER_KEY
FROM
 "v_database_name".dbo.donor
 WHERE CONVERT(date,DNR_CREATE_DT) >= DATEADD(day,-1,convert(date, 'v_inputdate'))
AND CONVERT(date,DNR_CREATE_DT) < CONVERT(date,'v_inputdate');
