 SELECT 
TRIM(CONVERT(CHAR,E_PMT_HIST_KY)) AS E_PAYMENT_HISTORY_KEY, 
 TRIM(CONVERT(CHAR,MPMT_KY)) AS MEMBERSHIP_PAYMENT_KEY, 
  TRIM(CONVERT(CHAR,TYPE_CD)) AS TYPE_CD, 
  TRIM(CONVERT(CHAR,SEQUENCE_NUMBER)) AS SEQUENCE_NUMBER, 
  TRIM(CONVERT(CHAR,ORDER_NUMBER)) AS ORDER_NUMBER,
  TRIM(TRANS_ID) AS TRANSACTION_ID, 
  TRIM(CONVERT(CHAR,REQUEST_ID)) AS REQUEST_ID, 
  TRIM(CONVERT(CHAR,AMOUNT)) AS AMOUNT, 
  TRIM(CONVERT(CHAR,TRANS_RETURN_CD)) AS TRANS_RETURN_CD, 
  TRIM(CONVERT(CHAR(200),TRANS_RETURN_TEXT)) AS TRANS_RETURN_TEXT, 
  TRIM(CONVERT(CHAR,PROCESSED_DATE,121)) AS PROCESSED_DTTIME, 
  TRIM(CONVERT(CHAR,TRANS_REF_NUMBER)) AS TRANS_REF_NUMBER, 
  TRIM(CONVERT(CHAR,MBRS_KY)) AS MBRS_KY, 
  TRIM(CONVERT(CHAR,EXTENDED_RETURN_CD)) AS EXTENDED_RETURN_CD , 
  TRIM(CONVERT(CHAR,REQUEST_DATE,121)) AS REQUEST_DTTIME, 
  TRIM(CONVERT(CHAR,VENDOR_RETURN_CD)) AS VENDOR_RETURN_CD, 
  TRIM(CONVERT(CHAR,RETURN_CD)) AS RETURN_CD, 
  TRIM(CONVERT(CHAR,AUTH_CODE)) AS AUTH_CODE, 
  TRIM(CONVERT(CHAR,BPMT_KY)) AS BPMT_KY, 
  TRIM(CONVERT(CHAR,AVS_FLAG)) AS AVS_FLG, 
  TRIM(CONVERT(CHAR,CVV_FLAG)) AS CVV_FLG,
  TRIM(CONVERT(CHAR,PROCESSOR)) AS PROCESSOR, 
  TRIM(CONVERT(CHAR,ACCOUNT_NUMBER)) AS ACCOUNT_NUMBER, 
  TRIM(CONVERT(CHAR,CC_TYPE_CD)) AS CC_TYPE_CD, 
  TRIM(CONVERT(CHAR,SUCCESS_FLG)) AS SUCCESS_FLG, 
  TRIM(CONVERT(CHAR,E_PMT_METHOD)) AS E_PAYMENT_METHOD, 
  TRIM(CONVERT(CHAR,SOFT_DECLINE)) AS SOFT_DECLINE, 
  TRIM(CONVERT(CHAR,CONTRACT_ID)) AS CONTRACT_ID, 
  TRIM(CONVERT(CHAR,TOKEN)) AS TOKEN
 FROM
 "v_database_name".dbo.E_PAYMENT_HISTORY
 WHERE CONVERT(date,REQUEST_DATE) >= DATEADD(day,-1,convert(date, 'v_inputdate'))
AND CONVERT(date,REQUEST_DATE) < CONVERT(date,'v_inputdate');
