select 
LTRIM(RTRIM(CONVERT(CHAR, E_PMT_KY))) AS E_PMT_KY,
LTRIM(RTRIM( CC_TYPE_CD)) AS CC_TYPE_CD,
LTRIM(RTRIM( ACCOUNT_NUMBER)) AS ACCOUNT_NUMBER,
LTRIM(RTRIM(CONVERT(CHAR, CC_EXPIRE_DATE,121))) AS CC_EXPIRE_DATE,
LTRIM(RTRIM(CONVERT(CHAR, REJECT_DATE,121))) AS REJECT_DATE,
LTRIM(RTRIM( REJECT_REASON_CODE)) AS REJECT_REASON_CODE,
LTRIM(RTRIM( OWNER_INDICATOR)) AS OWNER_INDICATOR,
LTRIM(RTRIM(CONVERT(CHAR, OWNER_KY))) AS OWNER_KY,
LTRIM(RTRIM(CONVERT(CHAR, CANCEL_DATE,121))) AS CANCEL_DATE,
LTRIM(RTRIM(CONVERT(CHAR, ENCRYPTION_KEY_ID))) AS ENCRYPTION_KEY_ID,
LTRIM(RTRIM( CONTRACT_ID)) AS CONTRACT_ID,
LTRIM(RTRIM( E_PMT_METHOD)) AS E_PMT_METHOD,
LTRIM(RTRIM( PRIOR_ACCOUNT_NUMBER)) AS PRIOR_ACCOUNT_NUMBER,
LTRIM(RTRIM( ACCOUNT_UPDATE_RESPONSE_CODE)) AS ACCOUNT_UPDATE_RESPONSE_CODE,
LTRIM(RTRIM(CONVERT(CHAR, ACCOUNT_UPDATE_DATE,121))) AS ACCOUNT_UPDATE_DATE,
LTRIM(RTRIM( CONVERT(CHAR,NEEDS_PRE_AUTH))) AS NEEDS_PRE_AUTH,
LTRIM(RTRIM(CONVERT(CHAR, ACCOUNT_UPDATE_SENT_DATE,121))) AS ACCOUNT_UPDATE_SENT_DATE
from [m_prd].[dbo].[E_PAYMENT_PROFILE]