select 
LTRIM(RTRIM(CONVERT(CHAR, BDTL_KY))) AS BDTL_KY,
LTRIM(RTRIM(CONVERT(CHAR, BDTL_LN_ITM_NR))) AS BDTL_LN_ITM_NR,
LTRIM(RTRIM(CONVERT(CHAR, BDTL_AT))) AS BDTL_AT,
LTRIM(RTRIM( BDTL_SLTN_CD)) AS BDTL_SLTN_CD,
LTRIM(RTRIM( BDTL_CMPT_CD)) AS BDTL_CMPT_CD,
LTRIM(RTRIM(CONVERT(CHAR, mbrship_bill_dtl.BILL_KY))) AS BILL_KY,
LTRIM(RTRIM(CONVERT(CHAR, mbrship_bill_dtl.MBR_KY))) AS MBR_KY,
LTRIM(RTRIM(CONVERT(CHAR, RIDE_KY))) AS RIDE_KY,
LTRIM(RTRIM(CONVERT(CHAR, mbrship_bill_dtl.MBRS_KY))) AS MBRS_KY,
LTRIM(RTRIM(CONVERT(CHAR, BDTL_PD_AT))) AS BDTL_PD_AT,
LTRIM(RTRIM( BDTL_BIL_CAT_CD)) AS BDTL_BIL_CAT_CD
    FROM [m_prd].[dbo].[mbrship_bill],[m_prd].[dbo].[mbrship_bill_dtl]
where mbrship_bill.bill_ky=mbrship_bill_dtl.bill_ky
  and bill_prnt_dt is null