--CONNECTSUITE_MEMBERSHIP_COST
SELECT TRIM(CONVERT(CHAR,MCST_KY ))  AS MEMBERSHIP_COST_KEY, 
TRIM(CONVERT(CHAR,MCST_COMP_CD)) AS MEMBERSHIP_COST_COMP_CD, 
TRIM(CONVERT(CHAR,MCST_AT,120)) AS MEMBERSHIP_COST_AMT, 
TRIM(CONVERT(CHAR,MCST_STS_CD)) AS MEMBERSHIP_COST_STS_CD, 
TRIM(CONVERT(CHAR,MBRS_KY)) AS MEMBERSHIP_KEY, 
TRIM(CONVERT(CHAR,MBR_KY)) AS MEMBER_KEY, 
TRIM(CONVERT(CHAR,RIDE_KY)) AS RIDE_KEY, 
TRIM(CONVERT(CHAR,MCST_COLT_AT)) AS MEMBERSHIP_COST_COLT_AMT, 
TRIM(CONVERT(CHAR,MCST_REFUND_AT)) AS MEMBERSHIP_COST_REFUND_AMT, 
TRIM(CONVERT(CHAR,MCST_EFF_DT,121)) AS MEMBERSHIP_COST_EFF_DTTIME, 
TRIM(CONVERT(CHAR,MCST_CANC_DT,121)) AS MEMBERSHIP_COST_CANC_DTTIME, 
TRIM(CONVERT(CHAR,MCST_REINST_IN)) AS MEMBERSHIP_COST_REINST_IND, 
TRIM(CONVERT(CHAR,MCST_REINST_DT,121)) AS MEMBERSHIP_COST_REINST_DTTIME,
TRIM(CONVERT(CHAR,MCST_PAYEE_CD)) AS MEMBERSHIP_COST_PAYEE_CD, 
TRIM(CONVERT(CHAR,MCST_PRIM_PMT_AT ))AS MEMBERSHIP_COST_PRIM_PMT_AMT, 
TRIM(CONVERT(CHAR,MCST_DNR_PMT_AT)) AS MEMBERSHIP_COST_DNR_PMT_AMT, 
TRIM(CONVERT(CHAR,MCST_PRIM_CRD_AT))AS MEMBERSHIP_COST_PRIM_CRD_AMT, 
TRIM(CONVERT(CHAR,MCST_DNR_CRD_AT)) AS MEMBERSHIP_COST_DNR_CRD_AMT, 
TRIM(CONVERT(CHAR,MCST_PAYBACK_REQ_IN)) AS MEMBERSHIP_COST_PAYBACK_REQ_IND, 
TRIM(CONVERT(CHAR,MCST_ACTV_DT,121)) AS MEMBERSHIP_COST_ACTV_DTTIME, 
TRIM(CONVERT(CHAR,CCST_KY)) AS CCST_KEY, 
TRIM(CONVERT(CHAR,MCST_PRIM_EXCL_CRD_AT)) AS MEMBERSHIP_COST_PRIM_EXCL_CRD_AMT, 
TRIM(CONVERT(CHAR,MCST_DNR_EXCL_CRD_AT)) AS MEMBERSHIP_COST_DNR_EXCL_CRD_AMT
FROM
"v_database_name".dbo.MBRSHIP_COST
WHERE CONVERT(date,MCST_EFF_DT) >= DATEADD(day,-1,convert(date, 'v_inputdate'))
AND CONVERT(date,MCST_EFF_DT) < CONVERT(date,'v_inputdate');
