SELECT 
TRIM(CONVERT(CHAR,BREJ_MBRS_ID)) AS BATCH_REJECT_MEMBERSHIP_ID,
TRIM(CONVERT(CHAR(200),BREJ_RSN_TX)) AS BATCH_REJECT_REASON_TX,
TRIM(CONVERT(CHAR,BREJ_KY)) AS BATCH_REJECT_KEY,
TRIM(CONVERT(CHAR,BTCH_KY)) AS BATCH_KEY,
TRIM(CONVERT(CHAR,BREJ_AT)) AS BATCH_REJECT_AMT,
TRIM(CONVERT(CHAR,BREJ_CREATE_DT,121)) AS BATCH_REJECT_CREATE_DT,
TRIM(CONVERT(CHAR,MBRS_KY)) AS MEMBERSHIP_KEY,
TRIM(CONVERT (CHAR,BREJ_EXTRACT_DT,121)) AS BATCH_REJECT_EXTRACT_DT,
TRIM(CONVERT(CHAR,MBRS_EXPIR_DT,121)) AS MEMBERSHIP_EXPIRE_DT,
TRIM(CONVERT (CHAR,BREJ_EXTERN_EXTRACT_DT,121)) AS BATCH_REJECT_EXTERN_EXTRACT_DT,
TRIM(CONVERT(CHAR,E_PMT_BILL_KY)) AS E_PAYMENT_BILL_KEY
FROM
"v_database_name".dbo.BATCH_REJECT
WHERE CONVERT(date,BREJ_CREATE_DT) >= DATEADD(day,-1,convert(date, 'v_inputdate'))
AND CONVERT(date,BREJ_CREATE_DT) < CONVERT(date,'v_inputdate');
