select 
LTRIM(RTRIM(CONVERT(CHAR, BILL_KY))) AS BILL_KY,
LTRIM(RTRIM(CONVERT(CHAR, BILL_STMT_NR))) AS BILL_STMT_NR,
LTRIM(RTRIM(CONVERT(CHAR, BILL_PROC_DT,121))) AS BILL_PROC_DT,
LTRIM(RTRIM(CONVERT(CHAR, BILL_PRNT_DT,121))) AS BILL_PRNT_DT,
LTRIM(RTRIM(CONVERT(CHAR, BILL_AT))) AS BILL_AT,
LTRIM(RTRIM(CONVERT(CHAR, MBRS_KY))) AS MBRS_KY,
LTRIM(RTRIM(CONVERT(CHAR, MBRS_DNR_KY))) AS MBRS_DNR_KY,
LTRIM(RTRIM( BILL_MRKT_TRK_CD)) AS BILL_MRKT_TRK_CD,
LTRIM(RTRIM( BILL_AUTO_REN_IN)) AS BILL_AUTO_REN_IN,
LTRIM(RTRIM(CONVERT(CHAR, BILL_CRED_AT))) AS BILL_CRED_AT,
LTRIM(RTRIM(CONVERT(CHAR, BILL_BAL_AT))) AS BILL_BAL_AT,
LTRIM(RTRIM( BILL_PAYEE_CD)) AS BILL_PAYEE_CD,
LTRIM(RTRIM( BILL_REPRT_REQ_IN)) AS BILL_REPRT_REQ_IN,
LTRIM(RTRIM( BILL_FST_IN)) AS BILL_FST_IN,
LTRIM(RTRIM( BILL_TYP_CD)) AS BILL_TYP_CD,
LTRIM(RTRIM( EMAILED_IND)) AS EMAILED_IND,
LTRIM(RTRIM(CONVERT(CHAR, MBRS_EXPIR_DT,121))) AS MBRS_EXPIR_DT
from [m_prd].[dbo].[mbrship_bill]
where bill_prnt_dt is null