CREATE OR REPLACE TABLE LANDING.WORK_CTS_COMPLAINT_DIM (
CMPLNT_ID	STRING,
MBR_ID	STRING,
RECEIVED_DT	STRING,
BRANCH_CD	STRING,
CATEGORY_CD	STRING,
CURR_STATUS_CD	STRING,
ORIGIN_CD	STRING,
NARRATIVE	STRING,
ORIG_CLB_CD	STRING,
FIRST_NM	STRING,
LAST_NM	STRING,
BASIC_ADR	STRING,
CITY_NM	STRING,
ST_CD	STRING,
ZIP_CD	STRING,
TELEPHONE_NBR	STRING,
EMAIL_ADR	STRING,
RECV_EMPLE_ID	STRING,
DESCRIPTION_TX	STRING,
ASC_ID	STRING,
CLUB_CD	STRING	 );

CREATE OR REPLACE TABLE LANDING.WORK_CTS_COMPLAINT_HISTORY_DIM (
BRANCH_CD	STRING,
RECEIVED_DT	STRING,
CMPLNT_ID	STRING,
STATUS_CD	STRING,
STATUS_DTIME_DT	STRING,
STATUS_EMPLE_ID	STRING,
STATUS_TX	STRING,
STATUS_SEQ_NBR	STRING);

CREATE OR REPLACE TABLE LANDING.WORK_CTS_INCIDENT_FACT  (
BRANCH_CD	STRING,
RECEIVED_DT	STRING,
CMPLNT_ID	STRING,
INCD_ID	STRING,
KEY_TYPE_CD	STRING,
SC_DT	STRING,
SC_ID	STRING,
INCD_DATE_DT	STRING,
CURR_RTE_EMPLE_ID	STRING,
CURR_STATUS_CD	STRING,
DESCRIPTION_TX	STRING,
PRIORITY_CD	STRING,
PRIORITY_DESCRIPTION	STRING,
COMPLAINT_FLG	STRING,
INCD_CLUB_CD	STRING,
CATEGORY_CD	STRING,
CATEGORY_DESCRIPTION	STRING,
CLOSE_EMPLE_ID	STRING,
DEPT_CD	STRING,
CHARGEBACK_AMT	STRING,
TRUCK_ID	STRING,
DRIVER_ID	STRING,
RSLUTN_CD	STRING,
RSLUTN_DESCRIPTION	STRING,
RSLUTN_AMT	STRING,
AMT_REQUESTED	STRING,
KEY_TYPE_DESC	STRING	
);

CREATE OR REPLACE TABLE LANDING.WORK_CTS_INCIDENT_HISTORY_FACT  (
BRANCH_CD	STRING,
RECEIVED_DT	STRING,
CMPLNT_ID	STRING,
INCD_ID	STRING,
STATUS_CD	STRING,
STATUS_DTIME_DT	STRING,
STATUS_EMPLE_ID	STRING,
STATUS_RSN_CD	STRING,
STATUS_TX	STRING,
STATUS_SEQ_NBR	STRING,
SUSPEND_UNTIL_DATE	STRING	
);

CREATE OR REPLACE TABLE LANDING.WORK_CTS_INCIDENT_ROUTING_LIST_FACT  (
BRANCH_CD	STRING,
RECEIVED_DT	STRING,
CMPLNT_ID	STRING,
INCD_ID	STRING,
RTE_SEQ_NBR	STRING,
RTE_EMPLE_ID	STRING,
IS_GROUP	STRING	
);
