SELECT
  CAST (TASK_ID AS INT64) TASK_ID,
  PART_NO,
  SAFE_CAST (QUANTITY AS int64)QUANTITY,
  CAST (TAXABLE AS int64) AS TAXABLE,
  SUPP_ID,
  PART_ORDER,
  SOURCE_SYSTEM_CD,
  CREATE_BY,
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    CREATE_DTTIME) AS CREATE_DTTIME
FROM
  `aaadata-181822.COR_WINWORKS.STG_PARTS`