SELECT
  CAST(STATUS_NO AS INT64)STATUS_NO,
  STATUS_NAME,
  STATUS_SHORT_NAME,
  RESPONSIBLE,
  CAST(NOTIFY_SERV_ADV AS INT64)NOTIFY_SERV_ADV,
  CAST(NOTIFY_PARTS_LOG AS INT64)NOTIFY_PARTS_LOG,
  CAST(NOTIFY_TECH AS INT64)NOTIFY_TECH,
  CAST(NOTIFY_QAMGR AS INT64)NOTIFY_QA_MANAGER,
  CAST(STATUS_COLOR AS INT64)STATUS_COLOR,
  CREATE_BY,
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    CREATE_DTTIME) AS CREATE_DTTIME,
  SOURCE_SYSTEM_CD
FROM
  `aaadata-181822.COR_WINWORKS.STG_BAY_SETTINGS`