SELECT
  CAST (PROFILETYPE AS INT64)AS PROFILETYPE,
  CAST (SERVICENO AS INT64)AS SERVICE_NUMBER,
  CAST (MILEAGE AS INT64)AS MILEAGE,
  CAST (MONTHS AS INT64)AS MONTHS,
  SINGLEUSE,
  CREATE_BY,
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    CREATE_DTTIME) AS CREATE_DTTIME,
  SOURCE_SYSTEM_CD
FROM
  `aaadata-181822.COR_WINWORKS.STG_PROFILES`