SELECT
  SUPPLIER_NAME,
  SUPP_ID,
  ADDRESS_1,
  ADDRESS_2,
  UPPER(CITY) CITY,
  UPPER(STATE)STATE,
  ZIP,
  PHONE,
  CONTACT,
  FAX,
  COMMENTS,
  ACCT_NO,
  CUST_ID,
  CAST (QB_VEND AS int64)QB_VEND,
  CAST (CONFIG AS int64)CONFIG,
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    CREATE_DTTIME) AS CREATE_DTTIME,
  CREATE_BY,
  SOURCE_SYSTEM_CD
FROM
  `aaadata-181822.COR_WINWORKS.STG_SUPPLIER`