SELECT
  CAST (SUR_ID AS INT64) AS SUR_ID,
  DESCRIPTION,
  CAST (AMOUNT AS FLOAT64) AS AMOUNT,
  CAST (FIXED AS INT64) AS FIXED,
  CAST (LABOR AS INT64) AS LABOR,
  CAST (PARTS AS INT64) AS PARTS,
  CAST (SUBLET AS INT64) AS SUBLET,
  CAST (SURCHARGE AS INT64) AS SURCHARGE,
  CAST (MIN AS FLOAT64) AS MIN,
  CAST (MAX AS FLOAT64) AS MAX,
  ACCTG,
  CAST (TAXABLE AS INT64) AS TAXABLE,
  CAST (WORK_ORDERS AS INT64) AS WORK_ORDERS,
  CAST (COUNTERS AS INT64) AS COUNTERS,
  S_TYPE,
  PARTAPP_L,
  SOURCE_SYSTEM_CD,
  CREATE_BY,
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    CREATE_DTTIME) AS CREATE_DTTIME
FROM
  `aaadata-181822.COR_WINWORKS.STG_SURCHARGES`