SELECT
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    W_DATE) AS W_DATE,
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    PAY_DATE) AS PAY_DATE,
  ORDER_NUMBER,
  CUST_ID,
  CAST (AMOUNT AS FLOAT64)AMOUNT,
  CAST (METHOD AS INT64)METHOD,
  REFERENCE,
  CAST (VOID AS INT64)VOID,
  CAST (PAY_ID AS INT64)PAY_ID,
  CAST (PMT_ID AS INT64) PMT_ID,
  CAST (ALLOCATED AS FLOAT64)ALLOCATED,
  CAST (PREVERBAL AS FLOAT64)PREVERBAL,
  CAST (PAID AS INT64 )PAID,
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    DUEON) AS DUEON,
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    CREATE_DTTIME) AS CREATE_DTTIME,
  CREATE_BY,
  SOURCE_SYSTEM_CD
FROM
  `aaadata-181822.COR_WINWORKS.STG_PAYMENTS`