SELECT
  CAST (TASK_ID AS int64)TASK_ID,
  TASK_DESCRIPTION,
  CAST(SERVICE_NO AS int64)SERVICE_NO,
  DETAILED_DESC,
  CAST(EST_HOURS AS float64)EST_HOURS,
  CAST(RATE AS float64)RATE,
  PART_GROUP,
  CAST(FLAT_RATE AS float64) FLAT_RATE,
  VEND_ID,
  CAST (SPECIFIC AS int64) SPECIFIC,
  SOURCE_SYSTEM_CD,
  CREATE_BY,
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    CREATE_DTTIME) AS CREATE_DTTIME
FROM
  `aaadata-181822.COR_WINWORKS.STG_TASKS`