SELECT
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    W_DATE) AS W_DATE,
  CORE_ID,
  CAST (CORE_NUMBER AS int64 )CORE_NUMBER,
  CORE_DESC AS CORE_DESCRIPTION,
  LOCATION,
  CUST_ID,
  CAST (COST AS float64) COST,
  SUPP_ID,
  ORDER_NUMBER,
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    DATE_SLDINSTL) AS DATE_SLDINSTL,
  SOURCE_SYSTEM_CD,
  CREATE_BY,
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    CREATE_DTTIME) AS CREATE_DTTIME
FROM
  `aaadata-181822.COR_WINWORKS.STG_CORES`