SELECT
  SOURCEID,
  DESCRIPTION,
  CAST(STATUS AS int64) AS STATUS,
  CREATE_BY,
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    CREATE_DTTIME) AS CREATE_DTTIME,
  SOURCE_SYSTEM_CD
FROM
  `aaadata-181822.COR_WINWORKS.STG_SOURCES`