SELECT
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    W_DATE) AS W_DATE,
    AUTO_ID,
    ORDER_NUMBER,
    CAST (WARRANTY AS INT64)WARRANTY,
    CAST (SERVICE_NO AS INT64)SERVICE_NO,
    CAST (SERVICE_MILES AS INT64)SERVICE_MILES,
    CAST (LABOR_CHARGE AS FLOAT64)LABOR_CHARGE,
    CAST (LABOR_COST AS FLOAT64)LABOR_COST,
    CAST (PARTS_CHARGE AS FLOAT64)PARTS_CHARGE,
    CAST (PARTS_COST AS FLOAT64)PARTS_COST,
    CAST (SUBLET_CHARGE AS FLOAT64)SUBLET_CHARGE,
    CAST (SUBLET_COST AS FLOAT64)SUBLET_COST,
    EMPL_ID,
    CAST (ACT_HOURS AS FLOAT64)ACT_HOURS,
    CAST (EST_HOURS AS FLOAT64)EST_HOURS,
    CAST (SPLIT_DETAIL AS INT64)SPLIT_DETAIL,
    DESCRIPTION,
    SUPP_ID,
    SOURCE,
    ADVISOR,
    PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    CREATE_DTTIME) AS CREATE_DTTIME,
    CREATE_BY,
    SOURCE_SYSTEM_CD
FROM
  `aaadata-181822.COR_WINWORKS.STG_SERVICES_MGMT`

  