
SELECT
  AUTOMAKE,
  AUTOMODEL,
        CASE WHEN SAFE_CAST(AUTOYEAR AS INT64) < 20 THEN CAST(CONCAT('20',AUTOYEAR) AS INT64)
        WHEN SAFE_CAST(AUTOYEAR AS INT64) > 20 THEN CAST(CONCAT('19',AUTOYEAR) AS INT64)
        ELSE NULL END AS AUTO_YEAR,
  AUTOENGDISP AS ENGINE_DISPLACEMENT,
  AUTOCYL AS CYLINDER,
  AUTOLICPLATE AS LIC_PLATE,
  AUTOVIN AS VIN,
  CAST(REPLACE(AUTOMILEAGE, ""43,495"", ""43495"") AS INT64)AS MILEAGE,
  --   PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    --     AUTOLASTIN) AS AUTO_LAST_IN,
  -- CAST(AUTOMILEAGE AS FLOAT64) AS MILEAGE,
  AUTOOPTIONS AS AUTO_OPTIONS,
  CUSTID AS CUST_ID,
  AUTOID AS AUTO_ID,
  PROFILETYPE AS PROFILE_TYPE,
  --   PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    --     PRODDATE) AS PROD_DATE,
  NOTES,
  RECOMMENDATIONS,
  CAST(AVEMILEAGE AS FLOAT64) AS AVG_MIL,
  FLEET,
  COLOR,
  STATE,
  FULLRECOM AS FULL_RECOMMENDATION,
  REGID AS REG_ID,
  OPTIONS2 AS OPTIONS_2,
  CREATE_BY,
  SOURCE_SYSTEM_CD
  --   ,
  --   PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    --     CREATE_DTTIME) AS CREATE_DTTIME
FROM
  `aaadata-181822.COR_WINWORKS.STG_AUTOMOBILE`