SELECT
  PHONEDESC AS PHONE_DESCRIPTION,
  PHONENUM AS PHONE_NUMBER,
  CUSTID AS CUST_ID,
  CAST (PHONEORDER AS INT64) PHONE_ORDER,
  SOURCE_SYSTEM_CD,
  CREATE_BY,
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    CREATE_DTTIME) AS CREATE_DTTIME
FROM
  `aaadata-181822.COR_WINWORKS.STG_PHONES`