SELECT
  CAST(DISC_ID AS INT64)DISCOUNT_ID,
  DISC_DESC AS DISCOUNT_DESC,
  DISC_TYPE AS DISCOUNT_TYPE,
  CAST(DISCOUNT AS FLOAT64)DISCOUNT,
  SOURCE_SYSTEM_CD,
  CREATE_BY,
  PARSE_DATETIME('%d-%h-%y %H.%M.%S.000000000 %p',
    CREATE_DTTIME) AS CREATE_DTTIME
FROM
  `aaadata-181822.COR_WINWORKS.STG_DISCOUNT`