WITH 
-- Take only most recent instance of CUSTOMER_KEY from SAM_CUSTOMERS table
SAM_MDM AS
(
SELECT MEMBER_ID, ASSOC_CD, CUSTOMER_KEY from (
    SELECT MEMBER_ID, ASSOC_CD, CUSTOMER_KEY, ROW_NUMBER() OVER (PARTITION BY CUSTOMER_KEY ORDER BY CREATE_DTTIME DESC ) RN
    FROM `aaa-mwg-dwprod.CUSTOMERS.SAM_CUSTOMERS`) SAM
WHERE SAM.RN=1
),
-- Take only most recent instance of CUSTOMER_MDM_KEY from CONNECTSUITE_MEMBER_DIM table
MEM_MDM AS
(
SELECT MEMBERSHIP_NUM, ASSOCIATE_ID, STATUS_CD, CUSTOMER_MDM_KEY FROM (
    SELECT MEMBERSHIP_NUM, ASSOCIATE_ID, STATUS_CD, CUSTOMER_MDM_KEY, ROW_NUMBER() OVER (PARTITION BY CUSTOMER_MDM_KEY ORDER BY EFFECTIVE_START_DT DESC ) RN
    FROM `aaa-mwg-dwprod.CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM`
    WHERE ACTIVE_FLG = 'Y') M
WHERE M.RN=1
),
-- Take all 'QUOTES' records from bridge table
Q_MDM AS
(
SELECT CUSTOMER_MDM_KEY, SOURCE_KEY1
FROM `aaa-mwg-dwprod.CUSTOMERS.MDM_CUSTOMER_BRIDGE`
WHERE SOURCE_SYSTEM = 'QUOTES')

SELECT DISTINCT 
  A.POLICY_NUM,
  A.INITIAL_AGENT_ID,
  A.POLICY_EFFECTIVE_DT,
  A.TRANSACTION_DT,
  A.PRODUCT_CD AS POLICY_TYPE,
  OPP.STATUS_CD AS OPP_STATUS_CD,
  A.CUSTOMER_ID,
  OPP.OPPORTUNITY_ID,
  A. DAY_100_VALID_MEMBER_CHECK,
  A. DAY_1_VALID_MEMBER_CHECK,
  DATE(OPP.OPPORTUNITY_CLOSE_DT) OPPORTUNITY_CLOSE_DT,
  A.AGENT_NM AS AGENT_NAME,
  A.CHECK_DT,
  CASE 
    WHEN TRIM(OPP.STATUS_CD) = 'CL' 
    THEN 'Y' 
    ELSE 'N' 
  END AS CLOSED_OPPORTUNITY_CHECK,
  CASE
    WHEN CONCAT(E.LEGAL_FIRST_NM," ",E.LEGAL_LAST_NM) = A.AGENT_NM -- name match
      OR (CONCAT(E.LEGAL_FIRST_NM," ",E.LEGAL_LAST_NM) != A.AGENT_NM AND DATE_DIFF(CURRENT_DATE(),Q.CREATE_DT,day) > 183 AND A.PRODUCT_TYPE = 'AUTO') -- no name match, AUTO quote create date is older than 183 days
      OR (CONCAT(E.LEGAL_FIRST_NM," ",E.LEGAL_LAST_NM) != A.INITIAL_AGENT_ID AND DATE_DIFF(CURRENT_DATE(),Q.CREATE_DT,day) > 250 AND A.PRODUCT_TYPE = 'HOME') -- no name match, HOME quote create date is older than 250 days
    THEN 'Y'
    ELSE 'N'
  END AS CLOSED_BY_ORIGINAL_AGENT_CHECK,
 A.RATED_MEMBER_FLG AS  VALID_MEMBER_CHECK,
  A.AUTO_BODILY_INJURY_LIMITS/100 BI_LIMITS,
  A.PREMIUM_BEARING_ENDORSEMENTS/100 PREMIUM_BEARING_ENDORSEMENTS,
  A.AUTO_BODILY_INJURY_LIMITS/100 AUTO_BODILY_INJURY_LIMITS,
  A.AUTO_PROPERTY_DAMAGE_LIMITS/100 AUTO_PROPERTY_DAMAGE_LIMITS,
  A.AUTO_UNINSURED_AND_UNDERINSURED_LIMITS/100 AUTO_UNINSURED_AND_UNDERINSURED_LIMITS,
  CASE
    WHEN A.AUTO_MEDPAY_OR_PIP_LIMITS IS NULL THEN 0
    ELSE A.AUTO_MEDPAY_OR_PIP_LIMITS/100
  END AUTO_MEDPAY_OR_PIP_LIMITS,
  A.PRIOR_POLICY_NUM,
  A.VIOLATION_DT,
  A.ANNUAL_MILEAGE_COUNT,
  A.HOME_POLICY_DWELLING_LIMIT,
  A.SELLING_BRANCH_KEY,
  A.SELLING_BRANCH_NM,
  A.SELLING_BRANCH_CITY,
  A.SELLING_BRANCH_STATE,
  A.SALES_CHANNEL,
  Q.QUOTE_NUM,
  A.PRODUCT_TYPE,
  CASE
    WHEN COALESCE(MEM_MDM.MEMBERSHIP_NUM, SAM_MDM.MEMBER_ID ) IS NULL THEN Q.MEMBERSHIP_NUM
    ELSE COALESCE(CONCAT('429005', MEM_MDM.MEMBERSHIP_NUM,CAST(MEM_MDM.ASSOCIATE_ID AS STRING)),
    CONCAT('429005',CAST(SAM_MDM.MEMBER_ID AS STRING),CAST(SAM_MDM.ASSOC_CD AS STRING)))
  END AS MEMBERSHIP_NUM,
  A.REGION,
  FORMAT_DATE("%Y%m%d",A.POLICY_EFFECTIVE_DT) AS NEW_POLICY_EFF_DATE,
  PREMIUM_BEARING_ENDORSEMENTS_FLG,
  A.POLICY_STATUS,
  A.PREMIUM_BEARING_ENDORSEMENTS_FLG_N
FROM `aaa-mwg-dwprod.CUSTOMER_PRODUCT.INSURANCE_QA` A
LEFT OUTER JOIN `aaa-mwg-dwprod.CUSTOMER_PRODUCT.QUOTES_DIM` Q
  ON SUBSTR(Q.POLICY_NUM,5)= A.POLICY_NUM
  AND Q.EFF_END_DT ='9999-12-31'
LEFT OUTER JOIN `aaa-mwg-dwprod.CUSTOMER_PRODUCT.SALES_OPPORTUNITIES` OPP
  ON Q.OPPORTUNITY_ID = OPP.OPPORTUNITY_ID
LEFT OUTER JOIN `aaa-mwg-dwprod.CUSTOMER_PRODUCT.EMPLOYEE_DIM` E
  ON CAST(Q.COMPENSATION_EMPLOYEE_ID AS STRING ) = E.EMPLOYEE_ID
  AND E.ACTIVE_FLG='Y'
LEFT OUTER JOIN `aaa-mwg-dwprod.CUSTOMERS.SAM_CUSTOMERS` C
  ON Q.CUSTOMER_ID=C.CUSTOMER_ID
LEFT OUTER JOIN `aaa-mwg-dwprod.CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM` MQ
  ON MQ.MEMBERSHIP_NUM = SUBSTR(Q.MEMBERSHIP_NUM,7,8)
  AND SAFE_CAST(SUBSTR(Q.MEMBERSHIP_NUM,15,1) AS INT64)= SAFE_CAST(MQ.ASSOCIATE_ID AS INT64)
  AND MQ.ACTIVE_FLG='Y'
LEFT OUTER JOIN Q_MDM 
  ON A.POLICY_NUM= SUBSTR(Q_MDM.SOURCE_KEY1,6)
LEFT OUTER JOIN MEM_MDM
  ON MEM_MDM.CUSTOMER_MDM_KEY = Q_MDM.CUSTOMER_MDM_KEY
LEFT OUTER JOIN SAM_MDM ON SAM_MDM.CUSTOMER_KEY = Q_MDM.CUSTOMER_MDM_KEY
LEFT OUTER JOIN `aaa-mwg-dwprod.CUSTOMER_PRODUCT.CONNECTSUITE_MEMBER_DIM` MEM_SAM
  ON MEM_SAM.MEMBERSHIP_NUM= SAM_MDM.MEMBER_ID
  AND SAFE_CAST(SAM_MDM.ASSOC_CD AS INT64) = MEM_SAM.ASSOCIATE_ID
  AND MEM_SAM.ACTIVE_FLG = 'Y'
WHERE
  EXTRACT(YEAR FROM A.POLICY_EFFECTIVE_DT) >= 2017