
UPDATE  CUSTOMER_PRODUCT.QUOTES_DIM QUOTE
SET QUOTE.ROW_END_DT = TEMP.END_DT
FROM (
SELECT QUOTE_NUM,ROW_START_DT,ROW_END_DT,HASH_VALUE,
CASE WHEN 
LEAD(DATE_SUB(ROW_START_DT, INTERVAL 1 DAY)) OVER (PARTITION BY QUOTE_NUM ORDER BY ROW_START_DT)  IS NULL
THEN 
'9999-12-31'
ELSE
LEAD(DATE_SUB(ROW_START_DT, INTERVAL 1 DAY)) OVER (PARTITION BY QUOTE_NUM ORDER BY ROW_START_DT) END END_DT
FROM 
CUSTOMER_PRODUCT.QUOTES_DIM
ORDER BY 1 ) TEMP
WHERE QUOTE.QUOTE_NUM=TEMP.QUOTE_NUM AND QUOTE.ROW_START_DT=TEMP.ROW_START_DT

  