SELECT POS_BANK_DEPOSIT.TRANSACTION_NUM AS TRANSACTION_NUM,
  FORMAT_DATETIME("%F %X",POS_BANK_DEPOSIT.TRANSACTION_DTTIME) AS TRANSACTION_DTTIME,
  POS_BANK_DEPOSIT.LOCATION_ID            AS STORE_NUM,
  POS_BANK_DEPOSIT.EMPLOYEE_ID          AS EMPLOYEE_ID,
  POS_BANK_DEPOSIT.EMPLOYEE_NM        AS EMPLOYEE_NAME,
  NULL                 AS BANK,
  NULL  AS ACCOUNT,
  POS_BANK_DEPOSIT.BAG_ID               AS BAG_ID,
  POS_BANK_DEPOSIT.TOTAL_AMT         AS TOTAL_AMOUNT,
  POS_BANK_DEPOSIT.CASH_AMT          AS CASH_AMOUNT,
  POS_BANK_DEPOSIT.CHECK_AMT         AS CHECK_AMOUNT,
  FORMAT_DATETIME("%F %X",POS_BANK_DEPOSIT.CREATE_DTTIME) AS CREATE_DTTIME,
  POS_BANK_DEPOSIT.ADJUSTMENT as ADJUSTMENT,
  NULL AS REASON,
  NULL AS ORIGINAL_TRANSACTION_NUM,
  POS_BANK_DEPOSIT.POS_TRANSACTION_ID
  FROM CUSTOMER_PRODUCT.POS_BANK_DEPOSIT_DIM POS_BANK_DEPOSIT
    where CAST(POS_BANK_DEPOSIT.TRANSACTION_DTTIME as date)=DATE_SUB(CURRENT_DATE,INTERVAL 1 DAY)
    --CREATE_DTTIME>'{{ prev_execution_date }}'
