SELECT DISTINCT POS_TENDER_SUMMARY.POS_TRANSACTION_ID AS TRANSACTION_NUM,
 FORMAT_DATETIME("%F %X",POS_TENDER_SUMMARY.TRANSACTION_DTTIME) AS TRANSACTION_DTTIME,
  POS_TENDER_SUMMARY.EMPLOYEE_ID AS STORE_NUM,
  NULL AS REGISTER_NUM,
  POS_TENDER_SUMMARY.EMPLOYEE_ID AS EMPLOYEE_NUM,
  POS_TENDER_SUMMARY.EMPLOYEE_NM AS EMPLOYEE_NAME,
  POS_TENDER_SUMMARY.MEMBER_NUM_15 as MEMBER_NUM,
  TRIM(CM.FIRST_NM) as MEMBER_FIRST_NAME,
  TRIM(CM.LAST_NM) AS MEMBER_LAST_NAME,
  POS_TENDER_SUMMARY.SKU_COMPANY,
  POS_TENDER_SUMMARY.VISA_AMT AS VISA_AMOUNT,
  POS_TENDER_SUMMARY.MASTERCARD_AMT AS MASTERCARD_AMOUNT,
  POS_TENDER_SUMMARY.DEBIT_AMT AS DEBIT_AMOUNT,
  POS_TENDER_SUMMARY.CASH_AMT AS CASH_AMOUNT,
  POS_TENDER_SUMMARY.CHECK_AMT AS CHECK_AMOUNT,
  POS_TENDER_SUMMARY.CHANGE_AMT AS CHANGE_AMOUNT,
  POS_TENDER_SUMMARY.PURCHASE_QUANTITY,
  POS_TENDER_SUMMARY.RETURN_QUANTITY,
  POS_TENDER_SUMMARY.GRAND_TOTAL,
  POS_TENDER_SUMMARY.VOID_TOTAL,
  POS_TENDER_SUMMARY.RETURN_TOTAL,
  POS_TENDER_SUMMARY.TENDER_TOTAL,
  POS_TENDER_SUMMARY.CASH_NET,
  POS_TENDER_SUMMARY.CHECK_NET,
  POS_TENDER_SUMMARY.CC_NET,
  POS_TENDER_SUMMARY.AMEX_AMT AS AMEX_AMOUNT,
  POS_TENDER_SUMMARY.DISCOVER_AMT AS DISCOVER_AMOUNT,
  POS_TENDER_SUMMARY.MISC_AMT AS MISC_AMOUNT,
  POS_TENDER_SUMMARY.MISC_NET
FROM CUSTOMER_PRODUCT.POS_TENDER_SUMMARY_DIM POS_TENDER_SUMMARY
LEFT OUTER JOIN CUSTOMERS.CONNECTSUITE_MEMBER CM ON POS_TENDER_SUMMARY.MEMBER_NUM_15 = SUBSTR(CM.MEMBER_NUM,1,15)
WHERE NOT (LINE_ITEM_VOID_FLAG='Y' OR FULL_TICKET_VOID_FLAG='Y' OR RETURN_FLAG='Y')  
AND POS_TENDER_SUMMARY.PURCHASE_QUANTITY>=0 
AND CAST(TRANSACTION_DTTIME as date)=DATE_SUB(CURRENT_DATE,INTERVAL 1 DAY)
--AND POS_TENDER_SUMMARY.TRANSACTION_DTTIME>'{{ prev_execution_date }}'
