  SELECT POS_TENDER_PICKUP.TRANSACTION_NUM,
    FORMAT_DATETIME("%F %X",POS_TENDER_PICKUP.TRANSACTION_DTTIME) AS TRANSACTION_DTTIME,
    POS_TENDER_PICKUP.LOCATION_ID AS STORE_NUM,
    NULL AS REGISTER_NUM,
    POS_TENDER_PICKUP.EMPLOYEE_ID AS EMPLOYEE_ID,
    POS_TENDER_PICKUP.EMPLOYEE_NM AS EMPLOYEE_NAME,
    POS_TENDER_PICKUP.CASH_AMT AS CASH_AMOUNT,
    POS_TENDER_PICKUP.CHECK_AMT AS CHECK_AMOUNT,
    POS_TENDER_PICKUP.CREDITCARD_AMT AS CREDITCARD_AMOUNT,
    POS_TENDER_PICKUP.ADJUSTMENT AS ADJUSTMENT,
    NULL AS REASON,
    NULL AS ORIGINAL_TRANSACTION_NUM,
    POS_TENDER_PICKUP.POS_TRANSACTION_ID
    FROM CUSTOMER_PRODUCT.POS_TENDER_PICKUP_DIM POS_TENDER_PICKUP
    where  CAST(TRANSACTION_DTTIME as date)=DATE_SUB(CURRENT_DATE,INTERVAL 1 DAY)
    --CREATE_DTTIME>'{{ prev_execution_date }}'
