SELECT DISTINCT FORMAT_DATETIME("%F %X",POS_TRANSACTION_DETAIL.TRANSACTION_DTTIME) AS TRANSACTION_DTTIME,
  POS_TRANSACTION_DETAIL.TRANSACTION_NUM,
  POS_TRANSACTION_DETAIL.POS_TRANSACTION_ID as POS_TRANSACTION_ID,
  POS_TRANSACTION_DETAIL.ITEM_NUM as ITEM_NUM,
  NULL as LINE_ITEM_VOID_ITEM_NUM,
  NULL AS RETURN_TRANSACTION_NUM,
  TRIM(POS_TRANSACTION_DETAIL.LOCATION_ID) as STORE_NUM,
  NULL as REGISTER_NUM,
  TRIM(POS_TRANSACTION_DETAIL.EMPLOYEE_ID) as EMPLOYEE_ID,
  TRIM(POS_TRANSACTION_DETAIL.EMPLOYEE_NM) as EMPLOYEE_NAME,
  NULL as ENTRY_METHOD,
  TRIM(POS_TRANSACTION_DETAIL.ITEM_DESCRIPTION) as ITEM_DESCRIPTION,
  TRIM(POS_TRANSACTION_DETAIL.ITEM_SKU) as ITEM_SKU,
  NULL as JPOINT_ITEM_SKU,
  TRIM(POS_TRANSACTION_DETAIL.SKU_COMPANY) as SKU_COMPANY,
  TRIM(POS_TRANSACTION_DETAIL.ITEM_PASSTHROUGH_DATA) as ITEM_PASSTHROUGH_DATA,
  TRIM(POS_TRANSACTION_DETAIL.ITEM_SPECIAL_ORDER_NUM) as ITEM_SPECIAL_ORDER_NUM,
  TRIM(POS_TRANSACTION_DETAIL.MEMBER_NUM_15) as MEMBER_NUM,
  TRIM(CM.FIRST_NM) as MEMBER_FIRST_NAME,
  TRIM(CM.LAST_NM) AS MEMBER_LAST_NAME,
  POS_TRANSACTION_DETAIL.ITEM_SALE_QUANTITY as ITEM_SALE_QUANTITY,
  POS_TRANSACTION_DETAIL.UNIT_PRICE,
  POS_TRANSACTION_DETAIL.ITEM_TAX_AMT AS ITEM_TAX_AMOUNT,
  POS_TRANSACTION_DETAIL.ITEM_DISCOUNT_AMT AS ITEM_DISCOUNT_AMOUNT,
  POS_TRANSACTION_DETAIL.TOTAL_ITEM_SALES_AMT AS TOTAL_ITEM_SALES_AMOUNT,
  TRIM(POS_TRANSACTION_DETAIL.LINE_ITEM_VOID_FLAG) as LINE_ITEM_VOID_FLAG,
  TRIM(POS_TRANSACTION_DETAIL.FULL_TICKET_VOID_FLAG) as FULL_TICKET_VOID_FLAG,
  TRIM(POS_TRANSACTION_DETAIL.RETURN_FLAG) as RETURN_FLAG  
FROM CUSTOMER_PRODUCT.POS_TRANSACTION_DETAIL_DIM POS_TRANSACTION_DETAIL
LEFT OUTER JOIN CUSTOMERS.CONNECTSUITE_MEMBER CM ON POS_TRANSACTION_DETAIL.MEMBER_NUM_15 = SUBSTR(CM.MEMBER_NUM,1,15)
WHERE not (LINE_ITEM_VOID_FLAG='Y' or FULL_TICKET_VOID_FLAG='Y' or RETURN_FLAG='Y')   
AND CAST(TRANSACTION_DTTIME as date)=DATE_SUB(CURRENT_DATE,INTERVAL 1 DAY)  
--AND POS_TRANSACTION_DETAIL.CREATE_DTTIME>'{{ prev_execution_date }}'
