  --notifications sql query to be put here
SELECT
  *
FROM
  OPERATIONAL.STAGE_MEMBERSHIP_NOTIFICATION
WHERE
  CREATE_DTTIME=(
  SELECT
    MAX(CREATE_DTTIME)
  FROM
    OPERATIONAL.STAGE_MEMBERSHIP_NOTIFICATION);