INSERT INTO CUSTOMER_PRODUCT.GIG_REGISTRATIONS_OVERVIEW(
JOIN_DTTIME ,
CUSTOMER_ID ,
PHONE_NUM ,
FIRST_NM ,
LAST_NM ,
EMAIL ,
MAILING_ADDRESS ,
MAILING_CITY ,
MAILING_STATE ,
LICENSE_ISSUED_STATE ,
BLOCKED_DTTIME ,
MEMBER_NUM ,
BACKGROUND_REPORT_DTTIME ,
BACKGROUND_REPORT_RESULT ,
IS_PHONE_VERIFIED ,
IS_JUMIO_VERIFIED ,
ACCOUNT_STATUS ,
RF_ID ,
CREDITS ,
CREDITS_SOURCE ,
CAN_MEMBER_RESERVE_CAR ,
HAS_VALID_CC ,
JOB_RUN_ID ,
SOURCE_SYSTEM_CD ,
CREATE_DTTIME ,
CREATE_BY )
(SELECT 
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S', Date_Joined ) ,
Customer_ID ,
Phone_Number ,
First_Name ,
Last_Name ,
Email ,
Mailing_Address ,
Mailing_City ,
Mailing_State ,
license_issued_state ,
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S', Blocked_At ) ,
Member_num  ,
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S', Background_Report_DT ) ,
Background_Report_Result ,
Is_Phone_Verified ,
Is_Jumio_Verified ,
Account_Status ,
RFID ,
SAFE_CAST(Credits AS FLOAT64) ,
Credits_Source ,
Can_Member_Reserve_Car ,
Has_Valid_CC ,
"8912",
"GIG",
SAFE_CAST(Created_Date AS DATETIME) ,
Created_By FROM LANDING.gig_customers);

INSERT INTO CUSTOMER_PRODUCT.GIG_DAILY_VEHICLE_HISTORY_REPORT
(TIMESTAMP ,
CREATED_DTTIME ,
VIN ,
LICENSE_PLATE_NUM ,
VEHICLE_MAKE ,
VEHICLE_COLOR ,
VEHICLE_GROUP ,
CAPACITY ,
BIKE_RACK_EQUIPPED ,
LIFT_EQUIPPED ,
IN_FLEET_DTTIME ,
DE_FLEET_DTTIME ,
REGISTRATION_DTTIME ,
INSURANCE_DTTIME ,
POOL ,
FUEL_PERCENTAGE ,
CHARGING_STATE ,
DOOR_STATUS ,
RESERVATION_STATUS ,
UPDATED_DTTIME ,
GPS_TIMESTAMP ,
LAT ,
LONG ,
SERVICE_ID ,
JOB_RUN_ID ,
SOURCE_SYSTEM_CD ,
CREATE_DTTIME ,
CREATE_BY )
(SELECT
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S', timestamp ),
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S+00',created_at),
vin , 
license_plate_number , 
vehicle_make , 
vehicle_color , 
vehicle_group , 
SAFE_CAST ( capacity AS INT64) , 
bike_rack_equipped , 
lift_equipped , 
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S+00',in_fleet_date) , 
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S+00',de_fleet_date) , 
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S+00', registration_date ), 
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S+00', insurance_date ),
pool , 
SAFE_CAST ( fuel_percentage AS FLOAT64) , 
charging_state , 
door_status , 
reservation_status , 
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S+00', updated_at ), 
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S+00', gps_timestamp ), 
SAFE_CAST ( lat AS FLOAT64) , 
SAFE_CAST ( lng AS FLOAT64) , 
SAFE_CAST (SERVICE_ID AS INT64) , 
"8912",
"GIG",
CURRENT_DATETIME() ,
"v_job_name" from LANDING.gig_vehicle_history );


INSERT INTO CUSTOMER_PRODUCT.GIG_DAILY_RENTAL_REPORT(
EVENT_ID ,
RESERVATION_MODE ,
RESERVATION_START_DTTIME ,
BOOKING_START_DTTIME ,
BOOKING_ENDED_DTTIME ,
CANCELLED_DTTIME ,
CANCELLATION_REASON ,
DRIVE_TM ,
PARKED_TM ,
TOTAL_TO_CHARGE ,
MILEAGE_DRIVEN ,
START_LOCATION_DISPLAY ,
START_LOCATION_LAT ,
START_LOCATION_LONG ,
START_LOCATION_ADDRESS ,
END_LOCATION_DISPLAY ,
END_LOCATION_LAT ,
END_LOCATION_LONG ,
END_LOCATION_ADDRESS ,
FIRST_NM ,
LAST_NM ,
EMAIL ,
RECEIPT_ID ,
DRIVE_FARE ,
PARKED_FARE ,
ADDITIONAL_MILEAGE_CHARGE ,
SHARED_ASSET_FEE ,
CREDITS_USED ,
TRANSACTION_FEE ,
BLOCK_DISCOUNT_AMT ,
BLOCKS ,
DEBITED_DTTIME ,
DEBIT_FAILED_DTTIME ,
REFUNDED ,
STRIPE_ID ,
REFUND_REASON ,
EXEMPT ,
MEMBERSHIP_DISCOUNT ,
TOTAL_TAX ,
STATE_TAX_NM ,
STATE_TAX_AMT ,
COUNTY_TAX_NM ,
COUNTY_TAX_AMT ,
DISTRICT_TAX_NM ,
DISTRICT_TAX_AMT ,
VIN ,
VEHICLE_MAKE ,
VEHICLE_NM ,
VEHICLE_LICENSE_PLATE ,
SERVICE_ID ,
JOB_RUN_ID ,
SOURCE_SYSTEM_CD ,
CREATE_DTTIME ,
CREATE_BY 
)
(SELECT
SAFE_CAST(Event_ID AS INT64) ,
Reservation_Mode ,
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S', Reservation_Start_Time ),
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S', Booking_Start_Time ),
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S', Booking_Ended_At ),
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S', Cancelled_At ),
Cancellation_Reason ,
Drive_Time ,
Parked_Time ,
SAFE_CAST(Total_to_Charge AS FLOAT64),
SAFE_CAST(Mileage_Driven AS FLOAT64),
Start_Location_Display ,
SAFE_CAST(Start_Location_Lat AS FLOAT64),
SAFE_CAST(Start_Location_Lng AS FLOAT64),
Start_Location_Address ,
End_Location_Display ,
SAFE_CAST(End_Location_Lat AS FLOAT64),
SAFE_CAST(End_Location_Lng AS FLOAT64),
End_Location_Address ,
First_Name ,
Last_Name ,
Email ,
SAFE_CAST(Receipt_ID AS INT64),
SAFE_CAST(Drive_Fare AS FLOAT64),
SAFE_CAST(Parked_Fare AS FLOAT64),
SAFE_CAST(Additional_Mileage_Charge AS FLOAT64),
SAFE_CAST(Shared_Asset_Fee AS FLOAT64),
SAFE_CAST(Credits_Used AS FLOAT64),
SAFE_CAST(Transaction_fee AS FLOAT64),
SAFE_CAST(Block_Discount_Amount AS FLOAT64),
SAFE_CAST(Blocks AS FLOAT64),
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S+00:00', Debited_At ) AS D_At,
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S+00:00', Debit_Failed_At ) AS D_F_At,
SAFE_CAST(Refunded AS FLOAT64),
Stripe_ID ,
Refund_Reason ,
Exempt ,
Membership_Discount,
Total_Tax,
State_Tax_Name ,
SAFE_CAST(State_Tax_Amount AS FLOAT64),
County_Tax_Name ,
SAFE_CAST(County_Tax_Amount AS FLOAT64),
District_Tax_Name ,
SAFE_CAST(District_Tax_Amount AS FLOAT64),
VIN ,
Vehicle_Make ,
Vehicle_Name ,
Vehicle_License_Plate ,
SAFE_CAST(SERVICE_ID AS INT64),
"8912",
"GIG",
SAFE_CAST(Created_Date AS DATETIME),
Created_By 
FROM LANDING.gig_rentals);


INSERT INTO CUSTOMER_PRODUCT.GIG_DAILY_RENTAL_RATING(
CREATED_DTTIME ,
EVENT_ID ,
LICENSE_PLATE_NUM ,
REPORTED_BY ,
RATING ,
RATING_REASON ,
COMMENT ,
SERVICE_ID ,
JOB_RUN_ID ,
SOURCE_SYSTEM_CD ,
CREATE_DTTIME ,
CREATE_BY )
(SELECT 
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S', Created_At ),
SAFE_CAST(Event_ID AS INT64),
License_Plate_Number ,
Reported_By ,
SAFE_CAST(Rating AS FLOAT64),
Rating_Reason ,
Comment ,
SAFE_CAST(SERVICE_ID AS INT64),
"8912",
"GIG",
CURRENT_DATETIME(),
"v_job_name" FROM LANDING.gig_rental_rating);

INSERT INTO CUSTOMER_PRODUCT.GIG_APPOPEN_RESERVATION_BOOKING (
APPOPEN_DT ,
TOTAL_APPOPEN_COUNT ,
REGISTERED_USER_APPOPEN_COUNT ,
RESERVATION_COUNT ,
BOOKING_COUNT ,
JOB_RUN_ID ,
SOURCE_SYSTEM_CD ,
CREATE_DTTIME ,
CREATE_BY )
(SELECT 
appopen_date ,
total_appopen_count ,
registered_user_appopen_count ,
reservation_count ,
booking_count ,
"8912",
"GIG",
CURRENT_DATETIME(),
"v_job_name" FROM LANDING.gig_app_events_summary);

INSERT INTO CUSTOMER_PRODUCT.GIG_DAILY_DAMAGE_REPORT  (
ID ,
CREATED_DTTIME ,
UPDATED_DTTIME ,
DAMAGE_LOCATION ,
DAMAGE_TYPE ,
VEHICLE_MAKE ,
VEHICLE_COLOR ,
LICENSE_PLATE_NUM ,
VIN ,
REPORTED_BY ,
PHONE_NUM ,
SERVICE_ID ,
JOB_RUN_ID ,
SOURCE_SYSTEM_CD ,
CREATE_DTTIME ,
CREATE_BY )
(SELECT 
SAFE_CAST(ID AS INT64) ,
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S', Created_At ) ,
SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%E*S', Updated_At ),
Damage_Location ,
Damage_Type ,
Vehicle_Make ,
Vehicle_Color ,
License_Plate_Number ,
VIN ,
Reported_By ,
Phone_Number ,
SAFE_CAST(SERVICE_ID AS INT64),
"8912",
"GIG",
CURRENT_DATETIME(),
"v_job_name"
FROM LANDING.gig_vehicle_damage);

INSERT INTO CUSTOMER_PRODUCT.GIG_EVENTS
(SRC_CREATED_DTTIME ,
SITE_NM ,
SITE_ID ,
PUBLISHER_NM ,
PUBLISHER_ID ,
SITE_EVENT_NM ,
SITE_EVENT_ID ,
STATUS ,
IS_RE_ENGAGEMENT ,
GOOGLE_AID ,
IOS_IFA ,
TEST_PROFILE_NM ,
TEST_PROFILE_ID ,
INSTALL_PUBLISHER_NM ,
INSTALL_PUBLISHER_ID ,
ATTRIBUTE_SUB1 ,
ATTRIBUTE_SUB2 ,
ATTRIBUTE_SUB3 ,
ATTRIBUTE_SUB4 ,
ATTRIBUTE_SUB5 ,
LAT ,
LONG ,
TRACKING_ID ,
DEVICE_BRAND ,
DEVICE_CARRIER ,
DEVICE_MODEL ,
CAMPAIGN_URL ,
CAMPAIGN_URL_ID ,
AGENCY_NM ,
AGENCY_ID ,
MATCH_TYPE ,
CAMPAIGN_NM ,
CAMPAIGN_ID ,
EVENT_TYPE ,
POSTAL_CD ,
REGION_NM ,
REGION_ID ,
TRANSACTION_ID ,
APP_NM ,
APP_VERSION ,
USER_ID ,
PUBLISHER_SUB_AD_NM ,
PUBLISHER_SUB_AD_ID ,
PUBLISHER_SUB_AD_REF ,
PUBLISHER_SUB_ADGROUP_NM ,
PUBLISHER_SUB_ADGROUP_ID ,
PUBLISHER_SUB_ADGROUP_REF ,
PUBLISHER_SUB_CAMPAIGN_NM ,
PUBLISHER_SUB_CAMPAIGN_ID ,
PUBLISHER_SUB_CAMPAIGN_REF ,
PUBLISHER_SUB_SITE_NM ,
PUBLISHER_SUB_SITE_ID ,
PUBLISHER_SUB_SITE_REF ,
JOB_RUN_ID ,
SOURCE_SYSTEM_CD ,
CREATE_DTTIME ,
CREATE_BY )
(SELECT 
 CASE WHEN SUBSTR (created,20,22) = "-08:00"
 THEN DATETIME_SUB(CAST(SUBSTR (created,0,19) AS DATETIME), INTERVAL 8 HOUR)
 WHEN SUBSTR (created,20,22) = "-07:00"
 THEN DATETIME_SUB(CAST(SUBSTR (created,0,19) AS DATETIME), INTERVAL 7 HOUR) ELSE NULL END ,
 --CAST(SUBSTR (created,0,19) AS DATETIME),
site_name ,
site_id ,
publisher_name ,
publisher_id ,
site_event_name ,
site_event_id ,
status ,
SAFE_CAST(is_reengagement AS STRING),
google_aid ,
ios_ifa ,
test_profile_name ,
test_profile_id ,
install_publisher_name ,
install_publisher_id ,
SAFE_CAST(attribute_sub1 AS STRING),
attribute_sub2 ,
SAFE_CAST(attribute_sub3 AS STRING),
attribute_sub4 ,
attribute_sub5 ,
latitude ,
longitude ,
tracking_id ,
device_brand ,
device_carrier ,
device_model ,
campaign_url_url ,
campaign_url_id ,
agency_name ,
agency_id ,
match_type ,
campaign_name ,
campaign_id ,
event_type ,
SAFE_CAST(postal_code AS INT64),
region_name ,
region_id ,
transaction_id ,
app_name ,
SAFE_CAST(app_version AS STRING),
SAFE_CAST(user_id AS STRING),
SAFE_CAST(publisher_sub_ad_name AS STRING),
publisher_sub_ad_id ,
SAFE_CAST(publisher_sub_ad_ref AS STRING),
SAFE_CAST(publisher_sub_adgroup_name AS STRING),
publisher_sub_adgroup_id ,
SAFE_CAST(publisher_sub_adgroup_ref AS STRING),
publisher_sub_campaign_name ,
publisher_sub_campaign_id ,
SAFE_CAST(publisher_sub_campaign_ref AS STRING),
publisher_sub_site_name ,
publisher_sub_site_id ,
publisher_sub_site_ref ,
"8912",
"GIG",
CURRENT_DATETIME(),
"v_job_name" FROM LANDING.gig_tune_events);