SELECT
LTRIM(RTRIM(CONVERT(CHAR,[AC Customer ID],120))) AS AC_CUSTOMER_ID ,
LTRIM(RTRIM(CONVERT(CHAR,HubJourneyHistoryId,120 ))) AS HUB_JOURNEY_HISTORY_ID ,
LTRIM(RTRIM(CAST(HubCIDGuid AS VARCHAR(36)))) AS HUB_CIDG_UID ,
LTRIM(RTRIM(CONVERT(CHAR,[Journey Code],120 ))) AS JOURNEY_CD ,
LTRIM(RTRIM(CONVERT(CHAR,[Journey Description],120 ))) AS JOURNEY_DESC ,
LTRIM(RTRIM(CONVERT(CHAR,[JourneyEnd DateTime],120 ))) AS JOURNEY_END_DTTIME ,
LTRIM(RTRIM(CAST(JourneyId AS VARCHAR(36)))) AS JOURNEY_ID ,
LTRIM(RTRIM(CONVERT(CHAR,[Journey Iteration],120 ))) AS JOURNEY_ITERATION ,
LTRIM(RTRIM(CONVERT(CHAR,[Journey Name],120 ))) AS JOURNEY_NM ,
LTRIM(RTRIM(CONVERT(CHAR,[JourneyStart DateTime],120 ))) AS JOURNEY_START_DTTIME ,
LTRIM(RTRIM(CONVERT(CHAR,[Node DateTime],120 ))) AS NODE_DTTIME ,
LTRIM(RTRIM(CONVERT(CHAR,[Node Name],120 ))) AS NODE_NM ,
LTRIM(RTRIM(CONVERT(CHAR,[Node Type],120 ))) AS NODE_TYPE ,
LTRIM(RTRIM(CONVERT(CHAR,[Node Category],120 ))) AS NODE_CATEGORY ,
LTRIM(RTRIM(CONVERT(CHAR,ARCHDATE,120 ))) AS ARCHIVE_DTTIME
FROM DF_NCNU_CLUB.dbo.Engage_Journey_History 
WHERE CONVERT(date,ARCHDATE)>= CONVERT(date,GETDATE() - v_incr_date)
AND CONVERT(date,ARCHDATE)<CONVERT(date,GETDATE())
ORDER BY ARCHDATE;