INSERT INTO OPERATIONAL.QUALTRICS_SURVEY_RESPONSE_COR(
                                
START_DT                        ,
END_DT                          ,
STATUS                          ,
IP_ADDRESS                      ,
PROGRESS                        ,
DURATION                        ,
FINISHED                        ,
RECORDED_DT                     ,
RESPONSE_ID                     ,
RECIPIENT_LAST_NM               ,
RECIPIENT_FIRST_NM              ,
RECIPIENT_EMAIL                 ,
EXTERNAL_REFERENCE              ,
LOCATION_LAT                    ,
LOCATION_LNG                    ,
DISTRIBUTION_CHANNEL            ,
USER_LANGUAGE                   ,
Q1                              ,
Q2                              ,
Q3                              ,
Q4                              ,
Q5                              ,
Q6                              ,
Q7_NPS_GROUP                    ,
Q7                              ,
Q8_NPS_GROUP                    ,
Q8                              ,
Q9                              ,
Q10                             ,
Q11                             ,
CLUB                            ,
FAC                             ,
FIRST_NM                        ,
LAST_NM                         ,
ADDRESS_1                       ,
ADDRESS_2                       ,
CITY                            ,
STATE                           ,
ZIP_CD                          ,
EMAIL                           ,
TRAN_DT                         ,
TRAN_ID                         ,
INV_NUM                         ,
MEM_NUM                         ,
CLUB_OPT1                       ,
CLUB_OPT2                       ,
CLUB_OPT3                       ,
CLUB_OPT4                       ,
CLUB_OPT5                       ,
CLUB_OPT6                       ,
CLUB_OPT7                       ,
CLUB_OPT8                       ,
CLUB_OPT9                       ,
CLUB_OPT10                      ,
AGE                             ,
GENDER                          ,
CELL                            ,
TEXT_CONSENT                    ,
PROGRAM                         ,
Q_TRAN_DT                       ,
INVITE_TRAN_DT                  ,
TRANS_MONTH                     ,
TRANS_YEAR                      ,
Q_URL                           ,
WEIGHTED_SEGMENT                ,
DIRECTIONAL_ERROR               ,
AGE_GROUP
)
SELECT 
SAFE_CAST(START_DT    AS TIMESTAMP)                    ,
SAFE_CAST(END_DT      AS TIMESTAMP)                      ,
SAFE_CAST(STATUS  AS INT64)                        ,
IP_ADDRESS                      ,
SAFE_CAST(PROGRESS       AS INT64)                  ,
SAFE_CAST(DURATION                   AS INT64)      ,
SAFE_CAST(FINISHED   AS INT64)                      ,
SAFE_CAST(RECORDED_DT AS TIMESTAMP)                     ,
RESPONSE_ID                     ,
RECIPIENT_LAST_NM               ,
RECIPIENT_FIRST_NM              ,
RECIPIENT_EMAIL                 ,
EXTERNAL_REFERENCE              ,
SAFE_CAST(LOCATION_LAT   AS FLOAT64)                  ,
SAFE_CAST(LOCATION_LNG    AS FLOAT64)                ,
DISTRIBUTION_CHANNEL            ,
USER_LANGUAGE                   ,
SAFE_CAST(Q1  AS INT64)                             ,
SAFE_CAST(Q2 AS INT64)                              ,
SAFE_CAST(Q3             AS INT64)                  ,
SAFE_CAST(Q4                         AS INT64)      ,
SAFE_CAST(Q5             AS INT64)                  ,
SAFE_CAST(Q6       AS INT64)                        ,
SAFE_CAST(Q7_NPS_GROUP AS INT64)                    ,
SAFE_CAST(Q7 AS INT64)                              ,
SAFE_CAST(Q8_NPS_GROUP   AS INT64)                  ,
SAFE_CAST(Q8  AS INT64)                             ,
Q9                              ,
SAFE_CAST(Q10  AS INT64)                            ,
SAFE_CAST(Q11  AS INT64)                            ,
SAFE_CAST(CLUB  AS INT64)                           ,
FAC                             ,
FIRST_NM                        ,
LAST_NM                         ,
ADDRESS_1                       ,
ADDRESS_2                       ,
CITY                            ,
STATE                           ,
ZIP_CD                          ,
EMAIL                           ,
SAFE_CAST(TRAN_DT  AS INT64)                        ,
SAFE_CAST(TRAN_ID AS INT64)                         ,
SAFE_CAST(INV_NUM  AS INT64)                        ,
MEM_NUM                         ,
CLUB_OPT1                       ,
CLUB_OPT2                       ,
CLUB_OPT3                       ,
CLUB_OPT4                       ,
CLUB_OPT5                       ,
CLUB_OPT6                       ,
CLUB_OPT7                       ,
CLUB_OPT8                       ,
CLUB_OPT9                       ,
CLUB_OPT10                      ,
AGE                             ,
GENDER                          ,
SAFE_CAST(CELL AS FLOAT64)                            ,
TEXT_CONSENT                    ,
PROGRAM                         ,
SAFE_CAST(Q_TRAN_DT AS DATE)                      ,
SAFE_CAST(INVITE_TRAN_DT AS DATE)                 ,
SAFE_CAST(TRANS_MONTH   AS INT64)                   ,
SAFE_CAST(TRANS_YEAR   AS INT64)                    ,
Q_URL                           ,
WEIGHTED_SEGMENT                ,
DIRECTIONAL_ERROR               ,
AGE_GROUP
FROM LANDING.WORK_SURVEY_COR