-- STEP0: starting load of `CUSTOMER.MDM_WORK_QUOTES_STG`
INSERT INTO `CUSTOMERS.MDM_WORK_QUOTES_STG`
(QUOTE_NUM,
FIRST_NAME,
MIDDLE_NAME,
LAST_NAME,
SUFFIX,
PRIMARY_ADDRESS_LINE1,
PRIMARY_ADDRESS_LINE2,
PRIMARY_CITY,
PRIMARY_STATE,
PRIMARY_ZIP,
HOME_TELEPHONE_NUM,
BUSINESS_TELEPHONE_NUM,
ADDRESS_EFFECTIVE_DT,
PRIMARY_EMAIL_ADDRESS,
QUOTES_ADDRESS_LINE1,
QUOTES_ADDRESS_LINE2,
QUOTES_CITY,
QUOTES_STATE,
QUOTES_ZIP,
QUOTES_HOME_TELEPHONE_NUM,
QUOTES_BUSINESS_TELEPHONE_NUM,
QUOTES_CREATE_DATE
)
SELECT
UPPER(QUOTE_NUM) AS QUOTE_NUM,
UPPER(FIRST_NM) AS FIRST_NAME,
UPPER(MIDDLE_NM) AS MIDDLE_NAME,
UPPER(LAST_NM) AS LAST_NAME,
UPPER(SUFFIX) AS SUFFIX,
UPPER(ADDRESS1) AS PRIMARY_ADDRESS_LINE1,
UPPER(ADDRESS2) AS PRIMARY_ADDRESS_LINE2,
UPPER(CITY) AS PRIMARY_CITY,
UPPER(STATE) AS PRIMARY_STATE,
UPPER(ZIP) AS PRIMARY_ZIP,
UPPER(HOME_PHONE) AS HOME_TELEPHONE_NUM,
UPPER(BUSINESS_PHONE) AS BUSINESS_TELEPHONE_NUM,
CAST(NULL AS DATE)  AS ADDRESS_EFFECTIVE_DT,
UPPER(EMAIL) AS PRIMARY_EMAIL_ADDRESS,
CAST(ADDRESS1 AS STRING) AS QUOTES_ADDRESS_LINE1,
CAST(ADDRESS2 AS STRING) AS QUOTES_ADDRESS_LINE2,
CAST(CITY AS STRING) AS QUOTES_CITY,
CAST(STATE AS STRING) AS QUOTES_STATE,
CAST(ZIP AS STRING) AS QUOTES_ZIP,
CAST(HOME_PHONE AS STRING) AS QUOTES_HOME_TELEPHONE_NUM,
CAST(BUSINESS_PHONE AS STRING) AS QUOTES_BUSINESS_TELEPHONE_NUM,
CURRENT_DATE() AS QUOTES_CREATE_DATE
FROM (
SELECT * FROM (
SELECT *, ROW_NUMBER() OVER (PARTITION BY QUOTE_NUM ORDER BY PARSE_DATE('%m/%d/%Y',UPDATE_DT) DESC ) RN FROM  LANDING.WORK_PAS_QUOTES
) Q
WHERE Q.RN=1 );

--STEP0: finished load of CUSTOMERS.MDM_WORK_QUOTES_STG
--STEP0: record count in CUSTOMERS.MDM_WORK_QUOTES_STG is
--select count(0) from `CUSTOMER.MDM_WORK_QUOTES_STG`;
