SELECT
 LTRIM(RTRIM(CONVERT(CHAR,SubscriberKey,120))) AS SUBSCRIBER_KEY,
 LTRIM(RTRIM(CONVERT(CHAR,FirstName,120))) AS FIRST_NM,
 LTRIM(RTRIM(CONVERT(CHAR,LastName,120))) AS LAST_NM,
 LTRIM(RTRIM(CONVERT(CHAR,EmailAddress,120))) AS EMAIL_ADDRESS,
 LTRIM(RTRIM(CONVERT(CHAR,MemberID,120))) AS MEMBER_ID,
 LTRIM(RTRIM(CONVERT(CHAR,AAAMemberID,120))) AS AAA_MEMBER_ID,
 LTRIM(RTRIM(CONVERT(CHAR,StateCode,120))) AS STATE_CD,
 LTRIM(RTRIM(CONVERT(CHAR,ZipCode,120))) AS ZIP_CD,
 LTRIM(RTRIM(CONVERT(CHAR,Zip4,120))) AS ZIP4,
 LTRIM(RTRIM(CONVERT(CHAR,SubscriberID,120))) AS SUBSCRIBER_ID,
 LTRIM(RTRIM(CONVERT(CHAR,RECNO,120))) AS REC_NUM,
 LTRIM(RTRIM(CONVERT(CHAR,ARCH_DATE,120))) AS ARCH_DT,
 LTRIM(RTRIM(CONVERT(CHAR,AAA_eTraveler,120))) AS AAA_ETRAVELER,
 LTRIM(RTRIM(CONVERT(CHAR,Emergency_and_Safety_Preparedness,120))) AS EMERGENCY_AND_SAFETY_PREPAREDNESS,
 LTRIM(RTRIM(CONVERT(CHAR,Featured_Travel_Offers,120))) AS FEATURED_TRAVEL_OFFERS,
 LTRIM(RTRIM(CONVERT(CHAR,Insurance_Offers,120))) AS INSURANCE_OFFERS,
 LTRIM(RTRIM(CONVERT(CHAR,Local_Branch_Events,120))) AS LOCAL_BRANCH_EVENTS,
 LTRIM(RTRIM(CONVERT(CHAR,Member_Discounts_and_Benefits,120))) AS MEMBER_DISCOUNTS_AND_BENEFITS,
 LTRIM(RTRIM(CONVERT(CHAR,Via,120))) AS VIA,
 LTRIM(RTRIM(CONVERT(CHAR,CID,120))) AS CID,
 LTRIM(RTRIM(CONVERT(CHAR,MultipleMember,120))) AS MULTIPLE_MEMBER,
 LTRIM(RTRIM(CONVERT(CHAR,EmailAddress_Lower,120))) AS EMAIL_ADDRESS_LOWER
FROM
 DF_NCNU_CLUB.dbo.ET_SubscriberAttr
WHERE LTRIM(RTRIM(CONVERT(date,ARCH_DATE))) >= 'v_incr_date'