INSERT INTO
  LANDING.DWH_SOURCE_TO_TARGET_AUDIT ( SOURCE_COUNT,
    SOURCE_NAME,
    SOURCE_TYPE,
    GCP_TABLE_NAME,
    JOB_RUN_ID,
    JOB_NAME,
    JOB_TYPE,
    CREATE_DTTIME )
SELECT
  CAST(SOURCE_COUNT AS INT64),
  SOURCE_NAME,
  SOURCE_TYPE,
  GCP_TABLE_NAME,
  CAST(JOB_RUN_ID AS INT64),
  JOB_NAME,
  JOB_TYPE,
  CAST(CREATE_DTTIME AS DATETIME)
FROM
  LANDING.WORK_ERS_AUDIT