SELECT TO_CHAR(SOURCE_COUNT) AS SOURCE_COUNT, 
TO_CHAR(SOURCE_TABLE_NAME) AS SOURCE_NAME, 
'TABLE' AS SOURCE_TYPE,
TO_CHAR(GCP_TABLE_NAME) AS GCP_TABLE_NAME, 
'jobrunid' AS JOB_RUN_ID, 
'jobname' AS JOB_NAME, 
'INBOUND' AS JOB_TYPE, 
TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') AS CREATE_DTTIME
FROM 
(select 
COUNT(*) AS SOURCE_COUNT, 'TOW_DEST_LIST' AS SOURCE_TABLE_NAME, 'ERS_AAA_AUTO_APPROVED_REPAIR' AS GCP_TABLE_NAME
from NCA_CAD.TOW_DEST_LIST 
UNION 
select 
COUNT(*), 'CAD_EMPLOYEE', 'ERS_STAGE_CAD_EMPLOYEE'
from NCA_CAD.CAD_EMPLOYEE 
UNION
select 
COUNT(*), 'CLUB_INFO', 'ERS_STAGE_CAD_CLUB_INFO'
from NCA_CAD.CLUB_INFO 
UNION 
select 
COUNT(*), 'SERVICE_FACILITY', 'ERS_STAGE_SERVICE_FACILITY'
from NCA_ERS_HIST.SERVICE_FACILITY 
UNION
select 
COUNT(*), 'SERVICE_TRUCK', 'ERS_STAGE_SERVICE_TRUCK'
from NCA_CAD.SERVICE_TRUCK 
UNION 
select 
COUNT(*), 'SVC_FAC_DBA', 'ERS_STAGE_SVC_FAC_DBA'
from NCA_APD.SVC_FAC_DBA 
UNION
select 
COUNT(*), 'CAD_SERVICE_FACILITY', 'ERS_STAGE_CAD_SERVICE_FACILITY'
from NCA_CAD.SERVICE_FACILITY 
UNION 
select 
COUNT(*), 'DUP_CALL_LST', 'ERS_STAGE_HIST_DUP_CALL_LST'
from NCA_ERS_HIST.DUP_CALL_LST 
UNION
select 
COUNT(*), 'LOOK_UP', 'ERS_LOOK_UP'
from NCA_CAD.LOOK_UP 
UNION 
select 
COUNT(*), 'LOOK_UP_NAMES', 'ERS_LOOK_UP_NAMES'
from NCA_CAD.LOOK_UP_NAMES 
UNION
select 
COUNT(*), 'SVC_TRK_DRIVER', 'ERS_SVC_TRK_DRIVER'
from NCA_CAD.SVC_TRK_DRIVER 
UNION 
select 
COUNT(*), 'PREDICTIVE_TRUCK_ASSIGNMENT', 'ERS_PREDICTIVE_TRUCK_ASSIGNMENT'
from NCA_ERS_HIST.PREDICTIVE_TRUCK_ASSIGNMENT
UNION 
select 
COUNT(*), 'VEHICLE_DATA', 'ERS_STAGE_CAD_VEHICLE_DATA'
from NCA_CAD.VEHICLE_DATA
UNION
select 
COUNT(*), 'REMB_DETAIL', 'ERS_STAGE_APD_REMB_DETAIL'
FROM NCA_APD.REMB_DETAIL RD,
NCA_APD.REIMBURSEMENT R
WHERE R.COMM_CTR_ID = RD.COMM_CTR_ID
AND R.SC_DT = RD.SC_DT
AND R.SC_ID = RD.SC_ID
UNION
select 
COUNT(*), 'SVC_FAC_ADJ_ITEM', 'ERS_STAGE_APD_SVC_FAC_ADJ_ITEM'
from NCA_APD.SVC_FAC_ADJ_ITEM
UNION 
select 
COUNT(*), 'AAR_REFERRAL', 'ERS_STAGE_HIST_AAR_REFERRAL'
from NCA_ERS_HIST.AAR_REFERRAL
UNION 
select 
COUNT(*), 'ENTITLEMENT_PERIODS', 'ERS_STAGE_INQ_ENTITLEMENT_PERIODS'
from NCA_INQ.ENTITLEMENT_PERIODS
UNION
select 
COUNT(*), 'PAYMENT', 'ERS_STAGE_PAYMENT'
from NCA_APD.PAYMENT 
UNION
select 
COUNT(*), 'REPORTS_DATA', 'ERS_STAGE_REPORTS_DATA'
from NCA_ERS_HIST.REPORTS_DATA
UNION 
select 
COUNT(*), 'STAT_GRP', 'ERS_STAGE_STAT_GRP'
from NCA_APD.STAT_GRP
UNION
select 
COUNT(*), 'REIMBURSEMENT', 'ERS_STAGE_APD_REIMBURSEMENT'
from NCA_APD.REIMBURSEMENT
UNION 
select 
COUNT(*), 'CALL_ADJ', 'ERS_STAGE_HIST_CALL_ADJ'
from NCA_ERS_HIST.CALL_ADJ
UNION 
select 
COUNT(*), 'GRID', 'ERS_STAGE_SPOT_GRID'
from NCA_SPOT.GRID
UNION
select 
COUNT(*), 'ARCH_CALL_EXTD', 'ERS_STAGE_ARCH_CALL_EXTD'
from NCA_ERS_HIST.ARCH_CALL_EXTD
UNION 
select 
COUNT(*), 'ARCH_CALL', 'ERS_STAGE_ARCH_CALL'
from NCA_ERS_HIST.ARCH_CALL 
UNION
select 
COUNT(*), 'SC_STATUS', 'ERS_STAGE_SC_STATUS'
from NCA_ERS_HIST.SC_STATUS
UNION 
select 
COUNT(*), 'MILEAGE_HIST', 'ERS_STAGE_MILEAGE_HIST'
from NCA_ERS_HIST.MILEAGE_HIST
)