MERGE INTO
  CUSTOMER_PRODUCT.CUSTOMER_CONTACT_PREFERENCE_DIM TGT
USING
  (
  SELECT
    TGT_CUSTOMER_ID,
    CUSTOMER_MDM_KEY,
    CUSTOMER_ID,
    MEMBERSHIP_NUM,
    MEMBER_NUM,
    DF_CUSTOMER_ID,
    DO_NOT_PHONE,
    DO_NOT_MAIL,
    DO_NOT_EMAIL,
	OK_TO_SOLICT,
	DMA_PANDER_FLAG,
    'Y' AS ACTIVE_FLG,
    DATE_SUB(CAST(FORMAT_DATETIME('%Y-%m-%d',
          CURRENT_DATETIME()) AS DATE), INTERVAL 1 DAY) AS ROW_START_DT,
    TGT_ROW_START_DT,
    PARSE_DATE('%Y-%m-%d',
      '9999-12-31') AS ROW_END_DT,
    DATE_SUB(CAST(FORMAT_DATETIME('%Y-%m-%d',
          CURRENT_DATETIME()) AS DATE), INTERVAL 2 DAY) AS UPD_ROW_END_DT,
    CURRENT_DATETIME() UPDATE_DTTIME,
    STG.SCD_ROW_TYPE_ID,
    scd_row_type
  FROM (
    SELECT
      TGT.CUSTOMER_ID AS TGT_CUSTOMER_ID,
      TGT.ROW_START_DT AS TGT_ROW_START_DT,
      STG.CUSTOMER_MDM_KEY,
      STG.CUSTOMER_ID,
      STG.MEMBERSHIP_NUM,
      STG.MEMBER_NUM,
      STG.DF_CUSTOMER_ID,
      STG.DO_NOT_PHONE,
      STG.DO_NOT_MAIL,
      STG.DO_NOT_EMAIL,
	  STG.OK_TO_SOLICT,
	  STG.DMA_PANDER_FLAG,
      CASE
        WHEN TGT.CUSTOMER_ID IS NULL THEN 1
        WHEN (STG.DO_NOT_PHONE !=TGT.DO_NOT_PHONE
        OR STG.DO_NOT_MAIL !=TGT.DO_NOT_MAIL
        OR STG.DO_NOT_EMAIL !=TGT.DO_NOT_EMAIL
		OR  STG.OK_TO_SOLICT !=TGT.OK_TO_SOLICT) THEN 2
        ELSE 0
      END AS SCD_ROW_TYPE_ID
    FROM (
      SELECT
        *
      FROM (
        SELECT
          CP.*,
          ROW_NUMBER() OVER(PARTITION BY CP.CUSTOMER_ID) AS ROW_NUM
        FROM
          LANDING.WORK_CONTACT_PREFERENCES CP)
      WHERE
        ROW_NUM=1) STG
    LEFT OUTER JOIN (
      SELECT
        *
      FROM
        CUSTOMER_PRODUCT.CUSTOMER_CONTACT_PREFERENCE_DIM
      WHERE
        ACTIVE_FLG='Y') TGT
    ON
      STG.CUSTOMER_ID =TGT.CUSTOMER_ID ) STG
  INNER JOIN (
    SELECT
      1 AS scd_row_type_id,
      'For Insert' AS scd_row_type
    UNION ALL
    SELECT
      2 AS scd_row_type_id,
      'For Update' AS scd_row_type ) scd_rows
  ON
    (scd_rows.scd_row_type_id<=STG.scd_row_type_id)) SRC
ON
  (TGT.CUSTOMER_ID=SRC.TGT_CUSTOMER_ID
    AND TGT.ROW_START_DT=CASE
      WHEN scd_row_type='For Update' THEN TGT_ROW_START_DT
      ELSE SRC.ROW_START_DT END AND TGT.ACTIVE_FLG='Y')
  WHEN MATCHED  THEN  UPDATE   SET  TGT.ROW_END_DT=SRC.UPD_ROW_END_DT, TGT.ACTIVE_FLG='N'
  WHEN NOT MATCHED
  THEN
INSERT
  (CUSTOMER_MDM_KEY,
    CUSTOMER_ID,
    MEMBER_NUM,
    DF_CUSTOMER_ID,
    MEMBERSHIP_NUM,
    DO_NOT_PHONE,
    DO_NOT_MAIL,
    DO_NOT_EMAIL,
	OK_TO_SOLICT,
	DMA_PANDER_FLAG,
    JOB_RUN_ID,
    ROW_START_DT,
    ROW_END_DT,
    ACTIVE_FLG,
    SOURCE_SYSTEM_CD,
    UPDATE_DTTIME)
VALUES
  ( SRC.CUSTOMER_MDM_KEY , SRC.CUSTOMER_ID , SRC.MEMBER_NUM,null, SRC.MEMBERSHIP_NUM, SRC.DO_NOT_PHONE, SRC.DO_NOT_MAIL, SRC.DO_NOT_EMAIL, SRC.OK_TO_SOLICT,SRC.DMA_PANDER_FLAG,'jobrunid', SRC.ROW_START_DT, SRC.ROW_END_DT, SRC.ACTIVE_FLG, 'CONNECT SUITE', SRC.UPDATE_DTTIME )
