CREATE OR REPLACE TABLE LANDING.CSS_DO_NOT_CONTACT (
MEMBER_NUM STRING,
PHONE_NUM STRING,
CAMPAIGN_ID STRING,
TREATMENT_CD STRING,
STATUS STRING,
ETL_JOB_RUN_ID STRING,
SOURCE_SYSTEM_CD STRING,
CREATE_DT DATE,
CREATE_BY STRING);


CREATE OR REPLACE TABLE LANDING.WORK_CSS_DO_NOT_CONTACT (
PHONE_NUM STRING,
MEMBER_NUM STRING,
CAMPAIGN_ID STRING,
TREATMENT_CD STRING,
STATUS STRING );
