--For the duplicates records in MDM_CUSTOMER_DIM based upon name and address create a work table WORK_MDM_CUSTOMER_DIM_DUPLICATES 
--with one extra blank columns named master flag and duplicate flag

CREATE OR REPLACE TABLE
  LANDING.WORK_MDM_CUSTOMER_DIM_DUPLICATE AS
SELECT
  TBL.*,
  NULL AS IVANS_RECORD,  
  NULL AS MASTER_FLAG,
  NULL AS DUPLICATE_FLAG,
  NULL AS MASTER_MDM_KEY,
  NULL AS DOB_DIFF
FROM (
  WITH
    DUP_TBL AS (
    SELECT
      FIRST_NM,
      LAST_NM,
      PRIMARY_ADDRESS_LINE1,
      PRIMARY_ADDRESS_LINE2,
      PRIMARY_CITY,
      PRIMARY_STATE,
      PRIMARY_ZIP
    FROM
      CUSTOMERS.MDM_CUSTOMER_DIM
    WHERE
      PRIMARY_ADDRESS_LINE1 IS NOT NULL
    GROUP BY
      FIRST_NM,
      LAST_NM,
      PRIMARY_ADDRESS_LINE1,
      PRIMARY_ADDRESS_LINE2,
      PRIMARY_CITY,
      PRIMARY_STATE,
      PRIMARY_ZIP
    HAVING
      COUNT(*)>1)
  SELECT
    CUSTOMER_MDM_KEY,
	FIRST_NM,
	LAST_NM,
	NAME_SUFFIX_CD,
	SALUTATION_CD,
	BIRTH_DATE,
	GENDER_CD,
	PRIMARY_ADDRESS_LINE1,
	PRIMARY_ADDRESS_LINE2,
	PRIMARY_CITY,
	PRIMARY_STATE,
	PRIMARY_ZIP,
	PRIMARY_EMAIL_ADDRESS,
	MEM_RESIDENTIAL_ADDRESS_LINE1,
	MEM_RESIDENTIAL_ADDRESS_LINE2,
	MEM_RESIDENTIAL_CITY,
	MEM_RESIDENTIAL_STATE,
	MEM_RESIDENTIAL_ZIP,
	MEM_BILLING_ADDRESS_LINE1,
	MEM_BILLING_ADDRESS_LINE2,
	MEM_BILLING_CITY,
	MEM_BILLING_STATE,
	MEM_BILLING_ZIP,
	MEM_OTHER_ADDRESS_LINE1,
	MEM_OTHER_ADDRESS_LINE2,
	MEM_OTHER_CITY,
	MEM_OTHER_STATE,
	MEM_OTHER_ZIP,
	MEM_EMAIL_ADDRESS,
	MEM_RESIDENTIAL_PHONE_NUM,
	MEM_WORK_PHONE_NUM,
	MEM_OTHER_PHONE_NUM,
	MEM_CREATE_DATE,
	IVANS_IE_RESIDENTIAL_ADDRESS_LINE1,
	IVANS_IE_RESIDENTIAL_ADDRESS_LINE2,
	IVANS_IE_RESIDENTIAL_CITY,
	IVANS_IE_RESIDENTIAL_STATE,
	IVANS_IE_RESIDENTIAL_ZIP,
	IVANS_IE_BILLING_ADDRESS_LINE1,
	IVANS_IE_BILLING_ADDRESS_LINE2,
	IVANS_IE_BILLING_CITY,
	IVANS_IE_BILLING_STATE,
	IVANS_IE_BILLING_ZIP,
	IVANS_IE_OTHER_ADDRESS_LINE1,
	IVANS_IE_OTHER_ADDRESS_LINE2,
	IVANS_IE_OTHER_CITY,
	IVANS_IE_OTHER_STATE,
	IVANS_IE_OTHER_ZIP,
	IVANS_IE_EMAIL_ADDRESS,
	IVANS_IE_RESIDENTIAL_PHONE_NUM,
	IVANS_IE_WORK_PHONE_NUM,
	IVANS_IE_OTHER_PHONE_NUM,
	IVANS_IE_CREATE_DATE,
	SAM_RESIDENTIAL_ADDRESS_LINE1,
	SAM_RESIDENTIAL_ADDRESS_LINE2,
	SAM_RESIDENTIAL_CITY,
	SAM_RESIDENTIAL_STATE,
	SAM_RESIDENTIAL_ZIP,
	SAM_BILLING_ADDRESS_LINE1,
	SAM_BILLING_ADDRESS_LINE2,
	SAM_BILLING_CITY,
	SAM_BILLING_STATE,
	SAM_BILLING_ZIP,
	SAM_OTHER_ADDRESS_LINE1,
	SAM_OTHER_ADDRESS_LINE2,
	SAM_OTHER_CITY,
	SAM_OTHER_STATE,
	SAM_OTHER_ZIP,
	SAM_EMAIL_ADDRESS,
	SAM_RESIDENTIAL_PHONE_NUM,
	SAM_WORK_PHONE_NUM,
	SAM_OTHER_PHONE_NUM,
	SAM_CREATE_DATE
  FROM
    CUSTOMERS.MDM_CUSTOMER_DIM MCD
  WHERE
    EXISTS(
    SELECT
      1
    FROM
      DUP_TBL
    WHERE
      DUP_TBL.FIRST_NM= MCD.FIRST_NM
      AND DUP_TBL.LAST_NM = MCD.LAST_NM
      AND DUP_TBL.PRIMARY_ADDRESS_LINE1 = MCD.PRIMARY_ADDRESS_LINE1
      AND COALESCE(DUP_TBL.PRIMARY_ADDRESS_LINE2,
        '~') = COALESCE(MCD.PRIMARY_ADDRESS_LINE2,
        '~')
      AND COALESCE(DUP_TBL.PRIMARY_CITY,
        '~') = COALESCE(MCD.PRIMARY_CITY,
        '~')
      AND COALESCE(DUP_TBL.PRIMARY_STATE,
        '~') = COALESCE(MCD.PRIMARY_STATE,
        '~')
      AND COALESCE(DUP_TBL.PRIMARY_ZIP,
        '~') = COALESCE(MCD.PRIMARY_ZIP,
        '~') ) ) TBL
