INSERT INTO OPERATIONAL.EXTERNAL_WNS_CHARGEBACK_PAYMENTS
(ACTIVITY_DT,
MEMBERSHIP_NUM,
MEMBER_NM,
AMOUNT,
RECPT_MERCH_NUM,
SEQUENCE_NUM,
SOURCE_FILE_NM,
SOURCE_FILE_DT,
JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATE_DTTIME
)
SELECT
PARSE_DATE('%m/%d/%Y',TRIM(ACTIVITY_DT)),
TRIM(MEMBERSHIP_NUM),
TRIM(MEMBER_NM),
SAFE_CAST(TRIM(AMOUNT) AS FLOAT64),
TRIM(RECPT_MERCH_NUM),
SAFE_CAST(TRIM(SEQUENCE_NUM) AS INT64),
'v_file_name',
PARSE_DATE("%Y-%m-%d",'v_file_date'),
SAFE_CAST('v_job_run_id' AS INT64),
'v_job_name',
CURRENT_DATETIME()
FROM LANDING.WORK_EXTERNAL_WNS_CHARGEBACK_PAYMENTS