INSERT INTO OPERATIONAL.EXTERNAL_SOURCE_PAYMENT_TRANSACTIONS
(
EXTERNAL_PAYMENT_TRANSACTION_ID,
TRANSACTION_DT,
TRANSACTION_AMT,
TRANSACTION_CD,
MEMBERSHIP_NUM,
MEMBER_NUM,
PAYMENT_CHANNEL,
PAYMENT_TYPE,
CREDIT_CARD_NUM_LAST_4,
CREDIT_CARD_TYPE,
CREDIT_CARD_EXP_DT_STRING,
CHECK_ROUTING_NUM_LAST_4,
CHECKING_ACCOUNT_NUM_LAST_4,
CHECK_NUM,
NOTES,
PAYMENT_RECONCILE_SENT_IND,
PAYMENT_RECONCILE_SENT_DT,
MEMBERSHIP_APPLICATION_SENT_IND,
MEMBERSHIP_APPLICATION_SENT_DT,
SOURCE_FILE_NM,
SOURCE_FILE_DT,
JOB_RUN_ID,
SOURCE_SYSTEM_CD,
CREATED_DTTIME,
UPDATE_DTTIME
)
SELECT
CASE
      WHEN PYMT.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
      ELSE PYMT.MAX_ID+(ROW_NUMBER() OVER ())
    END AS EXTERNAL_PAYMENT_TRANSACTION_ID ,
REC_DT ,
SAFE_CAST( SUBSTR( PRICE,2 ) AS INT64),
'Payment' AS TRANSACTION_CD,
LPAD(SUBSTR( MEMBERSHIP , -8),8,'0') AS MEMBERSHIP_NUM,
MEM.MEMBER_NUM AS MEMBER_NUM,
'OTC' AS PAYMENT_CHANNEL,
SAFE_CAST(NULL AS STRING) AS PAYMENT_TYPE,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_TYPE,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_EXP_DT_STRING,
SAFE_CAST(NULL AS STRING) AS CHECK_ROUTING_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CHECKING_ACCOUNT_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CHECK_NUM,
SAFE_CAST(NULL AS STRING) AS NOTES,
'Y' AS PAYMENT_RECONCILE_SENT_IND,
SAFE_CAST(NULL AS DATE) AS PAYMENT_RECONCILE_SENT_DT,
'Y' AS MEMBERSHIP_APPLICATION_SENT_IND,
SAFE_CAST(NULL AS DATE) AS MEMBERSHIP_APPLICATION_SENT_DT,
SOURCE_FILE_NM AS  SOURCE_FILE_NM,
SOURCE_FILE_DT AS SOURCE_FILE_DT,
6534 AS JOB_RUN_ID,
'GRPMBS' AS SOURCE_SYSTEM_CD,
CURRENT_DATETIME() AS CREATED_DTTIME,
CURRENT_DATETIME() AS UPDATE_DTTIME
FROM
OPERATIONAL.EXTERNAL_GROUPMEMBERSHIP_PAYMENTS EXT,
    (
    SELECT
      MAX( EXTERNAL_PAYMENT_TRANSACTION_ID ) MAX_ID
    FROM
      OPERATIONAL.EXTERNAL_SOURCE_PAYMENT_TRANSACTIONS) PYMT
      LEFT OUTER JOIN 
      OPERATIONAL.CONNECTSUITE_MEMBER MEM
      ON MEM.MEMBERSHIP_NUM=LPAD(SUBSTR(EXT.MEMBERSHIP, -8), 8, '0')
      WHERE DATE(CREATE_DTTIME) =CURRENT_DATE()
UNION ALL
SELECT
CASE
      WHEN PYMT.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
      ELSE PYMT.MAX_ID+(ROW_NUMBER() OVER ())
    END AS EXTERNAL_PAYMENT_TRANSACTION_ID ,
PROC_DT ,
SAFE_CAST(AMOUNT_APPLIED AS INT64),
'Payment' AS TRANSACTION_CD,
LPAD(TRIM(SUBSTR(EXT.MEMBERSHIP_NUM,-8)),8,'0') AS MEMBERSHIP_NUM,
MEM.MEMBER_NUM AS MEMBER_NUM,
'IG' AS PAYMENT_CHANNEL,
SAFE_CAST(NULL AS STRING) AS PAYMENT_TYPE,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_TYPE,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_EXP_DT_STRING,
SAFE_CAST(NULL AS STRING) AS CHECK_ROUTING_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CHECKING_ACCOUNT_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CHECK_NUM,
CONCAT('Batch No:',SAFE_CAST(BATCH_NUM AS STRING)) AS NOTES,
'Y' AS PAYMENT_RECONCILE_SENT_IND,
SAFE_CAST(NULL AS DATE) AS PAYMENT_RECONCILE_SENT_DT,
'Y' AS MEMBERSHIP_APPLICATION_SENT_IND,
SAFE_CAST(NULL AS DATE) AS MEMBERSHIP_APPLICATION_SENT_DT,
SOURCE_FILE_NM AS  SOURCE_FILE_NM,
SOURCE_FILE_DT AS SOURCE_FILE_DT,
6534 AS JOB_RUN_ID,
'SPLTINSMBS' AS SOURCE_SYSTEM_CD,
CURRENT_DATETIME() AS CREATED_DTTIME,
CURRENT_DATETIME() AS UPDATE_DTTIME
FROM
OPERATIONAL.EXTERNAL_INS_TO_MBR_SPLITS_PAYMENTS EXT,
    (
    SELECT
      MAX( EXTERNAL_PAYMENT_TRANSACTION_ID ) MAX_ID
    FROM
      OPERATIONAL.EXTERNAL_SOURCE_PAYMENT_TRANSACTIONS) PYMT
            LEFT OUTER JOIN 
      OPERATIONAL.CONNECTSUITE_MEMBER MEM
      ON MEM.MEMBERSHIP_NUM=LPAD(SUBSTR(EXT.MEMBERSHIP_NUM, -8), 8, '0')
      WHERE DATE(CREATE_DTTIME) =CURRENT_DATE()
UNION ALL
SELECT
CASE
      WHEN PYMT.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
      ELSE PYMT.MAX_ID+(ROW_NUMBER() OVER ())
    END AS EXTERNAL_PAYMENT_TRANSACTION_ID ,
RECORD_DT ,
SAFE_CAST(AMOUNT AS INT64),
'Payment' AS TRANSACTION_CD,
LPAD(TRIM(SUBSTR( FR_POLICY , -8)),8,'0') AS MEMBERSHIP_NUM,
MEM.MEMBER_NUM AS MEMBER_NUM,
'IG' AS PAYMENT_CHANNEL,
PYMT_TYPE AS PAYMENT_TYPE,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_TYPE,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_EXP_DT_STRING,
SAFE_CAST(NULL AS STRING) AS CHECK_ROUTING_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CHECKING_ACCOUNT_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CHECK_NUM,
NOTES AS NOTES,
'Y' AS PAYMENT_RECONCILE_SENT_IND,
SAFE_CAST(NULL AS DATE) AS PAYMENT_RECONCILE_SENT_DT,
'Y' AS MEMBERSHIP_APPLICATION_SENT_IND,
SAFE_CAST(NULL AS DATE) AS MEMBERSHIP_APPLICATION_SENT_DT,
SOURCE_FILE_NM AS  SOURCE_FILE_NM,
SOURCE_FILE_DT AS SOURCE_FILE_DT,
6534 AS JOB_RUN_ID,
'TRNFINSMBS' AS SOURCE_SYSTEM_CD,
CURRENT_DATETIME() AS CREATED_DTTIME,
CURRENT_DATETIME() AS UPDATE_DTTIME
FROM
OPERATIONAL.EXTERNAL_INS_TO_MBR_PYMTRFRQST EXT,
    (
    SELECT
      MAX( EXTERNAL_PAYMENT_TRANSACTION_ID ) MAX_ID
    FROM
      OPERATIONAL.EXTERNAL_SOURCE_PAYMENT_TRANSACTIONS) PYMT
      LEFT OUTER JOIN 
      OPERATIONAL.CONNECTSUITE_MEMBER MEM
      ON MEM.MEMBERSHIP_NUM=LPAD(SUBSTR(EXT.FR_POLICY, -8), 8, '0')
      WHERE DATE(CREATE_DTTIME)=CURRENT_DATE()
UNION ALL
SELECT
CASE
      WHEN PYMT.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
      ELSE PYMT.MAX_ID+(ROW_NUMBER() OVER ())
    END AS EXTERNAL_PAYMENT_TRANSACTION_ID ,
BALANCING_DT ,
SAFE_CAST( APPLIED_AMT AS INT64),
'Payment' AS TRANSACTION_CD,
LPAD(SUBSTR(ACCOUNT_NUM, -8), 8, '0') AS MEMBERSHIP_NUM,
MEM.MEMBER_NUM AS MEMBER_NUM,
'LB' AS PAYMENT_CHANNEL,
SAFE_CAST(NULL AS STRING) AS PAYMENT_TYPE,
CC_LAST_4 AS CREDIT_CARD_NUM_LAST_4,
CC_TYPE AS CREDIT_CARD_TYPE,
CHECK_RT AS CREDIT_CARD_EXP_DT_STRING,
SAFE_CAST(NULL AS STRING) AS CHECK_ROUTING_NUM_LAST_4,
SUBSTR(CHECKING_ACCOUNT,-4) AS CHECKING_ACCOUNT_NUM_LAST_4,
CHECK_NUM AS CHECK_NUM,
SAFE_CAST(NULL AS STRING) AS NOTES,
'Y' AS PAYMENT_RECONCILE_SENT_IND,
SAFE_CAST(NULL AS DATE) AS PAYMENT_RECONCILE_SENT_DT,
'Y' AS MEMBERSHIP_APPLICATION_SENT_IND,
SAFE_CAST(NULL AS DATE) AS MEMBERSHIP_APPLICATION_SENT_DT,
SOURCE_FILE_NM AS  SOURCE_FILE_NM,
SOURCE_FILE_DT AS SOURCE_FILE_DT,
6534 AS JOB_RUN_ID,
'LOCKBOX' AS SOURCE_SYSTEM_CD,
CURRENT_DATETIME() AS CREATED_DTTIME,
CURRENT_DATETIME() AS UPDATE_DTTIME
FROM
OPERATIONAL.EXTERNAL_LOCKBOX_PAYMENT_DETAILS EXT,
    (
    SELECT
      MAX( EXTERNAL_PAYMENT_TRANSACTION_ID ) MAX_ID
    FROM
      OPERATIONAL.EXTERNAL_SOURCE_PAYMENT_TRANSACTIONS) PYMT
      LEFT OUTER JOIN 
      OPERATIONAL.CONNECTSUITE_MEMBER MEM
      ON MEM.MEMBERSHIP_NUM=LPAD(SUBSTR(EXT.ACCOUNT_NUM, -8), 8, '0')
      WHERE DATE(CREATE_DTTIME)=CURRENT_DATE()
UNION ALL
SELECT
CASE
      WHEN PYMT.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
      ELSE PYMT.MAX_ID+(ROW_NUMBER() OVER ())
    END AS EXTERNAL_PAYMENT_TRANSACTION_ID ,
RECORD_DT ,
SAFE_CAST(AMOUNT AS INT64),
'Payment' AS TRANSACTION_CD,
LPAD(TRIM(SUBSTR(TO_POLICY,-8)),8,'0') AS MEMBERSHIP_NUM,
MEM.MEMBER_NUM AS MEMBER_NUM,
'IG' AS PAYMENT_CHANNEL,
PYMT_TYPE AS PAYMENT_TYPE,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_TYPE,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_EXP_DT_STRING,
SAFE_CAST(NULL AS STRING) AS CHECK_ROUTING_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CHECKING_ACCOUNT_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CHECK_NUM,
NOTES AS NOTES,
'Y' AS PAYMENT_RECONCILE_SENT_IND,
SAFE_CAST(NULL AS DATE) AS PAYMENT_RECONCILE_SENT_DT,
'Y' AS MEMBERSHIP_APPLICATION_SENT_IND,
SAFE_CAST(NULL AS DATE) AS MEMBERSHIP_APPLICATION_SENT_DT,
SOURCE_FILE_NM AS  SOURCE_FILE_NM,
SOURCE_FILE_DT AS SOURCE_FILE_DT,
6534 AS JOB_RUN_ID,
'TRNFMBSINS' AS SOURCE_SYSTEM_CD,
CURRENT_DATETIME() AS CREATED_DTTIME,
CURRENT_DATETIME() AS UPDATE_DTTIME
FROM
OPERATIONAL.EXTERNAL_MBR_TO_INS_PYMTRFRQST EXT,
    (
    SELECT
      MAX( EXTERNAL_PAYMENT_TRANSACTION_ID ) MAX_ID
    FROM
      OPERATIONAL.EXTERNAL_SOURCE_PAYMENT_TRANSACTIONS) PYMT
            LEFT OUTER JOIN 
      OPERATIONAL.CONNECTSUITE_MEMBER MEM
      ON MEM.MEMBERSHIP_NUM=LPAD(SUBSTR(EXT.TO_POLICY, -8), 8, '0')
      WHERE DATE(CREATE_DTTIME)=CURRENT_DATE()
UNION ALL
SELECT
CASE
      WHEN PYMT.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
      ELSE PYMT.MAX_ID+(ROW_NUMBER() OVER ())
    END AS EXTERNAL_PAYMENT_TRANSACTION_ID ,
RECEIVED_DT ,
SAFE_CAST(SUBSTR(AMOUNT,2) AS INT64),
'NSF' AS TRANSACTION_CD,
EXT.MEMBERSHIP_NUM AS MEMBERSHIP_NUM,
MEM.MEMBER_NUM AS MEMBER_NUM,
'IG' AS PAYMENT_CHANNEL,
SAFE_CAST(NULL AS STRING) AS PAYMENT_TYPE,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_TYPE,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_EXP_DT_STRING,
SAFE_CAST(NULL AS STRING) AS CHECK_ROUTING_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CHECKING_ACCOUNT_NUM_LAST_4, 
SAFE_CAST(NULL AS STRING) AS CHECK_NUM,
TYPE_OF_ACTIVITY AS NOTES,
'Y' AS PAYMENT_RECONCILE_SENT_IND,
SAFE_CAST(NULL AS DATE) AS PAYMENT_RECONCILE_SENT_DT,
'Y' AS MEMBERSHIP_APPLICATION_SENT_IND,
SAFE_CAST(NULL AS DATE) AS MEMBERSHIP_APPLICATION_SENT_DT,
SOURCE_FILE_NM AS  SOURCE_FILE_NM,
SOURCE_FILE_DT AS SOURCE_FILE_DT,
6534 AS JOB_RUN_ID,
'NSF_222' AS SOURCE_SYSTEM_CD,
CURRENT_DATETIME() AS CREATED_DTTIME,
CURRENT_DATETIME() AS UPDATE_DTTIME
FROM
OPERATIONAL.EXTERNAL_NSF222_PAYMENTS EXT,
    (
    SELECT
      MAX( EXTERNAL_PAYMENT_TRANSACTION_ID ) MAX_ID
    FROM
      OPERATIONAL.EXTERNAL_SOURCE_PAYMENT_TRANSACTIONS) PYMT
            LEFT OUTER JOIN 
      OPERATIONAL.CONNECTSUITE_MEMBER MEM
      ON MEM.MEMBERSHIP_NUM=EXT.MEMBERSHIP_NUM
      WHERE DATE(CREATE_DTTIME)=CURRENT_DATE()
UNION ALL
SELECT
CASE
      WHEN PYMT.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
      ELSE PYMT.MAX_ID+(ROW_NUMBER() OVER ())
    END AS EXTERNAL_PAYMENT_TRANSACTION_ID ,
PAYMENT_DT,
SAFE_CAST(PAYMENT_AMT AS INT64),
'Payment' AS TRANSACTION_CD,
SUBSTR(CUSTOMER_ACCOUNT_NUM, 7, 8) AS MEMBERSHIP_NUM,
CUSTOMER_ACCOUNT_NUM AS MEMBER_NUM,
'HB' AS PAYMENT_CHANNEL,
SAFE_CAST(NULL AS STRING) AS PAYMENT_TYPE,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_TYPE,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_EXP_DT_STRING,
TRACE_NUM AS CHECK_ROUTING_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CHECKING_ACCOUNT_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CHECK_NUM,
CONCAT('Trace #:',TRACE_NUM) AS NOTES,
'Y' AS PAYMENT_RECONCILE_SENT_IND,
SAFE_CAST(NULL AS DATE) AS PAYMENT_RECONCILE_SENT_DT,
'Y' AS MEMBERSHIP_APPLICATION_SENT_IND,
SAFE_CAST(NULL AS DATE) AS MEMBERSHIP_APPLICATION_SENT_DT,
SOURCE_FILE_NM AS  SOURCE_FILE_NM,
SOURCE_FILE_DT AS SOURCE_FILE_DT,
6534 AS JOB_RUN_ID,
'PAYMODE' AS SOURCE_SYSTEM_CD,
CURRENT_DATETIME() AS CREATED_DTTIME,
CURRENT_DATETIME() AS UPDATE_DTTIME
FROM
OPERATIONAL.EXTERNAL_PAYMODE_DETAIL_PAYMENTS,
    (
    SELECT
      MAX( EXTERNAL_PAYMENT_TRANSACTION_ID ) MAX_ID
    FROM
      OPERATIONAL.EXTERNAL_SOURCE_PAYMENT_TRANSACTIONS) PYMT
      WHERE DATE(CREATE_DTTIME)=CURRENT_DATE()
UNION ALL 
SELECT
CASE
      WHEN PYMT.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
      ELSE PYMT.MAX_ID+(ROW_NUMBER() OVER ())
    END AS EXTERNAL_PAYMENT_TRANSACTION_ID ,
TRANSACTION_DT ,
SAFE_CAST(PAYMENT_AMT AS INT64),
'Check_Refund' AS TRANSACTION_CD,
LPAD(TRIM(SUBSTR(PAYMENT_MEMO,-8)),8,'0') AS MEMBERSHIP_NUM,
MEM.MEMBER_NUM AS MEMBER_NUM,
'OTC' AS PAYMENT_CHANNEL,
SAFE_CAST(NULL AS STRING) AS PAYMENT_TYPE,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_TYPE,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_EXP_DT_STRING,
SAFE_CAST(NULL AS STRING) AS CHECK_ROUTING_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CHECKING_ACCOUNT_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CHECK_NUM,
CONCAT('Sett Run: ',SETTLEMENT_RUN,'| Ref: ',REFERENCE) AS NOTES,
'Y' AS PAYMENT_RECONCILE_SENT_IND,
SAFE_CAST(NULL AS DATE) AS PAYMENT_RECONCILE_SENT_DT,
'Y' AS MEMBERSHIP_APPLICATION_SENT_IND,
SAFE_CAST(NULL AS DATE) AS MEMBERSHIP_APPLICATION_SENT_DT,
SOURCE_FILE_NM AS  SOURCE_FILE_NM,
SOURCE_FILE_DT AS SOURCE_FILE_DT,
6534 AS JOB_RUN_ID,
'WDCHKRFND' AS SOURCE_SYSTEM_CD,
CURRENT_DATETIME() AS CREATED_DTTIME,
CURRENT_DATETIME() AS UPDATE_DTTIME
FROM
OPERATIONAL.EXTERNAL_WD_CHECK_REFUND_PAYMENTS EXT,
    (
    SELECT
      MAX( EXTERNAL_PAYMENT_TRANSACTION_ID ) MAX_ID
    FROM
      OPERATIONAL.EXTERNAL_SOURCE_PAYMENT_TRANSACTIONS) PYMT
            LEFT OUTER JOIN 
      OPERATIONAL.CONNECTSUITE_MEMBER MEM
      ON MEM.MEMBERSHIP_NUM=LPAD(TRIM(SUBSTR(PAYMENT_MEMO,-8)),8,'0')
      WHERE DATE(CREATE_DTTIME)=CURRENT_DATE()
UNION ALL
SELECT
CASE
      WHEN PYMT.MAX_ID IS NULL THEN 0+(ROW_NUMBER() OVER ())
      ELSE PYMT.MAX_ID+(ROW_NUMBER() OVER ())
    END AS EXTERNAL_PAYMENT_TRANSACTION_ID ,
ACTIVITY_DT ,
SAFE_CAST(AMOUNT AS INT64),
'Chargeback' AS TRANSACTION_CD,
EXT.MEMBERSHIP_NUM AS MEMBERSHIP_NUM,
MEM.MEMBER_NUM AS MEMBER_NUM,
'OTC' AS PAYMENT_CHANNEL,
SAFE_CAST(NULL AS STRING) AS PAYMENT_TYPE,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_TYPE,
SAFE_CAST(NULL AS STRING) AS CREDIT_CARD_EXP_DT_STRING,
SAFE_CAST(NULL AS STRING) AS CHECK_ROUTING_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CHECKING_ACCOUNT_NUM_LAST_4,
SAFE_CAST(NULL AS STRING) AS CHECK_NUM,
CONCAT('Rcpt or Mercht Order #: ',RECPT_MERCH_NUM,'| Seq #: ', SAFE_CAST(SEQUENCE_NUM AS STRING)) AS NOTES,
'Y' AS PAYMENT_RECONCILE_SENT_IND,
SAFE_CAST(NULL AS DATE) AS PAYMENT_RECONCILE_SENT_DT,
'Y' AS MEMBERSHIP_APPLICATION_SENT_IND,
SAFE_CAST(NULL AS DATE) AS MEMBERSHIP_APPLICATION_SENT_DT,
SOURCE_FILE_NM AS  SOURCE_FILE_NM,
SOURCE_FILE_DT AS SOURCE_FILE_DT,
6534 AS JOB_RUN_ID,
'CHRGBCK' AS SOURCE_SYSTEM_CD,
CURRENT_DATETIME() AS CREATED_DTTIME,
CURRENT_DATETIME() AS UPDATE_DTTIME
FROM
OPERATIONAL.EXTERNAL_WNS_CHARGEBACK_PAYMENTS EXT,
    (
    SELECT
      MAX( EXTERNAL_PAYMENT_TRANSACTION_ID ) MAX_ID
    FROM
      OPERATIONAL.EXTERNAL_SOURCE_PAYMENT_TRANSACTIONS) PYMT
            LEFT OUTER JOIN 
      OPERATIONAL.CONNECTSUITE_MEMBER MEM
      ON MEM.MEMBERSHIP_NUM=EXT.MEMBERSHIP_NUM
      WHERE DATE(CREATE_DTTIME)=CURRENT_DATE()

